- src/vcs/git.ts
Looks like a bug in fs or fs-extra.
Fails silently: `await Bluebird.map(["a"], el => el).map(stat)`
Works: `await Bluebird.map(["a"], el => el).map(el => stat(el))`
Where the `stat` above is imported from `fs-extra`.
> fix(vsc): handle weird stat behavior by wrapping it

- src/plugins/kubernetes/api.ts
One was malformed Error objects, which made error outputs less than
useful. The other was that all patch methods were broken due to
the wrong header being sent.
> Fix k8s api issues

- docs/introduction/getting-started.md
Fixed examples directory code sample
> docs: Fix path of examples checkout

- docs/README.md
- docs/introduction/README.md
- docs/introduction/the-faqs.md
> docs: add FAQs section and tmux/colors info

- src/vcs/base.ts
- test/src/vcs/base.ts
> fix(versioning): `resolveVersion` should not call `getTreeVersion`

- garden-cli/src/plugins/generic.ts
This had been addressed in a previous branch but I overwrote the
change when rebasing. Basically the generic build status handler
was assuming modules were built if they didn't specify a build command,
which doesn't apply to helm modules (and potentially others).
> fix(k8s): build status was incorrectly reported for helm modules

- garden-cli/src/plugins/kubernetes/helm.ts
- garden-cli/src/plugins/kubernetes/local.ts
> fix(k8s): wait for Tiller pod to be ready when initializing

- garden-cli/src/plugins/kubernetes/local.ts
cc @ellenkorbes - can you give this a spin?
> fix(k8s): don't deploy system services when running minikube

- docs/reference/config.md
- examples/local-tls/services/node-service/garden.yml
- garden-cli/src/plugins/container.ts
- garden-cli/src/plugins/openfaas.ts
- garden-cli/src/types/service.ts
- garden-cli/test/src/commands/call.ts
- garden-cli/test/src/commands/deploy.ts
- garden-cli/test/src/plugins/container.ts
- garden-cli/test/src/plugins/kubernetes/ingress.ts
Endpoint names will have to be removed from module configs.
> fix(config): remove name field from service endpoint spec

- garden-cli/support/install.ps1
> fix: windows install script

- garden-cli/src/logger/renderers.ts
- garden-cli/test/src/logger.ts
> fix(logger): appended error messages now rendered properly

- docs/reference/commands.md
- garden-cli/src/cli/cli.ts
- garden-cli/src/cli/helpers.ts
- garden-cli/src/logger/log-entry.ts
- garden-cli/src/logger/logger.ts
- garden-cli/src/logger/renderers.ts
- garden-cli/src/logger/writers/file-writer.ts
Closes #279.
Also added a global flag to the CLI to disable emoji in general.
> fix(logger): only print emoji if env supports it

- .chglog/CHANGELOG.tpl.md
- .chglog/config.yml
- CHANGELOG.md
- bin/bootstrap-osx
- bin/publish
- package.json
> chore(changelog): use git-chglog for changelog gen and fix CHANGELOG.md

- examples/remote-sources/README.md
- examples/remote-sources/garden.yml
- examples/remote-sources/services/jworker/garden.yml
- garden-service/src/vcs/git.ts
> docs(examples): use version tags in remote-sources repo urls

- docs/reference/config.md
- garden-service/src/plugins/container.ts
- garden-service/src/plugins/kubernetes/deployment.ts
- garden-service/test/data/test-project-container/module-a/docker-dir/Dockerfile
- garden-service/test/src/plugins/container.ts
> feat: allow custom dockerfile path for container modules

- garden-service/package-lock.json
- garden-service/package.json
- garden-service/src/commands/exec.ts
- garden-service/src/commands/run/module.ts
- garden-service/src/commands/run/service.ts
- garden-service/src/plugins/google/common.ts
- garden-service/src/plugins/google/gcloud.ts
- garden-service/src/plugins/kubernetes/actions.ts
- garden-service/src/plugins/kubernetes/kubectl.ts
- garden-service/src/types/plugin/params.ts
- garden-service/src/util/util.ts
- garden-service/test/helpers.ts
- garden-service/test/src/actions.ts
This further cuts down our native module dependencies
> refactor: remove node-pty dependency

- .circleci/config.yml
Remove unused dependencies and commented out code.
> chore(ci): Clean up circleci configs

- garden-service/src/vcs/git.ts
> fix(git): error when running before first commit is made in repo (#324)

- garden-service/.dockerignore
- garden-service/src/plugins/kubernetes/status.ts
> feat(k8s): print error logs when container fails to start

- garden-service/src/cli/helpers.ts
> fix(cli): change magenta to cyan in cli help text (#281)

- garden-service/src/build-dir.ts
Fixes #366
Only an issue when module and project are in the same directory
> fix: recursive bug copying .garden into .garden

- examples/gatsby-hot-reload/.dockerignore
- examples/gatsby-hot-reload/.gitignore
- examples/gatsby-hot-reload/.prettierrc
- examples/gatsby-hot-reload/Dockerfile
- examples/gatsby-hot-reload/LICENSE
- examples/gatsby-hot-reload/README.md
- examples/gatsby-hot-reload/garden.yml
- examples/gatsby-hot-reload/gatsby-config.js
- examples/gatsby-hot-reload/package-lock.json
- examples/gatsby-hot-reload/package.json
- examples/gatsby-hot-reload/src/components/layout.css
- examples/gatsby-hot-reload/src/components/layout.js
- examples/gatsby-hot-reload/src/pages/404.js
- examples/gatsby-hot-reload/src/pages/index.js
This example project showcases Gatsby running inside a container, with
support for hot reloading.
> chore(examples): added Gatsby hot reload example

- garden-service/src/commands/create/config-templates.ts
- garden-service/src/commands/create/project.ts
- garden-service/src/commands/deploy.ts
- garden-service/src/commands/run/module.ts
- garden-service/src/commands/run/test.ts
- garden-service/src/commands/test.ts
- garden-service/src/config-store.ts
- garden-service/test/src/commands/create/project.ts
- garden-service/test/src/commands/deploy.ts
- garden-service/test/src/commands/run/module.ts
- garden-service/test/src/commands/test.ts
- garden-service/test/src/garden.ts
- package.json
- tslint.json
See https://palantir.github.io/tslint/rules/object-literal-key-quotes/
Also see https://github.com/garden-io/garden/pull/378#discussion_r235069973
> refactor(formatting): improve quoting style of objects

- garden-service/src/plugins/kubernetes/deployment.ts
> fix(k8s): remove replicasets and daemonsets when deleting services

- garden-service/src/plugins/kubernetes/actions.ts
- garden-service/src/plugins/kubernetes/kubernetes.ts
- garden-service/src/plugins/kubernetes/logs.ts
- garden-service/src/plugins/openfaas/openfaas.ts
- garden-service/src/tasks/deploy.ts
- garden-service/src/types/plugin/outputs.ts
- garden-service/src/util/ext-tools.ts
Closes #411 
Also adds support for log tailing for OpenFaaS functions.
> Fix log tailing issues

- garden-service/src/tasks/build.ts
- garden-service/src/tasks/deploy.ts
> fix: minor logging issue

- garden-service/src/plugins/kubernetes/actions.ts
- garden-service/src/plugins/kubernetes/kubectl.ts
- garden-service/src/types/plugin/outputs.ts
> fix(k8s): exec and run commands didn't work properly in interactive mode

- docs/reference/config.md
- garden-service/package-lock.json
- garden-service/src/plugins/exec.ts
- garden-service/test/data/test-project-exec/module-a/garden.yml
- garden-service/test/src/plugins/exec.ts
A simple omission, seems @thsig had implemented the actual task action for the plugin.
> fix(exec): missing tasks key in module schema

- dashboard/src/app.tsx
- dashboard/src/components/checkbox.tsx
- dashboard/src/components/graph/graph.scss
- dashboard/src/components/graph/index.tsx
- dashboard/src/components/sidebar.tsx
- dashboard/src/components/spinner.tsx
- dashboard/src/styles/variables.ts
* add task type filter
* animate tasks that are in process
* improve text rendering inside task graph node
* replace spinner
> Update dashboard UI

- garden-service/package-lock.json
- garden-service/package.json
- garden-service/src/plugins/kubernetes/logs.ts
> fix(k8s): fix issue with log following for K8s

- dashboard/package-lock.json
- dashboard/package.json
- dashboard/src/app.tsx
- dashboard/src/components/card.tsx
- dashboard/src/components/checkbox.tsx
- dashboard/src/components/global-style.tsx
- dashboard/src/components/graph/index.tsx
- dashboard/src/components/logs.tsx
- dashboard/src/components/sidebar.tsx
- dashboard/src/components/spinner.tsx
- dashboard/src/components/table.tsx
- dashboard/src/components/terminal.tsx
- dashboard/src/styles/variables.ts
* Custom checkboxes
* Use react-select for dropdown
* Style refresh button on Logs page
> feat(dashboard): ui improvments

- examples/gatsby-hot-reload/garden.yml
- examples/hot-reload/node-service/garden.yml
- examples/simple-project/services/node-service/garden.yml
- examples/vote-helm/vote/garden.yml
- examples/vote/services/vote/garden.yml
Cleaned up the usage of command / hotReloadCommand / hotReloadArgs in
example projects.
> fix: clean up field usage in example projects

- .circleci/config.yml
- garden-service/src/vcs/base.ts
- garden-service/src/vcs/git.ts
- garden-service/test/helpers.ts
- garden-service/test/src/commands/update-remote.ts
- garden-service/test/src/garden.ts
- garden-service/test/src/vcs/base.ts
- garden-service/test/src/vcs/git.ts
> fix(vcs): untracked files didn't update version timestamp correctly

- garden-service/src/tasks/deploy.ts
> feat(cli): print ingress endpoints after deploying

- garden-service/src/plugins/kubernetes/status.ts
This fixes an occasional issue where deploying services with hot reloading enabled would fail.
> fix: include container name in pod log requests

- garden-service/src/tasks/test.ts
> fix(cli): log test duration in CLI output

- docs/reference/module-types/container.md
- docs/reference/module-types/maven-container.md
- garden-service/src/plugins/container/config.ts
- garden-service/src/plugins/kubernetes/container/run.ts
- garden-service/test/src/plugins/container.ts
> feat(container): add env field to task spec

- docs/reference/module-types/maven-container.md
- garden-service/src/plugins/kubernetes/helm/helm-cli.ts
- garden-service/src/plugins/maven-container/maven-container.ts
- garden-service/src/plugins/maven-container/maven.ts
- garden-service/src/plugins/maven-container/openjdk.ts
- garden-service/src/util/ext-tools.ts
Along the way, improved the external tool helper to support libraries
as well as executable binaries.
> feat(maven-container): automatically fetch Maven and OpenJDK

- garden-service/src/build-dir.ts
This fixes a regression from 9630192, where OpenFaas modules would sometimes fail. This was because the sync of the built templates into the build context directory of the module would result in files/folders being deleted from there.
> fix(build): don't delete when syncing dependencies

- README.md
- docs/basics/README.md
- docs/basics/installation.md
- docs/basics/quick-start.md
- docs/basics/stack-graph.md
- docs/reference/glossary.md
- docs/using-garden/README.md
- docs/using-garden/configuration-files.md
- docs/using-garden/features-and-usage.md
- docs/using-garden/hot-reload.md
- docs/using-garden/remote-clusters.md
- garden-service/package-lock.json
Next up is renaming example projects as needed, and setting up a new `hello-world` project.
In that PR, I'll change links/references to example projects appropriately, so don't worry about that here.
> docs: fixes and updates

- garden-service/src/plugins/kubernetes/status.ts
> fix(k8s): report correct deployment status when replicas=0

- garden-service/src/config/config-context.ts
- garden-service/src/garden.ts
- garden-service/src/template-string.ts
- garden-service/test/unit/data/test-projects/module-self-ref/garden.yml
- garden-service/test/unit/data/test-projects/module-self-ref/module-a/garden.yml
- garden-service/test/unit/src/garden.ts
- garden-service/test/unit/src/vcs/base.ts
> fix(config): catch module self-references instead of crashing

- docs/reference/template-strings.md
- docs/using-garden/configuration-files.md
- examples/kubernetes-module/postgres/garden.yml
- garden-service/src/config/config-context.ts
- garden-service/src/docs/templates/template-strings.hbs
- garden-service/static/openfaas/system/openfaas-system/garden.yml
- garden-service/test/unit/data/test-project-templated/module-a/garden.yml
- garden-service/test/unit/data/test-project-templated/module-b/garden.yml
- garden-service/test/unit/data/test-project-variable-versioning/module-a/garden.yml
- garden-service/test/unit/src/config/config-context.ts
> feat(config): add var alias for variables template key

- garden-service/src/plugins/kubernetes/namespace.ts
Before this fix, environment initialization for the OpenFAAS plugin would fail because a second call to `ensureNamespace` was made before the first call (with the same namespace name) was able to register that the namespace had been created. This created a race condition.
This was fixed by maintaining a "pending" status to deduplicate such requests.
> fix(k8s): deduplicate ns creation during init

- garden-service/src/plugins/kubernetes/container/handlers.ts
> fix(k8s): use correct container handler when building modules

- garden-service/src/plugins/kubernetes/namespace.ts
> fix(k8s): fix type error when Kubernetes is not running

- dashboard/src/components/info-card.tsx
- dashboard/src/components/module.tsx
- dashboard/src/containers/overview.tsx
> improvement(dashboard): add dependencies to each entity card

- garden-service/src/vcs/git.ts
- garden-service/test/unit/src/vcs/git.ts
> fix(vcs): error when handling files with spaces in the name

- docs/using-garden/remote-clusters.md
#811 needs to be merged first to avoid link check failing.
> Remote ingress update docs

- dashboard/src/components/entity-card.tsx
- dashboard/src/components/entity-result.tsx
- dashboard/src/components/ingresses.tsx
- dashboard/src/components/module.tsx
- dashboard/src/containers/overview.tsx
- garden-service/src/garden.ts
- garden-service/test/unit/src/commands/get/get-config.ts
> style(dashboard): overall improvements

- garden-service/src/commands/dev.ts
Came up after a merge conflict.
> fix(dev-command): prepareEnvironment was called twice

- docs/reference/commands.md
- garden-service/src/cli/cli.ts
- garden-service/src/commands/options.ts
This was causing our pre-commit integ tests to fail.
> fix(cli): ensure cli exits with code 0 when help/version called

- .circleci/config.yml
- examples/demo-project/garden.yml
- examples/hot-reload/garden.yml
- examples/remote-sources/garden.yml
- examples/tasks/garden.yml
- examples/vote-helm/garden.yml
- examples/vote/garden.yml
- garden-service/package.json
- garden-service/test/integ-helpers.ts
- garden-service/test/integ/README.md
- garden-service/test/integ/garden.yml
- garden-service/test/integ/integ-full.ts
- garden-service/test/integ/src/pre-release.ts
- garden-service/test/mocha.integ.opts
- garden-service/test/run-garden.ts
Run integration tests with Garden as part of our CI pipeline.
> ci: run integ tests with Garden in CI

- garden-service/bin/build-pkg.sh
This is already in the packaged v0.10.0-0 release
> chore(build): fix macos distribution

- garden-service/src/plugins/kubernetes/status.ts
> Fix K8s status issues

- garden-service/package-lock.json
- garden-service/package.json
- garden-service/src/plugins/kubernetes/api.ts
- garden-service/src/plugins/kubernetes/container/build.ts
- garden-service/src/plugins/kubernetes/container/ingress.ts
- garden-service/src/plugins/kubernetes/container/run.ts
- garden-service/src/plugins/kubernetes/helm/tiller.ts
- garden-service/src/plugins/kubernetes/hot-reload.ts
- garden-service/src/plugins/kubernetes/namespace.ts
- garden-service/src/plugins/kubernetes/secrets.ts
- garden-service/src/plugins/kubernetes/status.ts
- garden-service/src/plugins/kubernetes/system.ts
- garden-service/src/plugins/kubernetes/task-results.ts
- garden-service/src/plugins/kubernetes/test.ts
- garden-service/src/plugins/kubernetes/types.ts
- garden-service/src/plugins/kubernetes/util.ts
- garden-service/src/plugins/openfaas/openfaas.ts
- garden-service/test/unit/src/plugins/kubernetes/container/ingress.ts
This should overall make the API methods more nice and easy to use, and
imports some good fixes that we can use.
> refactor(k8s): update kubernetes API library to 0.10.1 and refactor wrapper

- docs/examples/demo-project.md
- docs/using-garden/configuration-files.md
- docs/using-garden/remote-clusters.md
We should re-add this into CI btw, ideally as an independent step
> docs: fix some broken links

- docs/basics/installation.md
- support/install.ps1
Allows installation on machines without Hyper-V option, and avoids hard
requirement on Docker.
> improvement(Windows): check for Hyper-V and ask if user wants Docker

- garden-service/src/cli/helpers.ts
- garden-service/src/logger/util.ts
Added a yellow warning message instead of the pink one.
> fix: update messaging when checking version

- docs/reference/commands.md
- garden-service/src/commands/config/config.ts
- garden-service/src/commands/link/link.ts
- garden-service/src/commands/options.ts
- garden-service/src/commands/run/run.ts
- garden-service/src/commands/unlink/unlink.ts
- garden-service/src/commands/update-remote/update-remote.ts
> style: consistent punctuation in command descriptions

- garden-service/src/plugins/kubernetes/helm/common.ts
- garden-service/src/plugins/kubernetes/util.ts
- garden-service/test/unit/src/plugins/kubernetes/util.ts
> fix(k8s): always flatten resources of kind List

- garden-service/src/plugins/kubernetes/container/build.ts
- garden-service/test/integ-helpers.ts
- garden-service/test/integ/README.md
- garden-service/test/integ/garden.yml
- garden-service/test/integ/integ-full.ts
- garden-service/test/integ/src/pre-release.ts
- garden-service/test/run-garden.ts
This is WIP because it exposes some issues, so tests won't pass until those are fixed.
> Integ test improvements

- docs/basics/installation.md
> docs: document configuration of proxies

- .circleci/config.yml
* **ci**: Changes to the CI configuration.
Fixes issue were CI would fail because we were using an older version of the `ghr` package.
> ci: update version of image used in release job

- .circleci/config.yml
> ci: fix typo

- CHANGELOG.md
- README.md
- bin/release.ts
- dashboard/package.json
- docs/examples/README.md
- docs/examples/demo-project.md
- docs/examples/remote-sources.md
- docs/examples/tls-project.md
- docs/examples/using-garden-in-ci.md
- docs/using-garden/container-modules.md
- docs/using-garden/remote-kubernetes.md
- docs/using-garden/using-helm-charts.md
- garden-service/package.json
Bump version and update changelog.
EDIT: Also includes a small fix to the release script.
> chore(release): bump version to v0.10.1

- examples/hot-reload/README.md
> docs: add README to hot-reload example

- garden-service/package-lock.json
- garden-service/package.json
> fix: update ansi-escapes to fix spinner issue on macOS Terminal.app

- docs/reference/module-types/container.md
- docs/reference/module-types/maven-container.md
- garden-service/src/plugins/container/build.ts
- garden-service/src/plugins/container/config.ts
- garden-service/src/plugins/local/local-google-cloud-functions.ts
- garden-service/src/plugins/openfaas/config.ts
- garden-service/test/unit/src/plugins/container/container.ts
- garden-service/test/unit/src/plugins/container/helpers.ts
Needed to make a separate PR after editing #1051
> Add docker command flags (rebased)

- garden-service/src/plugins/kubernetes/commands/cleanup-cluster-registry.ts
The cleanup script was hanging or simply not working. 
Specifically it would crash whenever it tried to delete images from a repo with no available tags.
Another issue occurred whenever the docker-daemon had too many images to delete and reached the maximum lenght of arguments for the delete command. 
This PR fixes those bugs. 
Fixes #1041 
> fix: cleanup-cluster-registry script fails to run

- garden-service/src/garden.ts
- garden-service/test/unit/data/test-projects/1067-module-ref-within-file/Dockerfile
- garden-service/test/unit/data/test-projects/1067-module-ref-within-file/garden.yml
- garden-service/test/unit/src/garden.ts
> fix(core): error in some cases when referencing modules within file

- CHANGELOG.md
- README.md
- dashboard/package-lock.json
- dashboard/package.json
- docs/examples/README.md
- docs/examples/demo-project.md
- docs/examples/remote-sources.md
- docs/examples/tls-project.md
- docs/examples/using-garden-in-ci.md
- docs/using-garden/container-modules.md
- docs/using-garden/remote-kubernetes.md
- docs/using-garden/using-helm-charts.md
- garden-service/package-lock.json
- garden-service/package.json
> chore(release): bump version to v0.10.5

- .circleci/config.yml
> Test Garden on minikube in CI

- garden-service/src/proxy.ts
Circumvents an issue where a `"close"` event is fired for the `local` socket in `proxy.ts` with the `_remote` still undefined.
The event fires when _opening_ a port forward URL in the browser, usually after having opened and closed the tab a few times before. I'm not sure why it fires on open and why `_remote` is undefined.
Fixes #1088 
@edvald Could you please sanity check this? I'm not sure what the underlying issue is TBH.
> fix(proxy): handle undefined _remote Socket

- garden-service/src/plugins/openfaas/build.ts
Previously, Garden would try to get the build status of an OpenFaaS module before building the function. This basically means that Garden was trying to run Docker commands in a directory that didn't exist, something like `.garden/build/my-function/build/my-function`, where the second `build/my-function` is only created when the function is built.
Now we build the function before getting the build status.
Fixes #1116 
Not super familiar with the OpenFaaS workflow so I just went with the most obvious solution.
> fix(openfaas): build function before getting container build status

- garden-service/src/vcs/git.ts
- garden-service/test/unit/src/vcs/git.ts
.gitignore files were not respected in the default configuration.
The issue also applied to other scenarios where users had multiple
dotIgnoreFiles set in their project configs.
Fixes #1121
> fix(vcs): .gitignore files were not respected

- garden-service/src/logger/renderers.ts
- garden-service/src/logger/writers/json-terminal-writer.ts
- garden-service/test/unit/src/logger/log-entry.ts
- garden-service/test/unit/src/logger/renderers.ts
- garden-service/test/unit/src/logger/writers/json-terminal-writer.ts
This is should've been included with #1128 from yesterday.
> fix(logger): concat messages when formatting for json

- garden-service/src/plugins/openfaas/openfaas.ts
> fix(openfaas): user env variables weren't passed to the function

- garden-service/src/config/common.ts
A minor refactor, relating to another PR that's in the works.
Nope.
> refactor: make joi.meta() arguments type-safe

- CONTRIBUTING.md
Makes the task of announcing the release explicit.
No
> docs: updated CONTRIBUTING.md to include release announcement

- garden-service/src/garden.ts
- garden-service/src/vcs/git.ts
- garden-service/src/vcs/vcs.ts
- garden-service/test/unit/src/garden.ts
- garden-service/test/unit/src/vcs/git.ts
- garden-service/test/unit/src/vcs/vcs.ts
We weren't explicitly catching the error thrown when Garden is run outside of a git repo. This makes that clearer to the user.
Closes #1194
> improvement: better error when attempting to run outside of git repo

- CONTRIBUTING.md
Improve CONTRIBUTING.md. See also #1135.
> docs: add npm install step to CONTRIBUTING.md

- docs/using-garden/variables-and-templating.md
- markdown-link-check-config.json
Fixes some broken links on `master`
Fixes #
> docs: fixed some broken links and updated link checker

- .github/workflows/update-homebrew.yml
- gulpfile.ts
- support/homebrew-formula.rb
This automates the Homebrew Formula push after a release is published.
Note: after this is merged and tested with a real release, I will make a new PR to update the `CONTRIBUTING.md` and remove the gulp task.
> chore: automated homebrew update with GitHub actions

- docs/reference/providers/kubernetes.md
- docs/reference/providers/local-kubernetes.md
- examples/deployment-strategies/README.md
- examples/deployment-strategies/backend/.dockerignore
- examples/deployment-strategies/backend/.gitignore
- examples/deployment-strategies/backend/Dockerfile
- examples/deployment-strategies/backend/garden.yml
- examples/deployment-strategies/backend/webserver/main.go
- examples/deployment-strategies/frontend/.dockerignore
- examples/deployment-strategies/frontend/Dockerfile
- examples/deployment-strategies/frontend/app.js
- examples/deployment-strategies/frontend/garden.yml
- examples/deployment-strategies/frontend/main.js
- examples/deployment-strategies/frontend/package.json
- examples/deployment-strategies/frontend/test/integ.js
- examples/deployment-strategies/garden.yml
- garden-service/src/config/common.ts
- garden-service/src/docs/config.ts
- garden-service/src/docs/templates/config-partial.hbs
- garden-service/src/plugins/kubernetes/config.ts
- garden-service/src/plugins/kubernetes/container/deployment.ts
- garden-service/src/plugins/kubernetes/container/service.ts
- garden-service/src/plugins/kubernetes/local/config.ts
- garden-service/src/plugins/kubernetes/status/status.ts
- garden-service/src/plugins/kubernetes/system.ts
- garden-service/src/types/plugin/service/deployService.ts
- garden-service/test/e2e/garden.yml
- garden-service/test/e2e/src/pre-release.ts
- garden-service/test/unit/src/plugins/kubernetes/container/service.ts
- Introduce the ability to specify different deployment-strategies.
- Implement blue-green deployments.
- Adds "experimental" meta field to joi schemas.
- Introduce "Experimental feature" warning message.
- Add new example called `deployment-strategies`
Fixes #
> feat: blue-green deployment

- .github/workflows/update-homebrew.yml
Add the workflow to update homebrew back.
As you might notice from the file, we check if the release is a `prerelease` on each step.
There was the possibility of filtering the full job with an `if` condition but it got removed few weeks ago because the implementation had bugs. Hopefully it will get back soon.
Also, no, `if: !github.event.release.prerelease` is not valid.
🎶 Oh, the joy of working with beta releases. 🎶
> ci: add updated version of GitHub workflow

- CONTRIBUTING.md
Are there any other manual testing steps we should be including here?
> docs: add manual testing to pre-release checklist

- garden-service/src/plugins/kubernetes/util.ts
This issue caused errors when e.g. exec-ing commands and retrieving logs
from pods.
Fixes #1184
> fix(k8s): filter out failed and evicted pods when listing

- .gitignore
- examples/terraform-gke/README.md
- examples/terraform-gke/garden.yml
- garden-service/src/plugins/terraform/common.ts
One small bug fix, and a small improvement to the `terraform-gke` example.
Look at the individual commits, pretty straightforward.
> Terraform fixes

- garden-service/src/plugins/kubernetes/api.ts
- garden-service/src/plugins/kubernetes/kubernetes-module/handlers.ts
This would also have applied in cases where a group had different
resource types under different API versions. Which is not particularly
common, but most likely affected some other resource types.
Fixes #1275
> fix(k8s): handle CronJob resources correctly

- .github/stale.yaml
Take a look at the configuration and see if it looks sane. This is basically the default config with a few adjustments.
> chore: setup stalebot

- .gitignore
This is used for the VSCode Local History plugin.
> chore: add .history to .gitignore

- examples/demo-project/garden.yml
> fix: set correct context for demo-project

- dashboard/.eslintrc.js
- dashboard/package-lock.json
- dashboard/package.json
- dashboard/src/app.tsx
- dashboard/src/components/action-icon.tsx
- dashboard/src/components/card.tsx
- dashboard/src/components/copy-action-icon.tsx
- dashboard/src/components/entity-result.tsx
- dashboard/src/components/modal.tsx
- dashboard/src/containers/entity-result.tsx
- dashboard/src/containers/overview.tsx
- dashboard/src/contexts/ui.tsx
- dashboard/src/setupProxy.js
- garden-service/src/actions.ts
- garden-service/src/commands/get/get-task-result.ts
- garden-service/src/commands/get/get-test-result.ts
- garden-service/src/server/server.ts
- garden-service/src/util/artifacts.ts
- garden-service/test/unit/src/commands/get/get-task-result.ts
- garden-service/test/unit/src/commands/get/get-test-result.ts
- garden-service/test/unit/src/server/server.ts
- garden-service/test/unit/src/util/artifacts.ts
Displays stored artifacts in the dashboard.
> Artifacts dashboard

- docs/README.md
- docs/guides/cert-manager-integration.md
- docs/reference/providers/kubernetes.md
- docs/reference/providers/local-kubernetes.md
- garden-service/src/plugins/kubernetes/config.ts
- garden-service/src/plugins/kubernetes/init.ts
- garden-service/src/plugins/kubernetes/integrations/cert-manager.ts
- garden-service/src/plugins/kubernetes/kubectl.ts
- garden-service/src/plugins/kubernetes/kubernetes.ts
- garden-service/src/plugins/kubernetes/local/config.ts
- garden-service/static/kubernetes/system/cert-manager/cert-manager-crd.yaml
- garden-service/test/unit/src/plugins/kubernetes/integrations/cert-manager.ts
- package-lock.json
Implement the cert-manager integration. This will allow installation and configuration of Tls certificates through Garden.
**NOTE: please merge after #1317**
For this feature to work properly, it needs better "readiness" check for Pods. I implemented and reverted a basic check in favour of @edvald implementation in the "artifact PR".
> feat: cert-manager integration

- garden-service/src/plugins/kubernetes/config.ts
> chore: fix linting error

- garden-service/src/plugins/kubernetes/run.ts
> fix(k8s): remove the tick

- garden-service/src/bin/add-version-files.ts
- garden-service/src/bin/generate-docs.ts
- garden-service/src/cli/cli.ts
- garden-service/src/commands/get/get-eysi.ts
- garden-service/src/docs/config.ts
- garden-service/src/docs/generate.ts
- garden-service/src/docs/table-of-contents.ts
- garden-service/src/util/ext-tools.ts
- garden-service/test/e2e/e2e-project.ts
- garden-service/test/helpers.ts
- garden-service/test/run-garden.ts
- garden-service/test/unit/src/build-dir.ts
- garden-service/tslint.json
> chore(lint): disallow console logs in garden-service

- docs/guides/using-helm-charts.md
- docs/reference/providers/kubernetes.md
- docs/reference/providers/local-kubernetes.md
- garden-service/src/build-dir.ts
- garden-service/src/plugins/kubernetes/commands/cleanup-cluster-registry.ts
- garden-service/src/plugins/kubernetes/config.ts
- garden-service/src/plugins/kubernetes/container/build.ts
- garden-service/src/plugins/kubernetes/hot-reload.ts
- garden-service/src/plugins/kubernetes/util.ts
- garden-service/src/util/string.ts
- garden-service/static/kubernetes/system/build-sync/templates/deployment.yaml
- garden-service/test/e2e/garden.yml
- garden-service/test/e2e/src/pre-release.ts
- garden-service/test/unit/src/plugins/kubernetes/hot-reload.ts
If two processes would copy at the same time to a target, one could
delete the files from the other. We now set rsync's temp directory
outside of the target directory, which resolves the problem.
> fix(sync): fix intermittent concurrency issues while syncing directories

- garden-service/src/build-dir.ts
Without this, filenames could be matched in any directory. Now the
file list is explicit about file locations. We thus don't need any
explicit excludes either.
The same issue was not found on other platforms, but it's possible this
also fixes potential issues on *nix platforms.
> fix(windows): fix excludes and filename anchoring

- CHANGELOG.md
- README.md
- dashboard/package-lock.json
- dashboard/package.json
- docs/examples/README.md
- docs/examples/demo-project.md
- docs/examples/tls-project.md
- docs/examples/using-garden-in-ci.md
- docs/guides/container-modules.md
- docs/guides/remote-kubernetes.md
- docs/guides/terraform.md
- docs/guides/using-helm-charts.md
- docs/guides/using-remote-sources.md
- docs/using-garden/adding-modules.md
- docs/using-garden/running-tasks.md
- garden-service/package-lock.json
- garden-service/package.json
~~Note: We need to fix the changelog before merging! The version tags are borked.~~
Edit: This has been fixed.
> chore(release): bump version to v0.10.15

- dashboard/package.json
- dashboard/src/containers/logs.tsx
The conditional calling of a hook was causing the following error:
https://stackoverflow.com/q/55622768/5629940
Fixes #1307
> fix(dashboard): fix hooks render order on logs page

- .circleci/config.yml
- bin/bootstrap-osx
- bin/check-docs
- docs/guides/remote-kubernetes.md
- docs/guides/using-helm-charts.md
- docs/reference/providers/README.md
- docs/troubleshooting.md
- examples/istio/README.md
Checking links in our docs was taking way too long. Now it's parallelized to be much faster.
> Faster docs check

- .circleci/config.yml
- examples/kaniko/README.md
- examples/kaniko/backend/.dockerignore
- examples/kaniko/backend/.gitignore
- examples/kaniko/backend/Dockerfile
- examples/kaniko/backend/garden.yml
- examples/kaniko/backend/webserver/main.go
- examples/kaniko/frontend/.dockerignore
- examples/kaniko/frontend/Dockerfile
- examples/kaniko/frontend/app.js
- examples/kaniko/frontend/garden.yml
- examples/kaniko/frontend/main.js
- examples/kaniko/frontend/package.json
- examples/kaniko/frontend/test/integ.js
- examples/kaniko/garden.yml
- garden-service/src/plugins/kubernetes/container/build.ts
- garden-service/src/plugins/kubernetes/system.ts
- garden-service/test/e2e/garden.yml
kaniko was trying to mount an inexistent volume, the deployment would hang and no images would get built.
Fixes #1293 
I added a new e2e test to verify this works and it runs against a new `demo-project-kaniko` project.
> fix(k8s): kaniko would hang when building remote images

- .circleci/config.yml
We were doing unnecessary work on tags and master merges, this should save some time and cycles.
Also separating e2e tests into individual tests now, instead of running all from one container.
> chore(ci): more optimal CircleCI pipelines

- CONTRIBUTING.md
- package-lock.json
- package.json
This PR removes a platform specific dev dependency, that makes building not non Darwin OS fail.
It also includes a line to text, to add context to the contributing guide
Fixes #
Please help pay attention to the package-lock.json file it is auto generated but there is a bit of change in there, I am not sure of why
> docs: remove extra package, add more text to readme

- garden-service/src/plugins/openfaas/openfaas.ts
We've been seeing flaky OpenFaaS example tests. This is an attempt to resolve that.
It is quite possible that this _doesn't_ solve the issue, but I've been unable to reproduce locally so it's worth a shot imo.
> fix(openfaas): add retry when deploying in case faas-netes is starting

- bin/release.ts
So that we don't push pre-release branches. Also updates updates the release script message for dry-runs.
> chore(release): do not push pre-release branches

- garden-service/src/plugins/kubernetes/helm/common.ts
- garden-service/src/plugins/kubernetes/helm/deployment.ts
- garden-service/src/plugins/kubernetes/helm/handlers.ts
- garden-service/src/plugins/kubernetes/helm/hot-reload.ts
- garden-service/src/plugins/kubernetes/helm/logs.ts
- garden-service/src/plugins/kubernetes/helm/run.ts
- garden-service/src/plugins/kubernetes/helm/status.ts
- garden-service/src/plugins/kubernetes/helm/test.ts
- garden-service/test/data/test-projects/helm/api-image/Dockerfile
- garden-service/test/data/test-projects/helm/api-image/app.py
- garden-service/test/data/test-projects/helm/api-image/garden.yml
- garden-service/test/data/test-projects/helm/api-image/requirements.txt
- garden-service/test/integ/src/plugins/kubernetes/helm/common.ts
- garden-service/test/integ/src/plugins/kubernetes/helm/deployment.ts
This helps avoids an issue when generating charts in other modules.
Relates to #1382
> refactor(k8s): avoid building Helm chart before getting deploy status

- garden-service/src/plugins/kubernetes/init.ts
My bad. This was introduced in the Helm 3 PR, so users have not been affected.
> fix(k8s): error when running cluster-init command

- examples/hot-reload/garden.yml
- garden-service/src/plugins/kubernetes/status/status.ts
- garden-service/src/plugins/openfaas/openfaas.ts
- garden-service/src/process.ts
- garden-service/static/kubernetes/system/ingress-controller/garden.yml
- garden-service/test/e2e/src/pre-release.ts
- garden-service/test/run-garden.ts
We hadn't updated this in a while, which a user pointed out on our Slack.
> improvement(k8s): update bundled nginx controller version

- garden-service/src/garden.ts
- garden-service/src/plugins/kubernetes/port-forward.ts
- garden-service/src/proxy.ts
- garden-service/src/server/server.ts
- garden-service/src/util/network.ts
- garden-service/test/integ/src/plugins/kubernetes/helm/config.ts
- garden-service/test/unit/src/garden.ts
- garden-service/test/unit/src/server/server.ts
- garden-service/test/unit/src/util/network.ts
Without this, the automatic includes/excludes that providers set will
have no effect.
cc @eysi09
> fix(config): detect overlap after resolving module configs

- .github/PULL_REQUEST_TEMPLATE.md
It's amusingly meta to edit a PR template for a PR which edits our PR template.
> chore: update maintainer list in PR template

- garden-service/src/plugins/kubernetes/helm/deployment.ts
This avoids issues with dangling resources after a failed upgrade.
cc @baspetersdotjpeg
> improvement(k8s): set --atomic flag on helm upgrade

- garden-service/src/plugins/kubernetes/helm/tiller.ts
Fix the unhandled exception thrown by Garden when running the helm migration against a namespace where either:
- tiller has been deployed in the past but is not present anymore.
- Or it's deployed in the garden-system but not in a new project namespace.
Fixes #
> fix: remove resources only when tiller not deployed

- CONTRIBUTING.md
- docs/reference/module-types/helm.md
- garden-service/src/plugins/kubernetes/helm/config.ts
> chore: fix typos / inaccuracies

- support/install.sh
close #1469
Debian
```
docker run -t --rm debian sh -c "apt-get update && apt-get install -y curl && curl -sL https://raw.githubusercontent.com/garden-io/garden/8effebacea6feaeb46d03a991a6b63b8284aff03/support/install.sh | bash && /root/.garden/bin/garden"
```
Alpine
```
docker run -t --rm alpine sh -c "apk add --no-cache gcc curl bash && curl -sL https://raw.githubusercontent.com/garden-io/garden/8effebacea6feaeb46d03a991a6b63b8284aff03/support/install.sh | bash && /root/.garden/bin/garden"
```
> detect alpine system

- garden-service/src/server/server.ts
What it says on the tin, pretty straightforward improvement.
> improvement(dashboard): default to port 9777 when available

- docs/guides/local-kubernetes.md
- docs/guides/remote-kubernetes.md
- docs/installation.md
> docs: clarify version requirements for K8s and other dependencies

- dashboard/src/app.tsx
- dashboard/src/components/error-boundary.tsx
- dashboard/src/components/sidebar.tsx
- dashboard/src/containers/sidebar.tsx
- dashboard/src/contexts/api.tsx
Lazy load dashboard modules and add an error boundary around major components.
> chore(dashboard): lazy load modules + add error boundary

- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
Adds an issue template for feature requests.
Discussion in #1523 about how a template for feature requests was needed.
@10ko Figured I'd save you the hassle, hope this works!
> chore(github): add feature request issue template

- garden-service/package-lock.json
- garden-service/package.json
- garden-service/src/config/common.ts
- garden-service/test/unit/src/config/common.ts
> fix(core): allow git URLs not ending in .git

- garden-service/test/data/test-project-dependants/build-dependant/.dockerignore~chore(tests): create separate integ test suite
> chore: remove stray temp file

- garden-service/src/commands/deploy.ts
- garden-service/src/tasks/deploy.ts
Bumped into this when recording the screencaps for the website.
> chore: fix log messages

- garden-service/src/config/config-context.ts
- garden-service/test/unit/src/config/config-context.ts
Simple change, makes it easier to understand why certain template strings don't resolve.
> improvement(template): better error when a template key is not found (WIP)

- garden-service/src/plugins/terraform/common.ts
When your terraform scripts has modules and init has not been called, this ensures init is called
Fixes #
> fix(terraform): include module check for terraform init

- .circleci/config.yml
- CONTRIBUTING.md
- garden-service/src/analytics/analytics.ts
Add an env var for disabling analytics when developing.
> chore(analytics): add GARDEN_DISABLE_ANALYTICS env var

- README.md
Their docs gave me bad info. Great.
> docs: fix README on GitBook

- docs/quick-start.md
Adds a note section in the Quick Start guide mentioning to update the context when running the demo project agains a remote cluster. A user on our Slack got stuck with that.
> docs: mention context config in quick start

- garden-service/src/commands/create/create-module.ts
Just some small things I noticed while demoing
> fix(cli): minor fixes for garden create module command

- dashboard/src/api/actions.ts
- garden-service/src/actions.ts
- garden-service/src/commands/get/get-status.ts
- garden-service/src/plugins/kubernetes/run.ts
- garden-service/src/tasks/get-service-status.ts
- garden-service/test/helpers.ts
- garden-service/test/unit/src/actions.ts
- garden-service/test/unit/src/commands/get/get-status.ts
- garden-service/test/unit/src/tasks/get-service-status.ts
> fix(core): tasks should not implicitly run when getting service status

- garden-service/src/plugins/kubernetes/helm/common.ts
Fix issues with using helm charts with external dependencies.
Fixes #1620
> Add dependency-update flag to helm template calls

- CONTRIBUTING.md
- bin/test-release.sh
Simple script for testing the release binary.
> chore(release): add a simple script for testing the release on *nix

- garden-service/src/plugins/kubernetes/helm/common.ts
- garden-service/src/plugins/kubernetes/helm/status.ts
> fix(k8s): error when helm returned empty YAML documents

- CONTRIBUTING.md
Updating the contributing instructions based on [this discussion ](https://kubernetes.slack.com/archives/CK7VC402X/p1583328082001000) on slack.
No issue.
@edvald
> docs: update contributing instructions

- README.md
This PR updates the link to the detailed installation instructions from a broken link.
> Updated link to detailed installation instructions

- .github/merge-when-green.yml
Giving this a spin... Might not work, but I need to merge it to find out.
> chore(ci): configure merge-when-green integration

- garden-service/src/plugins/kubernetes/logs.ts
Before this fix, `provider.kubeconfig` wasn't being passed to stern in the k8s log logic. This would result in errors when the context referenced by the provider config isn't defined in the default kubeconfig.
Also improved error messages when parsing log messages as JSON fails.
Fixes #1648
> fix(k8s): pass custom kubeconfig path to stern

- examples/build-dependencies/README.md
- examples/build-dependencies/backend/.dockerignore
- examples/build-dependencies/backend/.gitignore
- examples/build-dependencies/backend/Dockerfile
- examples/build-dependencies/backend/garden.yml
- examples/build-dependencies/backend/main.go
- examples/build-dependencies/frontend/.dockerignore
- examples/build-dependencies/frontend/Dockerfile
- examples/build-dependencies/frontend/app.js
- examples/build-dependencies/frontend/garden.yml
- examples/build-dependencies/frontend/main.js
- examples/build-dependencies/frontend/package-lock.json
- examples/build-dependencies/frontend/package.json
- examples/build-dependencies/frontend/test/integ.js
- examples/build-dependencies/garden.yml
- examples/build-dependencies/shared-config/config.env
- examples/build-dependencies/shared-config/garden.yml
Adds a dedicated "build dependencies" example. This gets asked about a lot in our community channel and so far this pattern has only been used implicitly in other example without proper explanation.
It'll also be referenced from the FAQ doc we're working on. 
None.
None.
> docs(examples): add build dependencies example

- garden-service/src/cli/cli.ts
- garden-service/test/unit/src/cli/cli.ts
I missed a beat in #1702, this should do the trick
Please test this quickly on your end before merging.
> fix(cli): configure provider/env correctly in `garden plugins` command

- examples/base-image/backend/Dockerfile.dev
- examples/base-image/backend/Dockerfile.prod
- examples/base-image/base-image/Dockerfile
- examples/base-image/garden.yml
See: https://github.com/garden-io/garden/issues/1707#issuecomment-600527508
> docs(examples): fix base image example

- docs/reference/module-types/persistentvolumeclaim.md
- garden-service/src/plugins/kubernetes/volumes/persistentvolumeclaim.ts
> fix(k8s): incorrect schema for persistentvolumeclaim dependencies field

- examples/ambassador/ambassador/garden.yml
The old chart was outdated and doesn't work with Helm 3.
Fixes #1748
> chore(examples): update ambassador helm chart

- garden-service/src/plugins/container/build.ts
- garden-service/src/plugins/container/helpers.ts
- garden-service/src/plugins/google/gcloud.ts
- garden-service/src/plugins/kubernetes/container/build.ts
- garden-service/src/plugins/kubernetes/container/exec.ts
- garden-service/src/plugins/kubernetes/run.ts
- garden-service/src/util/util.ts
- garden-service/test/integ/src/plugins/kubernetes/commands/pull-image.ts
- garden-service/test/unit/src/plugins/container/container.ts
I noticed some issues with error messages. I refactored the `spawn` util function slightly to make its output more explicit and clear.
> fix(k8s): duplicate text in some error logs

- garden-service/src/plugins/kubernetes/container/build.ts
This cleans up the kaniko pod after building images.
No issue.
Fixes #
@edvald
> fix: cleanup kaniko pod

- garden-service/src/commands/login.ts
- garden-service/src/commands/logout.ts
- garden-service/src/platform/auth.ts
• Made `login` and `logout` use `noProject = true` (to speed them up).
• Fixed login auth logic to work with latest platform implementation, and improved error handling.
> Login/logout command improvements.

- garden-service/package-lock.json
- garden-service/package.json
- garden-service/src/commands/migrate.ts
- garden-service/src/config/base.ts
- garden-service/test/data/test-project-invalid-config/invalid-syntax-module/garden.yml
- garden-service/test/unit/src/config/base.ts
When YAML parsing fails, emit more useful error messages by passing the failed file contents through a YAML validator.
This will e.g. identify duplicate keys and other syntax errors.
Fixes #1572.
> fix(core): better error messages for invalid YAML

- docs/advanced/terraform.md
- docs/guides/in-cluster-building.md
- docs/misc/faq.md
- garden-service/src/cli/cli.ts
- garden-service/src/plugins/terraform/commands.ts
- garden-service/src/util/ext-tools.ts
- garden-service/test/unit/src/cli/cli.ts
Couple of issues I bumped into while using the `garden plugins terraform ...` commands, on top of #1776.
See the individual commits for details.
> Fix terraform provider command issues

- docs/reference/providers/terraform.md
- garden-service/src/plugins/terraform/cli.ts
This PR, includes the latest version of terraform
Fixes #
Garden cloud is using the latest version of garden cloud
> chore(terraform): include latest terraform version

- garden-service/src/config/config-context.ts
- garden-service/test/unit/src/actions.ts
- garden-service/test/unit/src/config/config-context.ts
- garden-service/test/unit/src/template-string.ts
> fix(template): fix imprecise error when key on nested context is missing

- garden-service/src/plugins/kubernetes/run.ts
Ensure that artifacts are only copied into one location by using a tmpDir per artifact.
@edvald 
Fixes # https://github.com/garden-io/garden/issues/1781
> fix(k8s): only copy artifacts once

- garden-service/src/cli/cli.ts
- garden-service/src/cloud/auth.ts
- garden-service/src/cloud/buffered-event-stream.ts
- garden-service/src/commands/login.ts
- garden-service/src/config/project.ts
- garden-service/src/garden.ts
This replaces the temporary setup we had based on project names (using ids instead) and the `GARDEN_CLOUD` env variable.
> feat(platform): added id and domain to projects

- garden-service/src/plugins/kubernetes/helm/build.ts
- garden-service/src/plugins/kubernetes/helm/helm-cli.ts
This upgrades helm to the latest versions.
@edvald
> chore(k8s): upgrade helm

- garden-service/src/plugins/kubernetes/container/build.ts
Latest kaniko has a bug fix we need. 
@edvald
> chore(k8s): upgrade kaniko

- examples/local-exec/backend/garden.yml
Include was missing the Dockerfile.
> fix(examples): fix local exec example

- garden-service/src/plugins/kubernetes/container/build.ts
We currently run a bunch of noop containers that proxy kaniko to in-cluster registry, even if in-cluster registry is switched off. 
This means when running heavier loads, you're less likely to
starve out of PIDs. Also means the builds should start faster
We know that these are safe to remove because in our clusters we have manually deleted garden-registry and these just busyloop
> feat(kaniko): when using remote registry do not run the proxy

- garden-service/src/enterprise/buffered-event-stream.ts
This is done to match the renaming of this entity on the backend.
> chore: rename workflow UID to workflow run UID

- docs/reference/commands.md
- docs/reference/config.md
- garden-service/src/config/project.ts
- garden-service/src/config/workflow.ts
- garden-service/src/garden.ts
- garden-service/test/unit/src/config/workflow.ts
Added an optional `namespace` field to trigger specs.
We apply the same validation and default namespace rules for trigger namespaces as we do for environment specs.
> feat(workflows): add namespacing support

- garden-service/src/cli/cli.ts
- garden-service/src/enterprise/auth.ts
- garden-service/src/enterprise/buffered-event-stream.ts
- garden-service/src/enterprise/init.ts
Added some debug/silly-level log statements around auth token logic and `BufferedEventStream`.
> chore(enterprise): more debug log statements

- garden-service/src/plugins/kubernetes/container/build.ts
When running without socat we can't wait for socat to start.
I'm not sure how this passed the garden-io CI, it also magically
passed ours when we merged the update to the cli. This is to
quickly unbreak the master branch, I'll investigate further
Fixes #
> bugfix(kaniko): correctly set container command when using kaniko

- docs/getting-started/2-initialize-a-project.md
- examples/demo-project-start/backend/main.go
- examples/demo-project-start/frontend/Dockerfile
- examples/demo-project-start/frontend/app.js
> docs: fix broken test in starter project

- garden-service/src/plugins/kubernetes/helm/common.ts
- garden-service/src/plugins/kubernetes/types.ts
As described at https://github.com/garden-io/garden/issues/1951
When a helm chart has dependencies it needs to resolve them before executing the helm install/upgrade command
Fixes #1951
@edvald, @thsig
> #1951 Added helm dependency update in case of requirements.yaml or Chart dependencies

- garden-service/package-lock.json
- garden-service/package.json
- garden-service/src/analytics/analytics.ts
- garden-service/src/cli/cli.ts
- garden-service/src/cli/helpers.ts
- garden-service/src/constants.ts
- garden-service/src/db/connection.ts
- garden-service/src/enterprise/auth.ts
- garden-service/src/enterprise/buffered-event-stream.ts
- garden-service/src/logger/logger.ts
- garden-service/src/server/server.ts
- garden-service/src/task-graph.ts
- garden-service/src/tasks/resolve-provider.ts
- garden-service/src/util/profiling.ts
- garden-service/test/helpers.ts
- garden-service/test/unit/src/cloud/auth.ts
We now read and export most environment variables used by the framework in `constants.ts`, using the `env-var` library.
This should simplify tracking the environment variables used by the framework (compared to ad-hoc reading of `process.env.*`).
> chore: consolidate environment variables

- core/src/garden.ts
- core/src/server/server.ts
- dashboard/README.md
- dashboard/package-lock.json
- dashboard/package.json
- dashboard/public/index.html
- dashboard/src/components/logs.tsx
- dashboard/src/components/page-error.tsx
- dashboard/src/components/terminal.tsx
- dashboard/src/components/text.tsx
- dashboard/src/constants.js
- dashboard/src/styles/variables.ts
See individual commits. Handful of visual/UX improvements.
> Dashboard improvements

- dashboard/src/components/action-icon.tsx
...accidentally set the wrong color in a previous commit
> fix(dashboard): set correct icon hover color

- docs/getting-started/1-installation.md
Easy typo fixes make the documentation better for everyone.
> (chore) 1-installation.md: Typofix fisrt -> first

- .circleci/config.yml
- CONTRIBUTING.md
- scripts/push-containers.sh
- scripts/release.ts
In a recent refactor, some of the release-related scripts were changed and moved around, causing problems in the release pipeline.
Please comment if any of the changes feel hacky or incomplete with respect to the larger setup.
> chore: fixes to release process

- CONTRIBUTING.md
What it says on the tin.
Fixes #
> chore: remove references to npm from CONTRIBUTING.md

- core/src/plugins/kubernetes/util.ts
When we have environment variables  in nature below 
```
VAULT_APPROLE_SECRET_ID: ${var.vault-approle-secret-id}?
VAULT_APPROLE_ROLE_ID: ${var.vault-approle-role-id}?
```
They are conditional and can be `undefined`, `null` check involving `===` does not handle the case of it being `undefined`
This PR adds an explicit `undefined` check
Fixes #
> fix(k8s): filter out undefined environment variable values

- core/src/cli/cli.ts
- core/test/unit/src/cli/cli.ts
> fix(cli): handle option flags in any order

- core/src/plugins/kubernetes/commands/cleanup-cluster-registry.ts
Added some error handling, extended timeouts, set concurrency limits
and added batching for some potentially large requests.
> fix(k8s): fix some issues with the cleanup-cluster-registry command

- scripts/run-script.ts
We were not handling colors correctly, and the wrapping was busted
> chore(ci): fix log output in CircleCI script runs

- core/src/commands/get/get-modules.ts
- core/src/commands/get/get.ts
- core/test/unit/src/commands/get/get-modules.ts
- docs/reference/commands.md
- package.json
> feat(cli): add `get module(s)` command

- core/src/config/workflow.ts
- docs/reference/commands.md
- docs/reference/config.md
Adds `pull-request-opened` as a workflow trigger.
Fixes #
> fix(enterprise): add pull-request-closed as trigger event

- core/src/commands/run/workflow.ts
- core/src/constants.ts
- core/src/enterprise/buffered-event-stream.ts
- core/src/enterprise/workflow-lifecycle.ts
For logged-in users, we now also register internal workflow runs with GE.
> feat(enterprise): register internal workflows

- docs/advanced/terraform.md
The usage example in the terraform docs were not correct (missing `--` when passing arguments to the plugin command).
None
> chore(docs): fix usage example in terraform docs

- .circleci/config.yml
- cli/src/build-pkg.ts
- scripts/run-script.ts
> chore(release): fix edge build and release

- support/alpine.Dockerfile
- support/buster.Dockerfile
This was messing with our analytics stats.
> chore: disable analytics in docker builds

- core/src/plugins/kubernetes/api.ts
- scripts/test-release.sh
This fixes a regression that was introduced when we started using the k8s API to run commands in pods.
Fixes #2064.
> fix(k8s): fix IO handling for exec command

- core/src/enterprise/buffered-event-stream.ts
- core/test/unit/src/enterprise/buffered-event-stream.ts
We now correctly handle the case where a single event or log entry payload exceeds `MAX_BATCH_BYTES` (dropping the event / log entry and logging an error).
Also wrote a couple of unit tests for the batching logic.
In addition, the log level for error messages generated when posting to targets failed was raised, to avoid cluttering the log.
> fix(enterprise): fix batch sizing logic

- core/src/plugins/kubernetes/local/microk8s.ts
- docs/guides/local-kubernetes.md
Fixes microk8s command calls that previously used dot-notation.
Fixes #2067
Tested on macOS
> fix(cli): update microk8s commands

- core/src/cli/cli.ts
- core/src/commands/plugins.ts
- core/src/commands/tools.ts
- core/test/unit/src/cli/cli.ts
> fix(cli): bad error message when --env namespace is set on some commands

- core/src/garden.ts
- core/test/unit/src/garden.ts
Before this fix, circular build dependencies between modules would result in an internal error (instead of an informative error message).
> fix(core): fix circular dependency detection

- core/src/actions.ts
- core/src/commands/deploy.ts
- core/src/config/config-context.ts
- core/src/garden.ts
- core/src/resolve-module.ts
- core/src/tasks/deploy.ts
- core/src/tasks/resolve-module.ts
- core/src/template-string-parser.pegjs
- core/src/template-string.ts
- core/src/util/testing.ts
- core/test/unit/src/config/config-context.ts
- core/test/unit/src/garden.ts
This was introduced in v0.12.7 after some changes in template resolution
logic. Added tests to catch this, should all work as expected now, but
please test to make sure when reviewing.
Fixes #2110
> fix(core): some conditional template strings were not resolved correctly

- docs/misc/troubleshooting.md
This came up on our community channel.
Fixes #
> docs(troubleshootin): add entry on nginx timing out

- docs/misc/troubleshooting.md
Adds an entry in our Troubleshooting guide on a bug that some Docker CE users can bump into, see #2123 for details.
Fixes #2123 
> docs(faq): add an entry on Docker CE buildkit issue

- README.md
**What this PR does / why we need it**: Edits to the README to bring it up to date. 
**Which issue(s) this PR fixes**: [#2142](https://github.com/garden-io/garden/issues/2142)
Fixes #
> improvement(readme): Updates to project README

- core/src/config/config-context.ts
- core/src/config/module-template.ts
- core/src/config/project.ts
- core/src/garden.ts
- core/src/vcs/git.ts
- core/src/vcs/vcs.ts
- core/test/unit/src/config/config-context.ts
- core/test/unit/src/config/project.ts
- core/test/unit/src/garden.ts
- core/test/unit/src/vcs/git.ts
- core/test/unit/src/vcs/vcs.ts
- docs/reference/template-strings.md
The current Git branch can now be used in template strings under `${git.branch}`.
Closes #2086.
> feat(core): provide git branch to template strings

- core/src/proxy.ts
> fix(core): fix failing port forwards on Windows in certain scenarios

- docs/guides/in-cluster-building.md
- docs/misc/troubleshooting.md
Add a note on how to enable layer cache when using Kaniko on ECR.
Fixes #
> docs: add note on Kaniko cache repos

- scripts/release.ts
We now correctly increment the version used in non-root `package.json`-s in the release process.
> chore: fixes to release script

- core/src/plugins/kubernetes/helm/config.ts
- docs/guides/cloud-provider-setup.md
- docs/reference/module-types/helm.md
- static/kubernetes/system/ingress-controller/garden.yml
Supersedes #2173 (big thanks to @stevenmatthewt who worked this out 99%
of the way!)
> fix(k8s): upgrade from deprecated nginx helm chart

- examples/disabled-configs/garden.yml
This example project was broken when using the `remote` environment (since the `defaultNamespace` was set at the provider rather than at the environment level).
We usually run this project using the `local` environment, so this only surfaced today.
> chore: fix disabled-configs example project

- core/src/enterprise/api.ts
> fix(enterprise): also validate env tokens

- core/src/enterprise/api.ts
- core/src/enterprise/get-secrets.ts
> fix(enterprise): fix secrets res

- core/src/garden.ts
- core/src/template-string.ts
- core/test/unit/src/garden.ts
- core/test/unit/src/template-string.ts
TODO: Re-enable @thsig.
Fixes #
> chore(core): disable secret validation for now

- core/src/template-string.ts
> chore(core): fix lint error

- docs/welcome.md
**What this PR does / why we need it**: Mentions the community forum and Garden Enterprise on docs welcome page so that users who are looking for this information can find it more easily. 
Fixes #
> improvement(docs): add support forum and enterprise to welcome page

- core/src/plugins/terraform/common.ts
- core/test/unit/src/plugins/terraform/common.ts
> fix(terraform): make sure terraform init is run before workspace list

- core/src/config/config-context.ts
- core/src/config/project.ts
- core/src/garden.ts
- core/test/unit/src/config/config-context.ts
- core/test/unit/src/config/project.ts
- docs/reference/template-strings.md
Basic thing that I was looking to use, so I just added it.
> feat(config): add ${local.projectPath} template key

- core/test/unit/src/config/module-template.ts
> chore: fix broken unit test

- docs/using-garden/using-the-cli.md
> chore(docs): fix task command example

- .circleci/config.yml
- core/src/plugins/kubernetes/kubectl.ts
This should fix compatibility issues with recent versions of minikube.
> fix(k8s): fix issues with minikube v1.17

- .circleci/config.yml
- core/package.json
- core/src/plugins/kubernetes/config.ts
- core/src/plugins/kubernetes/container/build.ts
- core/src/plugins/kubernetes/container/deployment.ts
- core/src/plugins/kubernetes/local/config.ts
- core/src/plugins/kubernetes/local/kind.ts
- core/src/plugins/kubernetes/status/status.ts
- core/test/data/test-projects/container/volume-reference/garden.yml
- core/test/integ/src/plugins/kubernetes/container/deployment.ts
- core/test/integ/src/plugins/kubernetes/system.ts
- core/test/integ/src/plugins/kubernetes/volume/persistentvolumeclaim.ts
- docs/guides/local-kubernetes.md
- docs/reference/providers/kubernetes.md
- docs/reference/providers/local-kubernetes.md
- scripts/create-kind-cluster.sh
- static/kubernetes/system/nginx-kind/garden.yml
Found a few issues when setting up and using KinD. For one, installing nginx was not working, and some things needed explanation in the docs. 
Plus I've been wanting to set up an integ test for a while, having a crack at that now.
> fix(k8s): fix some issues with KinD and add integ test

- core/src/plugins/kubernetes/api.ts
- core/src/plugins/kubernetes/kubernetes-module/common.ts
- core/test/integ/src/plugins/kubernetes/kubernetes-module/handlers.ts
> fix(k8s): error in status checks for missing CRD manifests

- core/test/e2e/src/pre-release.ts
- examples/vote/README.md
- examples/vote/postgres/garden.yml
- examples/vote/workflows.garden.yml
Add a sanity check for the `run workflow` command in order to avoid future regressions.
Fixes #
> test(workflows): add workflow smoke-test in pre-release script

- core/src/config/config-context.ts
- core/src/config/workflow.ts
- core/test/unit/src/config/workflow.ts
> fix(workflows): error referencing undefined vars in workflow templates

- core/src/commands/exec.ts
- core/test/helpers.ts
- core/test/unit/src/commands/exec.ts
Fixes regression introduced in #2238 that hadn't been released
> fix(cli): regression in exec command parameter handling

- docs/misc/faq.md
Update FAQ question on out-of-scope Dockerfiles.
Fixes #
> docs(faq): update section on out-of-scope Dockerfiles

- support/alpine.Dockerfile
Closes #2261 (good catch @Chipcius 👍 )
> improve(core): add openssh-client to alpine base image

- core/src/plugins/terraform/cli.ts
> feat(terraform): add v0.14.7 as a supported version

- docs/reference/commands.md
- docs/reference/workflow-config.md
I merged a PR without the docs being up to date recently, this corrects that.
> chore: regenerate docs

- core/src/plugins/kubernetes/container/build/buildkit.ts
- core/test/unit/src/plugins/kubernetes/container/build/buildkit.ts
Flagged in community chat, simple fix + quick unit test.
> fix(k8s): typo in target image argument for buildkit

- dashboard/src/components/entity-cards/common.tsx
- dashboard/src/components/entity-result.tsx
- dashboard/src/components/graph/graph.scss
- dashboard/src/components/graph/index.tsx
- dashboard/src/components/logs.tsx
- dashboard/src/components/provider.tsx
- dashboard/src/components/terminal.tsx
- dashboard/src/containers/entity-result.tsx
- dashboard/src/containers/graph.tsx
- dashboard/src/containers/overview.tsx
- dashboard/src/containers/routes.tsx
Various fixes based on feedback on the new dashboard layout. Please check out the individual commits for review, and check each individually to see that it all works as desired.
> Dashboard styling fixes

- core/src/cli/cli.ts
- core/src/commands/login.ts
- core/src/commands/logout.ts
- core/src/enterprise/api.ts
- core/test/unit/src/commands/logout.ts
This really is an edge case and is mostly likely to happen during GE
development when switching between different GE envs.
Fixes #
> fix(core): fix logout when authenticated against different GE instance

- core/src/enterprise/api.ts
- core/src/enterprise/get-secrets.ts
- core/src/enterprise/workflow-lifecycle.ts
This is a regression introduced in a previous commit but was never
released.
Fixes #
> fix(enterprise): fix api response shape

- core/src/commands/login.ts
- core/src/enterprise/api.ts
- core/test/unit/src/commands/login.ts
I think this only happens for developers who may be logging into different instances of GE during testing. But who's to say we shouldn't get good error messages as well. 
Before:
```
Login ☁️
An error occurred while verifying client auth token with platform: Response code 401 (Unauthorized)
See error.log for detailed error message
```
After:
```
Login ☁️
⚠ Looks like your session token is invalid. If you were previously logged into a different instance
of Garden Enterprise, log out first before logging in.
An error occurred while verifying client auth token with platform: Response code 401 (Unauthorized)
See error.log for detailed error message
```
Fixes #
Feel free to add …
> improvement(enterprise): better error message on login 401 errors

- core/src/config/workflow.ts
- core/test/unit/src/commands/get/get-config.ts
- core/test/unit/src/commands/run/workflow.ts
- core/test/unit/src/config/workflow.ts
- docs/reference/commands.md
- docs/reference/workflow-config.md
Resource requests for workflow runner pods can now be set via `workflow.requests`.
> feat(enterprise): add requests to workflows

- support/install.ps1
We had some seriously outdated crap in there :/
> chore: update Windows installation script

- core/src/commands/enterprise/helpers.ts
- core/src/commands/enterprise/secrets/secrets-create.ts
- core/src/commands/enterprise/secrets/secrets-delete.ts
- core/src/commands/enterprise/secrets/secrets-list.ts
- core/src/commands/enterprise/users/users-create.ts
- core/src/commands/enterprise/users/users-delete.ts
- core/src/commands/enterprise/users/users-list.ts
- core/src/logger/util.ts
There were a couple of bugs with the enterprise secrets command:
- We weren't returning exit 1 when creating secrets failed.
- The `--yes` flag wasn't working.
This PR fixes both.
Fixes #
> fix(enterprise): ensure exit code and --yes flag work

- core/src/analytics/analytics.ts
- core/src/commands/get/get-config.ts
- core/src/enterprise/api.ts
- core/src/garden.ts
- core/test/data/test-project-a/garden.yml
- core/test/data/test-projects/login/has-domain-and-id/garden.yml
- core/test/unit/src/analytics/analytics.ts
- core/test/unit/src/commands/get/get-config.ts
- core/test/unit/src/config/base.ts
- docs/reference/commands.md
Add anonymized GE metadata to analytics events.
Fixes #
> chore: add anonymized GE metadata to analytic events

- core/src/plugins/kubernetes/helm/helm-cli.ts
This bumps the helm binary to v3.5.4 — helm 3.5 introduced experimental pull support for charts via OCI
> Chore(k8s): Update helm to v3.5.4

- core/src/commands/get/get-status.ts
- core/src/commands/get/get-test-result.ts
- core/src/commands/run/test.ts
- core/src/config-graph.ts
- core/src/tasks/test.ts
- core/src/types/test.ts
- core/src/vcs/vcs.ts
- core/test/integ/src/plugins/hadolint/hadolint.ts
- core/test/integ/src/plugins/kubernetes/container/container.ts
- core/test/integ/src/plugins/kubernetes/helm/test.ts
- core/test/integ/src/plugins/kubernetes/kubernetes-module/test.ts
- core/test/integ/src/plugins/kubernetes/system.ts
- core/test/unit/src/actions.ts
- core/test/unit/src/plugins/exec.ts
- core/test/unit/src/tasks/test.ts
- core/test/unit/src/types/test.ts
- plugins/conftest-kubernetes/test/conftest-kubernetes.ts
- plugins/conftest/test/conftest.ts
This ensures that tests are re-run when a downstream dependency changes that is more than one hop away in the config graph.
> fix(core): include deps in test version

- docs/guides/hot-reload.md
fix rendering in hot reloading docs.
Fixes #
> fix(docs): fix hint rendering

- core/src/enterprise/buffered-event-stream.ts
This was left in by accident as part of manual testing of a failure case.
> chore: fix typo

- core/src/commands/logs.ts
- core/test/unit/src/commands/logs.ts
Previously we were aligning service logs with respect to service names that were never rendered, e.g. because the log level was too high.
Fixes #
> improvement(core): better alignment for logs command

- core/package.json
- core/src/cli/cli.ts
- core/src/commands/get/get-vaccine.ts
- core/src/commands/get/get.ts
- docs/reference/commands.md
- yarn.lock
This command checks for openings at Berlin vaccination centers, using
the API from [Impstoff.Link](https://impfstoff.link/). Obviously this is only useful for people in
Berlin, and only during the vaccination efforts. A big shout out and
thank you to the people behind Impstoff.Link for making this possible.
And of course to everyone working towards getting Berliners vaccinated.
Fixes #
> chore: add vaccine watcher command

- docs/basics/stack-graph.md
Fixes #2401
cc @baspetersdotjpeg 
> docs: fix bad links

- core/src/template-string/functions.ts
- docs/reference/template-strings.md
Nice and simple. See the updated reference docs in the commit.
> feat(template): add yamlEncode and yamlDecode template helpers

- static/kubernetes/system/util/templates/deployment.yaml
> fix: malformed helm manifest

- core/src/plugins/kubernetes/run.ts
> fix(k8s): error copying artifacts with new version of tar in image

- core/src/plugins/kubernetes/util.ts
Ran into this when working on a different feature. Simple fix, but a somewhat embarrassing old bug 😬
> fix(k8s): logs command wouldn't get logs from all pods

- core/package.json
- core/src/analytics/analytics.ts
- core/src/plugins/kubernetes/util.ts
- core/test/unit/src/analytics/analytics.ts
- yarn.lock
This PR introduces a v2 version of anonymized analytics properties. This
version includes a human readable string in the ID so that they are
easier to recognize.
Fixes #
> chore: add human readable strings to anonymized IDs

- core/src/commands/get/get-tasks.ts
- core/src/commands/get/get-tests.ts
- core/src/commands/get/get.ts
- core/src/commands/helpers.ts
- core/src/config-graph.ts
- core/test/unit/src/commands/get/get-tests.ts
- docs/reference/commands.md
I noticed this command was missing when I needed it so I added it. Uses the same output format as the `get tasks` command.
Fixes #
> improvement(core): add get tests command

- core/src/plugins/kubernetes/constants.ts
- core/src/plugins/kubernetes/integrations/cert-manager.ts
- core/src/plugins/kubernetes/kubernetes.ts
- core/test/unit/src/plugins/kubernetes/integrations/cert-manager.ts
See https://kubernetes.slack.com/archives/CKM7CP8P9/p1625390626203500
> fix(k8s): ingressClass wasn't respected in cert-manager integration

- cli/package.json
- core/package.json
- core/src/plugins/terraform/common.ts
- core/src/tasks/base.ts
- core/src/util/archive.ts
- core/src/util/ext-tools.ts
- core/src/util/util.ts
- core/test/integ/src/plugins/kubernetes/api.ts
- dashboard/package.json
- package.json
- sdk/package.json
- yarn.lock
Fingers crossed, maybe this helps with our compilation times and VSCode performance...
> chore: update to TypeScript 4.3.5

- core/src/template-string/functions.ts
> fix(templates): uuidv4() helper function was broken

- core/src/cli/cli.ts
- core/src/exceptions.ts
- core/src/logger/util.ts
A little bundle of issues I found with error reporting. See individual commits.
> Fix error reporting issues

- docs/welcome.md
> chore: add additional analytics to docs welcome page

- core/src/cli/cli.ts
- core/src/enterprise/buffered-event-stream.ts
- core/src/events.ts
- core/src/exceptions.ts
When logged in, we now stream a command metadata event.
> feat(cloud): stream command metadata

- core/src/plugins/container/config.ts
- docs/reference/module-types/container.md
- docs/reference/module-types/helm.md
- docs/reference/module-types/kubernetes.md
- docs/reference/module-types/maven-container.md
This PR adds the allowed options for `devMode.sync[].mode` to the module specifications
Fixes #2520
**Special notes for your reviewer**: -
> chore: add available options to devMode.sync[].mode description

- core/src/cli/cli.ts
- core/src/commands/logs.ts
- core/src/exceptions.ts
- core/src/logger/log-entry.ts
- core/src/logger/renderers.ts
- core/test/unit/src/logger/log-entry.ts
- core/test/unit/src/logger/logger.ts
- core/test/unit/src/logger/renderers.ts
We no longer truncate logger sections. Also fixes some lint and test errors that accidentally got merged to
master.
Fixes #
> improvement(core): do not truncate logger sections

- core/src/config/base.ts
- core/test/data/test-project-a/module-a/garden.yml
- core/test/unit/src/config/base.ts
- examples/demo-project/backend/garden.yml
> fix(config): module variables weren't propagated right at parse time

- core/src/plugins/container/container.ts
- core/src/util/util.ts
- core/test/unit/src/plugins/container/container.ts
Fixes the logic that detects overlapping hot reload sync targets.
Fixes #2534
> fix(container): fix hot reload target validation

- core/src/plugins/kubernetes/commands/cleanup-cluster-registry.ts
- docs/welcome.md
- examples/vote/vote/package.json
Chipping away at those pesky flaky tests...
> Fix test errors

- docs/guides/container-modules.md
- docs/guides/in-cluster-building.md
The placement was a little confusing.
> docs: clarify image publishing docs a bit

- core/src/commands/deploy.ts
- core/src/commands/helpers.ts
- core/test/unit/src/commands/deploy.ts
- core/test/unit/src/commands/helpers.ts
- docs/reference/commands.md
> improve(cli): make empty --dev flag equivalent to --dev=*

- core/src/plugins/terraform/cli.ts
Hi @edvald,
We would appreciate it if you could review the created PR at your earliest convenience.
We need this feature to proceed with our development.
close #2556
> feat(terraform): add v1.0.5 as a supported version

- .circleci/config.yml
- core/src/plugins/kubernetes/commands/cleanup-cluster-registry.ts
- core/test/e2e/garden.yml
- core/test/integ/helpers.ts
- core/test/integ/src/plugins/kubernetes/container/build/build.ts
- dashboard/package.json
- dashboard/src/app.test.tsx
- examples/build-dependencies/garden.yml
- examples/demo-project/backend/garden.yml
- examples/demo-project/garden.yml
- examples/deployment-strategies/garden.yml
- examples/disabled-configs/garden.yml
- examples/gke/garden.yml
- examples/hadolint/garden.yml
- examples/hot-reload-k8s/garden.yml
- examples/hot-reload-post-sync-command/garden.yml
- examples/hot-reload/garden.yml
- examples/kaniko/garden.yml
- examples/kubernetes-module/garden.yml
- examples/kubernetes-secrets/garden.yml
- examples/openfaas/garden.yml
- examples/project-variables/garden.yml
- examples/remote-sources/garden.yml
- examples/tasks/garden.yml
- examples/templated-k8s-container/project.garden.yml
- examples/vote-helm/garden.yml
- examples/vote/garden.yml
- scripts/encrypt-file.ts
> chore: update ci cluster context

- core/src/cli/cli.ts
- core/src/commands/enterprise/helpers.ts
- core/src/commands/enterprise/secrets/secrets-create.ts
- core/src/commands/enterprise/secrets/secrets-list.ts
- core/src/commands/enterprise/users/users-list.ts
- core/src/enterprise/api.ts
- core/src/garden.ts
Prints the namespace Garden is running in in the header and the URL to the project in Garden Cloud if applicable.
Fixes #
> improvement: log namespace and cloud URL

- core/src/enterprise/api.ts
Adds a `x-core-version` header to all the Garden Cloud HTTP requests.
Fixes #
> chore(enterprise): add Core version to Cloud API http request headers

- core/src/cli/cli.ts
- docs/guides/in-cluster-building.md
> fix: fix namespace log line

- examples/ambassador/node-service/Dockerfile
- examples/build-dependencies/frontend/Dockerfile
- examples/demo-project-start/frontend/Dockerfile
- examples/demo-project/frontend/Dockerfile
- examples/deployment-strategies/frontend/Dockerfile
- examples/disabled-configs/frontend/Dockerfile
- examples/gatsby-hot-reload/Dockerfile
- examples/gke/frontend/Dockerfile
- examples/hadolint/frontend/Dockerfile
- examples/hot-reload-k8s/node-service/Dockerfile
- examples/hot-reload-post-sync-command/node-service/Dockerfile
- examples/hot-reload/node-service/Dockerfile
- examples/kaniko/frontend/Dockerfile
- examples/kubernetes-secrets/frontend/Dockerfile
- examples/local-tls/services/node-service/Dockerfile
- examples/openfaas/services/hello-container/Dockerfile
- examples/project-variables/frontend/Dockerfile
- examples/remote-k8s/services/node-service/Dockerfile
- examples/remote-sources/garden.yml
- examples/tasks/hello/Dockerfile
- examples/terraform-gke/frontend/Dockerfile
- examples/vote-helm/result-image/Dockerfile
- examples/vote-helm/vote-image/Dockerfile
- examples/vote/result/Dockerfile
- examples/vote/vote/Dockerfile
- static/local-gcf-container/Dockerfile
The node base images we were using in our example projects were getting quite old (mostly using node 9), so it was time for an update.
> chore(examples): update node base images

- core/src/plugins/kubernetes/mutagen.ts
This reduces the visual noise during long sync sessions.
> fix(dev-mode): reuse sync log line

- .circleci/config.yml
- core/test/integ/src/plugins/kubernetes/run.ts
This integ test case is no longer necessary after the recent changes to our pod runner.
> chore(tests): remove obsolete integ test case

- README.md
Fixes README spelling and formatting.
It appears that I cannot add reviewers to the PR, so I will mention @thsig @edvald here in the description. 😄
> docs: README spelling and spacing

- docs/guides/in-cluster-building.md
It adds documentation on how to use Google Artifacts Registry as a deployment registry for in-cluster building.
Fixes #
> docs: add docs about google artifact registry

- core/src/plugins/kubernetes/util.ts
When provided, we now use the custom namespace defined in `module.spec.namespace` for `helm` and `kubernetes` modules when getting the module's `serviceResource`.
> fix(k8s): use module ns in getServiceResource

- core/src/cli/cli.ts
- core/src/enterprise/session-lifecycle.ts
This is done in preparation for rolling out Stack Streams.
> feat(cloud): register session with API

- core/src/commands/dev.ts
> fix(core): ensure we print dev command banner at top

- core/src/plugins/exec.ts
- core/test/unit/src/plugins/exec.ts
> fix(exec): statusCommand output not being respected

- core/src/plugins/kubernetes/helm/logs.ts
We now no longer require building/preparing Helm modules ahead of streaming logs from them.
This was done by using the remote resources for the chart instead of relying on local manifests.
Fixes an issue where Helm log streaming would fail if the charts hadn't already been fetched locally.
> fix(helm): more robust log streaming

- core/src/commands/cloud/groups/groups.ts
- core/src/commands/cloud/secrets/secrets-list.ts
- core/src/commands/cloud/users/users-list.ts
- core/src/commands/login.ts
- core/test/unit/src/commands/login.ts
- core/test/unit/src/commands/logout.ts
> Paginate secrets list

- core/src/plugins/kubernetes/run.ts
Exclude `startupProbes` from task and test pods.
Fixes #
> chore(tasks): remove startupProbes from task and test pods

- docs/using-garden/tasks.md
- docs/using-garden/tests.md
It adds some docs on the pod spec of test and task pods for Kubernetes and Helm modules.
Fixes #
> docs: health checks in tests and tasks in kubernetes and helm modules

- docs/advanced/README.md
- docs/advanced/cert-manager-integration.md
- docs/advanced/rbac-config.md
- docs/advanced/terraform.md
- docs/advanced/using-remote-sources.md
This is essentially copied verbatim from an internal document on the
topic.
Fixes #
> docs: add minimal RBAC config for k8s plugin

- core/src/template-string/parser.pegjs
- core/test/unit/src/template-string.ts
> fix(template): template string in helper arguments weren't resolved

- docs/basics/how-garden-works.md
**What this PR does / why we need it**: Fixes a small typo in the docs
Fixes #
> fix(docs): fix a typo in the how garden works doc

- docs/basics/stack-graph.md
- docs/getting-started/2-initialize-a-project.md
- docs/guides/code-synchronization-dev-mode.md
- docs/guides/container-modules.md
- docs/guides/hot-reload.md
- docs/guides/in-cluster-building.md
- docs/guides/using-garden-in-ci.md
- docs/welcome.md
**What this PR does / why we need it**: Fixes several typos in the docs
I was skimming the docs and fixed some typos along the way.
> fix(docs): fix a few typos

- core/src/process.ts
When a task fails during a watch-mode command's execution, the footer now indicates that one or more tasks failed (instead of saying "Waiting for code changes...").
This has been asked for by several users, who felt that indicating an error in the footer makes it clearer that something went wrong as the tasks were being processed.
> improvement(core): show error in watch footer

- core/src/plugins/kubernetes/helm/helm-cli.ts
> improve(k8s): update Helm to v3.7.2

- core/src/plugins/kubernetes/kubectl.ts
This is to get in an upstream bug fix. Should work the same as before.
> improve(k8s): update kubectl to v1.23.3

- core/src/plugins/kubernetes/port-forward.ts
Use `getModuleNamespace` to retrieve namespace name in port forwarding for Kubernetes module.
Fixes #2764
> fix(k8s): use namespace from module when port forwarding

- .circleci/config.yml
- core/src/plugins/kubernetes/kubernetes-module/common.ts
- core/src/plugins/kubernetes/kubernetes-module/config.ts
- core/src/plugins/kubernetes/kubernetes-module/kustomize.ts
- core/src/plugins/kubernetes/kubernetes.ts
- core/test/helpers.ts
- core/test/integ/src/plugins/kubernetes/kubernetes-module/common.ts
- docs/reference/module-types/kubernetes.md
- examples/kustomize/README.md
- examples/kustomize/helloWorld/README.md
- examples/kustomize/helloWorld/configMap.yaml
- examples/kustomize/helloWorld/deployment.yaml
- examples/kustomize/helloWorld/garden.yml
- examples/kustomize/helloWorld/kustomization.yaml
- examples/kustomize/helloWorld/service.yaml
- examples/kustomize/ldap/README.md
- examples/kustomize/ldap/base/deployment.yaml
- examples/kustomize/ldap/base/env.startup.txt
- examples/kustomize/ldap/base/kustomization.yaml
- examples/kustomize/ldap/base/service.yaml
- examples/kustomize/ldap/garden.yml
- examples/kustomize/ldap/overlays/local/config.env
- examples/kustomize/ldap/overlays/local/deployment.yaml
- examples/kustomize/ldap/overlays/local/kustomization.yaml
- examples/kustomize/ldap/overlays/testing/deployment.yaml
- examples/kustomize/ldap/overlays/testing/kustomization.yaml
- examples/kustomize/project.garden.yml
See the added `kustomize` example project and reference for usage.
Closes #1192
> feat(k8s): support kustomize on kubernetes modules

- docs/using-garden/module-templates.md
Small missing text from a module invocation in the docs.
N/A
I understand that the docs are auto-generated from some sources but can't see the source that drives this particular file... please let me know if I edited the wrong one.
> Ensure the type field contains 'templated' in a template invocation.

- docs/advanced/custom-commands.md
Fixes a typo in the custom commands guide (a leftover half-sentence in an early paragraph) that slipped through during code review.
> chore(docs): fix to custom commands guide

- .circleci/config.yml
- bin/garden
- cli/bin/garden
- cli/bin/garden-debug
- cli/package.json
- cli/patches/pkg+5.5.2.patch
- core/test/unit/src/vcs/git.ts
- e2e/run-garden.ts
- e2e/test/pre-release.ts
- images/circleci-runner/Dockerfile
- images/circleci-runner/garden.yml
- support/alpine-builder.Dockerfile
- yarn.lock
This is a precursor to updating to Node.js 14 and adding proper support for ARM64 builds.
No rush to merge this ahead of tomorrow's release btw @thsig.
> improve(build): update pkg version and sign mac executables

- cli/tsconfig.json
- e2e/tsconfig.json
Missed a dependency declaration in the tsconfigs.
> chore(dev): yarn dev wasn't building plugins

- core/src/constants.ts
- core/src/garden.ts
- core/src/plugins/kubernetes/mutagen.ts
Co-authored-by: Thorarinn Sigurdsson <thorarinnsigurdsson@gmail.com>
This PR fixes build errors on arm64 machines.
> chore: fixed build errors for arm64 arch

- core/src/commands/base.ts
- core/src/constants.ts
- core/src/util/util.ts
Added missing `await` for user prompt.
Fixes #2826
> fix(core): add missing await for user prompt

- core/src/events.ts
- core/src/logger/log-entry.ts
- core/src/plugins/kubernetes/container/deployment.ts
- core/src/task-graph.ts
- core/test/unit/src/task-graph.ts
This attempts to fix a user reported memory error. We do not have a reliable
repro for this, so we're flying a little blind, but the fix tracks with
reported logs and backtraces and some prior experience with potential
recursion loops.
> fix(core): fix infinite recursion that could cause OOM error

- docs/advanced/using-remote-sources.md
> fix(docs): fix broken anchor link

- CONTRIBUTING.md
This PR adds some release-related corrections to the contributing guide.
> docs: updated release instructions

- core/package.json
- yarn.lock
Update the `dotenv` lib because the most recent versions include support for [multi-line env vars](https://github.com/motdotla/dotenv#multiline-values) which is e.g. useful when creating secrets from file. 
Fixes #
> chore(core): update dotenv dependency

- core/src/cloud/api.ts
Users have been reporting the following error when using Garden:
error: unhandledRejection: The `onCancel` handler was attached after
the promise settled.
I haven't been able to reproduce it but apparently it's an issue with
got. See: https://github.com/sindresorhus/got/issues/1489
This commit _attempts_ to fix it by implementing the workaround
suggested here:
https://github.com/sindresorhus/got/issues/1489#issuecomment-805485731
Some users have reported that it fixes the issue, others that it
doesn't. Since I haven't been able to repro myself this is sort of a
best effort thing. Hopefully it does the trick.
Fixes #
> fix(core): attempt to fix unhandled promise rejection from got

- .github/workflows/update-homebrew-test.yml
- .github/workflows/update-homebrew.yml
> Replace homebrew action test

- .github/workflows/npm-release.yml
The GitHub action that updates our Core NPM package has been failing for a bit (probably since we upgraded to Node 14). This PR fixes that.
> chore(release): use Node 14 in npm release action

- docs/README.md
- docs/guides/namespaces.md
- adds a guide on how to use namespaces
- n/a
> docs: add namespace guide

- core/src/commands/get/get-modules.ts
- core/src/commands/scan.ts
- core/src/logger/renderers.ts
- core/src/logger/util.ts
- core/src/types/module.ts
- core/test/unit/src/commands/get/get-modules.ts
Basically we were normalizing and serializing a recursive data structure, which could end up with a massive amount of data, which could kill the process in certain scenarios.
> fix(cli): potential OOM error during module and error serialization

- core/src/plugins/kubernetes/container/ingress.ts
- core/src/plugins/kubernetes/init.ts
- core/test/unit/src/plugins/kubernetes/init.ts
Follow-up to #290
* make message more informative
* don't spam the error
* don't show when ingressClass has not been configured
* adds tests
Still shows up twice when the very first garden initialization is done as all the plugins are initialized twice for some reason on the very first init
> fix(core): improve ingress warning

- core/src/resolve-module.ts
This especially improves resolution for large graphs, by improving concurrency
during the resolution process.
> improve(core): more efficient module resolution

- docs/using-garden/using-the-cli.md
- docs/using-garden/variables-and-templating.md
**What this PR does / why we need it**: minor documentation fixes
> docs: fix minor mistakes

- .chglog/config.yml
What it says on the can: `remove 'refactor' commits from CHANGELOG`
Fixes #
> chore: remove 'refactor' commits from CHANGELOG

- core/src/analytics/analytics.ts
- core/src/cloud/api.ts
- core/src/config-store.ts
- core/test/unit/src/analytics/analytics.ts
- core/test/unit/src/cli/cli.ts
Add support for additional metadata for cloud users. Associates cloud user metadata with analytics.
Fixes #
> feat: analytics with cloud user metadata

- CONTRIBUTING.md
- scripts/show-contributors.sh
- scripts/test-release.sh
This PR attempts to make the release guide a bit more clear.
Fixes #
> chore: updated release instructions

- core/src/analytics/analytics.ts
- core/src/cloud/api.ts
- core/src/config-store.ts
Fixes an issue with analytics when it was not possible to retrieve the cloud profile.
Fixes #
> fix: handle unknown cloud profile

- core/src/plugins/kubernetes/helm/common.ts
- core/src/plugins/kubernetes/helm/deployment.ts
> fix: allow garden helm plugin to install crds

- core/src/plugins/kubernetes/container/build/buildkit.ts
- core/src/plugins/kubernetes/container/build/common.ts
- core/src/plugins/kubernetes/container/build/kaniko.ts
- core/test/unit/src/logger/log-entry.ts
- core/test/unit/src/logger/logger.ts
- core/test/unit/src/logger/renderers.ts
- core/test/unit/src/logger/writers/basic-terminal-writer.ts
- core/test/unit/src/logger/writers/fancy-terminal-writer.ts
- core/test/unit/src/logger/writers/file-writer.ts
- core/test/unit/src/logger/writers/json-terminal-writer.ts
adds imagePullSecrets to kaniko pods and garden-util deployments
Fixes #
> fix: add imagePullSecrets

- core/src/process.ts
this addresses a few issues introduced in #2995
* improve logging (see pic below)
* clear cache for each cloud action (see commit for more detailed explanation)
* a few minor things
now looks like this:
> Interactivity improvements

- core/test/data/test-projects/helm/api-image/Dockerfile
- core/test/data/test-projects/helm/api-image/app.py
- core/test/data/test-projects/kubernetes-module/api-image/Dockerfile
- core/test/data/test-projects/kubernetes-module/api-image/app.py
This PR replaces the ancient Python 2.7 with the latest stable 3.10 version in the test projects. It also makes the code-style more Pythonic.
Fixes #
> chore(tests): used python 3 in test projects

- core/src/commands/get/get-workflows.ts
- core/src/commands/get/get.ts
- core/src/commands/helpers.ts
- core/test/unit/src/commands/get/get-workflows.ts
- docs/reference/commands.md
> feat: add get workflows command

- core/src/plugins/kubernetes/util.ts
- core/test/integ/src/plugins/kubernetes/util.ts
> test: post-merge fixes in tests

- CONTRIBUTING.md
- scripts/draft-release-notes.ts
This PR helps to (semi-)automate the release notes preparation process. It generates a draft that still should be edited manually. But the new draft generating script reduces the amount of manual work.
Fixes #
> chore: automated release notes draft generation

- core/src/plugins/kubernetes/kubernetes.ts
- core/src/plugins/kubernetes/logs.ts
- scripts/install-osx-dependencies.sh
This PR removes `stern` tools from the `kubernetes` plugin.
Fixes #
> refactor(k8s): remove `stern` from k8s plugin's tools

- core/src/config/template-contexts/project.ts
- core/test/unit/src/config/template-contexts/module.ts
- core/test/unit/src/config/template-contexts/project.ts
- core/test/unit/src/config/template-contexts/workflow.ts
- docs/reference/template-strings/custom-commands.md
- docs/reference/template-strings/environments.md
- docs/reference/template-strings/modules.md
- docs/reference/template-strings/project-outputs.md
- docs/reference/template-strings/projects.md
- docs/reference/template-strings/providers.md
- docs/reference/template-strings/remote-sources.md
- docs/reference/template-strings/workflows.md
This PR adds `local.arch` template variable.
Fixes #3086
> feat: `local.arch` template variable

- CONTRIBUTING.md
- scripts/draft-release-notes.ts
- scripts/test-release.sh
Some fixes in the release documentation and scripts.
Fixes #
> Release docs fixes

- core/src/cli/cli.ts
- core/src/events.ts
Adds a new cloud event including more context related to the running command.
Fixes #
> chore: added a new cloud event with context of a command

- core/src/analytics/analytics.ts
- Updates the link in the analytics message shown on first run
- Always show message on first run
Fixes #
> chore: update analytics msg link

- .circleci/config.yml
- scripts/build-containers.sh
- scripts/push-containers.sh
- support/aws-gcloud-azure.Dockerfile
- support/aws-gcloud.Dockerfile
- support/full.Dockerfile
I think this still qualifies as a breaking change
> Merge separate Garden Core docker repos into one with multiple different tags

- SECURITY.md
Adding a SECURITY.md describing how to do responsible security disclosure.
Fixes #
> chore: adding a security.md

- core/test/unit/src/config/template-contexts/module.ts
- core/test/unit/src/enterprise/event-handlers.ts
- core/test/unit/src/types/service.ts
- core/test/unit/src/types/test.ts
fix build issues in a couple of unit test modules.
> Graph v2 build tests albert

- core/test/unit/src/plugins/container/container.ts
- core/test/unit/src/plugins/container/helpers.ts
- core/test/unit/src/plugins/exec/exec.ts
- core/test/unit/src/plugins/kubernetes/container/build/buildkit.ts
- core/test/unit/src/plugins/kubernetes/container/build/kaniko.ts
- core/test/unit/src/plugins/kubernetes/container/service.ts
- core/test/unit/src/plugins/kubernetes/dev-mode.ts
- core/test/unit/src/plugins/kubernetes/init.ts
- core/test/unit/src/plugins/kubernetes/port-forward.ts
fix /plugins path build issues
> Graph v2 build tests /plugins

- core/test/unit/src/build-staging/build-staging.ts
This PR fixes compilation errors in `build-staging.ts` unit tests.
Fixes #
> test: fixed compilation errors in build-staging.ts

- core/src/runtime-context.ts
- core/test/unit/src/runtime-context.ts
This PR fixes compilation errors in `runtime-context.ts` unit tests.
Fixes #
> test: fixed compilation errors in runtime-context.ts

- core/test/unit/src/graph/solver.ts
Left a TODO comment to implement equivalent tests for the new graph.
Fixes #
> test: muted all tests for the old task-graph

- core/test/unit/src/tasks/deploy.ts
- core/test/unit/src/tasks/get-service-status.ts
- core/test/unit/src/tasks/run.ts
> test: fixed compilation errors in `tasks` unit tests

- core/test/unit/src/config-graph.ts
> test: fixed compilation errors in config-graph.ts

- core/test/unit/src/garden.ts
> test: fixed compilation errors in garden.ts

- core/test/unit/src/commands/run/run-workflow.ts
> test: fixed compilation errors in commands/run/run-workflow.ts

- core/test/unit/src/actions.ts
Fixes #
A quick iteration to fix easily-fixable errors. The rest compilation errors will be fixed in a separate PR.
> test: partially fixed errors in actions.ts

- .github/workflows/scorecards.yml
This PR fixes the syntax of the scorecard.yml workflow.
sorry for not detecting this one upfront.
Fixes #
> ci: fix yaml syntax

- core/test/unit/src/actions.ts
Continuation of https://github.com/garden-io/garden/pull/3143
Still a partial fix.
Fixes #
Another iteration will happen as a new PR.
> test: partially fixed compilation errors in actions.ts

- core/test/integ/src/plugins/kubernetes/dev-mode.ts
- core/test/integ/src/plugins/kubernetes/local-mode.ts
> test: fixed compilation errors for dev and local mode

- core/test/integ/src/plugins/kubernetes/commands/pull-image.ts
> test: fixed compilation errors in kubernetes/commands

- core/test/integ/src/plugins/kubernetes/helm/common.ts
- core/test/integ/src/plugins/kubernetes/helm/deployment.ts
- core/test/integ/src/plugins/kubernetes/helm/run.ts
- core/test/integ/src/plugins/kubernetes/helm/test.ts
> test: fixed compilation errors in helm

- core/test/integ/src/plugins/kubernetes/container/build/build.ts
- core/test/integ/src/plugins/kubernetes/container/container.ts
- core/test/integ/src/plugins/kubernetes/container/deployment.ts
- core/test/integ/src/plugins/kubernetes/container/ingress.ts
- core/test/integ/src/plugins/kubernetes/container/logs.ts
- core/test/integ/src/plugins/kubernetes/container/run.ts
There is still one error in the `container/ingress.ts`. One helper method must be fixed. This will be done a bit later.
Fixes #
> Graph v2 fix kubernetes/container/** errors

- core/test/integ/src/plugins/kubernetes/kubernetes-module/common.ts
- core/test/integ/src/plugins/kubernetes/kubernetes-module/handlers.ts
- core/test/integ/src/plugins/kubernetes/kubernetes-module/run.ts
- core/test/integ/src/plugins/kubernetes/kubernetes-module/test.ts
> Graph v2 fix k8s module errors

- core/test/unit/src/enterprise/event-handlers.ts
> Graph v2 tests event handler quickfix

- core/test/unit/src/config/template-contexts/module.ts
> Graph v2: removed leftovers of runtime-context 

- core/test/integ/src/plugins/hadolint/hadolint.ts
- core/test/integ/src/plugins/kubernetes/system.ts
- core/test/integ/src/plugins/kubernetes/util.ts
- core/test/integ/src/plugins/kubernetes/volume/configmap.ts
- core/test/integ/src/plugins/kubernetes/volume/persistentvolumeclaim.ts
- core/test/unit/src/outputs.ts
fix output.ts, hadolint and kubernetes/util build issues
> SGv2: output.ts, hadolint and kubernetes/util build issues

- core/test/integ/src/plugins/kubernetes/run.ts
I think this is the last one, right?
> test: fix integ plugins/kubernetes/run.ts build issues

- docs/README.md
small leftover from https://github.com/garden-io/garden/pull/3116
> docs: re-render docs

- core/test/helpers.ts
- core/test/unit/src/actions.ts
Continuation of https://github.com/garden-io/garden/pull/3147.
Fixes #
> Graph v2 fix actions unit tests

- core/test/unit/src/tasks/deploy.ts
> test: use skipRuntimeDependencies flag in deploy task tests

- core/test/helpers.ts
- core/test/unit/src/build-staging/build-staging.ts
- core/test/unit/src/cli/helpers.ts
- core/test/unit/src/config/common.ts
- core/test/unit/src/plugins/kubernetes/dev-mode.ts
- core/test/unit/src/util/streams.ts
This PR introduces a new helper function to examine expected error messages with less strict criteria.
The PR also fixes some assertions in the tests.
Fixes #
> test: less strict assertions in error messages

- core/src/plugin/action-types.ts
- core/src/plugin/handlers/module/convert.ts
- core/src/plugin/module-types.ts
- core/test/helpers.ts
> Graph v2 fix config schemas

- core/src/commands/base.ts
- core/src/config/group.ts
- core/src/garden.ts
- core/src/graph/config-graph.ts
- core/src/graph/results.ts
- core/src/graph/solver.ts
- core/src/plugin/handlers/module/convert.ts
- core/src/plugins/exec/exec.ts
- core/src/resolve-module.ts
- core/src/router/base.ts
- core/src/tasks/resolve-provider.ts
- core/test/helpers.ts
> Misc graph-v2 fixes

- plugins/jib/gradle.ts
>  improvement: upgraded gradle version to 7.5.1

- docs/reference/module-types/jib-container.md
- plugins/jib/index.ts
- plugins/jib/maven.ts
- plugins/jib/util.ts
This PR adds an ability to use a custom Maven binary in jib-modules.
Fixes #
> improvement: configurable maven binary

- core/test/unit/src/build-staging/helpers.ts
Yet another batch of fixed error message assertions.
Fixes #
> test: less strict assertions for error messages

- core/src/graph/actions.ts
> fix: pick action kind-specific validation schema

- core/src/build-staging/build-staging.ts
- core/test/unit/src/build-staging/build-staging.ts
> Partial fixes for build-staging.ts unit tests

- plugins/jib/gradle.ts
- plugins/jib/openjdk.ts
Also resolved some obsolete fixme-comments.
Fixes #
> chore(jib): explicit types for plugin tool specs

- core/src/plugin/handlers/module/convert.ts
- core/src/plugins/exec/exec.ts
- core/src/resolve-module.ts
> fix: empty action group when converting basic exec module

- core/src/actions/base.ts
- docs/reference/action-types/Deploy/container.md
- docs/reference/action-types/Deploy/exec.md
- docs/reference/action-types/Deploy/helm.md
- docs/reference/action-types/Deploy/kubernetes.md
- docs/reference/action-types/Deploy/pulumi.md
- docs/reference/action-types/Deploy/terraform.md
- docs/reference/action-types/Run/container.md
- docs/reference/action-types/Run/exec.md
- docs/reference/action-types/Run/kubernetes-pod.md
- docs/reference/action-types/Test/conftest-helm.md
- docs/reference/action-types/Test/conftest.md
- docs/reference/action-types/Test/container.md
- docs/reference/action-types/Test/exec.md
- docs/reference/action-types/Test/hadolint.md
- docs/reference/action-types/Test/kubernetes-pod.md
> fix: corrected `varfiles` definition in the base action config schema

- core/src/util/testing.ts
- core/test/unit/src/cli/helpers.ts
> refactor(test): multi-string error message matching

- core/test/unit/src/garden.ts
> Graph v2 refactor error expectations in `graph.ts` unit tests

- core/test/unit/src/commands/get/get-run-result.ts
- core/test/unit/src/commands/get/get-test-result.ts
- core/test/unit/src/commands/run/run.ts
> Graph v2 fix some commands unit tests

- core/test/unit/src/garden.ts
> Graph v2 fixed a few garden unit tests

- core/src/graph/common.ts
- core/src/graph/modules.ts
Fixed a spurious circular dependency error that was caused by a type problem in the circular dependency detection logic in the module resolution flow.
> fix: fix typing problems in circular dep logic

- core/src/config/base.ts
- core/test/helpers.ts
- core/test/unit/src/config/base.ts
- core/test/unit/src/plugins/container/helpers.ts
- core/test/unit/src/types/test.ts
please see individual commits for more details
> test fixes sgv2

- core/test/unit/src/enterprise/event-handlers.ts
> test: fixed most of the event handlers tests

- core/test/helpers.ts
- core/test/unit/src/commands/run/run-deploy.ts
- core/test/unit/src/commands/run/run-run.ts
- core/test/unit/src/commands/run/run-test.ts
- core/test/unit/src/commands/run/run-workflow.ts
- core/test/unit/src/garden.ts
Used `expectError` instead.
Fixes #
> [SGv2] Some fixes and refactoring in tests

- docs/README.md
leftover docs render from #2799
> docs: render new docs

- plugins/terraform/cli.ts
Add latest stable terraform release to our selection of tools.
**BREAKING CHANGE**: Change default terraform version from `0.13.3` to `1.2.9`
Fixes #3209
> improvement: upgraded default terraform tool version to 1.2.9

- docs/reference/providers/terraform.md
This patches https://github.com/garden-io/garden/pull/3220
Fixes #
> docs: re-generated terraform docs

- core/test/unit/src/garden.ts
This fixes some unit tests in `garden.ts`.
Fixes #
> test: fixed module converters' definitions

- core/src/util/util.ts
Fixes an issue where Garden would crash on Intel macs. This is a patch for https://github.com/garden-io/garden/pull/3185.
Closes https://github.com/garden-io/garden/issues/3166
> fix(core): fix Rosetta detection logic for OSX

- core/src/commands/update-remote/all.ts
- core/src/commands/update-remote/modules.ts
- core/src/commands/update-remote/sources.ts
- core/src/vcs/git.ts
- core/src/vcs/vcs.ts
- core/test/unit/src/commands/update-remote.ts
- core/test/unit/src/vcs/git.ts
- docs/reference/commands.md
This adds the ability for git pulls to happen in parallel. For projects with large amounts of repositories, it can start taking a _long_ time to update all repos.
> feat: add option to run git pulls in parallel

- core/src/graph/results.ts
- core/src/tasks/resolve-provider.ts
> fix: fixed task dependencies resolution

- core/src/graph/actions.ts
- core/src/plugins/container/config.ts
- core/src/plugins/container/container.ts
- core/src/plugins/exec/config.ts
- core/src/plugins/exec/exec.ts
> Graph v2 fix mini-pack

- core/test/unit/src/commands/run/run-build.ts
Those should be the same as module names
Fixes #
> test: fixed build action names

- core/src/actions/base.ts
This fixes linked module unit test in `get-linked-repos.ts`.
Fixes #
> Graph v2 fix `get-linked-repos.ts` unit tests

- core/src/config/module.ts
- core/src/docs/config.ts
- docs/README.md
- docs/reference/commands.md
- docs/reference/module-template-config.md
- docs/reference/module-types/configmap.md
- docs/reference/module-types/conftest.md
- docs/reference/module-types/container.md
- docs/reference/module-types/exec.md
- docs/reference/module-types/hadolint.md
- docs/reference/module-types/helm.md
- docs/reference/module-types/jib-container.md
- docs/reference/module-types/kubernetes.md
- docs/reference/module-types/maven-container.md
- docs/reference/module-types/openfaas.md
- docs/reference/module-types/persistentvolumeclaim.md
- docs/reference/module-types/pulumi.md
- docs/reference/module-types/templated.md
- docs/reference/module-types/terraform.md
- docs/reference/workflow-config.md
> fix: fixed template strings rendering in docs generator

- .github/PULL_REQUEST_TEMPLATE.md
> chore: updated list of recommended reviewers in PR template

- core/src/config/validation.ts
- core/src/graph/nodes.ts
- core/src/plugins/container/config.ts
- core/src/plugins/container/container.ts
- core/src/plugins/container/moduleConfig.ts
- core/src/plugins/exec/exec.ts
- core/src/plugins/hadolint/hadolint.ts
- core/src/plugins/kubernetes/helm/handlers.ts
- core/src/plugins/kubernetes/kubernetes-type/config.ts
- core/src/plugins/kubernetes/kubernetes-type/handlers.ts
- core/src/plugins/kubernetes/kubernetes-type/module-config.ts
- core/src/plugins/kubernetes/volumes/configmap.ts
- core/src/plugins/kubernetes/volumes/persistentvolumeclaim.ts
- core/src/plugins/templated.ts
- core/test/helpers.ts
- plugins/jib/index.ts
- plugins/pulumi/config.ts
- plugins/pulumi/index.ts
- plugins/terraform/index.ts
> Graph v2 fix some fixes in schemas and test configs

- core/src/template-string/template-string.ts
- core/src/vcs/vcs.ts
- core/test/unit/src/vcs/vcs.ts
TODOs:
* ~fix the assertion in the failing unit test~
Fixes #
> Graph v2 partial fixes in `VcsHandler` unit tests

- core/src/graph/actions.ts
- core/src/graph/config-graph.ts
- core/src/graph/solver.ts
- core/src/plugin/module-types.ts
- core/src/plugins/container/config.ts
- core/src/plugins/container/container.ts
- core/src/plugins/container/moduleConfig.ts
- core/src/plugins/exec/exec.ts
- core/src/resolve-module.ts
- core/src/router/base.ts
- core/src/router/module.ts
- core/src/tasks/resolve-action.ts
- core/test/helpers.ts
- core/test/unit/src/actions.ts
> Couple of fixes for graph v2

- docs/reference/action-types/Deploy/container.md
- docs/reference/action-types/Deploy/kubernetes.md
- docs/reference/action-types/Run/container.md
- docs/reference/action-types/Test/container.md
- docs/reference/module-types/container.md
- docs/reference/module-types/exec.md
- docs/reference/module-types/jib-container.md
- docs/reference/module-types/kubernetes.md
> docs: regenerated docs

- core/src/actions/base.ts
- core/src/actions/build.ts
- core/src/actions/deploy.ts
- core/src/actions/run.ts
- core/src/actions/test.ts
- core/src/commands/get/get-config.ts
- core/src/docs/action-type.ts
- core/src/graph/actions.ts
- core/src/plugin/handlers/module/convert.ts
- docs/reference/commands.md
> fix: fixed `actionConfigs` schema definition

- core/src/actions/base.ts
- core/src/actions/types.ts
- core/src/events.ts
- core/src/graph/actions.ts
- core/src/resolve-module.ts
- core/src/router/build.ts
- core/src/router/deploy.ts
- core/src/router/run.ts
- core/src/router/test.ts
- core/test/unit/src/actions.ts
- docs/reference/action-types/Build/container.md
- docs/reference/action-types/Build/exec.md
- docs/reference/action-types/Build/jib-container.md
- docs/reference/action-types/Deploy/container.md
- docs/reference/action-types/Deploy/kubernetes.md
- docs/reference/action-types/Run/container.md
- docs/reference/action-types/Test/container.md
- docs/reference/commands.md
- docs/reference/module-types/container.md
- docs/reference/module-types/exec.md
- docs/reference/module-types/jib-container.md
- docs/reference/module-types/kubernetes.md
please see individual commits for more details :)
Please note that some changes include logic fixes in addition to tests
> SHV2: Fix some action tests, some schemas and some logic

- scripts/draft-release-notes.ts
This PR makes the release notes draft editing easier.
Fixes #
> chore: save release notes draft as .md file

- CONTRIBUTING.md
- core/README.md
> chore(docs): updated `CONTRIBUTING.md` guide

- core/src/actions/base.ts
- core/src/graph/actions.ts
- core/src/resolve-module.ts
- core/test/unit/src/actions.ts
Fix some logic and some tests, mostly related to actions and module resolution
Please see individual commits for more detail.
> Fix more action things

- core/src/plugins/kubernetes/config.ts
- core/src/plugins/kubernetes/container/build/buildkit.ts
- docs/reference/providers/kubernetes.md
- docs/reference/providers/local-kubernetes.md
Allows adding kubernetes tolerations to cluster-buildkit deployments
> Allow adding tolerations to cluster buildkit deployments

- core/src/commands/get/get-run-result.ts
- core/src/router/base.ts
- core/src/router/run.ts
- core/src/util/artifacts.ts
- core/test/unit/src/actions.ts
- core/test/unit/src/commands/get/get-run-result.ts
- core/test/unit/src/util/artifacts.ts
> SGV2 - Fix more actions tests 

- .circleci/config.yml
- core/test/unit/src/cli/cli.ts
- package.json
- scripts/reportTestResultstToSlack.ts
Report the number of tests passing to slack
This pr can be reverted once all the tests are green
> report sgv2 unit test numbers to slack

- core/src/plugins/container/config.ts
- core/src/plugins/kubernetes/container/deployment.ts
- core/src/plugins/local/local-google-cloud-functions.ts
- core/test/integ/src/plugins/kubernetes/container/ingress.ts
- core/test/unit/src/commands/get/get-config.ts
- core/test/unit/src/garden.ts
- core/test/unit/src/plugins/container/container.ts
- core/test/unit/src/vcs/vcs.ts
- docs/reference/module-types/container.md
- docs/reference/module-types/jib-container.md
- docs/reference/module-types/maven-container.md
This PR makes the deployment strategy configurable for `container` module type.
Fixes #3237
Please check my comments in the change set.
> improvement(container): configurable deployment strategy 

- README.md
- RELEASE_PROCESS.md
- core/src/commands/get/get-debug-info.ts
- docs/advanced/cert-manager-integration.md
- docs/guides/cloud-provider-setup.md
- docs/guides/migrating-from-docker-compose.md
- docs/guides/remote-kubernetes.md
- docs/misc/faq.md
- docs/welcome.md
We're migrating our community from the private Kubernetes Slack workspace to a Discord server that we own.
This commit updates links in docs and code accordingly.
See also this Slack announcement for details:
-------------------------------------------------
In an effort to streamline our centers of community action, we at garden.io have decided to sunset our Discourse and Slack channels with a one month notice from today.
Why? Two reasons:
1. It's time to leave the nest.
Our Slack channel is under the auspices of the Kubernetes moderation team and we couldn't be more grateful for their efforts to make the Slack the warm and welcoming place it is. As we grow and add open source users it's important we have all the tools we need to (kindly) moderate our community and Discord simply has a …
> docs: use Discord instead of Slack for community links

- core/src/plugins/kubernetes/local-mode.ts
- examples/local-mode/backend-1/garden.yml
This PR fixes some issues with a reverse proxy container startup in local mode. See the individual commits for details.
Fixes #3284
> fix(local-mode): fixed some bugs in local mode config

- core/src/plugins/kubernetes/local-mode.ts
- docs/guides/running-service-in-local-mode.md
> fix(local-mode): disabled startup probes for proxy container

- CHANGELOG.md
> chore: fixed list of breaking changes in 0.12.45 changelog

- core/src/template-string/template-string.ts
> chore: removed duplicate string from the type definition

- core/test/unit/src/enterprise/event-handlers.ts
Fixed test names in input data and assertions.
Fixes #
> test: fixed tests in `event-handlers.ts`

- RELEASE_PROCESS.md
Corrected file extension of the draft release notes file.
Fixes #
> chore: updated release process guide

- docs/reference/action-types/Build/jib-container.md
- docs/reference/module-types/jib-container.md
- docs/reference/providers/pulumi.md
- docs/reference/providers/terraform.md
- plugins/jib/index.ts
- plugins/pulumi/commands.ts
Fixed some post-rebase type errors in the Pulumi and Jib plugins.
Commented out a bit of logic for one of the Pulumi plugin commands which I'll re-enable and test once 0.13 is stable enough.
> Graph v2 fix plugin build errors

- core/test/unit/src/build-staging/build-staging.ts
Fix the one failing build staging test.
Here's the line from the main branch.
https://github.com/garden-io/garden/blob/main/core/test/unit/src/build-staging/build-staging.ts#L490
These prs are starting to pile on each other
> Sgv2 fix build-staging test

- core/src/graph/modules.ts
- core/test/helpers.ts
- core/test/unit/src/commands/build.ts
> Graph v2 use exec handlers for test plugin + some Build command test fixes

- .circleci/config.yml
We disabled edge releases on merges to `main` back in September, since we were concerned about notification spam. This seems to have been unnecessary, so here we re-enable edge releases.
> chore: re-enable edge releases

- core/test/unit/src/commands/build.ts
Fixed assertions for module versions.
Fixes #
> SGV2: fixed single test for build command

- core/src/plugins/kubernetes/logs.ts
* Used new repo link for `stern` tool
* Updated `stern` to the latest release version
Fixes #3347
> fix(plugins): fixed `stern` repo link and updated version

- core/src/plugins/kubernetes/logs.ts
NOTE! In 0.13 `stern` will be removed from the plugin tools.
Fixes #
> improvement(plugins): supported arm64 `stern` binaries

- core/test/integ/src/plugins/hadolint/hadolint.ts
- core/test/unit/src/garden.ts
- core/test/unit/src/tasks/deploy.ts
> refactor(test): used setActionConfigs helper where possible

- core/test/unit/src/plugins/kubernetes/container/build/buildkit.ts
> chore(test): fixed compilation errors

- examples/local-mode/frontend/app.js
> chore(examples): fixed backend endpoint variables

- docs/guides/running-service-in-local-mode.md
- examples/local-mode/README.md
> docs(local-mode): better description of the limitations

- core/package.json
- core/src/plugins/kubernetes/api.ts
- core/src/plugins/kubernetes/container/build/common.ts
- core/src/plugins/kubernetes/container/deployment.ts
- core/src/plugins/kubernetes/container/ingress.ts
- core/src/plugins/kubernetes/hot-reload/helpers.ts
- core/src/plugins/kubernetes/logs.ts
- core/src/plugins/kubernetes/types.ts
- core/src/util/http.ts
- core/test/integ/src/plugins/kubernetes/container/logs.ts
- core/test/unit/src/plugins/kubernetes/status/ingress.ts
- yarn.lock
> update k8s client library and fix teleport issue

- images/buildkit/garden.yml
- images/circleci-runner/garden.yml
- images/docker-dind/garden.yml
- images/k8s-reverse-proxy/garden.yml
- images/k8s-sync/garden.yml
- images/k8s-util/garden.yml
- images/rsync-server/garden.yml
- images/skopeo/garden.yml
- images/socat/garden.yml
> chore(images): ensured amd64 arch for util container builds

- docs/reference/providers/pulumi.md
- plugins/pulumi/cli.ts
> improvement(pulumi): upgrade pulumi version

- core/src/commands/deploy.ts
- docs/reference/commands.md
> docs: added example for `--forward` flag in `deploy` command desc

- core/src/plugins/kubernetes/container/deployment.ts
> chore: proper impl of exhaustive type check

- docs/reference/providers/pulumi.md
- plugins/pulumi/cli.ts
> docs(pulumi): re-generated reference docs

- core/src/tasks/run.ts
The statement was the wrong way around
Big thanks to @vvagaytsev for helping to find this!
> fix: run action result processing

- RELEASE_PROCESS.md
> chore: restructure release guide

- scripts/test-release.sh
> chore: automatically revert all changes made by the test release script

- docs/basics/5-min-quickstart.md
> docs: add instructions for updating hostfile to quickstart guide

- core/package.json
- core/src/analytics/analytics.ts
- core/src/cloud/api.ts
- core/src/cloud/workflow-lifecycle.ts
- core/src/commands/cloud/groups/groups.ts
- core/src/commands/cloud/helpers.ts
- core/src/commands/cloud/users/users-create.ts
- core/src/commands/cloud/users/users-list.ts
- core/test/unit/src/analytics/analytics.ts
- yarn.lock
This updates the cloud platform API types to the latest version.
Fixes #
> chore: bump platform api types to 1.271.0

- .circleci/config.yml
- core/src/plugins/google/common.ts
- images/circleci-runner/Dockerfile
- images/circleci-runner/garden.yml
- scripts/install-asdf-dependencies.sh
- scripts/install-osx-dependencies.sh
- support/gcloud.Dockerfile
Related to changes outlined in https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
More task details in Asana.
> chore: upgrade gcloud cli and install gke auth plugin

- core/src/plugins/kubernetes/local/microk8s.ts
When microk8s runs within a multipass VM, we need to explicitly transfer any files into the VM before having access to them. This broke builds with local docker on macOS.
Since there is no simple way of determining whether microk8s runs within multipass, we instead ask multipass to list all its VMs and see if the default microk8s machine name is included. In that case we assume that we are running in multipass and transfer the file over.
Another option would be to mount the temporary directory in and potentially reduce the file transfer overhead
```ts
if (isInMultipassVM) {
await exec("multipass", ["mount", parsedTempFilePath.dir, `${MULTIPASS_VM_NAME}:${parsedTempFilePath.dir}`])
}
await exec("microk8s", ["ctr", "image", "import", sourceFilePath])
// Clean up the file within the VM by …
```
> fix: support local builds in microk8s in multipass

- core/src/cli/cli.ts
- core/src/cloud/api.ts
- core/src/cloud/get-secrets.ts
- core/src/commands/cloud/secrets/secrets-create.ts
- core/src/commands/cloud/secrets/secrets-list.ts
- core/src/commands/cloud/users/users-list.ts
- core/src/garden.ts
This is an experimental integration with Garden Cloud that automates cloud project creation for a signed-in user.
Fixes #
> improvement(cloud): automate remote project creation

- .circleci/config.yml
- cli/src/build-pkg.ts
Mostly attempting to fix the flaky dist build step in CI, but spotted an opportunity to do some caching along the way.
> chore(ci): optimize dist build and (hopefully) fix flaky pkg-fetch problem

- core/src/vcs/git.ts
- core/test/unit/src/vcs/git.ts
- docs/advanced/using-remote-sources.md
- examples/remote-sources/garden.yml
Will eventually fix #3172
I'm sorry :(
> Allow to specify commit for remote sources

- docs/reference/commands.md
> chore: re-generated docs

- scripts/reportTestResultstToSlack.ts
> fix Slack test report regex

- core/test/unit/src/config/base.ts
- core/test/unit/src/config/common.ts
- core/test/unit/src/config/module-template.ts
- core/test/unit/src/config/project.ts
**Which issue(s) this PR fixes**: 
Fixes https://github.com/garden-io/garden/issues/3506
> test: unit test assertion fixes on config directory

- core/test/unit/src/garden.ts
Fixes some but not all of the tests for #3530
Let's move incrementally here, fix more in a separate PR.
> test: core/garden test assertion fixes

- core/test/unit/src/build-staging/build-staging.ts
> test: build-stating test assertion fixes

- core/test/unit/src/router/_helpers.ts
- core/test/unit/src/router/base.ts
- core/test/unit/src/router/deploy.ts
- core/test/unit/src/router/run.ts
issue: #3540
some test were broken due to modifications to gerden code.
does not fix all the tests, just the one's modified.
There are a couple tricky ones left (see issue) and a couple that are just yet to be written (marked as todo in code)
> Refix action tests

- core/src/plugins/kubernetes/kubernetes-type/config.ts
- core/test/unit/src/plugins/kubernetes/container/build/buildkit.ts
- core/test/unit/src/plugins/kubernetes/container/service.ts
- core/test/unit/src/plugins/kubernetes/port-forward.ts
> test: fix tests in `plugins/kubernetes/**`

- core/test/unit/src/cli/cli.ts
fix two failing cli tests. One todo test remains for the cloud dashboard integration which we're yet to have written
> 0.13: Fix cli tests

- core/src/commands/exec.ts
- core/test/unit/src/cli/helpers.ts
See individual commits for the details.
Fixes #3572
> 0.13 fix tests in `cli/helpers.ts`

- core/src/server/client-router.ts
- core/src/tasks/test.ts
> fix: fixed test names creation for module-based configs in `clientRequestHandlers`

- core/test/unit/src/commands/get/get-run-result.ts
- docs/reference/commands.md
> 0.13 minor command fixes

- core/src/plugins/hadolint/hadolint.ts
- core/test/integ/src/plugins/hadolint/hadolint.ts
> fix: partially fixed integration tests for `hadolint` plugin

- core/test/helpers.ts
- core/test/unit/src/plugins/exec/exec.ts
> 0.13 exec plugin fixes

- core/test/data/test-projects/duplicate-service-and-task/module-b/garden.yml
- core/test/data/test-projects/duplicate-task/module-a/garden.yml
- core/test/data/test-projects/duplicate-task/module-b/garden.yml
- core/test/data/test-projects/source-module/module-a/garden.yml
- core/test/unit/src/config-graph.ts
> test: fixed test configs

- core/test/unit/src/tasks/get-service-status.ts
> test: fixed deploy name

- core/test/integ/src/plugins/kubernetes/commands/sync.ts
> chore(mutagen): fix flaky test

- core/src/vcs/git.ts
- core/src/vcs/vcs.ts
Adding some basic locks and improved cache keying to avoid concurrent identical git calls.
> perf(vcs): cut git CLI calls down by approx 60%

- plugins/terraform/cli.ts
Fix sha256 checksums on terraform 1.2.9. for darwin builds.
Fixes #
> fix(terraform): fix checksums for terraform 1.2.9 darwin builds

- core/src/actions/types.ts
- core/src/plugins/hadolint/hadolint.ts
Please review the code changes and the new `TODO-G2` comment. The `timeout` value should be passed, and the relevant schema should be fixed. I need help with that.
Fixes #
> 0.13 fix hadolint tests

- core/src/plugins/kubernetes/config.ts
- core/src/plugins/kubernetes/container/util.ts
- core/src/plugins/kubernetes/helm/config.ts
- core/src/plugins/kubernetes/helm/module-config.ts
- core/src/plugins/kubernetes/kubernetes-type/config.ts
- core/src/plugins/kubernetes/kubernetes-type/module-config.ts
- core/src/plugins/kubernetes/local-mode.ts
- core/test/unit/src/router/base.ts
Some refactoring and cleanup. See individual commits for details.
Fixes #
> 0.13 cleanup

- scripts/test-release.sh
the actual brew install is coreutils, and not gtimeout
Fixes #
> chore(release): fix brew install hint in test-release.sh

- .github/dependabot.yml
> chore: add dependabot for github-actions

- core/test/unit/src/plugins/container/container.ts
> 0.13: implement container module conversion tests

- plugins/terraform/common.ts
Improve the behaviour around validation and init for the terraform provider. We now always run `terraform init` if `terraform validate` fails and we display the different error messages accordingly. 
Example of error message:
```sh
emanuele  terraform-gke   fix-terraform-init-behaviour ±  g validate -l4 --force-refresh
Validate ✔️ 
[debug] Cloud/Enterprise domain not configured. Aborting.
[debug] Error reading safe directories from the .gitconfig: Error: Command "git config --get-all safe.directory" failed with code 1:
🌍  Running in namespace default in environment local
[debug] …
```
> fix(terraform): improve init behaviour on validate and error messages

- core/src/plugins/exec/exec.ts
- core/src/plugins/exec/moduleConfig.ts
- core/src/resolve-module.ts
- core/test/helpers.ts
- core/test/unit/src/plugins/exec/exec.ts
- docs/reference/providers/exec.md
Partially addresses #3549 
Please note 2 open discussions.
> 0.13 implement `exec` plugin tests

- .github/workflows/scorecards.yml
This is the continuation of #3668.
Fixes #
> ci: updated list of allowed endpoints in the scorecard GH action

- core/test/data/test-projects/container/local-mode/garden.yml
https://github.com/garden-io/garden/blob/fix-local-mode-prjc/core/src/plugins/container/config.ts#L224 <- this little thing was added at one point hehe
Incidentally this seems to fix a large portion of k8s integ tests :)
> Fix local mode prjc

- core/src/template-string/template-string.ts
- core/test/unit/src/template-string.ts
> 0.13 implement template string tests

- core/test/unit/src/garden.ts
> test: refactor tests in `garden.ts`

- cli/src/add-version-files.ts
- core/src/commands/get/get-debug-info.ts
- core/src/commands/migrate.ts
- core/src/commands/run.ts
- core/src/commands/util/hide-warning.ts
- core/src/garden.ts
- core/src/plugins/kubernetes/integrations/cert-manager.ts
- core/src/vcs/git.ts
- core/src/vcs/vcs.ts
- core/src/warnings.ts
- core/test/unit/src/garden.ts
- core/test/unit/src/vcs/git.ts
- core/test/unit/src/vcs/vcs.ts
Introduced in #3619. Closes #3688.
> fix(core): error when attempting to emit warning message

- core/test/data/test-projects/module-templates/templates.garden.yml
- core/test/unit/src/config/base.ts
- core/test/unit/src/garden.ts
Some simple fixes in test config and error message assertions.
Partially addresses #3530.
> 0.13 fix garden unit tests (part 2)

- core/src/util/fs.ts
- core/test/unit/src/commands/create/create-module.ts
- core/test/unit/src/commands/create/create-project.ts
- core/test/unit/src/commands/get/get-outputs.ts
- core/test/unit/src/commands/logs.ts
- core/test/unit/src/commands/run-workflow.ts
- core/test/unit/src/commands/tools.ts
- core/test/unit/src/commands/util/fetch-tools.ts
- core/test/unit/src/config-graph.ts
- core/test/unit/src/garden.ts
- core/test/unit/src/outputs.ts
- core/test/unit/src/plugins/exec/exec.ts
- core/test/unit/src/tasks/deploy.ts
- core/test/unit/src/tasks/get-service-status.ts
- core/test/unit/src/tasks/resolve-provider.ts
- core/test/unit/src/tasks/run.ts
Yet another round of simple refactoring in the tests. Just to avoid code duplication and to ensure the usage of the existing helpers.
Fixes #
> 0.13 refactor tests

- core/test/unit/src/config-store.ts
Fixes https://github.com/garden-io/garden/issues/3725
Trivial assertion data changes.
> test: fix config-store.ts assertions

- core/src/plugins/container/moduleConfig.ts
- core/src/plugins/exec/moduleConfig.ts
- core/test/helpers.ts
- core/test/unit/src/plugins/container/container.ts
- core/test/unit/src/plugins/container/helpers.ts
- core/test/unit/src/plugins/exec/exec.ts
> 0.13 some fixes and refactoring in `exec` plugin

- core/src/plugins/container/config.ts
- core/test/data/test-projects/container/local-mode/Dockerfile
- core/test/data/test-projects/container/local-mode/garden.yml
- core/test/integ/src/plugins/kubernetes/container/container.ts
- core/test/integ/src/plugins/kubernetes/local-mode.ts
a few various fixes here and there
> 0.13: a few integ test fixes

- core/test/unit/src/plugins.ts
> 0.13 fix handlers arity in plugin tests

- examples/base-image/base-image/Dockerfile
> fix(example): correct entrypoint in `Dockerfile` in base-image example

- docs/guides/running-service-in-local-mode.md
Restores the changes made in #3366.
Fixes #
> docs(local-mode): restored the latest valid version of the guide

- .circleci/config.yml
- core/src/actions/helpers.ts
- core/src/plugins/kubernetes/dev-mode.ts
- core/src/plugins/kubernetes/kubectl.ts
- core/src/plugins/kubernetes/local-mode.ts
- core/src/plugins/kubernetes/status/status.ts
- core/src/plugins/kubernetes/util.ts
Removed some dead code, used some helpers instead of repetitive code, and enhanced exhaustive type checks.
Also removed the slack test report script from CI.
Fixes #
> 0.13 some refactoring and cleanup

- core/src/plugins/kubernetes/helm/handlers.ts
- core/test/data/test-projects/helm/api/garden.yml
- core/test/integ/src/plugins/kubernetes/container/deployment.ts
- core/test/integ/src/plugins/kubernetes/util.ts
More fixed integ tests coming soon
> 0.13: helm fixes & few integ test fixes

- core/src/plugins/kubernetes/helm/deployment.ts
- core/src/plugins/kubernetes/kubernetes-type/deploy.ts
- core/src/plugins/kubernetes/kubernetes-type/handlers.ts
- core/src/plugins/kubernetes/local-mode.ts
- docs/reference/action-types/Deploy/helm.md
- docs/reference/action-types/Deploy/kubernetes.md
- docs/reference/module-types/helm.md
- docs/reference/module-types/kubernetes.md
Some fixes and refactoring in local mode impl.
This might be a pre-requisite for #3755
Fixes #
See individual commits for more details.
> 0.13 some local mode fixes

- .circleci/config.yml
- examples/vote/README.md
- examples/vote/api/garden.yml
- examples/vote/postgres/garden.yml
- examples/vote/redis/garden.yml
- examples/vote/result/garden.yml
- examples/vote/vote/garden.yml
- examples/vote/worker/garden.yml
Fixes https://github.com/garden-io/garden/issues/3757
Second example I'm converting, please let me know if there's anything I've missed or if anything can be made more idiomatic!
> chore(examples): update vote example to use action configs

- examples/local-mode-helm/frontend/test/integ.js
- examples/local-mode-k8s/README.md
- examples/local-mode-k8s/backend-image/garden.yml
- examples/local-mode-k8s/backend/garden.yml
- examples/local-mode-k8s/frontend/garden.yml
- examples/local-mode-k8s/frontend/test/integ.js
- examples/local-mode/README.md
> 0.13 example update: local-mode-k8s

- examples/variables/README.md
- examples/variables/backend/garden.yml
- examples/variables/frontend/app.js
- examples/variables/frontend/garden.yml
Fixes https://github.com/garden-io/garden/issues/3765
I noticed in the backend `main.go` and `Dockerfile` the port `8080` is used, so I edited that into the ingress definition (instead of `80`) and added it to the frontend as well (`const backendServiceEndpoint = 'http://backend:8080/hello-backend'`).
Let me know if there is a better way to fix this - I tried e.g. `containerPort: 8080, localPort: 80` on the backend ingress, but was unsuccessful.
> chore(examples): update variables example to use action configs

- examples/local-mode-helm/README.md
- examples/local-mode-helm/backend-image/garden.yml
- examples/local-mode-helm/backend/garden.yml
- examples/local-mode-helm/frontend/garden.yml
> 0.13 example update: local-mode-helm

- examples/local-mode-helm/backend/garden.yml
> 0.13 local mode helm patch

- examples/local-exec/README.md
- examples/local-exec/backend/backend.garden.yml
> 0.13 example update: local-exec

- examples/local-service/README.md
- examples/local-service/backend/garden.yml
- examples/local-service/frontend/garden.yml
> 0.13 example update: local-service

- .circleci/config.yml
- examples/jib-container/helloworld/helloworld.garden.yml
- examples/jib-container/spring-boot/spring-boot.garden.yml
- plugins/jib/index.ts
- plugins/jib/util.ts
Some code fixes and example updates.
Fixes #3782
> 0.13 example update: jib-container

- core/src/plugins/kubernetes/volumes/configmap.ts
- core/src/plugins/kubernetes/volumes/persistentvolumeclaim.ts
- core/test/integ/src/plugins/kubernetes/container/container.ts
- core/test/integ/src/plugins/kubernetes/container/deployment.ts
- core/test/integ/src/plugins/kubernetes/run.ts
- core/test/integ/src/plugins/kubernetes/util.ts
fix a couple of tests and a typo in module conversion
> 0.13: more integ test fixes (and some code fixes)

- examples/local-service/frontend/garden.yml
> chore(examples): patch local-service example's configs

- examples/local-tls/services/go-service/garden.yml
- examples/local-tls/services/node-service/garden.yml
> chore(examples): update local-tls example to use action configs

- core/src/config/template-contexts/project.ts
- core/src/plugins/container/config.ts
- core/src/plugins/kubernetes/container/deployment.ts
- core/src/plugins/kubernetes/helm/deployment.ts
- core/src/plugins/kubernetes/helm/status.ts
- core/src/plugins/kubernetes/kubernetes-type/handlers.ts
- core/src/plugins/kubernetes/status/status.ts
- core/src/plugins/kubernetes/sync.ts
- core/test/integ/src/plugins/kubernetes/container/deployment.ts
> refactor: rename "dev mode" to "sync mode" in more places

- .circleci/config.yml
Botched the env var interpolation :P
> chore(ci): fix test-windows step in CI

- core/src/plugins/kubernetes/util.ts
> fix(k8s): error when getting status of container Deploy in sync mode

- examples/kubernetes-secrets/README.md
- examples/kubernetes-secrets/backend/garden.yml
- examples/kubernetes-secrets/frontend/garden.yml
> chore(examples): update kubernetes-secrets example to use action configs

- examples/hadolint/frontend/garden.yml
- examples/kubernetes-secrets/frontend/garden.yml
- examples/local-tls/services/node-service/garden.yml
Fixes #
I added some unnecessary dependencies when I was transforming test configs to the new action-based format.
> chore(examples): remove unnecessary dependencies in unit tests

- examples/kaniko/README.md
- examples/kaniko/backend/garden.yml
- examples/kaniko/frontend/garden.yml
- examples/kaniko/garden.yml
> chore(examples): update kaniko example to use action configs

- core/src/commands/create/create-module.ts
- core/src/commands/get/get-config.ts
- core/src/commands/get/get-linked-repos.ts
- core/src/commands/get/get-outputs.ts
- core/src/commands/get/get-status.ts
- core/src/commands/get/get-test-result.ts
- core/src/commands/link/module.ts
- core/src/commands/logs.ts
- core/src/commands/plugins.ts
- core/src/commands/self-update.ts
- core/src/commands/serve.ts
- core/src/commands/test.ts
- core/src/commands/util/fetch-tools.ts
- core/src/commands/validate.ts
> fix(logger): ensure we print emoji instead of text description

- core/test/integ/src/plugins/kubernetes/container/ingress.ts
Turns out it was easier then I at first thought it'd be. With these changes all of them pass.
> 0.13: fix ingress integ tests

- examples/kustomize/README.md
- examples/kustomize/helloWorld/garden.yml
- examples/kustomize/ldap/garden.yml
> chore(examples): update kustomize example to use action configs

- core/package.json
- core/src/cloud/api.ts
- core/src/commands/cloud/groups/groups.ts
- core/src/commands/cloud/helpers.ts
- core/src/commands/cloud/secrets/secrets-create.ts
- core/src/commands/cloud/users/users-create.ts
- core/test/unit/src/analytics/analytics.ts
- yarn.lock
The cloud API types have changed to return strings instead of number. This PR updates to the latest version of api-types with resulting compatibility changes.
Fixes #
> cloud(fix): Update to use UUIDs

- core/src/constants.ts
- core/src/plugin-context.ts
A very tiny PR, just some more cleanup after removing the "fancy" logger.
Fixes #
Sorry for that tiny PR, just a cleanup.
> chore(logger): more cleanup as part of removing 'fancy' logger

- core/test/integ/src/plugins/hadolint/hadolint.ts
The last few fixes to make hadolint integrations tests work.
Fixes #3583
> test: fix hadolint integration tests

- core/src/plugins/kubernetes/config.ts
- core/src/plugins/kubernetes/container/deployment.ts
- core/src/plugins/kubernetes/container/logs.ts
- core/src/plugins/kubernetes/container/service.ts
- core/src/plugins/kubernetes/container/status.ts
- core/src/plugins/kubernetes/sync.ts
- core/src/plugins/kubernetes/system.ts
- core/test/integ/src/plugins/kubernetes/container/deployment.ts
- core/test/integ/src/plugins/kubernetes/container/logs.ts
- core/test/integ/src/plugins/kubernetes/util.ts
- core/test/unit/src/plugins/kubernetes/container/service.ts
- docs/reference/providers/kubernetes.md
- docs/reference/providers/local-kubernetes.md
Fixes #3638
The commits will be squashed before the merge.
> 0.13 deprecate `deploymentStrategies` config option

- .circleci/config.yml
- examples/run-actions/garden.yml
> ci: fix namespace cleanup

- core/src/plugins/kubernetes/container/deployment.ts
- core/src/plugins/kubernetes/volumes/configmap.ts
- core/test/data/test-projects/container/volume-reference/garden.yml
- core/test/data/test-projects/helm/api/templates/deployment.yaml
- core/test/data/test-projects/helm/api/values.yaml
- core/test/helpers.ts
- core/test/integ/src/plugins/kubernetes/container/deployment.ts
- core/test/integ/src/plugins/kubernetes/run.ts
- docs/reference/action-types/Deploy/configmap.md
- docs/reference/module-types/configmap.md
> 0.13: various integ test and logic fixes

- docs/k8s-plugins/module-types/configmap.md
Fixes a small typo in the config map documentation.
N/a
> docs: fix typo in configmap docs

- docs/using-garden/variables-and-templating.md
> docs: replace dead link

- .gitattributes
See https://docs.github.com/en/repositories/working-with-files/managing-files/customizing-how-changed-files-appear-on-github
cc @Walther
> chore: exclude lockfiles from GitHub diffs

- core/src/plugins/kubernetes/config.ts
- core/src/plugins/kubernetes/kubernetes.ts
- core/src/plugins/kubernetes/local/local.ts
- core/src/plugins/kubernetes/volumes/configmap.ts
- core/src/util/validateInstall.ts
- core/test/unit/src/build-staging/build-staging.ts
- docs/basics/how-garden-works.md
- docs/k8s-plugins/module-types/container.md
- docs/k8s-plugins/remote-k8s/configure-provider.md
- docs/k8s-plugins/remote-k8s/configure-registry/README.md
- docs/k8s-plugins/remote-k8s/create-cluster/aws.md
- docs/misc/faq.md
- docs/misc/troubleshooting.md
- docs/reference/module-types/configmap.md
- docs/reference/module-types/helm.md
- docs/reference/providers/kubernetes.md
- docs/reference/providers/local-kubernetes.md
- docs/using-garden/variables-and-templating.md
- examples/demo-project/README.md
- examples/local-service/README.md
- examples/remote-k8s/README.md
- examples/vote-helm/README.md
> fix(docs): add links were there weren't any

- core/src/plugins/kubernetes/helm/handlers.ts
- core/src/plugins/kubernetes/kubernetes-type/handlers.ts
- core/test/data/test-projects/kubernetes-module/with-source-module/garden.yml
- core/test/integ/src/plugins/kubernetes/container/run.ts
- core/test/integ/src/plugins/kubernetes/kubernetes-module/handlers.ts
please make your way to the commits :)
> 0.13: module conversion + integ tests

- core/src/plugins/kubernetes/commands/sync.ts
- core/src/plugins/kubernetes/mutagen.ts
This cherry-picks https://github.com/garden-io/garden/commit/53f82400 to `0.13`.
Fixes #
> cherry-pick for 0.13: improvement(dev-mode): address PR comments

- core/src/plugins/kubernetes/run.ts
- core/src/plugins/kubernetes/status/events.ts
- core/src/plugins/kubernetes/status/pod.ts
- core/src/plugins/kubernetes/status/workload.ts
- core/src/plugins/kubernetes/util.ts
This cherry-picks #3571 to `0.13`.
Fixes #
> fix(kubernetes): detect that pod has been killed (#3571)

- core/test/integ/src/plugins/kubernetes/commands/sync.ts
> cherry-pick for 0.13: chore(mutagen): fix flaky test

- .github/workflows/npm-release.yml
- .github/workflows/scorecards.yml
- .github/workflows/update-homebrew-deprecated.yml
> cherry-pick for 0.13: updated dependencies GH actions

- .github/workflows/scorecards.yml
- README.md
- docs/reference/action-types/Build/jib-container.md
- examples/local-service/frontend/yarn.lock
- examples/remote-local-hybrid/frontend/yarn.lock
- examples/rust/backend/Cargo.lock
- plugins/terraform/common.ts
- yarn.lock
> 0.13 cherry picks from main

- core/src/plugins/kubernetes/helm/handlers.ts
- core/src/plugins/kubernetes/kubernetes-type/handlers.ts
- core/test/data/test-projects/kubernetes-module/with-namespace/garden.yml
- core/test/integ/src/plugins/kubernetes/kubernetes-module/run.ts
commits contain the keys to the kingdom
> 0.13: a few fixes + remaining k8s run integ tests fixed

- core/src/config/project.ts
- core/src/garden.ts
- core/src/proxy.ts
- core/test/unit/src/garden.ts
- docs/reference/project-config.md
This PR cherry-picks https://github.com/garden-io/garden/commit/dd50be4ee4e2acf0c23c8ed9877db7459fc653d4 to `0.13`.
Fixes #
> cherry-pick for 0.13: improvement(framework): allow users to specify proxy hostname in project

- core/test/integ/src/plugins/kubernetes/container/container.ts
- core/test/integ/src/plugins/kubernetes/container/deployment.ts
- core/test/integ/src/plugins/kubernetes/container/run.ts
- core/test/integ/src/plugins/kubernetes/kubernetes-module/handlers.ts
- core/test/integ/src/plugins/kubernetes/kubernetes-module/test.ts
with this pr all tests under `integ/kubernetes/container` and `integ/kubernetes/kubernetes-module` pass.
> 0.13: fix various k8s integ tests

- core/src/plugins/kubernetes/helm/common.ts
- core/test/data/test-projects/helm/chart-with-dependency/.helmignore
- core/test/data/test-projects/helm/chart-with-dependency/Chart.yaml
- core/test/data/test-projects/helm/chart-with-dependency/garden.yml
- core/test/data/test-projects/helm/chart-with-dependency/templates/NOTES.txt
- core/test/data/test-projects/helm/chart-with-dependency/templates/_helpers.tpl
- core/test/data/test-projects/helm/chart-with-dependency/templates/deployment.yaml
- core/test/data/test-projects/helm/chart-with-dependency/templates/service.yaml
- core/test/data/test-projects/helm/chart-with-dependency/values.yaml
- core/test/integ/src/plugins/kubernetes/helm/common.ts
with this pr all tests in helm/common.ts pass
> 0.13: common helm functionality test and code fixes

- core/src/commands/logs.ts
From commit message:
```
fix(logs): exit with error if services not found when getting logs
BREAKING CHANGE: Previously Garden would just exit silently when running the logs command and no services were found, either because of bad params or because the project has no services.
Now we throw an error, exit with code 1, and log a helpful error message.
```
Fixes #
> fix(logs): exit with error if services not found when getting logs

- core/src/actions/base.ts
- core/src/build-staging/build-staging.ts
- core/src/graph/config-graph.ts
- core/src/plugins/container/config.ts
- core/src/plugins/kubernetes/sync.ts
- core/src/tasks/build.ts
- core/test/integ/src/plugins/kubernetes/commands/pull-image.ts
- core/test/integ/src/plugins/kubernetes/container/build/build.ts
- core/test/unit/src/build-staging/build-staging.ts
- docs/reference/action-types/Deploy/container.md
- docs/reference/module-types/container.md
- docs/reference/module-types/helm.md
- docs/reference/module-types/jib-container.md
- docs/reference/module-types/kubernetes.md
- examples/build-dependencies/README.md
- examples/build-dependencies/backend/garden.yml
- examples/build-dependencies/frontend/garden.yml
- examples/build-dependencies/shared-config/garden.yml
> fix: fix source builds processing in build-staging + updated `build-dependencies` example

- examples/gke/backend/garden.yml
- examples/gke/frontend/garden.yml
Fixes https://github.com/garden-io/garden/issues/3882
Trivial conversion, everything worked as expected
> chore(examples): update gke example to use actions

- .github/workflows/actionlint.yml
- .github/workflows/scorecards.yml
- examples/argocd/web/package-lock.json
- examples/argocd/web/package.json
> 0.13 dependabot cherry picks from main

- examples/argocd/README.md
- examples/argocd/web/package-lock.json
- examples/argocd/web/package.json
- Reverts the `@vue/cli-service` back to `3.2.0` version in ArgoCD example
- Fixes README.md in ArgoCD example
Fixes #
> chore: revert dependency upgrade and fix README

- examples/argocd/README.md
- examples/argocd/web/package-lock.json
- examples/argocd/web/package.json
Fixes #
Cherry picked the necessary commit to fix the failing CI test case
> chore: revert dependency upgrade and fix README (#3946)

- core/package.json
- core/src/cli/cli.ts
- core/src/cloud/api.ts
- core/src/cloud/workflow-lifecycle.ts
- core/src/commands/cloud/groups/groups.ts
- core/src/commands/cloud/helpers.ts
- core/src/commands/cloud/secrets/secrets-create.ts
- core/src/commands/cloud/secrets/secrets-list.ts
- core/src/commands/cloud/users/users-create.ts
- core/src/commands/cloud/users/users-list.ts
- core/src/commands/login.ts
- core/src/commands/logout.ts
- core/src/constants.ts
- core/src/exceptions.ts
- core/src/garden.ts
- core/src/util/util.ts
- core/test/unit/src/analytics/analytics.ts
- core/test/unit/src/commands/login.ts
- core/test/unit/src/commands/logout.ts
- yarn.lock
This cherry picks three commits from main:
- https://github.com/garden-io/garden/pull/3666
- https://github.com/garden-io/garden/pull/3814
- https://github.com/garden-io/garden/pull/3834
Fixes #
> improvement(cloud): auth-flow changes for logging in to cloud dashboard

- .circleci/config.yml
- core/test/data/test-projects/helm/api/garden.yml
- core/test/integ/src/plugins/container/container.ts
- core/test/integ/src/plugins/kubernetes/commands/sync.ts
- core/test/integ/src/plugins/kubernetes/container/deployment.ts
- core/test/integ/src/plugins/kubernetes/helm/common.ts
- core/test/integ/src/plugins/kubernetes/helm/config.ts
- core/test/integ/src/plugins/kubernetes/helm/deployment.ts
- core/test/integ/src/plugins/kubernetes/kubernetes-module/config.ts
- core/test/integ/src/plugins/kubernetes/kubernetes-module/handlers.ts
- core/test/integ/src/plugins/kubernetes/local-mode.ts
- core/test/integ/src/plugins/kubernetes/sync-mode.ts
- core/test/integ/src/plugins/kubernetes/volume/configmap.ts
We can actually close this once merged https://github.com/garden-io/garden/issues/3113
Probably need to open a separate issue for all the tests skipped or the ones yet to be written.
> 0.13: fix all integ tests

- .circleci/config.yml
- core/package.json
- core/src/plugins/kubernetes/api.ts
- core/src/plugins/kubernetes/namespace.ts
- yarn.lock
The changes in the fork have been released. We can move away from the
fork.
This enables NPM migration.
Fixes #
> chore: move away from k8s javascript client fork

- core/src/plugins/kubernetes/kubernetes-type/kubernetes-exec.ts
- core/src/plugins/kubernetes/run.ts
- core/src/plugins/kubernetes/util.ts
This was a simple oversight in https://github.com/garden-io/garden/pull/3960
> fix(k8s): add log streaming for exec Runs/Tests
