garden-io/garden

docs/reference/commands.md, src/cli/cli.ts, src/cli/helpers.ts
=> fix(cli): enforce single character option aliases

src/cache.ts, src/garden.ts, src/plugin-context.ts, src/plugins/container.ts, src/plugins/kubernetes/local.ts, src/types/module.ts, src/watch.ts, test/src/cache.ts, test/src/commands/push.ts, test/src/types/module.ts
As part of this I made TreeCache, which makes it easy to cache values
in-process and invalidate those entries based on a surrounding context,
which can be used for other scenarios as well. For the module versions,
the cache is invalidated by FSWatcher when watched modules are modified.
@thsig maybe you wanna take a look at this one, see if I got the watcher thing right etc.
=>  perf: implemented caching of module version

examples/hello-world/garden.yml, src/garden.ts, src/plugins/kubernetes/system.ts, src/types/project.ts, test/data/test-project-a/garden.yml, test/data/test-project-b/garden.yml, test/data/test-project-templated/garden.yml, test/src/types/config.ts
Existing garden.yml files will need to be updated if they use the
project.global key.
Closes #131
=> refactor: rename project.global to project.environmentDefaults (#131)

src/garden.ts, src/plugin-context.ts, src/types/plugin/params.ts, test/helpers.ts, test/src/plugins/container.ts
I came across this when working on something else. Basically we should
not hand the plugin context to the `parseModule` handlers, because they
could then try to engage with other modules while we are still loading
them.
=> fix(core): potential race-condition when parsing modules

src/cli/cli.ts, src/commands/base.ts, src/commands/build.ts, src/commands/deploy.ts, src/commands/dev.ts, src/commands/push.ts, src/commands/test.ts, src/plugin-context.ts, src/plugins/kubernetes/local.ts, src/process.ts, src/util/keyed-set.ts, src/watch.ts
Before this change, each module directory was watched separately for
changes during auto-reload, and didn't properly handle module- or
project-level configuration changes since the auto-reload watch was
started.
Here, we consolidate the module-level watches into a single
project-level watch, and call the originating command with a fresh
PluginContext when configuration changes. This includes the addition or
removal of modules during the lifetime of the watch.
=> feat(build): Handle config changes in auto-reload.

docs/guides/configuration.md, docs/guides/glossary.md
This one is short and simple, just wanted to get these links fixed ASAP.
=> docs: fix links in glossary & configuration guide

src/plugin-context.ts, src/tasks/test.ts, src/types/module.ts, test/data/test-project-test-deps/garden.yml, test/data/test-project-test-deps/module-a/garden.yml, test/data/test-project-test-deps/module-b/garden.yml, test/src/tasks/deploy.ts, test/src/tasks/test.ts
Previously, if you'd change code in a test dependency, the test would
not be re-run if previously passed, because the resolved version did
not factor in the dependency.
=> fix: test result versions now correctly account for test dependencies

.gitignore, src/plugin-context.ts, src/plugins/kubernetes/actions.ts, src/plugins/kubernetes/specs-module.ts, src/tasks/test.ts, src/types/module.ts, src/types/plugin/outputs.ts, src/types/plugin/params.ts, src/types/task.ts, src/vcs/base.ts, src/vcs/git.ts, test/data/test-project-a/module-a/.garden-version, test/helpers.ts, test/setup.ts, test/src/commands/push.ts, test/src/plugin-context.ts, test/src/task-graph.ts, test/src/tasks/test.ts, test/src/types/module.ts, test/src/vcs/base.ts
This refactor resolves issues with using plugin modules as dependencies,
and is important for multi-repo support. Basically we now hash versions
together instead of using the latest commit, which would of course only
work within a single repo.
One thing to look at here are how the versions are hashed together (see `src/vcs/base.ts`). Please let me know if you think it could/should be done differently.
=> fix: module versions are now handled properly across multiple repos

src/cli/cli.ts, src/cli/helpers.ts, src/logger/writers/file-writer.ts
Previously the file writer would create the `error.log` even when there were no errors (cause that's basically the Winston (our file logging framework) default). That felt kind of silly when using the create command which would basically create a new project full of empty error logs.
However, once a log file has been created for the first time it stays there. In the case of the `error.log` file, it's truncated each time (there are persistent log files under `.garden/logs`).
Does that make sense? Should we perhaps move the `error.log` to something like `garden_tmp` and remove it if there are no errors? Or just leave it as is?
=> fix(file-writer): only create file if content to write

docs/reference/commands.md
Not sure what happened but the generated docs were out of sync.
=> docs: add missing generated commands docs

docs/reference/commands.md, src/commands/create/config-templates.ts, src/commands/create/helpers.ts, src/commands/create/module.ts, src/commands/create/prompts.ts, test/src/commands/create/module.ts
Looks like another rebase regression. This is how it should've been in the first place.
=> fix(create-module-command): type option should be an enum

docs/reference/commands.md, garden-cli/src/commands/commands.ts, garden-cli/src/commands/exec.ts, garden-cli/src/plugins/kubernetes/actions.ts
This was mostly done before and accidentally committed, just needed some debugging and wrap-up.
=> feat: add exec command, to run commands in running service containers

garden-cli/src/commands/build.ts, garden-cli/src/commands/create/project.ts, garden-cli/src/commands/deploy.ts, garden-cli/src/commands/dev.ts, garden-cli/src/commands/test.ts, garden-cli/src/plugin-context.ts, garden-cli/src/plugins/openfaas.ts, garden-cli/src/process.ts, garden-cli/src/task-graph.ts, garden-cli/src/tasks/base.ts, garden-cli/src/tasks/build.ts, garden-cli/src/tasks/deploy.ts, garden-cli/src/tasks/test.ts, garden-cli/src/watch.ts, garden-cli/test/src/watch.ts
(pushing this on behalf of @thsig)
Each command's process function now explicitly controls which tasks are
added to the TaskGraph when a module is processed, with a separate
callback (processWatchChanges) for handling changes in watch mode. This
was previously controlled in garden-cli/src/process.ts.
This commit fixes
#193,
and a few other cases where the watch logic's behavior deviated from its
specification (in docs / help strings).
Following is a summary of the watch logic's behavior after these changes:
- `garden build -w` rebuilds changed modules, their build dependencies,
and their build dependants.
- `garden build -w some-module` rebuilds only `some-module` and its
dependencies when it changes (ignoring changes to other modules as
usual).
- `garden deploy -w` redeploys changed …
=> Templating refactor watch fixes

garden-cli/package.json
This issue breaks the garden-cli npm package. Once merged we should cut a new patch release.
=> fix: add axios as dependency (was dev dependency)

garden-cli/package-lock.json, garden-cli/package.json, garden-cli/src/plugins/kubernetes/ingress.ts
By removing the x509 library, in favor of the (admittedly odd) certpem/pkijs libs
Closes #261
=> refactor: get rid of native OpenSSL dependency

docs/introduction/getting-started.md, garden-cli/support/Windows.ps1, garden-cli/support/install.ps1
This is a PowerShell script for the installation on Windows.
It does:
```
```
Ideally we should be able to run it the same way as the Chocolatey installer, just by copying the command from our website and pasting it on the shell.
The Chocolatey package is in progress, should be done tomorrow. It's basically the same thing wrapped in a Chocolatey package, except without the bit that installs Chocolatey itself.
There are some comments and a couple unused functions that I'll leave there until we get to a finished version, as they may still be useful.
One thing we need to decide on about the Chocolatey package is the uninstall script. When installing, we're adding *a bunch* of stuff. When uninstalling, what should we remove? I don't think it makes sense to remove say node and git from the …
=> feat: windows installer

garden-cli/package-lock.json, garden-cli/src/plugins/kubernetes/actions.ts, garden-cli/src/plugins/kubernetes/deployment.ts, garden-cli/src/plugins/kubernetes/kubectl.ts, garden-cli/src/plugins/openfaas.ts, garden-cli/src/plugins/openfaas/faas-cli.ts, garden-cli/src/plugins/openfaas/openfaas.ts, garden-cli/src/plugins/plugins.ts
When deleting a container service via the delete command, also delete
its k8s service and ingress.
This fixes problems previously caused by dangling k8s
ingresses/services.
=> fix: incl. ingresses & services in delete command.

docs/introduction/getting-started.md
I always find it a bit of a hassle to find the specific link to the Edge version of Docker, so I thought I'd use it in the documentation instead of the generic Docker For Windows one.
=> docs: link specifically to edge version

garden-cli/package-lock.json, garden-cli/src/commands/dev.ts, garden-cli/src/commands/test.ts, garden-cli/src/garden.ts, garden-cli/src/tasks/test.ts, garden-cli/src/types/module.ts
Fixes: https://github.com/garden-io/garden/issues/307
**Include provided deps in module cache keys.**
`resolveVersion` now includes a sorted list of module names (from the provided dependencies) in the module version cache key.
**Prevent multiple prefixing in getModuleKey.**
Before, getModuleKey was not idempotent, leading to incorrect module keys when the plugin name got prefixed to the module name more than once.
=> Module version cache fix

docs/introduction/getting-started.md, garden-service/package-lock.json, garden-service/package.json, garden-service/src/constants.ts, garden-service/src/garden.ts, garden-service/src/plugins/kubernetes/helm.ts, garden-service/src/plugins/kubernetes/init.ts, garden-service/src/plugins/plugins.ts, garden-service/src/util/ext-source-util.ts, garden-service/src/util/ext-tools.ts, garden-service/src/util/is-subset.ts, garden-service/src/util/util.ts, garden-service/support/homebrew-formula.rb, garden-service/support/install.ps1, gulpfile.ts
We now automatically fetch helm when needed via the new tool helper.
Note: We still install Helm via package dependencies, because it's
really no bother for the user, but we don't need to explicitly list
it in docs.
Before completing this and using for more tools, I wanted to float the idea and see if it makes sense to everyone...
=> refactor: remove explicit helm and stern installation dependencies

garden-service/src/commands/logs.ts, garden-service/src/plugins/kubernetes/actions.ts, garden-service/src/plugins/kubernetes/deployment.ts, garden-service/src/plugins/kubernetes/helm.ts, garden-service/src/plugins/kubernetes/status.ts
=> fix: handle missing services gracefully in logs command

garden-service/src/util/ext-tools.ts
When validating the hash of a downloaded binary, `hash.read()` returns
`null` at the end of stream event. This wasn't handled properly before.
=> fix(ext-tools): handle end of stream event

Gopkg.lock, garden-cli/config.go, garden-cli/constants.go, garden-cli/dockerutil/docker.go, garden-cli/main.go, garden-cli/run.go, garden-cli/sync.go, garden-cli/util/util.go, garden-service/Dockerfile, garden-service/gulpfile.ts, garden-sync/Dockerfile, garden-sync/gulpfile.ts
An improved version of the Go CLI.
* Use Docker SDK where possible instead of shelling out
* Ensure sync is complete before running the command
* Keep the garden-service container running
=> refactor(go-cli): use docker sdk and keep containers running

bin/check-docs, docs/reference/glossary.md, package-lock.json, package.json
Adds automatic markdown linter for links. 
Can be run locally 
`npm run check-docs` 
Thinking we should split `check-docs` and `lint-docs` but kinda on the fence here
This also happens during CI now as well.
Closes #330 
Will rebase once #359  is merged.
=> Add automatic markdown link validator 

.gitmodules, bin/check-docs, garden-service/Dockerfile, garden-service/package-lock.json, garden-service/package.json, garden-service/src/plugins/kubernetes/api.ts, garden-service/src/plugins/kubernetes/secrets.ts, garden-service/src/plugins/kubernetes/status.ts, package.json
Removes dependency on git-submodules and simplifies garden-service dependancies.
We can either merge this now using our fork or wait for upstream to merge my PR there? Should still be this week, if not we can go forward with our fork. 
We just need to change 
`"@kubernetes/client-node": "kubernetes-cliet/javascript#hash",`
=> Cleaner service builds

.circleci/config.yml, garden-cli/.goreleaser.yaml, garden-cli/config_test.go
* Adds a dummy unit test and uploads its results into [circleci](https://circleci.com/docs/2.0/configuration-reference/#store_test_results)
* Refactors our circleCI config to make use of their [shared commands ](https://circleci.com/docs/2.0/configuration-reference/#commands-requires-version21) so we can share configuration between different jobs (this becomes useful when we actually start publishing releases via circleci)
* Switches go builds to use [goreleaser](https://goreleaser.com) this removes our bash hackery, it also allows us to much more easily extend
=> Improve garden-cli build setup

garden-service/src/tasks/helpers.ts
Previously, the module being hot-reloaded was rebuilt following the hot
reload operation.
This is an unnecessary step, and is removed in this commit to reduce CPU
load.
=> fix: skip build task during hot-reloading

docs/reference/config-files-reference.md, garden-service/src/plugins/container.ts, garden-service/src/plugins/kubernetes/actions.ts, garden-service/src/plugins/kubernetes/deployment.ts, garden-service/test/src/plugins/kubernetes/deployment.ts
Fixes issues with handling subpaths as hotreload sync targets with differences between the way `cp` and `rysync` and `k8s` handle the paths. 
Solves issues with trying to sync `src` into `/app/src` and other edge cases where hotreloading would only work after a first change was made to the source. 
Also originally both the source and target needed to be in the exact correct format for things to work regarding trailing slashes. 
@thsig I also made 2 small changes that should have zero impact on code but really bugged me.
1. Changed the sync container name to not include `-container` it's annoying to suffix things by what they are.
2. Changed the volume to be called `garden-sync` so removed `-volume` and the `-${service-name}` this volume isn't a global variable its only shared with in this …
=> fix: fixes to hot reload source/target handling

docs/reference/config.md, garden-service/src/config/common.ts, garden-service/test/src/types/common.ts
We should allow the same set of variables that bash/docker/k8s would allow. 
Fixes #369 
Also https://www.ietf.org/rfc/rfc2119.txt regarding usage of may/must :)
=> fix: allow env variables to be lower case

garden-service/src/commands/create/config-templates.ts, garden-service/src/commands/create/helpers.ts, garden-service/src/commands/create/module.ts, garden-service/src/commands/create/project.ts, garden-service/test/src/commands/create/config-templates.ts, garden-service/test/src/commands/create/project.ts
The `project` key was missing at the top of the project level `garden.yml` file generated by the create command. Furthermore, the tests were validating the generated config against the projectSchema instead of the entire configSchema.
=> fix(create-command): add project key to generated config and fix tests

docs/examples/hello-world.md, examples/hello-world/README.md, examples/hello-world/services/hello-container/app.js, examples/hello-world/services/hello-container/garden.yml
Fixes #325 
We can also better document it instead of being explicit, but I think this is more clear as a hello-world example.
I like the idea of the readme's in the example/xx/README.md being kinda a quick start compared to a full walkthrough like https://docs.garden.io/examples/hello-world  
But happy to change that?
=> Improve hello world example

garden-service/src/cli/cli.ts, garden-service/src/commands/base.ts, garden-service/src/commands/build.ts, garden-service/src/commands/deploy.ts, garden-service/src/commands/dev.ts, garden-service/src/commands/test.ts
Resolves https://github.com/garden-io/garden/issues/389.
Also added a `headerRendered` instance var to commands accepting the watch flag, to prevent commands re-rendering their header on restart.
I decided not to add `headerRendered` to the base `Command` class for starters. Thoughts?
=> fix: fix dev command terminating on config change

garden-service/src/commands/dev.ts, garden-service/src/dependency-graph.ts, garden-service/src/process.ts, garden-service/src/task-graph.ts, garden-service/src/tasks/helpers.ts, garden-service/src/watch.ts, garden-service/test/data/test-project-dependants/service-dependant2/.dockerignore, garden-service/test/data/test-project-dependants/service-dependant2/Dockerfile, garden-service/test/data/test-project-dependants/service-dependant2/garden.yml, garden-service/test/src/task-graph.ts, garden-service/test/src/tasks/helpers.ts
Fixes https://github.com/garden-io/garden/issues/386.
This bug was fixed here as a side-effect of simplifying the implementation of `TaskGraph`'s dependency logic.
Previously, dependency relationships of nodes in `TaskGraph` were updated by adding/removing from the dependencies/dependants arrays of the appropriate `TaskNode`s when nodes were added or removed.
This logic was somewhat opaque and difficult to maintain/debug. Here, we change the implementation to simply rebuild the dependency relationships of all nodes in `TaskGraph`'s index whenever a node is added or removed. We make use of a mutex/lock to prevent race conditions, and cache config-level dependency relationships for performance.
With this implementation, we no longer need to track dependants or handle predecessors (since …
=> fix: fixed dependency bug & simplified TaskGraph

docs/reference/commands.md, garden-service/package-lock.json, garden-service/package.json, garden-service/src/commands/get/get-graph.ts, garden-service/src/commands/get/get.ts, garden-service/src/dependency-graph.ts, garden-service/test/src/commands/get/get-graph.ts
This command returns a serialized representation of the project's
DependencyGraph.
=> feat: added get graph command

garden-service/src/cli/cli.ts, garden-service/src/commands/base.ts, garden-service/src/commands/build.ts, garden-service/src/commands/deploy.ts, garden-service/src/commands/dev.ts, garden-service/src/commands/helpers.ts, garden-service/src/commands/run/task.ts, garden-service/src/commands/serve.ts, garden-service/src/commands/test.ts, garden-service/src/commands/update-remote/all.ts, garden-service/src/events.ts, garden-service/src/process.ts, garden-service/src/server/commands.ts, garden-service/src/server/server.ts, garden-service/src/server/websocket.ts, garden-service/src/task-graph.ts, garden-service/src/watch.ts, garden-service/test/src/commands/build.ts, garden-service/test/src/server/server.ts, garden-service/test/src/task-graph.ts
=> refactor: nicer logging when watching for changes / hot reloading

garden-service/src/commands/serve.ts, garden-service/src/process.ts, garden-service/src/server/server.ts
via GARDEN_SERVER_PORT env variable
`GARDEN_SERVER_PORT=9778 GARDEN_ENABLE_SERVER=1 garden dev`
This should solve a bunch of hacks getting the dashboard port to update every time you run the a command.
=> Allow explicitly picking port for api in dev cmd

garden-service/src/actions.ts, garden-service/src/commands/deploy.ts, garden-service/src/commands/dev.ts, garden-service/src/tasks/helpers.ts, garden-service/test/src/commands/deploy.ts, garden-service/test/src/tasks/helpers.ts
Tasks should not run if they are leaf nodes after watch triggers.
Otherwise tasks that have no dependants get run automatically, and we
want users to be able to define tasks that are only run manually.
=> fix: do not run dependant tasks unless updated services depend on them

garden-service/src/cli/cli.ts, garden-service/src/process.ts
A side effect of this is that we always add a blank line at the bottom
of the console when using the fancy logger. I think it looks nice
in most cases, but we may want to adjust some logging later.
=> fix(log): log footer line was duplicated after config reload

garden-dashboard/public/index.html, garden-dashboard/src/api/types.ts, garden-dashboard/src/app.tsx, garden-dashboard/src/components/sidebar.tsx, garden-dashboard/src/containers/overview.tsx, garden-dashboard/src/containers/sidebar.tsx, garden-dashboard/src/context/config.tsx, garden-dashboard/src/context/status.tsx, garden-service/gulpfile.ts, garden-service/src/commands/get/get-status.ts, garden-service/src/config/project.ts, garden-service/src/garden.ts, garden-service/src/plugin-context.ts, garden-service/src/plugins/kubernetes/deployment.ts, garden-service/src/plugins/kubernetes/helm.ts, garden-service/src/plugins/kubernetes/init.ts, garden-service/src/plugins/kubernetes/local.ts, garden-service/src/plugins/kubernetes/status.ts, garden-service/src/plugins/openfaas/openfaas.ts, garden-service/src/types/plugin/outputs.ts, garden-service/src/types/plugin/plugin.ts, garden-service/static/kubernetes/system/kubernetes-dashboard/garden.yml, garden-service/test/src/actions.ts, garden-service/test/src/garden.ts, garden-service/test/src/plugins/kubernetes/ingress.ts
This also moves the dashboard link definitions from the plugin schema
to the environment status output, in order to accommodate dynamic links.
=> feat(dashboard): expose provider links in sidebar

garden-service/package-lock.json, garden-service/package.json, garden-service/src/plugins/kubernetes/api.ts, garden-service/src/plugins/kubernetes/secrets.ts, garden-service/src/plugins/kubernetes/status.ts
Switch back to official kubernetes node-client. As a side affect this also includes changes for `exec` as a local auth method (which will allow us to properly make use of gke/* clusters)
Before when accessing a gke cluster we would have to run something to refresh the token externally before using garden.
=> Upgrade kubernetes client to 0.7.2

docs/reference/commands.md, docs/reference/config.md, examples/tasks/hello/garden.yml, examples/tasks/user/garden.yml, garden-service/package-lock.json, garden-service/src/commands/get/get-secret.ts, garden-service/src/commands/get/get-tasks.ts, garden-service/src/commands/get/get.ts, garden-service/src/config/task.ts, garden-service/src/types/task.ts, garden-service/test/data/test-project-b/module-a/garden.yml, garden-service/test/src/commands/get/get-tasks.ts, package-lock.json, package.json
Added a get tasks command, which lists all the project's tasks by module. Also added a `description` field to task configs.
Implements https://github.com/garden-io/garden/issues/420.
Example output (when run in the `tasks` example project):
```yaml
$ garden get tasks
- tasks for module hello:
- name: node-migration
command:
- knex
- 'migrate:latest'
description: Creates the users table.
dependencies:
- postgres
- tasks for module postgres: []
- tasks for module user:
- name: ruby-migration
command:
- rake
- 'db:migrate'
description: Populates the users table with a few records.
dependencies:
- node-migration
```
=> feat: added get tasks command

.github/ISSUE_TEMPLATE/BUG_REPORT.md, docs/reference/commands.md, garden-service/src/cli/cli.ts, garden-service/src/cli/helpers.ts, garden-service/src/commands/commands.ts, garden-service/src/commands/version.ts, garden-service/test/src/cli/helpers.ts, garden-service/test/src/commands/version.ts
Adds a version command so it matches all a bunch of other tools.
`garden version` and `garden -v` return the same result.
=> feat(versioncmd): adds version command to return current version

docs/reference/config.md, examples/simple-project/services/go-service/garden.yml, examples/simple-project/services/go-service/webserver/main.go, garden-service/src/docs/config.ts, garden-service/src/plugins/container.ts, garden-service/src/plugins/kubernetes/deployment.ts, garden-service/src/plugins/kubernetes/ingress.ts, garden-service/src/plugins/kubernetes/service.ts, garden-service/src/plugins/local/local-docker-swarm.ts, garden-service/src/plugins/local/local-google-cloud-functions.ts, garden-service/test/src/docs/config.ts, garden-service/test/src/plugins/container.ts, garden-service/test/src/plugins/kubernetes/ingress.ts, garden-service/test/src/types/container.ts
Adds a `servicePort` configuration that if not there will default to `containerPort` this is the value that the service will be exposed on. 
I will fix  and improve all the docs / help text.
I would also like to add a doc that explains the differences between our service ports and how they work and what they map to in their native terms. 
fixes #400
=> Adds Service port config option to container module

garden-service/src/config/base.ts, garden-service/src/config/common.ts, garden-service/src/plugins/container.ts, garden-service/src/plugins/exec.ts, garden-service/src/plugins/google/google-cloud-functions.ts, garden-service/src/plugins/kubernetes/helm.ts, garden-service/test/data/test-project-invalid-config/garden.yml, garden-service/test/data/test-project-invalid-config/invalid-config-module/garden.yml, garden-service/test/data/test-project-invalid-config/invalid-syntax-module/garden.yml, garden-service/test/src/config/base.ts
When config validation fails for a module, the relative path (from project root) to the failing config file is included in the error message.
Resolves https://github.com/garden-io/garden/issues/410.
For example:
```
Error validating module user at user/garden.yml: key "foo" is not allowed at path [foo]
```
instead of
```
Error validating module user: key "foo" is not allowed at path [foo]
```
which is the current behaviour on `master`.
=> fix: add path to module validation error messages

garden-service/src/util/util.ts
Added `*.log` to the list of path patterns ignored by default.
Previously, running `garden get status` in a project where
* Another Garden command is running in watch mode, and
* A service from a module at the project level (i.e. with its
module config in the project-wide `garden.yml`) is deployed
with hot reloading enabled,
would erroneously trigger a hot reload of that service, due to the
project-level `error.log` getting touched during the execution of
`garden get status`.
Fixes https://github.com/garden-io/garden/issues/387.
=> fix: don't watch project-level log files

garden-service/src/plugins/kubernetes/hot-reload.ts
Added a simple in-process cache of port-forwards allocated for syncing
during hot-reloading.
This results in dramatic (often 50%) speedups for hot reloads subsequent
to the initial one, during the execution of the enclosing Garden command.
Addresses https://github.com/garden-io/garden/issues/458.
=> fix(perf): reuse port-forwards when hot-reloading

dashboard/src/api/index.ts, dashboard/src/api/types.ts, dashboard/src/components/card.tsx, dashboard/src/components/graph/index.tsx, dashboard/src/components/logs.tsx, dashboard/src/components/terminal.tsx, dashboard/src/containers/logs.tsx, dashboard/src/context/data.tsx, dashboard/src/styles/variables.ts, docs/reference/commands.md, garden-service/src/commands/logs.ts, garden-service/src/plugins/kubernetes/logs.ts, garden-service/src/types/plugin/params.ts, garden-service/test/src/actions.ts
This is really just to prevent the browser from crashing on the user if the logs are huge. We still need better log support for the dashboard in general. E.g:
* Improve UI
* Fetch logs for individual services
* Merge new log entries with those already in the data sore
=> fix(dashboard): limit number of log lines that are fetched (#461)

garden-service/src/actions.ts, garden-service/src/garden.ts, garden-service/src/plugins/container/container.ts, garden-service/src/plugins/exec.ts, garden-service/src/plugins/google/google-cloud-functions.ts, garden-service/src/plugins/kubernetes/container/handlers.ts, garden-service/src/plugins/kubernetes/helm/config.ts, garden-service/src/plugins/kubernetes/helm/handlers.ts, garden-service/src/plugins/kubernetes/kubernetes.ts, garden-service/src/plugins/kubernetes/local.ts, garden-service/src/plugins/local/local-google-cloud-functions.ts, garden-service/src/plugins/openfaas/openfaas.ts, garden-service/src/types/plugin/outputs.ts, garden-service/src/types/plugin/params.ts, garden-service/src/types/plugin/plugin.ts, garden-service/test/helpers.ts, garden-service/test/src/actions.ts, garden-service/test/src/commands/call.ts, garden-service/test/src/commands/delete.ts, garden-service/test/src/commands/deploy.ts, garden-service/test/src/commands/publish.ts, garden-service/test/src/plugins/container.ts, garden-service/test/src/plugins/kubernetes/container/ingress.ts
This is part of a larger branch I had, reworking the provider configuration and preparation mechanisms.
=> refactor: add configureProvider plugin action

docs/reference/config.md, garden-service/src/config/common.ts, garden-service/src/plugins/kubernetes/helm/common.ts, garden-service/src/plugins/kubernetes/helm/config.ts, garden-service/test/data/test-projects/helm/api/garden.yml, garden-service/test/src/config/common.ts, garden-service/test/src/plugins/kubernetes/helm/common.ts, garden-service/test/src/plugins/kubernetes/helm/config.ts, garden-service/test/src/plugins/kubernetes/helm/status.ts
This is necessary for another fix I'm working on, but can be reviewed separately.
=> feat(k8s): allow overriding release name in Helm modules

garden-service/src/plugins/kubernetes/container/status.ts, garden-service/src/plugins/kubernetes/helm/status.ts, garden-service/src/plugins/kubernetes/status.ts
Fixes https://github.com/garden-io/garden/issues/377.
Previously, deployed but unhealthy services would be reported as "ready" by the `get status` command. This is fixed here.
=> fix(status): return more correct/granular statuses

garden-service/src/commands/logs.ts, garden-service/src/logger/log-entry.ts, garden-service/src/server/commands.ts, garden-service/test/logger/log-entry.ts
Also renames `preserveLevel` to `childEntriesInheritLevel`. Although it really should just be `bequeathLevel`.
=> Fix serve command logs

.circleci/config.yml, Gopkg.lock, Gopkg.toml, garden-cli/config.go, garden-cli/constants.go, garden-cli/dockerutil/docker.go, garden-cli/main.go, garden-cli/run.go, garden-cli/sync.go, garden-cli/syncutil/sync.go, garden-cli/util/util.go, garden-service/src/util/util.ts, garden-sync/Dockerfile
First take on the [Mutagen](https://github.com/havoc-io/mutagen/) implementation. Tests are still missing so this should be considered work in progress. 
The previous Go CLI implementation used [Unison](https://www.cis.upenn.edu/~bcpierce/unison/) and did the syncing inside the sync container, similar to [this strategy](https://github.com/EugenMayer/docker-sync/wiki/8.-Strategies#native_osx-osx) that docker-sync uses. That however will not work on Windows. 
Therefore we opted for doing the syncing from the host and into the `garden-sync` container, using Mutagen as our synchronisation tool. The flow looks like this:
1.  Create a named Docker volume unique to the project
2. Create a `garden-sync` container unique to the project and mount it with the Docker volume
3. Use Mutagen to sync …
=> refactor(go-cli): replace unison with mutagen (wip)

garden-service/src/actions.ts
Occurred only when services depended on tasks, so it was missed
in testing.
=> fix(core): error in actions.getStatus helper

garden-service/src/actions.ts, garden-service/src/cli/cli.ts, garden-service/src/cli/helpers.ts, garden-service/src/commands/version.ts, garden-service/src/plugins/kubernetes/init.ts, garden-service/src/plugins/kubernetes/namespace.ts, garden-service/src/util/util.ts, garden-service/static/kubernetes/system/ingress-controller/garden.yml, garden-service/test/src/cli/helpers.ts
* Add a version annotation to k8s namespaces created by the framework.
* If the garden-system / garden-system--metadata namespaces have
versions corresponding to another release than is currently being used,
they're deleted and recreated.
* Added a releaseName to the k8s ingress-controller system module.
=> fix: delete outdated system namespaces

garden-service/src/plugins/kubernetes/init.ts
This avoids a class of errors that can come up when deployments of
system services in the local-kubernetes provider fail, or if resources
are manually deleted.
=> fix(local-k8s): always use force flag when deploying to garden-system ns

garden-service/src/events.ts, garden-service/src/process.ts, garden-service/src/watch.ts, garden-service/test/src/watch.ts
Fixes https://github.com/garden-io/garden/issues/512.
Before restarting a watch-mode command when a config file is changed/added/removed, attempt creating a new Garden instance using the project's (and its modules') updated config before performing the restart.
If a configuration error was introduced by the change, log an error message and keep the existing Garden instance instead of restarting.
=> feat: don't restart command when config is invalid

docs/examples/hello-world.md, docs/examples/remote-sources.md, docs/examples/simple-project.md, docs/examples/tls-project.md, examples/remote-sources/README.md, examples/simple-project/services/go-service/garden.yml, examples/simple-project/services/node-service/garden.yml
Usually the links to examples point to a specific release, say, v0.9.0. However, there were some issues with the docs at that tag, that we've since fixed. I've therefore created a new tag with the fixes, v0.9.0-docfix.1, and updated the links accordingly.
=> docs: update links to examples

garden-service/src/config/config-context.ts, garden-service/src/vcs/base.ts, garden-service/test/helpers.ts, garden-service/test/src/commands/deploy.ts, garden-service/test/src/vcs/base.ts
Added the "version-" prefix to the versionString field on ModuleVersion.
This should resolve an issue where module versions would be read as numbers when used as template variables when the first several characters of the commit hash were numbers.
@eysi09 and I have come across this error a couple of times during CI. Here's an example:
=> fix(templates): add prefix to versionString

garden-service/src/config/base.ts, garden-service/test/src/config/base.ts
This addresses an issue where config files defining Helm modules with the flat config style would result in the Helm module not having its path attribute set.
This PR is a simplified version of https://github.com/garden-io/garden/pull/554/files (which I'm closing), omitting the changes to the `vote-helm` project (and thus only consists of the bugfix itself).
=> fix: fixed bug in configuring flat-config modules

garden-service/src/plugins/kubernetes/helm/common.ts, garden-service/test/data/test-projects/helm/duplicate-keys-in-template/.helmignore, garden-service/test/data/test-projects/helm/duplicate-keys-in-template/Chart.yaml, garden-service/test/data/test-projects/helm/duplicate-keys-in-template/garden.yml, garden-service/test/data/test-projects/helm/duplicate-keys-in-template/templates/service.yaml, garden-service/test/data/test-projects/helm/duplicate-keys-in-template/values.yaml, garden-service/test/src/plugins/kubernetes/helm/common.ts
Prevents "duplicated mapping key" errors when loading remote charts with duplicate keys (e.g. official ambassador chart).
When loading the template with `{ json: true }`, duplicate keys in a mapping will override values rather than throwing an error.
However, this behavior is broken for the `safeLoadAll` function, see: https://github.com/nodeca/js-yaml/issues/456. We therefore need to use the `loadAll` function. See the following link for a conversation on using `loadAll` in this context: https://github.com/kubeapps/kubeapps/issues/636.
=> fix(helm): allow duplicate keys in template

garden-service/src/task-graph.ts, garden-service/test/src/task-graph.ts
Fixes https://github.com/garden-io/garden/issues/540.
This fixes an issue in `TaskGraph` where `taskPending` events were emitted for tasks with up-to-date cached results. This led to the task graph UI on the dashboard displaying the nodes corresponding to skipped tasks in a permanent pending state.
This was addressed by only emitting the event if the task was, in fact, added to `TaskGraph`'s index.
=> fix: don't emit taskPending if task is skipped

docs/reference/config.md, docs/reference/module-types/container.md, docs/reference/module-types/exec.md, docs/reference/module-types/helm.md, docs/reference/module-types/openfaas.md, garden-service/src/config/base.ts, garden-service/src/config/module.ts, garden-service/src/plugins/container/config.ts, garden-service/src/plugins/container/container.ts, garden-service/src/plugins/exec.ts, garden-service/src/plugins/kubernetes/helm/config.ts, garden-service/test/helpers.ts, garden-service/test/src/config/base.ts, garden-service/test/src/plugins/container.ts, garden-service/test/src/plugins/exec.ts, garden-service/test/src/plugins/kubernetes/helm/config.ts
Allows referencing a specific image in a multi-stage Dockerfile.
Needed a refactor to be able to add a field to the build schema.
=> feat(container): add `build.targetImage` parameter

garden-service/src/plugins/kubernetes/container/ingress.ts
Fixes a regression where getting the service status of a k8s service would fail (e.g. when calling garden get status or garden deploy).
=> fix: allow ingress annotations in service status

garden-service/src/process.ts
Before this fix, the module provided to the change handlers of watch-mode commands didn't have an up-to-date version, reflecting the latest dirty timestamp of the changed module.
This resulted in errors due to version discrepancies between e.g. build and deploy tasks in watch mode commands.
=> fix: ensure module is up to date in watch handler

docs/using-garden/using-helm-charts.md, examples/vote-helm/result-image/views/app.js, examples/vote-helm/result/garden.yml, examples/vote-helm/vote-image/vue.config.js, examples/vote-helm/vote/garden.yml, garden-service/src/plugins/kubernetes/hot-reload.ts
This avoids confusion/conflict when trying out both the vote and
vote-helm examples.
=> fix(examples): use different ingress hostnames for vote-helm example

support/install.ps1
Hi, this fixes #596 . Basically an update on the url endpoint for garden releases. Following @eysi09 comment.
=> chore(release): fix windows installer release url

garden-service/src/plugins/container/helpers.ts, garden-service/src/util/util.ts
This is a quick fix for #399 (addresses point one in this [comment](https://github.com/garden-io/garden/issues/399#issuecomment-443343277)).
A few things:
* I opted not to append the `stderr` to the `output` string in the `spawn` function since the error is already printed at the top of the error message. This also conforms to how the container build output was displayed before this change.
* We now only print the last hundred lines of the output in case of an error. Should this be more?
* The `MAX_BUFFER_SIZE` is pretty arbitrary, any thoughts?
=> fix: stream container build output and cap max buffer size

garden-service/src/tasks/build.ts
This addresses an issue where status checks rely on build sources
having been staged.
=> fix(build): always sync sources when building

docs/faqs.md, docs/reference/module-types/maven-container.md, docs/reference/providers/maven-container.md, garden-service/package-lock.json, garden-service/package.json, garden-service/src/config/common.ts, garden-service/src/docs/config.ts, garden-service/src/plugins/container/build.ts, garden-service/src/plugins/container/container.ts, garden-service/src/plugins/maven-container/maven-container.ts, garden-service/src/plugins/plugins.ts, garden-service/static/maven-container/Dockerfile
Pushing this a little early, to support a customer. We'll want to add an example for this, and some further documentation.
This plugin is a specialised version of the container plugin, that adds a couple of parameters, and a pre-build step ahead of building the actual container. The motivation being that it's very difficult and/or prohibitively slow to build large Java projects inside containers, especially if they're organised in a way that doesn't jive with typical docker build context layouts.
=> feat: add maven-container plugin type

garden-service/src/plugins/kubernetes/container/deployment.ts
The initial delay in the liveness probe config for k8s health checks was too short. This was due to the mistaken assumption that k8s would only start running the liveness probe after the readiness probe succeeded.
For services that take a long time to start up, the old config would sometimes lead to the liveness probe failing and thus the container being restarted - repeatedly, in some situations.
The initial delay and frequency of the readiness probe were also reduced.
Later, we should aim to make `initialDelaySeconds` configurable for the liveness probe.
=> fix: increase init delay for liveness probe

garden-service/src/logger/logger.ts
Fixes https://github.com/garden-io/garden/issues/604.
Before this commit, the log level passed to a command with `-l`/`--logLevel` was ignored when used in conjunction with the `GARDEN_LOGGER_TYPE` env var.
=> fix: respect level when using logger type env var

garden-service/package-lock.json, garden-service/src/plugins/kubernetes/hot-reload.ts, garden-service/test/src/plugins/kubernetes/hot-reload.ts
This fixes various issues with hot reload sync configuration and simplifies the internal logic.
One issue resolved by this change is that `Dockerfile`s with `WORKDIR`s nested under one of the sync targets no longer cause problems with hot reloading.
=> fix: use abs target paths in HR copy commands

garden-service/src/config/project.ts, garden-service/src/plugin-context.ts, garden-service/src/plugins/kubernetes/api.ts, garden-service/src/plugins/kubernetes/container/deployment.ts, garden-service/src/plugins/kubernetes/container/handlers.ts, garden-service/src/plugins/kubernetes/container/ingress.ts, garden-service/src/plugins/kubernetes/container/logs.ts, garden-service/src/plugins/kubernetes/container/run.ts, garden-service/src/plugins/kubernetes/container/status.ts, garden-service/src/plugins/kubernetes/helm/build.ts, garden-service/src/plugins/kubernetes/helm/common.ts, garden-service/src/plugins/kubernetes/helm/deployment.ts, garden-service/src/plugins/kubernetes/helm/logs.ts, garden-service/src/plugins/kubernetes/helm/run.ts, garden-service/src/plugins/kubernetes/helm/status.ts, garden-service/src/plugins/kubernetes/helm/test.ts, garden-service/src/plugins/kubernetes/helm/tiller.ts, garden-service/src/plugins/kubernetes/hot-reload.ts, garden-service/src/plugins/kubernetes/init.ts, garden-service/src/plugins/kubernetes/kubernetes.ts, garden-service/src/plugins/kubernetes/namespace.ts, garden-service/src/plugins/kubernetes/secrets.ts, garden-service/src/plugins/kubernetes/status.ts, garden-service/src/plugins/kubernetes/test.ts, garden-service/src/plugins/openfaas/openfaas.ts, garden-service/test/src/plugins/kubernetes/container/ingress.ts
This is to facilitate use of the `KubeApi` class e.g. in integration tests, where some k8s operations need to be run outside of a Garden project.
=> refactor: split provider from KubeApi

garden-service/test/integ-helpers.ts, garden-service/test/integ/src/pre-release.ts
Just a quick tweak that came to mind since I've been looking into the build dir / the `.garden` dir.
Removing the `.garden` dirs of the projects used before running the integration tests makes for a more neutral/standardised initial state.
=> fix(integ-tests): helper to remove .garden dirs

garden-service/src/plugins/container/config.ts, garden-service/src/plugins/kubernetes/container/handlers.ts, garden-service/src/plugins/kubernetes/kubernetes.ts, garden-service/src/plugins/maven-container/maven-container.ts
This fix is quite ugly, but will be handled better after pending
framework changes that better accommodate module-type customizations.
=> fix(k8s): validation error on maven-container modules

examples/simple-project/services/node-service/garden.yml, garden-service/src/plugins/kubernetes/container/ingress.ts, garden-service/test/unit/src/plugins/kubernetes/container/ingress.ts
Before this fix, services defining multiple ingresses would only have the last configured ingress deployed to the cluster (since each ingress for a given service had `metadata.name = service.name`).
=> fix: use unique names for a service's ingresses

garden-service/bin/build-pkg.sh
We need this to be able to run Garden in an alpine Docker container.
=> chore: add alpine as build target

garden-service/src/actions.ts, garden-service/src/commands/run/task.ts, garden-service/src/commands/run/test.ts, garden-service/src/plugins/kubernetes/container/handlers.ts, garden-service/src/plugins/kubernetes/container/run.ts, garden-service/src/plugins/kubernetes/container/test.ts, garden-service/src/plugins/kubernetes/helm/run.ts, garden-service/src/plugins/kubernetes/helm/test.ts, garden-service/src/plugins/kubernetes/task-results.ts, garden-service/src/plugins/kubernetes/test.ts, garden-service/src/tasks/deploy.ts, garden-service/src/tasks/task.ts, garden-service/src/tasks/test.ts, garden-service/src/types/plugin/outputs.ts, garden-service/src/types/plugin/params.ts, garden-service/src/types/plugin/plugin.ts, garden-service/test/unit/src/actions.ts
Added caching for task results. Similarly to the caching for test runs that was already in place, these are stored by version as `ConfigMap`s.
The version used to index these results includes the task's module's current version, along with the module versions of the task's runtime dependencies (if any). This is the same formula that is used for
computing test task versions.
A versioning bug was also fixed for the test result caching functionality. Here, the version used was just the test config's module's version, whereas now the corresponding test task's version
is used to index it instead (the same as is now also used to cache task results).
=> feat(k8s): cache task results

docs/reference/module-types/kubernetes.md, examples/kubernetes-module/README.md, examples/kubernetes-module/garden.yml, examples/kubernetes-module/postgres/garden.yml, examples/kubernetes-module/redis/garden.yml, examples/kubernetes-module/redis/redis.yml, garden-service/src/docs/config.ts, garden-service/src/plugins/kubernetes/kubernetes-module/config.ts, garden-service/src/plugins/kubernetes/kubernetes-module/handlers.ts, garden-service/src/plugins/kubernetes/kubernetes.ts
For those times when you want to deploy your own manifests, but don't
need the features and complexity of Helm modules.
See the kubernetes-module example for usage.
=> feat(k8s): add kubernetes module type

garden-service/package-lock.json, garden-service/package.json, garden-service/src/config/module.ts, garden-service/src/vcs/base.ts, garden-service/test/unit/data/test-project-variable-versioning/garden.yml, garden-service/test/unit/data/test-project-variable-versioning/module-a/garden.yml, garden-service/test/unit/data/test-project-variable-versioning/module-b/garden.yml, garden-service/test/unit/src/vcs/base.ts
Module versions now also include a serialized version of the resolved module config (hashed together with versions / dirty timestamps).
This fixes an issue where changes to project variables used in a module's config would not result in the module's version changing when recomputed.
This was the case because the version was based only on the latest commit and dirty timestamp of the module in question, and those of its dependencies, which doesn't factor in changes to project-level variables.
=> fix: include resolved config in module version

README.md, docs/README.md, docs/examples/README.md, docs/examples/using-garden-in-ci.md
=> docs: add a guide for using Garden in ci

.github/ISSUE_TEMPLATE/BUG_REPORT.md
I figured it would make sense to add a field to the bug report template to demonstrate how to work around the issue until it has been resolved.
=> chore: add workaround field to Github issue template

garden-service/src/commands/run/module.ts, garden-service/src/commands/run/run.ts, garden-service/src/commands/run/service.ts
Before this fix, the run module and run service commands would fail if any of the corresponding module's services had a task dependency.
For example, `garden run module hello "node"` and `garden run service hello` in the `tasks` example project both failed before this change (because the `hello` service has a task dependency).
=> fix(run): correctly ignore task dependencies

dashboard/src/containers/sidebar.tsx
show dashboard links in sidebar while external providers dedicated screens are being loaded.
=> chore: show sidebar links before external plugins have been loaded

garden-service/src/vcs/git.ts
This fixes an error where flat projects (i.e. those with a module whose config is co-located with the project config, and that don't define an include pattern) could not be deployed.
=> fix(vcs): exclude .garden from version hashing

garden-service/src/vcs/git.ts, garden-service/src/watch.ts
This can happen routinely if, for example, editors create temporary files that are then quickly removed.
=> fix(vcs): handle case when file is removed while listing VCS files

garden-service/package-lock.json, garden-service/src/events.ts, garden-service/src/vcs/git.ts, garden-service/test/unit/src/vcs/git.ts
This fixes an issue with the new version hash calculation logic where tests would not be re-run even if their underlying module sources changed.
Because the relative paths being used were relativized from different starting directories (git root VS module root), the modified file paths weren't matching with the module file paths.
=> fix(vcs): fixed path handling for modified files

garden-service/src/commands/deploy.ts, garden-service/src/commands/dev.ts
Fixes https://github.com/garden-io/garden/issues/599.
Before, the deploy and dev commands didn't validate that the service names passed to the `--hot`/`--hot-reload` option referred to existing services.
Also moved some config-level validation in the dev command before the `prepareEnvironment` call for faster feedback on config errors.
=> fix(cli): detect missing services in --hot option

dashboard/src/api/types.ts, dashboard/src/components/graph/graph.scss, dashboard/src/components/graph/index.tsx, garden-service/src/events.ts, garden-service/src/task-graph.ts, garden-service/test/unit/src/task-graph.ts
Fixes https://github.com/garden-io/garden/issues/685.
Added a `taskProcessing` state & event to the stack graph & task graph.
Now, pending task nodes are shown with a solid red/pink border, while in-progress task nodes are shown with the spinning, dashed red/pink border. This gives a clearer overview of the current state of the task graph.
=> feat(dashboard): added taskProcessing state

docs/reference/commands.md, docs/using-garden/hot-reload.md, garden-service/src/commands/deploy.ts, garden-service/src/commands/dev.ts, garden-service/src/commands/helpers.ts
Passing an asterisk (`*`) to the `--hot`/`--hot-reload` option deploys all compatible services with hot reloading enabled (i.e. all services belonging to a module specifying the `hotReload` field).
Also throw an error before initializing the environment or proceeding with deployment if one or more service names passed to the `--hot`/`--hotReload` option aren't configured for hot reloading.
=> feat(cli): allow --hot=* in dev/deploy commands

dashboard/package-lock.json, dashboard/src/api/types.ts, dashboard/src/components/graph/index.tsx, garden-service/package-lock.json, garden-service/src/config-graph.ts, garden-service/src/task-graph.ts, garden-service/src/tasks/base.ts, garden-service/src/tasks/build.ts, garden-service/src/tasks/deploy.ts, garden-service/src/tasks/helpers.ts, garden-service/src/tasks/hot-reload.ts, garden-service/src/tasks/publish.ts, garden-service/src/tasks/push.ts, garden-service/src/tasks/task.ts, garden-service/src/tasks/test.ts, garden-service/test/unit/src/config-graph.ts, garden-service/test/unit/src/task-graph.ts
In the dashboard, we match the keys emitted with the event payload
against the node keys returned by the get graph command.
This commit adds a generic makeBaseKey function that both the Task
classes and the config graph render function use.
Previously we emitted the task key, as opposed to just the base key.
=> fix(task-graph): ensure graph node keys and event payload keys match

docs/reference/module-types/container.md, garden-service/src/plugins/container/container.ts
The link should be generated by Gitbook but for some reason is not. As a
result, the check-docs script always fails in CI. We've already contacted
Gitbook support but still waiting for a reply.
=> docs: link to Github for K8s  docs because Gitbook link is broken

garden-service/package-lock.json, garden-service/package.json, garden-service/src/vcs/git.ts, garden-service/test/unit/src/vcs/git.ts
This solves an issue where Garden would flood spawned processes with
a huge amount of source files. This could happen, for example, when
library directories (e.g. node_modules) weren't ignored.
=> fix(vcs): don't fork a process for every untracked file

garden-service/package-lock.json, garden-service/src/commands/run/task.ts, garden-service/src/logger/log-entry.ts, garden-service/src/process.ts, garden-service/src/task-graph.ts, garden-service/src/tasks/base.ts, garden-service/src/tasks/helpers.ts, garden-service/test/integ-helpers.ts, garden-service/test/integ/src/integ-helpers.ts, garden-service/test/integ/src/pre-release.ts, garden-service/test/run-garden.ts, garden-service/test/unit/src/task-graph.ts, garden-service/test/unit/src/tasks/helpers.ts
In short, `baseKey` is now called `key`, `key` is now called `id`, and `id` is now called `uid`. The same applies to the corresponding getter methods on `BaseTask`.
`baseKey` has always been a somewhat awkward term, and with some of the recent changes to the events emitted by the `TaskGraph`, it had started to become slightly confusing as well. The new terminology should be clearer and more intuitive.
=> refactor: rename task baseKey to key and key to id

garden-service/src/plugins/kubernetes/kubernetes.ts
This fixes a regression from a recent PR which caused provider config schema validations during environment status checks to fail.
=> fix(k8s): allow unknown fields in provider config

garden-service/test/integ-helpers.ts, garden-service/test/integ/src/integ-helpers.ts, garden-service/test/integ/src/pre-release.ts
Deleting app namespaces after each sequence seems to improve performance and reduce stalling (at least when executing locally).
=> test(integ): perf & cleanup improvements

garden-service/gulpfile.ts
The `build-container` gulp task is unnecessary for the standard `build` gulp task. However, we don't remove it, since it is still useful in other contexts (e.g. CI).
=> chore(build): skip build-container in build task

garden-service/src/actions.ts, garden-service/src/plugins/kubernetes/status.ts, garden-service/src/template-string-parser.pegjs, garden-service/test/unit/src/template-string.ts
This removes the previously deprecated ability to do nested formatting
strings. It's not a helpful feature for most cases, and just complicates
the parser logic. Also wasn't documented really, so it should be safe to
remove without a minor version bump.
=> fix(config): recursion error with invalid template strings

garden-service/src/config/common.ts
Allow empty strings as default values for env vars used in template strings. For example, `${someVar || ""}`.
Previously, this would lead to a validation error due to `joiPrimitive` not permitting empty strings.
=> fix(config): validation fix for template strings

garden-service/src/commands/get/get-config.ts, garden-service/src/commands/get/get-graph.ts, garden-service/src/commands/get/get-status.ts, garden-service/src/commands/get/get-task-result.ts, garden-service/src/commands/get/get-test-result.ts, garden-service/src/logger/log-entry.ts, garden-service/src/logger/renderers.ts, garden-service/src/logger/writers/json-terminal-writer.ts
When the JSON logger type is being used (via -`-logger-type=json`), command results are rendered to the log as JSON objects instead of YAML strings. This facilitates parsing e.g. by testing code and other instrumentation.
Highlighted YAML remains the default rendering method (e.g. for the basic and fancy loggers).
=> feat: render results as JSON for json logger

docs/using-garden/remote-clusters.md
Otherwise this will fail on e.g. the simple project with:
```
No hostname configured for one of the ingresses on service go-service. Please configure a default hostname or specify a hostname for the ingress.
```
=> document defaultHostname in using remote clusters

garden-service/src/process.ts
When running garden with the -w flag and specifying services or modules,
we now always also watch their build dependencies.
=> fix: build deps not watched when using -w flag

CONTRIBUTING.md
This PR fixes the path where to find the `garden-debug` executable which was (probably) outdated.
=> fix(docs): update the path to run garden-debug

garden-service/src/actions.ts, garden-service/src/cli/cli.ts, garden-service/src/commands/base.ts, garden-service/src/commands/get/get-status.ts
When the get status command is called with json or yaml as the output option, test and task statuses for the latest test/task versions are included in the command result.
=> feat: add test/task statuses to get status command

garden-service/src/actions.ts, garden-service/src/plugins/kubernetes/helm/tiller.ts, garden-service/src/plugins/kubernetes/init.ts, garden-service/src/plugins/kubernetes/system.ts, garden-service/src/plugins/openfaas/openfaas.ts, garden-service/src/types/service.ts
Before, Garden would not deploy Tiller to the project namespace nor create the system namespaces for the Kubernetes provider. This was because the Kubernetes provider doesn't have any system services.
I also used the chance to refactor `getEnvironmentStatus` and `prepareEnvironment` handlers for the K8s provider since the control flow was a bit hard to follow. In particular because `getEnvironmentStatus` triggers a call to `actions.getStatus` which again calls `getEnvironmentStatus` for the system context. This lead to some code paths never being executed which caused #773  and #770.
After the refactor, most of the logic is hoisted to the top level handlers and `getEnvironmentStatus` is no longer called recursively. 
Fixes #773.
Fixes #770.
=> fix(k8s): ensure env is prepared

garden-service/src/logger/renderers.ts, garden-service/src/logger/writers/fancy-terminal-writer.ts
Before this change the spinner was being updated at the wrong x coordinate which resulted in something like this:
Not sure why it broke in the first place though. Perhaps another left-pad-gate since this depends on Lodash's `padStart` function. Checking back in the version history (without npm installing) still produced the error so it looks like a `node_modules` thing. In any case I changed to the native `String.padStart` function for good measure.
=> fix(logger): fix spinner pos

garden-service/package-lock.json, garden-service/package.json
They seem to have pulled the 2.0 release that we had upgraded to.
=> chore: fix broken tmp-promise dependency

garden-service/package-lock.json, garden-service/src/cli/cli.ts, garden-service/src/cli/helpers.ts, garden-service/src/commands/base.ts, garden-service/src/commands/get/get-status.ts, garden-service/src/commands/update-remote/all.ts, garden-service/src/server/commands.ts, garden-service/test/helpers.ts, garden-service/test/unit/src/commands/build.ts, garden-service/test/unit/src/commands/call.ts, garden-service/test/unit/src/commands/delete.ts, garden-service/test/unit/src/commands/deploy.ts, garden-service/test/unit/src/commands/get/get-config.ts, garden-service/test/unit/src/commands/get/get-graph.ts, garden-service/test/unit/src/commands/get/get-secret.ts, garden-service/test/unit/src/commands/get/get-tasks.ts, garden-service/test/unit/src/commands/link.ts, garden-service/test/unit/src/commands/publish.ts, garden-service/test/unit/src/commands/run/module.ts, garden-service/test/unit/src/commands/run/service.ts, garden-service/test/unit/src/commands/run/task.ts, garden-service/test/unit/src/commands/scan.ts, garden-service/test/unit/src/commands/set.ts, garden-service/test/unit/src/commands/test.ts, garden-service/test/unit/src/commands/unlink.ts, garden-service/test/unit/src/commands/update-remote.ts, garden-service/test/unit/src/commands/validate.ts
Make global CLI options (such as `output`) available in the `opts` command parameter.
=> fix: make global CLI opts available to commands

dashboard/src/components/graph/index.tsx, dashboard/src/containers/graph.tsx, dashboard/src/context/data.tsx
Symptom: The dashboard stack graph resets when I click a node. For example, if a test is broken, so a node has a red border, and I click it, the color goes back to green. Same applies if I click something while some nodes are pending/processing.
Fix: merged the event status into the graph object (in graph container) being passed to the graph component(graph/index)
=> fix(dashboard): stackgraph loses ws status when drawn

dashboard/src/components/graph/index.tsx, dashboard/src/components/group-filter.tsx, dashboard/src/containers/graph.tsx, dashboard/src/context/ui.tsx
Useful for many cases such as making the filters still valid if the user leave the page and comes back
=> improvement(dashboard): add graph filters to global context

garden-service/src/util/util.ts
Fixes #768.
The issue was due the fact we hadn't specify any handler for the `error` event which is the one emitted if the process cannot be spawned (which is the case if the command doesn't exist).
The output now it's something like this (from the vote-helm example):
```bash
18:07 $ g deploy
Deploy 🚀  
✔ providers                 → Getting status... → Ready
✔ base-chart                → Building version v-0141b6cf9d... → Done (took 0.4 sec)
api-image                 → Getting build status...
✔ redis                     → Building version v-15f2b52f7f... → Done (took 1.6 sec)
✔ postgres                  → Building version v-4385910de3... → Done (took 1.4 sec)
result-image              → Getting build status...
vote-image                → Getting build status...
Failed building api-image. …
```
=> fix: crash when deploy and docker not installed

docs/reference/providers/kubernetes.md, garden-service/src/plugins/kubernetes/config.ts, garden-service/src/plugins/kubernetes/kubernetes.ts
Note that the base branch is `remote-build`. We can either merge this into that one or wait until #808 is merged and change the base branch to `master`.
I'll update the "Remote Cluster" docs in a separate PR to avoid link check errors.
=> feat(k8s): optionally enable ingress controll for remote k8s

garden-service/src/cli/cli.ts
The default value for the logger was specified to `fancy` which has big impact on performace.
=> perf: improve performance of logs command

garden-service/src/commands/call.ts
Before this commit, running `garden call some-service` when `some-service` defines no ingresses would result in a cryptic error message (`Cannot read property 'path' of undefined`).
Now, the command outputs `Service user has no active ingresses` in such cases instead.
=> fix: improved error messages for call command

garden-service/src/commands/base.ts, garden-service/src/commands/init.ts, garden-service/src/commands/run/task.ts, garden-service/src/logger/util.ts
Introduce a new function called logFooter() to be used instead of logHeader(). 
It's (for now) just a wrapper around logHeader with the only differences being semantically more clear and implementing a new flag for adding a new line at the end of the command.
It can be extendend if we need to add more fancy logging at the end of a command.
Fixes #769
=> fix: some commands terminate with double new line

garden-service/src/plugins/kubernetes/api.ts, garden-service/src/plugins/openfaas/openfaas.ts
Basically I've completely overhauled the API wrapper, so that it should
dynamically and consistently support any API resource properly. This is
much cleaner and more similar to how kubectl works internally, for example.
=> fix(k8s): fix various issues with Kubernetes API queries

garden-service/src/constants.ts, garden-service/src/plugins/google/google-cloud-functions.ts, garden-service/src/plugins/kubernetes/container/deployment.ts, garden-service/src/plugins/kubernetes/kubernetes-module/handlers.ts, garden-service/src/plugins/kubernetes/namespace.ts, garden-service/src/plugins/kubernetes/system.ts, garden-service/src/util/string.ts
Cleaned up our annotations code slightly along the way. The actual fix is
in `garden-service/src/plugins/kubernetes/system.ts`, a rather simple one.
Fixes #818
=> fix(k8s): unhelpful error with conflicting namespace

examples/demo-project/garden.yml
It fell between the cracks when we re-named from simple-project.
=> chore(demo-project): re-insert remote env

docs/reference/module-types/container.md, docs/reference/module-types/maven-container.md, garden-service/package-lock.json, garden-service/src/commands/run/module.ts, garden-service/src/plugins/container/config.ts, garden-service/src/plugins/container/helpers.ts, garden-service/src/plugins/kubernetes/container/deployment.ts, garden-service/src/plugins/kubernetes/container/run.ts, garden-service/src/plugins/kubernetes/container/test.ts, garden-service/src/plugins/kubernetes/helm/config.ts, garden-service/src/plugins/kubernetes/helm/run.ts, garden-service/src/plugins/kubernetes/hot-reload.ts, garden-service/src/plugins/kubernetes/run.ts, garden-service/src/types/plugin/module/runModule.ts, garden-service/test/helpers.ts, garden-service/test/unit/src/actions.ts
Added `command` and `hotReloadCommand` fields to container module configs to go with `args` and `hotReloadArgs`  (on services, test configs and tasks).
For the k8s plugins, `command` corresponds to the `command` field on k8s podspecs, i.e. it's the "entrypoint" which `args` are passed to.
This is useful e.g. when some other entrypoint than `/bin/sh -c` is desired.
Closes https://github.com/garden-io/garden/issues/401.
=> feat(container): add command option

examples/gatsby-hot-reload/.dockerignore, garden-service/src/commands/base.ts, garden-service/src/commands/get/get-debug-info.ts, garden-service/src/config/base.ts, garden-service/src/constants.ts, garden-service/src/garden.ts, garden-service/src/types/module.ts, garden-service/src/util/fs.ts, garden-service/src/watch.ts, garden-service/test/helpers.ts, garden-service/test/unit/data/test-project-duplicate-yaml-file-extensions/garden.yaml, garden-service/test/unit/data/test-project-duplicate-yaml-file-extensions/garden.yml, garden-service/test/unit/data/test-project-yaml-file-extensions/garden.yaml, garden-service/test/unit/data/test-project-yaml-file-extensions/module-no-config/foo.yml, garden-service/test/unit/data/test-project-yaml-file-extensions/module-yaml/garden.yaml, garden-service/test/unit/data/test-project-yaml-file-extensions/module-yml/garden.yml, garden-service/test/unit/src/build-dir.ts, garden-service/test/unit/src/commands/get/get-debug-info.ts, garden-service/test/unit/src/garden.ts, garden-service/test/unit/src/util/fs.ts, garden-service/test/unit/src/watch.ts
With this PR, users can now name their Garden config files either `garden.yml` or `garden.yaml`.
Closes #562
=> feat(core): allow .yaml endings for Garden config files

docs/README.md
If a link is not included in the "SUMMARY" file, it won't work correctly
and will point to Github instead of docs.garden.io. Our "SUMMARY" file
is the docs/README.md file. This can be configured in the
`.gitbook.yaml` config file.
=> docs: add missing links to summary

docs/reference/commands.md, examples/vote-helm/postgres/garden.yml, garden-service/src/actions.ts, garden-service/src/commands/delete.ts, garden-service/test/unit/src/commands/delete.ts
This addresses issues where services contain resources that the provider
isn't directly aware of, e.g. when Helm charts deploy cluster-wide resources.
Closes #855
=> fix(delete-env): delete services before calling cleanupEnvironment

docs/reference/module-types/container.md, docs/reference/module-types/maven-container.md, docs/using-garden/configuration-files.md, examples/demo-project/README.md, examples/project-variables/README.md, examples/project-variables/backend/.dockerignore, examples/project-variables/backend/.gitignore, examples/project-variables/backend/Dockerfile, examples/project-variables/backend/garden.yml, examples/project-variables/backend/webserver/main.go, examples/project-variables/frontend/.dockerignore, examples/project-variables/frontend/Dockerfile, examples/project-variables/frontend/app.js, examples/project-variables/frontend/garden.yml, examples/project-variables/frontend/main.js, examples/project-variables/frontend/package.json, examples/project-variables/frontend/test/integ.js, examples/project-variables/garden.yml, garden-service/src/plugins/container/config.ts, garden-service/src/plugins/kubernetes/container/deployment.ts, garden-service/src/plugins/kubernetes/container/logs.ts, garden-service/src/plugins/local/local-google-cloud-functions.ts, garden-service/test/integ/garden.yml, garden-service/test/unit/src/plugins/container.ts, garden-service/test/unit/src/plugins/kubernetes/container/ingress.ts
Also added `project-variables` project to showcase the usage.
_Note: This is based off the template-string-improvement branch, since that was necessary to complete this. Please review but don't merge._
=>  feat(container): allow configuring # of replicas for container services

docs/reference/config.md, docs/reference/module-types/container.md, docs/reference/module-types/exec.md, docs/reference/module-types/helm.md, docs/reference/module-types/kubernetes.md, docs/reference/module-types/maven-container.md, docs/reference/module-types/openfaas.md, docs/reference/providers/kubernetes.md, docs/reference/providers/local-kubernetes.md, docs/reference/providers/local-openfaas.md, docs/reference/providers/maven-container.md, docs/reference/providers/openfaas.md, garden-service/src/bin/generate-docs.ts, garden-service/src/config/module.ts, garden-service/src/docs/config.ts, garden-service/src/docs/templates/config-partial.hbs, garden-service/src/docs/util.ts, garden-service/src/plugins/container/config.ts, garden-service/test/unit/src/docs/config.ts
=> docs: improve handling and display of default values in reference docs

garden-service/src/garden.ts, garden-service/src/util/util.ts, garden-service/src/watch.ts, garden-service/test/mocha.integ.opts, garden-service/test/mocha.opts
Turns out chokidar and the native fsevents module don't like it when multiple
instances are created in a single process, even if one is closed before the
other starts. Fixed it by making a global instance and reconfiguring on
reload instead. See https://github.com/fsevents/fsevents/issues/273 for
a discussion on this issue.
=> fix(core): chokidar watcher on mac could segfault after reloading config

garden-service/src/actions.ts, garden-service/src/plugins/container/container.ts, garden-service/src/plugins/container/publish.ts, garden-service/src/plugins/kubernetes/constants.ts, garden-service/src/plugins/kubernetes/container/build.ts, garden-service/src/plugins/kubernetes/container/handlers.ts, garden-service/src/plugins/kubernetes/container/publish.ts, garden-service/src/plugins/kubernetes/container/util.ts, garden-service/src/types/plugin/outputs.ts, garden-service/src/types/plugin/params.ts, garden-service/src/types/plugin/plugin.ts, garden-service/test/unit/src/actions.ts, garden-service/test/unit/src/commands/publish.ts, garden-service/test/unit/src/plugins/container.ts
This has the caveat that you need to have a local Docker daemon running.
Avoiding that requirement would take much more work, since we'd need to
tackle all manner of authentication/key management issues.
=> fix(k8s): enable publishing container modules when using remote builders

support/install.ps1
I tried installing Garden on Windows and got the following error:
`Invoke-WebRequest : The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first launch configuration is not complete. Specify the UseBasicParsing parameter and try again.`
This commit fixes that.
=> fix(install): Add -UseBasicParsing to Windows installer

docs/using-garden/remote-clusters.md, garden-service/src/actions.ts, garden-service/src/commands/init.ts, garden-service/src/plugins/kubernetes/commands/cluster-init.ts, garden-service/src/plugins/kubernetes/helm/tiller.ts, garden-service/src/plugins/kubernetes/init.ts, garden-service/src/plugins/kubernetes/kubernetes.ts, garden-service/src/plugins/kubernetes/status/status.ts, garden-service/src/types/plugin/provider/getEnvironmentStatus.ts, garden-service/src/types/plugin/provider/prepareEnvironment.ts
This avoids complications relating to differing provider configurations
and Garden versions, by removing cluster-wide init from the standard
`garden init` flow and making it an explicit plugin command.
`local-kubernetes` environments are not affected by this, since they are
not shared between users/CI/etc.
=> improvement(k8s): add explicit cluster-init command for remote clusters

README.md
In #quick-start of the README we mention the `demo-project` but still have the commands for `simple-project`. I'm assuming we want to use the ones for `demo-project` as that's @edvald 's latest change to the README.
=> docs: wrong example in readme

docs/examples/demo-project.md
While following the demo-project tutorial, reaching this step:
https://docs.garden.io/examples/demo-project#communication-between-services:
I ended up getting the following error from the frontend service at http://demo-project.local.app.garden/call-backend: 
```
{
error: {
name: "RequestError",
message: "Error: connect ECONNREFUSED 127.0.0.1:80",
cause: {
errno: "ECONNREFUSED",
code: "ECONNREFUSED",
syscall: "connect",
address: "127.0.0.1",
port: 80
},
error: {
errno: "ECONNREFUSED",
code: "ECONNREFUSED",
syscall: "connect",
address: "127.0.0.1",
port: 80
},
options: {
uri: "http://demo-project.local.app.garden/hello-backend",
method: "GET",
simple: true,
resolveWithFullResponse: false,
transform2xxOnly: false
}
},
message: "Unable to reach service at …
```
=> docs: fix backend service URL in demo project

examples/vote/services/postgres/garden.yml
The single quote in the `CREATE TABLE` statement were making the service fail on deploy.
=> fix: removed single quote from CREATE TABLE statement

garden-service/src/plugins/kubernetes/local/minikube.ts
https://github.com/garden-io/garden/issues/907
=> fix(k8s): skip setMinikubeDockerEnv when vm-driver=None

docs/basics/installation.md
Points users to the contributor guide in case they want to install from scratch. Also documents the need to have `static` in the same directory as the `garden` binary.
https://github.com/garden-io/garden/issues/732
=> docs: add info for manual installations

garden-service/static/kubernetes/system/registry-proxy/templates/daemonset.yaml
Run `garden plugins kubernetes cluster-init` for your environment after
upgrading to deploy the change.
=> fix(k8s): cluster registry only worked when service CIDR was 10.x.x.x/y

.circleci/config.yml, garden-service/src/task-graph.ts
The `GARDEN_TASK_CONCURRENCY_LIMIT` env variable can now be used to override the task graph's default concurrency limit. Values should be integers.
Also set this env variable to 10 in our CircleCI config.
=> feat: add env var for setting max task concurrency

dashboard/src/components/graph/graph.scss, dashboard/src/components/graph/index.tsx, dashboard/src/context/events.tsx, dashboard/src/styles/variables.ts, garden-service/src/events.ts, garden-service/src/task-graph.ts, garden-service/test/unit/src/task-graph.ts
Emit taskCancelled events when dependants of failed tasks are cancelled.
This is a new event type.
Closes #925.
=> fix(task-graph): emit and handle taskCancelled events

package-lock.json, package.json
**fix**
When running `npm install` with the latest version of node, `fsevents` library would throw errors.
The current version of `chokidar` we use requires some libraries, which require a very old version of the library. This PR brings requires the latest version of `fsevents` explicitly so we satisfy the dependency and fix the error (see #947).
Fixes #947
Nope
=> fix: declare latest version of fsevents explicity

garden-service/src/task-graph.ts, garden-service/test/unit/src/task-graph.ts
Before this fix, the first task to become pending for a given key was the one chosen by the deduplication process, instead of the last added task.
Now, when a task is added and there's already a pending task with the same key, the previously pending task is effectively replaced with the new task, ensuring that the last added task is the one that gets processed.
=> fix(task-graph): use latest version for dedup

garden-service/src/plugins/kubernetes/container/publish.ts
**fix**: A bug fix.
Publish command would fail for images built remotely since they will have different names than what's needed for the registry that's being published to. We might e.g. pull something like: `local.app.garden:53113/eysi-demo-project/backend:v-d8c8e24c77` but need to push something like: 
`eu.gcr.io/garden-dev-200012/backend:v-d8c8e24c77`. This PR resolves that.
Fixes #960
=> fix(k8s): ensure images built remotely are tagged before publishing

package.json
* **chore**: Changes to the build process or auxiliary tools and libraries such as documentation 
With this PR we no longer run integ tests before pushing. We're already running more comprehensive integ tests in CI so these are kind of superfluous and just slow us down.
=> chore: don't run integ tests before push

README.md, docs/using-garden/in-cluster-building.md, examples/demo-project/garden.yml, garden-service/static/kubernetes/system/docker-daemon/templates/volume.yaml, garden-service/static/kubernetes/system/docker-daemon/values.yaml
**fix**: A bug fix.
The storage size for the `garden-docker-data` PVC wasn't being populated by the value set in the project level `garden.yml` (under the `provider.storage.builder.size` field).
Fixes #956
=> Fix builder storage

garden-service/src/plugins/kubernetes/commands/cleanup-cluster-registry.ts, garden-service/src/plugins/kubernetes/container/build.ts
Previously, workspace directories that we synced to the cluster for in-cluster building would just pile up. Now they are cleaned up when you run `garden plugins kubernetes cleanup-cluster-registry`
=> improvement(k8s): cluster cleanup command now also cleans build sync dir

garden-service/src/build-dir.ts, garden-service/src/garden.ts, garden-service/src/tasks/build.ts, garden-service/src/vcs/vcs.ts, garden-service/test/unit/src/build-dir.ts, garden-service/test/unit/src/vcs/vcs.ts
This notably cascades neatly to anything that syncs _from_ the build
directory, so there should be no further action needed in e.g.
hot-reloading or remote-building code.
Fixes #968
=> fix(core): respect includes/excludes when syncing to build directory

.circleci/config.yml, CONTRIBUTING.md, bin/release.ts, garden-service/bin/build-pkg.sh, package-lock.json, package.json
* **chore**: Changes to the build process or auxiliary tools and libraries such as documentation generation.
With this PR we add more automation to our release process. In particular, we now publish releases _from CI_ as oppose to downloading the build artifacts from CI and uploading to Github manually. If the release is a pre-release it get's published automatically, otherwise a draft is created that needs to be published manually.
Furthermore, we now publish releases with the version tag `next` on every merge to `master`. 
See `CONTRIBUTING.md` for more details.
=> chore: automate release process

.circleci/config.yml
* **ci**: Changes to the CI configuration.
Because of an issue with the `npm run boostrap` command (and by extension lerna), we can't use pre-release versions in package.json. See #972.
We therefore flag all releases as pre-releases until the above is resolved,
=> ci: always flag releases as drafts and pre-releases

garden-service/src/bin/add-version-files.ts, garden-service/src/build-dir.ts, garden-service/src/types/module.ts
The error was caused by the use of absolute path in .garden-version
files. This needs a more complete overhaul and testing to avoid future
issues, but does the trick for now.
=> fix(core): rsync error when running from dist build

garden-service/gcloud.Dockerfile
This includes a change on the dockerfile for the garden-dev image. The old version would put in the PATH only the `gcloud` executable, while other ones might be needed.
I was having an issue when trying to build an image and push it to gcr. The command
`gcloud auth configure-docker` will not work if `docker-credential-gcloud` is not in the path.
None
No
=> improvement: updated PATH to include all gcloud bin-s

.circleci/config.yml, CONTRIBUTING.md, bin/release.ts
* **chore**: Changes to the build process or auxiliary tools and libraries such as documentation generation.
This fixes issue were lerna bootstrap would fail because the dashboard couldn't find the garden-service package.
Fixes #972
=> chore: use lerna to update version (as opposed to npm)

.github/PULL_REQUEST_TEMPLATE.md
* **chore**: Changes to the build process or auxiliary tools and libraries such as documentation generation.
Removes the **What type of PR is this** section seen above. It's superfluous since the commit messages already contain the type.
=> chore: remove PR type section from PR template

bin/release.ts
After we switched to using `lerna` for updating the version, the dashboard package.json is updated as well but the release didn't account for that.
=> chore: include dashboard package.json in release commit

docs/using-garden/remote-kubernetes.md, garden-service/src/actions.ts, garden-service/src/commands/delete.ts, garden-service/src/plugins/kubernetes/commands/uninstall-garden-services.ts, garden-service/src/plugins/kubernetes/init.ts, garden-service/src/plugins/kubernetes/kubernetes.ts
This cleans up everything in the garden-system namespace, as well as
related cluster-wide resources.
=> feat(k8s): add uninstall-garden-services command

garden-service/src/config/base.ts, garden-service/test/unit/data/test-projects/empty-doc/garden.yml, garden-service/test/unit/src/config/base.ts
Before, we'd throw an error if you'd, for example, end a `garden.yml` with a `---` line. Now we just ignore empty docs in multi-doc YAMLs.
=> fix(config): ignore empty docs in garden.yml files

examples/istio/reviews/templates/reviews.yaml, examples/kubernetes-module/redis/redis.yml, garden-service/src/plugins/kubernetes/container/deployment.ts
See https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
=> fix(k8s): update deprecated Deployment API versions ahead of 1.16

.github/ISSUE_TEMPLATE/BUG_REPORT.md
Remove the instructions to attach output of `garden get debug-info`. 
At the current stage the command output might contain sensitive info and needs to be reworked before asking our users to use it again.
This is a first workaround for #1024
no
=> improvement: removed get debug-info request

garden-service/src/plugins/kubernetes/hot-reload.ts, garden-service/test/helpers.ts, garden-service/test/unit/src/plugins/kubernetes/hot-reload.ts
This PR fixes two issues with hot reloading on Windows:
1. Copy command that runs inside container was being normalized with respect to platform. So we'd get Windows paths inside the container.
2. Trailing slash was missing for copy source on Windows. 
Fixes #1015
=> fix(hot-reload): fix path handling for Windows and add tests

garden-service/src/plugins/container/build.ts
Docker has special syntax where blank build args make it pull that key from the environment. We currently pass build args explicitly as null when they are.
Fixes #1023
=> fix: handle blank build args appropriately

garden-service/gcloud.Dockerfile
This PR add the installation of `kubectl` in our gcloud image. It's useful to have available and it's required in other applications.
None
No
=> improvement: install kubectl in garden-gcloud image

garden-service/src/vcs/git.ts, garden-service/test/unit/src/vcs/git.ts
This PR fixes #1029, which was caused by bad handling of symlink when initializing garden.
Fixes #1029
We use the git client to retrieve all the files from a project, from where to extract then the module config paths. The current implementation then doesn't allow the use of symlinks: the git client will never resolve a symlink if it's a directory. It will always treat it as file and (this is now fixed/prevented) would try to hash it using the node streams, failing.
From a design point of view, I am not 100% aware of all the reasons behinf choosing `git ls-files` instead of something else. What I find strange is the jump from "using a library" to retrieve files and "using bare …
=> fix: exclude symlinks to directories from hashing

garden-service/src/plugins/kubernetes/helm/deployment.ts, garden-service/src/plugins/kubernetes/helm/helm-cli.ts
=> fix(k8s): avoid "no deployed releases" errors after Helm install failure

garden-service/src/commands/base.ts, garden-service/src/garden.ts, garden-service/src/plugins/kubernetes/system.ts
This would routinely come up when one or more tasks fail in execution.
=> fix: fix 'cannot read property error of null' error

garden-service/src/plugins/kubernetes/util.ts
Previously we'd get the old ReplicaSet lumped in when checking Pod statuses, which could cause failures to reported based on those older versions.
=> fix(k8s): ignore older ReplicaSet Pods when checking Deployment status

garden-service/bin/build-pkg.sh
Makes the static directory a git repo. This is because Garden in general expects projects to be git repos. Now the static directory contains the garden-system project and it's simply easier to turn it into a git repo instead handling a bunch of special cases.
=> chore(dist): make static dir a git repo

.circleci/config.yml
The previous version ran the Garden bin from the `garden` root dir which is a git repo. Turns out, that bypassed a bug which only crops up if the binary is not in a git repo at all. So now we've moved the binary to the `$HOME/.garden` dir.
=> ci: move garden bin to HOME dir in test-dist job

bin/release.ts
...and make sure release script updates package-lock.json
Had to fix how execa was called due to recent update of deps in the root level package.json. Also, contains a hacky way to update package-lock files via lerna. Here's the issue and workaround: lerna/lerna#1415
=> chore: update release script due to deps updates

docs/reference/module-types/container.md, docs/reference/module-types/maven-container.md, garden-service/src/plugins/container/config.ts, garden-service/src/plugins/kubernetes/container/service.ts, garden-service/test/unit/src/plugins/kubernetes/container/service.ts
This allows the cluster to automatically pick a nodePort, which is
often preferable to hard-coding it.
Closes #1057 
cc @Eronarn
=> fix(container): allow setting nodePort=true on container modules

garden-service/src/commands/run/module.ts, garden-service/src/commands/run/service.ts, garden-service/src/plugins/kubernetes/run.ts
Basically running interactive commands via `garden run module` or `garden run service` was busted, after some refactors. Not sure how to best automate tests around this tbh, but it's something we need to look out for.
Please try messing with the run commands in a few different ways, and see if you find any issues, even related issues.
=> fix(run): interactive run module/service commands not working

docs/reference/commands.md, garden-service/package-lock.json, garden-service/src/actions.ts, garden-service/src/cli/cli.ts, garden-service/src/commands/get/get-debug-info.ts, garden-service/src/plugins/kubernetes/kubernetes.ts, garden-service/src/types/plugin/provider/getDebugInfo.ts, garden-service/src/util/fs.ts, garden-service/test/unit/src/commands/get/get-debug-info.ts, garden-service/test/unit/src/vcs/git.ts
As reported by @Eronarn, the `garden get debug-info` command might include sensitive data in the output file. This PR introduces a lot more logging in order to inform the user on what it is been extracted. It also changes the behaviour of the command when it comes to export data from the kubernetes cluster: by default the command will only dump data from the `garden-system` and `garden-system--metadata` namespaces. If the user uses the new flat `--include-project`, the command will dump the configuraition for the entire project as well. 
Fixes #1024
@eronarn to run the PR code you please follow this steps:
- `git clone git@github.com:garden-io/garden.git`
- `cd garden`
- `npm …
=> improve: get debug-info output

garden-service/src/server/commands.ts, garden-service/test/unit/src/server/server.ts
Previously we were creating a new Garden instance for every command that needed to be executed when receiving API calls from the Dashboard. This was because of the way we were resolving modules in the past.
Recent changes to how we resolve providers made this very slow so now we're just using the Garden instance already available to the server instead of creating a new one. This should be fine now, thanks to improvements we've made to the task graph and module resolutions.
=> fix(server): re-use Garden instance when running commands for API calls

garden-service/src/bin/add-version-files.ts, garden-service/src/commands/get/get-debug-info.ts, garden-service/src/events.ts, garden-service/src/garden.ts, garden-service/src/util/fs.ts, garden-service/src/vcs/git.ts, garden-service/src/vcs/vcs.ts, garden-service/src/watch.ts, garden-service/test/unit/src/util/fs.ts, garden-service/test/unit/src/vcs/git.ts, garden-service/test/unit/src/vcs/vcs.ts, garden-service/test/unit/src/watch.ts
Previously, we weren't handling large numbers of added/removed files well. We'd trigger **a lot** of version checks and updates. We now buffer additions of files and directories, and more optimally and consistently handle those changes.
This doesn't exactly fix #1077, which we should look more into, but it does help with many scenarios.
Please try to break this! Thrash the file watcher and see what comes up. Whether you find new or old issues, we should reproduce in tests and fix them in this PR.
Not for everyday use, but this has a significant performance benefit when adding/removing large directories, such as when vendoring dependencies (e.g. `npm install`).
=> improvement(watcher): adding/removing many files/dirs more performant

garden-service/src/plugins/kubernetes/util.ts
Whenever we retrieve logs with `garden logs` we assume the resource has a `selector`. This is not always true when we deal with Helm charts. This PR introduce a new function to determine a selector in case of an Helm chart. 
Please @edvald or @eysi09, do a sanity check to see if it makes sense. I did some tests with `stable/mysql` and some other charts and it "looks" like it's working but yeah, maybe you have some specific scenarios/charts in mind.
Fixes #1068
Well, it fixes an exception.
=> fix: exception when retrieving logs from helm resource

docs/reference/commands.md, garden-service/src/cli/cli.ts, garden-service/src/commands/base.ts, garden-service/src/commands/get/get-secret.ts, garden-service/src/commands/set.ts
Our current `get|set secret` commands are quite limited and seem to mostly cause confusion. E.g. in the `kubernetes-secrets` example, we recommend that people use kubectl for secrets.
This PR therefore hides the commands from `--help` output and adds an explanation to the docs.
Fixes #1094
=> chore: hide get|set secret commands for now

garden-service/src/vcs/git.ts, garden-service/test/e2e/src/pre-release.ts, garden-service/test/unit/src/vcs/git.ts
Previously we didn't initialise submodules for remote sources.
Fixes #463
=> fix(vcs): include submodules with remote sources

garden-service/src/plugins/kubernetes/local/config.ts, garden-service/src/plugins/kubernetes/local/minikube.ts
Contains fixes to two issues I ran into while trying to run Garden on minikube in CI. 
One issue was that Garden just hangs while trying to deploy the `kubernetes-dashboard` helm chart. Minikube already has a `dashboard` addon so now we just use that. This does mean that the link to the K8s dashboard is no longer visible on the Garden dashboard for minikube users.
I'll add a separate issue for that since it's a higher priority to be able to deploy a project to begin with.
=> Minikube fixes

docs/reference/module-types/container.md, docs/reference/module-types/maven-container.md, garden-service/src/plugins/container/build.ts, garden-service/src/plugins/container/config.ts, garden-service/src/plugins/container/container.ts, garden-service/src/plugins/container/helpers.ts, garden-service/src/plugins/kubernetes/container/build.ts, garden-service/src/plugins/local/local-google-cloud-functions.ts, garden-service/src/plugins/openfaas/config.ts, garden-service/test/unit/src/plugins/container/container.ts, garden-service/test/unit/src/plugins/container/helpers.ts
This allows users to control build timeouts per individual container module. This can be useful if certain builds are expected to take a long time.
=> feat(container): add build.timeout option

docs/reference/providers/kubernetes.md, docs/reference/providers/local-kubernetes.md, garden-service/src/plugins/kubernetes/config.ts, garden-service/src/plugins/kubernetes/init.ts, garden-service/src/plugins/kubernetes/kubernetes.ts, garden-service/static/kubernetes/system/build-sync/garden.yml, garden-service/static/kubernetes/system/nfs-provisioner/garden.yml
Previously, the `storage.sync.storageClass` parameter was silently
ignored. We now respect the parameter, and skip installing the NFS
provisioner if a storageClass is specified for the volume.
Fixes #1120
=> fix(k8s): allow user to configure own storageClass for build-sync volume

garden-service/bin/build-pkg.sh
Removes node_modules and package.json files from `dist` dir after building the package. If they're not removed, they get uploaded with the zip files when creating a release.
=> chore(build-script): remove node_modules and package files from dist dir

garden-service/src/commands/logs.ts, garden-service/src/logger/log-entry.ts, garden-service/src/logger/log-node.ts, garden-service/src/logger/logger.ts, garden-service/src/logger/renderers.ts, garden-service/src/logger/util.ts, garden-service/src/logger/writers/basic-terminal-writer.ts, garden-service/src/logger/writers/fancy-terminal-writer.ts, garden-service/src/server/commands.ts, garden-service/test/run-garden.ts, garden-service/test/unit/src/logger/log-entry.ts, garden-service/test/unit/src/logger/logger.ts, garden-service/test/unit/src/logger/renderers.ts
Previously, when calling `log.setState()`, `log.setSuccess()` etc, we would just overwrite the log message fields. This made it impossible to tell precisely when individual updates took place. Now we instead keep track of all updates in the `messageStates` field of the `LogEntry`. 
This way, we can look at a single entry, see when it was created, when it was updated, and when it completed.
This is e.g. useful for our own internal e2e tests to determine when tasks complete (cc @thsig ). Going forward, this will also allow us to completely replay an entire Garden run (e.g. at a different verbosity) without actually re-running Garden.
=> improvement(logger): store all message states

garden-service/src/plugins/container/config.ts
We were previously validating the path as a valid relative URI, which doesn't work with regexes, which are supported by e.g. nginx for URL rewrites.
Closes #1020
=> fix(container): allow any string as ingress path

garden-service/src/tasks/hot-reload.ts
Make it consistent with other tasks messages , close #985
=> fix(logger): display duration in seconds

garden-service/src/watch.ts
This avoids spamming logs at the debug log levels, since we now listen
for many events and only later filter them out.
Closes #1100.
=> fix(watcher): raise log level for watch events

garden-service/src/plugins/kubernetes/hot-reload.ts, garden-service/static/kubernetes/system/build-sync/templates/deployment.yaml, garden-service/test/unit/src/plugins/kubernetes/hot-reload.ts
This is mostly a security issue. We want to control the code we use,
instead of using a mutable tag maintained by a stranger. The code
is unchanged though, so this should have no effect for users.
Closes #666 👹
=> chore: use our own rsync image

garden-service/src/plugins/container/build.ts, garden-service/src/plugins/container/helpers.ts, garden-service/src/plugins/kubernetes/container/build.ts, garden-service/src/plugins/kubernetes/run.ts, garden-service/src/util/ext-tools.ts, garden-service/src/util/util.ts, garden-service/test/unit/src/plugins/container/container.ts
When using the fancy logger we only show one line at a time, but you
could use the basic logger to get the full log.
This should be helpful when debugging docker builds.
Closes #852
=> feat(container): output build log while building with debug log level

garden-service/src/commands/run/task.ts
The shape of the `TaskResult` output has changed and the logger was printing undefined instead fo the `TaskResult` output
Fixes #1137 
=> fix: running task would print undefined

garden-service/src/plugins/exec.ts
We were running exec module tests in the source path, and not the build path, which was inconsistent with exec tasks.
=> fix(exec): wrong cwd when running `exec` module tests

garden-service/src/config/common.ts, garden-service/test/unit/src/config/common.ts
This is to accommodate Java services that expect this format
(e.g. "some.var"). It's not expressly permitted in POSIX but is
apparently commonly used, so I see no reason to disallow it.
=> fix: allow dots in env variable names

garden-service/src/plugins/kubernetes/container/test.ts, garden-service/src/plugins/kubernetes/helm/test.ts, garden-service/src/plugins/kubernetes/task-results.ts, garden-service/src/plugins/kubernetes/test-results.ts, garden-service/src/types/plugin/task/runTask.ts
If users had cached test results, we weren't properly converting the old schema when reading the results. This would not have affected users on previous versions, this issue only affected the current master.
=> fix(k8s): error when retrieving older test results from cache

docs/reference/module-types/container.md, docs/reference/module-types/exec.md, docs/reference/module-types/helm.md, docs/reference/module-types/kubernetes.md, docs/reference/module-types/maven-container.md, docs/reference/module-types/openfaas.md, docs/reference/module-types/terraform.md, docs/reference/providers/kubernetes.md, docs/reference/providers/local-kubernetes.md, garden-service/src/config/config-context.ts, garden-service/src/docs/config.ts, garden-service/src/plugins/terraform/module.ts
We weren't rendering certain schemas properly, this fixes that and also slightly improves rendering of template string output references for module types and providers.
=> docs: fix and slightly improve rendering of module template ref docs

garden-service/src/types/plugin/base.ts
This caused breaking errors when retrieving outdated test results.
We may want to release this quickly as a hot patch release, it's
possible this is affecting a number of users.
cc @eysi09
=> fix: error in test result output schema

garden-service/src/tasks/task.ts
Fixes an issue where the `force` flag was not respected when running task tasks.
=> fix(tasks): respect force flag in task task

garden-service/src/vcs/git.ts
We now run fewer git commands to list files in a directory, and avoid
having to list every file before later filtering out ignored files.
We also use streaming to avoid any buffering issues, and for improved
efficiency.
Fixes #1162
=> fix(vcs): overflow error when repo contains large number of files

garden-service/src/plugins/kubernetes/test-results.ts
When storing or getting test results, ensure that the `garden-system--metadata` namespace exists.
This fixes an issue when using minikube (https://github.com/garden-io/garden/issues/1167), where this namespace wouldn't automatically be created during init, leading to errors when tests were run.
Fixes #1167.
=> fix(k8s): ensure sys metadata ns exists for tests

docs/using-garden/configuration-files.md, garden-service/src/config/config-context.ts, garden-service/src/template-string-parser.pegjs, garden-service/src/template-string.ts, garden-service/test/unit/src/config/config-context.ts, garden-service/test/unit/src/garden.ts, garden-service/test/unit/src/template-string.ts
This adds a variety of interesting possibilities for template string
expressions. The grammar is a reduced JavaScript grammar, with
some added restrictions on what is actually allowed (no insane
cross-type comparisons etc.). 
The whole list of operators is specified in the Configuration Files guide, along with some usage examples.
=> feat(config): add a number of new operators for template expressions

garden-service/src/cli/helpers.ts
This adds some extra headers to the `checkForUpdate` request and allows us to be able to filter better the requests on the backend side. 
Fixes #
=> improvement: added more headers to checkForUpdates

docs/basics/quick-start.md, docs/examples/demo-project.md, examples/demo-project/garden.yml
Added mentions of the `cluster-init` step for remote clusters to the _Quick Start_ and _Demo Project_ guides.
=> docs: mention cluster-init step

garden-service/src/plugins/kubernetes/helm/tiller.ts, garden-service/src/plugins/kubernetes/util.ts
Helm was returning an out-of-date manifest version for Tiller, which caused issues with Kubernetes 1.16. We patch it by converting the manifest version ourselves.
Fixes #1166
=> fix(k8s): helm returned deprecated manifest version for tiller

garden-service/src/plugins/kubernetes/container/logs.ts, garden-service/src/plugins/kubernetes/helm/logs.ts, garden-service/src/plugins/kubernetes/kubernetes-module/handlers.ts, garden-service/src/plugins/kubernetes/logs.ts, garden-service/src/plugins/kubernetes/util.ts, garden-service/src/plugins/openfaas/openfaas.ts, garden-service/src/util/ext-tools.ts
Previously we set the --namespace flag when applying the specified
resources. We now instead ensure the namespace property is set on every
relevant resource.
Also improved the log output when exec-ing external commands.
Fixes #1191
=> fix(kubernetes-module): handle namespace attribute correctly

docs/reference/module-types/helm.md, garden-service/src/plugins/kubernetes/helm/config.ts, garden-service/src/plugins/kubernetes/helm/deployment.ts, garden-service/src/plugins/openfaas/openfaas.ts, garden-service/test/unit/src/plugins/kubernetes/helm/config.ts
Previously we hard-coded a value of 600 seconds. This simply makes it configurable.
Closes #1200
=> feat(k8s): add timeout parameter to helm module type

.github/workflows/update-homebrew.yml
This is what might have caused the workflow to get stuck in `Starting your workflow run...`.
=> chore: runs-on option typo in workflow definition

dashboard/src/containers/entity-result.tsx, dashboard/src/containers/graph.tsx, dashboard/src/containers/logs.tsx, dashboard/src/containers/overview.tsx, dashboard/src/containers/sidebar.tsx, dashboard/src/contexts/api-handlers.ts, dashboard/src/contexts/api.tsx, dashboard/src/contexts/ws-handlers.ts
We were merging API responses to a stale version of the store
object. That got merged to the global store state, causing some changes
to be lost or overwritten.
This would cause the dashboard to not load at all and was flagged on our community Slack channel.
=> fix(dashboard): ensure fresh store state when merging data

.circleci/config.yml
This is just a very basic test that deploys the demo-project. Next step
is to bootstrap the npm project on Windows and run unit and (a subset of)
e2e tests.
This doesn't add much to the `test-dist` job currently but it's a first step towards proper Windows testing.
=> ci: test on Windows

garden-service/src/commands/run/task.ts, garden-service/src/garden.ts, garden-service/src/plugins/kubernetes/init.ts, garden-service/src/plugins/kubernetes/status/service.ts, garden-service/src/plugins/kubernetes/system.ts, garden-service/src/task-graph.ts, garden-service/src/tasks/base.ts, garden-service/src/tasks/resolve-provider.ts, garden-service/test/helpers.ts, garden-service/test/unit/src/plugins/exec.ts, garden-service/test/unit/src/plugins/terraform/terraform.ts
Basically we had mistyped the TaskResults object, so I made it
explicit that there may be a null value on a key, which is what happens
when a task is aborted after a dependency fails to execute.
=> fix(core): null reference error when an action with dependants failed

docs/using-garden/in-cluster-building.md
This was missing from our docs and has caused confusion among users.
=> docs: mention that remote builders don't support private registries

dashboard/src/components/ingresses.tsx, dashboard/src/components/view-ingress.tsx, dashboard/src/util/helpers.ts, dashboard/src/util/hooks.tsx, docs/reference/module-types/container.md, docs/reference/module-types/maven-container.md, garden-service/src/commands/call.ts, garden-service/src/plugins/container/config.ts, garden-service/src/plugins/kubernetes/container/ingress.ts, garden-service/src/tasks/deploy.ts, garden-service/src/types/service.ts, garden-service/test/unit/src/commands/call.ts
EDIT: Depends on #1234. Please review and merge that first. (This is because that one contains fixes that I hoped resolved the build error we were seeing. They don't. See comment below).
Allows the user to set the display URL for a service ingress that Garden prints in the console, displays in the Dashboard, and uses for the `call` command.
We need this because the URL is different from what Garden constructs from the ingress spec, e.g. because the user has a load balancer in front of the services that re-writes paths or secures them.
Closes #1185 
We've debated the name for the field and might still want to change it. Here are some contenders:
- `ingressUrl`
- `linkUrl`
- …
=> improvement(config): add linkUrl field

garden-service/src/plugins/kubernetes/logs.ts
In the case of no pods being found for a given service, the `getPodLogs`
promise would never resolve, causing the process to not exit properly.
Fixes #1226
=> fix(k8s): ensure get logs handler resolves

dashboard/src/api/actions.ts, dashboard/src/api/api.ts, dashboard/src/api/ws.ts, dashboard/src/containers/entity-result.tsx, dashboard/src/containers/graph.tsx, dashboard/src/contexts/api.tsx, dashboard/src/util/helpers.ts, garden-service/src/commands/get/get-task-result.ts, garden-service/src/commands/get/get-test-result.ts, garden-service/test/unit/src/commands/get/get-task-result.ts, garden-service/test/unit/src/commands/get/get-test-result.ts
Fixes a regression due to changes we made to shape of the output of task and test results. This caused the `get-task-result` and `get-test-result` commands to return empty output log. This also caused these not to load in the dashboard.
Fixes #1225
Fixes #1224
=> fix(commands): fix regression due to changes to test|task result output

bin/check-docs, docs/examples/demo-project.md, docs/examples/using-garden-in-ci.md, docs/reference/config.md, docs/reference/glossary.md, docs/reference/module-types/container.md, docs/reference/module-types/exec.md, docs/reference/module-types/helm.md, docs/reference/module-types/kubernetes.md, docs/reference/module-types/maven-container.md, docs/reference/module-types/openfaas.md, docs/reference/module-types/terraform.md, docs/reference/providers/kubernetes.md, docs/reference/providers/local-kubernetes.md, docs/using-garden/configuration-files.md, docs/using-garden/container-modules.md, docs/using-garden/in-cluster-building.md, docs/using-garden/remote-kubernetes.md, docs/using-garden/terraform.md, docs/using-garden/using-helm-charts.md, docs/using-garden/using-remote-sources.md, docs/using-garden/variables-and-templating.md, garden-service/src/docs/config.ts, garden-service/src/docs/templates/base-config.hbs, garden-service/test/unit/src/docs/config.ts, markdown-link-check-config.json, package-lock.json, package.json
`markdown-check-link` doesn't check internal header links. This is a
known issue (https://github.com/tcort/markdown-link-check/issues/65).
We therefore add a new tool to check for internal links and limit
markdown-check-link to external links.
The new tool is from the remark family of markdown tools and expects
anchor links to not include any special characters so we also had to
make appropriate changes to the docs generator functions.
Finally, this commit fixes broken links discovered because of these
fixes.
Fixes #1249
=> docs: ensure check-docs script checks internal header links

docs/reference/module-types/helm.md, garden-service/src/plugins/kubernetes/helm/config.ts
We were already accounting for this in the code, was just missing
from the validation schema.
=> fix(k8s): add missing command argument to helm module test schema

.circleci/config.yml, docs/reference/providers/kubernetes.md, docs/reference/providers/local-kubernetes.md, garden-service/src/plugins/kubernetes/commands/cluster-init.ts, garden-service/src/plugins/kubernetes/config.ts, garden-service/src/plugins/kubernetes/init.ts, garden-service/static/kubernetes/system/build-sync/garden.yml, garden-service/static/kubernetes/system/build-sync/templates/deployment.yaml, garden-service/static/kubernetes/system/build-sync/templates/volume.yaml, garden-service/static/kubernetes/system/build-sync/values.yaml, garden-service/static/kubernetes/system/docker-daemon/garden.yml, garden-service/static/kubernetes/system/docker-daemon/templates/deployment.yaml, garden-service/static/kubernetes/system/docker-daemon/values.yaml, garden-service/static/kubernetes/system/nfs-provisioner/Chart.yaml, garden-service/static/kubernetes/system/nfs-provisioner/README.md, garden-service/static/kubernetes/system/nfs-provisioner/garden.yml, garden-service/static/kubernetes/system/nfs-provisioner/templates/NOTES.txt, garden-service/static/kubernetes/system/nfs-provisioner/templates/_helpers.tpl, garden-service/static/kubernetes/system/nfs-provisioner/templates/clusterrole.yaml, garden-service/static/kubernetes/system/nfs-provisioner/templates/deployment.yaml, garden-service/static/kubernetes/system/nfs-provisioner/templates/rolebinding.yaml, garden-service/static/kubernetes/system/nfs-provisioner/templates/service.yaml, garden-service/static/kubernetes/system/nfs-provisioner/templates/serviceaccount.yaml, garden-service/static/kubernetes/system/nfs-provisioner/templates/storageclass.yaml, garden-service/static/kubernetes/system/nfs-provisioner/templates/volume.yaml, garden-service/static/kubernetes/system/nfs-provisioner/values.yaml
Enabling persistence hould avoid problems when pods
are evicted, e.g. due to resource constraints or node upgrades.
We're making the transition relatively seamless by creating a new
storage class, and switching from StatefulSet to Deployment (which
makes the underlying volume easier to manage and manipulate).
This needed a fork of the Helm chart, so we now need to track that
manually.
**Special notes for reviewer**:
I suggest trying this out on both a fresh cluster, and one that already had a previous version installed. Run `garden plugins kubernetes cluster-init` and afterwards make sure building works nicely, and the `garden-system` namespace looks as expected.
=> fix(k8s): avoid issues with NFS provisioner on node/pod eviction

garden-service/src/vcs/git.ts, garden-service/test/unit/src/vcs/git.ts
If you set `dotIgnoreFiles: []` in your project config, no modules would be found.
Just came across this myself.
=> fix(vcs): no files were found when dotIgnoreFiles was set to empty list

garden-service/src/plugins/kubernetes/init.ts
We used to keep the metadata namespace around when deleting environments, which was by design at the time but no longer makes sense, and just confuses users.
Closes #1266
=> improvement(k8s): also delete metadata namespace when cleaning up

docs/reference/providers/kubernetes.md, docs/reference/providers/local-kubernetes.md, garden-service/src/plugins/kubernetes/config.ts, garden-service/src/plugins/kubernetes/init.ts, garden-service/src/plugins/kubernetes/kubernetes.ts, garden-service/src/plugins/kubernetes/local/config.ts, garden-service/static/kubernetes/system/registry-proxy/garden.yml, garden-service/static/kubernetes/system/registry-proxy/templates/daemonset.yaml, garden-service/test/unit/src/plugins/kubernetes/container/ingress.ts
Enables users to set tolerations for the registry-proxy DaemonSet. From the docs:
> For setting tolerations on the registry-proxy when using in-cluster building.
The registry-proxy is a DaemonSet that proxies connections to the docker registry service on each node.
>
> Use this only if you're doing in-cluster building and the nodes in your cluster
have [taints](https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/).
Fixes #1279
The description for the individual toleration fields and the validation rules are derived from the [K8s API reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#toleration-v1-core).
=> feat: allow specifying tolerations for registry-proxy

docs/reference/module-types/container.md, docs/reference/module-types/maven-container.md, garden-service/src/plugins/container/config.ts, garden-service/src/plugins/kubernetes/container/deployment.ts, garden-service/src/plugins/local/local-docker-swarm.ts
Previously we implicitly expected an absolute path. Now we explicitly
make it relative to the module path, but also support absolute paths.
Also added some docs, warning against the usage of hostPath.
=> fix(k8s): hostPath is now relative to module source path

examples/demo-project/garden.yml, garden-service/src/build-dir.ts, garden-service/src/commands/get/get-debug-info.ts, garden-service/src/commands/get/get-eysi.ts, garden-service/src/garden.ts, garden-service/src/plugins/exec.ts, garden-service/src/plugins/kubernetes/container/build.ts, garden-service/src/plugins/kubernetes/hot-reload.ts, garden-service/src/plugins/kubernetes/local/config.ts, garden-service/src/plugins/kubernetes/local/microk8s.ts, garden-service/src/plugins/kubernetes/local/minikube.ts, garden-service/src/plugins/kubernetes/namespace.ts, garden-service/src/util/ext-tools.ts, garden-service/src/util/util.ts, garden-service/src/vcs/git.ts, garden-service/test/unit/src/garden.ts, garden-service/test/unit/src/util/util.ts
Previously, the error message was not visible when commands were executed via `execa` (see #1282 for an example). Furthermore `execa` and `spawn` would return different looking errors.
The `execa` error message looked like this:
Now both `execa` and `spawn` errors look like this:
In particular, the error itself is visible and the command and error are bold. (EDIT: Text is no longer bold, see comments below).
Fixes #1282, #1283 
I updated the commit to address an issue that just came up (#1283). I explain the changes in the comments below so that we can compare the different screenshots.
I suggest looking at the final changes as opposed to commit by commit. The tests should also …
=> Standardise errors

garden-service/src/actions.ts, garden-service/src/commands/delete.ts, garden-service/src/tasks/base.ts, garden-service/src/tasks/delete-service.ts
Short and sweet. The delete environment command now deletes services in dependency order.
That is, a service's _dependants_ are deleted before it itself is deleted.
Added a new task class, `DeleteServiceTask` to accomplish this. The `delete service` and `delete environment` commands now use this task internally instead of calling the action directly.
Resolves #1232.
Have a look at the `DeleteServiceTask` class (mostly the `getDependencies` method).
Try deploying e.g. the `vote` example, delete a service or two, then delete the environment, see if you approve of the minor tweaks to the log output here.
=> improvement(core): delete services in dep order

docs/reference/module-types/openfaas.md, docs/reference/providers/local-openfaas.md, docs/reference/providers/openfaas.md, garden-service/src/plugins/openfaas/config.ts, garden-service/src/plugins/openfaas/faas-cli.ts, garden-service/src/plugins/openfaas/openfaas.ts
Our faas-netes installation was out of date, which caused issues with Kubernetes 1.16. 
Also added some more configurability, which should allow users to make a more proper production-ready setup. See the updated docs for details.
Fixes #1306
=> improvement(openfaas): updated faas-netes and made more configurable

.circleci/config.yml, garden-service/src/build-dir.ts
We found rsync rename errors during testing on Windows. This is a workaround, that we only apply on Windows.
=> fix(sync): issue with build staging sync procedure on Windows

docs/guides/cert-manager-integration.md
The Guide for the cert-manager integration has a list which was syntacticly wrong in the markdonw file and rendered wrongly: `1) bla-bla` vs `1. bla-bla`.
=> docs: fix markdown list in cert-manager guide

garden-service/src/plugins/kubernetes/helm/build.ts, garden-service/src/plugins/kubernetes/helm/deployment.ts, garden-service/src/plugins/kubernetes/helm/status.ts
Turns out `helm status` doesn't do any meaningful comparison checks
on its own (in hindsight I really don't why I thought it did), so
updates to `helm` modules would get ignored without the `--force` flag.
We can rely on our version hash for comparison, however, since it
includes hashes of all the templates and the config passed to the
template.
Perhaps try messing with the `vote-helm` project, triggering reloads etc., and see if everything happens as expected.
=> fix(k8s): helm status check now compares Garden version

docs/reference/providers/kubernetes.md, docs/reference/providers/local-kubernetes.md, examples/demo-project/garden.yml, examples/vote/garden.yml, garden-service/src/plugins/kubernetes/config.ts, garden-service/src/plugins/kubernetes/container/build.ts, garden-service/static/kubernetes/system/docker-daemon/templates/deployment.yaml, garden-service/static/kubernetes/system/docker-daemon/values.yaml
This allows the user to use BuildKit, which in many cases offers
better performance than the standard builder, and will eventually
supplant the current default implementation.
Also updated the in-cluster docker daemon to 19.03.4, which addresses a bunch of BuildKit related issues.
=> feat(k8s): add `clusterDocker.enableBuildKit` option

docs/guides/cert-manager-integration.md, garden-service/src/plugins/kubernetes/integrations/cert-manager.ts
Fix the cert-manager logger appearing when the certManager.install property
was set to "false".
Bonus: fix triggering the creation of certificates when cert-manager is not installed
even if no certificates managed by cert-manager are present in the config.
Fixes #
=> fix: displaced/wrong logging when setting up cert-manager

docs/guides/remote-kubernetes.md, docs/guides/using-helm-charts.md, docs/reference/commands.md, docs/reference/config.md, docs/reference/module-types/container.md, docs/reference/module-types/maven-container.md, garden-service/src/analytics/analytics.ts, garden-service/src/cli/cli.ts, garden-service/src/commands/base.ts, garden-service/src/commands/build.ts, garden-service/src/commands/deploy.ts, garden-service/src/commands/dev.ts, garden-service/src/commands/init.ts, garden-service/src/commands/test.ts, garden-service/src/config/project.ts, garden-service/src/garden.ts, garden-service/src/plugin-context.ts, garden-service/src/plugins/container/config.ts, garden-service/src/plugins/kubernetes/container/deployment.ts, garden-service/src/plugins/kubernetes/container/logs.ts, garden-service/src/plugins/kubernetes/helm/deployment.ts, garden-service/src/plugins/kubernetes/hot-reload.ts, garden-service/src/plugins/kubernetes/kubectl.ts, garden-service/src/plugins/kubernetes/kubernetes-module/handlers.ts, garden-service/test/integ/src/plugins/kubernetes/util.ts, garden-service/test/unit/src/config/project.ts
Implements a `environments[].production` flag which alters the generated manifests for the container modules and put protections on a subset of garden commands.
Fixes #
WIP: Needs refactoring and more tests + the commands protection implementation.
Just putting it out here so we can review it fast.
=> feat: production flag

garden-service/src/build-dir.ts
Forgot to normalize the path we use for the local build sync temp directory, so we got permission errors in testing.
=> fix(windows): normalize path for sync temp directory

garden-service/static/kubernetes/system/build-sync/templates/deployment.yaml
We've observed Kubernetes killing the rsync pods, and suspect this may
have something to do with the probes.
=> improvement(k8s): tune probes for build-sync pods

README.md
The `Using Garden` link on the README is broken.
=> fix: broken link to 'Using Garden' page

garden-service/src/plugins/kubernetes/system.ts, garden-service/src/tasks/base.ts, garden-service/src/tasks/build.ts, garden-service/src/tasks/delete-service.ts, garden-service/src/tasks/deploy.ts, garden-service/src/tasks/get-service-status.ts, garden-service/src/tasks/stage-build.ts, garden-service/test/unit/src/commands/build.ts, garden-service/test/unit/src/commands/deploy.ts, garden-service/test/unit/src/commands/publish.ts, garden-service/test/unit/src/server/server.ts, garden-service/test/unit/src/tasks/helpers.ts
Because both the BuildTask and GetServiceTask need to stage builds,
they could in some cases end up stepping on each other because one
doesn't depend on the other. I resolved that by adding a StageBuildTask
that both depend on.
I also made DeleteService depend on a StageBuildTask to ensure that
sources are synced before attempting to run deleteService handlers,
which had caused a couple of reported issues.
Fixes #1189
Fixed #1245
=> fix(build): fix intermittent concurrency issues when staging build

garden-service/src/plugins/kubernetes/container/build.ts, garden-service/src/util/util.ts
The truncate was previously added to improve appearance in the fancy
logger, but we no longer use the fancy logger for verbose+ log levels.
Fixes #1357
=> fix(k8s): don't truncate container build logs

garden-service/src/cli/cli.ts, garden-service/src/logger/logger.ts, garden-service/src/logger/writers/base.ts, garden-service/src/logger/writers/basic-terminal-writer.ts, garden-service/src/logger/writers/fancy-terminal-writer.ts, garden-service/src/logger/writers/file-writer.ts, garden-service/src/logger/writers/json-terminal-writer.ts
This avoids triggering the log writers if their level is lower than
the log entry. This was particularly apparent when initializing
providers because that process triggers a lot of verbose+ entries.
=> fix(cli): fix janky spinner when initializing providers

garden-service/src/config/base.ts, garden-service/src/config/module.ts, garden-service/test/data/test-project-invalid-config/missing-kind/garden.yml, garden-service/test/data/test-project-invalid-config/missing-name/garden.yml, garden-service/test/data/test-project-invalid-config/missing-type/garden.yml, garden-service/test/unit/src/config/base.ts
We previously ignored configs that did not have `kind` set, and threw
some confusing errors when e.g. `type` or `name` were missing.
Fixes #1280
=> fix(config): throw error on base module schema validation errors

garden-service/src/commands/delete.ts, garden-service/test/unit/src/commands/build.ts, garden-service/test/unit/src/commands/delete.ts, garden-service/test/unit/src/commands/deploy.ts, garden-service/test/unit/src/commands/dev.ts, garden-service/test/unit/src/commands/init.ts, garden-service/test/unit/src/commands/test.ts
Set `protected = true` on delete commands.
=> improvement: add protection to more commands

docs/guides/remote-kubernetes.md, garden-service/src/plugins/kubernetes/container/deployment.ts
This adds a `securityContext` field in the pod definition when using the `container` module and the `production` flag.
Furthermore the `pod.containers[].securityContext.allowPrivilegeEscalation` is now by default set to `false`.
none
=> feat: added securityContext for production flag

.circleci/config.yml
A previous commit had accidentally changed the job to
release-service-dist. This PR reverts that change.
=> ci: use release-service-dist-edge job on merges to master

.circleci/config.yml
Apparently, CircleCI only runs workflows on tagging if all the jobs in
that workflow have a tags filter. See here:
https://circleci.com/docs/2.0/configuration-reference/#tags
=> ci: ensure tags workflow runs when tags are pushed

dashboard/src/contexts/ui.tsx
Previously, the "Show results" button on a task/test card on the Overview page wouldn't work if the "view ingress" component was open. This was because the result pane was hidden under the ingress view. Now we always close the "view ingress" component when opening the results pane.
Fixes #915
=> fix(dashboard): hide ingress view when showing task/test results

garden-service/src/config/module.ts, garden-service/src/vcs/vcs.ts, garden-service/test/data/test-projects/fixed-version-hashes-1/garden.yml, garden-service/test/data/test-projects/fixed-version-hashes-1/module-a/garden.yml, garden-service/test/data/test-projects/fixed-version-hashes-1/module-a/hello.txt, garden-service/test/data/test-projects/fixed-version-hashes-1/module-b/garden.yml, garden-service/test/data/test-projects/fixed-version-hashes-1/module-b/hello.txt, garden-service/test/data/test-projects/fixed-version-hashes-1/module-c/garden.yml, garden-service/test/data/test-projects/fixed-version-hashes-1/module-c/hello.txt, garden-service/test/data/test-projects/fixed-version-hashes-2/garden.yml, garden-service/test/data/test-projects/fixed-version-hashes-2/module-a/garden.yml, garden-service/test/data/test-projects/fixed-version-hashes-2/module-a/hello.txt, garden-service/test/data/test-projects/fixed-version-hashes-2/module-b/garden.yml, garden-service/test/data/test-projects/fixed-version-hashes-2/module-b/hello.txt, garden-service/test/data/test-projects/fixed-version-hashes-2/module-c/garden.yml, garden-service/test/data/test-projects/fixed-version-hashes-2/module-c/hello.txt, garden-service/test/unit/src/garden.ts, garden-service/test/unit/src/vcs/vcs.ts
Previously, module version hashes were contaminated with runtime specific content such as the module path and the `outputs` field.
This has now been fixed and tests added.
=> fix(vcs): ensure module versions are stable between runtimes

garden-service/src/proxy.ts
This PR uses the service's port when forwarding to localhost, if it's available, otherwise it uses a random available port. We need it because it's helpful for services to be on the expected localhost ports e.g. 3000 for Create React App, 27017 for MongoDB, 6379 for Redis.
Fixes #1428
=> feat(core): use service's port when forwarding to localhost if available

dashboard/src/service-worker.ts, garden-service/src/plugins/kubernetes/container/deployment.ts, garden-service/src/plugins/kubernetes/status/status.ts, package.json, tslint.base.json
Enforce [triple equals](https://palantir.github.io/tslint/rules/triple-equals/) in linter because using `==` can cause subtle bugs. For example:
```javascript
false == 0 // true
```
which we generally don't want.
**Notes for reviewer**
Also added `--no-bail` to `lint`, `test`, and `fix-format` commands so that `lerna` doesn't exit on when the first package errors.
=> chore(lint): enforce triple-equals

garden-service/src/plugins/kubernetes/commands/cleanup-cluster-registry.ts, garden-service/src/plugins/openfaas/openfaas.ts, garden-service/src/util/util.ts, garden-service/static/kubernetes/system/docker-registry/garden.yml
We need to terminate the registry pods instead of attempting to launch
another instance before terminating the other.
=> fix(k8s): in-cluster registry updates would hang with RWO volumes

garden-service/src/actions.ts
Before this fix, calls to service action handlers for services with runtime dependencies in template variables would fail if an empty `runtimeContext` was passed to the handler, even if the service handler in question doesn't need environment variables (e.g. `getServiceStatus` and `getServiceLogs`).
Fixes #1408.
=> fix(core): fix empty runtimeContext check

garden-service/src/plugins/kubernetes/helm/config.ts, garden-service/test/integ/src/plugins/kubernetes/helm/config.ts
From commit message:
The `include` field on Helm modules now defaults to:
```javascript
["*", "charts/**/*", "templates/**/*"]
```
if not set manually.
Previously, Helm modules would simply include all content under the
module path. If your Helm modules doesn't have `include` set and depends
on content that's not captured with the default include, you will need
to update the relevant `garden.yml` file and set the includes manually.
=> improvement: set default include on Helm modules

dashboard/README.md, garden-service/src/actions.ts
Before this fix, the `get status` command was using `force: false` for its `GetServiceStatus` tasks, which resulted in the overview tab of the dashboard displaying stale service statuses.
After this fix, refreshing the dashboard once all services are deployed will show their statuses as `"ready"`, which is the expected/correct behavior.
Fixes #1265
=> fix(core): use fresh statuses in get status cmd

examples/demo-project/garden.yml, examples/remote-k8s/garden.yml, examples/vote/garden.yml
...basically a copy/paste error from when we moved the example configs
to the top-level-provider style.
=> chore(examples): remove extra provider key

docs/reference/commands.md, garden-service/src/commands/commands.ts, garden-service/src/commands/migrate.ts, garden-service/test/data/test-projects/v10-configs-errors/garden.yml, garden-service/test/data/test-projects/v10-configs-errors/project-varfile/garden.yml, garden-service/test/data/test-projects/v10-configs/garden.yml, garden-service/test/data/test-projects/v10-configs/module-a/garden.yml, garden-service/test/data/test-projects/v10-configs/module-b/garden.yml, garden-service/test/data/test-projects/v10-configs/module-noop/garden.yml, garden-service/test/data/test-projects/v10-configs/nested/module-c/garden.yml, garden-service/test/unit/src/commands/migrate.ts
Adds a command that helps users migrate from `v0.10.x` to `v.11.y`. The command scans the project for outdated configs and attempts to update them.
- Name is still TBD, any suggestions welcome!
- Not all test cases are covered (yet).
- Dumping all the config to the screen when the command is run by default is questionable. Suggestions for UX improvements most welcome.
=> feat: add a migration command for migrating from v0.10 to v0.11

garden-service/src/plugins/kubernetes/init.ts
The Helm 3 migration wasn't being triggered for project namespaces.
=> fix(k8s): make sure Helm 3 migration is run for project namespaces

.circleci/config.yml
Since we use VM-less minikube, the layer caching should actually be helpful in terms of performance.
=> chore(ci): enable docker layer caching for minikube tests

docs/reference/module-types/container.md, docs/reference/module-types/helm.md, docs/reference/module-types/kubernetes.md, garden-service/src/config/common.ts, garden-service/src/config/module.ts, garden-service/src/plugins/container/config.ts, garden-service/src/plugins/container/container.ts, garden-service/src/plugins/kubernetes/helm/config.ts, garden-service/src/plugins/kubernetes/kubernetes-module/config.ts, garden-service/src/plugins/maven-container/maven-container.ts, garden-service/test/data/test-projects/kubernetes-module/garden.yml, garden-service/test/data/test-projects/kubernetes-module/module-simple/garden.yml, garden-service/test/integ/src/plugins/kubernetes/helm/config.ts, garden-service/test/integ/src/plugins/kubernetes/kubernetes-module/config.ts
Previously we would set a default `include` on some module configs if no `include` was specified. Updated to only set a default `include` if neither `include` nor `exclude` is specifically set.
Also updated the description test for the `include` directive and added more tests.
=> fix(config): do not set default include if exclude is set + add tests

garden-service/src/plugins/kubernetes/helm/helm-cli.ts, garden-service/src/plugins/kubernetes/helm/tiller.ts, garden-service/src/util/util.ts
The 2to3 plugin doesn't support multiple files in KUBECONFIG, and does
not support/respect the --kube-context parameter at all.
=> fix(k8s): fix issues with helm 2to3 migration

garden-service/src/analytics/analytics.ts, garden-service/src/vcs/git.ts
The `AnalyticsHandler` was wrongly expecting the project to have a `remote.url` set and it was failing when running garden on a local repo. Fixed that.
Fixes #
cc @thsig
=> fix: failing init if remote is not set

garden-service/src/plugins/kubernetes/helm/tiller.ts, garden-service/src/plugins/kubernetes/init.ts
Without it, `garden deploy` fails with the following error after migrating to Helm 3:
```
✖ ingress-controller        → Deploying version v-deb87c8a3a...
Failed resolving provider local-kubernetes. Here is the output:
local-kubernetes — an error occurred when configuring environment:
Error: Command "/Users/eysi/.garden/tools/helm3/dd4668d875bedaf5/darwin-amd64/helm --kube-context docker-for-desktop --namespace garden
-system upgrade garden-nginx /Users/eysi/code/garden-io/garden/examples/demo-project/.garden/kubernetes.garden/build/ingress-controller
/nginx-ingress --install --atomic --namespace garden-system --timeout 300s --values …
```
=> fix(k8s): ensure Garden can upgrade garden-nginx release

garden-service/src/config/common.ts, garden-service/src/plugins/kubernetes/api.ts, garden-service/src/plugins/kubernetes/commands/remove-tiller.ts, garden-service/src/plugins/kubernetes/helm/tiller.ts, garden-service/src/plugins/kubernetes/init.ts, garden-service/src/plugins/kubernetes/kubernetes.ts, garden-service/src/plugins/kubernetes/local/kind.ts, garden-service/src/plugins/kubernetes/secrets.ts, garden-service/src/plugins/kubernetes/status/status.ts, garden-service/src/types/plugin/provider/getEnvironmentStatus.ts, garden-service/src/types/plugin/provider/prepareEnvironment.ts, garden-service/src/util/string.ts, garden-service/test/integ/src/plugins/kubernetes/api.ts, garden-service/test/integ/src/plugins/kubernetes/container/build.ts, garden-service/test/unit/src/plugins/kubernetes/container/ingress.ts
Users may need Tiller for non-Garden related reasons. We now no longer
automatically remove Tiller from project namespaces (but we do for
garden-system), and instead provide a command to do the cleanup and a
prompt for the user to run it.
NOTE: We need to update the 0.11 release notes to reflect this!
=> fix(k8s): play nice with Helm 2 (Tiller) when users still need it

garden-service/src/plugins/kubernetes/init.ts, garden-service/static/kubernetes/system/ingress-controller/garden.yml
This was a simple omission. We should of course pass configured ports
to the nginx Helm chart when we're installing it.
=> fix(k8s): use configured ingress ports when installing nginx

garden-service/src/plugins/kubernetes/init.ts
This narrows the condition for throwing an error on init (when using
remote clusters). We now only throw an error if any of the expected
services are unhealthy, deploying or missing.
Also made the warning message a bit less intrusive, since it's to be
expected in some cases that configuration is out of sync between users,
as well as when users make modifications of their own.
=> fix(k8s): don't throw init error if garden-system services are modified

garden-service/src/analytics/analytics.ts, garden-service/src/config-store.ts
Tiny PR to address some small issues:
- Change the color of the message informing the users of the automatic opt-in
from yellow (warning) to gray (info).
- Allow unknown keys in the GlobalConfig to prevent errors in future versions
when changing the type keys.
Fixes #
=> chore(analytics): changed color to warning + retrocompatibility

garden-service/src/analytics/analytics.ts, garden-service/src/cli/cli.ts, garden-service/src/commands/migrate.ts, garden-service/src/vcs/vcs.ts, garden-service/test/unit/src/cli/cli.ts, garden-service/test/unit/src/garden.ts, garden-service/test/unit/src/vcs/vcs.ts
Adds a `DummyGarden` class to use for commands that run outside the context of a valid Garden project.
Fixes an issue where commands with `noProject=true` fail if the project contains template strings (and presumably for other reasons as well as Garden attempts to resolve providers and configs).
=> fix(cli): ensure 'noProject' commands run in invalid projects

garden-service/src/plugins/kubernetes/helm/helm-cli.ts, garden-service/src/plugins/kubernetes/helm/tiller.ts
Apparently, the Helm plugin system doesn't work on Windows (except in
bash-like shells). So instead of installing the 2to3 plugin via the Helm
CLI (as one would expect), we instead have to download it manually and
execute it directly.
=> fix(k8s): ensure helm migration works on Windows

garden-service/src/commands/config/config-analytics-enabled.ts
Enables toggling analytics opt-in/opt-out outside of the context of a working project.
Fixes #1488
=> fix(cli): enable running 'config analytics-enabled' with no project

garden-service/src/cli/cli.ts
This PR introduces a flush of the Analytics events queue before we return.
This is needed because we have been experiencing missing events an more often than not, the queue is not flushed before the end of the cli execution.
Fixes #
This way of handling this specific case will go away once we swith to stateful analytics events (sqlite + sending events batch).
=> fix: force anlytics events queue flush

docs/using-garden/README.md
Fixes a duplicate/incorrect link in one of our guides.
=> fix(docs): fix incorrect link in guide

support/install.sh
This will allow users to do things like:
```bash
curl -sL https://get.garden.io/install.sh | bash -s edge
```
or 
```bash
curl -sL https://get.garden.io/install.sh | bash -s v0.11.0-alpha.4
```
Leaving out the parameter `-s <release>` passed to `bash` will install the latest released version.
=> improvement: allow to specify release to install

garden-service/src/plugins/kubernetes/helm/common.ts, garden-service/src/plugins/kubernetes/helm/deployment.ts, garden-service/src/plugins/kubernetes/helm/hot-reload.ts, garden-service/src/plugins/kubernetes/hot-reload.ts, garden-service/test/data/test-projects/helm/api/Chart.yaml, garden-service/test/data/test-projects/helm/two-containers/.helmignore, garden-service/test/data/test-projects/helm/two-containers/Chart.yaml, garden-service/test/data/test-projects/helm/two-containers/garden.yml, garden-service/test/data/test-projects/helm/two-containers/templates/NOTES.txt, garden-service/test/data/test-projects/helm/two-containers/templates/_helpers.tpl, garden-service/test/data/test-projects/helm/two-containers/templates/deployment.yaml, garden-service/test/data/test-projects/helm/two-containers/templates/ingress.yaml, garden-service/test/data/test-projects/helm/two-containers/templates/service.yaml, garden-service/test/data/test-projects/helm/two-containers/values.yaml, garden-service/test/integ/src/plugins/kubernetes/helm/hot-reload.ts
Before this fix, the sync volume would be attached to all containers in the target resource when using hot reloading with Helm modules, which is not desirable e.g. when using user-specified sidecar containers.
Now, the sync volume is only attached to the container identified by `serviceResource.containerName` or the Helm module's name.
We (I) didn't create a GitHub issue for this one, but it was raised by a user in our community Slack channel.
Note that we're now also only attaching the sync volume to the "main" container for other Kubernetes module types (e.g. `container` and `kubernetes`).
=> fix(helm): only hot reload serviceResource

examples/terraform-gke/gke.tf
The 3.0 version of the Terraform Google provider changed the usage of the region, zone and location fields, which resulted in errors when running `garden plugins kubernetes cluster-init`.
=> chore(examples): update terraform example

garden-service/src/types/plugin/base.ts, garden-service/src/types/plugin/task/getTaskResult.ts
This adds a bit of future-proofing for schema changes to test and task results.
If unknown fields are not allowed in task and test results, new fields stored on results generated by newer versions of the framework may cause errors when read by older versions which do not recognize the new fields.
=> fix(core): allow unknown in task & test results

garden-service/src/commands/run/task.ts, garden-service/src/plugins/container/build.ts, garden-service/src/plugins/kubernetes/container/run.ts, garden-service/src/plugins/kubernetes/helm/handlers.ts, garden-service/src/plugins/kubernetes/run.ts, garden-service/src/plugins/kubernetes/task-results.ts, garden-service/src/tasks/task.ts, garden-service/src/util/ext-tools.ts, garden-service/test/integ/src/plugins/kubernetes/container/container.ts, garden-service/test/integ/src/plugins/kubernetes/helm/run.ts, garden-service/test/integ/src/plugins/kubernetes/helm/test.ts
Before this fix, failing tasks (e.g. with an invalid command or args configured) would succeed.
Also added integration tests for the failing case for tests and tasks for our k8s plugins, and fixed/improved logging of test/task logs and errors.
=> fix(k8s): fix failing tasks not throwing errors

garden-service/src/plugins/container/build.ts
Turns out logging build logs (introduced in #1143) can get really noisy if we don't
truncate the output somehow. I tried truncating it with the `cliTruncate`
function but it messed up the terminal cursor position and by extension
the entire log output. Putting this on ice for now.
=> refactor(container): revert build logs log level to debug

garden-service/src/util/fs.ts, garden-service/test/data/test-projects/build-dir/hidden-files/garden.yml, garden-service/test/unit/src/build-dir.ts, garden-service/test/unit/src/vcs/git.ts
Previously, hidden files would not be matched, unless glob patterns
were explicitly prefixed with a period. That was unexpected behavior in
various cases, so I'd qualify that as a bug.
=> fix(core): include hidden files when using include filters

garden-service/src/commands/dev.ts, garden-service/src/tasks/test.ts, garden-service/test/unit/src/tasks/test.ts
Before this fix, the `getDependencies` method of `TestTask` returned deploy tasks without the hot reload flag set appropriately.
This meant that repeated hot reloads of services with test dependants would fail (because the test dependant would redeploy the service without hot reloading enabled) when using the dev command.
Fixes #1552.
Do we think this needs additional test cases? Or is this fine as is?
=> fix(core): make test task deps hot-reload aware

garden-service/src/plugins/kubernetes/commands/cleanup-cluster-registry.ts, garden-service/src/plugins/kubernetes/commands/cluster-init.ts, garden-service/src/plugins/kubernetes/container/build.ts, garden-service/src/plugins/kubernetes/container/util.ts, garden-service/src/plugins/kubernetes/init.ts, garden-service/src/plugins/kubernetes/kubernetes.ts, garden-service/src/plugins/kubernetes/namespace.ts, garden-service/src/plugins/kubernetes/system.ts, garden-service/src/plugins/kubernetes/test-results.ts, garden-service/src/plugins/kubernetes/util.ts
Previously, we would just read the system namespace from the provider config and then execute commands in it without ensuring that it exists. Usually the system namespace gets created during the prepare/init environment flow but not if the project doesn't have any system services.
Now we instead ensure that the namespace exists before passing it off to commands that use it. 
Fixes #1464
=> fix(k8s): ensure system namespace exists before using it

garden-service/src/plugins/kubernetes/kubectl.ts, garden-service/src/plugins/kubernetes/status/status.ts, garden-service/src/plugins/kubernetes/util.ts, garden-service/src/util/string.ts
Previously we stored the raw manifest under the
garden.io/last-applied-configuration. We now hash it and store it under
garden.io/manifest-hash. This prevents errors when then annotation
string gets too long.
Fixes #1496
=> fix(k8s): hash configuration annotation

.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
Remove task list from PR template because GitHub renders it like this:
...which is confusing.
=> chore(pr-template): remove task list

garden-service/src/plugins/kubernetes/container/build.ts, garden-service/src/plugins/kubernetes/helm/run.ts, garden-service/src/plugins/kubernetes/run.ts, garden-service/src/plugins/kubernetes/util.ts, garden-service/test/unit/src/plugins/kubernetes/util.ts
Apologies, this was miscalculated when the fix was introduced.
If Pod names are deterministic we can run into conflicts when running
tasks and tests.
=> fix(k8s): ensure generated pod names are always unique

garden-service/src/plugins/kubernetes/system.ts
Just noticed this while looking into something else. Turns out the `values` lodash function isn't type-safe, so we missed a change during refactoring, and we shouldn't be using that anyway.
=> fix(k8s): provider init errors weren't handled properly

dashboard/src/api/api.ts, dashboard/src/containers/overview.tsx, docs/reference/commands.md, garden-service/src/commands/get/get-config.ts, garden-service/test/unit/src/commands/get/get-config.ts
Add `exclude-disabled` option to the `garden get config` command and use it in the dashboard when loading the config. Otherwise, the dashboard fails to render if there are disabled services in the config.
We might want to re-think how we display disabled entities in the dashboard in general but at least this fixes the rendering error. 
We also need to do the same for the `get graph` command although that's more complex since disabled modules may be built if they other modules depend on them.
=> fix(cli): add exclude-disabled option to get config command

garden-service/src/plugins/kubernetes/api.ts, garden-service/src/plugins/kubernetes/run.ts, garden-service/src/plugins/kubernetes/status/pod.ts, garden-service/src/plugins/kubernetes/status/workload.ts, garden-service/test/data/test-projects/container/missing-sh/garden.yml, garden-service/test/data/test-projects/container/missing-tar/garden.yml, garden-service/test/data/test-projects/container/simple/garden.yml, garden-service/test/data/test-projects/helm/artifacts/garden.yml, garden-service/test/data/test-projects/kubernetes-module/artifacts/garden.yml, garden-service/test/integ/src/plugins/kubernetes/container/container.ts
This was due to kubectl sometimes failing to attach to Pods. We now
explicitly fetch the logs, with a bit of trickery to be able to do so
when copying artifacts out of the container after running the test/task
command.
This should also address the flaky integ tests we've been seeing in
minikube.
=> fix(k8s): tasks and tests would sometimes return empty logs

garden-service/src/plugins/kubernetes/run.ts, garden-service/test/integ/src/plugins/kubernetes/container/container.ts
We were previously throwing a somewhat ugly error when files were missing, and in many cases you'd expect files to be missing after a run, e.g. after a failed run.
=> fix(k8s): don't throw error when test/task artifact is missing after run

garden-service/src/events.ts, garden-service/src/garden.ts, garden-service/src/task-graph.ts, garden-service/src/util/util.ts, garden-service/test/helpers.ts, garden-service/test/unit/src/task-graph.ts, garden-service/test/unit/src/util/util.ts, package.json
This commit adds batch-based concurrency to the task graph.
When `TaskGraph`'s process method is called, the requested tasks are grouped into batches that share one or more keys (including dependencies). These batches are then queued.
In each iteration of the task graph's main loop, any pending batches that share no keys with currently in-progress batches are added to the graph.
This enables e.g. hot reload tasks to be run concurrently with build and test tasks for their underlying modules, which was one of the primary motivators behind this change.
Also replaced the `concurrencyLimit` option for `TaskGraph`'s `processTasks` method with an `unlimitedConcurrency` option. This is useful e.g. when resolving providers.
Task nodes from batches with …
=> feat(core): improved task graph concurrency

.circleci/config.yml, garden-service/Dockerfile, garden-service/aws.Dockerfile, garden-service/bin/build-containers.sh, garden-service/bin/push-containers.sh
Adds a `gardendev/garden-aws` image to Docker Hub, that bundles the AWS CLI for convenience and use in CI.
=> feat(distribution): add container image baked with AWS CLI

support/install.ps1
Prevents Windows installer from installing `docker-for-windows` without first asking the user. (As implemented in #885)
=> fix(Windows): don't always install docker-for-windows

garden-service/src/plugins/kubernetes/container/run.ts, garden-service/src/plugins/kubernetes/container/test.ts, garden-service/src/plugins/kubernetes/helm/run.ts, garden-service/src/plugins/kubernetes/helm/test.ts, garden-service/src/plugins/kubernetes/kubernetes-module/run.ts, garden-service/src/plugins/kubernetes/kubernetes-module/test.ts, garden-service/src/plugins/kubernetes/run.ts, garden-service/src/types/plugin/module/runModule.ts, garden-service/test/helpers.ts, garden-service/test/integ/src/plugins/kubernetes/container/container.ts
See the added tests. We weren't handling timeouts correctly or consistently depending on whether artifacts were being copied or not.
=> fix(k8s): fixed handling of timeouts when artifacts are being copied

garden-service/src/plugins/kubernetes/kubernetes-module/common.ts, garden-service/src/plugins/kubernetes/kubernetes-module/handlers.ts, garden-service/src/plugins/kubernetes/kubernetes-module/run.ts, garden-service/src/plugins/kubernetes/kubernetes-module/test.ts, garden-service/src/tasks/get-service-status.ts, garden-service/src/types/plugin/service/getServiceStatus.ts
We shouldn't be staging the build when getting the service status as it
can remove build artifacts like those generated by the `helm` module. Had
to make adjustments to the `kubernetes` module `getServiceStatus` handler to
account for this change.
Fixes #1583
=> fix(core): remove StageBuildTask from GetServiceStatusTask dependencies

garden-service/src/plugins/terraform/common.ts
Increase the exec timeout when calling terraform init
Fixes #
=> fix(terraform): increase init timeout

garden-service/src/config/provider.ts, garden-service/src/tasks/resolve-provider.ts, garden-service/test/unit/src/garden.ts
Previously, referencing a disabled provider (i.e. one that is not
enabled for the current environment) in a template string in a provider
config would always throw an error.  Now the template reference 
returns undefined instead, so you can use those in conditionals.
Example:
```yaml
kind: Project
environments:
- name: dev
- name: prod
providers:
- name: terraform
environments: [prod]
- name: kubernetes:
context: ${providers.terraform.outputs.kubecontext || 'default'}
```
=> fix(core): allow referencing disabled providers in template strings

docs/guides/variables-and-templating.md, docs/reference/template-strings.md, garden-service/src/docs/templates/template-strings.hbs, garden-service/src/template-string-parser.pegjs, garden-service/src/template-string.ts, garden-service/test/unit/src/actions.ts, garden-service/test/unit/src/garden.ts, garden-service/test/unit/src/template-string.ts
In some cases, you may want to provide configuration values only for
certain cases, e.g. only for specific environments. By default, an
error is thrown when a template string resolves to an undefined value,
but you can explicitly allow that by adding a `?` after the template.
Example:
```yaml
kind: Project
...
providers:
- name: kubernetes
kubeconfig: ${var.kubeconfig}?
...
```
This is useful when you don't want to provide _any_ value unless one is
explicitly set, effectively falling back to whichever the default is
for the field in question.
=> feat(template): add optional suffix, to allow undefined values

.circleci/config.yml, docs/guides/in-cluster-building.md, docs/providers/kubernetes.md, garden-service/src/plugins/container/config.ts, garden-service/src/plugins/kubernetes/constants.ts, garden-service/src/plugins/kubernetes/container/build.ts, garden-service/src/plugins/kubernetes/kubernetes.ts, garden-service/src/plugins/kubernetes/local/config.ts, garden-service/src/plugins/kubernetes/util.ts, garden-service/test/data/test-projects/container/garden.yml, garden-service/test/data/test-projects/container/remote-registry-test/Dockerfile, garden-service/test/data/test-projects/container/remote-registry-test/garden.yml, garden-service/test/integ/src/plugins/kubernetes/container/build.ts, garden-service/test/integ/src/plugins/kubernetes/container/container.ts, garden-service/test/integ/src/plugins/kubernetes/container/deployment.ts, garden-service/test/integ/src/plugins/kubernetes/container/logs.ts, garden-service/test/integ/src/plugins/kubernetes/util.ts
Previously we would always deploy and use the in-cluster registry
when building in-cluster. Now we allow using the configured
`deploymentRegistry`, which is often preferable (and more scalable)
than using the simpler in-cluster registry.
Closes #1034
=> improvement(k8s): use deploymentRegistry with in-cluster building

garden-service/src/plugins/terraform/common.ts, garden-service/src/plugins/terraform/module.ts
Terraform would error if you had a `terraform` module that was not in the project root and that had the `init` field set.
Also added some logs to the `getStackStatus` function.
=> fix(terraform): ensure correct init root is validate + add logs

garden-service/src/commands/dev.ts, garden-service/src/task-graph.ts, garden-service/src/tasks/deploy.ts, garden-service/test/unit/src/commands/dev.ts, garden-service/test/unit/src/task-graph.ts, garden-service/test/unit/src/tasks/deploy.ts
This PR introduces two changes:
1. After this change, a task will not be re-run if it has force = false and another task with the same key and version has already thrown an error while running (and thus had its result cached in the graph's `ResultCache`).
This means that we treat task results as cached regardless of whether the task succeeded or not: The semantic is that a task with `force = false` should always succeed with the same result (or fail) for a given key + version.
When this is not the case, `force = true` should be used.
This prevents e.g. time-consuming tasks from repeatedly running and failing in the same fashion when repeatedly added to the task graph following watch changes.
2. `DeployTask`'s `getDependencies` method now always …
=> Task graph cache fixes and changes to DeployTask dependency logic tor task dependencies

.circleci/config.yml
Small omission that came up while debugging with @khaled :)
=> chore(ci): push buster image to registry after building

docs/quick-start.md
It is confusing explaining that the `--env=remote` is only needed when using a remote OR edit the garden.yaml. THEN the first command has the `env` flag stated but none of the following commands do. This confused me for hours. Removing the flag and going start-to-finish now makes a bit more sense.
**What this PR does / why we need it**: Docs update for clearity.
**Which issue(s) this PR fixes**: n/a
@edvald, @thsig, @eysi09, @10ko and @solomonope
=> docs: UPDATED quick-start.md

garden-service/src/commands/dev.ts, garden-service/test/data/test-project-a/module-a/garden.yml, garden-service/test/unit/src/commands/dev.ts, garden-service/test/unit/src/commands/test.ts, garden-service/test/unit/src/config/base.ts
Before this fix, if a service was deployed with hot reloading via the dev command, and a test spec had a runtime dependency on that service, the service would initially be deployed without hot reloading enabled.
This would result in subsequent hot reloads for that service failing.
Also added a test case checking for this behavior.
=> fix(core): fix to dependency logic in dev command

docs/reference/commands.md, garden-service/src/commands/get/get-linked-repos.ts, garden-service/src/commands/get/get.ts, garden-service/test/unit/src/commands/get/get-linked-repos.ts
This command renders a list of all linked remote project sources and modules.
This feature was recently requested by a user on our community Slack.
=> feat(core): add get remote-repos command

garden-service/src/template-string-parser.pegjs, garden-service/src/template-string.ts, garden-service/src/util/string.ts, garden-service/test/unit/src/config/config-context.ts, garden-service/test/unit/src/template-string.ts, garden-service/test/unit/src/util/string.ts
Previously it was not possible to include template strings in literals
within template strings, e.g. nested in a conditional. This could
cause problems if you need to template values differently based on
context (e.g. differently by environments).
You can now make expressions like
`${environment.name == "local" ? "something-${var.local-var}" : "other-${remote-var}"}`
Maybe try and break this somehow, see if you can think of any potential funky edge cases.
=> improvement(template): allow template expression in nested strings

garden-service/src/commands/serve.ts
Before this commit, the `garden serve` command would use `DEFAULT_PORT` as the default value for its `port` option.
If another command was already running and serving on `DEFAULT_PORT` when `garden serve` was called, this would result in an error.
This was fixed by deferring to the standard random port selection logic we use for other commands by skipping the default value for this command option.
Fixes #1657.
=> fix(commands): don't use default port in serve cmd

garden-service/src/plugins/kubernetes/kubernetes.ts, garden-service/test/helpers.ts, garden-service/test/integ/src/plugins/kubernetes/container/container.ts, garden-service/test/unit/src/plugins/kubernetes/kubernetes.ts
This means that by default builds are shared between users when sharing
a cluster. Image _layers_ were anyway shared, but this change will
accelerate builds and tests through reducing the number of steps
involved when all layers already exist.
Co-authored-by: swist <me@swistofon.pl>
Closes #1649 
cc @swist
=> improvement(k8s): default in-cluster registry namespace to project name

garden-service/src/plugins/kubernetes/container/build.ts, garden-service/src/plugins/kubernetes/util.ts
We were running a very old Kaniko version, due to some headaches with the upgrade. 
This involved some fresh hackery, see the code comments for details.
From this point, updating Kaniko should be much much easier.
Closes #1031 (still don't allow configuring the version, but we'll keep it more up-to-date now so I think it's safe to close)
=> improvement(k8s): update kaniko to v0.17.1

garden-service/src/plugins/kubernetes/constants.ts, garden-service/src/plugins/kubernetes/helm/common.ts, garden-service/src/plugins/kubernetes/task-results.ts, garden-service/src/plugins/kubernetes/test-results.ts, garden-service/test/integ/src/plugins/kubernetes/task-results.ts
This fix is a hacky temporary fix, just to get rid of the error case.
A better solution would be to store logs as files somehow, e.g. in a
persistent volume.
=> fix(k8s): error when task logs were longer than 500kB

garden-service/src/plugins/kubernetes/container/build.ts, garden-service/test/integ/src/plugins/kubernetes/container/build.ts, images/skopeo/Dockerfile, images/skopeo/garden.yml
We now use skopeo (https://github.com/containers/skopeo) to get build
status when using Kaniko. Previously the build status was reported as not
ready without an error, even when auth was missing or failed.
Fixes #1672 
cc @mitchfriedman @swist
=> fix(k8s): issues with private registry auth and kaniko build status

.circleci/config.yml
The larger container size doesn't appear to give us much in the way of performance, so this'll save a bit of money.
=> chore(ci): reduce container size

garden-service/src/config-graph.ts, garden-service/src/garden.ts, garden-service/src/plugins.ts, garden-service/src/task-graph.ts, garden-service/src/util/validate-dependencies.ts, garden-service/test/unit/src/garden.ts, garden-service/test/unit/src/task-graph.ts, garden-service/test/unit/src/util/validate-dependencies.ts
We now detect circular dependencies in `ConfigGraph` after the graph has been augmented, possibly catching more circular dependencies.
Also added circular task dependency detection to `TaskGraph`.
We also use the new `DependencyValidationGraph` class everywhere we need to detect circular dependencies, e.g. when detecting circular plugin/plugin module dependencies.
Some users have run into difficult-to-debug errors that seem to stem from circular config/task dependencies. Hopefully these changes will help quickly diagnose such errors.
=> fix(core): improved circular dependency detection

.circleci/config.yml
It's handy to be able to get dist builds after any CI build. Now we can fetch them from CircleCI.
=> chore(ci): store dist artifacts after CI runs

garden-service/src/plugins/kubernetes/container/build.ts
This fixes a few hairy things around dockerfiles not
being handled isomorphically to docker daemon.
We have had a few issues since 0.17 release and 
had figured out a few workarounds, but this claims
to fix those issues proper. Means our future modules
will require less oversight
=> chore: Bump kaniko version to 0.19.0

garden-service/src/plugins/kubernetes/status/pod.ts
I spotted this issue with a task that ran the AWS CLI to create DynamoDB tables. The output of the command is in JSON. When the output is JSON it comes into garden as an object, which doesn't have a trim method. You can see this in [run.ts](https://github.com/garden-io/garden/blob/master/garden-service/src/plugins/kubernetes/run.ts#L341).
You can recreate this issue by having a task output JSON, ala.
``` bash
#!/usr/bin/env bash
echo '{"hello": "world"}'
exit 0
```
_setup.sh_
``` yaml
kind: Module
name: database-tables
description: Create database tables
tasks:
- name: db-migrate-default
command: ["bash", "/project/setup.sh"]
dependencies:
- database-default
```
_garden.yml_
and then a docker file that just copies over the setup.sh …
=> fix(k8s): if the output is json, stringify it

garden-service/aws.Dockerfile
When running the Garden CLI on some clusters on AWS, the `aws-iam-authenticator` executable is required to look up credentials for ECR
When deploying to an EKS cluster on AWS using the `ecr-login` method of authentication (`{ "credHelpers": { "<aws_account_id>.dkr.ecr.<region>.amazonaws.com": "ecr-login" } }` and `https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/#registry-secret-existing-credentials`), Garden will call out to `aws-iam-authenticator` executable. This executable it not on the current container, and this PR installs it.
Fixes #
=> fix: include aws-iam-authenticator in AWS specific container

garden-service/src/plugins/kubernetes/container/build.ts, garden-service/static/kubernetes/system/docker-daemon/templates/deployment.yaml, garden-service/static/kubernetes/system/registry-proxy/values.yaml, images/socat/Dockerfile, images/socat/garden.yml
We've gotten reports of the socat proxy segfaulting on EKS 1.15. This is an experiment to see if this fixes that issue.
=> improvement(k8s): update socat image used for registry proxies

docs/reference/commands.md, garden-service/package-lock.json, garden-service/package.json, garden-service/src/cli/cli.ts, garden-service/src/commands/commands.ts, garden-service/src/commands/login.ts, garden-service/src/commands/logout.ts, garden-service/src/db/base-entity.ts, garden-service/src/db/connection.ts, garden-service/src/db/entities/client-auth-token.ts, garden-service/src/docs/commands.ts, garden-service/src/garden.ts, garden-service/src/platform/auth.ts, garden-service/test/unit/src/platform/auth.ts, garden-service/test/unit/src/util/artifacts.ts
* Added `login` and `logout` commands (not included in the docs for now).
* Auth logic for reading and storing client auth tokens (we use the local SQLite DB for this).
* Auth logic for visiting the platform's login page, and for receiving redirects from that page containing a valid client token.
A couple of open questions:
1. Should we use the presence of a `sessionId` in the options passed to `Garden.factory` as the indicator of whether the login flow should be engaged (this is the current approach)? Or should login be an "outside" operation, performed in the CLI and the login command?
2. Should we hardcode a default value for the platform URL, or keep using the `GARDEN_CLOUD` env var for now? The current setup may be fine for the time being, just wanted to flag this.
=> feat(platform): add client login to CLI

docs/reference/providers/kubernetes.md, docs/reference/providers/local-kubernetes.md, garden-service/package-lock.json, garden-service/package.json, garden-service/src/plugins/conftest/conftest-kubernetes.ts, garden-service/src/plugins/conftest/conftest.ts, garden-service/src/plugins/kubernetes/config.ts, garden-service/src/plugins/kubernetes/init.ts, garden-service/src/plugins/kubernetes/system.ts, garden-service/src/runtime-context.ts, garden-service/static/kubernetes/system/build-sync/garden.yml, garden-service/static/kubernetes/system/docker-daemon/garden.yml, garden-service/static/kubernetes/system/docker-registry/garden.yml, garden-service/static/kubernetes/system/ingress-controller/garden.yml, garden-service/static/kubernetes/system/nfs-provisioner/garden.yml, garden-service/static/kubernetes/system/policy/base_test.rego, garden-service/static/kubernetes/system/policy/deny.rego, garden-service/static/kubernetes/system/policy/kubernetes.rego, garden-service/static/kubernetes/system/policy/labels.rego, garden-service/static/kubernetes/system/policy/warn.rego, garden-service/static/kubernetes/system/registry-proxy/templates/daemonset.yaml, garden-service/test/integ/src/plugins/kubernetes/system.ts, garden-service/test/unit/src/plugins/kubernetes/container/ingress.ts, garden-service/test/unit/src/plugins/kubernetes/init.ts, garden-service/test/unit/src/plugins/kubernetes/kubernetes.ts
Adds default tolerations and expose the `nodeSelector` field on some Garden system services, namely:
* `build-sync`
* `docker-daemon`
* `docker-registry`
* `ingress-controller`
* `nfs-provisioner`
The tolerations have the following spec:
```yaml
tolerations:
- key: "garden-system"
operator: "Equal"
value: "true"
effect: "NoSchedule"
```
Fixes #1600 
We use the `conftest` plugin to test whether system services have the right policies. Dog fooding ftw. 
**Note that this does not apply to `cert-manager` and `default-backend`. **
=> improvement(k8s): add default tolerations to system services

.circleci/config.yml, garden-service/bin/build-pkg.sh
We stopped releasing an Alpine bin because of issues with building it locally, instead we built it in a container and released the image. However, we never removed it from the install script, an issue that a user recently bumped into (#1730).
This PR re-enables it by building the container image and copying the Alpine bin and deps from out of the container. 
Fixes #1730
N/A
=> chore: add alpine back to release bins

garden-service/src/actions.ts, garden-service/src/commands/get/get-status.ts, garden-service/src/commands/get/get-task-result.ts, garden-service/src/tasks/get-task-result.ts, garden-service/src/types/plugin/plugin.ts
When the `get task-result` command is run for a task whose module type doesn't implement the getTaskResult handler, we now display a more helpful error message.
Some users have been confused by the error messages displayed when running `garden get task-result` in `exec` modules, which don't currently support storing/reading task results.
Is this approach of using `undefined` as a return value for the default handler (to discriminate between "real" `null` values returned by plugin handlers that actually implement this behavior) a good way to go? Seemed simple and intuitive to me, at any rate.
=> fix(cmd): better error messages in get task-result

garden-service/src/tasks/helpers.ts, garden-service/test/unit/src/tasks/helpers.ts
Before this fix, if a service with a `sourceModule` was deployed with hot reloading enabled, a build task for its source module would be added when its sources change (in addition to the hot reload task).
This was not the desired behavior, and would (e.g. for `helm` modules using a `container` module as a `sourceModule`) result in unnecessary rebuilds of the source module.
This issue was reported by a user on our community Slack.
=> fix(core): fix watch task logic for sourceModules

garden-service/static/kubernetes/system/build-sync/templates/deployment.yaml
When using in-cluster building with the default NFS provisioner, users would very occasionally start getting errors like
```
Failed building backend. Here is the output:
Command "rsync --recursive --relative --links --perms --times --compress --delete --temp-dir /tmp /root/project/.garden/build/./backend/ rsync://*********:45957/volume/86b9b3e6-91da-4ffe-b43b-e7babfda628e/" failed with code 5:
@ERROR: chdir failed
rsync error: error starting client-server protocol (code 5) at main.c(1675) [sender=3.1.3]
```
This indicates a failure in the volume mount in the Pod. The liveness probe now …
=> fix(k8s): intermittent errors with volume mounts in build-sync pods

dashboard/package-lock.json, dashboard/package.json, garden-service/package-lock.json
The latest version of a 3rd party dependency, `normalize-url`, doesn't work on Firefox and Safari. See this issue for details: https://github.com/sindresorhus/normalize-url/issues/105
This PR fixes the version at 4.
Fixes #1738 
We need to start testing the dashboard in CI. See #1768
=> fix(dashboard): fix normalize-url to version 4

.github/stale.yml
Update stale bot message to reflect that only maintainers can remove labels.
=> chore: update stale bot msg

.circleci/config.yml
The iptables command that I copied from a microk8s example was sometimes causing problems due to some locking issue.
=> chore(ci): fix flaky microk8s test

docs/guides/in-cluster-building.md
BuildKit currently isn't documented in our in-cluster building guide.
The Kubernetes provider documentation has `local-docker` set as the build-mode. Assuming most users are using this provider for remote clusters, it makes more sense to change this to `cluster-docker`.
=> Add buildkit documentation / update kubernetes provider documentation

garden-service/src/plugins/kubernetes/helm/config.ts, garden-service/test/integ/src/plugins/kubernetes/helm/config.ts
Automatic includes weren't factoring in the configured `chartPath` (if any), which could cause errors when using that field.
I just noticed this, rather incidentally.
=> fix(k8s): automatic include for helm modules should include chartPath

garden-service/src/plugins/terraform/commands.ts, garden-service/src/util/ext-tools.ts, garden-service/src/util/util.ts
Before this fix, `stdin` was not being handled correctly for the terraform plugin's commands. They were unresponsive to input (including `CTRL-C`), which prevented the commands from being run to completion in some cases.
This was fixed by not setting `setRawMode` to `true` on the child process' `stdin`.
We added the `rawMode` option to `SpawnParams` to facilitate other use cases that need interactive input, but where `rawMode` doesn't play nicely with `stdin` for the underlying child process.
Fixes #1709.
Is there a decent way to test this for future regressions?
I thought about using the input stream's `write` method (see …
=> fix(terraform): fix stdin handling in commands

garden-service/src/task-graph.ts
It was quite spammy and unnecessary.
=> chore: reduce debug log noise from TaskGraph

garden-service/src/config-graph.ts, garden-service/src/util/validate-dependencies.ts, garden-service/test/helpers.ts, garden-service/test/unit/src/config-graph.ts, garden-service/test/unit/src/util/validate-dependencies.ts
Before this fix, we were throwing missing dependency errors in `ConfigGraph`'s constructor after relations were added, which could result in null errors in the case of missing runtime dependencies.
This was fixed by throwing missing dependency errors before adding relations in the constructor.
Fixes an issue reported in our community Slack (https://kubernetes.slack.com/archives/CKM7CP8P9/p1586257958248000).
=> fix(core): missing dep detection in ConfigGraph

garden-service/src/plugins/kubernetes/container/build.ts
I am seeing a lot of loglines in our garden k8s cluster from busybox like this:
ls: /.garden/comms/done: No such file or directory
As far as I can see this is spurious and safe to be hidden away.
This fixes it by piping stderr into /dev/null as well as stdout
I haven't created an issue for it yet, but I'm happy to do so
=> fix spurious logline from busybox

garden-service/src/plugins/kubernetes/run.ts
We need to follow the /tmp/output file in order to get all the logs, otherwise we will only get the last 10 (default by tail).
https://github.com/garden-io/garden/issues
Fixes #
@edvald
=> fix: use tail -f

garden-service/src/cli/cli.ts, garden-service/src/commands/get/get-debug-info.ts, garden-service/src/commands/migrate.ts, garden-service/src/commands/run/run.ts, garden-service/src/commands/scan.ts, garden-service/src/docs/config.ts, garden-service/src/docs/joi-schema.ts, garden-service/src/docs/json-schema.ts, garden-service/src/logger/renderers.ts, garden-service/src/plugins/kubernetes/api.ts, garden-service/src/plugins/kubernetes/helm/tiller.ts, garden-service/src/task-graph.ts, garden-service/src/util/util.ts, garden-service/test/unit/src/commands/create/create-module.ts, garden-service/test/unit/src/commands/create/create-project.ts, garden-service/test/unit/src/logger/renderers.ts, garden-service/test/unit/src/util/util.ts
We'd sometimes get errors when trying to dump JSON that includes the
value `undefined` since that's not a part of the formal YAML spec. We
address this by setting `skipInvalid: true` by default when dumping
YAML. This means other invalid values such as functions will also be
excluded.
Fixes #1758 and an issue raised on the community Slack.
=> fix(core): skip invalid yaml by default

garden-service/src/analytics/analytics.ts, garden-service/src/cli/cli.ts, garden-service/src/cloud/auth.ts, garden-service/src/cloud/buffered-event-stream.ts, garden-service/src/commands/login.ts, garden-service/src/commands/logout.ts, garden-service/src/db/base-entity.ts, garden-service/src/events.ts, garden-service/src/garden.ts, garden-service/src/logger/log-entry.ts, garden-service/src/logger/logger.ts, garden-service/src/logger/writers/json-terminal-writer.ts, garden-service/src/process.ts, garden-service/test/helpers.ts, garden-service/test/unit/src/events.ts, garden-service/test/unit/src/logger/logger.ts, garden-service/test/unit/src/platform/auth.ts, garden-service/test/unit/src/platform/buffered-event-stream.ts
* Added an event bus to `Logger`, which emits events when log entries are created or updated.
* Added the `BufferedEventStream` class. This is used for batching and streaming events from the Logger and the active Garden instance to the platform when the user is logged in. Later, we can use this class for streaming to the dashboard as well.
=> feat(core): add event and log streaming

garden-service/src/plugins/kubernetes/commands/cleanup-cluster-registry.ts, garden-service/src/plugins/kubernetes/constants.ts, garden-service/src/plugins/kubernetes/container/build.ts, garden-service/src/plugins/kubernetes/kubernetes.ts, garden-service/static/kubernetes/system/util/Chart.yaml, garden-service/static/kubernetes/system/util/garden.yml, garden-service/static/kubernetes/system/util/templates/_helpers.tpl, garden-service/static/kubernetes/system/util/templates/deployment.yaml, garden-service/static/kubernetes/system/util/values.yaml, garden-service/test/integ/src/plugins/kubernetes/container/build.ts, garden-service/test/integ/src/plugins/kubernetes/system.ts
This adds a persistent skopeo daemon deployed to the cluster. This is to avoid having to spin up a new skopeo container per build status check for container. We end up seeing some failures randomly in our EKS cluster, most likely to do with failures/timeouts mounting volumes, and this will resolve that issue for us.
@edvald
No issue.
=> feat(k8s): run a persistent skopeo daemon

garden-service/src/cli/cli.ts, garden-service/src/cloud/auth.ts, garden-service/src/garden.ts
Before this fix, the logout command would require the user to be logged in, which prevented the user from logging out when they had an invalid/expired auth token persisted in their local store.
=> fix(platform): fix login/logout control flow

.circleci/config.yml, garden-service/aws.gcloud.Dockerfile, garden-service/bin/build-containers.sh, garden-service/bin/push-containers.sh
<!--  Thanks for sending a pull request!  Here are some tips for you:
This PR creates an image that include gcloud, awscli and gardencli in one image
It is meant to be used for gardencloud staging deployment
Fixes #
=> chore(docker): add image that contains gcloud and aws

garden-service/src/plugins/kubernetes/run.ts, garden-service/test/integ/src/plugins/kubernetes/container/container.ts
Use cat instead of tail -f. For some reason, cat works with multiple tests and tail -f doesn't.
To replicate:
1. Make a garden file with a single test + artifacts.
2. Make that test fail. See the correct log output of > 10 lines.
3. Add a second test (can succeed/fail, have artifacts or not, doesn't matter).
4. Run the tests again, and see the truncated log output for the original failing test.
@edvald
=> fix(k8s): artifact logs

docs/misc/telemetry.md
This came up on Slack, simple omission from our docs.
=> docs: document GARDEN_DISABLE_ANALYTICS env variable

bin/test-release.sh, examples/disabled-configs/README.md, examples/disabled-configs/backend/.dockerignore, examples/disabled-configs/backend/.gitignore, examples/disabled-configs/backend/Dockerfile, examples/disabled-configs/backend/garden.yml, examples/disabled-configs/backend/main.go, examples/disabled-configs/frontend/.dockerignore, examples/disabled-configs/frontend/Dockerfile, examples/disabled-configs/frontend/app.js, examples/disabled-configs/frontend/garden.yml, examples/disabled-configs/frontend/main.js, examples/disabled-configs/frontend/package.json, examples/disabled-configs/frontend/test/integ.js, examples/disabled-configs/garden.yml, garden-service/src/commands/get/get-config.ts, garden-service/src/garden.ts, garden-service/test/helpers.ts, garden-service/test/unit/src/commands/get/get-config.ts
Due to a regression, the `get config` command was no longer returning disabled module configs. This caused issues with the dashboard.
This PR ensures that `get config` returns disabled configs by default and adds tests.
EDIT: Also added a `disabled-configs` example project and a manual release test.  
Addresses the same problem as this PR: #1803 
=> fix(commands): ensure get config returns disabled configs (by default)

docs/misc/telemetry.md, garden-service/src/analytics/analytics-types.ts, garden-service/src/analytics/analytics.ts
The task graph emits a lot of events that are mostly noise. Instead we
want to track individual task events at the task level. Such as a build
event or a deploy event.
Fixes #
=> chore(analytics): stop collecting task graph events

garden-service/src/plugins/kubernetes/container/build.ts
Upgrade kaniko to the most recent version: https://github.com/GoogleContainerTools/kaniko/releases
@edvald
=> chore(k8s): upgrade kaniko version

garden-service/src/plugins/kubernetes/container/build.ts
There appears to have been a bug in the v0.20 kaniko release, so they released a quick update:
https://github.com/GoogleContainerTools/kaniko/releases/tag/v0.21.0
@edvald
=> chore(k8s): bump kaniko

garden-service/src/plugins/kubernetes/container/build.ts, garden-service/test/unit/src/plugins/kubernetes/container/build.ts
When using immutable tags on ECR, it gives an error that looks like the one in the test and causes the kaniko build to fail. This gracefully handles that as a success.
@edvald
=> feat(k8s): support immutable build success

.circleci/config.yml
CI builds were failing because of missing in the Ubuntu image. See also: See: https://discuss.circleci.com/t/keys-missing-in-ubuntu-images/36004
=> ci: update unbuntu image because missing keys

garden-service/src/constants.ts, garden-service/src/plugins/kubernetes/helm/run.ts, garden-service/src/plugins/kubernetes/kubernetes-module/run.ts
Before this fix, the `task.timeout` config field was not being respected for `helm` and `kubernetes` tasks.
We now correctly use the configured value, and fall back to a default, explicit constant for `timeout` when calling `runAndCopy`.
Fixes #1837.
=> fix(k8s): make helm & k8s tasks respect timeouts

garden-service/src/garden.ts, garden-service/test/data/test-project-a/garden.yml, garden-service/test/unit/src/commands/get/get-config.ts, garden-service/test/unit/src/config/base.ts
This is useful for scanning for workflows in repos with several projects.
=> feat(core): add projectId to get config cmd output

garden-service/package-lock.json, garden-service/src/analytics/analytics.ts, garden-service/src/cli/cli.ts, garden-service/src/server/server.ts, garden-service/test/helpers.ts, garden-service/test/unit/src/analytics/analytics.ts, garden-service/test/unit/src/cli/cli.ts
Previously, we would wait for the `analytics.trackCommand` and `analytics.trackApi` calls to finish. This could cause a delay after Garden is finished resolving the providers and before it executes a given command.
Now we just call the track handlers synchronously and wait for pending events when Garden exits (generally there should be no pending events because the first event is flushed immediately and subsequent events every 300 ms).
It also adds some tests for the `AnalyticsHandler` class and one for the `CLI` class to verify that events are flushed before Garden exits.
Partially addresses #1824 
- I changed the `generateProjectMetadata` function to only use raw module …
=> perf(analytics): don't wait for event tracks

garden-service/src/analytics/analytics.ts
We were printing a message explaining our telemetry collection even if it was enabled.
Reported on Slack. Thanks @noizwaves!
=> fix(cli): don't show analytics message when telemetry is disabled

docs/reference/providers/terraform.md, garden-service/src/plugins/terraform/cli.ts
We had been collecting a bunch of Terraform versions over time. Now that we fetch them automatically, they're basically clutter, so the 0.12 breaking release is a good moment to remove them.
All Terraform versions below 0.12.26 have now been removed and are no
longer supported. If you have explicitly set a Terraform version in your
`terraform` provider config, you need to update that to `"0.12.26"` or 
remove the field.
=> improvement(terraform): support v0.12.26 and remove old versions

garden-service/src/db/connection.ts
A custom path to Garden's config DB can now be set via the `GARDEN_CONFIG_DB_PATH` variable.
There are no tests for this functionality (since I couldn't think of a way to test this automatically without getting into a lot of gymnastics).
But the semantics are very simple, and any errors should be obvious to the user during usage.
=> feat(core): allow custom local db path

garden-service/src/commands/run/workflow.ts, garden-service/src/logger/renderers.ts, garden-service/src/logger/util.ts, garden-service/test/unit/src/commands/run/workflow.ts
This fixes an oversight in the initial implementation, where succeeding steps were only aborted if the step threw an exception, but not if it had an an error in its command result.
We now abort subsequent steps if a step command has errors in its result, and log the error details directly in the log (since looking into `error.log` is an undesirable extra step e.g. in a CI context).
=> fix(workflows): abort if step cmd returns errors

garden-service/src/plugins/kubernetes/container/build.ts
Kaniko added some tweaks + tracing ahead of figuring out why sometimes hashing layers takes a very long time
Fixes #
=> chore(kaniko): bump kaniko version to 0.23

garden-service/src/plugins/container/build.ts, garden-service/test/unit/src/plugins/container/container.ts
We were only applying the `extraFlags` field for local builds. This moves it into a shared function that's used for all build modes.
Reported by @elliott-davis on Slack. Thanks :)
=> fix(container): extraFlags weren't used when building in-cluster

docs/reference/config.md, garden-service/src/commands/run/workflow.ts, garden-service/src/config/common.ts, garden-service/src/config/workflow.ts, garden-service/src/docs/config.ts, garden-service/src/garden.ts, garden-service/static/docs/templates/base-config.hbs, garden-service/test/unit/src/commands/run/workflow.ts
This allows writing files from either string data, or referencing secrets when using Garden Enterprise, ahead of running workflows. 
The files are resolved and written before resolving providers, so they can reference the files. A common use case would e.g. be to write authentication files like kubeconfigs, which providers can then use.
=> feat(workflows): allow writing files ahead of workflow execution

docs/reference/config.md, garden-service/src/commands/run/workflow.ts, garden-service/src/config/workflow.ts, garden-service/src/logger/log-entry.ts, garden-service/src/util/util.ts, garden-service/test/helpers.ts, garden-service/test/unit/src/commands/run/workflow.ts
Users can now add script steps to their workflows. The usage is quite
straightforward, just use a `script` key in your step instead of a
`command`. The script is evaluated with `bash`, and should return an
exit code of 0 if successful.
I will follow up with a 2nd PR which introduces the ability to reference
command outputs in script steps.
=> feat(workflows): add support for arbitrary user scripts in workflows

garden-service/src/commands/run/workflow.ts, garden-service/src/enterprise/buffered-event-stream.ts, garden-service/src/events.ts, garden-service/src/garden.ts, garden-service/src/logger/log-entry.ts, garden-service/src/logger/log-node.ts, garden-service/src/logger/logger.ts, garden-service/test/unit/src/commands/run/workflow.ts, garden-service/test/unit/src/logger/log-entry.ts
Added `workflowStep` metadata to log entries generated by step commands and scripts.
Added step status events, which are emitted when a workflow step starts processing, completes or fails.
Added support for an optional `GARDEN_WORKFLOW_UID` environment variable that is sent along with streamed events & log entries (if it's defined).
=> feat(workflows): improved log & event streaming

garden-service/src/garden.ts, garden-service/test/unit/src/commands/get/get-config.ts
Added `projectName` and `allEnvironmentNames` to the output of the `get config` command.
=> feat(commands): add fields to get config output

garden-service/Dockerfile
When attempting to clone a repository from within the docker images we encountered the error pasted below. In order to connect to github, we need the appropriate ssh credentials passed in via a env variable `SSH_AUTH_SOCK`. We aren't using file based ssh keys, instead we are using an ssh agent which is then shared with the container. Unfortunately, the ability to ssh is missing, hence this pull request.
```
Error: Command "git clone --recursive --depth=1 --branch=development git@github.com:<owner>/<repo>git /project/.garden/sources/module/app--61c96b198b" failed with code 128:
--
Cloning into '/project/.garden/sources/module/app--61c96b198b'...
error: cannot run ssh: No such file or directory
fatal: unable to fork
```
**Which issue(s) this PR …
=> (fix) install ssh to base image

garden-service/src/plugins/kubernetes/helm/build.ts, garden-service/src/plugins/kubernetes/helm/common.ts, garden-service/src/plugins/kubernetes/helm/helm-cli.ts, garden-service/test/data/test-projects/conftest-kubernetes/helm/garden.yml, garden-service/test/data/test-projects/helm/postgres/garden.yml, garden-service/test/integ/src/plugins/kubernetes/helm/common.ts
What this PR does / why we need it:
The helm template command doesn't render values that need to be
retrieved from the cluster. We therefore use helm install|upgrade --dry-run instead.
Which issue(s) this PR fixes:
Fixes #1795
Reviewer notes:
Actually, I closed the prior issue prematurely @eysi09. This remains separate from the other fix I'll follow up with.
=> fix(k8s): ensure rendered helm chart contain runtime values

garden-service/src/enterprise/buffered-event-stream.ts
We were using the wrong param name for the event and log entry endpoint. Highlights the need for e2e tests. But this fixes it for now. 
N/A
Should we be referring to the project ID as project UID internally? It leaks the implementation details but it's still just internal, and I can imagine this happening again.
=> fix(enterprise): use correct body param when streaming events

.circleci/config.yml, garden-service/azure.Dockerfile, garden-service/bin/build-containers.sh, garden-service/bin/push-containers.sh
This PR adds a gardendev/garden-azure image
We're using the image in our pipeline and the projects tests pass using the following flow on gitlab-ci:
```
image:
name: fqxeni/azure-garden:0.11.14
entrypoint: [""]
include:
- template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'
variables:
DOCKER_HOST: tcp://docker:2375
services:
- docker:18.09-dind
stages:
- test
before_script:
- az login --service-principal --username=${AZURE_DEV_SERVICE_PRINCIPAL_ID} --password=${AZURE_DEV_SERVICE_PRINCIPAL_PASSWORD} --tenant=${AZURE_TENANT_ID}
- az aks get-credentials --name dev-cluster --resource-group Dev-Cluster
test:
stage: test
script:
- garden test --logger-type=basic --env=dev
```
=> feat: add garden-dev/garden-azure docker image

docs/guides/variables-and-templating.md, garden-service/src/config/config-context.ts, garden-service/src/template-string-parser.pegjs, garden-service/src/template-string.ts, garden-service/test/unit/src/config/config-context.ts, garden-service/test/unit/src/garden.ts, garden-service/test/unit/src/template-string.ts
This greatly expands the power of our template strings. I'll copy the
added docs here for details:
In addition to dot-notation for key lookups, we also support bracketed
lookups, e.g. `${some["key"]}` and `${some-array[0]}`.
This style offer nested template resolution, which is quite powerful,
because you can use the output of one expression to choose a key in a
parent expression.
For example, you can declare a mapping variable for your project, and
look up values by another variable such as the current environment name.
To illustrate, here's an excerpt from a project config with a mapping
variable:
```yaml
kind: Project
...
variables:
- replicas:
dev: 1
prod: 3
...
```
And here that variable is used in a module:
```yaml
kind: Module
...
services:
replicas: …
```
=> feat(template): support nested expressions, maps and numeric keys

garden-service/src/cli/cli.ts, garden-service/src/enterprise/buffered-event-stream.ts, garden-service/test/unit/src/platform/buffered-event-stream.ts
We now wait for `BufferedEventStream` to finish flushing any buffered events and log entries before exiting a command.
=> fix(enterprise): wait for event stream to flush

docs/reference/config.md, docs/reference/template-strings.md, garden-service/src/config/common.ts, garden-service/src/config/config-context.ts, garden-service/src/config/project.ts, garden-service/src/docs/template-strings.ts, garden-service/src/garden.ts, garden-service/static/docs/templates/template-strings.hbs, garden-service/test/unit/src/config/project.ts
This makes it easier to keep your project config neat and concise, allowing for some deduplication when environment configs repeat a lot of variables.
Also fixes the issue where template strings were resolved in all
environments, instead of just the selected one.
Fixes #1814
=> feat(config): allow environment[].variables to reference top-level vars

docs/README.md, docs/reference/providers/README.md, docs/reference/providers/exec.md, garden-service/src/commands/run/workflow.ts, garden-service/src/docs/generate.ts, garden-service/src/plugins/exec.ts, garden-service/src/util/util.ts, garden-service/test/unit/src/actions.ts, garden-service/test/unit/src/plugins/exec.ts
This allows projects to define arbitrary scripts to run on init.
This is handy for running arbitrary script when initializing.
For example, another provider might declare a dependency on this
provider, to ensure this script runs before resolving that provider.
=> feat(exec): add script option to exec provider configuration

garden-service/src/enterprise/buffered-event-stream.ts
We now include the log level of streamed log entries sent from `BufferedEventSream`.
=> feat(enterprise): include log level when streaming

examples/vote-helm/postgres/garden.yml
Postgres Helm chart was outdated.
=> chore(examples): update postgres helm chart

docs/using-garden/using-the-cli.md
Fixes a few dead links in the "Using the CLI" guide.
=> Fix a couple of link issues using garden cli

garden-service/src/vcs/git.ts
Cache results of the `git exec calls`.
Pretty anecdotal/not-profile-driven perf improvements, but intuitively it makes sense anyways.
For example, on a project i'm working on I get over 200 of:
```
Calling git with args 'rev-parse --show-toplevel'
```
with > 700 git commands executing
before:
```
❯ time gfs validate
garden validate 42.44s user 63.68s system 237% cpu 44.720 total
```
after:
```
❯ time gfs validate                   
garden validate  40.08s user 52.55s system 279% cpu 33.179 total
```
Faster commands :)
=> perf(git): cache git exec results

garden-service/src/commands/run/workflow.ts, garden-service/src/garden.ts, garden-service/test/data/test-project-invalid-workflow/garden.yml, garden-service/test/unit/src/garden.ts
We now throw validation errors for invalid workflow configs immediately after scanning and adding workflow configs.
Now that partially resolving workflow configs (i.e. everything except step configs, which are resolved just-in-time before they're run) has become cheap, performing this validation at scan-time warns the user of invalid workflow configs earlier in development.
Fixes #1931.
=> feat(core): throw workflow config errors on scan

garden-service/src/cli/cli.ts, garden-service/src/enterprise/buffered-event-stream.ts, garden-service/test/unit/src/platform/buffered-event-stream.ts
We now include the current environment name and namespace in requests when streaming events to the platform.
=> feat(enterprise): include env and ns in events

docs/reference/commands.md, docs/reference/config.md, garden-service/src/config/workflow.ts
Documents the currently supported GitHub events that can be used as workflow triggers, as these currently aren't documented anywhere. We should probably do this automatically at some point.
=> docs: add supported github events

docs/welcome.md
The links on the intro paged used to point to the `README.md` file of each
section. However, those READMEs are not included in the summary file
(`docs/README.md`) and therefore won't work on Gitbook. If we want to link
to the section READMEs, we need to explicitly add them to each section.
That is, the sections would look something like:
```
Basics ToC (or whatever we'd call it)
How Garden Works
Stack Graph
Getting Started ToC
0. Introduction
...and so on and so forth.
```
Instead of doing that, I just updated to intro links to point to the first page of each section.
Fixes #1937 
=> docs: fix links on intro page

README.md
The link to docs.garden.io is broken in [README.md Documentation section](https://github.com/garden-io/garden#documentation).
=> docs(readme): fix docs.garden.io link in readme Documentation section

garden-service/src/cli/cli.ts, garden-service/src/commands/get/get-config.ts, garden-service/src/commands/login.ts, garden-service/src/commands/run/workflow.ts, garden-service/src/constants.ts, garden-service/src/enterprise/buffered-event-stream.ts, garden-service/src/enterprise/workflow-lifecycle.ts, garden-service/src/events.ts, garden-service/src/exceptions.ts, garden-service/src/garden.ts, garden-service/test/unit/src/commands/run/workflow.ts, garden-service/test/unit/src/platform/buffered-event-stream.ts
When the user is logged in to Garden Enterprise, the `run workflow` command will now register a workflow run with the backend, and include the workflow run's UID in streamed events and log entries.
This enables `run workflow` command invocations from e.g. a local machine or an external CI system to be represented in Garden Enterprise.
Depends on #1936, so we should merge that first (I'll rebase on `master` and mark this PR as ready for review once that's done).
The `_workflowRunRegistered` control event seemed like the least hacky way to communicate the workflow run UID from the `run workflow` command to `BufferedEventStream`, but I'm open to other suggestions.
=> feat(enterprise): register workflow runs

garden-service/src/plugins/kubernetes/local/config.ts
Adds `docker-desktop` as supported context for the `local-kubernetes` provider. Bumped into this after updating Docker for Mac.
Fixes #
=> fix(local-k8s): add 'docker-desktop' as supported context

garden-service/src/plugins/kubernetes/kubernetes-module/common.ts, garden-service/src/plugins/kubernetes/kubernetes-module/handlers.ts, garden-service/src/plugins/kubernetes/status/status.ts, garden-service/test/integ/src/plugins/kubernetes/kubernetes-module/handlers.ts
Before this fix, we were using the module/service name as the annotation value for all manifests/resources.
This didn't work for `Namespace` resources in particular, since deploying a `kubernetes` module that included a `Namespace` manifest would result in namespaces with different names (but deployed from the same module, e.g. by another user in the same cluster) being deleted.
The same applied to the `delete service` command when used in the same context.
We now annotate `Namespace` manifests/resources with the namespace name, and deploy/delete such resources accordingly, which fixes this problem.
=> fix(kubernetes-module): fix namespace handling

garden-service/src/plugins/kubernetes/kubernetes.ts
The util service was only being deployed if we were using an external registry. However kaniko works fine with an in-cluster registry, and kaniko requires the util service.
Fixes #1962
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/garden-io/garden/1963)
=> deploy util service if using kaniko

docs/guides/cloud-provider-setup.md
Documents a link to AWS's storage class setup guide. Dynamically provisioning PV's doesn't work out of the box, so it's good to have this documented.
=> docs: refer to AWS storage class docs

garden-service/src/commands/base.ts, garden-service/src/constants.ts, garden-service/src/garden.ts, garden-service/src/task-graph.ts, garden-service/src/tasks/base.ts, garden-service/src/tasks/build.ts, garden-service/src/tasks/delete-service.ts, garden-service/src/tasks/deploy.ts, garden-service/src/tasks/get-service-status.ts, garden-service/src/tasks/get-task-result.ts, garden-service/src/tasks/hot-reload.ts, garden-service/src/tasks/publish.ts, garden-service/src/tasks/resolve-module.ts, garden-service/src/tasks/resolve-provider.ts, garden-service/src/tasks/stage-build.ts, garden-service/test/unit/src/task-graph.ts
We now set concurrency limits for individual action types, which should
better align with resource pressure from different types.
We also set a hard global limit and some upper limit on module and
provider resolution, which was previously completely unlimited, which
could cause memory thrashing (even crashes) with very large projects
(200+ modules).
=> improvement(core): set smarter limits on concurrent graph actions

docs/using-garden/variables-and-templating.md, garden-service/src/template-string-parser.pegjs, garden-service/test/unit/src/template-string.ts
The `contains` operator can be used to see if an array contains a value,
an object contains a key, or if a string contains another string.
Examples:
* `${var.some-array contains "some-value"}` checks if the
`var.some-array` array includes the string `"some-value"`.
* `${var.some-string contains "some"}` checks if the `var.some-string`
string includes the string `"some"`.
* `${var.some-object contains "some-key"}` checks if the
`var.some-object` object includes the key `"some-key"`.
=> feat(config): add `contains` operator for template strings

garden-service/src/garden.ts, garden-service/test/unit/src/commands/get/get-config.ts
This fixes a recent regression where project IDs would not be included in the output of the `get config` command unless logged in.
=> fix(enterprise): add project id to config dump

docs/guides/container-modules.md, docs/reference/module-types/container.md, docs/reference/module-types/maven-container.md, garden-service/src/plugins/container/build.ts, garden-service/src/plugins/container/config.ts, garden-service/src/plugins/exec.ts, garden-service/src/runtime-context.ts, garden-service/test/data/test-projects/exec-artifacts/garden.yml, garden-service/test/unit/src/plugins/container/container.ts, garden-service/test/unit/src/plugins/exec.ts
This allows users to reference the module version at build time, which
can be quite useful to e.g. set deterministic values for build
artifacts.
For container builds, a `GARDEN_MODULE_VERSION` build arg is provided.
For exec module builds, tasks and tests, a `GARDEN_MODULE_VERSION` env variable is exposed to the command/script.
=> Expose build version in exec and container builds

docs/reference/commands.md, docs/using-garden/tasks.md, docs/using-garden/variables-and-templating.md, garden-service/src/cli/cli.ts, garden-service/src/commands/base.ts, garden-service/src/garden.ts, garden-service/test/unit/src/cli/base.ts, garden-service/test/unit/src/cli/cli.ts, garden-service/test/unit/src/garden.ts
From the added docs:
For tasks that are often run ad-hoc from the CLI, you can use variables and the `--var` CLI flag to pass in values to the task.
Here for example, we have a simple container task that can receive an argument via a variable:
```yaml
kind: Module
...
tasks:
- name: my-task
command: ["echo", "${var.my-task-arg || ''}"]
...
```
You can run this task and override the argument variable like this:
```sh
garden run task my-task --var my-task-arg="hello"!
```
=> feat(cli): add --var flag for setting individual variable values

docs/reference/commands.md, garden-service/src/plugins/kubernetes/port-forward.ts, garden-service/src/proxy.ts, garden-service/src/tasks/deploy.ts, garden-service/src/types/service.ts
We were using the Garden service name instead of the Kubernetes Service name, which caused problems when those differed.
Fixes #1827
cc @petr-motejlek
=> fix(k8s): incorrect Service name used for port forwards

garden-service/package-lock.json, garden-service/package.json, garden-service/src/build-dir.ts, garden-service/src/plugins/kubernetes/hot-reload.ts, garden-service/src/plugins/kubernetes/port-forward.ts, garden-service/src/util/fs.ts, garden-service/test/unit/src/plugins/kubernetes/hot-reload.ts
See commits for details. We had a few path handling issues after change made in v0.12.0, in particular on Windows and when hot-reloading `helm` modules.
Fixes #
Would be good to do a sanity check on this. I've tested on both Windows and mac, for container and helm+container syncs, but ya never know.
=> Fix hot reloading issues

docs/reference/commands.md, docs/reference/module-types/terraform.md, garden-service/src/config/common.ts, garden-service/src/plugins/terraform/terraform.ts, garden-service/src/types/service.ts, garden-service/test/data/test-projects/terraform-module/tf/foo.tf, garden-service/test/unit/src/actions.ts, garden-service/test/unit/src/commands/delete.ts, garden-service/test/unit/src/commands/deploy.ts, garden-service/test/unit/src/plugins/terraform/terraform.ts
=> fix(terraform): allow map outputs from modules

docs/reference/commands.md, docs/reference/config.md, garden-service/src/commands/run/workflow.ts, garden-service/src/config/workflow.ts, garden-service/test/unit/src/commands/run/workflow.ts, garden-service/test/unit/src/config/workflow.ts
Allows users to conditionally skip workflow steps with template strings.
Closes #1927
=> feat(workflows): add skip option for workflow steps

garden-service/src/build-dir.ts, garden-service/test/data/dummy-rsync/min-version/rsync, garden-service/test/unit/src/build-dir.ts
New rsync versions add a "v" prefix on the version string, and our regex didn't expect that. Fun!
=> fix(core): error with rsync v3.2.3 and later on certain OSes

garden-service/src/cli/cli.ts, garden-service/src/commands/login.ts, garden-service/src/commands/run/workflow.ts, garden-service/src/config/project.ts, garden-service/src/enterprise/buffered-event-stream.ts, garden-service/src/enterprise/init.ts, garden-service/src/enterprise/workflow-lifecycle.ts, garden-service/src/garden.ts, garden-service/test/unit/src/commands/get/get-outputs.ts, garden-service/test/unit/src/commands/login.ts
Fixes a recent regression in the login flow, and stops throwing enterprise-related errors for non-enterprise projects when the user is logged in.
Also added unit tests for the `login` command.
=> fix(enterprise): fix login flow

garden-service/src/config/config-context.ts, garden-service/src/config/provider.ts, garden-service/src/outputs.ts, garden-service/src/template-string.ts, garden-service/test/unit/src/config/config-context.ts, garden-service/test/unit/src/template-string.ts
Partial resolution was mangling key segments with dots in them, as well
as nested template strings.
=> fix(config): incorrect handling of bracketed template keys with dots

core/src/config/common.ts, core/src/config/workflow.ts, core/src/plugins/kubernetes/volumes/persistentvolumeclaim.ts, core/src/template-string.ts, core/src/util/util.ts, core/test/unit/src/config/common.ts, core/test/unit/src/docs/joi-schema.ts, core/test/unit/src/garden.ts, core/test/unit/src/template-string.ts, docs/reference/module-types/persistentvolumeclaim.md, docs/using-garden/variables-and-templating.md
Any object or mapping field supports a special `$merge` key, which
allows you to merge two objects together. This can be used to avoid
repeating a set of commonly repeated values.
Example:
```yaml
kind: Project
...
variables:
- commonEnvVars:
LOG_LEVEL: info
SOME_API_KEY: abcdefg
EXTERNAL_API_URL: http://api.example.com
...
```
```yaml
kind: Module
name: service-a
...
services:
env:
$merge: ${var.commonEnvVars}
OTHER_ENV_VAR: something
LOG_LEVEL: debug
...
```
```yaml
kind: Module
name: service-b
...
services:
env:
SOME_API_KEY: default
$merge: ${var.commonEnvVars}
...
```
=> feat(config): add $merge key for merging maps together in configs

core/src/config/provider.ts, core/src/garden.ts, core/src/plugins/container/container.ts, core/src/tasks/resolve-provider.ts, core/test/unit/src/actions.ts, core/test/unit/src/config/project.ts, core/test/unit/src/garden.ts, docs/reference/config.md, docs/reference/providers/conftest-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/exec.md, docs/reference/providers/hadolint.md, docs/reference/providers/kubernetes.md, docs/reference/providers/local-kubernetes.md, docs/reference/providers/maven-container.md, docs/reference/providers/openfaas.md, docs/reference/providers/terraform.md
This adds a `providers[].dependencies` field, which can be used to
explicitly declare dependencies at config time. Previously you could
only create implicit dependencies by referencing another provider's
outputs in template strings.
This should be handy when e.g. using the `exec` provider with an
`initScript`, which should run before resolving other providers.
=> feat(config): allow explicitly declaring provider dependencies

core/src/plugins/terraform/commands.ts, core/src/plugins/terraform/common.ts, core/src/plugins/terraform/init.ts, core/src/plugins/terraform/module.ts, core/src/plugins/terraform/terraform.ts, core/test/data/test-projects/terraform-provider/garden.yml, core/test/unit/src/plugins/terraform/terraform.ts, docs/reference/module-types/terraform.md, docs/reference/providers/container.md, docs/reference/providers/terraform.md
You can now set `allowDestroy: true` in both the provider config and
`terraform` module configs, which if set allow Garden to automatically
destroy stacks when calling `garden delete env` and/or
`garden delete service <module name>`.
Also added are new `garden plugins terraform destroy-root` and
`garden plugins terraform destroy-module` commands.
Closes #1928
cc @noizwaves
=> feat(terraform): add allowDestroy flags to automatically destroy stacks

core/src/commands/plugins.ts
I kept mistyping it and would see users do the same, so why not :P
=> improvement: add plugin alias for plugins command

cli/bin/garden, cli/package.json
This is one of a series of improvements I'm working on, to warn users
about very large projects that probably need better configuration of
includes/excludes/ignores.
This catches the "nuclear" case of running out of heap space, exiting
with a standard code of 137, and printing an error with a link to docs.
See #2003 for a reported case.
=> improvement(cli): catch OOM errors and exit with helpful error message

core/src/util/util.ts
Another one in the series of potential errors when the project file
count is too high.
See issue #2003 for one reported case of this.
=> improvement: explicitly catch EMFILE errors with better error message

cli/src/add-version-files.ts, core/src/commands/util/hide-warning.ts, core/src/commands/util/util.ts, core/src/db/connection.ts, core/src/db/entities/local-address.ts, core/src/db/entities/warning.ts, core/src/garden.ts, core/src/vcs/vcs.ts, core/test/unit/src/commands/util/hide-warning.ts, core/test/unit/src/db/entities/warning.ts, core/test/unit/src/vcs/vcs.ts, docs/reference/commands.md
Yet another enhancement geared towards alerting users about potential
misconfiguration.
This includes a new command and mechanism to suppress individual
warnings. We can use that to emit more warnings of this nature, where
the warning may or may not be relevant and could be annoying to see on
every invocation.
=> improvement(core): warn on large file count in modules

cli/bin/garden
We were essentially loading our code twice on startup, simple fix.
=> fix(cli): fix startup time regression after added OOM handling

core/src/plugins/container/config.ts, core/src/plugins/exec.ts, core/src/plugins/kubernetes/config.ts, docs/reference/module-types/container.md, docs/reference/module-types/exec.md, docs/reference/module-types/helm.md, docs/reference/module-types/kubernetes.md, docs/reference/module-types/maven-container.md
The location of the artifacts dir was missing from the field description.
Fixes #
=> docs: add path to artifacts dir to artifacts field description

core/src/actions.ts, core/src/enterprise/buffered-event-stream.ts, core/src/events.ts, core/src/logger/log-entry.ts, core/src/task-graph.ts, core/test/unit/src/platform/buffered-event-stream.ts, core/test/unit/src/task-graph.ts
Changed `BufferedEventStream`'s batching logic to fill batches with events / log entries up to a constant maximum byte count.
Compared to the previous batching logic, the new implementation is fundamentally robust with respect to request size, and generally drains its buffer much faster.
Also streamlined some event payloads to omit unnecessary and potentially very large fields.
=> fix(enterprise): enforce stream batch size

core/src/docs/common.ts, scripts/test-release.sh
There was some code that was still anticipating the `v` prefix in version strings.
Fixes #
=> chore: remove left out v prefixes from version strings

core/src/enterprise/auth.ts, core/src/enterprise/secrets/garden/get-secret.ts
This PR changes the authentication behaviour if a user set `GARDEN_AUTH_TOKEN`.
Before we would expect the value of `GARDEN_AUTH_TOKEN` to be a jwt and all the requests to GE were authenticated through `x-access-auth-token`.
We introduced in GE a new authentication header `x-ci-token`, which will get set if `GARDEN_AUTH_TOKEN`.
The old behaviour of overriding a persisted token remains unchanged, as well as the error/inconsistency handling.
=> feat(enterprise): enable authentication via ci-tokens

core/src/commands/link/module.ts, core/src/commands/link/source.ts, docs/reference/commands.md
Fix typo in docs from "containes" to "contains"
Fixes the typo in docs.
No issue exist for this change
none
=> Fix typo in docs from "containes" to "contains"

core/src/cli/cli.ts, core/src/cli/params.ts, core/src/logger/logger.ts, core/src/logger/renderers.ts, core/src/logger/writers/fancy-terminal-writer.ts, core/test/helpers.ts, core/test/setup.ts, core/test/unit/src/cli/cli.ts, core/test/unit/src/logger/renderers.ts, docs/reference/commands.md
Previously we would print the timestamp on the log entry proper, as opposed to on the latest message state. That meant that for basic log entries, the message state was being rendered would have the older timestamp of the entry itself. This fixes that.
Also, previously we'd show timestamps with the fancy logger as well but that doesn't really make sense because fancy entries update in-place and it's not clear what timestamp should mean in that context. So now we automatically set the logger to basic when timestamps are enabled. 
Fixes #
=> Fix timestamps

CONTRIBUTING.md
We removed the `v` prefix from our version strings in 0.12.4. The `CONTRIBUTING.md` guide has now been updated to reflect this.
=> chore: update version format in contributing guide

docs/guides/remote-kubernetes.md
Fixes a documentation error on the Remote Kubernetes page. Looks like someone bulk updated 'garden-service' to 'core', and missed this change.
N/A
Can't add reviewers, not sure if it's a permissions thing or what.
=> docs: Fix uninstall instructions on Remote Kubernetes doc

CONTRIBUTING.md, core/src/plugins/kubernetes/kubernetes.ts, core/src/plugins/kubernetes/local/local.ts, docs/guides/local-kubernetes.md, docs/misc/faq.md, docs/reference/providers/kubernetes.md, docs/reference/providers/local-kubernetes.md, markdown-link-check-config.json, package.json, scripts/check-docs.sh, yarn.lock
We now check one file at a time for external links. This avoids the `429 Too Many Requests` errors we've regularly been getting in CI.
Thus, we've also gotten rid of our dev dependency on the `parallel` command.
Since checking the files in sequence slows the process down, we've also removed the `check-docs` step from our pre-push hook (it's still run as part of `check-all`).
=> chore: fix check-docs script

core/src/events.ts, core/src/task-graph.ts, core/test/unit/src/task-graph.ts
We've now removed `dependencyResults` from the payload types of the `taskComplete` and `taskError` events (which were previously `GraphResult`).
Since `dependencyResults` is a recursive data structure, it can grow very large. And since `dependencyResults` in event payloads is not currently being used anywhere, it can safely be removed.
We also omit `result.output.log` and `result.output.buildLog` when present, since those strings can grow arbitrarily long (and since we're not currently using those payload fields anywhere).
=> fix(core): omit dependencyResults from events

core/src/garden.ts, core/src/resolve-module.ts, core/test/unit/src/garden.ts
We were unnecessarily resolving remote sources sequentially, which would slow down initialization quite a bit with multiple remote sources.
cc @mitchfriedman
=> improvement(core): resolve remote sources in parallel

core/src/plugins/kubernetes/config.ts, docs/guides/in-cluster-building.md
Bumps kaniko version to `1.2.0`. We need this because the previous version had a bug that we were bumping into.
Fixes #
=> chore(k8s): bump kaniko version

core/src/cli/params.ts
Before this fix, any errors in command results would not be rendered when `-o yaml` was used (instead, an empty array was rendered).
=> fix(cli): fix error rendering for yaml output

core/src/plugins/kubernetes/status/pod.ts, core/src/plugins/kubernetes/status/workload.ts
Show more log lines when K8s deployment fails. I added this because we were sometimes just missing useful log lines. For example:
```
<Showing last 20 lines per pod in this Deployment. Run the following command for complete logs>
$ kubectl -n ge-eysi --context=gke logs deployment/api
****** api-586d46f47f-k6wqv ******
------ api ------    at raiseError (/app/api/node_modules/env-var/lib/variable.js:36:11)
at Object.asInt (/app/api/node_modules/env-var/lib/variable.js:83:9)
at Object.<anonymous> (/app/api/dist/constants.js:94:44)
at Module._compile (internal/modules/cjs/loader.js:1137:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
at Module.load (internal/modules/cjs/loader.js:985:32)
at Function.Module._load …
```
=> improvement(k8s): show more pod log lines by default

core/src/cli/helpers.ts, core/src/config/workflow.ts, core/src/util/util.ts, core/test/unit/src/config/workflow.ts
Global options (such as `--env` or `-l`) have no effect when used in workflow step commands, since the step commands share a Garden instance with the enclosing `run workflow` command.
To prevent user confusion, we now validate that global options are not used in workflow step command specs, and throw an error if any are detected.
For example, the following workflow config
```yaml
kind: Workflow
name: test-workflow
steps:
- command: [test, "--env=foo", "-l", "4"
```
Would fail validation with the following error message:
```
$ garden validate
Invalid step command options for workflow test-workflow:
In command [test, --env=foo, -l, 4]: --env, -l
See error.log for detailed error message
```
=> fix(workflows): forbid use of global options

core/src/logger/renderers.ts, core/src/logger/writers/json-terminal-writer.ts, core/test/unit/src/logger/renderers.ts, core/test/unit/src/logger/writers/json-terminal-writer.ts
The JSON logger now includes timestamps in its log entries.
Fixes #2095
=> improvement: include timestamps in JSON logger

core/src/cli/cli.ts, core/src/commands/base.ts, core/src/commands/run/workflow.ts, core/src/logger/util.ts, core/src/task-graph.ts, core/test/unit/src/logger/renderers.ts
Previously, we were logging the details of failed tasks (along with their successfully executed dependencies, if any) when a workflow failed.
We've now simplified this to only render the error messages by default, and rendering the details of the failed tasks only (without dependencies) for log levels `debug` and higher.
The output logged to `error.log` has been streamlined in the same way, omitting details of successful dependencies of failed tasks.
=> fix(cli): less noisy error rendering for workflows

core/src/cli/cli.ts
This fixes a regression introduced in #2109. Non-task errors weren't being logged at the end of command runs.
We've now reinstated the logging of any errors at the end of commands.
=> fix(cli): fix regression in error logging

core/src/plugins/kubernetes/helm/helm-cli.ts
There was a bug in the version of Helm we're using that was causing issues for users (https://github.com/helm/helm/issues/2998). This PR bumps the Helm version to v3.3.4.
=> chore(k8s): bump helm version

core/src/plugins/kubernetes/kubernetes-module/handlers.ts, core/test/data/test-projects/kubernetes-module/module-simple/garden.yml, core/test/data/test-projects/kubernetes-module/with-namespace/garden.yml, core/test/integ/src/plugins/kubernetes/kubernetes-module/config.ts, core/test/integ/src/plugins/kubernetes/kubernetes-module/handlers.ts
This fixes a regression introduced when we added hot reloading support for the `kubernetes-module` module type.
Also added an integ test case to guard against this regression in the future.
=> fix(kubernetes-module): fix regression

.github/stale.yml
Configure Stalebot to not close issues with a `bug` label. Instead we can label bugs as `wontfix` and close them manually if needed (e.g. because a reproducible is needed or there's negative cost-benefit balance to fixing the it).
Also increases the `daysUntilStale` value from 60 to 90 days. The former felt a little too short, in particular for feature requests that we might want to look into but can't in the span of two months.
N/A
Does 90 days until stale make sense?
=> chore(stalebot): don't mark bugs as stale + increase days until stale

core/src/commands/login.ts, core/test/data/test-projects/login/has-domain-and-id/garden.yml, core/test/data/test-projects/login/has-domain/garden.yml, core/test/data/test-projects/login/missing-domain/garden.yml, core/test/data/test-projects/login/secret-in-project-variables/garden.yml, core/test/unit/src/commands/login.ts
Fixes an issue where using secrets outside of providers in project configuration would break the login command.
=> fix(enterprise): don't resolve config on login

core/src/commands/run/workflow.ts, core/src/config/workflow.ts, core/src/enterprise/workflow-lifecycle.ts, core/src/events.ts, core/src/exceptions.ts, core/test/unit/src/commands/run/workflow.ts, core/test/unit/src/config/workflow.ts, docs/reference/commands.md, docs/reference/workflow-config.md, docs/using-garden/workflows.md
Workflow steps can now use the `when: always | never | onError` modifier.
Steps with `when: always` can be used e.g. for running scripts or commands at the end of the workflow, regardless of whether the workflow failed.
Steps with `when: onError` can facilitate custom error handling and cleanup after failed steps or sequences of steps.
See the updated workflows guide (under Using Garden) for more details.
=> feat(workflows): implemented when modifier

core/src/config/common.ts, core/test/unit/src/config/common.ts, docs/reference/module-types/terraform.md, docs/reference/project-config.md, docs/reference/template-strings.md
Fixes issue where primitive values would get cast on schema validation. For example, something like `DB_PORT: "8080"` would be resolved as `DB_PORT: 8080`.
Fixes #
=> fix(core): ensure primitive values are not cast on schema validation

.gitbook.yaml
We're moving our blog posts to our own website and noticed that some of the links to our docs in the blog posts are outdated. This PR adds redirects to address that.
cc @wints 
Fixes #
=> docs: add more gitbook redirects to handle stale blog post links

core/src/config/common.ts, core/src/plugins/kubernetes/config.ts, core/src/types/service.ts, core/test/unit/src/config/common.ts, docs/reference/module-types/container.md, docs/reference/module-types/maven-container.md
Allow wildcards in the first DNS label of a hostname. I.e., we allow `*.foo.bar`, but not `foo.*.bar`. This is consistent with how Kubernetes treats hostnames.
Fixes #
Only allowing wildcards in the first label in ingress hostnames is pretty contested in the K8s community, see for example this issue: https://github.com/kubernetes/kubernetes/issues/41881.
However, I figured it'd make sense to start with the same restrictions as K8s since that's where the field is most used.
=> improvement(core): allow wildcard in first label in hostname

core/src/cli/cli.ts, core/src/commands/base.ts, core/src/commands/build.ts, core/src/commands/call.ts, core/src/commands/delete.ts, core/src/commands/deploy.ts, core/src/commands/dev.ts, core/src/commands/get/get-status.ts, core/src/commands/get/get-task-result.ts, core/src/commands/get/get-test-result.ts, core/src/commands/publish.ts, core/src/commands/run/task.ts, core/src/commands/run/test.ts, core/src/commands/run/workflow.ts, core/src/commands/test.ts, core/src/enterprise/buffered-event-stream.ts, core/test/unit/src/cli/cli.ts, core/test/unit/src/enterprise/buffered-event-stream.ts, core/test/unit/src/server/dashboard-event-stream.ts
We now only stream events and log entries to GE for whitelisted commands (those with `streamEvents = true` and/or `streamLogEntries = true`).
I couldn't think of a decent way to test this that didn't rely on counting invocations to `BufferedEventStream#connect`. Is this fine as is?
=> fix(enterprise): whitelist commands for streaming

core/src/logger/util.ts, core/src/plugins/container/build.ts, core/src/plugins/exec.ts
Logs exec module build logs when log level is verbose or greater. Also sets log level on container builds logs to verbose (from debug).
Fixes #2139 
=> improvement(exec): log build output with verbose logger

examples/tasks/postgres/garden.yml
The chart used for the `postgres` module for the `tasks` example was no longer deploying, which caused problems in CI.
This was fixed by using the same Helm chart for `postgres` as in the `vote-helm` example project.
=> chore: replace postgres chart in tasks example

core/src/commands/run/workflow.ts, core/src/events.ts, core/test/unit/src/commands/run/workflow.ts
This new event is necessary to correctly handle failed workflows when combined with the `when` modifier.
Also streamlined the module version included in task outputs in event payloads to avoid bloat.
=> fix(enterprise): add workflowError event

cli/src/add-version-files.ts, core/src/commands/get/get-debug-info.ts, core/src/commands/migrate.ts, core/src/garden.ts, core/src/util/fs.ts, core/src/vcs/vcs.ts, core/test/unit/src/vcs/git.ts, core/test/unit/src/vcs/vcs.ts
Because we require an `include` or `exclude` to be set on modules if
there are multiple modules in the same directory, this would only have
come up  as an issue if there's a single module in the project root
_or_ if users had used `exclude` fields and not `include` fields to
specify the module context.
Which is likely why this passed by for so long, but certainly this
change is the more sane default behavior.
=> fix(core): auto-exclude git and .garden dirs for modules in project root

core/src/garden.ts, core/src/util/fs.ts, core/test/unit/src/util/fs.ts
Came across this while debugging another issue. Simple fix.
=> fix(core): don't flag remote modules as overlapping with modules in root

core/src/garden.ts, core/src/plugins/terraform/commands.ts, core/src/plugins/terraform/common.ts, core/src/plugins/terraform/init.ts, core/src/plugins/terraform/module.ts, core/src/plugins/terraform/terraform.ts, core/test/data/test-projects/terraform-module/garden.yml, core/test/data/test-projects/terraform-module/tf/foo.tf, core/test/data/test-projects/terraform-provider/garden.yml, core/test/data/test-projects/terraform-provider/tf/foo.tf, core/test/unit/src/plugins/terraform/common.ts, core/test/unit/src/plugins/terraform/terraform.ts, docs/reference/module-types/terraform.md
You can now set the `workspace` field on the Terraform provider as well
as on `terraform` modules. When set, Garden will select (creating if
necessary) the specified Terraform workspace ahead of applying,
planning, destroying etc.
Closes #2024
=> feat(terraform): add support for workspaces

core/src/build-staging/rsync.ts
Fixes regression in the recent experimental build staging PR.
=> fix(core): incorrect paths in build staging rsync command

core/src/build-staging/rsync.ts, core/test/unit/src/build-staging/build-staging.ts, core/test/unit/src/build-staging/rsync.ts
Reported here:
https://kubernetes.slack.com/archives/CKM7CP8P9/p1606839970383500
This was a bit of a blunder, sorry about that. I had forgotten to move
some tests over to the common tests for both the rsync and the new
experimental implementation, and introduced a regression.
=> fix(core): regression when copying single files in build dependencies

core/src/config/config-context.ts, core/src/config/workflow.ts, core/test/unit/src/config/workflow.ts
We don't want to allow template strings in workflow names or trigger specs.
=> fix(core): prohibit templates in workflow name

core/src/template-string-parser.pegjs, core/src/template-string.ts, core/test/unit/src/actions.ts, core/test/unit/src/config/config-context.ts, core/test/unit/src/garden.ts, core/test/unit/src/template-string.ts, docs/using-garden/variables-and-templating.md
From the added docs:
In addition to [normal] conditionals [...] you can use if/else
blocks. These are particularly handy when templating multi-line strings
and generated files in [module templates](./module-templates.md).
The syntax is
`${if <expression>}<content>[${else}]<alternative content>${endif}`,
where `<expression>` is any expression you'd put in a normal template
string.
Here's a basic example:
```yaml
variables:
some-script: |
#!/bin/sh
echo "Hello, I'm a bash script!"
${if environment.name == "dev"}
echo "-> debug mode"
DEBUG=true
${else}
DEBUG=false
${endif}
...
```
You can also nest if-blocks, should you need to.
We could fairly easily add more types of blocks later, if we come up with some good ideas and use-cases.
=> feat(template): support if-blocks for multi-line conditionals

core/package.json, core/src/util/streams.ts, core/src/util/util.ts, core/src/vcs/git.ts, core/test/unit/src/util/streams.ts, core/test/unit/src/vcs/git.ts, examples/vote/garden.yml, yarn.lock
This fixes a performance and memory consumption issue when specifying
multiple `dotIgnoreFiles`.
We do this using a streaming set intersection, which avoids storing
unnecessary data in memory during the scan, relying on a sorted file
order coming from git.
It's not exactly a trivial implementation but this is only applied when
multiple .ignore files are configured, which is anyway a problematic
routine prone to thrashing the heap.
Closes #2084 (I _think_)
=> improvement(core): more efficient file scanning with multiple ignores

core/src/plugins/kubernetes/helm/build.ts
This is a temporary fix, in place of #2173. Since the old stable helm repository is no longer usable, this switches to using the stable archive repo as documented here: https://helm.sh/docs/faq/#i-am-getting-a-warning-about-unable-to-get-an-update-from-the-stable-chart-repository
1. Reset kubernetes cluster (or otherwise destroy ingress).
2. `rm -rf ~/Library/Caches/helm` the helm cache must be cleared to force a new download.
3. `helm repo update && helm repo remove stable`
4. cd `examples/demo-project`
5. `garden dev --force-refresh`
Without this PR's changes, you should see the `chart.metadata is required` error. With this PR's changes, you should be able to successfully install the nginx ingress and start the …
=> fix: use archive stable repository

core/src/enterprise/buffered-event-stream.ts, core/src/events.ts, core/src/logger/log-entry.ts, core/src/logger/log-node.ts, core/src/logger/logger.ts, core/src/logger/renderers.ts, core/src/logger/util.ts, core/src/logger/writers/fancy-terminal-writer.ts, core/src/logger/writers/fullscreen-terminal-writer.ts, core/test/helpers.ts, core/test/unit/src/cli/cli.ts, core/test/unit/src/commands/run/workflow.ts, core/test/unit/src/enterprise/buffered-event-stream.ts, core/test/unit/src/logger/log-entry.ts, core/test/unit/src/logger/log-node.ts, core/test/unit/src/logger/logger.ts, core/test/unit/src/logger/renderers.ts, core/test/unit/src/logger/writers/basic-terminal-writer.ts, core/test/unit/src/logger/writers/fancy-terminal-writer.ts, core/test/unit/src/logger/writers/file-writer.ts, core/test/unit/src/logger/writers/json-terminal-writer.ts, core/test/unit/src/server/server.ts, core/test/unit/src/util/util.ts
The log entries we were sending over didn't include all the message metadata to properly render them in GE. We were also including previous message states with the message sent which we shouldn't do. 
Fixes #
I kept the previous fields in the payload to maintain compatibility. We need to discuss how we do this moving forward. 
I also renamed some fields for clarity.
=> improvement(enterprise): include message metadata with log entries

core/src/config-graph.ts, core/src/tasks/deploy.ts, core/src/tasks/test.ts, core/test/unit/src/config-graph.ts
Previously, we didn't show the runtime dependencies of disabled nodes, which seemed confusing to me. Also, with #2169  in combination with this, we get a stable layout even if you disable modules/services/etc.
=> improvement(dashboard): show proper dependencies of disabled graph nodes

core/src/enterprise/buffered-event-stream.ts, core/src/logger/log-entry.ts, core/src/logger/log-node.ts, core/src/logger/logger.ts, core/src/logger/renderers.ts, core/test/unit/src/commands/run/workflow.ts, core/test/unit/src/logger/log-entry.ts, core/test/unit/src/logger/logger.ts, core/test/unit/src/logger/renderers.ts
Log entry streaming was failing because GE was throwing validation errors for the request payload. Turns placeholder entries were being shipped along and they were missing timestamps. 
I added timestamps to payload entries for good measure but also made sure we're sending them to begin with. Placeholders are not really log messages, but we've been treating them as such for convenience which requires a few special cases. I left a code comment to remind myself to refactor this.
I also refactored some tests and added new ones.
Fixes #
Once we merge this, Garden core `master` will be incompatible with GE. In particular this applies to the demo server. So we need to make sure to not …
=> chore(enterprise): fix log entry event payload

examples/deployment-strategies/garden.yml
The example was missing templating on the default hostname.
=> chore(examples): fix hostname in deployment-strategies example

core/src/cli/cli.ts, core/src/cli/params.ts, core/src/constants.ts, core/src/garden.ts, core/src/proxy.ts, core/test/unit/src/cli/cli.ts, docs/reference/commands.md
You can now set `--disable-port-forwards` or
`GARDEN_DISABLE_PORT_FORWARDS=true` to disable automatic port
forwarding, when running deploy/dev commands in watch mode.
=> feat(core): allow disabling port forwards

core/src/commands/logout.ts, core/src/enterprise/api.ts, core/src/enterprise/auth.ts
This PR fixes a problem we introduced recently where we would start the auth token refresh interval when using an Access Token. 
Additionally, I refactored the `logout` function, replacing old unused code with the actual implementation that was in `EnterpriseApi`
Fixes #
=> fix(enterprise): fix start interval when using access tokens

core/src/commands/login.ts, core/src/enterprise/auth.ts
Previously, running `garden logout` would throw if the logout API call fails and the access token would not be removed.
Fixes #
=> fix(enterprise): don't throw if log out fails

core/src/commands/build.ts, core/src/commands/deploy.ts, core/src/commands/dev.ts, core/src/commands/publish.ts, core/src/commands/run/task.ts, core/src/commands/run/test.ts, core/src/commands/test.ts
For now, we'll only stream log entries for the `run workflow` command (when logged in).
=> fix(enterprise): limit log streaming to workflows

core/src/commands/link/source.ts, core/src/commands/update-remote/sources.ts, core/src/garden.ts, core/src/plugin-context.ts, core/test/unit/src/commands/get/get-linked-repos.ts, core/test/unit/src/garden.ts
Requested on Slack, kinda surprised this hadn't come up sooner.
Project sources now support same template strings as providers (aside
from referencing providers, since they're initialized later).
=> feat(config): allow template strings in project source definition

core/src/config/config-context.ts, core/src/config/module-template.ts, core/src/garden.ts, core/src/plugins/templated.ts, core/src/resolve-module.ts, core/test/data/test-projects/module-templates/module-templates.json, core/test/data/test-projects/module-templates/modules.garden.yml, core/test/data/test-projects/module-templates/source.txt, core/test/data/test-projects/module-templates/templates.garden.yml, core/test/helpers.ts, core/test/unit/src/config/base.ts, core/test/unit/src/config/module-template.ts, core/test/unit/src/garden.ts, docs/reference/module-types/templated.md
Basically we now defer the full resolution on input template strings,
with the caveat that input values needed for module identifiers need
to be resolvable immediately.
Previously the values passed to the `inputs` field on templated modules
only had a very limited templating context available.
This involved quite a bit of added complexity, which is prompting me to
seriously consider a refactor in our template string resolution logic. This 
does the job for now, but I think we'll soon want to implement at least
partial lazy+recursive resolution of template strings, instead of all
this fine-grained logic to control what's resolved when.
=> improve(config): allow most template strings in templated module inputs

core/src/plugins/kubernetes/port-forward.ts, core/src/proxy.ts
Fixes #2129 (which turned out only partially to have to do with hot reloading, specifically)
I found two problems that relate to the issue, both pretty subtle.
One was that the subprocesses used for k8s port forwards could in some cases hang around after the main process closes. I _think_ the first commit takes care of that, at least I couldn't get it to come up again after the change.
Second was that we weren't properly catching the EADDRINUSE error from the proxy server we create as soon as we allocate the proxy (i.e. even before the underlying port-forward is started).
The reason this issue had eluded us during testing appears to be that it only came up on consecutive runs of Garden, where Garden would attempt to get the same port again on the next run, but Windows appears to reject …
=> Fix port forward issues on Windows

core/src/commands/run/workflow.ts
Fixes a regression introduced in `0.12.13` where weren't checking if a user was logged in before trying to register the Workflow.
Fixes #2226
=> fix(core): register workflow only if user is logged in

core/src/cli/helpers.ts, core/src/cli/params.ts, core/src/commands/exec.ts, core/src/commands/helpers.ts, core/src/commands/run/module.ts, core/src/commands/test.ts, core/test/unit/src/cli/helpers.ts, core/test/unit/src/cli/params.ts, core/test/unit/src/commands/run/module.ts, core/test/unit/src/commands/test.ts, docs/reference/commands.md
This allows you to e.g. specify `--name` multiple times for the
`garden test` command, multiple `--hot` parameters for deploy commands
etc., instead of comma-separating on the same parameter.
=> improvement(cli): allow multiple instances of array option parameters

core/src/commands/deploy.ts, core/test/unit/src/commands/deploy.ts, docs/reference/commands.md
Simply allows skipping specific services when running `garden deploy`,
nice and simple.
=> feat(cli): add --skip parameter to deploy command

core/src/template-string.ts, core/test/unit/src/template-string.ts, docs/using-garden/variables-and-templating.md
The example from the docs:
```yaml
kind: Project
variables:
some-values: ["a", "b"]
other-values: ["c", "d"]
---
kind: Module
type: helm
values:
some-array: ${var.some-values + var.other-values}
...
```
=> feat(templates): allow concatenating arrays with + operator

core/src/plugins/kubernetes/config.ts, core/src/plugins/kubernetes/helm/config.ts, core/src/plugins/kubernetes/helm/run.ts, core/src/plugins/kubernetes/helm/test.ts, core/src/plugins/kubernetes/kubernetes-module/run.ts, core/src/plugins/kubernetes/kubernetes-module/test.ts, core/src/plugins/kubernetes/run.ts, core/src/plugins/kubernetes/util.ts, core/test/data/test-projects/helm/artifacts/templates/deployment.yaml, core/test/data/test-projects/helm/artifacts/values.yaml, core/test/integ/src/plugins/kubernetes/helm/common.ts, core/test/integ/src/plugins/kubernetes/run.ts, docs/reference/module-types/helm.md, docs/reference/module-types/kubernetes.md
For `helm` and `kubernetes` modules, we now use all pod spec fields from the service resource when running the task/test (excluding a fixed blacklist of pod spec fields).
This allows tasks/tests to e.g. use custom service accounts, node selectors etc.
Also refactored / broke up the `runAndCopy` function.
Fixes #2118.
**Special notes for reviewer**:
What do we think of the blacklist as it is here? Do we want to add/remove any fields?
=> feat(k8s): use pod spec fields in tasks and tests

.circleci/config.yml, core/src/constants.ts, core/src/garden.ts, core/test/unit/src/build-staging/build-staging.ts, core/test/unit/src/build-staging/rsync.ts
We now default to using the new rsync-less build staging mechanism,
which previously had to be explicitly enabled with the
GARDEN_EXPERIMENTAL_BUILD_STAGE environment variable.
In turn, you can now switch _back_ to the older rsync-based mechanism
by setting `GARDEN_LEGACY_BUILD_STAGE=true` in your environment, in
case any unexpected issues come up. Please reach out to us if that
does happen and we'll try and fix any issues promptly.
=> improvement(core): default to new build staging mechanism

core/src/template-string-parser.pegjs, core/test/unit/src/template-string.ts
Previously, we would immediately resolve an optional template string
as undefined during partial resolution, which would cause problems when
using optional template strings for variables that are only available
later in the process. We now leave them unchanged until the final
resolution occurs.
Fixes #2241
=> fix(config): pass optional templates through during partial resolution

.circleci/config.yml, core/src/plugins/kubernetes/api.ts, core/src/plugins/kubernetes/container/build.ts, core/src/plugins/kubernetes/init.ts, core/src/plugins/kubernetes/kubernetes.ts, core/src/plugins/kubernetes/util.ts, docs/guides/cloud-provider-setup.md, docs/guides/in-cluster-building.md, examples/gke/README.md, examples/gke/backend/.dockerignore, examples/gke/backend/.gitignore, examples/gke/backend/Dockerfile, examples/gke/backend/garden.yml, examples/gke/backend/main.go, examples/gke/frontend/.dockerignore, examples/gke/frontend/Dockerfile, examples/gke/frontend/app.js, examples/gke/frontend/garden.yml, examples/gke/frontend/main.js, examples/gke/frontend/package.json, examples/gke/frontend/test/integ.js, examples/gke/garden.yml, images/docker-dind/Dockerfile, images/docker-dind/garden.yml, images/skopeo/Dockerfile, images/skopeo/garden.yml, static/kubernetes/system/docker-daemon/values.yaml, static/kubernetes/system/util/values.yaml
fix(k8s): issues with GCR auth when running in-cluster builds on GKE
This adds a new `gke` example project, with instructions on how to set
up GCR auth with Kaniko. The procedure is unfortunately a bit involved,
but it does follow the suggested best practice in the Kaniko docs:
https://github.com/GoogleContainerTools/kaniko#pushing-to-gcr-using-workload-identity
Once #2216 is merged, we should fold the relevant parts of the README in the new `gke` example project into the in-cluster building guide.
=> fix(k8s): issue with GCR auth when running in-cluster builds on GKE

core/src/commands/run/workflow.ts, core/src/config/workflow.ts, core/src/plugins/exec.ts, core/src/util/util.ts, core/test/unit/src/commands/run/workflow.ts, core/test/unit/src/config/workflow.ts, docs/reference/commands.md, docs/reference/workflow-config.md
Nice and simple, what it says on the tin. You can now specify (and thus template) environment variables for script steps.
=> feat(workflows): add envVars field for script steps

core/src/plugins/kubernetes/init.ts, examples/gke/README.md, examples/gke/garden.yml
Turns out automatically including the `credHelpers` entries for GCR
could cause conflicts if users already had token auth set up.
I've also gone with a different suggested approach for GCR auth with
Kaniko, that is both simpler to implement and will also work seamlessly
for `cluster-docker` and `cluster-buildkit`.
=> fix(k8s): fix potential GCR auth issue + simpler GKE+GCR instructions

core/src/config/config-context.ts, core/test/unit/src/config/config-context.ts, docs/reference/template-strings.md
In addition to the `local.username` template variable, we now provide `local.usernameLowerCase`.
This is useful e.g. when templating in the local username in namespaces or hostnames.
=> feat(core): lower case username for templates

core/src/plugins/kubernetes/helm/config.ts, core/src/plugins/kubernetes/helm/deployment.ts, core/src/plugins/openfaas/openfaas.ts, core/test/integ/src/plugins/kubernetes/commands/pull-image.ts, core/test/integ/src/plugins/kubernetes/helm/config.ts, docs/misc/faq.md, docs/reference/module-types/helm.md
This adds an `atomicInstall` option to `helm` modules. Set this to
`false` if you prefer Helm not to automatically roll back. This is
handy if you're trying to track down installation issues and want to
inspect deployed resources and statuses.
=> feat(helm): allow disabling atomic installs/upgrades

core/src/config/config-context.ts, core/src/config/module.ts, core/src/resolve-module.ts, core/src/template-string-parser.pegjs, core/src/template-string.ts, core/src/util/fs.ts, core/test/unit/src/garden.ts, core/test/unit/src/template-string.ts, docs/reference/commands.md, docs/reference/module-template-config.md, docs/reference/module-types/conftest.md, docs/reference/module-types/container.md, docs/reference/module-types/exec.md, docs/reference/module-types/hadolint.md, docs/reference/module-types/helm.md, docs/reference/module-types/kubernetes.md, docs/reference/module-types/maven-container.md, docs/reference/module-types/openfaas.md, docs/reference/module-types/persistentvolumeclaim.md, docs/reference/module-types/templated.md, docs/reference/module-types/terraform.md, docs/using-garden/module-templates.md
This addresses an issue where template strings couldn't easily be
escaped, such that Garden _wouldn't_ attempt to resolve them.
From the docs:
Sometimes you may want to pass template strings through when generating
files, instead of having Garden resolve them. This could for example be
handy when templating a Terraform configuration file which uses a
similar templating syntax.
To do this, simply add an additional `$` in front of the template
string, e.g. `$${var.dont-resolve-me}`.
=> feat(template): allow escaping template strings for generated files

core/src/actions.ts, core/src/commands/publish.ts, core/src/config/config-context.ts, core/src/plugins/container/helpers.ts, core/src/plugins/container/publish.ts, core/src/plugins/kubernetes/commands/pull-image.ts, core/src/plugins/kubernetes/container/publish.ts, core/src/tasks/publish.ts, core/src/types/plugin/module/publishModule.ts, core/src/types/plugin/plugin.ts, core/src/vcs/vcs.ts, core/test/data/test-projects/container/remote-registry-test/garden.yml, core/test/integ/src/plugins/kubernetes/container/build/build.ts, core/test/integ/src/plugins/kubernetes/container/container.ts, core/test/unit/src/commands/publish.ts, core/test/unit/src/plugins/container/container.ts, docs/guides/in-cluster-building.md, docs/reference/commands.md
It was time to give the publish command a bit of ❤️. Couple of commits:
**fix(k8s): garden publish command now works with any deploymentRegistry**
We had been making some assumptions that the in-cluster registry was
being used. We already had the code to pull images from other
registries, so this wasn't actually to hard to address. Also added
tests to validate.
**feat(publish): add template-able --tag parameter to publish command**
This should generally make the `garden publish` command a lot more
usable. You can now override the default tag at publish-time, and
even apply template strings on the tags.
From the updated in-cluster building docs:
-------
You can also set the `--tag` option on the `garden publish` command to override the tag used for images. You can both set a specific tag …
=> Publish command fixes/improvements

core/test/unit/src/watch.ts
The module names in the event payload here sometimes came out in a different order in CI. Sorting the array should resolve this.
See for example:
https://app.circleci.com/pipelines/github/garden-io/garden/8599/workflows/f81edeb2-f1b1-4547-95d1-482b2fa1f890/jobs/106375
=> chore(test): fix flaky watcher test

core/src/build-staging/helpers.ts
This is hard to repro and test, but was reported to come up on Windows
=> fix(build-stage): don't throw when setting utime on missing file

core/src/commands/tools.ts
This was getting in the way of automation.
=> fix(cli): don't print "Tools" header in tools command

core/src/plugins/kubernetes/container/build/buildkit.ts, core/test/integ/src/plugins/kubernetes/container/build/buildkit.ts, docs/guides/in-cluster-building.md
Requested by a user. Helps to push build deployments to separate nodes from applications.
=> feat(k8s): add garden-build toleration to garden-buildkit deployments

core/src/cli/params.ts, core/src/constants.ts, core/test/unit/src/cli/cli.ts
Nice and simple, we can now set `GARDEN_ENVIRONMENT` instead of the
`--env` option flag.
=> feat(cli): allow setting environment with GARDEN_ENVIRONMENT

cli/src/add-version-files.ts, core/src/actions.ts, core/src/cache.ts, core/src/commands/get/get-debug-info.ts, core/src/commands/migrate.ts, core/src/commands/scan.ts, core/src/garden.ts, core/src/util/fs.ts, core/src/vcs/git.ts, core/src/vcs/vcs.ts, core/test/unit/src/util/fs.ts, core/test/unit/src/vcs/git.ts, core/test/unit/src/vcs/vcs.ts, support/azure.Dockerfile
This is a collection of fixes/improvements to make the file scanning during initialization and module version resolution faster. It's gonna help more in some cases than others, the key problems we're addressing are inefficiencies with large monorepos and many modules in the same directories.
cc @SGudbrandsson @Chipcius
**For the reviewer:**
Please give it a spin, see if you notice an improvement (or the opposite of course).
=> File scan improvements

scripts/release.ts
Not sure when TypeScript started flagging this (resolving a promise without a value), but I ran into this while making a release.
A simple fix.
=> chore: fix release script

core/src/plugins/kubernetes/run.ts, core/src/plugins/kubernetes/status/pod.ts
Test/task Pods would often hang with injected sidecars prior to this change, except for Istio (which we had a special provision for). This should solve that more generically.
=> fix(k8s): handle injected service mesh containers for tests+tasks

core/test/data/test-projects/build-dir/symlink-absolute/symlink.txt
Symlinking to /tmp was a Bad Idea™. Took me a while to figure out why
things suddenly were going haywire.
=> chore: fix symlink that would break VSCode file watching

support/alpine.Dockerfile, support/buster.Dockerfile
The flag was only intended for the build flow, not the actual runtime
environment for Garden in the container.
=> chore: re-enable analytics in container images

core/package.json, core/src/plugins/kubernetes/api.ts, yarn.lock
This should both be a strong performance improvement when connecting to clusters by hostname (as opposed to IP, which some cloud providers do), and eliminate potential overloads on the OS-level DNS lookups.
=> improvement(k8s): cache DNS lookups for cluster hostnames

core/src/commands/delete.ts, core/test/unit/src/cli/helpers.ts, core/test/unit/src/commands/delete.ts, docs/reference/commands.md
Basically this makes it easy to delete all services in a namespace.
Sort of a silly omission to begin with.
=> improvement(cli): allow `garden delete services` with no arguments

core/src/resolve-module.ts
This is a little bit of a shot in the dark, looking to solve an issue reported on Slack (https://kubernetes.slack.com/archives/CKM7CP8P9/p1614599864049600), but it's in any case a sane thing to do. Basically we now ensure that a new tree scan is performed after manipulating files in a particular module path.
=> fix(core): potential edge-case issue with versions and generateFiles

.github/workflows/npm-release.yml
This PR fixes the double version bump which was happening in the previous version of the script.
Furthemore we now tag the pre-releases with the `edge` tag and so we can better manage dependencies on the consumer side. 
Fixes #
=> ci(core): fix unnecessary version bump when releasing npm package

.github/workflows/npm-release.yml
In the previous refactor I messed up the authentication line therefore the script was trying to publish without a valid access token in the `.npmrc` file. Furthermore I also realized we were trying to fetch the current version from the `package.json` before the checkout step. 🤭 
Fixes #
=> ci(core): missing authentication when publishing npm core package

core/src/plugins/container/config.ts, core/src/plugins/kubernetes/container/deployment.ts, core/test/integ/src/plugins/kubernetes/container/deployment.ts, docs/reference/module-types/container.md, docs/reference/module-types/maven-container.md
When using the Kubernetes provider, the annotations set on
`services[].annotations` in container modules are now applied to both
Service and Pod resources. You can generally specify the annotations
intended for both Pods or Services here, and the ones that don't apply
on either side will be ignored (i.e. if you put a Service annotation
here, it'll also appear on Pod specs but will be safely ignored there,
and vice versa).
=> feat(k8s): apply container service annotations to Pod templates as well

core/package.json, core/src/cli/params.ts, core/src/commands/commands.ts, core/src/commands/enterprise/enterprise.ts, core/src/commands/enterprise/groups/groups.ts, core/src/commands/enterprise/helpers.ts, core/src/commands/enterprise/secrets/secrets-create.ts, core/src/commands/enterprise/secrets/secrets-delete.ts, core/src/commands/enterprise/secrets/secrets-list.ts, core/src/commands/enterprise/secrets/secrets.ts, core/src/commands/enterprise/users/users-create.ts, core/src/commands/enterprise/users/users-delete.ts, core/src/commands/enterprise/users/users-list.ts, core/src/commands/enterprise/users/users.ts, core/src/enterprise/api.ts, core/src/enterprise/get-secrets.ts, core/src/enterprise/workflow-lifecycle.ts, docs/reference/commands.md, yarn.lock
This PR contains a handful of experimental utility commands to manage
enterprise resources such as users and secrets. This is flagged as
experimental for now, since it requires GE 1.13.1 or higher and probably
some more iteration from our end. But the core functionality is all
there.
Here's the secret command in action:
The users and groups command work much the same.
Todo:
Fixes #
=> feat(enterprise): add utility commands to manage enterprise resources

core/src/constants.ts, core/src/garden.ts
This temporarily mitigates #2299 by reverting back to using rsync for
build staging on Windows, while we work out why exactly it fails for
some users/projects.
Users can still opt into the newer rsync-less mode by setting
`GARDEN_EXPERIMENTAL_BUILD_STAGE=true` in their shell environment.
=> fix(core): default back to rsync build staging on Windows

core/src/actions.ts, core/src/config/template-contexts/module.ts, core/src/garden.ts, core/src/outputs.ts, core/src/resolve-module.ts, core/src/tasks/publish.ts, core/test/unit/src/config/template-contexts/module.ts, docs/reference/module-types/conftest.md, docs/reference/module-types/container.md, docs/reference/module-types/exec.md, docs/reference/module-types/hadolint.md, docs/reference/module-types/helm.md, docs/reference/module-types/kubernetes.md, docs/reference/module-types/maven-container.md, docs/reference/module-types/openfaas.md, docs/reference/module-types/persistentvolumeclaim.md, docs/reference/module-types/templated.md, docs/reference/module-types/terraform.md, docs/reference/template-strings.md
This adds `${this.name}`, `${this.buildPath}` and `${this.path}` to the
template context when resolving modules.
Because someone might ask, `${this.version}` is not included because the
module version is determined after resolving the configuration.
I'm adding this both as a convenience and as a part of a different
project, where I'll add further keys to the `this.*` context.
=> feat(config): add `this` context when resolving modules

support/aws-gcloud-azure.Dockerfile
This PR add the kubelogin tool to the aws-gcloud-azure image. Kubelogin can be used to authenticate with Azure AD to AKS clusters.
Fixes #
=> chore(workflow-runner): add kubelogin to workflow runner image

core/src/plugins/kubernetes/container/deployment.ts, core/test/data/test-projects/container/hot-reload/Dockerfile, core/test/data/test-projects/container/hot-reload/garden.yml, core/test/integ/src/plugins/kubernetes/container/deployment.ts
During a hot reload event, a pod might not respond to liveness probes, e.g. because the server is restarting. This causes issues where K8s terminates the pod mid restart and the process needs start from the scratch. This PR fixes that be increasing the liveness probes on manifests for the container module type when in hot reload mode. 
The values are what we've seen work for GE but happy to receive other suggestions.
Fixes #
=> improvement(core): increase liveness probes when in hot-reload mode

core/src/plugins/exec.ts
Before this, you'd see`(commandResult.stdout + commandResult.stderr).trim is not a function` in the command output if the command fails, when running a local exec module in interactive mode .
Fixes #
=> fix(core): handle undefined stdout/stderr on exec module failures

docs/reference/module-types/container.md
=> Fixing typo for ingress annotations in container module docs

docs/reference/module-types/container.md
This reverts commit ad6548ffdfd4ba113dcc5f71481f130981e38300.
Fixes #
=> Revert "Fixing typo for ingress annotations in container module docs"

core/src/commands/run/workflow.ts, core/src/commands/validate.ts, core/src/garden.ts, core/test/data/validate/bad-workflow/garden.yml, core/test/unit/src/commands/run/workflow.ts, core/test/unit/src/commands/validate.ts, core/test/unit/src/garden.ts
In the `run workflow` command, we now only resolve the workflow config being run.
This adds flexibility when some workflows reference e.g. secrets that are created by other workflows.
=> feat(workflows): only resolve config being run

core/package.json, yarn.lock
Ensure we're on the latest version of the K8s client since we've been bumping into some issues regarding auth tokens not refreshing. I actually doubt that this will fix the issue, I don't see anything in the commit history for the K8s client that suggests that, but want to make sure we're on the latest version regardless to eliminate that case while debugging.
Fixes #
=> chore: update k8s client lib

core/src/commands/test.ts, core/test/unit/src/commands/test.ts, docs/reference/commands.md
The current behavior of the test command when called with a list of module names is to run all tests in those modules, and all tests in modules with dependencies on those modules.
This is not the desired behavior in all cases, so here we add a `--skip-dependants` option to the test command. When used, only tests in the requested modules will be run.
=> feat(commands): skip-dependants opt for test cmd

core/src/proxy.ts
Fixes #2370
Basically this happens when the server is already closed. So we just swallow the error, can't think of any legit error that would come about there.
=> fix(core): catch EPIPE error when closing port proxies

core/src/plugins/kubernetes/commands/pull-image.ts, core/src/plugins/kubernetes/constants.ts, images/k8s-util/Dockerfile, images/k8s-util/garden.yml
Hunting down a sporadic issue, reported by a customer. Timeouts extended and made more consistent, memory request set for the image pull pod, and updating Skopeo along the way to rule out any fixed upstream issues.
=> fix(k8s): timeout/OOM error when pulling large image to local docker

core/src/plugins/kubernetes/api.ts
We now automatically retry failed Kubernetes API requests if the reason for the failure matches certain conditions.
For example, timeouts or DNS-related errors will result in retries, but not 404/not found errors (and so forth), which will be thrown without retrying.
We can easily add more error codes and/or conditions to this logic if we discover further error cases that should result in retries.
Fixes #2255.
Should also fix the sporadic API timeouts that some users have been encountering in day-to-day usage.
Do we want to include any more status codes and/or error messages in the `shouldRetry` helper? Are there other kinds of conditions for which we want to retry?
Also, feel …
=> fix(k8s): automatic retry for failed API requests

core/src/plugins/exec.ts
A user from our community pointed out that test and task logs were missing from the `exec` module. We now log them when log level is set to verbose or higher.
Fixes #
=> improvement(exec): show test and task logs when log level is verbose

core/src/commands/logout.ts, core/src/enterprise/api.ts, core/src/enterprise/buffered-event-stream.ts, core/src/enterprise/workflow-lifecycle.ts, core/src/plugins/kubernetes/api.ts, core/src/plugins/kubernetes/container/util.ts, core/src/util/http.ts
We now retry the `POST` requests made by `BufferedEventStream` if the request fails with a network- or timeout-related status code.
This should make log & event streaming more robust to unstable network conditions or during periods of high load.
Also added a few more status codes to the retry logic for the k8s API.
=> fix(cloud): retry streaming on network error

core/src/actions.ts, core/src/config/template-contexts/module.ts, core/src/garden.ts, core/src/plugin-context.ts, core/src/plugins/kubernetes/hot-reload/hot-reload.ts, core/src/plugins/kubernetes/kubernetes-module/common.ts, core/src/plugins/kubernetes/kubernetes-module/config.ts, core/src/plugins/kubernetes/kubernetes-module/handlers.ts, core/src/plugins/kubernetes/kubernetes-module/run.ts, core/src/plugins/kubernetes/kubernetes-module/test.ts, core/src/types/plugin/module/getBuildStatus.ts, core/src/types/service.ts, core/test/integ/src/plugins/kubernetes/kubernetes-module/handlers.ts, core/test/unit/src/actions.ts, core/test/unit/src/commands/deploy.ts, docs/reference/module-types/conftest.md, docs/reference/module-types/container.md, docs/reference/module-types/exec.md, docs/reference/module-types/hadolint.md, docs/reference/module-types/helm.md, docs/reference/module-types/kubernetes.md, docs/reference/module-types/maven-container.md, docs/reference/module-types/openfaas.md, docs/reference/module-types/persistentvolumeclaim.md, docs/reference/module-types/templated.md, docs/reference/module-types/terraform.md, docs/reference/template-strings.md, examples/kubernetes-module/garden.yml, examples/kubernetes-module/redis/redis.yml
Previously, you could only use template strings when inlining
manifests using the `manifests` field. Now, template strings are also
resolved in the files referenced in the `files` key.
Internally, we now make a `ctx.resolveTemplateStrings()` for all
plugin handlers, so this will be easy to do in other scenarios as well.
Also added a commit to allow referencing service or task versions via e.g.
`${runtime.services.my-service.version}` or
`${runtime.tasks.my-task.version}`.
=> feat(k8s): resolve template strings in kubernetes module manifest files 

core/src/plugins/container/config.ts, core/src/plugins/google/google-cloud-functions.ts, core/src/plugins/kubernetes/container/deployment.ts, core/src/plugins/kubernetes/container/run.ts, core/src/plugins/kubernetes/container/test.ts, core/src/plugins/kubernetes/container/util.ts, core/src/plugins/kubernetes/run.ts, core/src/plugins/local/local-google-cloud-functions.ts, core/test/integ/src/plugins/kubernetes/container/deployment.ts, core/test/integ/src/plugins/kubernetes/run.ts, core/test/unit/src/commands/get/get-config.ts, core/test/unit/src/commands/run/workflow.ts, core/test/unit/src/garden.ts, core/test/unit/src/plugins/container/container.ts, core/test/unit/src/plugins/kubernetes/container/ingress.ts, core/test/unit/src/vcs/vcs.ts, docs/reference/module-types/container.md, docs/reference/module-types/maven-container.md
Resource requests and limits can now be set for `container` services, tasks and tests via the new `cpu` and `memory` fields.
The `service.limits` field has now been deprecated, and should be removed in a future breaking release. Values set in `service.limits` are still applied when deploying `container` services, and take precedence over the max values set in the `cpu` and `memory` fields.
Closes #2317 and #2309.
=> feat(container): custom min/max resources

core/src/cli/cli.ts, core/src/cli/helpers.ts, core/src/config/template-contexts/project.ts, core/test/unit/src/cli/helpers.ts, docs/reference/template-strings.md
The values of a CLI option can now be looked up by alias in template strings.
For example, `${command.params contains 'dev-mode'}` and `${command.params contains 'dev'}` will now both work (previously, only the `dev-mode` key would have the option values populated).
Fixes #2397.
=> feat(core): allow opt aliases in ${command.params}

core/src/plugins/container/config.ts, core/src/plugins/kubernetes/dev-mode.ts
Adds additional option for `devMode.sync.mode` `one-way-replica` that maps to same sync mode in `mutagen`.
The rationale is that for cases where `garden dev` is used to sync source code from developer's machine to remote container, the files are not always overwritten with `one-way` mode.
The reason is that `one-way` mode in `garden` maps to `one-way-safe` mode for `mutagen`, which by design does not overwrite files where the original contents of the file on one end does not match contents on the other end. This behavior is documented in [Modes](https://mutagen.io/documentation/synchronization#modes) section of `mutagen` documentation.
I was hesitant between having `one-way` default to `one-way-replica` as I think the `one-way-safe` mode is less …
=> feat: add one-way-replica as additional devMode.sync.mode

cli/package.json, cli/patches/pkg+4.5.1.patch, cli/src/build-pkg.ts, core/src/util/util.ts, support/alpine-builder.Dockerfile, yarn.lock
This works around https://github.com/vercel/pkg/issues/897 by patching
the `pkg` `prelude/bootstrap.js` script.
Fixes #2032
=> fix(workflows): error when running `garden` in a workflow script step

core/src/plugins/kubernetes/kubernetes-module/handlers.ts
This could cause issues when using other modules to render manifests.
=> fix(k8s): remove unnecessary build step for kubernetes modules

core/src/plugins/container/config.ts, core/src/plugins/kubernetes/container/status.ts, core/src/proxy.ts, core/src/types/service.ts, docs/reference/commands.md, docs/reference/module-types/container.md, docs/reference/module-types/maven-container.md
This adds a `localPort` field to the `services[].ports` field, to make
it easier to control the local port used for port forwards. This is
handy for a variety of reasons, one of which is to have a predictable
port for debuggers.
=> feat(container): allow specifying preferred local port for port-forwards

core/src/tasks/build.ts, core/src/tasks/stage-build.ts
Specifically, raised the level for "Syncing module sources..." and
added a touch more clarity when a module is found to be already built.
=> improvement(core): tweak log output during builds

core/src/config/module-template.ts, core/src/config/project.ts, core/src/config/template-contexts/base.ts, core/src/config/template-contexts/project.ts, core/src/config/template-contexts/workflow.ts, core/src/enterprise/api.ts, core/src/enterprise/get-secrets.ts, core/src/enterprise/workflow-lifecycle.ts, core/src/garden.ts, core/test/unit/src/config/project.ts, core/test/unit/src/config/template-contexts/project.ts, core/test/unit/src/enterprise/api.ts, core/test/unit/src/garden.ts
We now log more informative error messages when a missing secret is referenced, and when trying to fetch secrets for an environment that doesn't exist on the backend.
We also don't throw errors when fetching secrets for an environment that doesn't exist (but we do log additional information around this at the `debug` log level).
In addition to better handling of secret-related errors, this PR improves on the following:
* We now throw an error when a null client auth token / jwt is received from the backend during login. Previously, we were only logging an error, without indicating that the command had failed. The error message was also a bit cryptic.
* When workflow run registration fails due to CLI/backend API incompatibility (i.e. if the shape of …
=> improvement(cloud): better secrets/API errors

core/src/vcs/git.ts
In a recent minor version update of Git, either the `--cache` or the `--other` flag has to be passed when using the `--ignore` flag.
The `--cache` flag (on by default) is now explicitly passed in the relevant calls to `git ls-files`.
Fixes #2426.
=> fix(core): support git 2.32.0

core/src/commands/base.ts, core/src/config/workflow.ts, core/src/plugins/kubernetes/config.ts, core/src/plugins/kubernetes/helm/config.ts, core/src/plugins/kubernetes/run.ts, core/test/integ/src/plugins/kubernetes/run.ts
We now no longer include liveness or readiness probes on the pod spec used when running e.g. tests or tasks for `kubernetes` or `helm` modules.
In certain situations, these probes could result in test pods being evicted before the test suite was able to finish. This is fixed here.
=> fix(k8s): omit probes in runner pod spec

core/src/plugins/kubernetes/container/build/buildkit.ts, core/src/plugins/kubernetes/container/build/kaniko.ts
Turns out we were only tapping stdout when streaming logs directly from buildkit+kaniko builds.
=> fix(k8s): missing stderr in verbose buildkit+kaniko build logs

core/src/plugins/exec.ts
Output logs were missing from exec deploy.
Fixes #2457 
=> fix(core): log outputs from exec service deploy at verbose level

docs/misc/troubleshooting.md
=> docs: add troubleshooting section on Azure auth

docs/guides/local-kubernetes.md
I had a bad time using `kind` in both Linux (Ubuntu 20.04) and OSX (Big Sur 11.1).
Checked both garden and kind docs and I saw the `authorization-mode: "AlwaysAllow"` is [no longer shown in kind docs](https://kind.sigs.k8s.io/docs/user/ingress/#create-cluster).
I tried removing the line and `kind` worked just fine and garden was happy with it.
I didn't create an issue for this, sorry.
Fixes #
=> docs: Update kind create cluster snippet

core/src/config/project.ts, core/src/config/template-contexts/project.ts, core/src/config/template-contexts/workflow.ts, core/src/docs/template-strings.ts, core/src/garden.ts, core/test/unit/src/config/project.ts, core/test/unit/src/garden.ts, docs/reference/template-strings.md, static/docs/templates/template-strings.hbs
Template strings in remote sources now have access to the same variables as provider configs.
This adds flexibility when using remote sources in conjunction with automation (e.g. when using dynamic Git branches / tags for remote sources, depending on project- and environment-level variables).
Fixes #2436.
Previously, referencing `${var.*}` in remote sources would result in a template string error, since remote sources were being resolved at the same time as the top-level project config (which is before project- and environment-level variables are resolved).
We now only resolve template strings in remote sources on demand, when `getProjectSources` are called. Is this a good …
=> feat(core): allow variables in remote sources

core/src/plugins/kubernetes/container/build/kaniko.ts
Previously, we were applying a `NoSchedule` toleration to the `garden-util` pod, but not the actual builder pods. This is fixed here.
Fixes #2464.
=> fix(k8s): apply toleration to kaniko build pods

core/src/plugins/kubernetes/volumes/persistentvolumeclaim.ts
Previously, `persistentvolumeclaim` modules wouldn't work when used with the `dev` command, because the `devMode: true` flag was being passed to the `getServiceStatus` and `deployService` handlers.
We now ensure that dev-mode-related changes to the generated manifests are not applied for PVC modules.
Fixes #2369.
=> fix(core): don't apply dev mode to PVC modules

core/src/actions.ts, core/src/events.ts, core/src/types/plugin/base.ts, core/src/types/plugin/module/build.ts, core/test/unit/src/actions.ts, core/test/unit/src/commands/deploy.ts
We now stream build status events, similarly to how we've been streaming service, test and task status events.
We've also added a `running` state to the `RunState` type, and we include a `building` state in the new `BuildState` type to represent builds/tests/tasks that are in progress.
Additionally, we now emit a `serviceStatus` event with the `deploying` state in the `deployService` action just before the deploy handler is called.
=> feat(core): stream build statuses

core/src/plugins/kubernetes/container/build/buildkit.ts
Adds a tag to the buildkit output so that it is pushing to latest.
Buildkit doesn't actually cache anything because the import-cache is looking for an untagged image (ie. latest) but all the builds are going to the garden module versions.
Fixes #
=> Fix: resolve issue with build kit not caching

core/src/plugins/kubernetes/port-forward.ts, core/src/plugins/kubernetes/util.ts, core/test/unit/src/plugins/kubernetes/port-forward.ts, core/test/unit/src/plugins/kubernetes/util.ts
Previously we only created port forwards for Service resources. We
still prefer those when applicable but also create port forwards
directly to Deployment and DaemonSet container ports.
=> feat(k8s): port-forward to Deployments and DaemonSets

core/src/config/common.ts, core/src/config/project.ts, core/src/config/workflow.ts, core/src/docs/config.ts, core/src/plugins/container/config.ts, core/src/plugins/kubernetes/config.ts, core/src/plugins/kubernetes/kubernetes.ts, core/test/unit/src/plugins/kubernetes/kubernetes.ts, docs/guides/in-cluster-building.md, docs/reference/module-types/container.md, docs/reference/module-types/maven-container.md, docs/reference/project-config.md, docs/reference/providers/kubernetes.md, docs/reference/providers/local-kubernetes.md, docs/reference/workflow-config.md, static/docs/templates/config-partial.hbs
It's time. We now show a warning when still using the cluster-docker build mode, and docs/references reflect the deprecated feature status.
=> refactor(k8s): officially deprecate the cluster-docker build mode

core/src/plugins/kubernetes/api.ts, core/src/plugins/kubernetes/commands/cleanup-cluster-registry.ts, core/src/plugins/kubernetes/container/build/buildkit.ts, core/src/plugins/kubernetes/container/build/cluster-docker.ts, core/src/plugins/kubernetes/container/build/common.ts, core/src/plugins/kubernetes/status/pod.ts, core/src/plugins/kubernetes/status/service.ts, core/src/plugins/kubernetes/util.ts
I spotted a little Kubernetes delight, where k8s sometimes reports pods
as "Running" even though they are in fact Terminated. We'd fixed that
check elsewhere but had left an older check in one place. This should
get rid of that problem.
Also fixed an issue related to the WebSocket wrapper, where connection
interruptions could unnecessarily throw an error.
=> fix(k8s): intermittent errors when building/syncing to cluster 

core/src/template-string/functions.ts
Fixes `joi` validation for `replacement` argument of `replace` helper function to allow empty strings.
Fixes #2493 
=> fix(core): allow empty replacement strings in 'replace' helper function

support/azure.Dockerfile
Adds the correct items needed for this Docker image to run on Azure DevOps
Fixes #2502 
@edvald I checked the code I copied from Stack Overflow, it was in fact all needed -  I purposely chose to add the extra bits for Azure DevOps in a second run command so that it creates a separate layer for reuse in other images as necessary. I'm pretty sure this can all be collapsed in to a single run command if you prefer.
The Endpoint and label are both required by Azure DevOps for the image to run.
I've deployed this image to our internal registry and updated our CI/CD pipeline to use it.
=> chore: Update azure.Docker file to work with Azure DevOps Pipelines

core/src/commands/deploy.ts, core/test/unit/src/commands/deploy.ts
Simple omission, we forgot to check the dev flag when checking if the
method would be persistent (and should thus start proxies).
Fixes #2497
=> fix(core): deploy command wouldn't start port forwards with dev flag

core/src/plugins/kubernetes/volumes/persistentvolumeclaim.ts
=> fix(k8s): persistentvolumeclaim modules would include unnecessary files

core/src/plugins/kubernetes/helm/deployment.ts, core/src/plugins/kubernetes/helm/exec.ts, core/src/plugins/kubernetes/helm/run.ts, core/src/plugins/kubernetes/helm/status.ts, core/src/plugins/kubernetes/helm/test.ts, core/src/plugins/kubernetes/hot-reload/hot-reload.ts, core/src/plugins/kubernetes/kubernetes-module/exec.ts, core/src/plugins/kubernetes/kubernetes-module/handlers.ts, core/src/plugins/kubernetes/kubernetes-module/run.ts, core/src/plugins/kubernetes/kubernetes-module/test.ts, core/src/plugins/kubernetes/util.ts, core/test/integ/src/plugins/kubernetes/hot-reload.ts, core/test/integ/src/plugins/kubernetes/run.ts, core/test/integ/src/plugins/kubernetes/util.ts
Specifically, modules without a serviceResource declaration. This is
an error introduced alongside the new dev mode.
There was a prior fix but it turns out it wasn't quite enough.
=> fix(k8s): error when using dev mode on certain kubernetes modules

.circleci/config.yml, core/src/plugins/kubernetes/api.ts, core/src/plugins/kubernetes/config.ts, core/src/plugins/kubernetes/container/ingress.ts, core/src/plugins/kubernetes/kubernetes-module/common.ts, core/src/util/util.ts, core/test/integ/src/plugins/kubernetes/container/ingress.ts, core/test/integ/src/plugins/kubernetes/namespace.ts, core/test/unit/src/plugins/kubernetes/init.ts, core/test/unit/src/plugins/kubernetes/kubernetes.ts
We now auto-detect the most up-to-date supported Ingress API version
and create resources accordingly.
=> fix(k8s): correctly handle Ingress API versions for container modules

.circleci/config.yml, core/src/plugins/kubernetes/container/deployment.ts, core/src/plugins/kubernetes/container/status.ts, core/src/plugins/kubernetes/helm/deployment.ts, core/src/plugins/kubernetes/kubernetes-module/config.ts, core/src/plugins/kubernetes/kubernetes-module/handlers.ts, core/src/plugins/kubernetes/run.ts, core/src/plugins/kubernetes/status/status.ts, core/src/plugins/openfaas/openfaas.ts, core/test/integ/src/plugins/kubernetes/api.ts, core/test/integ/src/plugins/kubernetes/kubernetes-module/config.ts, docs/reference/module-types/kubernetes.md
The default deployment timeout of 300 seconds could be too short,
best to let users configure that themselves if needed.
=> feat(k8s): add timeout parameter to kubernetes module type

core/src/watch.ts
This seems like a reasonable buffer and appears to fix a handful of
issues where Garden throws while in watch mode because different git
commands fail, usually because the file system is changing while the git
command is being run.
Obviously this doesn't really fix the underlying issue and we should also look into also retrying git command on enoent errors. Flagging this PR as draft until we get to that. 
Fixes #2430 
=> fix(core): bump file watcher DEFAULT_BUFFER_INTERVAL to 1250

core/src/plugins/exec.ts, core/src/util/ext-tools.ts, core/src/util/util.ts
For some reason this never happens during our own testing, but some users have reported this. Should be simple as this.
=> fix(cli): avoid cmd.exe windows popping up during execution

core/src/actions.ts, core/src/build-staging/build-staging.ts, core/src/commands/build.ts, core/src/tasks/deploy.ts, core/src/tasks/helpers.ts, core/test/unit/src/tasks/helpers.ts
Couple of issues fixed here:
**improvement(core): don't explicitly create build tasks in dev command**
There's really no reason to run builds explicitly when running
`garden dev`. Users generally won't expect generally unnecessary builds
to happen as they edit code. Builds should happen only if they are
required by deployments, tests and tasks.
**fix(core): don't omit dev mode services from deployment dependencies**
This was done a little carelessly (by me). There's a different behavior for
dev mode, compared to hot reload, in that we don't expressly signal
whether a service supports dev mode. So when running the dev command
or `deploy --dev=*` this would in effect completely mess up the
dependency order of actions.
=> Fix dev command issues

package.json
It was just getting in the way, really.
=> chore: don't run npm test in pre-push hook

core/src/util/fs.ts, core/src/vcs/git.ts, core/test/unit/src/vcs/git.ts
Fixes #2430
Also adds more specific and helpful error messages when we encounter
missing/invalid submodule paths.
=> fix(core): warn instead of error when attempting to scan non-directory

core/src/commands/dev.ts
This for example was an issue with the default macOS terminal, but
others like iTerm 2 on Mac is fine (and please use that btw!), as well
as the Windows terminal and most Linux ones by now.
=> fix(cli): don't print dev cmd banner when terminal doesn't support it

core/src/plugins/kubernetes/config.ts, core/src/plugins/kubernetes/container/build/kaniko.ts, docs/reference/providers/kubernetes.md, docs/reference/providers/local-kubernetes.md
Allows specifying additional tolerations that get passed to kaniko pods (both util and the builder pods).
A nice to have if stuff is run on, say, AKS - where any spot instance automatically has a taint that you need to tolerate in order to run anything.
=> feat: allow passing additional tolerations to kaniko pods

static/kubernetes/system/ingress-controller/garden.yml
It's more annoying than useful in the context, has caused user
confusion.
=> improve(k8s): disable validation hooks on default nginx installation

docs/guides/in-cluster-building.md
Adds a note in the docs about setting image tag mutability to mutable, when using ECR with kaniko.
Fixes #
=> docs: mention image tag mutability when using kaniko with ECR

core/src/docs/module-type.ts, core/src/plugins/kubernetes/container/deployment.ts, core/src/plugins/kubernetes/kubernetes.ts, core/src/plugins/kubernetes/volumes/configmap.ts, core/test/data/test-projects/container/configmap-reference/garden.yml, core/test/integ/src/plugins/kubernetes/container/deployment.ts, core/test/integ/src/plugins/kubernetes/volume/configmap.ts, docs/README.md, docs/guides/container-modules.md, docs/reference/module-types/README.md, docs/reference/module-types/configmap.md
This facilitates mounting ConfigMap resources as volumes in container
modules.
Closes #2456 
The added docs:
---
Very similar to the above example, you can also mount ConfigMaps on
Kubernetes using the
[`configmap` module type](../reference/module-types/configmap.md),
supported by the `kubernetes` provider. Here's a simple example:
Example:
```yaml
kind: Module
name: my-configmap
type: configmap
data:
config.properties: |
some: data
or: something
---
kind: Module
name: my-module
services:
- name: my-service
volumes:
- name: my-configmap
module: my-configmap
containerPath: /config
...
```
This mounts all the keys in the `data` field on the `my-configmap`
module under the `/config` directory in the container. In this case,
you'll find the file `/config/config.properties` …
=> feat(k8s): add `configmap` module type, mountable on container modules

core/src/plugins/kubernetes/api.ts, core/src/plugins/kubernetes/config.ts, core/src/plugins/kubernetes/dev-mode.ts, core/src/plugins/kubernetes/helm/config.ts, core/src/plugins/kubernetes/helm/deployment.ts, core/src/plugins/kubernetes/helm/exec.ts, core/src/plugins/kubernetes/helm/run.ts, core/src/plugins/kubernetes/helm/status.ts, core/src/plugins/kubernetes/helm/test.ts, core/src/plugins/kubernetes/hot-reload/helpers.ts, core/src/plugins/kubernetes/hot-reload/hot-reload.ts, core/src/plugins/kubernetes/kubernetes-module/config.ts, core/src/plugins/kubernetes/kubernetes-module/exec.ts, core/src/plugins/kubernetes/kubernetes-module/handlers.ts, core/src/plugins/kubernetes/kubernetes-module/run.ts, core/src/plugins/kubernetes/kubernetes-module/test.ts, core/src/plugins/kubernetes/run.ts, core/src/plugins/kubernetes/types.ts, core/src/plugins/kubernetes/util.ts, core/test/integ/src/plugins/kubernetes/container/build/buildkit.ts, core/test/integ/src/plugins/kubernetes/hot-reload.ts, core/test/integ/src/plugins/kubernetes/run.ts, core/test/integ/src/plugins/kubernetes/util.ts, core/test/unit/src/plugins/kubernetes/hot-reload.ts, core/test/unit/src/plugins/kubernetes/util.ts, docs/reference/module-types/helm.md, docs/reference/module-types/kubernetes.md, examples/vote-helm/vote-image/package.json
Previously you could only reference workload resources contained in the
module/chart when choosing which resource to sync to or to use as base
for test/task Pod specs. Now you can reference any Pod by a label
selector, which provides a good deal of flexibility.
=> feat(k8s): allow setting podSelector on helm/kubernetes resource refs

core/src/plugins/kubernetes/run.ts, core/test/data/test-projects/container/simple/garden.yml, core/test/integ/src/plugins/kubernetes/run.ts, examples/vote/api/test.py
Fixes #1777
Also makes the copying process more efficient by putting it all in one
copy command, and also compressing the files (which we clumsily
neglected to do previously).
=> fix(k8s): bad handling of directory paths for artifact sources

core/package.json, core/src/plugins/kubernetes/config.ts, core/src/plugins/kubernetes/helm/config.ts, core/src/plugins/kubernetes/helm/deployment.ts, core/src/plugins/kubernetes/helm/status.ts, core/src/plugins/kubernetes/kubernetes-module/config.ts, core/src/plugins/kubernetes/kubernetes-module/handlers.ts, core/src/plugins/kubernetes/port-forward.ts, core/test/integ/src/plugins/kubernetes/container/build/build.ts, core/test/unit/src/plugins/kubernetes/port-forward.ts, docs/reference/module-types/helm.md, docs/reference/module-types/kubernetes.md
This allows users to explicitly configure the ports to forward for
kubernetes and helm modules, including which local port to forward to.
Example:
```yaml
kind: Module
type: kubernetes
...
portForwards:
- name: http
resource: Service/my-service
targetPort: 80
localPort: 8080
```
Closes #2504 
cc @ITHedgeHog
=> feat(k8s): manual port forward config for helm and kubernetes modules

core/src/plugins/kubernetes/mutagen.ts
Just a little Facepalm Fail™, discovered in pre-release testing (and
thus thankfully not affecting users atm).
=> fix(k8s): error fetching mutagen CLI on Windows

core/src/commands/deploy.ts, core/src/process.ts, core/test/unit/src/commands/deploy.ts, docs/reference/commands.md
This allows users to run the deploy command as a long lived, persistent
process with port forwards enabled without having Garden watch for
changes.
Fixes #
=> improvement(core): add --forward flag to deploy command

core/src/commands/deploy.ts, core/src/commands/dev.ts, core/src/commands/helpers.ts, core/src/garden.ts, core/src/process.ts, core/src/watch.ts, core/test/unit/src/commands/helpers.ts, core/test/unit/src/watch.ts
This is a performance optimization that lowers resource use when using dev mode. We now don't watch files inside the module roots of modules having one or more services deployed with dev mode, except for the modules' Garden config path.
The rationale here is that FS watches can be resource intensive, especially when there's a lot of churn (and especially on Linux). Since Mutagen takes care of the dev-mode sync (and doesn't go through the framework-native watch logic), this is usually unwanted overhead.
Also fixed a UI bug for watch-mode commands where an additional "Waiting for code changes..." footer log line would be rendered if a Garden config was changed.
This PR is an attempt to fix OOM issues that some of our …
=> improvement(core): don't watch dev-enabled modules

core/src/config/workflow.ts, docs/reference/commands.md, docs/reference/workflow-config.md
Adds the push event as a supported trigger event type.
=> feat(cloud): add trigger support for push events

core/src/commands/base.ts, core/src/commands/build.ts, core/src/commands/call.ts, core/src/commands/delete.ts, core/src/commands/deploy.ts, core/src/commands/dev.ts, core/src/commands/get/get-status.ts, core/src/commands/get/get-task-result.ts, core/src/commands/get/get-test-result.ts, core/src/commands/publish.ts, core/src/commands/run/task.ts, core/src/commands/run/test.ts, core/src/commands/run/workflow.ts, core/src/commands/test.ts
This fixes a regression introduced in `6382d3d` (emit stack graph & task log events), where we began emitting `stackGraph` events before running the workflow's steps.
This caused problems for workflows that rely on script steps to prepare authentication for providers (e.g. k8s credentials).
We now simply emit the `stackGraph` event from the relevant step commands.
=> fix(workflows): defer provider resolution

core/src/events.ts
The values for this field can sometimes be too large to be reliably streamed.
=> fix(core): omit `output.detail` from graph events

core/src/plugins/container/config.ts, core/src/plugins/kubernetes/config.ts, core/src/plugins/kubernetes/dev-mode.ts, core/src/plugins/kubernetes/mutagen.ts, core/test/data/test-projects/container/dev-mode/garden.yml, core/test/data/test-projects/container/garden.yml, core/test/integ/src/plugins/kubernetes/container/deployment.ts, core/test/integ/src/plugins/kubernetes/dev-mode.ts, core/test/unit/src/plugins/kubernetes/dev-mode.ts, docs/guides/code-synchronization-dev-mode.md, docs/reference/module-types/container.md, docs/reference/module-types/helm.md, docs/reference/module-types/jib-container.md, docs/reference/module-types/kubernetes.md, docs/reference/module-types/maven-container.md, docs/reference/providers/kubernetes.md, docs/reference/providers/local-kubernetes.md
Added `one-way-reverse` and `one-way-replica-reverse` sync modes for dev mode when using `container`, `kubernetes` and `helm` services.
This adds a great deal of flexibility and specificity when a full two-way sync is not desirable (especially since conflicts can happen with the `two-way-safe` Mutagen mode).
Also expanded the dev mode guide.
Excludes and permission/owner/group settings can now be set on the provider level for `kubernetes` and `local-kubernetes`.
Defaults specified there will be extended/overridden by corresponding settings on individual sync specs.
This helps reduce clutter when the same excludes and permission settings are commonly applied across services/modules.
=> feat(k8s): reverse sync and provider-level dev mode defaults

core/src/runtime-context.ts, core/test/unit/src/runtime-context.ts
This was causing unnecessary re-deployments of container modules.
We had previously flagged this as a breaking change, but on reflection
this behavior is undocumented and should not have been used for a long
while now, and it's causing meaningful user issues.
=> fix(core): don't add mutating env vars to runtime context

core/src/plugins/kubernetes/dev-mode.ts, core/src/plugins/kubernetes/mutagen.ts
We now log an informative warning message when mutagen sync conflicts are detected.
We've also started logging more sync-related log lines again to make it clear to the user when the sync has been established (and which pairs are being synced).
=> improvement(dev-mode): log sync conflicts

core/src/proxy.ts
Basically we were unnecessarily specifying 127.0.0.1 instead of
localhost, which meant we weren't exposing ports on ipv6.
=> improvement(port-forward): also bind to ::1 address by default

core/src/config/module.ts, core/src/resolve-module.ts, core/test/unit/src/config/module-template.ts, core/test/unit/src/garden.ts, docs/reference/commands.md, docs/reference/module-template-config.md, docs/reference/module-types/configmap.md, docs/reference/module-types/conftest.md, docs/reference/module-types/container.md, docs/reference/module-types/exec.md, docs/reference/module-types/hadolint.md, docs/reference/module-types/helm.md, docs/reference/module-types/jib-container.md, docs/reference/module-types/kubernetes.md, docs/reference/module-types/maven-container.md, docs/reference/module-types/openfaas.md, docs/reference/module-types/persistentvolumeclaim.md, docs/reference/module-types/templated.md, docs/reference/module-types/terraform.md
In many cases, it's not desirable to pass files specified under
`generateFiles[].sourcePath` through template resolution. This adds a
flag to control that behavior explicitly.
=> feat(config): allow skipping source template rendering in generateFiles

core/src/plugins/kubernetes/container/build/kaniko.ts, core/src/plugins/kubernetes/helm/run.ts, core/src/plugins/kubernetes/logs.ts, core/src/plugins/kubernetes/run.ts, core/test/integ/src/plugins/kubernetes/container/logs.ts, core/test/integ/src/plugins/kubernetes/run.ts
We now reuse the machinery from the new Kubernetes logs follower for gathering real-time log output from `runAndCopy` when run without artifacts.
This should ensure that all log lines are captured, and makes the log gathering process more robust when the connection to the pod fails and has to be reestablished.
When the connection has to be reestablished, we replay past log lines and deduplicate them against a fixed-size buffer of log entries for the pod + container in question to ensure that no lines are lost, while not emitting duplicate log lines.
=> improvement(cloud): more robust log streaming

core/src/cli/cli.ts, core/src/events.ts
We now emit session end events when the command exits.
=> feat(cloud): emit session events on exit

core/src/cli/cli.ts
Previously running `garden --help` and `garden -h` would exit with code
`0` but running `garden help` would exit with code `1`. This fixes that.
Fixes #
=> fix(cli): ensure help exits with code 0

docs/guides/code-synchronization-dev-mode.md
The devMode docs reference `one-way-replicated` as one of mutagen's synchronization methods, while the actual parameter is `one-way-replica` instead, using the formerresults in the following error:
```
...
key .services[0][devMode][sync][0][mode] must 
be one of [one-way, one-way-replica, one-way-reverse, one-way-replica-reverse, two-way], key .services[1][name]
```
This PR simply replaces all typos in the docs, no code changes required.
=> fixes docs mentioning one-way-replicated sync mode

core/src/proxy.ts
This should fix an error that some users have run into when using watch-mode commands when services are redeployed.
=> fix(k8s): fix port-forward error handling

core/src/plugins/kubernetes/config.ts
Before this fix, the `kind` field of a `serviceResource` could not be set/overridden when also providing a `podSelector` in a `serviceResource`.
Fixes the issue reported in #2635.
=> fix(k8s): validation fix in serviceResource schema

core/src/plugins/kubernetes/container/deployment.ts, core/test/integ/src/plugins/kubernetes/container/deployment.ts
The `privileged` config flag for `container` services wasn't resulting in the `allowPrivilegeEscalation` flag being set too. This is fixed here.
=> fix(container): propagate privileged flag

core/src/constants.ts, core/test/helpers.ts
Before this fix, setting ANALYTICS_DEV=false would be interpreted as
truthy because it was being evaluated as a string. Only the dev team
uses this so it was basically a none issue, but incorrect none the less.
Fixes #
=> chore: ensure ANALYTICS_DEV env var has the right type

core/src/cli/cli.ts
I found the log message slightly confusing and I think we should include the full environment name.
=> improve(cli): clearer message stating the namespace/environment name

core/src/plugins/container/config.ts, core/src/plugins/kubernetes/config.ts, core/src/plugins/kubernetes/container/deployment.ts, core/src/plugins/kubernetes/kubernetes-module/config.ts, core/test/unit/src/commands/get/get-config.ts, core/test/unit/src/garden.ts, core/test/unit/src/vcs/vcs.ts, docs/reference/module-types/container.md, docs/reference/module-types/jib-container.md, docs/reference/module-types/maven-container.md
This has been requested by a few users. The deployment timeout for `container` services can now be configured.
=> feat(k8s): add timeout to container services

.circleci/config.yml, core/src/plugins/kubernetes/api.ts, core/src/plugins/kubernetes/commands/cleanup-cluster-registry.ts, core/src/plugins/kubernetes/container/deployment.ts, core/src/plugins/kubernetes/container/ingress.ts, core/src/plugins/kubernetes/container/status.ts, core/src/plugins/kubernetes/helm/deployment.ts, core/src/plugins/kubernetes/integrations/cert-manager.ts, core/src/plugins/kubernetes/kubectl.ts, core/src/plugins/kubernetes/kubernetes-module/handlers.ts, core/src/types/plugin/tools.ts, core/test/data/test-projects/helm/api/templates/ingress.yaml, core/test/integ/src/plugins/kubernetes/container/deployment.ts, core/test/integ/src/plugins/kubernetes/container/ingress.ts, core/test/integ/src/plugins/kubernetes/helm/common.ts
This fixes an issue when using newer versions of `kubectl` with older cluster versions.
When `kubectl apply --prune` is used against a cluster with different API versions of certain resources (most commonly `Ingress` and `CronJob`), it will fail because `kubectl apply --prune` can only handle the resources hardcoded in the current version of `kubectl`.
See: https://github.com/kubernetes/kubectl/blob/0a152f10/pkg/cmd/apply/prune.go#L176-L192
Since the `--prune` option for `kubectl apply` currently isn't backwards-compatible, here we essentially reimplement the pruning logic in our Kubernetes plugin to be able to prune resources in a way that works for newer and older versions of Kubernetes.
This really should be fixed in `kubectl` proper. In fact, …
=> fix(k8s): backwards-compatible deployment logic

core/src/plugins/exec.ts
This fixes that pkg issue we had previously fixed for workflow steps,
but left out of the exec module type.
=> fix(exec): error when calling garden CLI within exec module tasks

core/src/config/common.ts, core/src/config/project.ts, core/src/garden.ts, core/test/data/test-project-malformed-environments/garden.yml, core/test/unit/src/garden.ts
We now validate that `project.environments` is an array and throw an informative error if it isn't.
Previously, if `project.environments` was mistakenly formatted as a map instead of an array, a cryptic type error would be printed (e.g. "Cannot read property name of undefined"). We now clearly indicate the problem
to the user.
Additionally, the `joiSparseArray` schema can now properly handle non-array inputs without failing cryptically.
Fixes #2653.
You'll note that I removed support for defining an environment with a string instead of an object. For example something like the following was allowed by `environmentsSchema`
```
environments
- someEnvName
- name: someOtherEnv …
```
=> fix(core): improve project config validation

docs/advanced/cert-manager-integration.md, markdown-link-check-config.json
Some of the links in the cert-manager guide were outdated (since the documentation site we link to has moved some pages around).
Also bumped the timeout for checking external links from 10 seconds (the default) to 30 seconds. In the past few months, GitBook has often exceeded the timeout during link checking, making our link checker falsely categorize it is a dead link.
=> chore: update links in cert-manager guide

core/src/config/common.ts, core/src/config/template-contexts/base.ts, core/src/template-string/template-string.ts, core/test/unit/src/template-string.ts, docs/using-garden/variables-and-templating.md, examples/demo-project/backend/garden.yml
This PR includes two major templating improvements:
- Any list/array value now supports a special kind of value, which is an object with a single `$concat` key. This allows you to easily concatenate multiple arrays.
- You can now map through a list of values by using the special `$forEach/$return` object.
Here's an example where we concatenate the same templated value into
two arrays of test arguments:
```yaml
kind: Module
...
variables:
commonArgs:
- yarn
- test
- -g
tests:
- name: test-a
args:
- $concat: ${var.commonArgs}
- suite-a
- name: test-b
args:
- $concat: ${var.commonArgs}
- suite-b
```
To perform a for-each loop, you specify an object with two keys, `$forEach: <some list>` and `$return: <any value>`. You can also optionally add a `$filter: <expression>` key, which if evaluates …
=> For loops and list concatenation

core/src/actions.ts
We were calling the environment status handler unnecessarily, which
might implicitly create a k8s namespace during execution.
=> fix(k8s): delete env command would recreate namespace after delete

core/src/commands/run/workflow.ts
This ensures that we also emit the stack graph event when the workflow only has script steps, or only has command steps that don't emit the stack graph event.
=> chore: always emit stack graph event in workflows

core/src/template-string/parser.pegjs, core/test/unit/src/template-string.ts
=> fix(template): ignore errors in skipped ternary clause

core/src/plugins/exec.ts, core/src/util/util.ts, core/test/unit/src/util/util.ts
This replicates the behavior in e.g. container builds. Behavior stays
the same on the default log level.
Closes #2669
cc @tedchang77
=> improve(exec): stream logs from exec module on verbose log level

core/src/commands/run/workflow.ts
This fixes a regression introduced in the last release where providers would be resolved ahead of any script steps in a workflow, which caused problems when using a script to e.g. prepare auth credentials that were subsequently used when resolving providers.
We now don't emit a stack graph event for workflows that don't have a command step that resolves the config graph.
=> fix(workflows): fix provider resolution issue

core/src/plugins/kubernetes/container/build/common.ts, core/src/plugins/kubernetes/dev-mode.ts, core/src/plugins/kubernetes/mutagen.ts, docs/guides/code-synchronization-dev-mode.md
This is just to ease troubleshooting, since otherwise the directory is
difficult to find. The symlink is named with the Garden session ID, e.g.
`.garden/mutagen/f98b8d43-baf0-448d-98d7-bc3a295beb8a`.
We also add a `mutagen.sh` script into the data directory which makes
it easier to call the mutagen CLI with the right env vars set.
So from the Garden project root, you can run e.g.
`.garden/mutagen/<session UUID>/mutagen.sh sync list`
=> improve(k8s): add symlink to mutagen data directory to .garden/mutagen

static/kubernetes/system/ingress-controller/garden.yml
The nginx ingress controller version 0.43.0 currently installed by the helm chart 3.19.0 does not support Kubernetes 1.22. Updating the chart to version 4.0.13 installs the controller in version 1.1.0, which is compatible with Kubernetes 1.19 to 1.22.
Fixes #
=> chore(ingress-nginx): update ingress-nginx to latest versio

core/src/config/base.ts, core/src/config/module.ts, core/src/config/project.ts, core/src/garden.ts, core/src/resolve-module.ts, core/test/data/test-projects/module-varfiles/garden.module-a.default.env, core/test/data/test-projects/module-varfiles/garden.project.env, core/test/data/test-projects/module-varfiles/garden.yml, core/test/integ/src/plugins/kubernetes/helm/config.ts, core/test/unit/src/config/base.ts, core/test/unit/src/garden.ts, core/test/unit/src/vcs/vcs.ts, docs/reference/commands.md, docs/reference/module-template-config.md, docs/reference/module-types/configmap.md, docs/reference/module-types/conftest.md, docs/reference/module-types/container.md, docs/reference/module-types/exec.md, docs/reference/module-types/hadolint.md, docs/reference/module-types/helm.md, docs/reference/module-types/jib-container.md, docs/reference/module-types/kubernetes.md, docs/reference/module-types/maven-container.md, docs/reference/module-types/openfaas.md, docs/reference/module-types/persistentvolumeclaim.md, docs/reference/module-types/templated.md, docs/reference/module-types/terraform.md, docs/using-garden/variables-and-templating.md
Added support for module varfiles. These are located at or under the module root, and take precedence over module variables (thus having the second-highest precedence behind CLI vars).
The path to the module varfile is set via the optional `module.varfile` field.
Also fixed an issue where CLI variables were overridden by module variables. CLI variables now correctly have the highest precedence.
Fixes #2687.
Fixes #2676.
=> feat(core): module varfiles

core/src/plugins/kubernetes/helm/common.ts, core/src/plugins/kubernetes/status/status.ts
We have a scenario where our helm chart has only one single helm hook (db migration steps)
This ends up creating any resources from helm point of view, the issue is that garden tries to wait for resources with a list `["undefined"]` producing  a weird and unclear error message
```
[2021-12-09T16:58:36.315Z] TypeError: Cannot read property 'name' of undefined
at KubeApi.<anonymous> (/home/janario/Projects/open/garden/core/src/plugins/kubernetes/api.ts:388:105)
at Generator.next (<anonymous>)
at /home/janario/Projects/open/garden/core/build/src/plugins/kubernetes/api.js:15:71
at new Promise (<anonymous>)
at __awaiter (/home/janario/Projects/open/garden/core/build/src/plugins/kubernetes/api.js:11:12)
at KubeApi.readBySpec (/home/janario/Projects/open/garden/core/build/src/plugins/kubernetes/a …
```
=> Added check chart without resources besides helm hook

core/src/plugins/kubernetes/config.ts, docs/README.md, docs/reference/providers/kubernetes.md
=> fix(k8s): allow any style of path for kubeconfig field

core/src/docs/template-strings.ts, core/src/template-string/functions.ts, docs/reference/template-strings.md, static/docs/templates/template-strings.hbs
This is useful for indenting YAML strings, for example:
`${indent("some: multiline\nyaml: document", 2)}`
->
```
some: multiline
yaml: document
```
Closes #2659
=> feat(template): add indent helper function

core/src/config/base.ts, core/src/resolve-module.ts, core/test/data/test-projects/dynamic-build-dependencies/garden.yml, core/test/data/test-projects/dynamic-build-dependencies/module-a/garden.yml, core/test/data/test-projects/dynamic-build-dependencies/module-b/garden.yml, core/test/data/test-projects/dynamic-build-dependencies/module-c/garden.yml, core/test/unit/src/config/base.ts, core/test/unit/src/garden.ts
Previously, adding an optional build dependency via a template string that sometimes resolves to null would throw an error when the string resolved to null.
The build dependencies array was always intended to be a sparse array, but due to the special handling we have to support both the shorthand (module name only) and the full (a map with the module name and other fields) formats, we needed to add a bit of extra logic to account for this use case.
Fixes #2685.
It's a bit awkward that we have to normalize / clean up the shape of the build dependencies array in two separate places, but it's perhaps acceptable given the incremental nature of the module resolution flow.
=> fix(core): properly handle sparse build deps

core/src/commands/deploy.ts, core/src/commands/test.ts, core/src/tasks/build.ts, core/src/tasks/delete-service.ts, core/src/tasks/deploy.ts, core/src/tasks/get-service-status.ts, core/src/tasks/get-task-result.ts, core/src/tasks/helpers.ts, core/src/tasks/hot-reload.ts, core/src/tasks/publish.ts, core/src/tasks/stage-build.ts, core/src/tasks/task.ts, core/src/tasks/test.ts, core/test/helpers.ts, core/test/unit/src/commands/deploy.ts, core/test/unit/src/commands/test.ts, core/test/unit/src/garden.ts, core/test/unit/src/tasks/deploy.ts, core/test/unit/src/tasks/test.ts, docs/reference/commands.md
Added a `--skip-dependencies` CLI option for the `deploy` and `test` commands.
When used with the `deploy` command, the specified services are deployed, but any additional services or tasks that they depend on are skipped.
This can be useful e.g. when your stack has already been deployed, and you want to deploy a subset of services in dev mode without redeploying any service dependencies that may have changed since you last deployed.
Similarly, for the `test` command, this option skips deploying/running any runtime dependencies of the requested test suites (not recommended for CI, but can be useful during inner-loop development in certain scenarios).
=> feat(core): add --skip-dependencies CLI option

core/src/plugins/kubernetes/status/workload.ts, core/test/unit/src/garden.ts
@twelvemo and I paired on this.
Before this fix, the rollout status of deployments using the `Recreate` strategy would be reported as ready before the new pods were fully ready.
This was fixed by copying/following the latest logic from kubectl's rollout status checking logic, comparing the requested number of replicas from the deployment spec with the actual updated pod count.
See the [corresponding logic in kubectl](https://github.com/kubernetes/kubectl/blob/24d21a0ee42ecb5e5bed731f36b2d2c9c0244c35/pkg/polymorphichelpers/rollout_status.go).
Fixes #2630 and #2717.
=> fix(k8s): fix rollout status check for Recreate

cli/bin/garden, core/src/proxy.ts
The OOM check (which involves forking the main process and monitoring
it) is causing more problems than it solves, and may also be slowing
down the overall execution.
We should test this well but my sense is this will be a net improvement.
=> fix(cli): get rid of EPIPE error and OOM check

core/src/plugins/kubernetes/logs.ts, core/src/plugins/kubernetes/run.ts, core/test/integ/src/plugins/kubernetes/container/logs.ts
Here, we remove the byte limit when streaming k8s logs directly (e.g. via the `logs` command), and greatly increase the byte limit when streaming logs for buids/tests/tasks.
Fixes #2716.
I've tested this with extremely long log lines, and with test suites where we previously saw lines being truncated. Everything is looking good.
=> fix(k8s): better handling for long log lines

.gitignore, core/src/plugins/kubernetes/config.ts, core/src/plugins/kubernetes/container/deployment.ts, core/src/plugins/kubernetes/run.ts, core/src/plugins/kubernetes/secrets.ts, core/test/integ/src/plugins/kubernetes/container/ingress.ts, core/test/unit/src/plugins/kubernetes/init.ts, core/test/unit/src/plugins/kubernetes/kubernetes.ts, docs/reference/providers/kubernetes.md, docs/reference/providers/local-kubernetes.md
This PR surfaces a new configuration field that can be used to specify arbitrary secrets that should be copied to each deployed environment. This is very similar to `imagePullSecrets` but it can be very useful to copy arbitrary secrets into namespaces  so that, for example, all developers can share a secret needed to authenticate with AWS S3 or Azure Blob Storage.
=> feat(k8s): arbitrary shared secrets

core/test/data/test-projects/terraform-module/tf/foo.tf, core/test/data/test-projects/terraform-provider/tf/foo.tf
Terraform issued warnings when running tests. The warnings were related to a missing variable and for a type defined with quotes. This reduce warning logs when running terraform related tests. 
Fixes #
=> test(terraform): removed tf syntax warnings

core/src/commands/build.ts, core/test/helpers.ts, core/test/unit/src/commands/build.ts, docs/reference/commands.md
Adds a `--with-dependants` option to the `build` command.
When used, build dependants of the modules provided as CLI arguments (and their build dependants, recursively) will also be rebuilt.
Closes #2749.
=> feat(core): --with-dependants option for build cmd

core/src/plugins/kubernetes/constants.ts, core/src/plugins/kubernetes/dev-mode.ts, core/src/plugins/kubernetes/mutagen.ts, core/test/integ/src/plugins/kubernetes/container/deployment.ts, images/k8s-sync/Dockerfile, images/k8s-sync/garden.yml, images/k8s-util/garden.yml
This PR updates Garden to use Mutagen v0.13.0.  While this still uses a custom fork of the Mutagen CLI, it now switches to using the official Mutagen agent release binaries.  These changes are important for (a) bringing in fixes and enhancements added after Mutagen v0.12.0-beta3 (on which Garden's fork was previously based) and (b) moving Garden towards using official Mutagen release binaries.
This PR also fixes an incorrect command invocation in the Mutagen plugin and switches to using the more idiomatic `MUTAGEN_DISABLE_AUTOSTART` environment variable to prevent autostart of the Mutagen daemon when invoking commands (allowing for removal of the `--auto-start` flag in Garden's fork of Mutagen).
CC @edvald @thsig
=> chore(k8s): update to Mutagen v0.13.0

core/src/plugin-context.ts, core/src/plugins/kubernetes/helm/deployment.ts, core/src/plugins/kubernetes/helm/logs.ts, core/src/plugins/kubernetes/helm/status.ts, core/test/integ/src/plugins/kubernetes/helm/deployment.ts
This PR changes the status check for the Helm plugin to mark resources that have been deployed via Helm and paused by Garden Cloud AEC functionality as `outdated`.
This is needed because when we scale down Helm workload resources from the CleanupRunners, Helm stays unaware of those changes and always returns the `ready` status.
Note: I might need help with testing this @thsig and we were also wondering how to pass a `gardenCloudContext` to plugin handlers in order to call this logic only if the user is logged in Garden Cloud and avoid unnecessary checks otherwise.
Fixes #
cc @twelvemo
=> improvement(cloud): handle AEC for Helm services

.circleci/config.yml, support/aws-gcloud-azure-ibmcloud.Dockerfile
It adds a container image that also includes the ibmcloud cli tool. Some users are using ibmcloud and need this image for running workflows in Garden Cloud. Usually we also add an image just with Garden and the respective cloud provider tool, in this case i am not sure if there is demand for that. But I can easily add that, if it makes sense.
Fixes #
=> chore: add garden image with ibmcloud cli tool

examples/conftest/helm-chart/templates/ingress.yaml, examples/hot-reload-k8s/node-service/garden.yml, examples/vote-helm/base-chart/templates/ingress.yaml, examples/vote-helm/vote/templates/ingress.yaml
Update the ingress spec in our examples to use `networking.k8s.io/v1`. The examples still using `extensions/v1beta1` or 
`networking.k8s.io/v1beta1` stopped working in Kubernetes 1.22.
Fixes #
=> improvement(examples): update ingress specs in example garden projects

core/src/cli/cli.ts, core/src/commands/base.ts, core/src/commands/run/workflow.ts
We now log any errors that come up in a workflow step command in the body log. The `run workflow` command's error logging was also improved and cleaned up.
The optional `skipCliErrorSummary` field isn't ideal, but we need to assume a bit more manual control over the error output/formatting for the `run workflow` command (because we don't want to log the errors twice).
=> improvement(core): better workflow error logging

core/src/cloud/api.ts, core/src/cloud/auth.ts
Currently, if a domain contains a trailing slash in the project config it can cause garden to redirect to incorrect URLs, for example, attempting to log in with the domain set to `https://example.com/` will yield a login URL with two slashes after the origin (i.e. `https://example.com//clilogin/123`. This PR updates all the instances I found where this issue can occur using the `URL` builtin.
Fixes #
=> fix(core): ignore trailing slashes in project config domains

scripts/install-osx-dependencies.sh
The brew command has changed format, this means `brew cask ...` as used in the installation script does not work anymore.
Fixes #
=> fix: updated brew command in dependency install script

cli/bin/garden, cli/bin/garden-debug, cli/src/build-pkg.ts
This raises the maximum heap size for uncollected objects in the process, which may be necessary for large projects.
=> fix(cli): potential OOM error for large projects

core/src/cli/cli.ts, core/src/cli/debug-logs.ts, core/src/logger/renderers.ts, core/src/logger/util.ts, core/src/logger/writers/file-writer.ts, core/src/logger/writers/json-file-writer.ts, core/src/logger/writers/json-terminal-writer.ts
We now output all debug-level and silly-level logs into logfiles in the project's `.garden/logs` directory.
Debug-level logs are logged to a debug logfile using standard text formatting.
Silly-level logs are logged to a JSONL-formatted logfile (where each line is a JSON string). These can later be used to provide dynamic rendering of command logs via the CLI (e.g. allowing the user to select the log level, and then filtering the JSON entries before rendering them to the terminal).
The names of these logfiles include the command name, log level and the time the command was executed (as an ISO timestamp).
Logfiles older than 7 days are also automatically cleaned up by this logic.
This will be useful for gathering debug information when something goes …
=> feat(core): debug logfiles

core/src/template-string/functions.ts, core/test/unit/src/template-string.ts, docs/reference/template-strings.md
We have the need for stable but unguessable identifiers for some aspects of our Garden stacks. Unfortunately uuidv4 as a template string function satisfies the latter requirement, but would presumably change on every deploy so we'll end up with a continually changing stack. Using a hashing function would satisfy both requirements.
This PR just adds a template string `sha256` based on the crypto package in the standard library.
N/A
=> feat(core): add template string sha256 function

scripts/install-osx-dependencies.sh
**What this PR does / why we need it:**
`nvm` command fails in the `install-osx-dependencies.sh` script because it is not visible in the script after the installation. The fix is based on the suggestion from the installer.
This PR also adds `yarn` installation command to the `install-osx-dependencies.sh`.
=> fix(scripts): fixed deps installation script

core/src/plugins/kubernetes/container/build/buildkit.ts, images/buildkit/Dockerfile, images/buildkit/garden.yml
Updates the version of BuildKit used for the `cluster-buildkit` build mode from 0.8.1 to 0.9.3.
The accompanying Docker images have been built and published.
Fixes #2815.
=> improvement(k8s): bump BuildKit version to 0.9.3

core/src/plugins/container/config.ts, core/src/plugins/exec/logs.ts, core/test/unit/src/plugins/exec/logs.ts
From individual commits:
[fix(core): treat null/false as undefined for container image field](https://github.com/garden-io/garden/commit/df9c3c64a27549700e31d90d078d4a6c9f854a74) 
We want to add a Joi schema that treats null/false values as undefined
for optional strings in general but this is just a quick fix to unblock
a user.
And:
[fix(core): treat null/false as undefined for container image field](https://github.com/garden-io/garden/commit/df9c3c64a27549700e31d90d078d4a6c9f854a74) 
We want to add a Joi schema that treats null/false values as undefined
for optional strings in general but this is just a quick fix to unblock
a user.
Fixes #
=> Fix exec error log streaming

core/src/plugins/kubernetes/helm/status.ts, core/src/plugins/kubernetes/kubernetes-module/handlers.ts, core/src/plugins/kubernetes/status/ingress.ts, core/src/plugins/kubernetes/types.ts, core/src/types/service.ts, core/test/unit/src/plugins/kubernetes/status/ingress.ts, docs/reference/commands.md
This adds a best-effort extraction of ingresses from the resources generated
in `kubernetes` and `helm` modules.
=> improve(k8s): pick up ingresses from kubernetes and helm modules

examples/demo-project-start/backend/Dockerfile, examples/demo-project/backend/Dockerfile
Golang image version 1.8.3 is too old and is not compatible with arm64 architecture. Thus, it can't be used with Apple M1 chips.
Used the latest available golang version.
Old version had compatibility issues with Apple M1.
Now the golang image is upgraded to the latest stable version.
=> fix(examples): updated golang version in examples

plugins/jib/maven.ts
It fixes an issue where garden tries to extract a downloaded maven tarball with zip on windows.
Fixes #2849 
=> fix: maven download for windows

core/src/plugins/kubernetes/dev-mode.ts
This fixes an error that occurs when syncing to/from a local path that contains spaces.
=> fix(k8s): escape spaces in local mutagen dests

core/src/plugins/exec/exec.ts, core/test/data/test-project-exec/module-local-persistent/garden.yml, core/test/unit/src/plugins/exec/exec.ts
Before this fix, log streaming would simply stop if a line was empty.
This could e.g. happen on double new-lines.
This commit fixes the issue and adds a unit test.
Fixes #
=> fix(exec): properly handle empty lines in local service logs

CONTRIBUTING.md
This PR adds some instructions on how to fix possible ARM64 issues when running `yarn test` locally. It also fixes some documentation links and typos.
=> Docs: updated yarn test instructions for arm64 arch

core/src/proxy.ts
This slipped through tests after the Node.js 14 move.
Again, need to test explicitly for watch mode issues on mac, but rushing this through to unblock.
=> fix(core): fix EADDRNOTAVAIL error in watch mode

core/src/cli/cli.ts, core/src/commands/custom.ts, core/test/unit/src/cli/cli.ts
This was both inefficient and unnecessary, and could cause issues in some edge cases (as discovered by a user).
=> fix(cli): avoid unnecessary git scan at startup

core/src/cli/cli.ts, core/src/cli/helpers.ts
Users would see some log spam upon certain errors during the version check. This cleans that up.
As a general note, let's _please_ not allow floating promises and do this type of catching instead.
=> fix(cli): uncaught promise error when version check fails

.circleci/config.yml
We were leaving one namespace per CI run basically, filled up the cluster :P
=> chore(ci): fix cleanup of windows test namespace

core/src/plugins/kubernetes/config.ts, core/src/plugins/kubernetes/kubectl.ts, docs/reference/providers/kubernetes.md
A request from a user. Should help with some edge-case scenarios, but should be noted (and is noted in the docs) that this should be avoided unless there are specific reasons to use it.
=> feat(k8s): allow overriding kubectl path in provider config

scripts/test-release.sh
@thsig recommended disabling some steps in the test script, those steps have been commented out.
Also, the dev mode test was modified to use the `vote` project instead of the `demo-project`, because the demo project doesn't have a dev mode sync configuration, and the vote does. It allows testing code changes syncing in dev mode.
=> chore: test release script corrections

core/src/plugins/kubernetes/mutagen.ts
This PR fixes an issue where a space in the `kubectl` executable path (e.g. in a home directory name) would cause Garden's Mutagen exec transport to fail.  It reverts a previous fix that performed escaping on the path and updates the Mutagen fork to parse around this issue.
I can't find an assigned issue; the problem was reported via Slack.
The corresponding fix in Garden's Mutagen fork is garden-io/mutagen@1c930de.  This is a temporary fix.  Once we add custom transports in Mutagen v0.15, we can abolish the exec transport and provide the `kubectl` path more robustly.
CC @edvald @thsig
=> fix(k8s): handle spaces in kubectl path provided to Mutagen

static/kubernetes/system/ingress-controller/garden.yml
The Garden shipped ingress controller sets it's own `ingressClass` to the default one, which makes it pick up ingresses that don't have the `ingressClass` param specified.
Fixes #
=> fix: add default ingress class for nginx ingress controller

core/src/cli/cli.ts, core/src/server/server.ts
We removed the dashboard link in favour of a link to the Garden Cloud
namespace for Cloud users, but in hindsight we should also print the
dashboard link for them.
Fixes #
=> fix(core): always show dashboard link

README.md, core/src/cli/cli.ts, core/src/config/workflow.ts, docs/reference/commands.md, docs/reference/workflow-config.md, markdown-link-check-config.json
This PR fixes the formatting issue reported by the linter.
=> style: fixed formatting

core/src/commands/create/create-module.ts, core/src/commands/create/create-project.ts, core/src/commands/create/helpers.ts, core/src/docs/config.ts, core/test/unit/src/commands/create/create-module.ts, core/test/unit/src/commands/create/create-project.ts, core/test/unit/src/docs/config.ts, docs/getting-started/2-initialize-a-project.md, docs/reference/commands.md
This pr adds a `--skip-comments` flag to create commands which removes all commented out sections from the generated files.
Motivation for the change is that the [getting started guide](https://docs.garden.io/getting-started/2-initialize-a-project) has all the comments removed so it would make sense to add that option to the cli as well.
* Please note if I need to update any documentation or add a note about the flag to the [getting started guide](https://docs.garden.io/getting-started/2-initialize-a-project)
* I gave up on adding this as an interactive option as current logic doesn't differentiate between boolean parameters being undefined or false. That change would require a bit of a bigger rewrite
=> feat: add skip-comments option to cli create command

core/src/actions.ts, core/src/cache.ts, core/src/garden.ts, core/src/resolve-module.ts, core/src/types/module.ts, core/src/types/plugin/provider/augmentGraph.ts, core/src/vcs/vcs.ts, core/src/watch.ts, core/test/unit/src/actions.ts, core/test/unit/src/cache.ts, core/test/unit/src/garden.ts, core/test/unit/src/vcs/vcs.ts
This combines two things:
1. Avoid unnecessary cache invalidation when using `generateFiles`
2. Drop an unused and soon-to-be-superseded plugin framework feature that
prompted an unnecessary extra set of version resolution and file scanning.
Also threw in some extra debug logs for when we might need to dig further.
This should provide a small boost for most/all projects, but potentially
substantial improvements for larger projects, especially when using module
templates and `generateFiles`.
=> improve(core): faster module resolution for certain scenarios

.circleci/config.yml
It looks like our CircleCI containers are using old Ubuntu 16 images. Recently I (and likely many of us) received an email about the deprecation of old Ubuntu images.
The same warning can be found in [CircleCI logs](https://app.circleci.com/pipelines/github/garden-io/garden/11466/workflows/4c6334c4-6cd8-4baa-b411-1acc412c65cc/jobs/177831):
> This job is either using an Ubuntu 14.04 image, an Ubuntu 16.04 image, or the default Ubuntu 14.04-based image by specifying machine:true in config. These images (including the default image) [will be removed on May 31, 2022. ](https://circleci.com/blog/ubuntu-14-16-image-deprecation/)Upgrade your image from Ubuntu [14.04 ](https://circleci.com/docs/2.0/images/linux-vm/14.04-to-20.04-migration/)or …
=> chore: updated circleci ubuntu image to 20.04

core/src/plugins/kubernetes/container/ingress.ts, core/src/plugins/kubernetes/local/config.ts, static/kubernetes/system/ingress-class/garden.yml
* Fixes ingress not working for microk8s
* adds a warning if the networking api is at `networking.k8s.io/v1` and no ingressclass exists for the ingresses created by garden 
(the warning appears twice because two containers are created which both have ingress)
=> fix: ingress for microk8s and k8s 1.22

core/src/cli/cli.ts
Before this fix, a new log line with the Cloud NS link would be added every time a config was changed.
Just a quick fix for something I noticed in a demo the other day.
=> fix(cloud): fix duplicate footer on config change

core/src/vcs/git.ts, core/test/unit/src/vcs/git.ts
**What this PR does / why we need it**: Fixes handling of uninitialized or not-updated git submodules. Previously having an empty git submodule resulted in garden getting stuck and eventually running into stack overflow.
Fixes #2119
Explanation of the bug:
the recursive [getFiles](https://github.com/garden-io/garden/blob/git-submodule-fixes/core/src/vcs/git.ts#L130) function calls itself for each git submodule. If a submodule is initialized it acts as it's own git project and thus the [gitRoot](https://github.com/garden-io/garden/blob/git-submodule-fixes/core/src/vcs/git.ts#L204) changes to that module's own path. This change will stop the recursion if the submodule doesn't have a submodule of it's own. But when a …
=> fix(core): fix git submodules usage

docs/README.md
This PR updates auto-generated docs introduced in https://github.com/garden-io/garden/pull/2873
=> fix(docs): re-generated docs

core/src/commands/test.ts, core/test/unit/src/commands/test.ts, docs/reference/commands.md
The test command was missing a `--skip` flag (similar to what the deploy command has). This PR fixes that (needed by a user). 
More on the meta level, but it would be great to have more consistency in command arguments and options and ideally enforce that somehow. E.g., all commands that operate on lists should be guaranteed to have a filter / omitter and the logic would ideally be re-used so that we don't need to test each one in isolation. 
Fixes #
=> improvement(core): add --skip flag to test command

core/src/plugins/kubernetes/dev-mode.ts, core/src/plugins/kubernetes/mutagen.ts, core/test/integ/src/plugins/kubernetes/container/deployment.ts, images/k8s-sync/Dockerfile, images/k8s-sync/garden.yml
This pull request updates the k8s-sync functionality to use Mutagen v0.14.0 (or, rather, Garden's Mutagen fork rebased atop Mutagen v0.14.0).  The [v0.14.0](https://github.com/mutagen-io/mutagen/releases/tag/v0.14.0) release brings some important optimizations to synchronization and filesystem watching.  This should hopefully be the last of the fork-based updates to Mutagen in Garden.
No specific issues are fixed by this PR.
This PR is not yet complete, because a corresponding `gardendev/k8s-sync` tag needs to be built manually using `images/k8s-sync/Dockerfile`.  Once that's done, another commit will be necessary as part of this PR to reference the updated image.
It may be worth …
=> chore(k8s): update Mutagen to v0.14.0

core/src/plugins/kubernetes/dev-mode.ts, core/src/plugins/kubernetes/mutagen.ts, core/test/integ/src/plugins/kubernetes/container/deployment.ts, images/k8s-sync/Dockerfile, images/k8s-sync/garden.yml
This reverts commit 27033ae2cd333ca8861e32d22ab60e346c9df9b6.
It reverts the Mutagen version to `0.13` and fixes Circle CI pipeline failures in master.
Fixes #
=> revert: "chore(k8s): update Mutagen to v0.14.0"

plugins/conftest/.mocharc.yml, plugins/terraform/.mocharc.yml
This was causing some CI flakiness.
=> chore(ci): longer timeouts in conftest + terraform plugin tests

core/src/plugins/kubernetes/namespace.ts
Just a minor thing I happened to come across, some no-op k8s API calls being made on provider init.
=> fix(k8s): avoid unnecessary namespace patch no-op on init

docs/guides/in-cluster-building.md
The markdown anchor links must be lowercased. This PR fixes anchor links in "In-Cluster Building" guide.
=> docs: fixed anchor links

docs/getting-started/1-installation.md
Removed some obsolete parts from the Windows installation guide. This complements the commit https://github.com/garden-io/garden/commit/97d49fe783af4288d9489a0654ca5d7b21e0b463.
Fixes #2958
=> docs: updated windows installation guide

core/src/cli/cli.ts, core/src/commands/base.ts, core/src/commands/run/workflow.ts, core/test/unit/src/commands/run/workflow.ts
Fixes the issue introduced in https://github.com/garden-io/garden/pull/2754 where workflows will fail silently if they fail outside of the steps (e.g. invalid workflow config) issue: #2883
Also fixes scripts logs not being visible with the `--output` option, issue: #2898
closes: #2883 and #2898
With this logic:
1. If `--output` is not specified and error(s) occur in the workflow steps themselves they will be printed while running the task and generic aggregated error will be printed at the bottom.
2. If `--output` is not specified and error occurs *outside* the workflow steps it will be printed immediately
The `--output` option also works now and the `.garden/error.log` gets properly populated as well.
=> fix: workflows fail silently and don't output script logs with --output option

core/src/plugins/kubernetes/container/build/common.ts
Increased timeout and number of retries for the `rsync` command call.
Fixes #2944
This _should_ fix https://github.com/garden-io/garden/issues/2944. The reporter hasn't verified the fix yet. The link to the edge release was posted in the original issue.
=> fix: increased num of retries and timeouts for rsync

core/src/plugins/kubernetes/container/deployment.ts, core/src/plugins/kubernetes/container/status.ts
Before this fix, `container` services without dev mode configs would be redeployed when toggling dev mode (e.g. when running `garden dev` and then `garden deploy`). This led to unwanted and unnecessary redeploys in
certain scenarios.
The fix essentially consisted of applying the the same fix to `container` service deployments and status checks as were applied to `kubernetes` and `helm` services in 5bfb3d70.
Fixes an issue that's been driving @eysi09 up the walls for months.
=> fix(container): fix unneeded redeploys in dev mode

core/src/plugins/container/config.ts, core/src/plugins/kubernetes/container/deployment.ts, core/test/unit/src/commands/get/get-config.ts, core/test/unit/src/garden.ts, core/test/unit/src/vcs/vcs.ts, docs/reference/module-types/container.md, docs/reference/module-types/jib-container.md, docs/reference/module-types/maven-container.md
This PR exposes an optional `tty` property on container module configs. This property defaults to `false`, which used to be the only option before exposing it as a property in the config schema.
The benefit of being able to turn TTY/stdin on is to support attaching to a running container with TTY/stdin turned on. This comes into play when troubleshooting a service as it runs with a framework that supports interactive breakpoints. Interactive breakpoints require that you can send keyboard input to the service and interact with it via SSH.
As a companion to this configuration option, `garden attach` could potentially be added as a command, but even without that I find immense utility in being able to run commands like `kubectl attach -ti …
=> Feat: Expose TTY setting on container modules

CHANGELOG.md
This PR synchronizes the changelog with the [0.12.41 release notes](https://github.com/garden-io/garden/releases/tag/0.12.41).
Fixes #
=> chore: synced changelog with release notes

core/test/data/test-projects/helm/postgres/garden.yml, core/test/integ/src/plugins/kubernetes/util.ts, docs/guides/using-helm-charts.md, examples/tasks/postgres/garden.yml, examples/vote-helm/api-image/app.py, examples/vote-helm/postgres/garden.yml, examples/vote-helm/redis/garden.yml, examples/vote-helm/worker-image/src/main/java/worker/Worker.java, examples/vote-helm/worker-image/src/main/resources/application.properties, plugins/conftest-kubernetes/test/test-project/helm/garden.yml
Some tests fail with errors:
```
Error: chart "postgresql" version "8.10.5" not found in https://charts.bitnami.com/bitnami repository
Error: chart "redis" version "10.5.7" not found in https://charts.bitnami.com/bitnami repository
```
The charts older than 6 months are not available in the [standard bitnami charts repo](https://charts.bitnami.com/bitnami) since June 1st.  The index file was too heavy and some older versions were removed from the index. Too heavy index file caused some CloudFront traffic limitations and errors like this:
```
failed to generate YAML for specified Helm chart: failed to pull chart: looks like "https://charts.bitnami.com/bitnami" is not a valid chart repository or cannot be reached: stream error: stream ID 1; …
```
=> test: updated some old helm charts to the newer versions

core/src/plugins/container/container.ts
Updated the bundled Docker CLI from 19.03.6 to 20.10.9.
This is prompted by some users running into trouble with local Docker builds because we were shipping an older version of Docker.
If the need arises, we could also add a config field to the `local-kubernetes` and `kubernetes` providers that allows using whatever Docker CLI binary is on the PATH instead of the Garden-bundled version (like we do with the `terraform` and `pulumi` version fields).
That said, this may be unnecessary in practice unless actual backwards-incompatibilities are encountered by our users.
=> chore: update bundled Docker to 20.10.9

docs/advanced/terraform.md
**What this PR does / why we need it**: This PR explains how to use an exec module to inject environment variables into backend terraform files
=> docs: add backend injection to terraform doc

core/src/commands/get/get-modules.ts, core/test/unit/src/commands/get/get-modules.ts, docs/reference/commands.md
Added a `--full` option to the `get modules` command.
When used, the fully resolved module config is logged (with some internal/irrelevant fields omitted). Any Garden Cloud secrets that would appear in the logged output are hidden/sanitized.
This is useful for debugging/writing template strings for modules, and for reasoning about which files/variables factor into the  module's version calculation.
This PR replaces #2652, and reuses much of the rendering logic sketched out there.
=> feat(cli): --full option for get modules command

core/src/plugins/kubernetes/local/config.ts, core/src/plugins/kubernetes/util.ts, static/kubernetes/system/nginx-kind/garden.yml, static/kubernetes/system/nginx-kind/nginx-kind-new.garden.yml, static/kubernetes/system/nginx-kind/nginx-kind-old.garden.yml
based on https://github.com/garden-io/garden/pull/2902, but is backwards compatible
this is currently blocking #2999
(ignore the broken ci, I have  #2999 for that)
=> fix: update nginx ingress controller for kind

examples/vote-helm/api-image/Dockerfile, examples/vote-helm/api-image/app.py, examples/vote/api/Dockerfile, examples/vote/api/app.py
This PR changes `vote` and `vote-helm` examples to use modern Python 3.10 instead of ancient Python 2.7.
Fixes #
=> chore: changed vote examples to use python 3

core/src/plugins/kubernetes/config.ts, docs/reference/providers/kubernetes.md, docs/reference/providers/local-kubernetes.md
Kaniko has a bug with not computing the correct cache keys when running multistage builds yielding images with outdated files inside. This version fixes the issue.
=> fix(k8s): change kaniko default image to 1.8.1

.circleci/config.yml, cli/package.json, cli/patches/pkg+5.7.0.patch, cli/src/build-pkg.ts, docs/advanced/pulumi.md, docs/guides/remote-kubernetes.md, plugins/jib/test/index.ts, static/kubernetes/system/cert-manager/cert-manager-crd.yaml, static/kubernetes/system/nginx-kind/nginx-kind-old.garden.yml, support/alpine-builder.Dockerfile, support/gcloud.Dockerfile, yarn.lock
FIx a bunch of small things that were messing up ci + add new k8s versions and remove old unsupported ones.
Please review this commit by commit (they have a lot of extra info in them)
Stuff that still sometimes fails (don't have any more time to spend on debugging, maybe will do so later)
* build step will still occasionally fail due to the concurrency issue in pkg. The delays seemed to help, but not completely fix (more info in the pkg commits)
* in vm e2e runs sometimes mutagen fails to sync stuff and crashes ([example](https://app.circleci.com/pipelines/github/garden-io/garden/12104/workflows/7e760b32-0793-46e7-8182-91b19118599c/jobs/196256))
=> fix a few ci problems

images/circleci-runner/Dockerfile, images/circleci-runner/garden.yml, support/alpine-builder.Dockerfile, support/alpine.Dockerfile, support/buster.Dockerfile, support/gcloud.Dockerfile
Update node, alpine and the gcloud SDK versions:
- node from 14.19.0 -> 14.19.3
- alpine from 3.14 -> 3.16
- GCloud SDK from 331.0.0 to 390.0.0. Note that there are some breaking changes detailed in the changelog: https://cloud.google.com/sdk/docs/release-notes
Fixes #
=> improvement: bump alpine, node and gcloud SDK version in support

core/src/vcs/git.ts
This is an additional fix for #2905. The same issue happened with some sub-folder of the git repo in the Garden Cloud testing.
The suggested solution is to always consider any working directory in a git repository as a safe one.
Fixes #
=> fix: git repository ownership issue

core/src/cli/cli.ts, core/src/cloud/api.ts, core/src/cloud/buffered-event-stream.ts, core/src/commands/dashboard.ts, core/src/config-graph.ts, core/src/events.ts, core/src/process.ts, core/src/server/server.ts, core/src/tasks/test.ts, core/test/unit/src/enterprise/event-handlers.ts
Listen to events from cloud and create tasks based on them. Also dashboard command can also be used for it.
Will leave as draft until this has been properly tested and combined with the Cloud implementation and the command palette.
=> Core-cloud Interactivity

core/src/vcs/git.ts
This PR minimizes number of `git status` calls in the `GitHandler.ensureSafeDirGitRepo(log: LogEntry, path: string)` method. Every successful `git status` result is cached in memory.
Fixes #
See https://github.com/garden-io/garden/pull/3012#discussion_r902252328 for more details.
=> improvement: optimized safety checks for git repos

core/src/plugins/kubernetes/api.ts
closes #2741
before: (see issue for why this is bad)
```
Failed resolving provider local-kubernetes. Here is the output:
contexts[0].name is missing
Failed resolving one or more providers:
- local-kubernetes
```
after:
```
Failed resolving provider kubernetes. Here is the output:
Could not parse kubeconfig, Error: contexts[0].name is missing
Failed resolving one or more providers:
- kubernetes
See .garden/error.log for detailed error message
```
=> chore: add more context for kubeconfig err

core/src/actions.ts, core/src/tasks/test.ts, core/src/types/plugin/plugin.ts, core/test/data/test-project-test-deps/module-a/garden.yml, core/test/unit/src/tasks/test.ts
Before this fix, `${runtime.*}` values were not resolved in test configs before calling the plugin handlers for `getTestStatus` and `testModule`.
This was fixed by applying a similar runtime resolution flow as is used for service and task actions to test actions.
For consistency, a few interfaces and types were added to correspond with how these things are laid out for service and task handlers.
Fixes #2862.
=> fix(core): resolve runtime values in test configs

cli/package.json, core/package.json, core/src/actions.ts, core/src/config-store.ts, dashboard/package.json, dashboard/src/api/actions.ts, e2e/package.json, package.json, sdk/package.json, yarn.lock
This paves the way for an update to Node 16 and supporting ES modules.
See more on TS 4.7 here:
https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/
=> chore: update TypeScript to 4.7.4

core/src/plugins/kubernetes/run.ts
When running tests that return artifacts, the K8S runner needs to take a different path compared to the case without artifacts. In this case the log output is diverted into a named pipe. Due to how the output was passed to the named pipe (using `exec`), stderr was not included. This PR tries to ensure that stderr is included in the log output. 
Fixes #
=> fix: include stderr for outputs from commands returning an artifact

.circleci/config.yml
there's a small chance it will help with the flaky build-dist step, but I doubt it :pray:
=> Use proper cache dir for pkg node binary caching

core/src/plugins/kubernetes/constants.ts, core/src/plugins/kubernetes/mutagen.ts, images/k8s-sync/Dockerfile, images/k8s-sync/garden.yml, images/k8s-util/garden.yml
This pull request updates Garden to use Mutagen v0.15.0 for dev mode.  It makes use of the JSON output added in Mutagen v0.15.0, obviating the need for part of Garden's Mutagen fork.  The custom Garden exec transport is still implemented via the fork.
While this PR doesn't include any user-visible changes to Garden's behavior (except when using the `mutagen.sh` wrapper script), it does make additional synchronization session statistics and metadata available to Garden internally, which can be presented to users in future updates. For now this information is available via the `mutagen.sh` script.
The `k8s-sync` and `k8s-util` images will need to be manually regenerated before CI will succeed.
I'm not sure of the …
=> refactor(k8s): update Mutagen to v0.15.0

core/src/commands/cloud/groups/groups.ts, core/src/commands/cloud/secrets/secrets-create.ts, core/src/commands/cloud/secrets/secrets-delete.ts, core/src/commands/cloud/secrets/secrets-list.ts, core/src/commands/cloud/secrets/secrets.ts, core/src/commands/cloud/users/users-create.ts, core/src/commands/cloud/users/users-delete.ts, core/src/commands/cloud/users/users-list.ts, core/src/commands/cloud/users/users.ts, docs/reference/commands.md
This PR removes some obsolete "experimental" labels from the Garden cloud commands' description.
Fixes #
=> docs(cloud): removed "experimental" labels from cloud commands

core/src/commands/base.ts, core/src/commands/run/task.ts, core/src/commands/run/test.ts, core/src/task-graph.ts, core/test/helpers.ts, core/test/unit/src/commands/run/task.ts, core/test/unit/src/commands/run/test.ts, core/test/unit/src/task-graph.ts
This would mask failures in task/test dependencies and create an opaque error message.
=> fix(cli): bad error message when dependency fails in run task/test cmd

core/src/actions.ts, core/src/commands/delete.ts, core/src/tasks/delete-service.ts, core/test/unit/src/commands/delete.ts, docs/reference/commands.md
Added a `--dependants-first` option to the `delete service` and `delete environment` commands.
When used, services will be deleted in reverse dependency order. That is, service dependants will be    deleted before their dependencies.
Also added a `--with-dependants` option to the `delete service` command, which deletes any running      dependants of the requested service/services.
Fixes #2782.
Note that the dependency logic here only uses service dependencies and doesn't traverse task dependencies to find transitive service dependencies.
This means that e.g. in the vote project, the `result` service won't be deleted before the `postgres` service, even though `result` transitively …
=> feat(core): opt for deleting services in dep order

core/src/template-string/parser.pegjs, core/test/unit/src/template-string.ts, docs/using-garden/variables-and-templating.md
A long-requested addition to the template syntax. Examples:
`${[1, 2, 3]}`
`${["foo", "bar"]}`
`${[var.someKey, var.someOtherKey]}`
`${join(["foo", "bar"], ",")}`
Fixes #3053
=> feat(config): support array literals in template strings

core/src/plugins/kubernetes/local-mode.ts, core/src/util/recoverable-process.ts, core/src/util/util.ts, core/test/integ/src/plugins/kubernetes/container/deployment.ts, core/test/integ/src/plugins/kubernetes/helm/deployment.ts, core/test/integ/src/plugins/kubernetes/kubernetes-module/handlers.ts, core/test/integ/src/plugins/kubernetes/local-mode.ts, core/test/unit/src/util/recoverable-process.ts
I've noticed that sleep periods between retries do not work well when I use Garden binaries built by CI pipeline. Local builds work fine. I'm not sure if it's related to the sync sleeping implementation, but it makes sense to use async sleep like anywhere else in the project codebase.
Async sleep won't spawn a new OS process, it will use `Promise` instead.
Also, sleep is called from the [async function](https://github.com/garden-io/garden/blob/master/core/src/util/recoverable-process.ts#L423), so it makes sense to keep the sleep call async too.
This PR also fixes state management in `RecoverableProcess` class. Now both `"stopped"` and `failed"` are the valid final states. The former stands for forced process tree stop, the latter -- for the failure …
=> improvement: used async sleeps between retries in recoverable process

core/src/commands/delete.ts, core/test/unit/src/cli/helpers.ts, core/test/unit/src/commands/run/workflow.ts, docs/reference/commands.md
This PR only contains the user-facing parts for now. We can rename internals later. The internal includes the classes like `DeleteXxx[Command|Params|Result]`, some handlers, methods and functions in the action router, local variables, etc.
Changing the internal now can cause extra conflicts with https://github.com/garden-io/garden/tree/graph-v2.
Fixes #
=> refactor: renamed delete commands

core/src/commands/deploy.ts, core/src/commands/dev.ts, core/src/commands/helpers.ts
This PR ensures that modules deployed in `local-mode` are skipped by the file watcher.
Fixes #
No tests have been added because there are no similar tests for `dev-mode`. Test coverage can be improved later, for instance, in `0.13` branch.
=> improvement(local-mode): don't watch files in local-mode modules

.github/workflows/update-homebrew-action.yml, cli/src/build-pkg.ts, cli/test/unit/src/build-pkg.ts, core/src/commands/self-update.ts, scripts/test-release.sh, support/install.ps1, support/install.sh
This PR updates Garden release packages' URLs. New URLs are connected to Scarf.sh to get better tracking of downloads.
Fixes #
=> chore: update release url

core/src/commands/logs.ts, core/src/commands/publish.ts, core/test/unit/src/cli/helpers.ts, core/test/unit/src/commands/logs.ts, core/test/unit/src/commands/publish.ts, docs/reference/commands.md
This PR removes deprecated opts from garden CLI commands.
Fixes #
=> refactor: removed deprecated options from garden commands

core/src/commands/create/create-module.ts, core/src/commands/create/create-project.ts, core/src/commands/create/helpers.ts, core/test/unit/src/commands/create/create-module.ts, core/test/unit/src/commands/create/create-project.ts, docs/getting-started/2-initialize-a-project.md, docs/reference/commands.md
with this addition I'm undoing my very first contribution to garden (as an employee). #2904
* create commands no longer add empty commented fields
* remove `--skip-comments` flag
* update getting-started docs accordingly
* add links do docs on top of generated docs
=> Remove commented fields from create command outputs

core/src/cli/cli.ts, core/src/config/project.ts, core/src/docs/config.ts, core/src/garden.ts, core/test/data/test-build-dependants/project.garden.yaml, core/test/data/test-projects/custom-commands-invalid/project.garden.yml, core/test/data/test-projects/custom-commands/project.garden.yml, core/test/data/test-projects/empty-doc/garden.yml, core/test/data/test-projects/exec-task-outputs/garden.yml, core/test/data/test-projects/helm/garden.yml, core/test/data/test-projects/huge-project/garden.yml, core/test/data/test-projects/kubernetes-module/garden.yml, core/test/data/test-projects/persistentvolumeclaim/garden.yml, core/test/data/validate/bad-module/garden.yml, core/test/data/validate/bad-project/garden.yml, core/test/data/validate/bad-workflow/garden.yml, core/test/unit/src/config/base.ts, core/test/unit/src/config/project.ts, core/test/unit/src/garden.ts, docs/reference/project-config.md
Now environment field is required in project configs.
This also eliminates the need for an internal default env (used to be "local"), now if default env is not set just the first one will be selected (as before) and error is thrown if envs is undefined or an empty array.
=> chore: require environments field in project configuration

core/src/cli/helpers.ts
This PR fixes the displayed values of multi-char aliases in Garden commands' descriptions.
Fixes #3084
=> fix(docs): fixed multi-char aliases in commands' descriptions

core/src/config-store.ts
needed for backwards compatibility (if user downgrades from a garden version which has new keys garden would stop working otherwise).
Needs to be merged before #3097
=> chore: allow unknown keys in config-store

core/src/build-staging/rsync.ts, core/src/cli/cli.ts, core/src/cli/helpers.ts, core/src/config-store.ts, core/src/util/validateInstall.ts, core/src/vcs/vcs.ts, core/test/unit/src/cli/cli.ts, core/test/unit/src/config-store.ts, core/test/unit/src/util/validateInstall.ts
checks if git and rsync are installed with valid versions
and gives readable error otherwise.
check results are cached and are not checked again once passed
I opted for the global config instead of the sqlite because connecting to the db and starting it took too long.
=> chore: check for requirements being installed

docs/reference/module-types/jib-container.md, plugins/jib/index.ts
This PR fixes the config schema validation for `jib-module` module type.
Prior to this PR, the validation did not work properly for the `jdkVersion`, `projectType` and `tarFormat` config fields. This happened because `joi.allow()` method itself doesn't raise an error in an invalid value is passed in. To make it work, it should be used with `.only()` method like `joi.string().allow("a", "the").only()`. Alternatively, a single `.valid()` method can be used (this approach was chosen to fix the issue).
Without the changes made in this PR the jib plugin failed with the error below if any incorrect values were passed to the fields validated with `.allow()` method:
```
Failed building {module-name}. Here is the output: …
```
=> improvement(jib): enhanced schema validation

.github/workflows/scorecards.yml
The OSSF scorecard scanner will check for the following best practices:
https://github.com/ossf/scorecard#scorecard-checks
It can be used to increase visibility for some bad practices that increase risk for supply chain attacks.
Fixes #
=> ci: add OSSF Scorecard security scanner

.github/workflows/update-homebrew-deprecated.yml
We reduce permissions to make it unlikely that third party actions
do something weird with out GITHUB_TOKEN – the token is accessible
by third party actions by default and could be misused.
Fixes code-scanning alert 12
Fixes #
=> ci: restrictive permissions for update-homebrew-deprecated.yml

.github/workflows/scorecards.yml
we can now block other egress to make it harder to exfiltrate secrets for third
party dependencies and actions
none really, it just hardens the scorecard workflow, because we can (basically as a canary for hopefully our release workflows in the future, when we migrate them from macOS to Linux)
Stepsecurity audit log
https://app.stepsecurity.io/github/garden-io/garden/actions/runs/2918784935
=> ci: harden egress for scorecard workflow

core/src/commands/custom.ts
Closes https://github.com/garden-io/garden/issues/3151
Garden [custom commands](https://docs.garden.io/advanced/custom-commands) were run from the path the command was called from. Now garden project root is used for `cwd`.
Please note that I also removed the `noProject = true` property, which means that custom commands only work in garden projects now. I couldn't think of any reason why one would define a custom command without a garden project and it also aligns with doc which says
> As part of a Garden project, you can define custom commands
I spent a good 30min thinking how to test this but couldn't figure out any good solution, suggestions welcome. Existing unit tests are defined [here](https://github.com/garden-io/garden/blob/exec-dir/core/test/unit/src/commands/custom.ts)
=> fix(cli): run exec commands from project root

core/src/util/ext-tools.ts
Fixes issues like
```
ENOTEMPTY: directory not empty, rename 
'/github/home/.garden/tools/kubectl/49eb930aa565a80f.1480f616' -> 
'/github/home/.garden/tools/kubectl/49eb930aa565a80f'
```
when fetching plugin tools automatically.
=> fix(core): fixed concurrency issue with plugin tool downloads

core/src/plugins/container/config.ts, docs/reference/module-types/container.md, docs/reference/module-types/helm.md, docs/reference/module-types/jib-container.md, docs/reference/module-types/kubernetes.md, docs/reference/module-types/maven-container.md, examples/build-dependencies/README.md, examples/build-dependencies/backend/Dockerfile, examples/build-dependencies/backend/garden.yml, examples/build-dependencies/backend/main.go, examples/build-dependencies/frontend/app.js, examples/build-dependencies/frontend/garden.yml, examples/build-dependencies/frontend/package-lock.json, examples/build-dependencies/frontend/package.json, examples/build-dependencies/shared-config/config.env, examples/build-dependencies/shared-config/config.json
allow mutagen code sync outside subpath and add dev-mode to the [build dependencies example](https://github.com/garden-io/garden/tree/sync-build-deps/examples/build-dependencies)
=> improvement: allow mutagen code sync outside subpath

docs/reference/module-types/jib-container.md, plugins/jib/index.ts, plugins/jib/openjdk.ts
This PR updates LTS JDK versions (8 and 11) to the latest releases and adds the latest LTS JDK 17 to the list of the supported ones.
Fixes #
* Older non-LTS versions 9, 10, 12-16 are EOL ones, see the [Java version history](https://en.wikipedia.org/wiki/Java_version_history).
* Support of the latest non-LTS JDK 18 was intentionally omitted. An ability to use custom JDK will be implemented in https://github.com/garden-io/garden/issues/3152. This looks like a better alternative to the continuous support of short-term releases.
* OpenJDK binaries [have been moved](https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/) to [Eclipse Adoptium …
=> improvement(jib): updated LTS JDK binaries to the latest releases

core/src/plugins/container/container.ts, core/src/plugins/hadolint/hadolint.ts, core/src/plugins/kubernetes/helm/helm-cli.ts, core/src/plugins/kubernetes/kubectl.ts, core/src/plugins/kubernetes/kubernetes-module/kustomize.ts, core/src/plugins/kubernetes/logs.ts, core/src/plugins/octant/octant.ts, core/src/plugins/openfaas/faas-cli.ts, core/src/util/ext-tools.ts, core/src/util/util.ts, plugins/conftest/index.ts, plugins/jib/gradle.ts, plugins/jib/maven.ts, plugins/jib/openjdk.ts, plugins/pulumi/cli.ts, plugins/terraform/cli.ts
Use M1 native tools where upstream provides official builds.
The idea of this PR is to already download and call native M1 tools where available.
We should actually change our build processes to provide native ARM Garden builds for Linux and MacOS, but this change is simpler and already relieves some pain for tools with ARM incompatibilities (like with terraform, see #3166).
Also in case of Java, users can benefit from faster builds with native execution.
Implements #3166
I gave my best to make sure that all the hashes and instances of the string `arm64`/`aarch64` are correct. I smoke tested using this command:
```
garden tools 2>&1 | grep -E '\[(binary|library)\]' | awk -F' ' …
```
=> feat: use m1 native tools where available

CONTRIBUTING.md, RELEASE_PROCESS.md
This PR extracts release process instructions from `CONTRIBUTING.md` as a standalone guide.
Fixes #
=> docs: moved release process guide to a standalone doc

core/src/config/module.ts, docs/reference/commands.md, docs/reference/module-template-config.md, docs/reference/module-types/configmap.md, docs/reference/module-types/conftest.md, docs/reference/module-types/container.md, docs/reference/module-types/exec.md, docs/reference/module-types/hadolint.md, docs/reference/module-types/helm.md, docs/reference/module-types/jib-container.md, docs/reference/module-types/kubernetes.md, docs/reference/module-types/maven-container.md, docs/reference/module-types/openfaas.md, docs/reference/module-types/persistentvolumeclaim.md, docs/reference/module-types/pulumi.md, docs/reference/module-types/templated.md, docs/reference/module-types/terraform.md
The copy target did not actually default to source, as
stated in the documentation. This commit changes that. Now instead of writing
```
build:
dependencies:
- name: other
copy:
- source: "src"
target: "src"
```
you can actually write
```
build:
dependencies:
- name: other
copy:
- source: "src"
```
without a confusing error message:
```
Error validating Module 'module' (module): key .build.dependencies[0][copy][0][target] is not allowed to be empty
```
Fixes #
=> fix: make copy target actually default to source

docs/reference/module-types/jib-container.md, plugins/jib/index.ts, plugins/jib/util.ts
This PR adds the ability to use a custom JDK distribution with JIB modules.
Fixes #3152
=> improvement(jib): configurable jdk path

core/src/garden.ts, core/src/util/fs.ts, core/test/unit/src/util/fs.ts
This fixes module validation to allow for modules to overlap, if
one of them is disabled. Example use case: one environment deploys
to kubernetes, the other environment deploys to a serverless env.
This also changes the error message: The goal was to make clear that
there are two ways to get rid of the error if the overlap is intentional.
Fixes #
=> feat: allow module overlap if one or both of them are disabled
