garden-io/garden

- .circleci/config.yml
We've started getting complaints from users that they're being spammed with release notifications for every edge release.
For the time being, we'll disable edge releasees on merges to master. We may re-enable them once we've had a closer look and found a way to do this in a less noisy way.
> chore: disable edge releases on master

- .circleci/config.yml
- core/src/build-staging/rsync.ts
- core/src/vcs/vcs.ts
This PR fixes the regex patterns for `git` and `rsync` version checks. The previous pattern was not accurate enough. Fow Windows output it grabbed the whole version like `2.37.0.windows.1` instead of semver-only sub-part like `2.37.0`.
Now it's fixed. The relevant error message was not informative enough. The error handling will be fixed in a separate PR.
This PR also ensures that `git` and `rsync` are installed and up-to-date in `test-macos` and `test-windows` steps of the CircleCI pipeline.
Fixes #
> fix: ensure semver format in git/rsync version regex

- core/src/cli/cli.ts
- core/test/unit/src/cli/cli.ts
Fixes https://github.com/garden-io/garden/issues/3256
Tiny simplifications to `cli.ts` help handling while at it.
Slightly more correct return values for nonexistent commands even with `-h` passed.
```
garden cloud
USAGE
garden cloud <command> [options]
COMMANDS
cloud groups   List groups.
cloud secrets  List, create, and delete secrets.
cloud users    List, create, and delete users.
```
```
garden cloud users
USAGE
garden cloud <command> [options]
COMMANDS
cloud groups   List groups.
cloud secrets  List, create, and delete secrets.
cloud users    List, create, and delete users.
```
| command                         | return |
| ------------------------------- | ------ |
| garden; echo $?;                | 0      |
| garden help; echo $?;           | 0      |
| garden -h; echo $?; …
> fix: subcommand help listing

- .tool-versions
- CONTRIBUTING.md
- docs/README.md
- scripts/install-asdf-dependencies.sh
- chore: add install-asdf-dependencies.sh script
- docs: update linux development documentation
Updates the contribution docs to note that the provided scripts work when using Linux Brew, and adds a second script for dev setup that uses the tool [asdf](https://asdf-vm.com/) to manage several of the tool versions via the `.tool-versions` config file, which I would propose is a much easier method of dealing with tool versions during development and makes it much easier to swap out versions of the tools.
> Linux Dev Env Setup and asdf-based dev setup script

- docs/reference/providers/pulumi.md
- docs/reference/providers/terraform.md
- plugins/pulumi/config.ts
- plugins/terraform/index.ts
This PR improves the version validation for Terraform and Pulumi plugins. The validation is now more strict, and the error messages are more informative.
**Before:**
```
Failed resolving provider terraform. Here is the output:
Unsupported Terraform version: 0.13.0
Failed resolving one or more providers:
- terraform
```
**After:**
```
Failed resolving provider terraform. Here is the output:
Error validating provider configuration: key .version must be one of [0.12.26, 0.13.3, 0.14.7, 1.0.5, 1.2.9, null] …
```
> Stricter validation

- core/src/plugins/container/config.ts
- docs/guides/running-service-in-local-mode.md
- docs/reference/module-types/container.md
- docs/reference/module-types/jib-container.md
- docs/reference/module-types/maven-container.md
This PR updated the local mode guide and module reference docs to explicitly note the experimental status of the local mode feature.
Caused by #3271.
Fixes #
> docs: noted experimental status of the local mode feature in the docs

- core/src/commands/update-remote/all.ts
- core/src/commands/update-remote/helpers.ts
- core/src/commands/update-remote/modules.ts
- core/src/commands/update-remote/sources.ts
- docs/reference/commands.md
The `--parallel` flag of the `garden update-remote sources` sub-command was not defined properly. This PR fixes that issue.
This patches #3206.
Fixes #3269
> Fixed `--parallel` flag implementation in `garden update-remote sources` sub-command

- core/src/commands/deploy.ts
- core/src/commands/test.ts
- docs/reference/commands.md
It looks like the alias name cannot contain any dash characters (`-`).
So, the `--no-deps` alias for `--skip-dependencies` hasn't been working properly since the `0.12.34` - the release when the `--skip-dependencies` flag was introduced.
This PR fixes the issue by replacing `--no-deps` alias with `--nodeps`.
Fixes #3275
Formally, it's a breaking change. But, in fact, it is not, because the old flag's alias hasn't been working properly for a long time.
> fix(cli): fixed alias of `--skip-dependencies` flag in garden commands

- core/src/server/server.ts
Previously we were exiting early from the websocket connection handler if the server wasn't ready but not terminating the actual connection.
This meant that a client could be connected but websocket messages were otherwise not handled.
Now we simply terminate the connection so that clients can retry.
Fixes #
> fix(server): terminate ws connection if server not ready

- core/src/commands/cloud/users/users-create.ts
I required field for the request payload was missing so the command would fail.
This is just a quick fix that adds the field, but in general we need to:
- Update the api-types package
- Consider using the api client that ships with it
- Ensure we're testing Core and Cloud across versions
Fixes #
> fix(cloud): quick fix the "cloud create user" command

- core/src/plugins/exec/exec.ts
We now stream build, deploy, test, task and service logs for `exec` modules.
This brings the Cloud logging experience for `exec` modules to full parity with our k8s-based module types.
I've verified that build, test, deploy, task and service log events are emitted, and that they show up in the logging UI in Cloud.
Would be nice to have proper automated testing for the end-to-end flow here, but since this log event emission logic is rarely changed after its initial implementation, it may not be worth the effort right now.
> feat(exec): live log streaming for exec modules

- core/src/template-string/functions.ts
- core/test/unit/src/template-string.ts
This PR allows using empty string (`""`) as a separator in the `join helper function in the template strings.
Without this PR Garden fails with an error like this:
```
Invalid template string (${join(["a", "b"], "")}): Error validating argument 'separator' for join helper function: value is not allowed to be empty
```
Fixes #
> improvement(template): allow empty string separator in `join` function

- core/src/template-string/template-string.ts
- core/test/unit/src/template-string.ts
- docs/using-garden/variables-and-templating.md
This PR allows using `+` operator for string concatenation in template strings.
Without this PR Garden fails with an error like this:
```
Invalid template string (${"a" + "b"}): Both terms need to be either arrays or numbers for + operator (got string and string).
```
Fixes #
> improvement(template): support string concatenation with `+` operator

- core/src/template-string/functions.ts
- core/test/unit/src/template-string.ts
- docs/reference/template-strings/functions.md
- docs/using-garden/variables-and-templating.md
This PR allows using the `concat` helper function to concatenate strings, and not only arrays.
Fixes #
> improvement(template): string concatenation with `concat` function

- core/src/template-string/functions.ts
- core/test/unit/src/template-string.ts
This PR supports numeric indices in the `slice` helper function.
Fixes #3248
> fix(template): support numeric indices in `slice` function

- core/src/plugins/kubernetes/config.ts
- core/src/plugins/kubernetes/container/build/buildkit.ts
- core/test/unit/src/plugins/kubernetes/container/build/buildkit.ts
- docs/reference/providers/kubernetes.md
- docs/reference/providers/local-kubernetes.md
While most self-hosted registries do support buildkits mode=max,
harbor doesnt and so we can't use mode=max as a default unless we find
a way to autodetect the support for an unknown registry.
Fixes #3279
> fix(k8s): use mode=inline for buildkit in-cluster builder as default

- core/src/plugins/kubernetes/run.ts
- core/src/plugins/kubernetes/status/pod.ts
- core/src/tasks/test.ts
This PR unifies error handling for `garden run` and `garden test` commands when running those with and without artifacts.
Partially resolves #3297
> improvement(logs): run and test commands error handling

- core/src/actions/build.ts
- core/src/build-staging/build-staging.ts
- core/src/commands/get/get-modules.ts
- core/src/commands/publish.ts
- core/src/plugin/handlers/build/publish.ts
- core/src/plugins/exec/exec.ts
- core/src/tasks/base.ts
- core/src/tasks/publish.ts
- core/src/types/module.ts
- core/test/unit/src/commands/publish.ts
- core/test/unit/src/plugins/exec/exec.ts
Fixes all but one tests for the publish command. The one remaining tests fails due to I bug in the solver I think?
Currently no builds are being triggered by the publish task. I'm not sure if that's a deliberate change or not.
Also removed build metadata logic.
> Fix publish tests

- core/src/plugins/kubernetes/container/build/buildkit.ts
- images/buildkit/Dockerfile
- images/buildkit/garden.yml
Updates the buildkit image to use v0.10.5.
Fixes #
> improvement(k8s): bump buildkit image to v0.10.5

- core/src/plugins/kubernetes/container/build/common.ts
- core/src/plugins/kubernetes/hot-reload/helpers.ts
- core/test/unit/src/plugins/kubernetes/hot-reload.ts
- static/kubernetes/system/build-sync/templates/deployment.yaml
Add a preStop command for rsync containers to make sure that an ongoing
rsync is not interrupted (or at least make it unlikely, as transfers
usually are quicker than 30 seconds)
Fixes #
> fix(k8s): add preStop command for rsync containers

- core/src/plugins/container/config.ts
- core/src/plugins/kubernetes/container/util.ts
- core/test/unit/src/plugins/kubernetes/container/util.ts
- docs/reference/module-types/container.md
- docs/reference/module-types/jib-container.md
- docs/reference/module-types/maven-container.md
closes #3337
If the max value of memory or cpu under the container service is set to
null, no resource limit will be set. If they are NOT set to anything at
all (undefined), a default value is used like before.
> feat: allow to set no resource limits

- core/src/plugins/container/helpers.ts
- core/test/unit/src/plugins/container/helpers.ts
Fixes bug in auto-resolve logic for includes running on multi-stage Dockerfiles that has multiple arguments for COPY command.
`autoResolveIncludes` logic was relying on having just one argument in ADD or COPY commands, and therefore filtering was done based only on the first argument (args[0]).
However, there are cases when both `--chown` and `--from` arguments can be used for COPY command (in multi-stage builds), and in such case Garden would handle includes successfully only if `--from` was the first argument. For cases when it's not, e.g. `COPY --chown=bla --from=bla file-b file-c`, existing logic would try to use `--from=bla` as an include parameter and fail with a cryptic message:
```
Error validating configure …
```
> fix: fixed autoResolveIncludes for multi-stage dockerfiles

- core/src/plugins/container/helpers.ts
- core/test/unit/src/plugins/container/helpers.ts
This fixes the `autoResolveIncludes` function so it ignores
all unknown ADD/COPY flags. That way users do not receive
strange looking error messages like
```
Error validating configure container output from provider kubernetes:
key .moduleConfig.include[2] must be a relative sub-path (may not contain '..' segments or be an absolute path)
```
This improves further upon the bug fix in #3354
Thanks again to @ivanbabenko to bring this up.
Fixes #
> fix(autoResolve): handle unknown Dockerfile flags

- core/src/plugins/kubernetes/config.ts
- core/src/plugins/kubernetes/container/build/buildkit.ts
- core/src/plugins/kubernetes/container/build/common.ts
- core/src/plugins/kubernetes/container/build/kaniko.ts
- core/src/plugins/kubernetes/container/util.ts
- core/test/unit/src/plugins/kubernetes/container/build/common.ts
- docs/reference/providers/kubernetes.md
- docs/reference/providers/local-kubernetes.md
closes #3197
Now custom resource limits and requests and tolerations can be set for the `garden-util` pod. See schema changes in the file diff.
> Separate resource and toleration configuration for garden-util pod

- docs/reference/module-types/jib-container.md
- plugins/jib/index.ts
- plugins/jib/mavend.ts
- plugins/jib/util.ts
Added one more build option in `type:jib-container` to use [Mavend](https://github.com/apache/maven-mvnd#introduction) for faster build processes of maven projects.
User can now use `mavend` to specify in `projectType` for `jib-container` modules.
Eg.
```
kind: Module
type: jib-container
name: spring-boot
build:
projectType: mavend
```
This is useful for maven based projects and aims at providing faster Maven builds, when using jib container module.
> feat(jib-container): add maven daemon support as project type

- core/src/plugins/kubernetes/config.ts
- core/src/plugins/kubernetes/container/build/buildkit.ts
- core/src/plugins/kubernetes/container/build/common.ts
- core/src/plugins/kubernetes/container/build/kaniko.ts
- core/src/plugins/kubernetes/status/status.ts
- core/test/integ/src/plugins/kubernetes/container/build/buildkit.ts
- core/test/unit/src/plugins/kubernetes/container/build/buildkit.ts
- core/test/unit/src/plugins/kubernetes/container/build/common.ts
- core/test/unit/src/plugins/kubernetes/container/build/kaniko.ts
- docs/reference/providers/kubernetes.md
- docs/reference/providers/local-kubernetes.md
Allow specifying custom annotations for garden-
managed pods when using in-cluster building with
buildkit or kaniko.
This is useful when users want to alter how certain
components, like the cluster-autoscaler treat these
pods.
Fixes #2628
> feat(k8s): custom annotations for builder pods

- core/src/plugins/kubernetes/constants.ts
- core/src/plugins/kubernetes/container/build/buildkit.ts
- core/src/plugins/kubernetes/util.ts
- images/buildkit/Dockerfile
- images/buildkit/garden.yml
- images/docker-dind/Dockerfile
- images/docker-dind/garden.yml
- images/k8s-util/Dockerfile
- images/k8s-util/garden.yml
- images/skopeo/Dockerfile
- images/skopeo/garden.yml
- static/kubernetes/system/docker-daemon/values.yaml
- static/kubernetes/system/util/values.yaml
amazon-ecr-credential-helper version 0.4.0 has no imdsv2
support (instance metadata service v2). AWS recmmends
disabling imdsv1 for security reasons, so EKS clusters
that follow this recommendation aren't usable with some
garden features anymore.
This PR updates amazon-ecr-credential-helper to 0.6.0 as
imdsv2 support has been introduced in 0.5.0
Fixes #3368
> fix(k8s): update ecr-cred-helper for imdsv2 support

- core/src/plugins/kubernetes/status/workload.ts
getRolloutStatus got stuck in an endless loop waiting for
1 replica when Deployment had zero desired replicas.
Fix was checking for undefined explicitly.
Fixes #3377
Fixes #
> fix(k8s): make getRolloutStatus work with 0 replicas

- support/aws-gcloud-azure.Dockerfile
- support/azure.Dockerfile
Helps with bumping the version of `kubelogin` binary used in Azure based images
Fixes #
happy to pair and test locally.
> chore(update): update kubelogin version to v0.0.24

- core/package.json
- core/src/plugins/kubernetes/api.ts
- yarn.lock
Fixes the regression in local Docker Desktop Kubernetes introduced in https://github.com/garden-io/garden/pull/3374 due to some adverse interaction with the DNS caching library we used.
Replaces the need to revert the changes with https://github.com/garden-io/garden/pull/3387
The `dns-lookup-cache` library has its latest commit at nearly 3 years ago, so we should remove it anyway. If we absolutely need a DNS caching solution, we should figure out an alternative.
> chore: remove dns-lookup-cache

- core/src/plugins/kubernetes/logs.ts
Fixes an issue introduced in https://github.com/garden-io/garden/pull/3374 where each time garden attempts to follow logs from newly deployed service about 20-200 lines of debug level logs are printed with the same message.
The logic is meant to retry the connection until it succeeds and it doesn't make sense to log the generic http error as it means the pod is just not up yet.
Before the kubernetes client library update there was a separate callback for connection failed, now it's all the same promise rejection so it has to be handled separately.
> fix: do not log failed log connection attempt

- core/src/plugins/kubernetes/config.ts
- core/src/plugins/kubernetes/container/build/common.ts
- core/test/unit/src/plugins/kubernetes/container/build/common.ts
- docs/reference/providers/kubernetes.md
- docs/reference/providers/local-kubernetes.md
Enables customizing `nodeSelector` requirements for the `garden-util` pods when using `kaniko` in kubernetes.
Fixes #
Taking inspiration from https://github.com/garden-io/garden/pull/3365.
This is currently implemented on top of existing code. This means that we configure `nodeSelector` for the `util` manifests in the `common.ts` file, even if we only expose the configuration options under `kaniko.util` specifically. If we want to, we can later refactor this, for example move the configuration logic to `kaniko.ts` specifically, or keep the configuration reading logic in `common.ts` and move the `util` configurations upwards in the configmap, or something else.
I've also verified …
> feat(k8s): custom nodeSelector for util pods

- .circleci/config.yml
This enhances the cleanup routines for the shared ci cluster so
we actually remove namespaces that are older than 1h additionally to
the current build namespaces.
These old namespaces can pile up because the cleanup commands will not be executed by circleci, despite `when: always`. We often have auto-cancelled jobs when developer pushes a new commit while the workflows are still running.
Fixes #
> ci(gke): clean up old namespaces

- core/src/config-store.ts
- core/test/unit/src/config-store.ts
Previously the ConfigStore class would throw if attempting to delete an entry with a key that doesn't exist.
So e.g. running delete twice on the same key would fail the second time.
I'm 99.9% sure this that is just a mistake that was made years ago and hasn't surfaced before.
This fix is needed to handle a test error on a different branch.
Fixes #
> fix(framework): idempotent config store deletes

- core/src/constants.ts
- core/src/logger/writers/fancy-terminal-writer.ts
This fixes a massive paper cut where the spinner would be rendered out of whack and the terminal scrollback buffer would contain duplicate entries. 
Before this fix, the spinner would be out of place (top left corner) if the entry it belongs to is outside of the terminal viewport.
Furthermore, updating entries outside of the terminal viewport would cause some log lines to be rendered twice. This was only visible when scrolling back.
The commit also adds an env var which allows users to fallback to the previous render logic. Terminals are fickle beings and it feels good to have an escape hatch if this breaks, say, tmux on WSL.
We can remove the env var later if there are no complaints.
Fixes #
**Special notes for …
> fix(logger): fix issues with spinner and duplicated entries

- core/src/logger/writers/fancy-terminal-writer.ts
Fixes an edge case bug where the fancy logger used ansi escape codes to erase new entries that where much longer then the full terminal viewport.
Now we explicitly ensure that new lines get rendered at the bottom of the terminal without any ansi escape tricks.
Fixes #
> fix(logger): ensure fancy logger doesn't erease new entries

- core/src/analytics/analytics.ts
- core/src/cli/helpers.ts
- core/src/config-store.ts
- core/test/helpers.ts
- core/test/unit/src/analytics/analytics.ts
- core/test/unit/src/cli/cli.ts
This commit adds a 'isRecurringUser' field to the analytics event payload.
I also used the chance to refactor some of the code since it was quite old and had become difficult to maintain and test. Namely:
- Have the factory function initialize the class as opposed to running it after initialisation.
- Simplify the logic around initializing and saving the config.
- Rename types and remove unneeded type casts.
- Add more tests.
Fixes #
> chore(core): add 'isRecurringUser' to analytics payload + refactor

- core/src/plugins/kubernetes/api.ts
- core/src/plugins/kubernetes/run.ts
- core/test/integ/src/plugins/kubernetes/run.ts
* Refactored error handling and log retrieval for `garden run` and `garden test` commands.
* Aligned error code handling for running tests with and without artifacts.
* Extracted a number of helper functions to avoid too long function bodies
See individual commits for more details.
Fixes #3330.
This should partially resolve the issues reported in #3330. The error messages now are more structured and should be more informative. However, mappings between K8s errors and suggested solutions haven't been implemented yet. It's expected to be done in #3254.
Partially resolves #3297.
This PR also fixes flaky-tests like [this](https://app.circleci.com/pipelines/github/garden-io/garden/13888/workflows/f3ae8d4e-48f3-4bc3-a604-7 …
> improvement(k8s): better error handling and logging in `PodRunner`

- core/src/cli/cli.ts
- core/src/cloud/api.ts
- core/src/cloud/get-secrets.ts
- core/src/commands/login.ts
- core/src/commands/logout.ts
- core/src/constants.ts
- core/src/garden.ts
- core/test/data/test-projects/login/has-domain/garden.yml
- core/test/data/test-projects/login/missing-domain/garden.yml
- core/test/data/test-projects/login/secret-in-project-variables/garden.yml
- core/test/helpers.ts
- core/test/integ/src/plugins/kubernetes/helm/deployment.ts
- core/test/unit/src/analytics/analytics.ts
- core/test/unit/src/commands/login.ts
- core/test/unit/src/commands/logout.ts
The cloud API required both a `domain` and a `projectId` to be initialised. This PR removes the requirement of a `projectId` which makes it possible to implement new cloud commands that does not need a `projectId`. An example would be a command to create garden cloud projects.
A new environment variable `GARDEN_CLOUD_DOMAIN` is introduced that makes it possible to override a cloud domain configured in the project for easier configuration/testing.
Fixes #
> improvement: decoupled the cloud api login from project configuration and verification

- core/src/plugins/kubernetes/api.ts
- core/src/plugins/kubernetes/run.ts
This patches https://github.com/garden-io/garden/pull/3388. If the method `PodRunner.exec()` throws an error, then the error's `detail` field must contain the `result` field to ensure the proper error handling in [`skopeoBuildStatus`](https://github.com/garden-io/garden/blob/main/core/src/plugins/kubernetes/container/build/common.ts#L198) function.
Fixes #
> fix(k8s): fixed error detail format in `PodRunner.exec()`

- core/src/server/server.ts
- core/test/unit/src/server/server.ts
These better websocket close / ready messages are helpful for Cloud (and future clients) when handling websocket connections.
Fixes #
> fix(server): send better close codes on ws connection close

- docs/using-garden/variables-and-templating.md
Clarifies the documentation on the `varfile` field, to make it match the expected behavior and current code implementation.
Fixes #3150 
Relevant code at https://github.com/garden-io/garden/blob/35fdae0560536b3480e05b50766d635a941e52d5/core/src/config/base.ts#L243-L302
> chore: clarify documentation on varfiles

- core/src/plugins/container/container.ts
- core/src/plugins/exec/exec.ts
- core/src/plugins/kubernetes/kubernetes.ts
- core/src/plugins/kubernetes/task-results.ts
- docs/reference/module-types/helm.md
- docs/reference/module-types/kubernetes.md
Adds the `joi` schema for `runtime.tasks.<task-name>.outputs.log` for both `helm` and `kubernetes` module types.
The necessary code for passing the logs already exists for both [helm](https://github.com/garden-io/garden/blob/7ba352815890ebcf727ae5731dd06bd3599aa866/core/src/plugins/kubernetes/helm/run.ts#L185) as well as [kubernetes](https://github.com/garden-io/garden/blob/7ba352815890ebcf727ae5731dd06bd3599aa866/core/src/plugins/kubernetes/kubernetes-module/run.ts#L73), but they were not documented correctly.
Fixes #3378 
> chore: add runtime.tasks.<task-name>.outputs.log schema to helm and kubernetes modules

- core/src/plugins/kubernetes/api.ts
Removes the https agent in kubernetes `api.ts`.
The request library now picks the protocol automatically - previously this required the use of `https` protocol.
This agent and its use and removal has some interactions with other recent PRs as well. The global agent initialization used to be forced before #3374. After the PR, the local `https` agent created in this `api.ts` was used instead of a global one, and required the use of `https` protocol. This regressed the ability to use `http` endpoints for kubernetes.
The original reason for using the local agent here was to provide a dns lookup cache for it with the use of `dns-lookup-cache` library, but that was removed in #3389. Thus, there is no reason to keep this local agent anymore and it can be …
> fix: kubernetes endpoints over plain http

- core/src/cli/cli.ts
- core/src/logger/renderers.ts
- core/src/logger/util.ts
- core/src/plugins/container/build.ts
- core/src/plugins/exec/exec.ts
- core/src/plugins/kubernetes/container/build/buildkit.ts
- core/src/plugins/kubernetes/container/build/cluster-docker.ts
- core/src/plugins/kubernetes/container/build/kaniko.ts
- core/src/plugins/kubernetes/container/deployment.ts
- core/src/tasks/deploy.ts
- core/src/util/util.ts
- core/test/unit/src/logger/renderers.ts
From the commit message:
Before this fix, basic logger entries would regularly be 'orphaned'
because the parent section wasn't printed. This made it very hard to
tell what section a given log entry would belong to.
E.g. when the log level is set to verbose, it's hard to tell if build
logs belong to one module or the other.
Furthermore, the commit also:
- Prints the name of the command when rendering output streams.
- Ensures the header isn't rendered twice with the basic logger.
- Removes superfluous arrows from some log strings which don't render
nicely with the basic logger.
- Prints the log level if using the basic logger and the level is higher
than 'info'.
- Skip left padding for basic logger.
Partially address …
> Better basic logger

- docs/reference/module-types/jib-container.md
- plugins/jib/gradle.ts
- plugins/jib/index.ts
- plugins/jib/maven.ts
- plugins/jib/util.ts
This PR adds an option to make the `gradle` binary path configurable.
A similar change was done for `maven` in #3173.
There is a lot of code duplication in [`maven.ts`](https://github.com/garden-io/garden/blob/improvement/configurable-gradle-binary/plugins/jib/maven.ts) and [`gradle.ts`](https://github.com/garden-io/garden/blob/improvement/configurable-gradle-binary/plugins/jib/gradle.ts). Those parts will be refactored in a separate PR.
> improvement(jib): configurable gradle binary

- core/src/plugins/kubernetes/dev-mode.ts
- core/src/util/enumerate.ts
- core/test/unit/src/plugins/kubernetes/dev-mode.ts
- core/test/unit/src/util/enumerate.ts
Patch for #3145.
As a bonus track, it introduces a new [helper function](https://github.com/garden-io/garden/pull/3447/commits/048f8ea31a875300a380960db6b7f9dcb81ece62) - an analog of the [Pythonic `enumerate`](https://docs.python.org/3/library/functions.html#enumerate).
Fixes the [Mutagen file sync in devMode using absolute paths appears to not be working](https://discord.com/channels/817392104711651328/1051879220789399612) issue from our public Discord.
> fix(dev-mode): proper support of absolute source paths

- core/src/actions/base.ts
- core/src/graph/config-graph.ts
- core/src/tasks/helpers.ts
- core/src/util/testing.ts
- core/test/unit/src/tasks/deploy.ts
- core/test/unit/src/tasks/get-service-status.ts
- core/test/unit/src/tasks/helpers.ts
- core/test/unit/src/tasks/run.ts
- core/test/unit/src/tasks/test.ts
This pr fixes a few bugs in core itself and a bunch of task tests. 4 tests are still not passing. Two due to template strings not quite working yet and two due to the test plugin bugs that will hopefully be fixed via https://github.com/garden-io/garden/pull/3351
> Sgv2 fix most of tasks tests

- core/src/tasks/resolve-provider.ts
- core/test/data/exec-provider-cache/.gitignore
- core/test/data/exec-provider-cache/project.garden.yml
- core/test/integ/src/plugins/exec/resolve.ts
- plugins/terraform/commands.ts
When users change environments, we need to re-initialize providers.
Let's consider the following example:
User has a provider config like so:
```
providers:
- name: exec
initScript: echo ${environment.name} > someFile
```
If user runs a garden command with --env foo, and then with --env bar,
and then again with --env foo we would expect `someFile` to contain `foo`. But
the file actually contains bar.
Reason for this is that garden skipped executing the initScript in the foo env,
because it has already been executed. But the cache logic is not aware that the
last command that ran was in the bar env.
This commit fixes that problem.
Fixes #
> fix: re-initialize providers changing environments

- core/test/integ/src/plugins/kubernetes/commands/pull-image.ts
Disables image pull tests for in-cluster image registry.
The in-cluster image registry is deprecated and removed in 0.13 anyway, and these tests are incredibly flaky and a major(ity?) chunk of our CI failures.
This solution is not ideal, but neither is our CI pipeline failing most of its runs.
Let's not let perfect be the enemy of good here.
> chore(ci): remove in cluster image pull tests as too flaky

- cli/src/build-pkg.ts
- support/alpine-builder.Dockerfile
This is a cheap improvement enabled by a compression feature in pkg.
pkg docs suggest this would generally improve startup time but in my manual testing I could find no meaningful changes on that front in either direction, but that's all good.
> improvement(cli): trim binary size by approx 1/3

- core/src/tasks/resolve-provider.ts
- core/test/data/exec-provider-cache/.gitignore
- core/test/data/exec-provider-cache/project.garden.yml
- core/test/integ/src/plugins/exec/resolve.ts
- plugins/terraform/commands.ts
* fix: re-initialize providers changing environments
When users change environments, we need to re-initialize providers.
Let's consider the following example:
User has a provider config like so:
```
providers:
- name: exec
initScript: echo ${environment.name} > someFile
```
If user runs a garden command with --env foo, and then with --env bar,
and then again with --env foo we would expect `someFile` to contain `foo`. But
the file actually contains bar.
Reason for this is that garden skipped executing the initScript in the foo env,
because it has already been executed. But the cache logic is not aware that the
last command that ran was in the bar env.
This commit fixes that problem.
* improvement: remove unnecessary check for env name
Reasoning is that when the env name changes and that is …
> port fix: re-initialize providers changing environments (#3481)

- core/src/plugins/kubernetes/helm/config.ts
- core/test/integ/src/plugins/kubernetes/helm/common.ts
Relaxes the path validation requirements for `valueFiles` field in helm modules.
Fixes https://github.com/garden-io/garden/issues/3367
Introduces https://github.com/garden-io/garden/issues/3487
Based on internal conversations, we're essentially trading issues here: allow users to specify the valueFiles in a bit more flexible manner to unblock them, while introducing the slight risk of possible version/cache invalidation issues.
> chore(helm): relax path validation requirements for valueFiles

- plugins/pulumi/handlers.ts
tiny cleanup, the `serviceStatus` block below handles the same case in the same way.
found this while reading through the code when debugging https://github.com/garden-io/garden/issues/3468 and thought might as well remove it, even if it doesn't really matter. we can also let it be, if we prefer.
> refactor(pulumi): remove dead code

- plugins/jib/index.ts
Fixes the `mvnd` support for jib module type that was initially implemented in #3361.
The feature was accidentally broken while merging `main` into `0.13` (see https://github.com/garden-io/garden/commit/5f2a54afe5ade93553bd19ea17f2b02c76b47274#diff-b3bbd18a1db370349e20a629ca82693b5349d847b24cf167d6ca726406160f8b, https://github.com/garden-io/garden/commit/f433568fe82e98dbd01bd4f54361e29145cc7646#diff-b3bbd18a1db370349e20a629ca82693b5349d847b24cf167d6ca726406160f8b, and https://github.com/garden-io/garden/commit/db432a464670c34a1d53fe5b822e5cac51772f05)
> fix(jib): fixed broken Maven Daemon support in  0.13

- core/src/plugins/kubernetes/config.ts
- core/src/plugins/kubernetes/integrations/cert-manager.ts
- docs/advanced/cert-manager-integration.md
- docs/reference/providers/kubernetes.md
- docs/reference/providers/local-kubernetes.md
Marking `cert-manager` as deprecated and warning on the use of it.
Related to https://github.com/garden-io/garden/issues/2551 but not closing it.
Let's close it during 0.13 when it will be actually removed.
This has been asked about in the community Discord as well, so we should definitely get these docs up to date.
> chore: mark cert-manager integration as deprecated

- core/test/unit/src/vcs/git.ts
This reverts the test config for `GitHandler`.
Fixes #
See https://github.com/garden-io/garden/pull/3498#discussion_r1072311317 for the details.
> chore(test): reverted test config for `GitHandler`

- core/src/server/server.ts
Previously we were logging websocket ping/pongs at the debug level. A user pointed out that this was adding a lot of noise to their logs. 
This PR removes the logs altogether since they'll add noise at any level. We do log when the connection times out which is based on the ping/pongs and should be enough. 
Fixes #
> chore(server): remove debug logs for ws ping pongs

- core/src/plugin/handlers/deploy/delete.ts
- core/src/types/service.ts
- core/test/unit/src/plugins/exec/exec.ts
Fixes some tests in `plugins/exec/exec.ts`.
Partially addresses #3549 
Please check the new `TODO-G2` comments.
> 0.13 partially fix some `plugins/exec` tests

- core/src/constants.ts
- core/src/plugins/kubernetes/commands/sync.ts
- core/src/plugins/kubernetes/container/build/common.ts
- core/src/plugins/kubernetes/dev-mode.ts
- core/src/plugins/kubernetes/kubernetes.ts
- core/src/plugins/kubernetes/mutagen.ts
- core/test/integ/src/plugins/kubernetes/commands/sync.ts
- core/test/integ/src/plugins/kubernetes/dev-mode.ts
This commit adds Kubernetes plugin commands for getting the Mutagen sync status, pausing syncs, and resuming syncs.
I also refactored the Mutagen code to use a class which makes it a little easier to manage some of the daemon process life cycle logic.
The class is currently a singleton but should be refactored after v0.13 into a "normal" class that we can attach to the `garden` instance.
Finally, the new MutagenDaemon class also logs more information about what Mutagen is doing under the hood. This is e.g. useful when Mutagen is syncing large change sets because without the added logs it looks like nothing is happening.
Fixes #
> feat(kubernetes): add sync helper commands

- core/src/actions.ts
- core/src/commands/logs.ts
- core/src/plugin-context.ts
- core/src/plugins/container/build.ts
- core/src/plugins/exec/exec.ts
- core/src/plugins/kubernetes/container/build/buildkit.ts
- core/src/plugins/kubernetes/container/build/cluster-docker.ts
- core/src/plugins/kubernetes/container/build/kaniko.ts
- core/src/plugins/kubernetes/helm/run.ts
- core/src/plugins/kubernetes/run.ts
- core/src/plugins/kubernetes/status/status.ts
- core/src/util/ext-tools.ts
- plugins/jib/index.ts
This commit makes it harder to forget sending verbose logs (mostly tool
output) to both Garden Cloud and to the CLI logs.
To accomplish that, this commit
1. Fixed the type assertions in the PluginEventBroker. Now typescript
will actually verify the types for the events in `emit` and in `on`
etc.
2. Added two additional parameters to the `log` event, origin and log.
Log is supposed to be a LogEntry placeholder with verbose log level.
3. Make sure that we use the `ctx.events.emit` in the plugin
implementations to stream logs to Garden Cloud and CLI
Fixes #3331
Difference for `garden test --force -l3` before and after the change:
```diff
--- before.log	2023-01-24 19:01:51
+++ …
```
> fix(framework): increase consistency in verbose plugin logs

- core/src/garden.ts
- core/src/graph/config-graph.ts
- core/src/graph/nodes.ts
- core/src/graph/results.ts
- core/src/graph/solver.ts
- core/src/tasks/base.ts
- core/src/tasks/build.ts
- core/src/tasks/resolve-action.ts
- core/src/types/namespace.ts
- core/test/helpers.ts
- core/test/unit/src/commands/build.ts
- core/test/unit/src/commands/deploy.ts
- core/test/unit/src/router/base.ts
All BuildCommand tests now pass, and disabled Build actions are now handled as before.
> fix(core): issues with disabled actions and BuildCommand tests

- core/src/commands/deploy.ts
- core/src/commands/dev.ts
- core/src/commands/helpers.ts
- core/test/unit/src/commands/deploy.ts
- core/test/unit/src/commands/dev.ts
- docs/reference/commands.md
This is an experimental behaviour that allows users to disable watching while in dev mode.
Note that this refers to Garden's watching, Mutagen syncs still work.
This behaviour will change in a future release where we'll make the whole watch mechanism smarter and more consistent.
Fixes #
> feat(commands): allow disabling watch in dev mode

- core/src/events.ts
- core/src/plugin-context.ts
- core/src/plugins/kubernetes/run.ts
This essentially reverts a change that was made in https://github.com/garden-io/garden/pull/3576
(commit: b52e9b298f7c59b8210a77edc4c451301daa76e3).
The type has always been 'number' but we were in fact sending strings to Garden Cloud which is the payload it expects.
Garden Cloud (version >= 1.360) now supports numbers but we need to continue sending strings for backwards compatibility.
We can tighten the type to just 'number' once all Cloud instances are up to date.
Fixes #
> fix(events): update log event timestamp type be string or number

- core/src/events.ts
- core/src/server/server.ts
- core/test/unit/src/server/server.ts
This event was introduced awhile ago but isn't used by any client at the moment.
It was made into its own event type by mistake, it should've just been a normal event with the name 'serverReady'. This fixes that.
Fixes #
> improvement(server): ensure serverReady event has correct type

- core/src/commands/run.ts
Field `graphResults: graphResultsSchema()` is already defined in `processCommandResultSchema`.
Fixes #
> refactor: remove unnecessary schema field definition

- core/src/plugins/kubernetes/commands/cluster-init.ts
- core/src/plugins/kubernetes/commands/uninstall-garden-services.ts
- core/src/plugins/kubernetes/helm/build.ts
- core/src/plugins/kubernetes/helm/common.ts
- core/src/plugins/kubernetes/helm/deployment.ts
- core/src/plugins/kubernetes/helm/helm-cli.ts
- core/src/plugins/kubernetes/helm/run.ts
- core/src/plugins/kubernetes/helm/status.ts
- core/src/plugins/kubernetes/run.ts
Actually stream helm module outputs to CLI and Garden Cloud; the
log context was in the wrong place before.
Fixes #
Difference for `garden deploy --force -l3 --env testing` in `vote-helm` example before and after the change:
```diff
--- before.log	2023-01-25 11:14:34
+++ after.log	2023-01-25 11:15:09
@@ -1,4 +1,4 @@
-$ garden deploy --force -l3 --env testing
+$ gdev deploy --force -l3 --env testing
Deploy 🚀
@@ -14,8 +14,8 @@
ℹ db-init                   → Checking result...
ℹ base-chart [verbose]      → Syncing module sources (8 files)...
ℹ result-image [verbose]    → Syncing module sources (10 files)...
-ℹ vote-image [verbose]      → Syncing module sources (26 files)...
ℹ …
```
> fix(helm): stream logs to CLI and Garden Cloud

- core/src/plugins/kubernetes/run.ts
- core/src/plugins/kubernetes/status/events.ts
- core/src/plugins/kubernetes/status/pod.ts
- core/src/plugins/kubernetes/status/workload.ts
- core/src/plugins/kubernetes/util.ts
Detect that the pod has been killed, in order to
- improve the error message (relates to #3331)
- fix a bug where a test might have been reported as successful while it
actually was killed (Fixes #3535)
This has been extracted from the PR #3537 (to keep it separate and merge
it more quickly)
Fixes #3535
> fix(kubernetes): detect that pod has been killed

- .circleci/config.yml
- images/circleci-runner/garden.yml
I rebuilt and published the circleci-runner image, to include the `gh` cli tool that was added to the Dockerfile since the previous build. I forgot to rebuild and push after merging a newer main where the `gh` changes were added.
Quick fix to the release steps of our CI pipeline.
https://app.circleci.com/pipelines/github/garden-io/garden/14560/workflows/35b906c2-6a29-461f-ba45-7965d5e8cd24/jobs/246450
> chore(ci): rebuild circleci-runner node16 image to have gh cli

- core/src/commands/dev.ts
- core/src/commands/serve.ts
- core/src/config/project.ts
- core/src/garden.ts
- core/test/unit/src/commands/dev.ts
- core/test/unit/src/config/project.ts
- docs/reference/commands.md
For now, the `dev` command implementation is basically that of the `serve` command, with an added "under construction" message to steer users to the `deploy --dev` command.
Later we will add interactivity on top, hopefully before the 0.13 GA.
The behavior of the `garden dev` command is being fully replaced. It will no longer automatically perform all tests and deployments, but instead connect to the new dashboard, and later feature a command input in the terminal.
> refactor: remove old `garden dev` command implementation

- core/test/unit/src/config-graph.ts
This PR implements the missing tests in `config-graph.ts`. The broken tests were fixed in #3596.
The tests are based on the *action-based* configs instead of the module-based ones. The new tests also do not use any predefined Garden test projects from the `test/data` directory.
Fixes #3595
> test: implement missing unit tests for `getAction(s)ByKind`

- core/src/events.ts
Core sometimes dropped events on error, because the detail property was too large.
This PR omits the details event on stack graph results before sending the event payload to Garden Cloud.
Fixes #
> fix(framework): omit detail property of errors for GraphResultEventPayload

- core/src/actions.ts
- core/src/events.ts
- core/src/plugin-context.ts
- core/src/plugins/container/build.ts
- core/src/plugins/exec/exec.ts
- core/src/plugins/kubernetes/container/build/buildkit.ts
- core/src/plugins/kubernetes/container/build/cluster-docker.ts
- core/src/plugins/kubernetes/helm/helm-cli.ts
- core/src/plugins/kubernetes/run.ts
- core/src/plugins/kubernetes/status/status.ts
- core/src/task-graph.ts
- core/src/util/ext-tools.ts
- core/test/unit/src/task-graph.ts
- plugins/jib/index.ts
Previously the event payload type for dates was a JS Date instance. When these events are emitted to other consumers such as Cloud the dates are marshalled to ISO strings.
This commit updates the payload types to strings so that the types reflect what the consumers actually receive and so that the types can be re-used across consumers.
Fixes #
> fix(events): use ISO format date strings in event payload

- scripts/release.ts
- scripts/run-script.ts
- scripts/script-utils.ts
The release script used to import the utility `getPackages` from another script
called `run-script.ts`.
This in turn led to the side effect of `runInPackages` which would run
a script in all packages, if the first argument of release.ts happens to
be a script in that package.
It also led to a confusing error message on release.ts with no params:
```
% ./scripts/release.ts
Error: Must specify script name
```
This error is thrown in `run-scripts.ts`.
This PR moves the utilities to a different package with no side effects
on import.
Fixes #
> chore(scripts): release.ts unintentionally also ran scripts

- plugins/terraform/common.ts
A user was encountering an error when running Garden against a project using the Garden Terraform provider.
More specifically, Garden is supposed to run `terraform init` when a required Terraform provider is missing and we do this by checking the error message returned by the Terraform cli.
It's possible, that in-between releases this error message has changed and we were not running `terraform init` when a provider needed a fresh installation.
Fixes #3325
This is a quick fix for unblocking a user, but theoretically, we'd want to rewrite this logic to be more robust (e.g. does the Terraform cli return machine-readable output and error codes we can parse?).
> fix(terraform): update condition that triggers `terraform init`

- core/src/plugins/kubernetes/logs.ts
- core/src/plugins/kubernetes/run.ts
- core/src/util/util.ts
- core/test/unit/src/util/util.ts
This bug was introduced when we changed `timestamp.getTime()` to `timestamp.toISOString()` in #3576.
Turns out that the former returns `NaN` if the date instance is invalid whereas the latter throws. So this had basically been failing silently until that change was made.
This commit ensures we check for the validity of the date instance.
Fixes #3652 
> fix(logs): ensure invalid dates are handled properly

- .github/workflows/scorecards.yml
This PR should fix errors like [this](https://github.com/garden-io/garden/actions/runs/4073917619).
Fixes #
> ci: updated list of allowed endpoints in the scorecard GH action

- .github/workflows/scorecards.yml
This is the continuation of #3664. The [issue](https://github.com/garden-io/garden/actions/runs/4076470288) still happens, but with different addresses.
This PR changes the `egress-policy` to `audit` to avoid maintenance of the `allowed-endpoints`.
Fixes #
> ci: use audit egress-policy in the scorecard GH action

- core/src/plugins/container/helpers.ts
Previously the cli was attemped to be spawned at path "docker", which doesn't exist, at least on my machine. The bug was introduced [here](https://github.com/garden-io/garden/commit/4c816700db7c1166316f63452f89de918863b4c1#diff-b0ee402f0d037eec73174cc4a8ce543692ed4ae12193f28c8bcfe91b0280868dL257-R257), probably due to the slightly confusing argument which I removed as it's never used. This also fixes all container integ tests. closes #3675
> fix: fix getDockerVersion helper

- core/test/unit/src/commands/link.ts
- core/test/unit/src/commands/unlink.ts
> chore(test): fix link.ts and unlink.ts test assertions

- core/src/config/project.ts
- core/src/garden.ts
- core/src/proxy.ts
- core/test/unit/src/garden.ts
- docs/reference/project-config.md
After upgrading to Node 18, some users reported issues with port forwarding to "localhost" when using Node's `createProxyMiddleware` package.
This appears to be mostly the [expected behaviour in Node 17+](https://github.com/garden-io/garden/issues/3667#issuecomment-1415665510) and previously the only workaround was to set the proxy URL via the `GARDEN_DEFAULT_PROXY_ADDRESS` env var.
This PR adds a `proxy` field to the project config so that user can explicitly set the proxy address for the project without having to ask everyone to update their environment variables:
```yaml
kind: Project
name: <my-project>
proxy:
hostname: 127.0.0.1
```
Fixes #3667
> improvement(framework): allow users to specify proxy hostname in project config

- core/src/cli/params.ts
- core/test/unit/src/cli/cli.ts
- docs/reference/commands.md
The -v CLI flag (alias for --version) has been replaced by -V (upper-case). This is to make way for #3499.
> refactor(cli): make -V instead of -v (lowercase) print Garden version

- core/src/plugins/kubernetes/config.ts
- core/src/plugins/kubernetes/container/build/kaniko.ts
- core/test/data/test-projects/container/garden.yml
- docs/k8s-plugins/advanced/in-cluster-building.md
- docs/reference/providers/kubernetes.md
- docs/reference/providers/local-kubernetes.md
- examples/kaniko/README.md
- examples/kaniko/garden.yml
Closes #3508
The default namespace for kaniko build Pods is now the project namespace. Set `kaniko.namespace` in the provider configuration to override to a specific, separate namespace.
> refactor(k8s): change default kaniko namespace to the project namespace

- core/test/unit/src/util/ext-source-util.ts
Fixes https://github.com/garden-io/garden/issues/3723
I made the distinction between `sourcesObj` and `sourcesList` more explicit, as some of the functions expect a plain list and others expect the object with name-based keys.
This makes the tests on this file pass, however, let me know if this is actually the _intended_ behavior or whether we need to change the underlying code to unify the formats.
> test: fix util/ext-source-util.ts assertions

- core/test/unit/src/cloud/api.ts
Fixes https://github.com/garden-io/garden/issues/3727
The removed test saved an auth token, which breaks the test right below it as it expects a token to not exist yet.
This test was a duplicate anyway: saving and retrieving a token gets tested one test below as well.
> test: fix cloud/api.ts

- core/src/docs/generate.ts
- core/src/garden.ts
- core/src/graph/actions.ts
- core/src/plugins.ts
- core/src/router/base.ts
- core/src/tasks/resolve-action.ts
- core/src/util/util.ts
- core/test/unit/src/garden.ts
This fixes only one failing test, but brings some changes to the existing type system to ensure that some custom [mapped types](https://www.typescriptlang.org/docs/handbook/2/mapped-types.html) can also return optional values, i.e. the ones that can be `undefined`.
For example, let's consider the type
```
export type ActionTypeMap<T> = {
[K in ActionKind]: {
[type: string]: T
}
}
```
When an object of the type above is referenced as `typeMap[kind][type]` it still can return an `undefined` value. The first-level sub-map can to forced to never return `undefined` by explicit initialization of `typeMap` for each `kind` like this: `typeMap[kind] = {}`. But `type` is an arbitrary string here.
If there is a better way or TS best practice to handle …
> 0.13 fix `resolveProviders` spec in garden unit tests

- core/test/unit/src/analytics/analytics.ts
Fixes https://github.com/garden-io/garden/issues/3707
We should probably double-check that all the `optedIn` / `optedOut` logic is correct - the tests pass now, but I would love to have another pair of eyes on them before merging.
> test: fix analytics.ts assertions

- core/src/util/testing.ts
- core/test/unit/src/build-staging/helpers.ts
- core/test/unit/src/cli/cli.ts
- core/test/unit/src/cli/helpers.ts
- core/test/unit/src/commands/create/create-module.ts
- core/test/unit/src/commands/create/create-project.ts
- core/test/unit/src/commands/custom.ts
- core/test/unit/src/commands/login.ts
- core/test/unit/src/commands/logs.ts
- core/test/unit/src/commands/run-workflow.ts
- core/test/unit/src/commands/run.ts
- core/test/unit/src/commands/test.ts
- core/test/unit/src/commands/tools.ts
- core/test/unit/src/config/base.ts
- core/test/unit/src/config/common.ts
- core/test/unit/src/config/project.ts
- core/test/unit/src/config/provider.ts
- core/test/unit/src/config/template-contexts/base.ts
- core/test/unit/src/config/workflow.ts
- core/test/unit/src/template-string.ts
- core/test/unit/src/util/util.ts
- core/test/unit/src/util/validateInstall.ts
- plugins/jib/test/util.ts
More janitorial work to use the benefits of the `expectError` helper function.
The helper function `expectError` was refactored in https://github.com/garden-io/garden/pull/3733/commits/42513956dfd026f29b3e2d598664a7c47b84d667.
Fixes #
Checked all affected tests manually and verified the results.
> test: use `expectError` helper in tests

- core/src/plugins/kubernetes/local-mode.ts
- examples/local-mode/README.md
- examples/local-mode/backend-1/garden.yml
- examples/local-mode/backend-2/garden.yml
- examples/local-mode/frontend/garden.yml
* Some bug fixes in local mode configuration (ssh keys naming)
* Action-based config for `local-mode` example
See individual commits for the details.
Note, the example works well and the apps in local mode are reachable. But, the Garden console gets stuck at build actions for both services. This will be fixed in the next PR(s).
Closes #3750
> 0.13 example local mode

- examples/rust/README.md
- examples/rust/backend/backend.garden.yml
Fixes https://github.com/garden-io/garden/issues/3740
First time converting an example to the new config format.
Is this correct and aligned with the best practices?
> chore(examples): update rust example to use action configs

- core/src/commands/delete.ts
Just a random small thought - maybe some other emoji could be more aligned with our tone and visual style in the cleanup command.
Originally I wanted to use the broom emoji 🧹  but the emoji library we use does not have it available, so I chose the recycling icon instead. Let me know if you have better suggestions or if we should close without merging.
> chore: switch the cleanup command emoji

- core/src/plugins/hadolint/hadolint.ts
Some fixes in `hadolint` plugin.
...and type-safety for all :)
There was some mess with the `Dockerfile` path processing for different kinds and types of actions. A type-safe approach made it better.
Partially addresses #3583
See individual commits for details, it might be simpler to review it commit-by-commit.
> 0.13 fix hadolint plugin

- core/src/config/template-contexts/actions.ts
- core/src/plugins/kubernetes/sync.ts
- docs/reference/action-types/Deploy/helm.md
- docs/reference/action-types/Deploy/kubernetes.md
- examples/vote-helm/vote/garden.yml
Besides fixing an outright schema error that I introduced during a conflict resolution, this adds a missing feature that I'd forgotten to implement which is necessary to support syncing with `helm` and `kubernetes` Deploy actions.
> Fix vote helm example

- .circleci/config.yml
- e2e/test/pre-release.ts
Noticed some namespaces stacking up after CI runs. I think this should do the trick. @stefreak could you take a look?
> chore(ci): fix namespace cleanup

- core/src/cli/cli.ts
- core/src/cloud/api.ts
- core/src/cloud/workflow-lifecycle.ts
- core/src/commands/cloud/secrets/secrets-create.ts
- core/src/commands/cloud/secrets/secrets-list.ts
- core/src/commands/cloud/users/users-list.ts
- core/src/exceptions.ts
- core/src/garden.ts
- core/test/unit/src/commands/login.ts
Improve handling of the case when switching between projects with that uses different cloud API endpoints.
- Continues the command even if the token refresh fails. 
- Clearer error message indicating that a logout is needed before the cloud API can be used for the current project.
Fixes #
> fix(cloud): continue when token refresh fails

- core/src/events.ts
- core/src/graph/solver.ts
- core/src/plugin-context.ts
- core/src/plugins/container/build.ts
- core/src/plugins/exec/exec.ts
- core/src/plugins/kubernetes/container/build/buildkit.ts
- core/src/plugins/kubernetes/helm/helm-cli.ts
- core/src/plugins/kubernetes/logs.ts
- core/src/plugins/kubernetes/run.ts
- core/src/plugins/kubernetes/status/status.ts
- core/src/router/build.ts
- core/src/router/deploy.ts
- core/src/util/ext-tools.ts
- core/src/util/util.ts
- core/test/unit/src/util/util.ts
- plugins/jib/index.ts
Applies the changes from https://github.com/garden-io/garden/pull/3618 and https://github.com/garden-io/garden/pull/3653 on top of 0.13.
This was done by cherry-picking the commits and resolving the resulting conflicts.
> cherry-pick for 0.13: ISO timestamp changes to event payloads

- core/src/cli/params.ts
- core/src/commands/unlink/module.ts
- core/src/commands/unlink/source.ts
Some aliases for CLI options have been permanently removed and are no longer supported:
* `-r` for `--root`
* `-s` for `--silent`
* `-a` for `--all` in `garden unlink module` and `garden unlink source` commands
Fixes #
> refactor(cli): remove some aliases for CLI options

- .circleci/config.yml
What this PR does / why we need it:
For testing edge-bonsai it would be good to build and release container images for use where CI depends on a container image e.g. GitLab CI. Users sourcing the Garden binary as part of a multi-stage Dockerfile strategy should also be pleased with the option to have an edge release available.
> Edge bonsai docker release 0.13

- .circleci/config.yml
Fixes #3868 by increasing filter to include `build-dist-edge-bonsai`. From [CircleCI's reference](https://circleci.com/docs/configuration-reference/#requires):
> A list of jobs that must succeed for the job to start. Note: When jobs in the current workflow that are listed as dependencies are not executed (due to a filter function for example), their requirement as a dependency for other jobs will be ignored by the requires option. However, if all dependencies of a job are filtered, then that job will not be executed either.
> fix: edge-bonsai-docker-release-0.13

- README.md
The old Discord invite link had expired.
This new link should point new members directly to the rules channel, and never expire.
We should edit our website to have this new link as well: https://discord.gg/FrmhuUjFs6
> chore: fix discord invite link

- .circleci/config.yml
This stops git hashes from proliferating in our Docker Hub by removing any step that pushes a git hash. Building is already taken care of by our push-containers.sh scripts which itself calls build-containers.sh.
We want to move to images for clouds (AWS, GCP, etc.) as an image tag for 0.13.  This does not address that. This also tests using `latest` which is not in any way ideal when any number of image builds could be competing for the tag.
> ci: clean-up docker tags

- .github/dependabot.yml
This means more dependabot PRs, and hopefully less manual work keeping Dockerfiles up to date.
In some cases careful testing will be required before merging Docker PRs but at least we have a to-do list in the form of dependabot PRs.
With the npm package ecosystem, dependabot will also start suggesting more NPM updates, and not just the security updates (that's why I limited the number of them until 0.13 has landed).
Fixes #
> ci: add dependabot docker and npm ecosystems

- docs/using-garden/variables-and-templating.md
Cherry-picking https://github.com/garden-io/garden/pull/3851 on 0.13 to fix the `check-docs` CI step
> docs: replace dead link

- core/src/commands/logs.ts
- core/src/plugins/kubernetes/logs.ts
- core/src/plugins/kubernetes/run.ts
- core/src/plugins/kubernetes/util.ts
- core/test/integ/src/plugins/kubernetes/container/logs.ts
- docs/reference/commands.md
Fixes an issue with very high upload bandwidth use when running Kubernetes based tests/tasks that produce a lot of log output.
co-written by @stefreak and @thsig
* Improved connection management and pod lifecycle logic, including more robust connection timeout enforcement.
* Removed keepalive logic, since it doesn't work on all operating systems.
* Improved deduplication logic to generate fewer false positives (and eliminate false-negatives).
* Use `sinceTime` when fetching logs on retry to make sure we don't fetch any unnecessary logs.
* When a runner pod terminates, we make sure to wait until the final logs have been fetched.
* Default to using the `tail` option in conjunction with a "max log lines in memory" setting instead of `limitBytes` to …
> fix(k8s): more stable & performant log streaming

- core/src/actions/build.ts
- core/test/data/test-projects/helm/api copy/.helmignore
- core/test/data/test-projects/helm/api copy/Chart.yaml
- core/test/data/test-projects/helm/api copy/garden.yml
- core/test/data/test-projects/helm/api copy/templates/NOTES.txt
- core/test/data/test-projects/helm/api copy/templates/_helpers.tpl
- core/test/data/test-projects/helm/api copy/templates/deployment.yaml
- core/test/data/test-projects/helm/api copy/templates/ingress.yaml
- core/test/data/test-projects/helm/api copy/templates/service.yaml
- core/test/data/test-projects/helm/api copy/values.yaml
- core/test/integ/src/plugins/kubernetes/helm/deployment.ts
- core/test/unit/src/actions/action-configs-to-graph.ts
- core/test/unit/src/actions/build.ts
For `BuildAction`s generated by converting modules, we now override the `versionString` of the full version of `Build` actions with the `versionString` of their parent module.
This fixes an issue where e.g. `helm` modules that referred to `${modules.some-container-module.version}` would fail to deploy, since the version of the `Build` action that `container-module` would get converted to wouldn't match that of the `container` module that it was converted from—this resulted in a different version being built than the Helm chart expected, leading to image pull errors.
The same pattern is also standard when using `kubernetes` and `container` modules in conjunction.
This should ease the transition from 0.12 to 0.13 for many projects.
> fix(core): override Build version with module

- core/src/commands/logs.ts
- core/src/plugins/kubernetes/logs.ts
- core/src/plugins/kubernetes/run.ts
- core/src/plugins/kubernetes/util.ts
- core/test/integ/src/plugins/kubernetes/container/logs.ts
- docs/reference/commands.md
* fix(k8s): more stable & performant log streaming
Fixes an issue with very high upload bandwidth use when running Kubernetes based tests/tasks that produce a lot of log output.
co-written by @stefreak and @thsig
- Improved connection management and pod lifecycle logic, including more robust connection timeout enforcement.
- Removed keepalive logic, since it doesn't work on all operating systems.
- Improved deduplication logic to generate fewer false positives (and eliminate false-negatives).
- Use sinceTime when fetching logs on retry to make sure we don't fetch any unnecessary logs.
- When a runner pod terminates, we make sure to wait until the final logs have been fetched.
- Default to using the tail option in conjunction with a "max log lines in memory" setting instead of limitBytes …
> 0.13 cherry-pick: more stable & performant log streaming (#3730)

- core/src/commands/base.ts
- core/src/graph/nodes.ts
- core/src/graph/results.ts
- core/test/helpers.ts
- core/test/unit/src/commands/deploy.ts
- core/test/unit/src/commands/publish.ts
Fixes an OOM error that would occur when several actions failed during a command run.
We now mostly select a picked list of fields for including in our command result, instead of skipping fields (which has historically led to new fields with unbounded size slipping in, which calls for repeated fixes around this).
> fix(core): improve graph result filtering

- examples/remote-k8s/README.md
- examples/remote-k8s/garden.yml
- examples/remote-k8s/services/go-service/garden.yml
- examples/remote-k8s/services/node-service/app.js
- examples/remote-k8s/services/node-service/garden.yml
Fixes https://github.com/garden-io/garden/issues/3846
I have now tested this enough with a GKE cluster to be personally comfortable with merging this.
Deploying and remote builds work, and the services are accessible via a custom hostname - with some not-committed, local changes required to the configuration, as per instructions.
I have also removed the mention of TLS configuration in the example, to keep this focused on the remote builds and deployments. We have other examples for `cert-manager` use, and using a load balancer for TLS termination is another viable choice for production workloads - either of which should be better than manually setting kube secrets.
Squashing …
> chore(examples): update remote-k8s example to use actions

- core/src/graph/results.ts
This fixes an error that would come up when rendering command results for failed commands when the command didn't produce any result.
This is a follow-up/fix to https://github.com/garden-io/garden/pull/3911.
> chore: fix result filtering logic

- core/src/graph/solver.ts
- core/src/plugins/kubernetes/container/deployment.ts
- core/src/plugins/kubernetes/container/status.ts
- core/src/plugins/kubernetes/kubectl.ts
- core/src/plugins/kubernetes/kubernetes-type/handlers.ts
- core/src/plugins/kubernetes/status/status.ts
- core/src/plugins/kubernetes/volumes/persistentvolumeclaim.ts
- core/src/router/router.ts
- core/src/tasks/helpers.ts
- core/test/integ/src/plugins/kubernetes/container/deployment.ts
- core/test/integ/src/plugins/kubernetes/kubernetes-module/handlers.ts
In 0.12, we had wanted to update the `selector.matchLabels` used for `container` deploys, but doing so would require redeploying those resources (since `spec.selector.matchLabels` is an immutable field).
In 0.13, we decided to simply automatically redeploy any `container` deploys if needed (unless the environment in question is a production environment), since we wanted to use different labels (e.g. `action` instead of `service`).
Deleting the resources before redeploying them is necessary in this case, since the `spec.selector` field is immutable and attempting to update it for running resources will simply result in an error).
We don't automatically do this for production environments, except when force-deploying (which is a framework-native way …
> improvement(container): redeploy when spec changes

- core/src/cloud/api.ts
- core/src/plugins/container/container.ts
- core/src/plugins/container/moduleConfig.ts
- core/src/plugins/kubernetes/kubernetes-type/handlers.ts
- core/src/tasks/build.ts
- docs/reference/module-types/container.md
**fix(container): fix spec.image in container conversion**
When `module.spec.image` is provided, but the value has no tag, we weren't setting the Build/module version as the default tag/suffix to the image ID.
In 0.12, this was done by referencing the deployment image ID from the container build's outputs, which we can't do here. Therefore, we simply call the relevant helper to shim that behaviour here.
**fix: schema fixes around k8s/container conversion**
The `spec.targetImage` field was called `spec.image` on `containerBuildSchema` (i.e. the interface and the schema didn't agree).
Also fixed the spec conversion logic for `kubernetes` modules.
**chore: set default Cloud API auth token validity**
> chore: misc fixes for cloud

- core/src/actions/deploy.ts
- core/src/actions/run.ts
- core/src/actions/test.ts
- core/src/graph/actions.ts
- core/src/plugin/handlers/base/configure.ts
- core/src/plugins/hadolint/hadolint.ts
This enables `timeout` field in the `convert` handler of the `hadolint` plugin.
Fixes #
The original error message was confusing:
```
Error: 
Error parsing config for Test action foo:
Error validating configure handler output from provider hadolint for Test type hadolint: key "timeout" is not allowed at path .config[timeout]. Available keys: config)
at garden/core/src/graph/actions.ts:108:13
```
It should be fixed as well. Looks like there are some issues in the error description rendering in the [`validateSchema` function](https://github.com/garden-io/garden/blob/0.13/core/src/config/validation.ts#L84). It does not expand the existing `config` field and does not print the …
> 0.13 enable timeout for hadolint plugin

- .eslintrc
Add an ESlint rule for disallowing `console.log` family of commands
> chore: eslint: add no-console at error level

- core/src/analytics/analytics-types.ts
- core/src/analytics/analytics.ts
- core/src/cli/cli.ts
When the anonymous analytics is enabled, we currently track that a command is run, but not the actual outcome of the command. With this PR, we add an analytics event after a command has finished including the result as success/failure, error type and command duration. 
Fixes #
> improvement: track the command run result and duration

- core/src/plugins/kubernetes/api.ts
- core/src/plugins/kubernetes/run.ts
- core/src/plugins/kubernetes/types.ts
- core/test/integ/src/plugins/kubernetes/api.ts
Before this change, the Kubernetes API request sent as part of PodRunner
exec calls have not been retried.
This change makes sure that we use the existing Kubernetes API retry
implementation and at the same time it makes sure that HttpErrors are
wrapped properly, for improved error messages.
Fixes #
> fix(k8s): retry exec attempts in PodRunner

- core/src/actions/base.ts
- core/src/actions/types.ts
- core/src/events.ts
- core/src/plugin/base.ts
- core/src/plugin/handlers/Build/get-status.ts
- core/src/plugin/handlers/Deploy/get-status.ts
- core/src/plugins/exec/deploy.ts
- core/src/plugins/kubernetes/container/status.ts
- core/src/plugins/kubernetes/helm/status.ts
- core/src/plugins/kubernetes/init.ts
- core/src/plugins/kubernetes/integrations/cert-manager.ts
- core/src/plugins/kubernetes/kubernetes-type/handlers.ts
- core/src/plugins/kubernetes/status/pod.ts
- core/src/plugins/kubernetes/status/status.ts
- core/src/router/build.ts
- core/src/router/deploy.ts
- core/src/router/run.ts
- core/src/router/test.ts
- core/src/types/service.ts
- core/test/helpers.ts
- core/test/integ/src/plugins/kubernetes/container/container.ts
- core/test/integ/src/plugins/kubernetes/container/run.ts
- core/test/unit/src/commands/deploy.ts
- core/test/unit/src/plugins/exec/exec.ts
- core/test/unit/src/router/build.ts
- core/test/unit/src/router/deploy.ts
- core/test/unit/src/router/run.ts
- core/test/unit/src/router/test.ts
- plugins/pulumi/handlers.ts
- plugins/terraform/action.ts
Here, we udpate and simplify the action status event payload types used to communicate with Cloud.
The event payload types have been streamlined and standardized. We now use `actionState` as the primary state indicator field, which should reduce the special-casing needed on the backend (since we can interpret a common sum type for status events from all the main action kinds).
The action states have also been documented thoroughly, which should help newcomers understand the larger flow more easily.
We now also generate action UIDs for individual task instances, enabling us to use the same UID for the status handler call and the processing handler call.
This way, the API can correlate a status check with its subsequent processing call (if any).
We'll …
> chore(cloud): update action status & log events

- core/src/plugins/kubernetes/container/deployment.ts
- core/src/plugins/kubernetes/helm/deployment.ts
- core/src/plugins/kubernetes/kubernetes-type/handlers.ts
- core/src/plugins/kubernetes/local-mode.ts
- core/src/plugins/kubernetes/sync.ts
- core/src/plugins/kubernetes/types.ts
- core/test/integ/src/plugins/kubernetes/local-mode.ts
This PR **does not** fully fix the local mode integration tests. It refactors the local mode implementation, making it aligned with sync mode code, more readable, and easier to maintain. It also fixes some minor issues, and unifies the way of local mode config and start for all supported providers.
See individual commits for details. The commits be squashed before the merge. 
Fixes #
The local mode works well. Most likely, there is something wrong with the test implementation. That does not block the `0.13` release, and could be fixed in a separate PR.
> 0.13 some refactoring and minor fixes for local mode

- core/src/plugins/kubernetes/api.ts
- core/src/plugins/kubernetes/run.ts
- core/src/plugins/kubernetes/types.ts
- core/test/integ/src/plugins/kubernetes/api.ts
* fix(k8s): retry exec attempts in PodRunner
Before this change, the Kubernetes API request sent as part of PodRunner exec calls have not been retried.
This change makes sure that we use the existing Kubernetes API retry implementation and at the same time it makes sure that HttpErrors are wrapped properly, for improved error messages.
* fix(k8s): wrap k8s errors for better error messages
This change makes sure that we wrap exec k8s errors like we do for other Kubernetes API endpoints. This improves the error messages.
* improvement: only retry if the error is recoverable
Only retry on 500, 502, 503 and 429 errors to reduce the risk that the command is being executed twice.
---------
This PR cherry-picks #3956 to `0.13`.
**Which issue(s) this PR …
> 0.13 cherry-pick: fix(k8s): retry exec attempts in PodRunner

- core/src/cli/cli.ts
- core/src/cli/helpers.ts
- core/src/cloud/api.ts
- core/src/commands/custom.ts
- core/src/commands/dev.ts
- core/src/garden.ts
- core/src/logger/logger.ts
- core/src/plugins/kubernetes/status/status.ts
- core/src/process.ts
- core/src/server/server.ts
- core/test/unit/src/analytics/analytics.ts
- core/test/unit/src/cli/cli.ts
- core/test/unit/src/logger/logger.ts
- core/test/unit/src/server/server.ts
In a handful of places the rendered output assumes the fancy logger is being used and it really doesn't play nice with the basic logger.
This commit adds a logger "type" field to the root Logger and in a handful of places tweaks a given log message depending on the that type.
This is a prerequisite to making the basic logger the default but we still need to add some sort of a status indicator at the bottom before doing that since otherwise it's hard to tell whether Garden is still executing or waiting for changes when in persistent mode.
Fixes #
> improvement(logger): various fixes to make basic logger render nicer

- core/src/plugins/kubernetes/run.ts
- core/test/integ/src/plugins/kubernetes/container/container.ts
- core/test/integ/src/plugins/kubernetes/container/run.ts
- core/test/integ/src/plugins/kubernetes/run.ts
A user is having intermittent errors when running a test with artifacts where Garden responds with the error message:
```
<test-name> specifies artifacts to export, but the image doesn't contain the sh binary. In order to copy artifacts out of Kubernetes containers, both sh and tar need to be installed in the image.
```
They are sure that both `sh` and `tar` are present in the container.
Given the way we determine if `sh` or `tar` are not present and the difficulty in reproducing the error, I propose to print the full error message we receive from the execution, in the hope we can identify the root cause.
Fixes #
> improvement: add additional info to error message when sh is not found

- core/src/tasks/build.ts
Before this fix, the log line emitted in `BuildTask`'s `process` method was a rather confusing, since it seemed to indicate that the build was complete before it was executed.
> chore: fix confusing log lines in BuildTask

- core/src/events.ts
- core/src/router/build.ts
- core/src/router/deploy.ts
- core/src/router/run.ts
- core/src/router/test.ts
In order to have Cloud process events from 0.13 correctly, we needed to add the `actionType` key to emitted events which is one of "build", "deploy", "run" or "test".
These are hardcoded here as the property `action.type` available internally contained a different kind of information.
Fixes #
> 0.13 cloud alignment

- core/src/commands/self-update.ts
- core/test/unit/src/commands/self-update.ts
- docs/reference/commands.md
This PR cherry-picks #3999 to the `main` branch. it also contains some trivial whitespacing changes to satisfy the old linter.
Fixes #
> improvement: more granular version control in `self-update` command

- core/src/tasks/build.ts
- docs/README.md
- docs/tutorials/migrating-to-bonsai.md
This adds a rudimentary migration guide from 0.12 to Bonsai.
This is a bit of a minimum viable tutorial for pre-release purposes only. We should replace this with better documentation and a blog post later on.
Squash before merging to clean up the history.
> docs: add migration guide from 0.12 to bonsai

- core/src/analytics/analytics.ts
- core/src/cli/cli.ts
- core/src/commands/serve.ts
- core/src/config/config-template.ts
- core/src/config/render-template.ts
- core/src/config/template-contexts/project.ts
- core/src/garden.ts
Fixes #
The local dashboard has been removed in `0.13`. If users run `garden serve` but are not logged in to the Garden Cloud, throw an error with a helpful message.
I've also added a tiny helper method `isLoggedIn()` to the Garden class, to remove the `!!cloudApi` use and make things slightly more readable.
> chore: garden serve: require login

- core/src/commands/validate.ts
continuation of https://github.com/garden-io/garden/pull/3997
closes #3802
attempt full graph resolution, thus running all the handler and schema validation and catching errors in the template strings.
> 0.13: fix validate command not validating

- core/src/actions/base.ts
- core/src/graph/config-graph.ts
- core/src/plugins/container/container.ts
closes https://github.com/garden-io/garden/issues/4012
also adds validation to other container runtime actions
> 0.13: fix disabled build validation

- core/test/integ/src/plugins/kubernetes/container/ingress.ts
The failures were caused by https://github.com/garden-io/garden/pull/3997 as the container validation
handler actually modifies the deployment's ingress hostname
to the project default hostname if it's not specified on the deploy
itself.
I couldn't figure out how to fix this in a way where the proper default would be passed from the mocked provider config in the tests so I just manually assigned the hostnames.
> test: fix ingress integ tests

- core/src/commands/self-update.ts
- core/test/unit/src/commands/self-update.ts
- docs/reference/commands.md
To be able to update to the `0.13` pre-releases from `0.12.x` using `garden self-update` command.
This PR also contains some refactoring.
Fixes #
The commits will be squashed before the merge. See individual commits for details.
> feat: support pre-release versions in `self-update` command

- core/src/config-store/local.ts
Currently the `garden set default-env ''` command doesn't work due to garden thinking `""` is a non-existing parameter. I think we should implement a `garden clear` instead as that's a more clear api, no pun intended. I can do that if we agree that's the best way to go
> fix: set defaultEnv default value

- core/src/plugins/kubernetes/helm/config.ts
- core/src/plugins/kubernetes/helm/deployment.ts
- core/src/plugins/kubernetes/helm/handlers.ts
- core/src/plugins/kubernetes/helm/module-config.ts
- docs/reference/action-types/Deploy/helm.md
- docs/reference/module-types/helm.md
- static/kubernetes/system/ingress-controller/garden.yml
`helm` Deploy actions don't default to atomic installs.
This isn't strictly speaking breaking, because helm Modules still retain the old behavior, but it's worth mentioning in release notes anyway.
> refactor(k8s): don't set --atomic flag by default in helm Deploy actions

- core/src/commands/exec.ts
- core/src/graph/actions.ts
- core/src/plugin/handlers/Deploy/exec.ts
- docs/reference/commands.md
This prevents the `garden exec` command from executing any deployments. If the target container is found, the command execution proceeds. Otherwise, an error is thrown.
Fixes #
The commits will be squashed before the merge.
> 0.13 fix exec to not deploy anything

- core/src/commands/exec.ts
Caused by rebasing #4040 on top of merged #4052. Looks like there were no merging/rebasing conflicts in the changeset, but some "semantical" conflicts were. The compilation error appeared because of the renamed field (`state` -> `deployState`).
Fixes #
> chore: fix post-rebase compilation error

- core/src/plugins/kubernetes/api.ts
A user came across this nice little Kubernetes API peculiarity. Should help make the API wrapper more resilient to etcd throttling issues.
> improvement(k8s): catch internal etcdserver throttling error from API

- core/src/cli/command-line.ts
- core/src/commands/login.ts
- core/src/commands/logout.ts
- docs/reference/commands.md
Ensures that the login/logout commands uses the cloud domain in the project config. Both have the `noProject` flag set which leads to the garden instance not being initialized with a project config. Ensures that this is compatible with `garden dev` and also includes login/logout in the help listing.
Fixes #4049 
@edvald There was an earlier commit which reverted this behavior because of the dev command, https://github.com/garden-io/garden/commit/7f93b90830e1968526fa7f748e6f195c9a6e4421. Could you give some more context on how this relates?
> fix: login/logout using the configured domain

- docs/k8s-plugins/local-k8s/install.md
Documentation update for running minikube local cluster and authenticating to container registry 
@edvald @thsig
> docs: update docs for minikube registry auth

- static/kubernetes/system/nginx-kind/nginx-kind-new.garden.yml
https://cloud.google.com/blog/products/containers-kubernetes/how-the-kubernetes-k8sgcrio-redirect-impacts-gke-and-anthos
> In November 2022, the open source Kubernetes project [announced](https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/) that its new image registry, registry.k8s.gcr.io, was [officially GA](https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/). The new registry would replace the legacy k8s.gcr.io registry, with k8s.gcr.io getting [no further updates](https://kubernetes.io/blog/2023/02/06/k8s-gcr-io-freeze-announcement/) after April 3, 2023. To assist in this transition and ensure that users of earlier Kubernetes releases and tooling can update to supported versions in time, the Kubernetes …
> chore: switch from k8s.gcr.io to registry.k8s.io due to deprecation

- core/src/plugins/kubernetes/commands/pull-image.ts
Fixes `garden publish` on our example projects, where we use GCR as the registry and `kaniko` build mode. Without this change, `skopeo` invocation during the image pull was using the wrong secret, with no permissions attached.
> fix: use the correct secret in pullFromExternalRegistry in kaniko builds

- core/src/cli/cli.ts
- core/src/cli/helpers.ts
- core/src/commands/sync/sync-start.ts
- core/src/commands/sync/sync-stop.ts
- core/src/logger/renderers.ts
- core/src/mutagen.ts
- core/src/plugins/kubernetes/helm/common.ts
- core/src/plugins/kubernetes/helm/logs.ts
- core/src/plugins/kubernetes/helm/status.ts
- core/src/plugins/kubernetes/helm/sync.ts
- core/src/plugins/kubernetes/sync.ts
- core/test/unit/src/cli/helpers.ts
- docs/reference/commands.md
Before this fix, we were using locally rendered manifests instead of remotely deployed resources for status checks for helm Deploys.  This caused problems when starting/stopping syncs.
We were also using locally rendered manifests to find target resources
for log streaming for Helm Deploys. While this probably didn't cause problems in most cases, it also didn't make proper use of the retry loop in our Helm logging control flow.
A couple of other fixes were also made along the way:
**fix(sync-mode): ensure project mutagen dir exists**
Before this fix, we'd get Mutagen-related errors when listing syncs if the target resource wasn't deployed with sync mode.
**fix(cli):  correctly handle multiple opt aliases**
This fixes an issue with CLI options with …
> fix(helm): fix status checks around code syncing

- core/src/commands/exec.ts
- core/src/commands/sync/sync-start.ts
- core/src/events.ts
- core/src/plugins/exec/deploy.ts
- core/src/plugins/kubernetes/container/deployment.ts
- core/src/plugins/kubernetes/container/exec.ts
- core/src/plugins/kubernetes/container/status.ts
- core/src/plugins/kubernetes/helm/deployment.ts
- core/src/plugins/kubernetes/helm/exec.ts
- core/src/plugins/kubernetes/helm/status.ts
- core/src/plugins/kubernetes/init.ts
- core/src/plugins/kubernetes/kubernetes-type/exec.ts
- core/src/plugins/kubernetes/kubernetes-type/handlers.ts
- core/src/plugins/kubernetes/system.ts
- core/src/router/deploy.ts
- core/src/tasks/deploy.ts
- core/src/types/service.ts
- core/test/helpers.ts
- core/test/integ/src/plugins/kubernetes/helm/deployment.ts
- core/test/unit/src/commands/delete.ts
- core/test/unit/src/commands/deploy.ts
- core/test/unit/src/commands/get/get-status.ts
- core/test/unit/src/outputs.ts
- core/test/unit/src/plugins/exec/exec.ts
- core/test/unit/src/router/_helpers.ts
- core/test/unit/src/router/deploy.ts
- core/test/unit/src/tasks/deploy.ts
- docs/reference/commands.md
- plugins/pulumi/handlers.ts
- plugins/terraform/action.ts
This ensures that the detailed status state-field is named consistently across action kinds. It reverts a previous commit which changed `state` -> `deployState` for the `deploy` action.
Fixes #
Details in this thread: https://discord.com/channels/817392104711651328/1095652284379168869
> fix: 0.13 export the status state-field consistently across action types

- core/src/plugins/kubernetes/commands/sync.ts
- core/src/plugins/kubernetes/sync.ts
- docs/reference/action-types/Deploy/helm.md
- docs/reference/action-types/Deploy/kubernetes.md
If a target is not specified for a sync override the default target is used.
Also unified the schema and types between targets for sync and sync overrides.
Changed the behavior to throw if target is not set instead of a warning. I don't think it makes sense to just warn here.
> 0.13 fix: use default target in sync overrides

- core/src/commands/serve.ts
The dev command needs to work offline and when the user isn't logged in.
> fix(cli): don't throw in dev command if offline

- core/src/events.ts
- core/src/plugin/handlers/Build/get-status.ts
- core/src/types/service.ts
Define `{ActionKind}StatusForEventPayload` interfaces and types in the same places where `{ActionKind}State` interfaces are defined. That has already been done for `RunState` and `RunStatusForEventPayload`. This makes the code navigation a bit easier.
Fixes #
> refactor: moved some type definitions to other the packages

- core/src/plugins/kubernetes/api.ts
There have been some reports of `ECONNREFUSED` when running in github actions, which is only a temporary state and recovers when retried.
Thus we added the error to the list of retryable errors.
We also aligned the retry for k8s exec with other k8s requests to share the same logic.
> feat: retry ECONNREFUSED

- core/src/commands/exec.ts
To keep the same DX and in `test` command.
Fixes #
> feat: allow `-i` alias for interactive mode in `exec` command

- core/src/commands/custom.ts
Refs: 96f6721 and #3983
In PR #3983 we set noProject=true on the custom commands class.
This was to prevent the entire init logic from re-running for the inner command when set.
Re-running the init logic means the user is authenticated against Cloud twice, two buffered event streams are created, the command is tracked twice, etc etc.
However, setting noProject=true on the outer command means that variables aren't resolved which means you can't reference them in custom commands which of course also causes issues.
So despite its flaws, we're reverting to the previous version. But in general this behaviour hasn't been thought fully through, and the implementation we're reverting to doesn't play well with Cloud.
In my opinion, we should create a single …
> revert: remove noProject flag from custom commands

- core/src/commands/custom.ts
Refs: 96f6721 and #3983
In PR #3983 we set noProject=true on the custom commands class.
This was to prevent the entire init logic from re-running for the inner command when set.
Re-running the init logic means the user is authenticated against Cloud twice, two buffered event streams are created, the command is tracked twice, etc etc.
However, setting noProject=true on the outer command means that variables aren't resolved which means you can't reference them in custom commands which of course also causes issues.
So despite its flaws, we're reverting to the previous version. But in general this behaviour hasn't been thought fully through, and the implementation we're reverting to doesn't play well with Cloud.
In my opinion, we should create a single session for a single custom command and …
> 0.13 cherry-pick: revert: remove noProject flag from custom commands

- core/src/commands/commands.ts
- core/src/commands/community.ts
Adds a new command `garden community` that opens the Garden Community Discord invite link.
Completes the task defined on the Q2 ideas Miro board.
Sorted the imports in `commands.ts` as a separate commit, as they were _almost_ sorted already.
> feat: `garden community` command

- plugins/pulumi/cli.ts
Fixes typo in Platform architecture for Pulumi CLI. Also, updates the `_includeInGardenImage` flag for the previous default version. This is a follow-up fix for #4107.
Fixes #
> chore: fix typo in pulumi cli's architecture

- core/src/monitors/logs.ts
- scripts/run-script.ts
Every time I ran `yarn build` I thought `cli` had errored out:
So this PR removes the color red from the non-error based logs that I could find, making `cli` not look like something went wrong:
Feel free to point me in the direction of other logging methods or helper functions that might be using the color red.
> refactor: remove the color red from non-error related logging

- core/src/plugins/kubernetes/status/status.ts
This relatively simple change substantially reduces API requests during status polling, particularly when waiting for deployments to complete.
> improvement(k8s): reduce number of k8s API calls during status monitoring

- .circleci/config.yml
Fixes CI runs for `helm` cli invocations against a GKE cluster.
We have already installed the newer `gke` auth plugin, and it works by default for `kubectl`. However, the `helm` cli does not use it unless you specify the env var.
https://github.com/helm/helm/issues/11069
https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
> chore(ci): fix gcloud gke auth

- core/src/garden.ts
- core/test/data/test-projects/config-valid-v0/project.garden.yml
- core/test/integ/src/plugins/kubernetes/helm/config.ts
- core/test/unit/src/garden.ts
Fixes this error in all projects that are missing `apiVersion: v1`:
✖ Action kinds are only supported in project configurations with "apiVersion: garden.io/v1". A detailed migration guide is available at https://docs.garden.io/tutorials/migrating-to-bonsai
The error is supposed to be thrown only if action kinds are declared.
Fixes #
> fix: do not throw if no action kinds & garden.io/v0

- core/test/data/test-execprovider-fail/garden.yml
- core/test/unit/src/commands/run-workflow.ts
To make it possible to prepare kubeconfigs and other prerequisites to
provider initialization in a workflow, we want to manifest this
behaviour using tests.
Fixes #
> test(workflows): add test case for lazy initialization

- docs/basics/quickstart.md
- docs/guides/installation.md
- scripts/install-osx-dependencies.sh
- Fixes the error regarding brew install `kubernetes-helm` as its now renamed to helm. 
- Adds pointer about Rosetta requirement in installation instructions for Apple Silicon macs. In case Rosetta is not installed, user faces: `bad CPU type in executable` while using `garden` in terminal.
Fixes #
> fix osx install deps script and add pointer about Rosetta

- core/src/commands/deploy.ts
- core/src/monitors/logs.ts
- core/test/unit/src/commands/deploy.ts
- docs/reference/commands.md
When used, the `--logs` option streams service logs during deployment, and then keeps the command running until the user exits it.
This is useful for combining deployment with log streaming.
We should only be streaming logs from the current time onwards, but the logs monitor currently doesn't support the `since` option. I didn't add it back in since IIRC @eysi09 is working on a branch that addresses that.
> feat(core): --logs option for deploy command

- core/src/cli/cli.ts
- core/src/cloud/buffered-event-stream.ts
- core/src/commands/serve.ts
- core/src/monitors/manager.ts
- core/src/server/server.ts
- core/test/unit/src/garden.ts
- core/test/unit/src/logger/renderers.ts
- e2e/test/pre-release.ts
Previously, the monitor statuses known to the monitor manager could be wrong due to a race condition when toggling monitors.
Consider the following:
- T1: Log monitor A is requested via websocket
- T2: Log monitor A is aborted via websocket
- T3: The stop function from T2 returns and sets the status to stopped
- T4: The start function from T1 returns and set the status to started
In this case the final status is incorrectly 'started' as opposed to 'stopped'.  
It's not clear if this actually causes issues but in any case it's confusing and makes it hard to debug other issues around monitors if we can't trust the statuses displayed by the manager.
Fixes #
> fix(monitors): ensure status isn't overwritten due to a race condition

- core/src/commands/run.ts
- core/test/unit/src/commands/run.ts
We now throw if the user calls `garden run test ...`, `garden run task ...` or `garden run workflow ...`, since that almost certainly implies they were trying to run commands that were removed in 0.13.
> improvement(cli): detect calls to removed run cmds

- core/src/commands/base.ts
- core/src/commands/custom.ts
- core/src/commands/deploy.ts
- core/src/commands/dev.tsx
- core/src/commands/logs.ts
- core/src/commands/serve.ts
- core/src/commands/sync/sync-start.ts
- core/src/monitors/base.ts
- core/src/monitors/logs.ts
- core/src/monitors/manager.ts
- core/src/server/commands.ts
- core/src/server/server.ts
- core/test/unit/src/commands/base.ts
- core/test/unit/src/commands/logs.ts
Previously we were re-using the same command instance for every server request (created at start time via `getCoreCommands()`).
This meant that multiple requests would all subscribe to the same instance.
Concretely, if request A, asks for logs for service X and request B, asks for logs for service Y, they would both subscribe to the same logs command.
Now, when service X writes logs, the callbacks for both request A and request B would be called and to the end user it looks like both services X and service Y are writing the logs.
**UPDATE:**
This first one didn't quite do the trick. There's a follow up commit with following commit message:
This is a follow up to: https://github.com/garden-io/garden/commit/ac54b93ef8680f12e86b24b52dcf5221af5e8be7
The …
> fix(server): ensure fresh command instance per request

- core/src/commands/commands.ts
- core/src/commands/run.ts
- core/src/commands/validate.ts
- core/src/commands/workflow.ts
- core/src/config/template-contexts/project.ts
- core/src/garden.ts
- core/test/unit/src/cli/helpers.ts
- core/test/unit/src/commands/workflow.ts
- docs/reference/commands.md
- docs/reference/template-strings/action-all-fields.md
- docs/reference/template-strings/action-specs.md
- docs/reference/template-strings/custom-commands.md
- docs/reference/template-strings/environments.md
- docs/reference/template-strings/modules.md
- docs/reference/template-strings/project-outputs.md
- docs/reference/template-strings/projects.md
- docs/reference/template-strings/providers.md
- docs/reference/template-strings/remote-sources.md
- docs/reference/template-strings/workflows.md
- docs/using-garden/using-the-cli.md
- docs/using-garden/workflows.md
- e2e/projects/vote-modules/README.md
- e2e/test/pre-release.ts
- examples/vote/README.md
This PR does two things:
- Renames `garden run-workflow` command to a simplified `garden workflow`
- Moves the old-style run command invocation detection earlier (before graph init), to support lazy-init usecases (e.g. workflows)
Fixes https://github.com/garden-io/garden/issues/4166
Not flagging this commit specifically as a breaking change, as the breaking change in behavior has already been flagged earlier when moving from `run workflow` to `run-workflow`. This commit also makes sure all the docs are up to date, so we should be good in terms of communication.
Ship small, ship often. This PR continues the old behavior of throwing a config error in case of the use of old-style …
> refactor: rename `run-workflow` to `workflow`

- docs/basics/quickstart.md
- docs/guides/installation.md
- scripts/install-osx-dependencies.sh
Cherry-picks https://github.com/garden-io/garden/pull/4157 to 0.13.
Fixes #
> 0.13 cherry-pick: osx dependencies & rosetta in docs

- docs/tutorials/your-first-project/1-initialize-a-project.md
- docs/tutorials/your-first-project/3-deploy-and-test.md
- docs/tutorials/your-first-project/4-configure-your-project.md
- docs/tutorials/your-first-project/README.md
- docs/using-garden/using-the-cli.md
Addresses the tutorials part of #4067.
Fixes #
> 0.13 docs update: tutorials

- core/src/commands/run.ts
- core/src/commands/workflow.ts
- core/test/data/test-projects/old-style-run-invocations/garden.yml
- core/test/data/test-projects/old-style-run-invocations/module-a/garden.yml
- core/test/unit/src/commands/run.ts
Adds backwards compatibility for old-style `run` command invocations.
```console
cd examples/vote/;
garden run task db-init;
garden run workflow full-test;
```
Fixes https://github.com/garden-io/garden/issues/4166
I would appreciate if the reviewers could try this out on some known-working workflows and tasks to verify the backwards compatibility works, by using the old-style `garden run workflow foo`, `garden run task foo`, `garden run test foo` invocations. These should be run against both `0.12` style and `0.13` style config files.
Pardon the slightly hacky implementation. If you have suggestions on how to make this cleaner, I'm all ears <3
> fix: add backwards compatibility for old-style run commands

- core/src/util/testing.ts
- core/test/unit/src/commands/run.ts
Garden emits non-repeatable warning "Project is configured with `apiVersion: garden.io/v0`, running with backwards compatibility." Thus, the variable `logMessages` may contain 2 lines. This commit introduces helper function `expectLogsContain` to check if there is at least one entry of a given sample among all log lines.
Patch for #4195
It makes the log-checking unit test assertions more stable by taking into account non-repeatable warnings.
> test: fix assertions for `run` command

- e2e/projects/jib-container-modules/spring-boot/README.md
- examples/jib-container/spring-boot/README.md
Removing a couple of unnecessary social media links from spring-boot example project readme files (not created by us).
Twitter has started to return 403 on the intent-tweet page when you are not logged in, causing our link checker in the `check-docs` CI step to fail.
> docs: remove some unnecessary social media links from readmes

- core/src/cloud/buffered-event-stream.ts
- core/src/logger/log-entry.ts
- core/src/logger/logger.ts
- core/src/server/commands.ts
- core/src/server/server.ts
- core/test/unit/src/logger/log-entry.ts
- core/test/unit/src/logger/logger.ts
- core/test/unit/src/server/server.ts
Previously, we'd only stream Garden events to websocket subscribers but not actual log entries.
This meant clients could only respond to events and subscribe to service logs but not render actual Core log entries.
This fixes that by simply piping log events to websocket subscribers.
Fixes #
> feat(server): stream log entries over ws

- core/src/cli/command-line.ts
Before this fix, adding a space at the end of a command invocation in the `dev` command would result in unexpected CLI argument parsing behavior (e.g. no Deploys being requested when running `deploy --logs` with a trailing space).
> fix(dev): trim trailing whitespace from cmd args

- docs/pulumi-plugin/configure-modules.md
- docs/pulumi-plugin/configure-provider.md
- docs/reference/module-types/pulumi.md
- docs/reference/providers/pulumi.md
- plugins/pulumi/config.ts
- plugins/pulumi/handlers.ts
- plugins/pulumi/helpers.ts
Initialize Pulumi's backendURL and orgName with default values. Also make them as non-required config options.
Fixes #
> chore(pulumi): make pulumi backendURL and orgName as non-required fields

- core/src/graph/actions.ts
- examples/remote-sources/README.md
- examples/remote-sources/garden.yml
- examples/remote-sources/worker/garden.yml
The git diff looks very odd, but basically I set the action base bath to the `remoteSourcePath` which fixes the treeVersion issue. Also updated the example.
> 0.13: remote sources fix + example update

- core/src/plugin/handlers/Deploy/deploy.ts
- docs/basics/how-garden-works.md
- docs/guides/code-synchronization.md
- docs/guides/migrating-from-docker-compose.md
- docs/k8s-plugins/advanced/in-cluster-building.md
- docs/misc/faq.md
- docs/other-plugins/container.md
Improve docs around sync mode as `garden dev` now opens interactive shell env instead of dev mode as it was in 0.12.
Fixes #
> docs: improve sync mode docs

- core/src/cli/cli.ts
- core/src/cloud/buffered-event-stream.ts
- core/src/commands/base.ts
- core/src/commands/dev.tsx
- core/src/commands/serve.ts
- core/src/commands/test.ts
- core/src/server/server.ts
When starting the CLI, a buffered event stream is created that subscribes
to events from a Garden instance.
However, when running a serve command, a new Garden instance is created
via the "reload" function which the buffered event stream wasn't
subscribing to.
This commit fixes that by setting the new instance explicitly on the
buffered event stream.
This is pretty hacky and just a workaround to unblock things which will
be removed when we introduce a proper instance manager.
Fixes #
> 0.13 ensure dev command sends events

- core/test/integ/src/plugins/kubernetes/container/deployment.ts
- core/test/unit/src/actions/action-configs-to-graph.ts
- core/test/unit/src/server/core-event-stream.ts
- core/test/unit/src/tasks/deploy.ts
- e2e/test/pre-release.ts
> 0.13 clean up some skipped tests

- core/src/plugins/kubernetes/container/build/common.ts
- core/test/unit/src/plugins/kubernetes/container/build/common.ts
This PR allows to create new registry repositories (via `skopeo`) on the fly and makes parity with the current `GCP/GAR` support.
This is beneficial for the first build of a new project, as Garden checks the image status and fails due to the repository is not found.
Reported internally
I love Garden ❤️
> feat(plugins): set the manifest to unknown if repository is not found

- core/src/plugins/kubernetes/container/build/common.ts
- core/test/unit/src/plugins/kubernetes/container/build/common.ts
Cherry-picks #4229 to `0.13`.
Fixes #
> 0.13 cherry-pick: feat(plugins): set the manifest to unknown if repository is not found

- cli/src/cli.ts
- core/src/config-store/base.ts
The lock library we use in the config store throws an uncaught exception when a lock is compromised. We catch the error and log out a warning to avoid the entire garden process to crash. This is a workaround for now until we can reproduce and fix the root cause. 
Fixes #
> fix: unhandled errors when config store update fails

- core/src/cache.ts
- core/src/config/provider.ts
- core/src/plugins/kubernetes/container/build/buildkit.ts
- core/src/plugins/kubernetes/container/build/kaniko.ts
- core/src/plugins/kubernetes/init.ts
- core/src/plugins/kubernetes/jib-container.ts
- core/src/plugins/kubernetes/kubernetes.ts
- core/src/plugins/kubernetes/namespace.ts
- core/src/plugins/kubernetes/port-forward.ts
- core/src/plugins/kubernetes/run-results.ts
- core/src/plugins/kubernetes/status/status.ts
- core/test/integ/src/plugins/kubernetes/api.ts
- core/test/integ/src/plugins/kubernetes/container/build/buildkit.ts
- core/test/integ/src/plugins/kubernetes/container/ingress.ts
- core/test/integ/src/plugins/kubernetes/namespace.ts
- core/test/unit/src/cache.ts
- core/test/unit/src/plugins/kubernetes/init.ts
Because the `delete namespace` command can be called interactively (which deletes the default app namespace), and because of the `reload` command, we needed a different approach to caching namespace statuses in the Kubernetes plugin.
The new approach scopes the cache by provider UID, and clears the cache for a given provider UID if the `delete namespace` command is called.
We also introduced an async lock to the `ensureNamespace` helper, since the first `deploy` command after a `delete namespace` command can result in more than one concurrent `ensureNamespace` call for the same namespace.
Fixes #4223.
As noted in one of the comments, we may want to provide a cache to all plugin …
> fix(k8s): fix namespace caching logic

- .circleci/config.yml
- support/alpine-builder.Dockerfile
- support/alpine.Dockerfile
- support/buster.Dockerfile
- support/docker-bake-test.sh
- support/docker-bake.hcl
Co-authored-by: Tim Beyer <TimBeyer@users.noreply.github.com>
- Use sha256 references that can be automatically updated by dependabot
- Use buildkit's cacheFrom and cacheTo to increase difficulty of supply chain attacks
Addresses #3993 
> ci(dockerhub): secure sha256 references and multi-layer caching

- core/src/cli/command-line.ts
- core/src/commands/dev.tsx
- core/src/commands/serve.ts
- core/src/events.ts
- core/src/garden.ts
- core/src/watch.ts
- core/test/unit/src/watch.ts
If one or more Garden configs is changed during a `dev` command, we lazily reload the project when the next command is run.
This approach avoids multiple reloads when the user is modifying their Garden configs.
The old Watcher class was reduced down to its bare essentials for this purpose (up to this point, it had been unused in 0.13).
Fixes #4213.
> improvement(dev): handle config changes

- core/src/cli/command-line.ts
- core/src/events.ts
- core/src/plugin-context.ts
- core/src/server/server.ts
- core/test/unit/src/events.ts
Closes https://github.com/garden-io/garden/issues/4186.
Before this fix, we weren't removing event listeners registered by the plugin event brokers (mostly for the `_exit` and `_restart` control events).
This is now done in a simple way via the new `onKey`  and `clearKey` methods on the event bus, which facilitates removing all listeners matching a given key.
We use `garden.sessionId` as the key now, which is not quite ideal when running concurrent commands in `garden dev`, but we'll be assigning a command-unique `sessionId` in an upcoming PR (which gives us precisely the semantics we want here).
Fixes #4186 and #2422.
> fix(core): improve event listener cleanup

- core/src/commands/base.ts
- core/src/commands/logs.ts
- core/src/logger/logger.ts
- core/src/server/commands.ts
Before this, server logs would be emitted twice over ws. Once via the 'commandOutput' event which a request would subscribe to and once as a 'logEntry' event.
By setting the logger instance to the VoidLogger for the logs when executed by the server, we eliminate the latter and only emit the log once.
Note that this is a bit hacky and means that other log entries that the logs command creates are also ignored.
Fixes #
> fix(server): ensure server logs aren't emitted twice

- core/src/commands/logs.ts
- core/src/commands/sync/sync-status.ts
- core/src/commands/sync/sync.ts
- core/src/mutagen.ts
- core/src/plugin/handlers/Deploy/get-sync-status.ts
- core/src/plugins/kubernetes/sync.ts
- docs/reference/commands.md
This PR adds a command for getting the current status of all
configured syncs.
In this first iteration the command is not persistent but we may decide
to add a "--follow" or "--monitor" flag later.
The main reason I'm not doing it here is because even if we're
monitoring the sync statuses, we don't get the "sync stop" events from
Mutagen which is one of the main events we'd want to follow in the first
place.
So since sync monitoring would be incomplete and you'd need to re-run
the command to get the latest status I decided leave it out for now.
Fixes #
Here's a screenshot of the output. I was feeling a little uninspired tbh, so happy to receive suggestions.
> Add "sync status" command

- core/src/server/server.ts
Before this fix, the dev command would appear to hang indefinitely after typing "exit" or killing the process with ctrl+c because the websocket connection wasn't closed properly.
Fixes #4209 
> fix(server): ensure ws connection is closed on Garden "_exit" event

- core/package.json
- core/test/integ/src/plugins/kubernetes/kubernetes-module/handlers.ts
- core/test/integ/src/plugins/kubernetes/local-mode.ts
- core/test/integ/src/plugins/kubernetes/sync-mode.ts
- core/test/unit/src/cache.ts
- core/test/unit/src/commands/deploy.ts
- core/test/unit/src/commands/get/get-config.ts
- core/test/unit/src/garden.ts
- core/test/unit/src/router/build.ts
- core/test/unit/src/template-string.ts
Fixes missing linting for the `core/test` directory. This meant that e.g. `.only` directives were not caught, despite our intention to fail the linting on the presence of exclusive tests.
Previously, in `core`, we were only linting the `src/` directory. Now we will lint the `test/` directory too.
> chore: linter fixes for core

- core/src/plugins/kubernetes/namespace.ts
previously the error was
"Namespace garden-system doesn't exist and Garden was unable to create it. You may need to create it manually or ask an administrator to do so."
which is plain misleading.
I tried to implement logic that waits for the termination to complete, but the `ensureNamespace` function is called multiple times which makes it hard and I judged it not worth the effort.
This probably closes #3696
> chore: improve error for when ns in terminating

- docs/using-garden/README.md
- docs/using-garden/actions.md
> docs: update actions guide

- core/src/cli/cli.ts
This will allow to mute the warning via the `garden util hide-warning bonsai-warning` command
> chore: use emitWarning for 0.13 warn msg

- core/src/plugins/base-volume.ts
- core/src/plugins/kubernetes/volumes/configmap.ts
- core/src/plugins/kubernetes/volumes/persistentvolumeclaim.ts
- docs/reference/action-types/Deploy/persistentvolumeclaim.md
- docs/reference/module-types/persistentvolumeclaim.md
The schema validation for the jsonSchema generated spec actually doesn't work but I don't want to spend more time on this and k8s validates it on apply anyway
> fix: remove duplicate accessModes key from pvc provider module and action

- core/src/plugins/kubernetes/local/config.ts
[Colima](https://github.com/abiosoft/colima) is a popular container runtime for MacOS with built-in kubernetes support. This adds `colima` as a supported context for the local k8s plugin.
Fixes #
> chore: kubernetes with local context including colima

- core/src/config/workflow.ts
- docs/reference/commands.md
- docs/reference/workflow-config.md
- docs/using-garden/workflows.md
Updates the docs around using garden workflows. Since commands in bonsai don't export a lot of outputs that were output in acorn, i had to remove a part of the docs regarding using step outputs. I will file an issue of re-implementing these outputs and then this part of the docs should be adjusted again.
Fixes #4292
> docs(workflows): update workflow docs for bonsai

- core/src/commands/dev.tsx
We now exit the process with a nonzero exit code 5 seconds after receiving a `SIGINT` or a control-c keystroke.
This is to ensure that if the Garden process hangs for any reason, it doesn't stay unresponsive for longer than a limited time.
> improvement(core): ensure SIGINT is honored

- core/src/config/project.ts
- core/src/garden.ts
- core/src/logger/renderers.ts
- core/src/template-string/template-string.ts
- core/test/unit/src/config/project.ts
**improvement(core): project conf. validation errors**
Improved the error logging for the case where template string resolution fails during project config resolution.
Previously, it wasn't obvious where the failing template string came from when the validation error is in the project config (unlike template errors in action configs, where the error logging was already pretty good).
**fix(core): don't log error details in terminal renderer**
The error logging in Bonsai had become extremely verbose. This was because we were rendering error details in the terminal renderer when an error object was provided to `log.error`.
Fixes #4305 and #4308.
> Error logging improvements

- core/src/plugins/exec/deploy.ts
- core/src/plugins/exec/exec.ts
- core/src/process.ts
- core/src/router/deploy.ts
- core/test/integ/src/plugins/kubernetes/container/build/buildkit.ts
- core/test/unit/src/plugins/exec/exec.ts
- docs/reference/providers/exec.md
Before this fix, `exec` Deploys that were deployed with `persistent: true` in their config weren't being terminated when deleted (e.g. via the `cleanup deployment` command).
This was fixed by killing child processes of the PID as well.
Also removed some noisy warning logs when including `exec` Deploys in a sync-related command.
The `exec` plugin doesn't define `syncStart` or `syncStop` handlers, since it uses the `persistent: boolean` config flag for a similar purpose.
Here, we raise the log level for the "No startSync/stopSync handler available for action type exec" log lines to `debug`.
> fix(exec): fix delete handler for persistent mode

- core/src/logger/renderers.ts
- core/test/unit/src/logger/renderers.ts
Before:
After:
I know people have strong opinions on timestamps, here I'm using 24 hour time with the format "HH:mm:ss" but happy to revise.
We could also make it configureable for that matter but this feels like a good start.
Fixes #
> improvement(logger): render timestamp as local time string

- .circleci/config.yml
We support only last 6 versions.
Fixes #
> ci(test): remove old minikube with kubernetes 1.19

- core/src/commands/sync/sync-restart.ts
- core/src/commands/sync/sync-start.ts
- core/src/commands/sync/sync-status.ts
- core/src/commands/sync/sync-stop.ts
- core/src/commands/sync/sync.ts
- core/src/mutagen.ts
- core/src/plugin/handlers/Deploy/get-sync-status.ts
- core/src/plugins/kubernetes/sync.ts
- docs/reference/commands.md
feat(core): added sync restart command
This command stops and starts any active syncs for the relevant Deploy actions.
This is useful for recovering from error states for syncing tools.
Also added diagnostic message logging for failure states to the `sync status` command.
For Mutagen-based syncs, we provide clear information to the user why the sync has been halted, and suggest running the `garden sync reset` command after making sure that the relevant directories are in the expected state.
This addresses sporadic reports we've gotten from our users where code syncing stops working due to a failure condition in Mutagen (e.g. when the user deletes or moves the source dir). Here, both the diagnostics and the …
> feat(core): added sync restart command

- core/src/commands/get/get-status.ts
- core/src/commands/sync/sync-status.ts
- core/test/unit/src/commands/get/get-status.ts
- docs/reference/commands.md
This commit adds a couple of "internal" flags to the sync status and get status commands that make it easier for Cloud and Desktop to consume their output.
Note that the "garden get status" command will be replaced with a top level "garden status" command and that these changes aren't really meant to be user facing. Rather just to unblock a few things on the Cloud side.
Fixes #
> improvement(commands): add --skip-detail and --only-deploys flags

- core/src/commands/sync/sync-status.ts
Fixes a recent regression in the args handling for the new `sync status` command.
> fix: fix regression in sync status cmd arg handling

- core/src/commands/base.ts
- core/src/commands/deploy.ts
- core/src/commands/publish.ts
- core/src/commands/sync/sync-status.ts
- core/src/graph/results.ts
- core/src/types/service.ts
- core/test/unit/src/commands/build.ts
- docs/reference/commands.md
In 0.12, we included keys for build, deploys and tasks in the command result for commnds that used the task graph (e.g. the build & deploy commands).
In 0.13, we initially removed these in favour of the `graphResults` object. Here, we reintroduce them (with most fields still there). This should prevent breakages e.g. in workflows where referencing command outputs is relatively common.
In a future PR, we should get rid of the `graphResults` key entirely from command results. Doing so will require reworking some of our unit tests (since some suites rely on the dependency structure of the results to verify which tasks were actually run).
Fixes #4324
> fix(core): reintroduce kind-specific cmd outputs

- core/src/commands/base.ts
- core/src/server/commands.ts
- core/test/setup.ts
- core/test/unit/src/cli/analytics.ts
This introduces a flag per command to disable analytics. Initially we use this for autocomplete.
Fixes #
There is a temporary fix for an issue with nock and node 18 to make sure we use a compatible fetch. This can be removed when we move to node 20.
> chore: add a per-command flag to disable analytics, starting with autocomplete

- core/src/analytics/analytics.ts
- core/src/commands/base.ts
- core/src/commands/dev.tsx
- core/src/commands/serve.ts
- core/test/unit/src/analytics/analytics.ts
When analytics is initialized the first time it has a dummy garden instance. This instance is not aware of a cloud connection which means all subsequent commands will not be associated with a possibly logged in user. This change ensures that we reload the analytics metadata when the garden instance is a proper instance.
The second commit introduces a parentSessionId and includes that explicitly when tracking events. We also ensure that the sessionId from the dummy garden instance created when starting the `dev` command is brought over into the instance manager. The initial sessionId is sent in the first track event, before `action` is called on dev and the following serve command. Without this we would not be able to consistently follow a complete …
> fix: re-init the analytics handler metadata on project switch

- core/src/commands/sync/sync-status.ts
- core/src/server/commands.ts
- core/src/server/instance-manager.ts
This is an internal command that's only used by Cloud to get sync and deploy statuses in a single command to prevent Cloud having to call two commands for that data (since it polls for it).
Fixes #
> perf(dev): add internal command for getting sync and deploy statuses

- core/src/plugins/kubernetes/status/workload.ts
We were getting the desired replica count from the status API
response [1] which has the current replica count, not the desired amount.
Desired amount is specified in the spec [2].
1. https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/stateful-set-v1/#StatefulSetStatus
2. https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/stateful-set-v1/#StatefulSetSpec
> fix: properly wait for k8s deploys to complete

- core/src/util/sync.ts
- core/test/unit/src/build-staging/build-staging.ts
Filenames such as `[id].vue` can break our file synchronization (and hence builds and deploys) on Windows, where we use `rsync`
Fixes https://github.com/garden-io/garden/issues/4018
Verified using a [reproducible example](https://github.com/uni-venkateshwar-viswanathan/garden-test/) on a Windows VM on Azure
https://linux.die.net/man/1/rsync section `Include/Exclude Pattern Rules`
> rsync chooses between doing a simple string match and wildcard matching by checking if the pattern contains one of these three wildcard characters: oq*cq, oq?cq, and oq[cq . 
Do we want to backport this to 0.12 (and cut a new release)?
> fix: escape rsync special characters in filenames on windows

- core/src/plugins/kubernetes/config.ts
- docs/reference/providers/kubernetes.md
to reflect the (already not so) new and cool `ingressClassName`.
closes https://github.com/garden-io/garden/issues/3344
I also added the rename of the field to the breaking changes wishlist.
> docs: update ingressClass doc

- support/buster.Dockerfile
This should save us around 270 MB or so of unused dependencies.
Fixes #
> build: use slim buster image instead of large one

- core/src/plugins/kubernetes/helm/config.ts
- core/test/data/test-projects/helm-name-version-regression/garden.yml
- core/test/integ/src/plugins/kubernetes/helm/config.ts
- docs/reference/action-types/Deploy/helm.md
- docs/reference/action-types/Run/helm-pod.md
- docs/reference/action-types/Test/helm-pod.md
Fixes https://github.com/garden-io/garden/issues/4461
Validated locally using the example from the mentioned issue
```
gdev deploy
Deploy 🚀
Project is configured with `apiVersion: garden.io/v0`, running with backwards compatibility.
ℹ garden               → Running in Garden environment default.default
ℹ providers            → Getting status...
✔ providers            → Cached (took 0.7 sec)
ℹ providers            → Run with --force-refresh to force a refresh of provider statuses.
ℹ graph                → Resolving actions and modules...
✔ graph                → Done (took 0 sec)
ℹ deploy.mailhog       → missing
ℹ deploy.mailhog       → Deploying version v-68d2bc1af2...
ℹ …
```
> fix: helm module to action conversion: do not require version with name

- core/src/cli/command-line.ts
- core/src/cli/helpers.ts
- core/src/logger/renderers.ts
- core/src/logger/util.ts
- core/test/unit/src/logger/renderers.ts
See commits for details.
A bunch of test assertions might fail, will need to fix separately if so.
This also completes this https://github.com/orgs/garden-io/projects/5/views/1?pane=issue&itemId=28914020 <- was erroring out just as expected, it's just that the error was not shown.
> fix: render (log) errors

- core/src/plugins/kubernetes/helm/helm-cli.ts
Updates `helm` from the ancient version `3.7.2` to the latest release `3.12.0`.
Fixes #3753
This is a _potentially_ breaking change. There were some breaking changes in helm CLI and SDK between the versions:
* helm 3.11.1 https://github.com/helm/helm/releases/tag/v3.11.1
* helm 3.9.0 https://github.com/helm/helm/releases/tag/v3.9.0
Those changes might not be breaking for Garden helm provider. We use `install`, `upgrade`, and `template` helm commands, but I haven't faced any issues yet. Tested with `garden deploy` in the [`vote-helm` example](https://github.com/garden-io/garden/tree/main/examples/vote-helm).
> Update helm version from `3.7.2` to `3.12.0`

- docs/reference/module-types/pulumi.md
- plugins/pulumi/config.ts
- plugins/pulumi/index.ts
Adds a separate spec for Pulumi modules and actions, so that we can validate old configurations correctly.
Fixes https://github.com/garden-io/garden/issues/4468
Taking inspiration from the terraform plugin, and how the module and action validation is handled there.
Pardon the seemingly large changes due to moving the `.keys()` call outside the function for reuse purposes - it is mostly indents.
> fix: pulumi module validation

- core/src/plugins/kubernetes/kubernetes-type/common.ts
- core/test/data/test-projects/kubernetes-module/config-map-list/garden.yml
- core/test/data/test-projects/kubernetes-module/config-map-list/manifests.yaml
- core/test/integ/src/plugins/kubernetes/kubernetes-module/handlers.ts
> fix(kubernetes): do not fail to deploy List kinds (e.g. ConfigMapList)

- core/src/commands/self-update.ts
- docs/reference/commands.md
We need to release this asap, especially for 0.12 as people seem to be installing the 0.13.0-0 pre-release from March
0.12 pr: https://github.com/garden-io/garden/pull/4455
> 0.13 docs: update self-update command docs

- core/src/server/server.ts
Filters out defined commands from analytics when requested through the websocket server.
Fixes #
> chore: disable analytics for WS server commands

- plugins/terraform/common.ts
- plugins/terraform/index.ts
- plugins/terraform/module.ts
- plugins/terraform/test/.gitignore
- plugins/terraform/test/terraform.ts
- plugins/terraform/test/validation.ts
Fixes https://github.com/garden-io/garden/issues/4508
We should make a release after merging this PR, as currently terraform module configurations will not work on Bonsai.
We should clean up these tests a bit some other day in a separate PR.
> fix: terraform module validation

- core/src/plugins/exec/deploy.ts
- core/src/process.ts
- core/test/data/test-project-exec/module-local-persistent/garden.yml
- core/test/unit/src/plugins/exec/exec.ts
Shelling out to the `kill` command was not portable, and the parent process also did not get the termination signal.
> fix(exec): cleaning up persistent processes didn't work in some cases

- core/src/commands/base.ts
- core/src/commands/get/get-config.ts
- core/src/garden.ts
- docs/reference/commands.md
To be used in Garden Desktop. This is quick and dirty just to unblock client dev, will fill in project/plugin-specific suggestions later.
> chore: return list of suggested commands in `get config` output

- core/src/build-staging/build-staging.ts
- core/src/tasks/build.ts
Ensure build context being available even if the plugin handler returns `ready` status for the action. For example if a container is already built but the build context has additional files needed for the Deploy.
closes: https://github.com/garden-io/garden/issues/4513
> fix: ensure build context on ´ready´ status builds

- core/src/cloud/api.ts
- core/src/commands/base.ts
Instead of current lengthy urls in cli, it shows a short url of  format <domain>/go/<shortlink>.
Fixes #4295
> fix: show short url for cloud

- support/alpine.Dockerfile
This backports the new methods of installing the latest versions of AWS CLI, azure CLI and Google Cloud CLI from the main branch (Bonsai).
Fixes #4571 because there is an incompatibility between AWS CLI v1 and the latest helm versions.
> 0.12 backport chore(deps): update AWS CLI, google cloud CLI and azure CLI to latest versions

- core/src/commands/dev.tsx
- core/src/commands/serve.ts
Dev command wasn't working if a few plugins outside of garden core were initialized (incl. terraform and pulumi).
Fixed by properly setting class plugins and session id params on action call.
closes https://github.com/garden-io/garden/issues/4529
Took me a shameful lot of time to get to the bottom of this but at least I'm more familiar with the `GardenInstanceManager` singleton and `serve` command now.
cc @worldofgeese
> fix: dev command not working with some plugins

- core/src/mutagen.ts
- core/src/plugins/kubernetes/commands/sync.ts
- core/src/plugins/kubernetes/container/build/common.ts
Add some warnings on too-long sync paths to make the error details more informative. See individual commits for details.
Mitigates #4527
I skipped the FAQ docs update. The warnings are visible well enough to users. And this problem occurs not that often for be a Frequently asked question :)
The commits will be squashed before the merge.
> chore: fire warnings on too long sync paths

- core/src/commands/logs.ts
- gulpfile.ts
Shows proper list of deploy names instead of `[object Object]` in error output.
Additionally, disables info output for license check plugin that was enabled by mistake in #4553
Fixes #4594 
> fix: show correct deploy name in logs error output in case of unknown deploy

- core/src/plugins/kubernetes/api.ts
- core/src/plugins/kubernetes/logs.ts
- core/test/integ/src/plugins/kubernetes/container/build/buildkit.ts
First commit fixes [this test failure](https://app.circleci.com/pipelines/github/garden-io/garden/17859/workflows/69bf2bb2-0617-4fa3-aa16-a59658881c34/jobs/311020?invite=true#step-112-515). This is also fixes a real bug for users.
second commit fixes [this test case](https://app.circleci.com/pipelines/github/garden-io/garden/17859/workflows/69bf2bb2-0617-4fa3-aa16-a59658881c34/jobs/311020?invite=true#step-112-508). cluster buildkit is not supported on microk8s. There's a conversation to be had about allowing to run the buildkit tests on minikube but that's unrelated to this pr.
third commit fixes an infinite retry loop and [these flaky tests](https://app.circleci.com/pipelines/github/garden-io/garden/18355/workflows/c81b92d3-e133-479c-b4d7-e928a2a932ca/jobs/324610?invite=true#step-110-531) …
> fix: microk8s issues (and all the integ tests)

- core/src/plugins/kubernetes/api.ts
It seems that one 500ms delay retry [wasn't enough](https://app.circleci.com/pipelines/github/garden-io/garden/18394/workflows/04f7f878-c4b5-4da9-9964-c0e5b32c8725/jobs/325915?invite=true#step-110-535)
> chore: retry pod creation three times

- core/src/config/project.ts
- core/src/garden.ts
- core/test/unit/src/config/project.ts
Before this fix, the namespace we read from the project config when creating the instance key wasn't resolved. This caused down stream issues for the instance manager.
Fixes #4597 
> fix(garden): ensure namespace is resolved when getting instance key

- examples/rust/backend/Cargo.lock
- examples/rust/backend/dev.Dockerfile
- examples/rust/backend/release.Dockerfile
A quick PR to repeat some changes for our Rust example that I did over the weekend in a personal project:
- In the `dev` image used in `deploy --sync` mode, use `cargo binstall` to install `cargo watch` from binaries instead of building from scratch
- Update Rust base image to 1.70
- Run `cargo update` to update deps in lockfile
> chore(examples): improve rust example cold build time

- core/src/plugins/kubernetes/api.ts
This is a quickfix for Quickstart example demo in the Google Cloud Shell.
A quickfix for #4460
Fixes #4460
> improvement(k8s): catch k3s connectivity error and retry

- core/src/commands/base.ts
- core/src/server/commands.ts
- core/src/server/server.ts
This fixes an issue that was there all along but wasn't exposed until we fixed a separate issue with the instance manager (#4649). Until then the instance manager wasn't re-using instance properly and masking the underlying problem.
Before this particular fix, we were setting the log level on the Garden instances which doesn't work if we're re-using them. So either logs that shouldn't be visible were, or vice versa.
This fixes that by not tampering with the log level on the Garden instance but rather optionally overwriting it when running a given command.
Fixes #
> fix(server): ensure logs are displayed in dev command

- core/src/commands/sync/sync-status.ts
- core/src/plugins/kubernetes/container/sync.ts
- core/src/plugins/kubernetes/helm/sync.ts
- core/src/plugins/kubernetes/kubernetes-type/sync.ts
- core/src/plugins/kubernetes/status/status.ts
- core/src/plugins/kubernetes/sync.ts
Before this fix, the `sync status` command would always show the status of active syncs for `kubernetes` Deploys as `not-active`.
This was because we were passing deployed resources for `container` and `helm` deploys when starting syncs and getting sync statuses, but passing local manifests for `kubernetes` deploys.
Fixes #4511
> fix(sync): fix status bug for `kubernetes` deploys

- core/src/cli/cli.ts
- core/src/commands/commands.ts
- core/src/commands/version.ts
- core/src/server/instance-manager.ts
- core/test/unit/src/cli/cli.ts
- core/test/unit/src/commands/version.ts
- docs/reference/commands.md
- Fixes custom commands not working on first run in dev mode.
- Also uses command artifact for `version` command so it is supported in dev mode and shows up in help.
Fixes #4647 
The second issue with custom gardenCommands reported in #4647 will be address separately. Tracking that with https://github.com/garden-io/garden/issues/4668
> fix custom commands in dev mode

- core/src/commands/deploy.ts
Throwing on using this flag is unnecessary and can trip users migrating from 0.12.
> fix(cli): ignore deprecated --skip-watch flag in deploy command

- core/src/commands/get/get-files.ts
- core/src/commands/get/get.ts
- docs/reference/commands.md
Came up in a customer conversation. Quite basic but also handy.
> feat(cli): add `get files` command to see files included in actions

- core/src/cloud/api.ts
- core/src/commands/base.ts
- core/src/commands/deploy.ts
- core/src/commands/helpers.ts
- core/src/commands/serve.ts
- core/src/commands/up.ts
When a command is run with an option that results in it being run inside the `dev` command instead (e.g. `garden deploy --sync`), we now register the initial command session with Cloud as a `dev` command with the `--cmd` option set appropriately. This is useful for Cloud when listing command sessions created this way.
For good measure, we include an explicit `isDevCommand` parameter with the session registration request to Cloud to make this setup more robust against future changes (instead of inferring whether the command is a `dev` command from the `commandInfo` map).
I've verified that including the `isDevCommand` param in the registration request doesn't result in errors (it will be ignored by the API until …
> fix(cloud): properly handle dev delegation

- core/src/cloud/api.ts
- core/src/commands/base.ts
- core/src/commands/serve.ts
From commit message:
Before this fix we were printing links to the live page for command
results. This fixes that but in turn we need to deal with the
unshortened link until we add link shortening support for command
results page.
See also: https://github.com/garden-io/garden/issues/4683
Fixes #
> fix(cli): print correct link to web dashboard

- core/src/plugins/kubernetes/sync.ts
This gets rid of our custom sanitization function and also trims the source path to a relative path to make the key cleaner+shorter.
> fix(k8s): invalid session name error with e.g. underscore in username/path

- core/src/analytics/analytics.ts
- core/src/exceptions.ts
- core/test/unit/src/exceptions.ts
This adds minimal stack trace data from the code location where garden fails. It helps pinpoint at least the file and function where the error was thrown. 
Fixes #
> chore(analytics): add top of last stack trace to error metadata

- plugins/terraform/test/common.ts
- plugins/terraform/test/terraform.ts
- plugins/terraform/test/validation.ts
Fixes #4473 
We use node version `18.12` in the `circleci-runner` image.
We used to have an `nvm install` step in our CI, which actually updated node to the latest `18.x`. This was removed in https://github.com/garden-io/garden/pull/4451/files
Because of the #4467 issue and https://github.com/ZJONSSON/node-unzipper/issues/271 the `unzipper` extracted binaries can get corrupted when using node version `18.16` and above. After removing the `nvm` steps, we are back to using `18.12` and this should just work again.
Sidenote: in our `support` images, we are referring to node base image hashes that _are_ on `18.16`. We should unify the versions so that our entire repository is synced …
> chore: re-enable terraform plugin tests

- core/src/vcs/vcs.ts
- core/test/unit/src/garden.ts
- core/test/unit/src/vcs/vcs.ts
cherry picks #4660 to 0.12
Fixes #
> 0.12 back-port: fix: update version hash if a file is renamed

- core/src/vcs/vcs.ts
- core/test/unit/src/garden.ts
- core/test/unit/src/vcs/vcs.ts
Consider relative file path along with the file hash for version hash calculation. Previously, version was not updated if file is renamed without any change in its content.
Considers relative file path in content hash to cater for path changes (e.g. renaming).
Fixes #4661
This will probably mark all existing caches invalid due to different versions.
> fix: update version hash if a file is renamed

- core/src/actions/base.ts
- core/src/actions/types.ts
- core/src/events/util.ts
- core/src/graph/actions.ts
- core/src/router/build.ts
- core/src/router/deploy.ts
- core/src/router/run.ts
- core/src/router/test.ts
Before this fix, `log` events emitted by router methods wouldn't include the same `actionUid` as the status events emitted by the `emitGetStatusEvents` and `emitProcessingEvents` helpers. This led to those action logs not loading in Cloud.
This was because the memoized `getUid()` instance method on the `BaseTask` didn't result in the UID being passed on to the resolved (and later, the executed) action, since those are initalized with the same constructor params as their parent action.
This was fixed by explicitly including the `uid` in the base action constructor params, which means that it gets passed on to the resolved and executed phases of the action (if any).
> fix(cloud): emit stable action uids across phases

- core/src/template-string/functions.ts
- core/test/unit/src/template-string.ts
Before this fix, helper functions were being applied even on resolved string and the unsubstituted string was considered the string itself for helper function. 
Basically, in the [first resolveTemplateStrings of module](https://github.com/garden-io/garden/blob/main/core/src/resolve-module.ts#L358), when only `inputs` are available and keys like `environment` are missing, unresolved strings are fine as `allowPartial` is set to `true`. However, the helper functions were still being applied.
For example, for a template string like  
```
TEST:  "base64Encode(\"${environment.namespace}\")"`
```
base64Encode was being called for `environment.namespace` instead of the actual value and resulted in wrong values. So before the [2nd resolveTemplateStrings of …
> fix(template-strings): do not apply helper functions on unresolved string

- core/src/template-string/functions.ts
- core/test/unit/src/template-string.ts
cherrypicks #4692 into 0.12
Fixes #
> 0.12-Backport: fix(template-strings): do not apply helper functions on unresolved string

- core/src/constants.ts
- docs/reference/module-types/jib-container.md
- examples/jib-container/spring-boot/spring-boot.garden.yml
- plugins/jib/build-tool-base.ts
- plugins/jib/gradle.ts
- plugins/jib/index.ts
- plugins/jib/maven.ts
- plugins/jib/mavend.ts
- plugins/jib/util.ts
Cherry-pick #4695 and #4709 to `0.12`.
Fixes #
> 0.12 back-port: allow custom `mvnd` binaries and concurrent Maven builds

- core/src/plugins/kubernetes/sync.ts
A recent change introduced kebab-casing for the sync keys used with Mutagen, but this wasn't applied in the sync prefix helper. This led to syncs not being stopped by the `sync stop` command.
> fix(k8s): fix regression in  sync stop logic

- core/src/plugins/kubernetes/helm/deployment.ts
Before this fix, ingresses of resources deployed with helm were missing in response of deploy and therefore, were not being shown in cli output as well as on the cloud.
Fixes #4732
> fix(helm): expose ingresses of resources deployed with helm

- core/src/util/ext-tools.ts
Just prints the version of a downloaded plugin tool along with its name.
Output before:
```
✔ build.spring-boot    → Fetched maven (took 7.3 sec)
```
Output after:
```
✔ build.spring-boot    → Fetched maven 3.8.8 (took 7.3 sec)
```
Fixes #
> chore: print version of the fetched tool

- core/src/plugins/kubernetes/kubernetes-type/config.ts
- core/src/plugins/kubernetes/kubernetes-type/handlers.ts
- core/src/plugins/kubernetes/status/status.ts
- core/test/integ/src/plugins/kubernetes/kubernetes-module/config.ts
- docs/reference/action-types/Deploy/kubernetes.md
- docs/reference/module-types/kubernetes.md
> feat(k8s): introduce new flag waitForJobs to wait for k8 jobs

- core/src/plugins/kubernetes/namespace.ts
- core/src/plugins/openshift/openshift.ts
- core/test/data/openshift/demo-project/hello/garden.yml
- core/test/integ/src/plugins/openshift/tests.ts
> feat(openshift): Run and Test actions

- core/src/graph/actions.ts
in action pre-processing, only use the var files that are not template strings as those are resolved and populated later.
Fixes #4702
> fix: don't use var file when path is unresolved

- core/src/plugins/container/publish.ts
- core/src/plugins/kubernetes/container/publish.ts
Fixes https://github.com/garden-io/garden/issues/4095
> fix: respect deploymentRegistry in the garden publish command

- e2e/projects/remote-sources-modules/garden.yml
This PR changes the repository URL of the `web-services` remote sources to the [`0.14` branch](https://github.com/garden-io/garden-example-remote-sources-web-services#0.4). That branch is a module-based version of the project.
This only fixes the Python runtime errors in `api` module in [e2e-vote-modules](https://app.circleci.com/pipelines/github/garden-io/garden/18749/workflows/6348dc30-0a6d-45bf-bb14-407ad1742a0e/jobs/337115). The e2e tests are still flaky.
> chore(test): update remote source repo link

- e2e/projects/vote-modules/vote/Dockerfile
An attempt to resolve the failing e2e vote-module tests. Updates the node version in vote-module test project. 
The test seemed to be failing due to some dependencies issue in the vote `build` and since the dependencies layer was cached by kaniko, every build of `vote` resulted in bad dependencies.
Updating node version should result in invalidating of the kaniko dependencies layer cache and fetch dependencies again.
> ci: fix e2e vote-module test

- core/src/plugins/kubernetes/api.ts
- core/src/plugins/kubernetes/kubectl.ts
- core/src/plugins/kubernetes/retry.ts
A follow-up PR for #4657. The original PR introduced an error message pattern to enable retries for k3s deployment errors. However, the retries didn't work because the deployment was done over the `kubectl` command instead of `KubeApi`.
This PR wraps the most frequently used `kubectl` calls into the retry machinery that is used in `KubeApi`. The retry settings are customized to avoid too-long retry intervals.
Fixes #4460
See individual commits for details. Most of the changes are related to the dedicated refactoring commit https://github.com/garden-io/garden/pull/4749/commits/707d176c250fae41440f7f0d32e2edbf4c7752ff.
I tested the fix twice with Google CloudShell and got no errors …
> improvement(k8s): ensure retries for most frequent `kubectl` calls

- core/src/cloud/api.ts
- core/src/commands/base.ts
Show shorter cloud url for command result
Fixes #4683
> feat(cloud): display short url for command result

- core/src/router/base.ts
handler results are already validated here:
https://github.com/garden-io/garden/blob/c16bff6c9e4caa11f26211b0f1af9c2d73009aa3/core/src/router/base.ts#L380
closes [#4544](https://github.com/garden-io/garden/issues/4544)
> chore: remove handler validation todo comment

- core/src/cli/autocomplete.ts
- core/src/cli/params.ts
- core/src/cloud/buffered-event-stream.ts
- core/src/logger/renderers.ts
- core/src/logger/writers/json-file-writer.ts
- core/src/logger/writers/json-terminal-writer.ts
- core/src/plugins/kubernetes/run.ts
- core/src/plugins/kubernetes/status/pod.ts
- core/src/watch.ts
Replace `JSON.stringify` with [`json-stringify-safe`](https://github.com/moll/json-stringify-safe) - a lightweight wrapper on top of `JSON.stringify`. [NPM trends](https://npmtrends.com/circular-json-vs-fast-safe-stringify-vs-json-stringify-safe) show it as the most frequently used library.
This might address #4592
> chore: use `safe-json-stringify` in logging and output rendering

- core/src/graph/actions.ts
- core/src/vcs/git.ts
- core/test/unit/src/actions/action-configs-to-graph.ts
- docs/using-garden/actions.md
- docs/using-garden/configuration-overview.md
> file inclusion improvement + docs

- core/src/garden.ts
- core/test/unit/src/cli/cli.ts
- core/test/unit/src/garden.ts
- docs/using-garden/variables-and-templating.md
allows to override nested variables using dot notation.
So if there's a config like following:
```
kind: Project
name: example-nested-vars
environments:
- name: local
providers:
- name: local-kubernetes
environments: [local]
namespace: ${project.name}-testing-${var.userId}
variables:
userId: ${local.username}
foo:
bar: something
somevar.withdot: oldvalue
examplevar: someoldvalue
```
it's possible to override variable values in garden deploy:
```
garden deploy --var foo.bar=newvalueofbar,somevar.withdot=mynewvalue,examplevar=hello
```
Fixes #3873 
> fix(cli): override nested variables using dot notation

- core/src/garden.ts
- core/src/graph/actions.ts
- core/test/unit/src/actions/action-configs-to-graph.ts
A follow up PR to #3873 for addressing #4772. Previously, variables set using the --var cli flag only had impact on the
project level variables. 
Fixes #4772
> fix: override action variables via --var cli flag

- .circleci/config.yml
- core/package.json
- core/src/plugins/kubernetes/api.ts
- core/src/plugins/kubernetes/namespace.ts
- yarn.lock
* chore: move away from k8s javascript client fork
The changes in the fork have been released. We can move away from the
fork.
* ci: make sure to use fresh cache when yarn.lock changes
This is to avoid running into caching issues
* fix: pin down version to 0.18.0
We had to pin the version to 0.18.0 because with 0.18.1 we ran into a problem due to kubernetes client's migration from execa to child_process.spawnSync, see also https://github.com/kubernetes-client/javascript/issues/1013
Makes it possible to merge https://github.com/garden-io/garden-platform/pull/2694
> forgotten cherry-pick from 0.12: chore: move away from k8s javascript client fork (#3967)

- core/src/cloud/api.ts
- core/src/cloud/buffered-event-stream.ts
- core/src/commands/base.ts
- core/src/events/events.ts
Previously we'd send a "sessionCompleted" event which caused Cloud to display the wrong command status.
This is really just a quickfix since it's urgent but we should add some tests here.  
Fixes #
> fix(cloud): send "sessionFailed" event if result has errors

- core/src/commands/sync/sync-status.ts
Fixes https://github.com/garden-io/garden/issues/4748
Added a breakpoint in the debugger and looked around, did not find any obvious variables/flags denoting that we would be within an interactive `garden dev` repl. Removing the hint message entirely, instead of only in dev mode.
> chore: remove output flag hint from sync status

- examples/templated-k8s-container/template/garden.yml
This is a very simple PR to fix Garden attempting to pull from a non-existent Docker registry. Garden should always build and push our templated image.
The `imagePullPolicy: "Always"` setting in Kubernetes means that it will always attempt to pull the image from a Docker registry.
Since we're using the templated `Build` image for our manifest, I've removed this line, which automatically sets `ImagePullPolicy: IfNotPresent`, our desired behavior.
> chore(example): remove `imagePullPolicy` from `templated-k8s-container`

- core/src/actions/base.ts
- core/src/garden.ts
- core/src/graph/actions.ts
- core/test/unit/src/actions/action-configs-to-graph.ts
What it says on the tin. Pretty straightforward, really.
> feat(config): allow multiple actions with same key if all but one is disabled

- core/src/plugins/container/build.ts
- core/src/plugins/kubernetes/container/handlers.ts
- plugins/jib/index.ts
- plugins/jib/test/util.ts
- plugins/jib/util.ts
Respect the `spec.publishId` for publishing the image using `garden publish`.
Fixes #4796
> fix: respect spec.publishId for publishing image

- core/src/template-string/functions.ts
- core/test/unit/src/template-string.ts
Fixes handling of `null` values as helper function arguments and allows empty strings as valid args in `isEmpty()` helper function.
Fixes #3398
The original issue was reported in Garden 0.12. This fixes the `0.12` branch, and the fix still needs to be ported to the `main` branch. The 0.13 PR is #4810.
> 0.12 fix(template): allow `null` as a valid argument in helper functions

- core/src/commands/base.ts
- core/src/events/events.ts
- core/src/server/server.ts
Before this change, we only POSTed session events over http but did not send over ws.
It's actually useful to do that as well so that we can better display currently running commands on the live page.
NOTE: Also reverted a change to the "commandStart" event from the following commit: a1742a6d7cea4425803399a511346ab54415d91d since we're now reading this data via "commandInfo" events
Fixes #
> improvement(server): also send sessions events over ws

- core/src/analytics/analytics.ts
- core/src/analytics/helpers.ts
- core/src/exceptions.ts
- core/src/graph/nodes.ts
- core/src/graph/results.ts
- core/src/graph/solver.ts
- core/test/unit/src/analytics/analytics.ts
- core/test/unit/src/exceptions.ts
Garden errors are aggregated in several steps when executing a graph. This PR simplifies the error reporting in analytics by only including the `lastError`. This is the last error added to the list of errors in the results of a graph execution. The struct reported back in analytics has detailed data on three levels:
- `error`, which refers to the top-most error
- `wrapped`, the first wrapped error in the top-most error
- `leaf`, the first leaf found when recursively iterating through wrapped errors. This is the most specific error and should provide a good indication of the error cause.
In addition to the new structure, we also started on an error context struct which can contain specific fields that would help identify task-types or plugins that …
> chore(analytics): improve error reporting structure

- scripts/changelog.ts
- scripts/draft-release-notes.ts
- scripts/release.ts
Aligned with `draft-release-notes.ts` script.
Used explicit version range instead of experimental `--next-tag` flag.
Fixes #
To be ported to `0.12` to fix the changelogs computed against the latest 0.13 version. This change has no visible effect in 0.13, but it must be applied as it is the semantically correct approach.
> chore: fix changelog generation

- scripts/changelog.ts
- scripts/draft-release-notes.ts
- scripts/release.ts
Aligned with `draft-release-notes.ts` script.
Used explicit version range instead of experimental `--next-tag` flag.
Cherry-picks #4827 to the `0.12` branch.
Fixes #
> 0.12 back-port: chore: fix changelog generation

- core/src/build-staging/build-staging.ts
- core/src/plugins/kubernetes/container/build/local.ts
- core/src/util/util.ts
The issue (#4815) happens on the build status check when the active provider has the `deploymentRegistry` configuration.
The action's build directory might not exist on the first build status check.
The underlying `docker` command does not use the action's build directory in any context. So, there is no reason to run the `docker` command from the action's build directory.
The `cwd` for the underlying `docker` command has been changed to the garden project root dir. Just like in a normal local status check in [`imageExistsLocally`](https://github.com/garden-io/garden/blob/main/core/src/plugins/container/helpers.ts#L243).
Fixes #4815
> fix: local-docker build failure when `deploymentRegistry` is enabled

- core/src/resolve-module.ts
closes https://github.com/garden-io/garden/issues/4816
> fix: allow to use `parent.name` template in templated modules

- core/src/plugins/container/container.ts
Updates the bundled Docker CLI from 20.10.9 to 24.0.4
Fixes #4550
I couldn't find the SHA256 hashes of published packages officially, except for the windows binary (that we download from Github). So, i computed the SHA256 hashes manually of downloaded packages using `shasum` utility on mac.
> improvement: update docker to v24.0.4

- core/src/plugins/container/container.ts
Backports #4840 to 0.12
Fixes #
> 0.12-backport: update docker to v24.0.4

- core/src/commands/exec.ts
- core/src/plugin/handlers/Deploy/exec.ts
- core/src/plugins/kubernetes/container/deployment.ts
- core/src/plugins/kubernetes/container/exec.ts
- core/src/plugins/kubernetes/kubernetes-type/common.ts
- core/src/plugins/kubernetes/kubernetes-type/exec.ts
- core/src/plugins/kubernetes/logs.ts
- core/src/plugins/kubernetes/run.ts
- core/src/plugins/kubernetes/util.ts
- core/test/integ/src/plugins/kubernetes/container/deployment.ts
- core/test/unit/src/commands/exec.ts
- docs/reference/commands.md
Introduces a flag `--target` in `exec` command. This is useful when a Deploy action consists of multiple underlying components and user wants to target a specific one.
At the moment, this flag is only supported for kubernetes-exec and container-exec. When a pod has multiple containers, user can use `target` flag to exec into a specific container. Additionally, if no container name is provided, it respects the annotation `kubectl.kubernetes.io/default-container` and defaults to that container. The existing behavior is still the default: it picks the first container in Pod.
This PR also adds the default container annotation in the manifests generated with `container` type.
Fixes #3039
**Special notes for your …
> introduce --target option for exec command to target specific container in pod

- scripts/release.ts
Reverts #4827 and #4847. Function `getChangelog` can't be used because the target tag doesn't exist when we generate the changelog.
Fixes #
> chore: fix missing tag error in changelog generation

- scripts/release.ts
Reverts #4828 and #4847<F69.
Function `getChangelog` can't be used
because the target tag doesn't exist when we generate the changelog.
(cherry picked from commit 3c15d08c387f371cef339a87045ba23c1b3ead23)
Fixes #
> 0.12 back-port: chore: fix missing tag error in changelog generation

- .circleci/config.yml
- core/src/plugins/kubernetes/local/microk8s.ts
> fix(k8s): install `microk8s` addons sequentially

- support/docker-bake-test.sh
Use new `garden version` command instead of discontinued `garden --version`.
Fixes the way of checking the Garden version in the `docker-bake-test.sh` script.
Without this PR the command fails silently with OK exit status like this:
<details>
```console
USAGE
garden <command> [options]
COMMANDS
build          Perform your Builds.                                                     
cleanup        Clean up resources.                                                      
cloud          Manage Garden Cloud/Enterprise resources such as users, groups and       
secrets.                                                                 
community      Join our community Discord to chat with us!                              
config         Configure user and …
```
> ci(dockerhub): fix garden version checks

- core/src/vcs/git.ts
- core/test/unit/src/vcs/git.ts
This can be a major optimization in certain cases.
The reason this wasn't done previously was due to a git ls-files issue but we missed out on this path when no includes are used, in which case the issue doesn't come up.
Usually includes are much more specific than excludes in configs, so this approach should cover a lot of user scenarios.
It is still more optimal to use `.gardenignore` files over exclude patterns where possible, but using excludes in configs is obviously  a common and supported use case, and not always possible to use the ignore files (say, if many actions/modules share a directory and need different exclusions).
Fixes #4763
> perf(git): optimize git scan when exclude but no include filter is set

- core/src/mutagen.ts
- core/src/plugins/kubernetes/commands/sync.ts
- core/test/integ/src/plugins/kubernetes/commands/sync.ts
Use directory at shorter path for mutagen syncs if the project path is longer than `MUTAGEN_DATA_DIRECTORY_LENGTH_LIMIT`. The shorter directory path is computed using hash of the path of .garden dir in project and appending to `$HOME/.garden/mutagen`.
Fixes #4527 
> fix(mutagen): use shorter directories for mutagen syncs

- support/alpine.Dockerfile
- support/buster.Dockerfile
We do not need an ENTRYPOINT, and azure devops only supports images
without it.
Fixes #4818
> fix: restore azure devops support for dockerhub images

- core/src/config/template-contexts/actions.ts
- core/src/template-string/template-string.ts
- core/test/data/test-projects/template-strings/garden.yml
- core/test/unit/src/template-string/template-strings-e2e.ts
The regression was introduced in #4659.
In that PR `this.variables` field was overwritten with the action-level values. It caused the erasure `this.variables = garden.variables` assignment in the super-class constructor.
Fixes #4830
See individual commits. There is more explanation in the commit messages.
> fix(template): respect project level variables in action config context

- core/src/config/base.ts
- core/test/data/test-project-multiple-project-configs/garden.yml
- core/test/data/test-project-multiple-project-configs/project.garden.yml
- core/test/unit/src/config/base.ts
throw an error if multiple project configs are found across multiple files in a dir (e.g. in garden.yml and project.garden.yml)
Fixes #3210
> fix(config): throw error if multiple project configs are found

- docs/tutorials/migrating-to-bonsai.md
Document the breaking change in the Run command caching. Now the caching is enabled by default.
Fixes #4890
> fix(docs): update migration guide

- core/src/plugins/kubernetes/kubernetes-type/common.ts
- core/test/data/test-projects/kubernetes-type/with-build-action/deployment-action.yaml
- core/test/data/test-projects/kubernetes-type/with-build-action/with-build.garden.yml
- core/test/integ/src/plugins/kubernetes/kubernetes-type/common.ts
The regression was introduced in #4516. After that PR, it was possible to silently skip all non-existing files specified in in `spec.files` of a Deploy action of type `kubernetes`.
In `0.13.6` that would fail with error like this:
```console
ENOENT: no such file or directory, open '~/garden/core/test/data/test-projects/kubernetes-type/with-build-action/deployment-action1.yaml'
```
This PR implements some explicit checks for path existence and makes the output a bit more readable:
```console
Invalid manifest file path(s) in Deploy action 'with-build-action'. Cannot find manifest file(s) at ~/garden/core/test/data/test-projects/kubernetes-type/.garden/build/exec-build/deployment-action1.yaml
```
Issues #4505 and #4506 still exist. That's why the …
> fix(k8s): regression in globs in k8s manifest files

- core/src/plugin/base.ts
- core/src/plugins/kubernetes/run.ts
- core/src/tasks/run.ts
- core/src/tasks/test.ts
- docs/reference/commands.md
We now only log the full pod status on the debug log level and above when a Test or Run fails.
This makes e.g. logs for failing Tests much less verbose by default, which should be a UX improvement.
> improvement(k8s): less verbose Run/Test errors

- core/src/commands/set.ts
- core/test/unit/src/commands/set.ts
Adds a check to not allow setting an invalid environment as default env.
Fixes #4922
> fix: only allow a valid environment to be set as default env

- core/.mocharc.yml
- core/package.json
- core/src/config/constants.ts
- core/src/config/render-template.ts
- core/src/graph/actions.ts
- core/src/template-string/functions.ts
- core/src/template-string/template-string.ts
- core/test/data/test-projects/merge-in-module-template/Dockerfile
- core/test/data/test-projects/merge-in-module-template/bug-demo.garden.yml
- core/test/data/test-projects/merge-in-module-template/manifests-template.yml
- core/test/data/test-projects/merge-in-module-template/project.garden.yml
- core/test/data/test-projects/merge-in-module-template/schema.json
- core/test/unit/src/resolve-module.ts
- core/test/unit/src/template-string.ts
Fixes an issue where in Action / Module templates there would be variable used to iterate over using `$foreach` which cannot be resolved in partial application using `allowPartial: true` but still gets returned as an object.
We now check if something returned to iterate over still includes unresolved 'magic' keys and in case that is the case, it tries to resolve them again in non-partial mode, or just returns the original unresolved value in partial mode.
That ensures that we do not iterate over those until the final non-partial application of the templating.
Fixes https://github.com/garden-io/garden/issues/4880
> fix: templated module templating

- .circleci/config.yml
- cli/package.json
- cli/src/build-pkg.ts
- core/src/commands/self-update.ts
- core/src/mutagen.ts
- core/src/plugins/container/container.ts
- core/src/plugins/hadolint/hadolint.ts
- core/src/plugins/kubernetes/helm/helm-cli.ts
- core/src/plugins/kubernetes/kubectl.ts
- core/src/plugins/kubernetes/kubernetes-type/kustomize.ts
- core/src/plugins/octant/octant.ts
- core/src/plugins/otel-collector/otel-collector.ts
- core/src/util/util.ts
- docs/reference/providers/octant.md
- plugins/conftest/index.ts
- plugins/jib/gradle.ts
- plugins/jib/maven.ts
- plugins/jib/mavend.ts
- plugins/jib/openjdk.ts
- plugins/pulumi/cli.ts
- plugins/terraform/cli.ts
- scripts/draft-release-notes.ts
- support/install.sh
- yarn.lock
This PR adds ARM64 support for MacOS and Linux.
Not all dependencies are supported yet - specifically for the jib plugin on Linux - but those that are have been added.
It also updates the install script to pick the correct architecture, and it updates the self-updater to update to the ARM version when available and pick the AMD64 version otherwise.
Homebrew still requires an update to the formula to pick based on the architecture, but I believe we can do that separately which will also be a bit easier once the builds already exist. The homebrew formula is updated by a github action which doesn't support two different binaries right now, so that needs changes as well.
I have tested the ARM build for MacOS on MacOS and the Linux one inside a VM. …
> feat: add ARM64 support

- core/src/commands/self-update.ts
Ensures that self-update to bonsai-edge keeps installing arm builds if available.
This should always work since there won't be any more versions without an ARM build unless we remove the option altogether.
Fixes #
> feat: allow arm installs for self-update to bonsai-edge

- core/src/commands/self-update.ts
- core/src/util/util.ts
Currently everyone is running an amd64 build.
That means everyone is running under rosetta at the moment.
Due to the OS always reporting it's x86, it would thus never update to the ARM build if available.
We now detect if we are running under emulation and if so, we request the ARM build if possible.
Fixes #
> fix: detect rosetta emulation during self-update

- .circleci/config.yml
Makes sure that we update the tag for `edge-bonsai` when we make a prerelease for it.
Also updates the release to point to the new edge tag.
That way the edge release should always be up to date with the correct pointer and be easily findable in GH.
Fixes #
> build: fix edge release

- .circleci/config.yml
We didn't checkout the code for the prerelease step so the added tagging now fails.
This should fix it.
Fixes #
> fix: checkout repo before prerelease

- core/src/plugin/tools.ts
- core/src/util/util.ts
- plugins/jib/mavend.ts
- plugins/jib/openjdk.ts
The native aarch64 build of maven has not been used before this commit,
because the arch was wrongly specified as "aarch64" in the tool spec,
instead of the correct "arm64".
This commit also prevents similar mistakes in the future by improving
the types.
We are allowing platforms and architectures that are not technically supported right now here–
this can be adressed in a future PR if needed.
Fixes #
> fix(jib): make native arm maven usable on ARM macs

- core/src/graph/graph-execution-overview.md
I wrote some internal documentation on how graph execution (solver + task classes) works in Garden.
This should be useful for contributors (and might be interesting for power-users).
> docs: added internal docs for solver flow

- .circleci/config.yml
- images/circleci-runner/Dockerfile
- images/circleci-runner/garden.yml
github fixed cli/cli#6680
Let's use the latest version of gh in CircleCI. This will also fix the [github-edge-prerelease](https://app.circleci.com/jobs/github/garden-io/garden/362715)
Fixes #
> fix(circleci): use latest gh cli utility

- core/src/actions/types.ts
- core/src/graph/actions.ts
- core/src/plugins/kubernetes/helm/status.ts
- core/test/unit/src/actions/action-configs-to-graph.ts
With this PR, we avoid marking an action's implicit dependency as needing execution if a static output of dependency is referenced.
Fixes #4920
> fix: avoid action execution for the static outputs references of implicit dependencies.

- core/src/config/render-template.ts
- core/src/resolve-module.ts
- core/test/data/test-projects/template-configs/garden.yml
- core/test/data/test-projects/template-configs/schema.json
- core/test/unit/src/resolve-module.ts
Before this fix, we weren't performing a partial resolution pass on module template inputs before validating them against the input schema. This looks like it was a simple oversight (there's definitely no point in partially resolving an always-empty object).
This would result in validation errors e.g. when the schema declares a boolean field but the unresolved template is still a string value.
Fixes #4946.
While looking at the code around input resolution and validation, I noticed that we never apply the input schema (as defined in e.g. `schema.json`) against the fully resolved inputs.
It looks like the idea here is to allow the user to pass through template strings that …
> fix(core): input validation for module templates

- core/src/commands/deploy.ts
- core/src/commands/run.ts
- core/src/commands/self-update.ts
`build` offered the `-f` alias for `--force`, but all other commands did
not. I found myself trying to run `garden deploy -f` multiple times and
it failed, so let's just make it consistent.
Fixes #
> improvement: always offer -f as alias with --force

- core/src/commands/create/create-project.ts
- core/test/unit/src/commands/create/create-project.ts
- docs/k8s-plugins/remote-k8s/README.md
- docs/tutorials/your-first-project/1-initialize-a-project.md
The previous yaml generated by the docs-generator looked like this:
```yaml
#
#
#
kind: Project
name: foobar
environments:
- # The name of the environment.
name: default
providers:
- # The name of the provider plugin to use.
name: local-kubernetes
```
While it is cool that we are re-using the descriptions from our docs,
there are some problems with this yaml code:
- The comments often do not add any valuable information. For example
it's already clear that `name: foobar` is the name of the project.
- Another problem is that the description in the reference docs is not
necessarily the information a user needs when getting started. This
becomes apparent in the comment above `apiVersion`, for example.
This commit simplifies the …
> improvement: more useful "create project" yaml

- core/src/plugins/kubernetes/local/config.ts
- docs/k8s-plugins/local-k8s/install.md
Adds [orbstack's new native local Kubernetes offering](https://docs.orbstack.dev/kubernetes/) to the list of supported local Kubernetes providers. It is super fast, easy to use and works out of the box since it uses K3s.
Fixes #
> docs: add orbstack to supported local Kubernetes providers

- core/src/plugins/kubernetes/kubectl.ts
Before this we were printing all the manifests we were applying at the verbose level which imo is too low a level and can make the logs very noisy.
Noticed this e.g. when streaming logs via the dashboard.
Fixes #
Assigning @stefreak since you added this. Not sure if it was intentional or not, but don't you agree that this should be debug as opposed to verbose?
> improvement(plugins): debug log manifest dump

- core/src/plugins/kubernetes/helm/deployment.ts
- core/src/plugins/kubernetes/helm/handlers.ts
- core/src/plugins/kubernetes/helm/status.ts
- core/src/plugins/kubernetes/kubernetes-type/handlers.ts
- core/src/plugins/kubernetes/port-forward.ts
- core/test/unit/src/plugins/kubernetes/port-forward.ts
Just a quick PR to minimize the changeset in #4846. That will make conflict resolution easier.
Fixes #
> refactor: move mode checks to `getForwardablePorts`

- docs/k8s-plugins/action-types/kubernetes.md
The docs about the Kubernetes deploy action had a little mistake where the action was a helm type instead of kubernetes.
Fixes #
> docs: fix wrong use of helm deploy in docs about kubernetes deploy

- core/src/commands/update-remote/actions.ts
When there were no `actionSources` during a remote update, `pMap` was still called but the concurrency would have been set to 0.
That would cause an error and lead to it failing.
Now we only call the map if the `actionSources` are actually there.
fixes https://github.com/garden-io/garden/issues/5035
> fix: do not error if actionSources are empty

- docs/README.md
- docs/basics/use-cases.md
Adds a "Use Cases" page to the "Basics" section of our docs. 
The end goal is to have a link to a case study and a detailed how to guide for each of the use cases but we just don't have them for all of these at the moment, so instead it's more of a high level overview as things stand. 
The idea was also to split this up into individual pages so that they're visible from the front page, but if it's all the same I'd like to do that in a follow up PR.
We're making quite a few changes to the docs and it'll be easier to split this up and cross link once all those changes have been merged. Otherwise we'll just end up wasting time moving links around as we iterate on this. 
Fixes #
> docs: add a 'Use Cases' page

- core/src/plugins/kubernetes/api.ts
- core/src/plugins/kubernetes/kubectl.ts
- fix: use forceRetry when using requestWithRetry with kubectl command
- fix: use correct manifest loglevel in the error message
Fixes #
> fix: avoid crash during kubectl retry

- core/src/plugins/exec/deploy.ts
- core/src/plugins/exec/run.ts
- core/src/plugins/exec/test.ts
This PR prints the Run and Test action output on the INFO log level, just like in 0.12.
Fixes #4983
We can also consider introducing a flag called `--show-output` and enable it by default for Run and test actions.
> fix: print the output of Run and Test actions on the info log level

- scripts/install-osx-dependencies.sh
- support/homebrew-formula.rb.j2
According to our install guide we only depend on rsync on Windows.
See also https://docs.garden.io/guides/installation
Fixes https://github.com/garden-io/homebrew-garden/issues/8
> fix: remove rsync dependency from homebrew formula

- images/buildkit/Dockerfile
This PR upgrades the moby/buildkit to [v0.12.2](https://github.com/moby/buildkit/releases/tag/v0.12.2), which, among other improvements, adds the `--secret` flag which will allow secrets to be mounted into buildkit builds without including them in the final image layers. This is a security improvement, as it helps prevent secrets from leaking out in the image layers, if used properly by end users.
Technically, the secrets flag was added in [v0.12.0](https://github.com/moby/buildkit/releases/tag/v0.12.0), but I am assuming that it would be a better use of everyone's time if we went directly to the most recent Z release.
Fixes #
> improvement(build): update moby/buildkit to v0.12.2

- .circleci/config.yml
We disabled the checks to push through a big docs PR that briefly invalidated some URLs. We restore those here. In the future, contributors will read through our contributors to the docs page.
> test: restore docs checks

- core/src/plugins/kubernetes/container/build/buildkit.ts
- core/src/plugins/kubernetes/container/build/common.ts
- core/test/unit/src/plugins/kubernetes/container/build/buildkit.ts
- core/test/unit/src/plugins/kubernetes/container/build/common.ts
We need to use the "[Recreate](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#recreate-deployment)" strategy for garden-util and garden-buildkit deployments, because
otherwise we can run into issues where multiple Pods are running at the same time
Also with the latest main I often get an error "Could not find a running Pod in Deployment garden-buildkit in namespace xxx" – this change fixes that too.
e.g. Fixes #2570
The remote tests are covering this issue, but they are currently disabled in CI. Enabling them is out of scope for this PR, but will be addressed in #5103
> fix(remote-building): use "Recreate" strategy garden-util (kaniko) and garden-buildkit deployments

- core/src/config-store/base.ts
This removes the lock when reading from a global or local config file. The read lock can lead to dead-lock in situations where we trigger concurrent reads, e.g. in projects having multiple modules with linked sources. @nilium has provided a reproducible example here: https://github.com/nilium/garden-locker, see discord thread for more details: https://discord.com/channels/817392104711651328/1151269956240031826
__Is it safe to remove the read lock?__
- Concurrent reads are safe since they don't modify the state of the config.
- Writes need the lock since they perform a read + write of the config, which in the case of concurrent writes could result in a trace with R1, R2, W2, W1. Process 1 overwrites the values from process 2 leading to a potentially …
> fix: remove read lock from config get

- core/src/tasks/base.ts
Memoize was using an object as a cache key whose identity kept changing. Thus it never returned a cache hit and kept storing new objects in cache. With this fixed, memory consumption becomes a lot more reasonable, plus the cache actually yields the desired performance benefits.
Fixes https://github.com/garden-io/garden/issues/4638
> fix: memoize memory leak

- docs/k8s-plugins/local-k8s/README.md
Just saw that we forgot to add K3s and friends to our overview of supported local-k8s distros.
However we are not (yet) routinely testing against these distros in CI. Not mentioning them at all in this overview also seems wrong though.
EDIT: we have tests for K3s, which should cover sufficiently for rancher desktop and orbstack, who both use K3s under the hood.
Fixes #
> docs: add all supported local k8s distros to overview

- core/src/plugins/otel-collector/otel-collector.ts
I noticed that we were just checking if the array exists, which it always does.
Instead we need to check if it's empty.
Also removed the yarn release which we don't need anymore.
Fixes #
> fix: otel collector enabled detection

- package-lock.json
- package.json
Add `inquirer` in dependencies as it's used in release script. Had to install it for release script to work.
https://github.com/garden-io/garden/blob/62a16b252f05b2085ac416e280870616a064d98a/scripts/release.ts#L4-L6
> chore: add inquirer in dev dependencies

- cli/src/build-pkg.ts
Fixes an issue with the built binaries not including fsevents in core/node_modules.
Fixes #5146 
> fix: include fsevents in core instead of cli

- core/package.json
- core/src/server/server.ts
- core/test/unit/src/server/server.ts
- package-lock.json
> fix(server): ensure using a free port for dev console

- core/src/graph/nodes.ts
- plugins/pulumi/src/commands.ts
- plugins/pulumi/src/helpers.ts
This enforces responses of type ValidResultType for the pulumi plugin commands for actions. Previously, the plugin commands for actions were not returning anything, resulting in runtime errors. The TS compiler didn't catch these due to the pulumi plugin command responses typed as `any`.
Fixes #5118
Fixes #5084
> fix(pulumi): return correct responses for pulumi plugin commands

- README.md
Separate Garden logo for dark mode in main README.
Dark mode looked like this:
now looks like this:
with light mode still looking like this:
> docs: separate logo for dark mode

- README.md
- docs/misc/faq.md
- docs/terraform-plugin/about.md
- docs/using-garden/tasks.md
- docs/using-garden/tests.md
- docs/using-garden/variables-and-templating.md
- examples/argocd/README.md
- examples/base-image/README.md
- examples/build-dependencies/README.md
- examples/conftest/README.md
- examples/demo-project/README.md
- examples/hadolint/README.md
- examples/istio/README.md
- examples/jib-container/README.md
- examples/kubernetes-module/README.md
- examples/kustomize/README.md
- examples/local-service/README.md
- examples/remote-k8s/README.md
- examples/remote-local-hybrid/README.md
- examples/remote-sources/README.md
- examples/vote/README.md
Fixes base docs URL to point to `https://docs.garden.io/v/acorn-0.12` in 0.12 documentation.
Fixes #
The `check-docs` CI step must pass.
> docs: fix docs base url

- core/src/commands/serve.ts
- docs/reference/commands.md
Patches #5163 to avoid any potential regression. The default server port number is now reverted back to `9777`, as before #5163.
Fixes #
> chore(server): restore the previous default server port number `9777`

- core/src/vcs/vcs.ts
- core/test/unit/src/garden.ts
- core/test/unit/src/vcs/vcs.ts
This PR cherry-picks 2 commits from the `main` branch:
* c17a6cfbd89384a7415cf259ce53b28c3e1c90ea
* 57d884a55f1175f491ada85fd158a3b74b5118a8
This is a pre-requisite for #5180 and should fix the [test-framework failures](https://app.circleci.com/pipelines/github/garden-io/garden/20816/workflows/42ec6f01-8f92-4e35-9e92-fad2b4012d46/jobs/400864).
Prior to this PR, individual test case `"should return module version if there are no dependencies"` from [`core/test/unit/src/garden.ts`](https://github.com/garden-io/garden/blob/main/core/test/unit/src/garden.ts) was failing, while the whole test suite was passing without errors.
Now, both scenarios pass without failures.
Some amendments …
> fix(core): more narrow set of config fields to hash for module versions

- core/src/actions/base.ts
- core/src/commands/get/get-actions.ts
`get actions --detail` command basically doesn't work in case one of the actions is disabled. Ran into this multiple times and it's so annoying.  With this PR, it stops throwing error for get actions, if an action is disabled. 
Fixes #4937
> fix: allow listing disabled actions in get actions cmd

- core/src/server/instance-manager.ts
- core/src/server/server.ts
That's a function, not a boolean we were evaluating so it always returned true. This fixes that.
Fixes #
> fix(core): ensure needsReload flag works

- core/package.json
- core/src/config/base.ts
- core/src/plugins/kubernetes/kubernetes-type/common.ts
- core/test/unit/src/config/base.ts
- core/test/unit/src/config/validation.ts
- package-lock.json
- plugins/pulumi/src/helpers.ts
- chore(deps): update yaml to 2.3.2
- fix: prevent crash due to unresolved alias in yaml
- improvement: use loadAndValidateYaml for both kubernetes manifests and garden configs
- test: add tests for loadAndValidateYaml
- improvement: eliminate explicit any in loadAndValidateYaml
Fixes #5186
This is a workaround for possible upstream bug described in https://github.com/eemeli/yaml/issues/497
Manual test looks like this:
```
% gdev deploy  
Deploy 🚀 
Garden v0.13 (Bonsai) is a major release with significant changes. Please help us improve it by reporting any issues/bugs here:
https://go.garden.io/report-bonsai
→ Run garden util hide-warning 0.13-bonsai to disable this warning.
ℹ …
```
> fix: prevent crash due to unresolved alias in yaml

- core/src/util/util.ts
Before this change, we logged stderr streams from
init scripts as errors but now we log it at the info level.
The reason is that some tools, e.g. gcloud, write to stderr even if it's
not an actual error.
In the case of an actual error the script exits with a non-zero
code and that's handled specifically.
So this is really just a cosmetic change to how exec provider logs are
rendered.
Fixes #
> improvement(core): log stderr from exec as info

- core/src/plugins/container/helpers.ts
- core/src/vcs/vcs.ts
- core/test/unit/src/plugins/container/build.ts
- plugins/jib/src/index.ts
- plugins/jib/src/util.ts
- plugins/jib/test/util.ts
In the container and jib-container build actions, we checked for the
existance of files checked in to version control for certain checks.
Garden allows for files to be injected into the build action dynamically
at run time, e.g. by using `copyFrom` and `generateFiles`.
We want to check for actual presence of files in the action's build
directory instead of checking for the files that are included from
version control.
Fixes #5201
> fix: allow generated files in build actions

- core/src/cli/helpers.ts
- core/src/commands/self-update.ts
- core/src/constants.ts
- core/test/unit/src/commands/self-update.ts
- docs/reference/commands.md
This is a 0.12 backport of #5229. Tests and code are ported over. ARM support was excluded from the backport since its only available from 0.13.12.
Fixes #4893 
> 0.12 backport: improvement: using new release endpoint for self-update

- core/src/cli/cli.ts
- core/test/unit/src/cli/cli.ts
This PR brings strict consistency into Garden command exit codes and fixes the possible CI problems like the ones we got in #4868.
Fixes #4911
This PR has been done in TDD mode :)
The test specs were written first.
~To be back-ported to `0.12`.~
TODOs (to be addressed in a separate PR):
* ensure the error message is always printed on unrecognized flag
* ensure the error message is always printed on unrecognized command or sub-command
> fix(cli): exit code 1 on unknown commands, sub-commands and flags

- markdown-link-check-config.json
CI reports this link as a dead one quite often:
```console
ERROR: 1 dead links found!
[✖] https://support.apple.com/en-us/HT211861 → Status: 0
```
The link is alive. Skip it to avoid false positive alarms in CI.
Some recent failure examples:
* https://app.circleci.com/pipelines/github/garden-io/garden/21128/workflows/dc36583b-49a0-4834-82c3-8cb176a606a4/jobs/411027
* https://app.circleci.com/pipelines/github/garden-io/garden/21128/workflows/722802a6-3440-40e2-ba46-1bb0aa2d26fa/jobs/410993
* https://app.circleci.com/pipelines/github/garden-io/garden/21128/workflows/33d42493-9c66-4d56-8854-c0748258e4dc/jobs/410982
* https://app.circleci.com/pipelines/github/garden-io/garden/21109/workflows/e39819ba-8816-47da-b00c-5cb5d5d3c890/jobs/410387
**Which …
> ci: omit a single link check in CI

- core/src/util/testing.ts
- core/test/unit/src/build-staging/helpers.ts
This approach covers the edge case
when 2 numeric values are in the same precision vicinity, but get rounded to the different values.
E.g. `a = 0.514` and `b = 0.516`.
The diff is `0.002`,
but the diff between rounded values was `0.01` before this fix.
This is a tiny fix, but without it, the CI fails from time to time. That could cost ~35m of waiting time in the merge queue.
CI failure example: https://app.circleci.com/pipelines/github/garden-io/garden/21172/workflows/b60898fb-d5d9-43f0-abab-ce3b99e9fd07/jobs/412425
Fixes #
> test: use more precise time comparison

- core/src/plugins/kubernetes/kubernetes-type/common.ts
- core/test/integ/src/plugins/kubernetes/sync-mode.ts
- core/test/unit/src/plugins/kubernetes/kubernetes-type/common.ts
This PR ensures the the module conversion respects the 0.13 schema validation rules, which are now stricter than in 0.12.
Fixes #5269
A new function `convertServiceResourceSpec` was extracted to take more specific input parameters and to do the spec-to-spec conversion. This also allowed making the unit test data preparation way easier.
> fix(k8s): correct `0.12 => 0.13` service resource conversion

- core/src/exceptions.ts
- core/src/graph/nodes.ts
- core/src/resolve-module.ts
- core/test/unit/src/analytics/analytics.ts
- core/test/unit/src/exceptions.ts
- core/test/unit/src/garden.ts
Changes GardenError to expand the stack in the initializer already, so
that errors are always rendered expanded in mocha tests.
This greatly eases test development.
Fixes #
> test: make testFlags.expandErrors work with mocha error renderer

- examples/kubernetes-deploy/redis/redis.yml
Kubernetes only supports YAML 1.1, and we recently fixed a bug to read kubernetes manifests using the correct YAML version (#5184)
We accidentally did not update the example to use the old-style octal numbers. Searching for `0o` gives no further results at least in the garden repo.
Fixes #
> fix(examples): use yaml 1.1 octal numbers in kubernetes manifest files

- core/src/cloud/api.ts
Before this fix, 404 errors that happened when fetching secrets were logged at a debug level and not visible to users.
This fixes that and improves the error message. 
Related to #5275 because fixing that will reduce the chance of this error surfacing in the first place. 
Fixes #
> fix(api): visible and better error when fetching secrets 404s

- CONTRIBUTING.md
This fixes the broken links from CONTRIBUTING to our docs page.
> fix: change contributing redirect

- core/src/cli/command-line.ts
- core/src/cloud/buffered-event-stream.ts
- core/src/constants.ts
- core/src/logger/log-entry.ts
- core/src/monitors/logs.ts
- core/test/unit/src/logger/logger.ts
This commit adds a 'rawMsg' field to the log entry message type which can be used for log lines that don't map well between the terminal and the web dashboard.
The dashboard will prefer the 'rawMsg' if set.
This is e.g. used when streaming service logs but prior to this commit we added ansi colors to them which didn't play when e.g. rendering JSON logs in the dashboard.
The commit also use this field for rendering the command start/finish messages which are printed in the dev console and don't render nicely in browser when the divider is too long.
This is perhaps a bit hacky and we should probably just a have a log entry type "separator" that the browser can handle properly. But this does the trick for now.
Fixes # …
> improvement(logs): add 'rawMsg' field to logEntry

- core/src/garden.ts
Before this fix, we'd log a warning about secrets not existing for users on the community tier when in fact we shouldn't be attempting to fetch them in the first place.
Fixes #
> fix(cloud): do not fetch secrets on community tier

- core/src/graph/solver.ts
- core/src/logger/util.ts
- core/src/plugins/exec/build.ts
- core/src/plugins/exec/deploy.ts
Previously these actions were logged at the verbose level which doesn't really make sense imo.
In particular since other exec actions are on the info level so to the end user it'll be confusing that some exec results get logged and others not.
Also updated the various places where we render a divider to make sure we also include a browser friendly version.
Fixes #
> fix(logger): log exec build/deploy actions at info level

- core/src/plugins/kubernetes/container/status.ts
- core/src/plugins/kubernetes/status/status.ts
- core/test/integ/src/plugins/kubernetes/container/deployment.ts
- core/test/integ/src/plugins/kubernetes/helm/deployment.ts
- core/test/integ/src/plugins/kubernetes/kubernetes-type/handlers.ts
Before this fix, we were returning the action mode (e.g. `default`, `sync` or `local`) set on the locally generated manifests under `status.detail.mode` for `container` Deploys.
This meant that e.g. the `get status` command would always show the mode as `default`. The fix was to use the action mode set on the deployed resources, like we've been doing for `kubernetes` and `helm` Deploys.
Also added an integ test case for this behavior.
The usefulness of this fix is that it should allow the Cloud UI to rely on the action modes in deploy statuses to show e.g. the mode of Deploys in the graph view.
> fix(k8s): return deployed mode in container Deploy status

- core/src/plugins/kubernetes/helm/status.ts
> fix(helm): handle missing (null) values in version check

- plugins/pulumi/src/commands.ts
Method `resolveDependencies` was unused before this fix. However, it was implemented to handle the process dependencies. This commit renames it to override the corresponding method of the parent class, as it was initially intended.
Fixes #
> fix(pulumi): fix process dependency resolution in plugin command

- plugins/pulumi/src/commands.ts
- plugins/pulumi/test/test-project-k8s/k8s-deployment/varfile1.yaml
- plugins/pulumi/test/test-project-k8s/k8s-deployment/varfile2.yaml
This fixes the regressions introduced in `0.13`. In `0.12`, references to `${modules.*}` in the Pulumi varfiles were possible.
This PR fixes `0.13` to use:
* the `${actions.*}` references in Pulumi varfiles
* the `${modules.*}` references with module-based configs
Fixes #5083
> fix(pulumi): propagate resolved action context to pulumi plugin commands

- core/src/analytics/analytics.ts
- core/src/exceptions.ts
- core/src/plugins/kubernetes/retry.ts
- core/test/unit/src/exceptions.ts
DNS error codes are not included in the OS error constants
(os.constants) / https://nodejs.org/docs/latest-v18.x/api/os.html#error-constants
This PR adds DNS error codes to the list of handled errno errors.
Fixes https://github.com/garden-io/garden/issues/5217
> fix: handle and retry DNS errors

- core/src/logger/util.ts
Before this fix, commands in a dev command session would fail with an error if the terminal width was less than the length of the command (including opts and args).
Fixes #4912.
> fix(dev): fix crash on very narrow terminals

- core/src/cloud/api.ts
- core/src/garden.ts
- core/test/helpers/api.ts
- core/test/integ/src/plugins/kubernetes/helm/deployment.ts
- core/test/unit/src/garden.ts
This commit fixes a regression introduced with:
https://github.com/garden-io/garden/pull/5291
That commit was just a tiny tweak to a couple of lines of code to improve error messages but actually ended up breaking the core <> cloud interaction for the community tier dashboard.
The underlying reason is the fact that this particular code was quite convoluted and not tested well enough.
So this commit refactors the cloud init logic to make it more readable and adds a handful of tests to prevent these kind of regressions from happening again.
Fixes #
~I'm flagging as draft since there are some changes around the init logic for the community dashboard that I'd like to get feedback on. …
> fix(cloud): ensure cloud project id is set on garden class

- core/src/plugins/kubernetes/kubernetes-type/common.ts
- core/test/integ/src/plugins/kubernetes/kubernetes-type/common.ts
When applying K8s resources, we create a ConfigMap with metadata about the resources for faster lookup.
This metadata includes the resource namespace among other things.
Before this fix, we'd create the ConfigMap before applying the resource patch which meant that if you patched the actual resource namespace, Garden wouldn't store that information.
Later when looking up the status of the resource, Garden would use the data from the ConfigMap and basically look for the resource in the wrong namespace and return status "not-ready" (when in fact the resource could be ready, just in a different namespace).
Fixes #
- Are there other places in the code you can think of were we could be …
> fix(k8s): ensure patchResources can patch namespace

- core/test/unit/src/commands/self-update.ts
Retry the flaky selfUpdateCommand test. Hopefully this helps, otherwise we can consider retrying the whole SelfUpdateCommand tests.
Had to convert the arrow function for this to work properly otherwise arrow function[ cannot access the mocha context](https://mochajs.org/#arrow-functions).
Fixes #
> test: retry flaky test

- docs/reference/action-types/Build/jib-container.md
- docs/reference/module-types/jib-container.md
- plugins/jib/src/index.ts
- plugins/jib/src/openjdk.ts
Add the possibility to use JDK 21 for running the jib action type.
This changeset adds the ability to use JDK 21 for the jib action type.
This is effectively a copy of https://github.com/garden-io/garden/commit/3f3c91f31db7abed0553802d2149e18197ad3210 , just with JDK 21 instead of JDK 17.
> improvement(jib): support JDK 21 LTS version

- core/src/graph/actions.ts
- core/test/data/test-projects/action-source-path/project.garden.yml
- core/test/data/test-projects/action-source-path/some-dir/with-source.garden.yml
Before this fix, we weren't resolving template strings on the optional `source.path` action config field. This caused errors when `git` was called on a path that still had unresolved template strings.
This was fixed by preprocessing action configs (which resolves template strings on them) before passing the paths to the VCS helper that computes minimal roots.
> fix(core): resolve templates in `source.path`

- garden-sea/src/extract.rs
- garden-sea/src/node.rs
This is to double down on making sure that self-update updates the
correct path (See also #5352)
Fixes #
> fix(garden-sea): resolve symlinks for GARDEN_SEA_EXECUTABLE_PATH

- core/src/commands/self-update.ts
Otherwise `homebrew` but also other setups might fail and corrupt data since we will replace the symlink instead of the actual binary.
Fixes #
> fix: always resolve symlinks for the executable path in the self-updater

- .circleci/continue-config.yml
- Save ~/.npm folder in npm_install cache and use --prefer-offline
option (node_modules are always nuked by npm ci)
- Always save caches with context parameter, as paths differ on
different runners.
- Rename some variables to make the circleci config more clear
- Remove "~/.npm" before restoring cache to avoid permission errors (See also https://github.com/CircleCI-Public/node-orb/issues/158#issuecomment-1461095390)
Fixes #
> chore(circleci): improve npm and node cache hits

- .circleci/continue-config.yml
- core/src/plugins/container/config.ts
- core/src/plugins/kubernetes/sync.ts
- docs/reference/action-types/Deploy/container.md
- docs/reference/action-types/Deploy/helm.md
- docs/reference/action-types/Deploy/kubernetes.md
- docs/reference/module-types/container.md
- docs/reference/module-types/helm.md
- docs/reference/module-types/jib-container.md
- docs/reference/module-types/kubernetes.md
This unifies the way we validate the sync mode's source paths for all action types.
Fixes #4982
Fixes #5031
I tested and verified the changes on the Windows machine. I tried both relative and absolute Windows paths as a sync-mode source path.
I also added 2 test cases for Windows in 40ec1ea0b6f38ea9ac37ab57055cc8e29f50aca1.
Verified the failure of those tests manually and in [CI](https://app.circleci.com/pipelines/github/garden-io/garden/21852/workflows/460299a5-632f-4e11-803c-68d11368279a/jobs/433221).
> fix(sync-mode): use the same source path schemas for all action types

- core/src/plugins/kubernetes/api.ts
- core/src/plugins/kubernetes/config.ts
- core/src/plugins/kubernetes/constants.ts
- core/src/plugins/kubernetes/container/build/buildkit.ts
- core/src/plugins/kubernetes/container/build/common.ts
- core/src/plugins/kubernetes/container/build/kaniko.ts
- core/src/plugins/kubernetes/jib-container.ts
- core/src/plugins/kubernetes/status/status.ts
- core/src/plugins/kubernetes/types.ts
- core/test/integ/src/plugins/kubernetes/container/build/build.ts
- core/test/unit/src/plugins/kubernetes/container/build/common.ts
- core/test/unit/src/plugins/kubernetes/container/build/kaniko.ts
- docs/k8s-plugins/advanced/in-cluster-building.md
- docs/reference/action-types/Deploy/pulumi.md
- docs/reference/providers/kubernetes.md
- docs/reference/providers/local-kubernetes.md
- images/buildkit/Dockerfile
- images/buildkit/garden.yml
- images/k8s-util/Dockerfile
- images/k8s-util/garden.yml
- images/skopeo/Dockerfile
- images/skopeo/garden.yml
This PR introduces a new service account, and makes the annotations
configurable in kaniko and buildkit in-cluster-builders.
This change enables the use of IRSA for in-cluter-building which makes
in-cluster building more secure.
Fixes #2931
> feat(k8s): add service account and irsa support for in-cluster-builder

- scripts/release.ts
> chore: fix CommonJS module import in the release script

- core/test/integ/src/plugins/kubernetes/container/logs.ts
This test is flaky because the order of log entries isn't always stable now.
Thus we find the correct log line first and then assert that it exists.
Actually all the following tests in this file did the same pattern, so maybe something like this has been the case in the past as well and only this test somehow survived.
Fixes #
> test: fix flaky test for deploy logs

- docs/getting-started/quickstart.md
Otherwise I get this error on windows:
```
PS Z:\Documents> git clone https://github.com/garden-io/quickstart-example.git && cd quickstart-example
At line:1 char:63
+ ...  clone https://github.com/garden-io/quickstart-example.git && cd quic ...
+                                                                ~~
The token '&&' is not a valid statement separator in this version.
+ CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : InvalidEndOfLine
```
Fixes #
> docs: make sure git clone command works on windows

- cli/src/build-pkg.ts
- core/src/util/util.ts
- rollup.config.js
Currently edge versions pretend to be production version. This was a regression introduced in #5233 
This commit fixes that, to ensure that we do not confuse edge builds
with production builds and to ensure that our analytics is correct.
Currently edge builds pretend to be production builds:
```
steffen@MacBook-Pro-3 garden % garden self-update edge-bonsai
Update Garden 🗞️
No installation directory specified via --install-dir option. Garden will be re-installed to the current installation directory: /opt/homebrew/Cellar/garden-cli/0.13.19/libexec
Checking for target and latest versions...
Current Garden version: 0.13.20
Target Garden version to be installed: edge-bonsai
Latest release version: 0.13.20
Downloading …
```
> chore: fix edge version

- core/src/actions/helpers.ts
- core/src/commands/base.ts
- core/src/garden.ts
- core/src/logger/renderers.ts
- core/src/logger/styles.ts
- core/src/logger/util.ts
- core/src/plugins/kubernetes/container/build/common.ts
- core/src/plugins/kubernetes/nginx/default-backend.ts
- core/src/plugins/kubernetes/nginx/nginx-helm.ts
- core/src/plugins/kubernetes/nginx/nginx-kind.ts
- core/src/plugins/kubernetes/nginx/nginx-microk8s.ts
- core/src/plugins/kubernetes/nginx/nginx-minikube.ts
- core/src/tasks/base.ts
- core/src/tasks/build.ts
- core/src/tasks/deploy.ts
- core/src/tasks/run.ts
- core/src/tasks/test.ts
- core/test/unit/src/logger/renderers.ts
This commits adds more logging to the action lifecycle. That is logs about getting status of a given action, the results, next steps, etc.
The logging is done in the task decorators that are also used for emitting events.
The goal is obviously to make the logs more informative but also more consistent.
Fixes #
Here's a screenshot of the new logs. Note that the screenshot uses different colors to what we currently have so that the change is more visible. But we'll make those color changes in a separate PR though.
> improvement(core): better action lifecycle logs

- core/src/vcs/git.ts
- core/test/unit/src/vcs/git.ts
This PR introduces a more precise error message examination for Git exit code 128.
Fixes #5434
> fix(git): fix confusing error messages on exit code 128

- core/src/constants.ts
- core/src/logger/log-entry.ts
- core/src/logger/renderers.ts
- core/test/unit/src/logger/renderers.ts
- docs/misc/faq.md
A quick fix to ensure Garden respects the `NO_COLOR` env var and doesn't print colored logs if it's set. We should also this as a CLI flag but this is a start.
A second commit also removes unused code that got accidentally left in. 
Fixes #2420
> feat: respect NO_COLOR env var

- core/src/plugins/kubernetes/container/build/common.ts
- core/src/plugins/kubernetes/ephemeral/config.ts
- core/src/plugins/kubernetes/status/status.ts
Various tweaks to log lines. Namely:
- Show provider name in the section for `ephemeral-kubernetes`
- Add origin to K8s logs
- Add origin to build util logs
Note that adding `origin` to a given log context means that it'll be printed with the log line.
So instead of:
`deploy.api => Deployment/web: Started container web`
We print:
`deploy.api => [kubernetes] Deployment/web: Started container web`
Fixes #
> improvement(logger): various tweaks to log lines

- core/src/cli/cli.ts
- core/src/commands/deploy.ts
- core/src/garden.ts
- core/src/plugins/kubernetes/ephemeral/config.ts
- core/src/plugins/kubernetes/init.ts
- core/src/plugins/kubernetes/local/config.ts
- core/src/tasks/base.ts
- core/src/tasks/resolve-provider.ts
- core/test/unit/src/cli/cli.ts
- plugins/terraform/src/index.ts
- plugins/terraform/src/init.ts
This commits add more logging around the provider resolution phase of the Garden initialization. Also ensures that the log context passed to the plugin handlers has the provider name set.
For context, these log improvements I've been making are part of the "getting started" video work. The idea there is to explain how Garden works and we need better lifecycle logging to support that.
Fixes #
> improvement(logger): better provider resolution lifecycle logs

- core/src/logger/styles.ts
Before this commit, our primary log color was chalk.grey and people generally agree that it's too vague.
This commit changes the primary log color we've been using since we first released Garden to chalk.white for better accessibility and more fun.
In general we can make this configurable. But I figured I'd just bite the bullet.
See also discussion in: https://github.com/garden-io/garden/pull/5464
Fixes #5464
> improvement(logger): use 'white' as primary color

- core/package.json
- package-lock.json
We switch to internal kubernetes-client/javascript fork where we fixed
this issue upstream in commit https://github.com/kubernetes-client/javascript/pull/1436/commits/60f0ea6de09777ceabd5afc3e306801fd0b025cc
See also https://github.com/kubernetes-client/javascript/pull/1436
Fixes #
> fix(k8s): read tls-server-name correctly from kubeconfig

- core/src/tasks/resolve-provider.ts
Reverts an earlier commit where we set the log level for exec providers to verbose which means logs from init scripts aren't visible.
That was a mistake and this fixes that.
My apologies.
Fixes #
> fix(core): log exec provider resolution at info level

- core/src/commands/exec.ts
- core/test/integ/src/plugins/kubernetes/commands/exec.ts
- core/test/unit/src/cli/helpers.ts
- core/test/unit/src/commands/exec.ts
- docs/reference/commands.md
- docs/using-garden/using-the-cli.md
Fixes the garden exec command, which wasn't working when given more than two arguments e.g. `garden exec backend "ls -la"` would fail with executable file not found, while `garden exec backend ls`  succeeds. If not quoting the command with two arguments, garden would interpret the `-la` as a garden argument and fail as well.
This PR restores the behavior for the command argument as it was in 0.12.x which means that commands are getting split which still fails in cases where there are quoted substrings see #2957. 
It also  introduces the option to use `--` as a separator to specify commands the same way kubectl does it. Using the `--` separator results in quoted strings to be interpreted as one argument.
e.g.:
`garden exec debian -- /bin/sh -c echo …
> Fix exec command strings

- core/src/vcs/vcs.ts
This avoids potential bugs in the places where we need to examine the value of the description. See https://github.com/garden-io/garden/blob/main/core/src/vcs/git-repo.ts#L48
Fixes #
We might need to introduce a separate action- / module-name-agnostics type like `RepoPathType` to make its declaration simpler. But the current solution also works fine and ensures we don't use potentially wrong values in the conditional code constructions. Wdyt?
> improvement(git): type-safety for repo path description

- core/src/plugins/kubernetes/api.ts
- core/test/integ/src/plugins/kubernetes/api.ts
When using absolute paths in URLs e.g. `/version` for initializing the kubernetes provider, we need to remove the leading slash due to the way URL constructs the full URL. If we don't remove it, it is seen as an absolute path which leads to all other parts of the path to be stripped. For example if this URL is specified in the kubeconfig for a Kubernetes api server
`https://rancher.18.194.162.172.sslip.io/k8s/clusters/c-m-qkrwsnsg`
when adding the `/version` endpoint we get:
`https://rancher.18.194.162.172.sslip.io/version`
This causes the request to fail. Instead we need:
`https://rancher.18.194.162.172.sslip.io/k8s/clusters/c-m-qkrwsnsg/version`
This PR fixes this behavior.
Fixes #
**Special notes for your …
> fix(k8s): fix paths in requests to kubernetes api

- core/src/cli/cli.ts
- core/src/commands/base.ts
- core/src/commands/login.ts
- core/src/garden.ts
- core/src/graph/actions.ts
- core/src/monitors/port-forward.ts
- core/src/mutagen.ts
- core/src/tasks/base.ts
- core/src/tasks/resolve-provider.ts
From commit message:
[improvement(logger): some minor fixes](https://github.com/garden-io/garden/pull/5475/commits/2120f9bd10b72022588161baedda51a8627e9178) 
Namely:
- Setting logs for some built-in providers to debug because that's just
more fitting
- Do not print new line after resolving providers and graph. Doesn't
render nicely.
- Add an "init" log context for the Garden class that logs when Garden
has been initialized with duration for non-dev commands.
- Print link to Cloud at end of command run as well
- DO NOT log outdated statuses at a "warning" level
- Other minor tweaks
Fixes #
I know these keep raining in. My apologies. They're not super urgent per se and just small …
> improvement(logger): some minor fixes

- core/src/garden.ts
- core/test/unit/src/vcs/git-repo.ts
- core/test/unit/src/vcs/git.ts
This PR patches #5399 and fixes test setup for VCS handlers.
This is also a pre-requisite for #5472.
Fixes #
> fix(git): prefer project-level repo scan mode over env variable

- core/src/plugins/kubernetes/helm/helm-cli.ts
Upgrade Helm from version 3.12.0 to 3.12.2. As this is a non-breaking change in the Helm CLI, the Garden helm provider should function seamlessly.
Refer to the Helm 3.12.2 release for more details: https://github.com/helm/helm/releases/tag/v3.12.2
This update addresses an issue where Helm fails with HTTP error code 426, as reported on the Helm GitHub repository:
https://github.com/helm/helm/issues/12071
Fixes #
> improvement(helm): update helm to `3.12.2`

- core/src/commands/logs.ts
- core/src/monitors/logs.ts
A user pointed out that we no longer print log command metadata (i.e. tags and timestamps) in grey. This fixes that.
Fixes #
> fix(commands): print log command metadata in secondary color

- core/src/analytics/analytics.ts
The segment client has a new API in the updated version. It calls an errorHandler function when there are network level failures such as DNS lookup errors. This change logs the error description on the debug level instead of a full error output on the console. 
Fixes #
> fix: adding an error handler to the segment client

- core/src/commands/sync/sync-status.ts
The sync status command would show strings with undefined when the status was 'not-deployed'.
```
The api Deploy action has 1 sync configured:
→ Sync from .../api to /app/api undefined not deployed
→ Mode: one-way-replica
```
Fixes #
> fix(sync-mode): showing undefined when sync status is not-deployed

- docs/contributing/README.md
- docs/contributing/contributing-docs.md
- docs/contributing/garden-dev-env-setup.md
- examples/local-service/README.md
Fixes made in this PR:
- replace `yarn` references with `npm` in the contributing guides and in the relevant examples
- actualize instructions on license header check
- actualize instructions on docs generation
This PR restores some of the changes made in #5132 and #5182 that were accidentally reverted in #5108.
> docs: actualize contributing guides

- core/src/vcs/git-repo.ts
- core/src/vcs/git.ts
- core/src/vcs/vcs.ts
- core/test/data/test-projects/include-exclude/module-b/dir1/foo.txt
- core/test/data/test-projects/include-exclude/module-b/dir2/bar.txt
- core/test/data/test-projects/include-exclude/module-b/garden.yml
- core/test/unit/src/vcs/git.ts
Fixes #5317
Based on test fixes made in #5472.
> fix(git): fix `exclude` files handling in `subtree` Git repo scan mode

- core/src/monitors/logs.ts
- core/test/unit/src/commands/logs.ts
This fixes a regression from the Bonsai release where log line sections weren't printed in color.
Fixes #4725 
> fix(commands): print section and tags in color

- core/src/plugins/kubernetes/ephemeral/config.ts
- core/test/unit/src/plugins/kubernetes/ephemeral.ts
The error message contained the hard coded string 'Garden Cloud'. We should instead use the 'getCloudDistributionName' helper.
In this case we can also just skip a reference to the distro name to keep things simple.
Fixes #
> improvement(ephemeral-kubernetes): tweak text in error message

- docs/getting-started/quickstart.md
Removes the dashboard gif from the quickstart guide. 
The gif is a bit distracting and pushes the actual content of the guide below the initial view port which may discourage users from following along.
The gif is also not really relevant to the _quickstart_ guide, rather it's a tour of the dashboard.
We now have that tour on the Dashboard docs page at: https://docs.garden.io/using-garden/dashboard
The Quickstart example repo itself now also includes a gif that actually demonstrates the steps of the guide: https://github.com/garden-io/quickstart-example
So with the above in mind, I think we can remove this one.
Also, this commit adds the `--sync` flag to the deploy command in the guide which is the intended behaviour.
**Which issue(s) this PR …
> docs: remove gif from quickstart guide

- docs/k8s-plugins/guides/in-cluster-building.md
- docs/k8s-plugins/remote-k8s/create-cluster/aws.md
This gives specific advice for creating an EKS cluster ready to be used for in-cluster image building when an EKS cluster is created with Amazon's official eksctl tool.
> docs: add eksctl guide

- core/src/cli/cli.ts
- core/src/cli/helpers.ts
- core/src/commands/serve.ts
- core/src/garden.ts
- core/src/server/server.ts
- core/src/util/cloud.ts
- core/test/unit/src/commands/login.ts
- core/test/unit/src/commands/logout.ts
- core/test/unit/src/commands/tools.ts
- core/test/unit/src/garden.ts
- core/test/unit/src/util/cloud.ts
This commit adds a message about the dashboard to all Garden commands. Previously we only showed it for the 'dev' command.
The message can be disabled.
It also consistently logs a warning if a user is logged in across all cloud distros.
Fixes #
> improvement(dashboard): better warning logs

- core/src/garden.ts
- core/test/unit/src/garden.ts
A previous commit (see #5538) logged this at the warning level which is relevant for the commercial edition but the community. This fixes that.
Fixes #
> improvement(cloud): log 'not logged in' msg at info level for community

- core/src/util/serialization.ts
This is a quickfix for #5442 to avoid Garden crashes on yaml highlighting. The proper fix still needs to be implemented.
A quickfix for #5442
> fix(cli): fallback to non-highlighted yaml if error occurs

- docs/use-cases/jumpstart-idp.md
- docs/use-cases/local-development-remote-clusters.md
- docs/use-cases/portable-ci-pipelines.md
Until we build out learning paths centered around use cases, it's best the docs are somewhat hermetic in their approach. This changes the docs to be less tutorial and more resource page for people looking to make use of them.
> docs: clean up Use Cases

- core/src/plugins/kubernetes/helm/helm-cli.ts
Patches #5497
The issue was found by the test script implemented in #5556.
Nothing to back-port to `0.12`, because it does not support `linux-arm64` binaries for Helm.
> fix(helm): fix `sha256` hash for `linux-arm64` binary

- plugins/jib/src/openjdk.ts
Fixes #
The issue was found by the test script implemented in #5556.
Nothing to back-port to `0.12`, because it does not support `linux-arm64` binaries for OpenJDK.
> fix(jib): fix OpenJDK `sha256` hashes for `linux-arm64` binaries

- docs/README.md
- docs/use-cases/jumpstart-idp.md
- docs/use-cases/local-development-remote-clusters.md
- docs/use-cases/on-demand-preview-envs.md
- docs/use-cases/portable-ci-pipelines.md
- docs/use-cases/shift-testing-left.md
This is a follow up to the work we started of splitting up the previous 'Use Cases' page into several top level pages.
This adds the remaining use cases and tweaks the format a bit.
Fixes #
> docs: add more uses cases

- core/src/vcs/git-repo.ts
- core/src/vcs/git.ts
- core/test/unit/src/plugins/container/container.ts
- core/test/unit/src/vcs/git.ts
This PR aligns the `exclude` file filter behavior between `GitRepoHandler` and `GitHandler`.
Also, it adds a few more test cases to cover more scenarios.
The behavior of `GitHandler` was taken as a reference, because it's been there for a long time before we switched the default repo scanner to `GitRepoHandler` in #5399 ([0.13.20](https://github.com/garden-io/garden/releases/tag/0.13.20)).
Fixes _some_ of the [`GitRepoHandler` test failures](https://app.circleci.com/pipelines/github/garden-io/garden/22567/workflows/4c86af6d-1ab2-4f3e-9502-1d8460251de2/jobs/453884) that were introduced in #5472. Those were enabled only for `GitHandler` that passed all the tests.
> fix(git): fix `exclude` filter in `repo` Git scan mode

- core/src/graph/actions.ts
In e0505642e2cf415a3255db72bcc4a94b4ad97bdf, we added a warning message that's shown when setting the mode on Build actions depended on byDeploys that are being deployed in sync mode.
These messages were noisy and unclear, so we're removing them here.
Closes #5602
> fix: remove confusing warning message

- core/src/config/base.ts
- core/src/config/project.ts
- core/test/data/test-projects/project-include-exclude/garden.yml
- docs/reference/project-config.md
Before this fix, an error would be thrown if using `scan.git.mode` and `module.include` or `module.exclude` together (since the Joi helper for renaming fields fails if there's already a value at the destination).
> fix(core): fix config error when using project.modules

- core/src/config/project.ts
- core/src/constants.ts
- docs/reference/project-config.md
The quick-fix to revert the [regression](https://github.com/garden-io/garden/pull/5399) introduced in [0.13.20](https://github.com/garden-io/garden/releases/tag/0.13.20).
Fixes #5624
Fixes #5625
> fix(git): revert default Git scan mode to `subtree`

- core/src/constants.ts
- core/src/garden.ts
- core/src/graph/actions.ts
- core/test/unit/src/actions/action-configs-to-graph.ts
- core/test/unit/src/graph/actions.ts
- docs/reference/project-config.md
- examples/remote-sources/garden.yml
Before this fix, remote actions (i.e. actions with `source.repository.url` set, not sources declared at the project level) didn't work correctly when using the new `repo` git scanning mode.
Also set the default git scanning mode back to `repo`, since this bug (which we've now fixed) was the reason we reverted to `subtree`.
The error arose because the base path wasn't being set to the locally cloned path of the remote source's repo early enough in the resolution process. This led to the repo scanning logic using the action's config directory instead of the cloned source directory as the repo root (thus ignoring the sources).
We've added a unit test that verifies that the base path is being set correctly when the action graph is initialized.
**Which …
> fix(core): fix "repo" scan mode for remote actions

- core/src/plugins/kubernetes/kubectl.ts
Kubernetes manifests often contain sensitive values, and Garden at the
moment does not offer sufficient facilities to filter them reliably
enough.
Fixes #
> fix(k8s): remove k8s manifest logs on apply

- core/src/template-string/functions.ts
- core/test/unit/src/template-string.ts
This caused bad handling of e.g. $forEach objects in input variables for templated actions.
> fix(template): do not partially resolve function arg objects with special keys

- core/src/plugins/container/container.ts
- core/src/plugins/container/helpers.ts
- core/src/resolve-module.ts
- core/test/helpers.ts
- core/test/unit/src/plugins/container/container.ts
- core/test/unit/src/plugins/kubernetes/container/module-conversion.ts
Before this fix, build dependencies weren't being transferred to the generated actions in all cases.
This was a problem e.g. if using a `helm` module with a build dependency on a `container` module, whose built image was referenced in the chart (since the missing build dependency meant that the image wasn't necessarily ready by the time the deploy started).
This was fixed by simply ensuring that any explicit build dependencies (i.e. under `module.build.dependencies`) are included in the dependencies of any generated runtime actions (Deploys, Tests and Runs).
This reflects the 0.12-era semantics, where every test, service and task had a build dependency on the module's build step, which in turn respected any build dependencies declared on the module …
> fix(module-conversion): always include build deps

- core/src/plugins/container/container.ts
- core/test/unit/src/plugins/container/container.ts
This is a follow-up to #5671 (see `47c24d5`). We also need to remove the added dependencies on the build steps of `persistentvolumeclaim` modules, since the converted actions there don't include a Build action.
Although this hasn't been reported yet, this would result in missing dependency errors when executing Runs or Tests that come from `container` modules which mount a `persistentvolumeclaim` module (using the `volumes` config field for `container` module services).
> fix(module-conversion): more fixes to PVC type

- .circleci/continue-config.yml
- cli/src/build-pkg.ts
- docs/contributing/developing-garden.md
- garden-sea/README.md
On macos we should use cargo directly, as cross needs custom docker images.
A recent version of cross does not automatically fall back to just cargo anymore, so we need to introduce a cargo command flag for npm run dist.
> fix(ci): macos cross build error

- core/src/tasks/base.ts
- core/test/unit/src/tasks/base.ts
When executing an action that depends on a disabled dependency, the disabled dependency should be skipped (unless it's a build).
This is fixed here (in accordance with the docstring for the `disabled` field on action configs).
> fix(core): don't execute disabled dependencies

- core/src/plugins/kubernetes/helm/action.ts
- core/src/plugins/kubernetes/helm/helm-cli.ts
- docs/reference/action-types/Deploy/helm.md
- docs/reference/module-types/helm.md
It looks like there were no breaking changes in [3.13.0](https://github.com/helm/helm/releases/tag/v3.13.0) and [3.14.0](https://github.com/helm/helm/releases/tag/v3.14.0), so we can update the helm version used by Garden internally.
In 3.13.x there were some fixes on the consistency of values handling:
> Values handling had numerous issues fixed and now consistently has a priority of (1) User specified values (e.g CLI), (2) parent chart values, (3) imported values, and (4) subchart values. Additionally, null can now consistently be used to remove values. Note, there is a regression around this in 3.13.0 that's fixed in 3.13.1.
Fixes #
> improvement(helm): update helm to 3.14.0

- core/src/plugins/kubernetes/retry.ts
- core/src/plugins/kubernetes/status/workload.ts
This should fix an intermittent class of errors reported by users, where unhealthy pods result in Garden failing to fetch logs for these same pods (for the purposes of error reporting) and throwing a noisy error that obscures the underlying problem.
See https://github.com/garden-io/garden/issues/5559, for example.
Here, we catch errors thrown during the diagnostic pod log error fetching, and simply log a warning message that the log fetching failed.
Fixes #5559 (hopefully).
It's kind of hard to write tests for this, but at least we're explicitly only catching an exception we weren't catching before, so this should be eminently safe.
> fix(k8s): don't throw when log fetching fails

- core/src/vcs/git-repo.ts
- core/src/vcs/git.ts
- core/test/unit/src/vcs/git.ts
- core/test/unit/src/vcs/vcs.ts
- docs/using-garden/actions.md
This fixes an error that would come up e.g. when an action config in the project root excluded a subdirectory containing another action config.
In that setup, the file list for the action in the subdirectory would be empty because the file list had been cached using the exclude config applied when computing the file list for the action config at the root level (which included no files for the excluded subdirectory).
This was fixed by adding another level of caching to `GitRepoHandler` that accounts for different includes/excludes and filter functions for the same path.
Note the slightly awkward clarification section about the difference between the exclude behavior of `subtree` and `repo` when no includes are …
> fix(git): fix file list caching bug for repo mode

- core/src/config/module.ts
- docs/reference/commands.md
- docs/reference/config-template-config.md
- docs/reference/module-types/configmap.md
- docs/reference/module-types/conftest.md
- docs/reference/module-types/container.md
- docs/reference/module-types/exec.md
- docs/reference/module-types/hadolint.md
- docs/reference/module-types/helm.md
- docs/reference/module-types/jib-container.md
- docs/reference/module-types/kubernetes.md
- docs/reference/module-types/persistentvolumeclaim.md
- docs/reference/module-types/pulumi.md
- docs/reference/module-types/templated.md
- docs/reference/module-types/terraform.md
The docstring for the `allowPublish` field for modules was ambiguous (some users interpreted it as applying to the `build` command as well).
> docs: fix docstring for allowPublish for modules

- core/src/mutagen.ts
- core/src/plugins/container/container.ts
- core/src/plugins/hadolint/hadolint.ts
- core/src/plugins/kubernetes/helm/helm-cli.ts
- core/src/plugins/kubernetes/kubectl.ts
- core/src/plugins/kubernetes/kubernetes-type/kustomize.ts
- core/src/plugins/octant/octant.ts
- core/src/plugins/otel-collector/otel-collector.ts
- core/test/unit/src/verify-ext-tool-binary-hashes.ts
- plugins/conftest/src/index.ts
- plugins/conftest/test/verify-conftest-binary-hashes.ts
- plugins/jib/src/gradle.ts
- plugins/jib/src/maven.ts
- plugins/jib/src/mavend.ts
- plugins/jib/src/openjdk.ts
To improve UX, let's always print the concrete versions of the tools in the `garden tools` output.
This PR also does refactoring in the tool definitions. It extracts tools versions as named constants to make the version update process easier. The PR also adds some missing tests to verify the binary hashes for the tools.
Fixes #
> improvement(ext-tools): always print versions in `garden tools` output

- .circleci/continue-config.yml
This PR fixes the [failures](https://app.circleci.com/pipelines/github/garden-io/garden/23459/workflows/06e8dab2-5a4d-46e2-b471-b8a081330b7d/jobs/478798) in the environment setup for Windows tests.
The CI error was:
```console
Update done!
RefreshEnv.cmd does not work when run from this process. If you're in PowerShell, please 'Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1' and try again.
Exited with code exit status 1
```
This PR applies the fix suggested in the logs above.
> ci: fix env setup for Windows tests

- core/src/resolve-module.ts
- core/test/unit/src/plugins/kubernetes/container/module-conversion.ts
- core/test/unit/src/resolve-module.ts
When a module has a build dependency on another module that doesn't have a corresponding Build after being converted into actions (e.g. a build dependency on a `terraform` module), we now log a warning and remove the dependency from the generated actions instead of erroring out.
In 0.12, some users had build dependencies on modules with no-op build steps (e.g. `terraform`, `kubernetes` and `helm` modules)
While this was harmless in 0.12, this resulted in noisy errors before this fix.
> fix(module-conversion): skip omitted build deps

- core/src/resolve-module.ts
Use `partition` to separate existing and missing deps, and then process each collection separately, just for better readability and ensuring SRP.
A leftover from the core review for #5727 :)
Fixes #
> refactor(resolve-module): separate filtering and warnings logging

- core/src/commands/base.ts
- core/src/graph/common.ts
- core/src/graph/nodes.ts
- core/src/graph/results.ts
- core/src/graph/solver.ts
- core/src/logger/log-entry.ts
- core/test/unit/src/commands/build.ts
Before this fix, we would include a stack trace in the error logged when a requested action has a missing dependency. This was very noisy and indicated a problem with Garden (when it's a totally normal user error).
> improvement(core): less noisy missing dep errors

- docs/guides/code-synchronization.md
Remove outdated command that was referencing a non-existing script.
Use the proper Garden command instead.
> docs(sync): actualise sync list command

- core/src/constants.ts
- core/src/mutagen.ts
- core/src/plugins/kubernetes/sync.ts
- core/src/util/ext-tools.ts
- core/test/unit/src/verify-ext-tool-binary-hashes.ts
- docs/guides/code-synchronization.md
Garden currently uses a custom fork of Mutagen for its `kubectl exec` transport. This is the last remaining blocker to get Garden back on the official Mutagen releases.
At the moment, Mutagen doesn't support custom transports, but it does allow a custom ssh executable to be specified, which presents an opportunity for using a faux SSH command that calls down to `kubectl exec` using parameters smuggled through the SSH hostname specification. In this case, they are smuggled in a Base64-encoded JSON object (with some slight encoding tweaks to pass through Mutagen's local path detection heuristic).
The faux SSH implementation added in the original PR #3102 will almost certainly be useable (with minor tweaks) as a custom transport implementation once …
> improvement(mutagen): use faux SSH command to use original Mutagen

- .circleci/continue-config.yml
Some enhancements in the Windows test environment configuration:
* Use the latest available executor `circleci/windows@5.0.0` for `win/server-2022`
* Print the versions of the installed Chocolatey and PowerShell (it might be useful for troubleshooting).
> ci(windows): update to the latest Win Server 2022 executor

- core/package.json
- core/src/plugins/kubernetes/retry.ts
- core/test/unit/src/plugins/kubernetes/retry.ts
- package-lock.json
We failed retrying `WebsocketError` during Pod exec operations, because the regex "WebsocketError: Unexpected server response" did not match
anymore after we refactored `toKubernetesError`, because the formatting
changed.
Let's retry if just the name `WebsocketError` appears in the message.
Fixes #5729
> fix(k8s): retry websocket errors

- core/src/plugins/kubernetes/kubernetes.ts
- docs/getting-started/installation.md
- docs/reference/providers/kubernetes.md
Update the instructions on the Kubernetes support by Garden.
Now Garden only supports the latest and the officially maintained Kubernetes versions.
This is a follow-up PR for #5664 and #5696.
> docs(k8s): update Kubernetes support policy

- .circleci/continue-config.yml
- core/src/plugins/kubernetes/kubectl.ts
Update kubectl and kind image in CI:
* use `kubectl` version `1.29.2`
* use `kindest/node` version `1.29.2` in CI
> improvement(k8s): update `kubectl` version to `1.29.2`

- .circleci/continue-config.yml
Use the latest available minikube and kubernetes version in the remote integration tests.
Used config guides:
* https://minikube.sigs.k8s.io/docs/drivers/none/#requirements
* https://kubernetes.io/blog/2022/03/31/ready-for-dockershim-removal/
* https://github.com/Mirantis/cri-dockerd?tab=readme-ov-file#build-and-install
> ci: use latest minikube and k8s in remote tests

- core/src/plugins/kubernetes/config.ts
- core/src/plugins/kubernetes/container/build/buildkit.ts
- core/test/unit/src/plugins/kubernetes/container/build/buildkit.ts
- docs/k8s-plugins/guides/in-cluster-building.md
- docs/reference/providers/kubernetes.md
- docs/reference/providers/local-kubernetes.md
AWS ECR now supports `mode=max` together with an extra option
`image-manifest=true`.
See also https://aws.amazon.com/blogs/containers/announcing-remote-cache-support-in-amazon-ecr-for-buildkit-clients/
Fixes #5683
> feat(k8s): support mode=max for AWS ECR with cluster-buildkit build mode

- core/package.json
- core/src/commands/dev.tsx
Enable linter for `*.tsx` files too.
> chore(lint): enable linter for `*.tsx` files

- core/src/plugins/kubernetes/container/build/buildkit.ts
- core/test/unit/src/plugins/kubernetes/container/build/buildkit.ts
If the liveness probe fails, buildkit gets restarted which cancels the context. The command for the liveness probe seems to sometimes fail, even though the build is still going on. With removing the explicit liveness probe, we use the default kubernetes liveness probe, which is tied to the lifecycle of the main container process.
Fixes #
> chore(buildkit): remove liveness probe to avoid unneccessary restarts of buildkit

- core/src/plugins/kubernetes/util.ts
Try to choose a running Pod for execing into. Without this, users might get the following error persistently if the first pod happened to be crashlooping:
```
run.test✖ Failed processing Run type=kubernetes-exec name=test (took 12.35 sec). This is what happened:
────────────────────────────────────────────────────────────────────────────────────────────────────
Error while performing Kubernetes API operation Pod exec: WebsocketError
Unexpected server response: 500
────────────────────────────────────────────────────────────────────────────────────────────────────
```
Fixes #5729
> fix(k8s): attempt execing on running pod

- core/src/commands/util/profile-project.ts
- core/src/commands/util/util.ts
- core/src/vcs/git-repo.ts
- docs/reference/commands.md
- docs/reference/dockerhub-containers.md
Added a simple utility command for profiling projects, the `profile-project` command.
This command logs the number of files included in each action and module in the project (omitting actions that were converted from modules to avoid duplication), their include/exclude configs (if any), and finally the number of modules, actions and tracked files in the project.
This should be useful when helping users with large projects diagnose slow init performance and how to best structure their includes, excludes and `.gardenignore`.
> feat: added profile-project command

- core/src/plugins/kubernetes/status/workload.ts
For checking the rollout status of workloads we were using the `spec.replicas` and not the `status.replicas` in some cases. This means that during a rollout we would not catch the case where there are currently more `replicas` than `updated` replicas. If we compare the `spec.replicas` to `updated` it is possible that both have the same number, even though `updated` has not passed it's readiness probe yet, which is the trigger for the old pods to be terminated. Only once `status.replicas` and `status.updated` match are we truly done. This led to garden not waiting for deployment rollouts in some cases, which could lead to further errors trying to run execs or tests in non-running pods or pods being canceled mid-execution, due to them being terminated …
> fix(k8s): fix kubernetes workload rollout status check

- core/src/commands/deploy.ts
- core/src/commands/sync/sync-start.ts
The current behaviour of both commands is now deprecated and will be changed in a future breaking change release.
Both commands will be allowed to execute only inside dev console.
We recommend to run these commands from inside dev console starting from now.
> feat(sync): deprecate non-interactive `sync start` and `stop` commands

- core/src/config/render-template.ts
- core/test/data/test-projects/config-templates-with-templating/project.garden.yml
- core/test/data/test-projects/config-templates-with-templating/runs.garden.yml
- core/test/data/test-projects/config-templates-with-templating/schema.json
- core/test/data/test-projects/config-templates-with-templating/tempate.garden.yml
- core/test/unit/src/config/workflow.ts
- core/test/unit/src/garden.ts
Prior to this PR Garden did not allow the templating in the `ConfigTemplate.configs` like this:
```yaml
kind: ConfigTemplate
name: runs-template
inputsSchemaPath: schema.json
configs:
- $concat:
$forEach: ${inputs.names}
$return:
kind: Run
type: exec
name: "${item.value}"
spec:
command: ["echo", "${item.value}"]
---
kind: RenderTemplate
template: runs-template
name: my-runs
inputs:
names: ["run-a", "run-b"]
```
and it failed with error:
```console
Unexpected kind 'undefined' found in ConfigTemplate 'runs-template'. Supported kinds are: Build, Deploy, Run, Test and Workflow
```
<details>
<summary>Click to expand schema.json</summary>
```yaml
{
"type": "object",
"properties": {
"names": {
"type": "array"
}
}
}
```
</details>
Now, Garden partially …
> fix(template): support template strings in `ConfigTemplate.configs`

- core/src/commands/validate.ts
- core/test/integ/src/plugins/kubernetes/helm/config.ts
- core/test/integ/src/plugins/openshift/tests.ts
- core/test/unit/src/commands/base.ts
- core/test/unit/src/commands/validate.ts
- docs/reference/commands.md
- plugins/terraform/test/validation.ts
Before this commit, the `garden validate` command would fully resolve the config graph. This caused problems for users that had references to runtime outputs of actions in their action configs, since fully resolving the graph in such cases means executing the action (e.g. actually building/deploying).
Here, we change the default behavior of the validate command to only partially resolve the config graph, but also introduce a `--resolve` CLI option for resolving some or all actions fully. This allows users to fully resolve action configs for debugging purposes, but also to sidestep action configs with runtime output references.
Fixes #5695.
> improvement: improvements to validate command

- core/src/plugins/kubernetes/commands/pull-image.ts
- core/src/plugins/kubernetes/container/build/buildkit.ts
- core/src/plugins/kubernetes/container/build/common.ts
- core/src/plugins/kubernetes/container/build/kaniko.ts
- core/test/integ/src/plugins/kubernetes/container/build/build.ts
- core/test/integ/src/plugins/kubernetes/container/build/buildkit.ts
- docs/k8s-plugins/guides/in-cluster-building.md
The pull-image command spawns a pod for each image to pull. If you have set-up IRSA or Google Workload Identity for in-cluster building these pods also need to use the same service account as for in-cluster building.
Fixes #5591
> fix(k8s): use the same service account for pulling images as building

- core/src/plugins/container/build.ts
- core/src/plugins/kubernetes/container/build/buildkit.ts
- core/src/plugins/kubernetes/container/build/kaniko.ts
- core/src/plugins/kubernetes/jib-container.ts
- core/src/plugins/kubernetes/run.ts
- core/src/plugins/kubernetes/sync.ts
- core/src/server/server.ts
- core/src/util/escape.ts
- core/test/integ/src/plugins/kubernetes/container/deployment.ts
- core/test/integ/src/plugins/kubernetes/run.ts
- core/test/unit/src/plugins/kubernetes/container/build/buildkit.ts
- core/test/unit/src/plugins/kubernetes/container/build/kaniko.ts
- core/test/unit/src/util/escape.ts
Shell commands need to be carefully constructed to avoid command
injection issues, and also to avoid issues with the shell interpreting
input strings, e.g. parenthesis or glob characters.
If possible, we should pass a command list for executing commands.
For untrusted input values, one should use environment variables and
access them from the shell script. Make sure to access them wrapped
around double quotes, otherwise the script is prone to command injection
attacks.
Sometimes it is needed to construct a shell script to chain multuiple
commands together. In this case, this commit introduces a utility
function `commandListToShellScript`.
It wraps every parameter in single quotes, escaping contained single quotes (for use in bash scripts). Joins the …
> fix(core): properly escape shell commands

- core/src/plugin/handlers/Deploy/get-port-forward.ts
- core/src/plugins/kubernetes/container/util.ts
- core/src/plugins/kubernetes/port-forward.ts
this PR introduces a named types for the params of `getPortForwardHandler`. It also removes some dead code.
Fixes #
> refactor(port-forward): add explicit types

- core/src/plugins/kubernetes/helm/common.ts
- core/src/plugins/kubernetes/helm/deployment.ts
- core/src/plugins/kubernetes/helm/status.ts
- core/test/data/test-projects/helm-local-mode/backend-image/garden.yml
- core/test/data/test-projects/helm-local-mode/backend/garden.yml
- core/test/data/test-projects/helm-local-mode/frontend/garden.yml
- core/test/integ/src/plugins/kubernetes/helm/common.ts
- core/test/integ/src/plugins/kubernetes/helm/deployment.ts
Store garden metadata for Helm deploy actions in a config map in the same namespace instead of adding them as additional values to the Helm release, which caused schema validation to fail for Helm charts with `additionalProperties: false` in the `values.schema.json`.
Also fixes a skipped integration test on `localMode` for Helm Charts by updating the example project from modules to actions.
**Which issue(s) this PR fixes**: 
Fixes #3962
> feat(helm): store garden metadata in configmap instead of helm values

- core/src/plugins/container/build.ts
- core/src/plugins/container/container.ts
- core/src/plugins/container/helpers.ts
- core/src/plugins/kubernetes/container/build/kaniko.ts
- core/src/plugins/kubernetes/kubernetes.ts
- core/test/integ/src/plugins/container/container.ts
- docs/reference/providers/container.md
Allows overriding the docker command, and setting global extra build flags.
This can be useful when configuring custom remote builders.
Example:
```
providers:
- name: exec
initScript: |
docker buildx create --driver ... custom-builder
- name: container
dockerBuildExtraFlags: ["--builder", "custom-builder", "--push"]
```
This is useful as a first step for experimental Namespace builder support.
This PR also changes the Kubernetes provider initialization to allow missing `deploymentRegistry` config flag in remote kubernetes clusters. It now prints a warning instead of throwing an error.
> feat(container): allow global extra build flags e.g. for custom remote builders

- core/test/unit/src/util/string.ts
- core/test/unit/src/util/util.ts
A quick janitorial PR to keep the string util tests in the same file. I've made that while porting the util unit tests to Grow.
Fixes #
> chore(test): move string unit tests to the dedicated file

- core/src/commands/validate.ts
- docs/reference/commands.md
Prior to this change the flag was implemented but not considered as a valid one.
Patches #5809.
> fix: recognize `--resolve` flag in `validate` command

- core/package.json
- package-lock.json
Move away from our fork as our changes have landed upstream in
`1.0.0-rc4` (See also https://github.com/kubernetes-client/javascript/pull/1436)
> chore(deps): update `@kubernetes/client-node` to 1.0.0-rc4

- core/src/plugins/kubernetes/helm/config.ts
- core/test/data/test-projects/helm/oci-url/garden.yml
- core/test/integ/src/plugins/kubernetes/helm/deployment.ts
- docs/k8s-plugins/actions/deploy/helm.md
- docs/reference/action-types/Deploy/helm.md
- docs/reference/action-types/Run/helm-pod.md
- docs/reference/action-types/Test/helm-pod.md
- fix(k8s): allow specifying version for oci helm charts
- docs(helm): add examples for using OCI charts
Fixes #
> fix(k8s): allow specifying version for oci helm charts

- core/src/build-staging/build-staging.ts
- core/src/config/base.ts
- core/src/config/module.ts
- core/src/plugins/exec/convert.ts
- core/src/plugins/exec/moduleConfig.ts
- core/src/resolve-module.ts
- core/src/types/module.ts
- core/test/integ/src/plugins/kubernetes/helm/config.ts
- core/test/unit/src/config/base.ts
- core/test/unit/src/plugins/exec/exec.ts
- docs/reference/commands.md
- docs/reference/config-template-config.md
- docs/reference/module-types/configmap.md
- docs/reference/module-types/conftest.md
- docs/reference/module-types/container.md
- docs/reference/module-types/exec.md
- docs/reference/module-types/hadolint.md
- docs/reference/module-types/helm.md
- docs/reference/module-types/jib-container.md
- docs/reference/module-types/kubernetes.md
- docs/reference/module-types/persistentvolumeclaim.md
- docs/reference/module-types/pulumi.md
- docs/reference/module-types/templated.md
- docs/reference/module-types/terraform.md
Here, we make the `local` config field (previously only available to `exec` modules) available for all module types.
When used, it maps to the `buildAtSource` field of any generated Build actions in the module conversion process.
This is done because some users/projects that haven't migrated from modules to actions yet need to reference symlinked directories in their builds, where the simplest solution appears to be to simply opt out of build staging for those modules.
Workaround for #2382.
**Notes for reviewer**:
Will this cause problems with build copying? Does allowing this violate any subtle invariants?
> feat(modules): allow opting out of build staging

- core/src/events/events.ts
Some users with very large projects occasionally run into a "maximum event listeners exceeded" warning. It's not quite clear why this would happen, but maybe this is to be expected for larger projects.
Raising the limit should be harmless, and might help reveal underlying issues with the event listener lifecycle.
> fix(core): increase max event listener count

- core/src/plugins/kubernetes/container/build/common.ts
- core/src/plugins/kubernetes/run.ts
This is a workaround for a failure mode where we receive valid skopeo JSON output via the websocket connection, which
indicates that the image exists, but we never receive the message that the command has completed, which leads to a timeout.
The skopeo command output indicates that the image exists, but the Kubernetes API did not signal command completion.
This might indicate a network problem, e.g. an issue with Path MTU discovery that leads to packets being dropped, or another problem in the client or server implementation.
We don't know what the problem is yet, it might be the client, the
server or the network in between, the kernel etc.
the Websocket client code in the Kubernetes Client library is quite complex (See …
> fix(k8s): work around a rare websocket connection issue & warn

- core/src/vcs/git.ts
- core/test/unit/src/vcs/git.ts
@stefreak we discussed this yesterday. This PR introduces a standalone class that holds convenience methods for Git operations and supports arbitrary commands execution. Such approach allows to avoid passing the Git executor instance to every utility function.
Continuation of #5902.
> refactor(git): collect Git utils in one class

- core/src/exceptions.ts
- core/src/util/util.ts
- core/src/vcs/git.ts
- core/src/vcs/vcs.ts
The project scan fails with the following error for large projects:
```console
Command "git --glob-pathspecs ls-files --ignored --cached --exclude /workspace/all-the-things/.garden --exclude **/.garden/**/* --exclude-per-directory .gardenignore" failed with code undefined:
Here are the last 100 lines of the output:
// the logs have been omitted, there were no actual error details
```
We run the underlying git command with some custom options, and we have used the 10MB buffer instead of the default 100MB. That can be the cause of the problem. Let's merge it and ask the issue reporter to try out the edge build.
Fixes #
> fix(git): increase max proc buffer size and fix error handling

- core/src/mutagen.ts
Removes a `}` char in a warning message that shouldn't be there.
Fixes #
> fix(sync): fix typo in warning message

- core/package.json
- core/src/cloud/api.ts
- core/src/constants.ts
- core/src/plugins/container/build.ts
- core/src/plugins/container/cloudbuilder.ts
- core/src/plugins/container/container.ts
- core/src/plugins/kubernetes/container/build/local.ts
- core/src/plugins/kubernetes/container/extensions.ts
- core/src/util/ext-tools.ts
- core/src/util/process.ts
- core/test/unit/src/plugins/container/build.ts
- core/test/unit/src/verify-ext-tool-binary-hashes.ts
- docs/reference/providers/container.md
- package-lock.json
- plugins/pulumi/src/cli.ts
- plugins/terraform/src/cli.ts
Experimental cloudbuilder support for alpha preview users.
Implements Garden Cloud Builder support, but also Fixes #5437
Tests are missing. I'd like to start dogfooding and validating this, and then implement tests before we make it generally available.
> feat(container): experimental cloudbuilder support

- support/alpine.Dockerfile
- support/debian.Dockerfile
Buildx plugin will be required for Garden Cloud Builder.
> improvement(support): install docker-buildx-plugin in garden Docker images

- core/src/config-store/base.ts
- core/test/unit/src/cli/cli.ts
- core/test/unit/src/garden.ts
The signature `get<S extends keyof I<T>, K extends keyof I<T>[S]>(section: S, key: K)` may return `undefined` because the `key` parameter is a dynamic value, that might not exist in the config store.
See `CloudApi.getStoredAuthToken()`.
It can return `undefined` and we check it in `CloudApi.factory()`.
Prevents potential runtime `undefined`-errors.
I figured this out while reviewing #5502.
> chore: stricter return type in `ConfigStore.get(...)`

- core/src/actions/base.ts
- core/src/actions/types.ts
- core/src/graph/nodes.ts
- core/src/graph/solver.ts
- core/src/plugins/container/build.ts
- core/src/plugins/container/cloudbuilder.ts
- core/src/plugins/container/container.ts
- core/src/plugins/kubernetes/container/extensions.ts
- core/src/plugins/kubernetes/kubernetes.ts
- core/src/tasks/base.ts
- core/src/tasks/build.ts
- core/src/tasks/delete-deploy.ts
- core/src/tasks/deploy.ts
- core/src/tasks/publish.ts
- core/src/tasks/resolve-action.ts
- core/src/tasks/resolve-provider.ts
- core/test/unit/src/graph/solver.ts
- core/test/unit/src/tasks/base.ts
- plugins/pulumi/src/commands.ts
- Allow more fine-grained status and execute task node concurrency control in the
plugins using setters on the action.
- Assign concurrency group by node execution type (status, execute), action type
(exec, container) and the concurrency setting (assuming that actions with a separate
max concurrency setting are a different workload class).
- Fine-tune the build concurrency settings in the container and kubernetes plugins in the
`validate` and `getStatus` handlers for every action.
- This speeds up `garden build -f` in an internal project from ~40 seconds to ~14 seconds.
> improvement: allow for more concurrency when using cloud builder

- .circleci/continue-config.yml
Our CI builds started failing at the [`build-dist-linux-windows` step](https://app.circleci.com/pipelines/github/garden-io/garden/24667/workflows/0006be7a-19c4-45d6-a1ba-b215b178f62b/jobs/508315) a few days ago.
That step uses Cross for cross-platform binary compilation.
It looks like [ghcr.io/cross-rs/x86_64-pc-windows-gnu:main](http://ghcr.io/cross-rs/x86_64-pc-windows-gnu:main) was published 5 days ago as an edge version.
The latest stable one is `0.2.5`: https://github.com/cross-rs/cross/pkgs/container/x86_64-pc-windows-gnu
and it was published about a year ago.
So, now our CI downloads the edge release as it can be seen from the [CI logs](https://app.circleci.com/pipelines/github/garden-io/garden/24667/workflows/0006be7a-19c4-45d6-a1ba-b215b178f …
> ci(build-dist): use the latest stable pair of Rust and Cross

- .circleci/continue-config.yml
- cli/src/build-pkg.ts
- images/circleci-runner/Dockerfile
- images/circleci-runner/garden.yml
This PR updates the current Node 21 version it its latest minor/patch release.
See the [changelog](https://github.com/nodejs/node/compare/v21.1.0...v21.7.3) between `21.1.0` and `21.7.3` for the details.
Let's release this in `0.13.30`, and upgrade to the Node 22 LTS in `0.13.31`.
> improvement: update bundled NodeJS runtime to `21.7.3`

- docs/k8s-plugins/guides/in-cluster-building.md
Fixes a bug in the irsa IAM config snippet. Since we are using a wildcard, we need to use `StringLike` and not `StringEquals`.
Fixes #5977 
> docs: fix irsa iam config snippet

- .circleci/continue-config.yml
Update `microk8s` CI tests to use the latest Kubernetes version (`1.30`).
Kubernetes `1.26` is no longer supported, and `1.30` was released recently.
See https://kubernetes.io/releases/
Fixes #
The default `minikube` version was also updated to be `v1.32.0` (which is the currently used one).
> ci: use kubernetes 1.30 in microk8s tests 

- core/test/data/test-projects/helm/api-image/Dockerfile
- core/test/data/test-projects/helm/api-image/requirements.txt
- core/test/data/test-projects/kubernetes-type/api-image/Dockerfile
- core/test/data/test-projects/kubernetes-type/api-image/requirements.txt
- e2e/projects/vote-helm-modules/api-image/Dockerfile
- e2e/projects/vote-helm-modules/api-image/requirements.txt
- e2e/projects/vote-modules/api/Dockerfile
- e2e/projects/vote-modules/api/requirements.txt
- examples/k8s-deploy-config-templates/api/Dockerfile
- examples/k8s-deploy-config-templates/api/requirements.txt
- examples/k8s-deploy-patch-resources/api/Dockerfile
- examples/k8s-deploy-patch-resources/api/requirements.txt
- examples/k8s-deploy-shared-manifests/api/Dockerfile
- examples/k8s-deploy-shared-manifests/api/requirements.txt
- examples/vote-helm/api-image/Dockerfile
- examples/vote-helm/api-image/requirements.txt
- examples/vote/api/Dockerfile
- examples/vote/api/requirements.txt
In this PR:
* Update Python Docker images to be the latest Python-3.12 Alpine ones in tests and examples
* Update `Flask` versions across tests and examples
* Align `requests` and `urllib3` versions across tests and examples
The `psycopg2` dependency should also have an explicit version. Some image build errors occurred while trying to use the latest available version. That library can get an explicit version in a separate PR, it not urgent to do it now.
> chore(deps): update Python deps in tests and examples

- core/test/integ/src/plugins/kubernetes/kubernetes-type/common.ts
- core/test/unit/src/commands/workflow.ts
- plugins/terraform/test/terraform.ts
Follow-up on #6037 (This adds a missing test)
> test(terraform): add assertion for terraform stdout

- core/package.json
- package-lock.json
* remove redundant `@types/wrap-ansi`
* update `ink` to `5.0.0` to get rid of deprecated transitive dependency on `@types/wrap-ansi`
> chore(deps): update ink to 5.0.0

- .circleci/continue-config.yml
We use rollup wasm build since
https://github.com/garden-io/garden/pull/5400 so no need to install
linux build of rollup in CI anymore.
> chore: remove unneeded ci step to save 50 seconds

- garden-sea/src/node.rs
Use the V8 cache feature introduced in Node v22.1.0 to improve the CLI command startup time.
This feature is enabled by default, and `GARDEN_COMPILE_CACHE=0` can be used if it causes a problem as escape hatch.
On my M2 mac it saves ~11-30ms when running `garden --help`; On CircleCI Windows runner it saves 2 seconds for each CLI command invocation, so the difference can be really significant.
> improvement: improve cli startup performance using v8 cache

- core/src/plugins/container/build.ts
- core/src/plugins/container/helpers.ts
- core/src/plugins/container/publish.ts
- core/src/plugins/kubernetes/commands/pull-image.ts
- core/src/plugins/kubernetes/container/build/local.ts
- core/src/plugins/kubernetes/container/handlers.ts
- core/src/plugins/kubernetes/container/publish.ts
This PR fixes the behavior of `garden publish` command. See #6050 for additional context and technical details.
Fixes #6050
Fixes #4796
Reverts #4740 
Reopens #4095
Patches #4808
This PR does not address possible **Action Router** problems mentioned in #6050. There might be no issues at all in the Action Router. That should be considered separately, and another PR can be created if any fix is required.
> fix: `garden publish` command to respect `publishId`

- core/src/commands/get/get-actions.ts
- core/src/commands/get/get-files.ts
- core/src/commands/get/get-graph.ts
- core/src/commands/get/get-modules.ts
- core/src/commands/logs.ts
- core/src/commands/update-remote/actions.ts
- core/src/commands/update-remote/modules.ts
- core/src/commands/util/profile-project.ts
Applies the `statusOnly` option for provider resolution for all kinds of read-only commands:
* get-actions
* get-modules
* get-files
* get-graph
* update-remote
* profile-project
* logs
Fixes #3327
Based on the changes made in #6051.
> fix(commands): use statusOnly provider resolution for several read-only commands

- core/src/graph/actions.ts
To make it possible to return all outputs from actions as a json string, we need to allow setting the `needsExecutedOutputs` to `true`.   
When referencing `${actions.deploy.<name>.outputs}` without another key `outputKey` is `undefined` which without the change in this PR will cause `needsExecutedOutputs` to be `false`. This results in `${actions.deploy.<name>.outputs}` to always be an empty object.
Fixes #6046
TODO:
* Need to adjust the joi schema for outputs, so this is also documented in the reference docs.
* Need to track down why provider outputs are returned as plain object, while action outputs are returned as json string.
> fix(actions): return all outputs of an action as a json string

- cli/.mocharc.yml
Package build tests can take longer than 10 seconds. Let's put 20 seconds for it.
This should prevent CI failures like [this](https://app.circleci.com/pipelines/github/garden-io/garden/25091/workflows/b3f52529-4b88-41ee-91f9-0c329aa6e0b0/jobs/518388).
> test: increase timeouts for CLI tests

- images/README.md
- images/buildkit/garden.yml
- images/circleci-runner/garden.yml
- images/k8s-reverse-proxy/garden.yml
- images/k8s-sync/garden.yml
- images/k8s-util/garden.yml
- images/skopeo/garden.yml
Adds multi-platform builds for all the garden deployed containers like `buildkit`, `skopeo`, `k8s-sync`, etc. This allows users to run garden on arm64 native kubernetes.
We can not use the publish command any longer to publish the images to dockerhub, since the docker-container buildx runner is not able to load the images in the default local docker image store. To facilitate this, we now always push to DockerHub when running `garden build` in this project, but with a `dev` tag. When running `garden build --var publish=true` we push them with the specified production tag in `release_tag`.  This is a temporary workaround until we have properly integrated mutli-platform building into garden.
Also moves the images project from modules to actions ;-) …
> feat(images): add multi-platform images for garden deployed services

- core/src/plugins/kubernetes/helm/deployment.ts
- core/src/plugins/kubernetes/status/status.ts
The `--wait` option for `helm deploy` and `helm upgrade` is now applied by default for `helm` Deploys.
We had previously used `waitForResources` for this (since Helm's rollout statuses weren't reliable enough when using `--wait`).
In the `helm` deploy handler, we now only use `waitForResources` to wait for resources updated for local or sync mode.
Fixes #6053.
> improvement(helm): use --wait when deploying

- core/package.json
- package-lock.json
Update `segment/analytics-node` to the latest available version. Cloud still uses `2.1.0` - it's better to update that too.
Fixes #
> chore(deps): bump `segment/analytics-node` to `2.1.2`

- core/src/cloud/api.ts
- core/src/commands/cloud/helpers.ts
Skip already existing secrets instead of failing in `garden cloud secrets create` command.
This behaviour applies to all input secret sources, i.e. when those are passed as CLI args or from an input file.
Fixes #6048
Behaviour of secrets creation is now aligned with users creation.
The `--upsert` flag has not been implemented for `secrets create` command yet. It's available in the `secrets update` which, in turn, could be refactored and optimized; to avoid fetching all secrets and to share some secrets create/update/upsert machinery with the `secrets create` command.
It's better to refactor the `secrets update` command first, and the support the `--upsert` flag in the `secrets …
> fix(secrets): skip already existing secrets while creating

- core/src/plugins/kubernetes/constants.ts
- examples/local-mode-k8s/backend/garden.yml
- examples/local-mode/backend-1/garden.yml
- examples/local-mode/backend-2/garden.yml
This PR also fixes some broken local mode examples.
Fixes #
A follow-up PR for #6072. The [linuxserver/openssh-server:version-9.6_p1-r0](https://hub.docker.com/layers/linuxserver/openssh-server/version-9.6_p1-r0/images/sha256-81bcc076d4365b7498cd63384688e4301b0f99304780d1b74e9795255c62c74a?context=explore) tag seems to be rewritable, so the `k8s-reverse-proxy` got a new base image in the version `0.1.1`. This PR takes the latest `k8s-reverse-proxy` into use.
Maybe we should consider sticking to `-ls...` builds like [this](https://hub.docker.com/layers/linuxserver/openssh-server/9.6_p1-r0-ls157/images/sha256-81bcc076d4365b7498cd63384688e4301b0f99304780d1b74e9795255c62c74a?context=e …
> chore(images) use latest `k8s-reverse-proxy` image

- core/src/commands/cloud/secrets/secrets-update.ts
- core/test/unit/src/commands/cloud/secrets/secrets-update.ts
A follow-up PR to fix some bugs introduced in  #6068.
This also gets rid of unnecessary type `UpdateSecretBody`. Its `newValue` field was set but never read. The secrets to be updated did never get updated values.
Moreover, the `UpdateSecretBody.newValue` was set incorrectly, because it used  index-based access on array with the secret id/name used as an index value. That resulted to `undefined` value.
Patches #6068
* The secrets updating logic is still a bit complicated and will be simplified in the next PRs.
* This has `refactor` commit header because it's a follow-up PR, not a bug fix for an issue that exists in an official release.
* The changes were tested manually by …
> refactor(secrets): payload creation for `secrets update` command

- core/src/commands/cloud/helpers.ts
- core/src/commands/cloud/secrets/secrets-create.ts
- core/src/commands/cloud/secrets/secrets-update.ts
- core/src/commands/cloud/users/users-create.ts
Align the flow with the `users create` command. Stick to the same validation order.
Fixes #
> refactor(cloud): unify input key/value resource reading and mapping

- docs/reference/providers/terraform.md
- plugins/terraform/cli.ts
Align it with Garden 0.13 to use the newer terraform version in the Docker image.
The older version has a dependency with a vulnerability.
Fixes #
Supersedes #6108.
> improvement(terraform): update default terraform tool to 1.4.6

- core/src/plugins/kubernetes/run.ts
- core/test/integ/src/plugins/kubernetes/run.ts
If a `kubernetes-pod` Run or Test includes `volumeMounts` on the first container in its `podSpec`, we now include this in the runner pod.
Previously, we omitted the `volumeMounts` field from the first container in the (optional) user-supplied `podSpec` field. This is because the relevant code assumed `container` Runs/Tests—it's now appropriate for `container` and `kubernetes-pod` Runs/Tests.
Fixes #6069.
> improvement(k8s): allow volume mounts in runners

- core/src/plugins/kubernetes/kubectl.ts
Starting from `1.30.0`, Kubectl uses Go `1.22.0`.
This is important to resolve some exec path issues in Windows.
See #6120.
Fixes #
> tool(kubectl): update version to `1.30.1`

- .chglog/config.yml
- commitlint.config.cjs
- docs/contributing/README.md
Now we can use **tool** commit header for version updates of the Garden's embedded tools. Let's also expose these changes in the release notes.
Fixes #
> chore: add commit header for bundled tool version updates

- core/src/plugins/kubernetes/container/build/buildkit.ts
Back-ports #6072 and #6098 to `0.12.`
Fixes #6126
Instead of copying the contents of the `Dockerfile` and publishing it under a different tag, let's re-use alrwady published image.
**Q:** Should we delete the `images/buildkit` directory from 0.12 to avoid confusion?
> chore(images): [0.12] update `buildkit` image

- core/src/plugins/kubernetes/kubernetes-type/kustomize.ts
Update `kustomize` to the latest `4` version. Version `5` will be supported in a separate PR and will be used as a default one and included into Docker images to address #6128.
> tool(kuztomize): update version to `4.5.7`

- images/skopeo/Dockerfile
- images/skopeo/garden.yml
Partially reverts #6132.
The `skopeo` image is used by some components in `static/kubernetes/system`. So, let's restore it to see what exactly is used in the system namespace.
The `skopeo` image is not used in the code, so it's not necessary to revert the dead code deletion.
> chore(images): [0.12] restore `skopeo` image

- core/src/mutagen.ts
- core/src/plugins/kubernetes/constants.ts
- images/k8s-sync/Dockerfile
- images/k8s-sync/garden.yml
- images/k8s-util/garden.yml
Updated the native Mutagen client to the latest available stable version `0.17.6`.
The native Mutagen client is still available via `GARDEN_ENABLE_NEW_SYNC=1` feature flag.
Fixes #
> tool(mutagen): update to version `0.17.6`

- core/src/plugins/kubernetes/kubernetes-type/common.ts
- core/src/plugins/kubernetes/kubernetes-type/kustomize.ts
- core/src/plugins/kubernetes/kubernetes.ts
- core/test/unit/src/verify-ext-tool-binary-hashes.ts
- docs/reference/action-types/Deploy/kubernetes.md
- docs/reference/action-types/Run/kubernetes-pod.md
- docs/reference/action-types/Test/kubernetes-pod.md
- docs/reference/module-types/kubernetes.md
Adds support for the latest available major version of `kustomize`, and uses it by default in the code and Docker images.
Fixes #6128
Multi-version tool lookup still requires some hard-coding and manual lookup-key construction. So, a few files should be modified at once despite there is no obvious connection between them.
This is how it's done in nother multi-version tools. It would be nice to refactor that approach, but nice things are nice :)
The refactoring can be done for all tools in separate PR(s).
> tool(kuztomize): support version `5.4.2` and use it by default

- core/src/vcs/git-repo.ts
- core/src/vcs/git.ts
- core/src/vcs/vcs.ts
Class `VcsHandler` already stores the same `projectRoot` as `Garden` does. No need to read the project root from Garden.
Thus, the `VcsHandler` references `Garden` only to use its warning-emitting machinery. That can be decoupled as well.
Fixes #
> refactor(vcs): less coupling between `VcsHandler` and `Garden` classes

- core/src/mutagen.ts
- docs/guides/code-synchronization.md
A follow-up PR for #6148.
This makes the users aware about the upcoming change of the code syncing daemon.
Fixes #
> tool(sync): print warn on upcoming code sync daemon change

- support/debian.Dockerfile
Ports #6164 to `debian.Dockerfile`.
Fixes #
> chore(dockerhub): bump Google Cloud SDK to `479.0.0` in `debian.Dockerfile`

- support/alpine.Dockerfile
Supersedes #6163
We can switch to Python 3.12 when all SDKs (GCP, AWS and Azure) support it properly. Afaik, Azure has no Python 3.12 support yet, see https://github.com/Azure/azure-cli/issues/27673
> chore(dockerhub): stick to Alpine 3.19 for Python compatibility

- core/src/graph/actions.ts
- core/test/unit/src/garden.ts
Before this fix, we'd erroneously list the available action kinds instead of the available action types (for the invalid action's kind).
Fixes #5401.
> improvement(core): fix missing action type err msg

- core/src/commands/workflow.ts
- core/src/config/template-contexts/workflow.ts
- core/src/config/workflow.ts
- core/src/exceptions.ts
- core/test/unit/src/commands/workflow.ts
- core/test/unit/src/config/workflow.ts
- docs/reference/commands.md
- docs/reference/template-strings/workflows.md
- docs/reference/workflow-config.md
> feat: add allowFailure option for workflow steps

- core/src/vcs/git-repo.ts
- core/src/vcs/vcs.ts
- core/test/unit/src/vcs/vcs.ts
This PR fixes cache key construction in `GitRepoHandler` that accounts for different includes/excludes and filter functions for the same path.
Originally, the caching was implemented in #5710. This PR makes sure that 2 filter-objects are considered tom have the equal cache keys if the difference is only in the order of the `augmentedExcludes` and `augmentedIncludes` arrays, ad there is no difference between the sets of values of both arrays.
A follow-up PR for #5526 and #5710
~The changes made #5710 make the caching in `GitRepoHandler.scanRoot(...)` unnecessary. That caching logic will be removed in a separate PR.~ The caching in `GitRepoHandler.scanRoot(...)` might still make …
> fix(git): fix repo scan result caching

- .circleci/continue-config.yml
- cli/src/build-pkg.ts
Fixes the CI due to the current brownout.
See also https://discuss.circleci.com/t/macos-intel-support-deprecation-in-january-2024/48718
Fixes #
> ci: stop using x86 circleci macos runners, as they are not supported anymore

- core/src/cloud/api.ts
- core/src/plugins/container/build.ts
- core/src/plugins/container/cloudbuilder.ts
- core/src/plugins/kubernetes/container/build/local.ts
- core/src/plugins/kubernetes/container/extensions.ts
During review of #6153, Anna rightfully pointed out that the availability code is quite confusing (https://github.com/garden-io/garden/pull/6153#discussion_r1633020040 ). We've looked a little more closely at it together and concluded that the code even has potential for weird race conditions, where we are reporting building in cloud builder but actually built the image locally.
Worse yet, builds might fail with an InternalError if the user is unlucky ("You must call isConfiguredAndAvailable before calling withBuilder").
This refactor eliminates these weird races and also makes the code easier to understand and reason about at the same time.
Thanks Anna :)
> refactor: cloud builder availability

- core/src/commands/util/profile-project.ts
- docs/reference/commands.md
Fixes a typo in the help output of garden `garden util` command.
Fixes #6202
> docs(command): fix typo in `garden util profile-project` command

- core/src/plugins/kubernetes/helm/common.ts
- core/test/integ/src/plugins/kubernetes/helm/common.ts
What this PR does / why we need it:
fix read `valueFiles` in helm deployments with sources.repository.url
Which issue(s) this PR fixes:
Fixes https://github.com/garden-io/garden/issues/6146
Special notes for your reviewer:
It's same like #6147 just for `valueFiles` @stefreak 
---
I did test it against this (new uncommitted) example:
<details><summary>show example</summary>
examples/remote-helm/garden.yml
```yaml
kind: Project
name: remote-helm
environments:
- name: local
variables:
baseHostname: remote-helm.local.demo.garden
providers:
- name: local-kubernetes
environments: [local]
variables:
userId: ${kebabCase(local.username)}
```
examples/remote-helm/redis.garden.yml
```yaml
kind: Deploy
description: Redis service for queueing votes before they are aggregated …
```
> fix: 🐛 load valuefiles from config file location

- plugins/jib/src/index.ts
The `localId` was not set in the JIB module-to-action converter. That caused an unexpected value as an image id while JIB builds. The module's `name` was used as an image id instead of module's `image` config field.
Fixes #6204
We do not have any specific tests for JIB module converters and for Maven build args yet. I've tested the changes manually.
> fix(jib): set `localId` in JIB module-to-action converter

- core/src/plugins/container/build.ts
- core/src/plugins/container/cloudbuilder.ts
- core/src/plugins/container/config.ts
- core/src/plugins/container/container.ts
- core/src/plugins/container/helpers.ts
- core/src/plugins/container/publish.ts
- core/src/plugins/kubernetes/container/build/buildkit.ts
- core/src/plugins/kubernetes/container/build/kaniko.ts
- core/src/plugins/kubernetes/container/publish.ts
- core/test/integ/src/plugins/container/container.ts
- core/test/unit/src/verify-ext-tool-binary-hashes.ts
- docs/k8s-plugins/guides/in-cluster-building.md
- docs/other-plugins/container.md
- docs/reference/action-types/Build/container.md
- docs/reference/action-types/Build/jib-container.md
- docs/reference/module-types/container.md
- docs/reference/module-types/jib-container.md
- images/README.md
- images/buildkit/garden.yml
- images/circleci-runner/garden.yml
- images/k8s-reverse-proxy/garden.yml
- images/k8s-sync/garden.yml
- images/k8s-util/garden.yml
Adds the config option and capability to trigger multi-platform builds. To allow publishing multi-platform images with the publish command, the publish command now uses `regctl` whenever possible. This allows us to copy newly tagged images directly without the need to pull them down to a local image store first. This is more performant, enables usage of the publish command in container based CIs and it is necessary in the context of multi-platform builds because most local image stores don't support storing multi-platform images.
- feat(container): add multi platform builds
- feat(container): publish images without the need to pull them locally
Fixes #
Uses regctl instead of …
> feat: add building and publishing multi-platform images

- support/debian.Dockerfile
Picks changes from #6218 to `debian.Dockerfile`.
Fixes #
> chore(deps): bump google/cloud-sdk from 479.0.0 481.0.0 in debian.Dockerfile

- plugins/pulumi/src/commands.ts
The flag `--skip-dependencies` was initially implemented in #3096.
The logic that respects the flag was removed in e54d1b5eda7f88df8afba373ff3a5f65400ce6e5, likely by accident.
This commit restores the logic that prevents dependency resolution if the corresponding flag is set.
Fixes #6206
> fix(pulumi): respect `--skip-dependencies` flag in `preview` command

- core/src/template-string/template-string.ts
- core/test/unit/src/template-string.ts
This PR allows using partially resolved variables in arithmetic operations.
Fixes #6201
If we omit the explicit double-quotes in the `echo` command args in the example in #6201, i.e. replace
```yaml
spec:
command: [echo, '"${var.prefix.suffix * 4}"']
```
with
```yaml
spec:
command: [echo, '${var.prefix.suffix * 4}']
```
we'll get a schema validation error:
```console
Error validating spec for Run type=exec name=my-test:
At path spec.command.1: Expected string, received number
```
That is not related to the template string resolution and should be fixed in a separate PR. A possible solution is to stringify all numbers in `spec.command`'s args implicitly.
> fix(template): allow partially resolved vars in arithmetic expressions

- plugins/pulumi/src/commands.ts
A follow-up fix for #6226.
It returns the current task itself if the `--skip-dependencies` flag is on.
Otherwise, a [graph resolution error](https://github.com/garden-io/garden/issues/6206#issuecomment-2188967323) will be thrown.
Patches #6226
Fixes #6206
> fix(pulumi): fix dependency resolution when `--skip-dependencies` is on

- core/src/mutagen.ts
We'll likely release `0.13.33` patch later this week to address some `0.12` -> `0.13` migration issues.
So, let's defer the daemon switch to `0.13.34`, to give more time to users to be ready.
Fixes #
> chore: amend warn on upcoming sync daemon change

- core/src/constants.ts
- core/src/mutagen.ts
This PR flips the default value of `GARDEN_ENABLE_NEW_SYNC` feature flag to `true`.
It means that the sync mode will use the [native Mutagen](https://github.com/mutagen-io/mutagen) instead of the [Garden-fork](https://github.com/garden-io/mutagen) as a synchronization machinery.
Fixes #
> improvement(sync): use native Mutagen daemon by default

- core/src/cloud/api.ts
- core/src/garden.ts
- core/src/plugin-context.ts
- core/src/plugins/container/build.ts
- core/src/plugins/container/cloudbuilder.ts
- core/src/plugins/container/container.ts
- core/src/plugins/kubernetes/container/extensions.ts
- core/test/helpers/api.ts
- core/test/unit/src/garden.ts
- core/test/unit/src/verify-ext-tool-binary-hashes.ts
Establish buildx remote builders via MTLS to also support Windows.
Note: At the moment this implementation is mysteriously 5-20 seconds slower per build than the nsc-proxy implementation. There seems to be an additional cost of establishing the connection.
The `referenceCounter` can be used to cache the certificates in Cloud, but to make use of this the cache in the backend still needs to be implemented.
> feat: Windows support for cloud builder

- docs/reference/providers/pulumi.md
- plugins/pulumi/src/cli.ts
> tool(pulumi): switch default version to 3.102.0

- core/src/plugins/kubernetes/sync.ts
- docs/reference/action-types/Deploy/helm.md
- docs/reference/action-types/Deploy/kubernetes.md
Adds a feature I need - the ability to replace the deployed image when running the sync mode. The motivation is explained in the linked issue  :smile: 
Fixes #6232 
Can't seem to run `npm run generate-docs`, I get an error. 
Feel free to regenerate and push in my stead :man_shrugging:
> Feature: allow replacing image when in sync mode

- docs/reference/providers/pulumi.md
- plugins/pulumi/src/cli.ts
> tool(pulumi): switch default version to 3.122.0

- core/src/cache.ts
- core/test/unit/src/cache.ts
This PR adds a few more tests for `TreeCache` to ensure the internal invariants of the cache and to verify the structure consistency. The JSDoc were added to the `ContextNode` interface to explain its invariants and possible states.
The test-case implemented in 1b4ed18cf861c9edd8994ddf07a9a580592aaff3 covers the _current_ behaviour of the `TreeCache`, that was initially implemented years ago.
There is one fix for `ContextNode.key` assignment while creation, but that fix is not critical because the wrong value assignment hasn't seem to cause any real issues.
The wrong value just looked very confusing while debugging sessions.
Fixes #
> chore: ensure consistency of `ContextNode` keys and add new tests

- core/src/plugins/container/build.ts
- core/src/plugins/container/cloudbuilder.ts
We try to install a buildx builder directly by writing to the local .docker directory and if that fails we use docker cli to install the builder. In some environments e.g. CI the local .docker directory may not be available or not configured with the correct subpath of `~/.docker/buildx/instances`. We were missing some error handling and await when checking for these paths, which led garden to fail in case the path does not exist.
Also adds an error message for a common error which is missing or wrong credentials for the registry.
Fixes #
> fix(cloudbuilder): add error handling to fallback to cli install of buildx builder

- core/src/plugins/kubernetes/config.ts
- core/src/plugins/kubernetes/helm/helm-pod.ts
- core/src/plugins/kubernetes/helm/module-config.ts
- core/src/plugins/kubernetes/kubernetes-type/common.ts
- core/src/plugins/kubernetes/run.ts
- core/src/plugins/kubernetes/util.ts
- core/test/integ/src/plugins/kubernetes/run.ts
- core/test/unit/src/plugins/kubernetes/util.ts
- docs/reference/action-types/Run/helm-pod.md
- docs/reference/action-types/Run/kubernetes-exec.md
- docs/reference/action-types/Run/kubernetes-pod.md
- docs/reference/action-types/Test/helm-pod.md
- docs/reference/action-types/Test/kubernetes-exec.md
- docs/reference/action-types/Test/kubernetes-pod.md
- docs/reference/module-types/helm.md
- docs/reference/module-types/kubernetes.md
The kubernetes-type and helm pod runners for `Run` and `Test` actions are using the `podSpec` from a Kubernetes manifest or helm chart if a `resource` is specified. If these resources e.g. a `statefulSet` include volumes, these pods may fail to be deployed, because the volumes are already attached (most volumes are read-write-once).
We therefore sanitize the `podSpec` by removing all volumes except `configMaps` and `secrets`  which may be crucial for the pod to contain the correct configuration or credentials to run. These volume types can also be mounted several times and are less likely to cause issues.
In case of `configMaps` we also make sure that the `defaultMode` of the file permission is in octal.
If the `podSpec` is explicitly configured in …
> fix(kubernetes-plugin): sanitize volumes configuration for helm and kubernetes type pod runners

- core/src/plugins/kubernetes/commands/cleanup-garden-util.ts
- core/src/plugins/kubernetes/container/build/common.ts
- core/src/plugins/kubernetes/kubernetes.ts
A kubernetes plugin command to manually remove the unnecessary `garden-util` resources from the cluster.
Fixes #5909
> feat(kubernetes): plugin command to remove `garden-util` resources

- core/src/garden.ts
- core/test/data/test-projects/disabled-action-with-duplicate-name/project.garden.yml
- core/test/data/test-projects/disabled-action-with-duplicate-name/runs.garden.yml
- core/test/unit/src/garden.ts
This PR patches the feature implemented in #4805 and #5686.
Without this fix, the disabled flag on actions is not resolved properly if it's defined as a template string.
> fix: resolve `disabled` action flag before duplicate action names validation

- core/src/plugins/exec/common.ts
No need to do explicit logging because we already emit the log events.
Fixes #6292
> fix(exec): remove duplicate logging

- core/src/garden.ts
Do not allow `this.*` context for `disabled` field, just to avoid unnecessary complexity in passing action mode to the `scanAndAddConfigs()`.
Now an error is thrown if  `disabled:` flag has a reference to `${this.mode}`.
Fixes the incorrectly defined action mode introduced in #6293.
We can support `${this.*}` context as a separate feature PR if necessary.
> fix(template): use stricter context for `disabled` flag resolution

- core/src/plugins/kubernetes/helm/helm-cli.ts
- docs/reference/action-types/Deploy/helm.md
- docs/reference/module-types/helm.md
Update helm cli to the latest available version.
Fixes #
> tool(helm): update version to 3.15.3

- core/src/plugins/container/helpers.ts
- core/src/util/ext-tools.ts
- core/src/util/util.ts
Prior to #6294 we have never used the `env` parameter of the function `containerHelpers.dockerCli(...)`.
This PR ensures that the original process environment is always preserved and pass to the Docker process.
Without this fix, any custom `env` would replace the original process environment variables.
Instead of composing the merged env vars on the caller side, it's now done inside the helper function.
Fixes #
> fix: retain original process env when call `spawn` helper

- core/src/mutagen.ts
- core/src/plugins/kubernetes/commands/sync.ts
- core/src/plugins/kubernetes/constants.ts
- core/src/plugins/kubernetes/sync.ts
- core/test/integ/src/plugins/kubernetes/container/deployment.ts
Make sure that `MUTAGEN_SSH_PATH` pointing to the faux ssh is always set when a native Mutagen daemon is used.
See the [Discord thread](https://discord.com/channels/817392104711651328/1239306293307637932/1239306293307637932).
This doesn't completely solve the original issue mentioned in the Discord. But, it ensures that the right version of the ssh binary (i.e. our own faux ssh binary) is used.
> fix(sync): ensure the sync daemon env is configured correctly

- core/package.json
- core/src/analytics/analytics.ts
- core/src/cloud/api.ts
- core/src/garden.ts
- core/src/plugins/container/cloudbuilder.ts
- core/src/util/testing.ts
- core/test/helpers/api.ts
- core/test/unit/src/analytics/analytics.ts
- package-lock.json
This PR replaces #6310 that was automatically generated by dependabot.
Supersedes #6310
Some non-trivial code changes were required to use the new version of `@garden-io/platform-api-types`. Thus, a separate PR was created to avoid code changes committed by dependabot.
> chore(deps-dev): bump @garden-io/platform-api-types from 1.914.0 to 1.1131.0

- core/src/util/profiling.ts
The profiler has been broken since #5955
where we introduced properties with getters and setters in some classes.
The decorator implementation was crashing on getters and setters.
Fixes the crash that has been occurring while running `GARDEN_ENABLE_PROFILING=true garden util profile-project`:
```console
file:///~/garden/core/build/src/graph/nodes.js:216
return this.task.executeConcurrencyLimit;
^
TypeError: Cannot read properties of undefined (reading 'executeConcurrencyLimit')
at get concurrencyLimit (file:///Users/vladimirvagaytsev/Repositories/garden/core/build/src/graph/nodes.js:216:26)
at file:///~/garden/core/build/src/util/profiling.js:169:51
at __decorate …
```
> fix(profiler): handle getters and setters in `@Profile` decorator

- core/src/plugins/exec/common.ts
- core/src/plugins/exec/run.ts
- core/src/plugins/exec/test.ts
This PR fixes the command result processing and error handling in `Run` and `Test` actions of `exec` type, and align the error handling behaviour between the commands.:
* an error is returned immediately if the command exited with non-zero code, so Garden does not attempt to copy missing or incomplete artifacts; the error message includes the command output and the exit code.
* the command execution output is always printed in the console if the command was successful; in case of error, it will be printed as a part of the error message, and won't be printed twice.
* the artifacts are copied only if the command execution as successful
* I/O errors while artifacts copying do not crash the Garden process, and are handled as the other runtime errors …
> fix(exec): fix error handling in exec run and test actions

- garden-sea/src/node.rs
Allow specifying extra params via GARDEN_NODE_EXTRA_PARAMS environment
variable.
E.g. GARDEN_NODE_EXTRA_PARAMS="--inspect" garden deploy
> improvement(garden-sea): node extra params via env

- cli/src/cli.ts
- core/src/constants.ts
This adds the GARDEN_IGNORE_UNCAUGHT_EXCEPTION env var to work around
https://github.com/garden-io/garden/issues/6322 until we find a more
permanent solution.
> improvement: add GARDEN_IGNORE_UNCAUGHT_EXCEPTION

- core/src/cli/command-line.ts
- core/src/commands/dev.tsx
Before this fix, running a custom command within the `dev` command's interactive command line would fail.
Fixes #4688.
> fix(dev): fix custom commands not working in dev console

- core/src/template-string/template-string.ts
This PR handles the case when either of binary operator's arguments is undefined and an error occurs.
Fixes #
> fix(template): null-safe error message extraction

- support/debian.Dockerfile
Ports #6354 to `debian.Dockerfile`.
Fixes #
> chore(deps): bump google/cloud-sdk to 486.0.0 in debian.Dockerfile

- images/circleci-runner/Dockerfile
- images/circleci-runner/garden.yml
* Update cimg/node to 22.6.0
* Update google/cloud-sdk to 487.0.0
* Update kubectl to 1.30.2
Fixes #
> chore(ci): bump tools versions in circleci-runner image

- support/alpine.Dockerfile
- support/debian.Dockerfile
gsutil references a lot of old python packages which gives us a lot of alerts in our security scanners.
The gsutil component is not necessary for our users.
> chore: remove gsutil component due to security issues in submodule

- e2e/projects/code-synchronization-modules/garden.yml
- e2e/projects/demo-project-modules/garden.yml
- e2e/projects/hadolint-modules/garden.yml
- e2e/projects/jib-container-modules/project.garden.yml
- e2e/projects/kustomize-modules/project.garden.yml
- e2e/projects/open-telemetry/project.garden.yml
- e2e/projects/remote-sources-modules/garden.yml
- e2e/projects/tasks-modules/garden.yml
- e2e/projects/templated-k8s-container-modules/project.garden.yml
- e2e/projects/vote-helm-modules/garden.yml
- e2e/projects/vote-modules/garden.yml
- examples/code-synchronization/garden.yml
- examples/demo-project/garden.yml
- examples/gke/garden.yml
- examples/hadolint/garden.yml
- examples/jib-container/project.garden.yml
- examples/kustomize/project.garden.yml
- examples/remote-sources/garden.yml
- examples/run-actions/garden.yml
- examples/templated-k8s-container/project.garden.yml
- examples/vote-helm/garden.yml
- examples/vote/garden.yml
Added an `imagePullSecret`  for dockerhub to our ci GKE cluster and now we need to reference it in all garden projects that are used for e2e testing, since google cloud is not exempted from dockerhub rate limiting anymore.
Fixes #
> ci: add imagepullsecret for dockerhub for e2e tests

- core/src/util/ext-tools.ts
- core/src/util/process.ts
This PR simplifies the machinery of spawning oulumi CLI process and streaming its logs.
Now it uses `spawnAndWait` as many other external tools and supplies a logStream as `stdout` and `stderr` to stream the logs to the Cloud.
Fixes #6322
> fix(pulumi): fix process spawn machinery in Pulumi plugin

- core/src/plugins/kubernetes/test-results.ts
- core/src/util/serialization.ts
When serializing test result data, we can get an undefined value for some optional keys e.g. `diagnosticErrorMsg`. This will result in the reported error. Fixing this by transforming it to null in serialization and back to undefined in deserialization.
Fixes #5561 
> fix(testResult): transform undefined to null when serializing test result

- core/src/resolve-module.ts
- core/src/template-string/template-string.ts
- core/test/unit/src/template-string.ts
> fix(template): unescape escape templates when not doing partial resolution

- core/src/resolve-module.ts
- core/src/template-string/parser.pegjs
- core/src/template-string/template-string.ts
* Skip pre-mature string unescaping in Module configs
* Fix too greedy escaped string pattern definition in PeggyJS
Fixes #3989
Patches #5680
> fix(template): fix template string escaping and resolution in Module configs

- .circleci/continue-config.yml
* Update k3s from 1.27 to 1.30.
* Update kind version to the latest patch release.
Fixes #
> ci: update k8s version matrix in integration tests

- core/src/plugins/kubernetes/kubernetes-type/config.ts
- core/src/plugins/kubernetes/kubernetes-type/handlers.ts
- core/test/data/test-projects/kubernetes-type/apply-args/garden.yml
- core/test/data/test-projects/kubernetes-type/apply-args/manifests.yaml
- core/test/integ/src/plugins/kubernetes/kubernetes-type/handlers.ts
Add already prepared `applyArgs` to KubeCtl's `apply` function 🫣
Fixes #3839
Patches #6107
i am a little bit lost where to add some tests. can someone give me a hint? 😊
> fix: add applyArgs to kubectl apply function

- core/src/mutagen.ts
- core/src/util/ext-tools.ts
Fixes a small bug where the mutagen faux ssh binary path is wrong for linux arm64 builds. Also improves the error message around this.
Fixes #
> fix(sync): correct search path for mutagen faux ssh

- core/src/build-staging/build-staging.ts
- core/src/build-staging/helpers.ts
- core/test/unit/src/build-staging/helpers.ts
Allows using relative symlinks to directories and files when using build staging.
The goal is to reproduce symlinks in the target directory as-is, without having to resolve them.
The user would be responsible for making sure that both the relative symlink as well as the target
directory are included in the action.
If the symlink points to a file or directory outside the actions's source path, this throws an
error.
To avoid this becoming a breaking change, we keep the old behaviour if the symlink points to a
file. In that case, we resolve the symlink and copy the target file. If the target file is outside
the action's source or build directory, log a warning.
In a future 0.14 release of Garden, we should remove that branch, only reproduce symlinks …
> fix: allow relative symlinks to directories when using build staging

- core/src/config/template-contexts/actions.ts
- core/src/garden.ts
- core/test/data/test-projects/disabled-action-with-var-context/project.garden.yml
- core/test/data/test-projects/disabled-action-with-var-context/runs.garden.yml
- core/test/unit/src/garden.ts
* Do early `disabled` flag evaluation only for actions with duplicate names.
* Deny the usage of `var` and `variables` contexts in early `disabled` flag evaluation.
The contexts `var` and `variables` contexts are not fully resolved at that stage.
That can lead to incorrectly resolved `disabled` flag values.
Patches #4805, #5686, #6293, and #6406.
> fix(template): avoid premature `disabled` flag evaluation on actions

- core/src/garden.ts
- core/src/vcs/git.ts
Extract `getPathInfo()` function as a standalone helper and use it directly instead of unnecessary `GitHandler` instance creation.
Also, move the logic of `getPathInfo()` helper to `GitCli` class, and retain the standalone helper function, because It can be used directly in the case above.
Fixes #
A follow-up PR for #6455.
> refactor(git): avoid unnecessary Git handler creation

- core/src/garden.ts
- core/src/vcs/vcs.ts
To avoid keeping 2 different references to the same cache instance in `VcsHandler` and `Garden`.
Having `Garden.treeCache` as a property delegating to `VcsHandler.cache` makes it more clear.
Otherwise, it's not obvious that the cache instance in shared between 2 classes.
Fixes #
An alternative approach is to keep 2 independent cache instances for module versions and VCS files. Such attempt was taken in #6458.
That would not make the code simpler, because in some scenarios we need to `invalidateUp` or `invalidateDown` both caches synchronously. That would be error-prone, so let's keep the semantics as it is, and avoid more complex refactoring if that's not necessary.
> refactor: convert `Garden.treeCache` from class field to property

- images/k8s-sync/Dockerfile
The `mutagen-agent` binary in arm64 builds of `k8s-sync` (and therefore also `k8s-util`) were the binaries for amd64 instead. This updates the Dockerfile for `k8s-sync` to copy the correct binary for `mutagen-agent`.
> fix(sync): use right arch of `mutagen-agent` binary in `k8s-sync` image

- core/src/plugins/kubernetes/constants.ts
- images/k8s-sync/Dockerfile
- images/k8s-sync/garden.yml
- images/k8s-util/garden.yml
A follow-up PR for #6465.
Fixes #
The new images were already built and pushed.
> chore(sync): use new `k8s-sync` and `k8s-util` images

- core/src/util/fs.ts
- core/src/vcs/git-repo.ts
- core/src/vcs/git-sub-tree.ts
- core/src/vcs/vcs.ts
- core/test/unit/src/commands/build.ts
As it was mentioned in #5920, Garden Core calls `AbstractGitHandler.getFiles()` method twice:
* While looking for Garden config files
* While actions/modules resolution
For big projects with a large amount of untracked files that can cause performance downgrade, because each calls trigger the hash calculation of the untracked files.
This PR makes a simple improvement by disabling hash-calculation in the config files detection phase.
It improves a performance only in a specific scenario, when too many files untracked by Git are included into the Garden.
Fixes #
The performance difference can be compared by running `validate -l3`  Garden command in the root of …
> perf(git): avoid unnecessary file hashing while config files detection

- core/package.json
- package-lock.json
This might help to create an auto-fix PR for one security alert from dependabot.
Fixes #
> chore(deps): bump mockhttp to 3.15.2

- core/src/constants.ts
- core/src/vcs/git-sub-tree.ts
> chore(git): diagnostic flag to log action files untracked by Git

- core/src/build-staging/helpers.ts
- core/src/vcs/git-sub-tree.ts
- core/src/vcs/git.ts
- core/test/unit/src/build-staging/build-staging.ts
- core/test/unit/src/vcs/git.ts
This commit resolves an error "Failed copying a file because a directory
exists at the target path" which was a regression introduced in #6430.
Fixes #6456
> fix(core): avoid crash when using `copyFrom` together with symlinks

- core/src/commands/build.ts
- core/src/commands/delete.ts
- core/src/commands/deploy.ts
- core/src/commands/publish.ts
- core/src/commands/run.ts
- core/src/commands/sync/sync-start.ts
- core/src/commands/test.ts
- core/src/garden.ts
- core/src/graph/actions.ts
- core/src/graph/solver.ts
- core/src/outputs.ts
- core/src/plugins/kubernetes/logs.ts
- core/src/plugins/kubernetes/namespace.ts
- core/src/router/router.ts
- core/src/util/testing.ts
- core/src/vcs/git-sub-tree.ts
- core/src/vcs/git.ts
- core/test/integ/src/plugins/kubernetes/commands/exec.ts
- core/test/integ/src/plugins/kubernetes/commands/sync.ts
- core/test/integ/src/plugins/kubernetes/container/build/build.ts
- core/test/integ/src/plugins/kubernetes/container/deployment.ts
- core/test/integ/src/plugins/kubernetes/helm/common.ts
- core/test/integ/src/plugins/kubernetes/local-mode.ts
- core/test/unit/src/commands/publish.ts
- core/test/unit/src/graph/solver.ts
- core/test/unit/src/tasks/resolve-action.ts
- plugins/conftest-kubernetes/test/conftest-kubernetes.ts
- plugins/conftest/test/conftest.ts
- plugins/pulumi/src/commands.ts
- plugins/terraform/test/terraform.ts
Fix some confusing messages and reduced some mess around log instances.
Fixes #
> chore: minor fixes and improvements in logging

- core/src/cli/cli.ts
> fix: misleading warning message when cloud session is expired

- cli/src/cli.ts
- cli/test/unit/src/cli.ts
- core/package.json
- core/src/cli/cli.ts
- core/src/commands/custom.ts
- core/src/util/open-telemetry/exporters/reconfigurable-exporter.ts
- core/src/util/open-telemetry/tracing.ts
- core/src/util/util.ts
- core/test/unit/src/cli/analytics.ts
- core/test/unit/src/cli/cli.ts
- core/test/unit/src/commands/version.ts
- package-lock.json
Before this fix, when the -o/--output option was used the last OTEL span wouldn't be sent.
Fixing this surfaced some other issues and the code changes might look odd out of context so I'll try and explain the motivations below (also explained in the individual commit messages):
**First commit**
First off, the `Cli.run()` method would either return the results to the callee which would then do the clean up OR, if a certain combination of flags was passed, it would trigger a process exit itself (via the `shutdown` function) and the cleanup logic in the callee would never run. This was one of the reasons for the OTEL bug.
This meant that the behaviour of `Cli.run()` was pretty unpredictable and hard to track and the cleanup logic in the callee wasn't guaranteed to run. This was fixed in the …
> fix(otel): ensure OTEL sends final span when -o opt is used

- plugins/pulumi/src/helpers.ts
This PR addresses an issue where existing pulumi config files fail to be read in, and are then overwritten by Garden, essentially deleting all existing config from the file.
In `applyConfig()`, there's this line here that overwrites the pulumi config that gets read in:
```python
stackConfig.config = vars
```
The docs for the pulumi provider and actions aren't clear about how existing pulumi config files are handled, so I'm not sure if this is intentional or not, but I'm pretty sure this is meant to merge these values into the existing pulumi config, rather than overwriting it. Since I wasn't certain about whether or not this was intentional, I left it alone and just called it out here.
> fix(pulumi): prevent existing pulumi configs from being overwritten

- core/src/actions/types.ts
- core/src/events/util.ts
- core/src/graph/actions.ts
- core/src/graph/config-graph.ts
- core/src/util/testing.ts
- core/test/data/test-projects/kubernetes-type/module-simple/garden.yml
- core/test/integ/src/plugins/kubernetes/kubernetes-type/handlers.ts
- core/test/unit/src/actions/action-configs-to-graph.ts
- core/test/unit/src/config-graph.ts
- core/test/unit/src/garden.ts
- core/test/unit/src/plugins/container/container.ts
- core/test/unit/src/tasks/build.ts
- core/test/unit/src/tasks/deploy.ts
- core/test/unit/src/tasks/run.ts
Sends the action type to cloud so that it can e.g. be displayed in the graph UI and in command results in general. 
We weren't doing that previously because a bit of a legacy baggage but that has been resolved. 
Fixes #
Garden Cloud itself was updated awhile ago to handle this data so this only required Core fixes.
> improvement(api): send action type to cloud

- core/src/plugins/kubernetes/sync.ts
> fix(k8s): add imagePullSecret from kubernetes provider to sync init container

- core/src/plugins/kubernetes/sync.ts
Was thinking about this again and since the `imagePullSecrets` are added on the existing pod spec which could also come from a kubernetes or helm action we need to make sure we don't overwrite any `imagePullSecrets` that were specified on the pod spec from the original manifests since kuberenetes and helm type actions don't automatically use the provider `imagePullSecrets`.
Fixes #
> chore(k8s): push imagePullSecrets to existing for sync mode

- core/src/garden.ts
- core/src/graph/actions.ts
Handle potentially wrong action names produced from configuration templates,
when a templated action name from a config template is evaluated to `null` or `undefined`.
Such resolved template values are interpolated into the string values for the action names.
This is how the current template resolution engine works.
We should skip such dependencies instead of failing fast with an error.
Fixes #
> fix: fail-safe dependency config lookup in action config processing

- .circleci/continue-config.yml
See https://circleci.com/docs/migrate-from-deploy-to-run/
Fixes #
> ci: migrate from deprecated `deploy` to `run`

- core/src/graph/actions.ts
> chore: logging corrections and tweaks

- core/src/graph/actions.ts
Extra logging to get mored details on the slow functions returned by the profiler.
Fixes #
> chore: diagnostic logging

- docs/guides/code-synchronization.md
Updates the header on the docs for switching from the new mutagen back to old to match the content (new to old.) Docs are less confusing after the change.
I haven't checked if there is an existing issue. I assumed not, since it is minor.
> docs: fix header on migrating back to old mutagen

- core/src/plugins/kubernetes/commands/pull-image.ts
- core/src/plugins/kubernetes/config.ts
- core/src/plugins/kubernetes/constants.ts
- core/src/plugins/kubernetes/container/build/buildkit.ts
- core/src/plugins/kubernetes/container/build/common.ts
- core/src/plugins/kubernetes/container/build/kaniko.ts
- core/src/plugins/kubernetes/ephemeral/config.ts
- core/src/plugins/kubernetes/local-mode.ts
- core/src/plugins/kubernetes/nginx/default-backend.ts
- core/src/plugins/kubernetes/sync.ts
- core/test/integ/src/plugins/kubernetes/container/deployment.ts
- core/test/integ/src/plugins/kubernetes/container/ingress.ts
- core/test/integ/src/plugins/kubernetes/sync-mode.ts
- core/test/unit/src/plugins/kubernetes/container/build/buildkit.ts
- core/test/unit/src/plugins/kubernetes/container/build/common.ts
- core/test/unit/src/plugins/kubernetes/container/build/kaniko.ts
- core/test/unit/src/plugins/kubernetes/init.ts
- core/test/unit/src/plugins/kubernetes/kubernetes.ts
- docs/README.md
- docs/k8s-plugins/guides/registry-mirror.md
- docs/k8s-plugins/remote-k8s/configure-provider.md
- docs/k8s-plugins/remote-k8s/configure-registry/README.md
- docs/k8s-plugins/remote-k8s/configure-registry/docker-hub.md
- docs/misc/faq.md
- docs/reference/providers/ephemeral-kubernetes.md
- docs/reference/providers/kubernetes.md
- docs/reference/providers/local-kubernetes.md
Garden uses various utility container images, e.g. for the K8s sync utility pod, and hosts them on Docker Hub.
Some users have their own mirror of Docker Hub that they'd rather use instead of Docker Hub itself. This avoids issues with rate limiting among other things.
This commit adds a config field on the Kubernetes provider spec that allows users to configure what registry is used.
Note that it only allows users to specify the registry domain, not the repository, image name, or tag. So the assumption is that mirror has the exact same "layout" as Docker Hub itself which is usually (always?) the case.
If needed, we can later expose more granular control, e.g. setting the image tag, but that's not required for now. …
> feat(k8s): allow using registry mirror for utility images

- core/src/plugins/kubernetes/kubectl.ts
The old links refering to https://storage.googleapis.com/kubernetes-release have not been getting updated since the k8s 1.30.5 release.
Switch to https://dl.k8s.io/
Fixes #
> chore(tools): actualise kubectl download links

- .circleci/continue-config.yml
Update k8s integ test matrix to support the latest available k8s 1.31.
Fixes #
> ci: use v1.31.1+k3s1 in k3s integ tests

- docs/reference/action-types/Deploy/pulumi.md
- docs/reference/module-types/pulumi.md
- plugins/pulumi/src/action.ts
- plugins/pulumi/src/helpers.ts
- plugins/pulumi/src/index.ts
Some outputs in Pulumi are considered secrets, and you need to use the `--show-secrets` flag to show them. If you don't, secret outputs get replaced with `[secret]`. Because the Pulumi provider doesn't include the `--show-secrets` flag, you can't use outputs from Pulumi which are marked as secrets, which can really limit the usefulness of the Pulumi deploy action's outputs.
This PR makes it so that secret values are included in the output of the Pulumi deploy action.
> feat(pulumi): add `spec.showSecretsInOutput` config to Pulumi deploy action

- core/src/plugins/exec/config.ts
- core/src/plugins/exec/run.ts
- core/src/plugins/exec/test.ts
- core/test/unit/src/plugins/exec/exec.ts
- docs/reference/action-types/Build/exec.md
- docs/reference/action-types/Deploy/exec.md
- docs/reference/action-types/Run/exec.md
- docs/reference/action-types/Test/exec.md
> feat(exec): separate `stdout` and `stderr` in Run and Test `exec`-action outputs

- core/src/config/base.ts
- core/src/config/template-contexts/base.ts
- core/src/graph/actions.ts
- core/src/graph/common.ts
- core/src/router/base.ts
- core/src/tasks/resolve-action.ts
- core/src/template-string/template-string.ts
- core/src/util/profiling.ts
> fix(profiler): fix sync profiler and collect more data

- core/src/constants.ts
- core/src/graph/actions.ts
The actual value doesn't affect performance a lot.
Let's just keep batch size 100 to limit the object allocation rate in the runtime.
Fixes #
> chore: restore fixed action config proc batch size

- core/src/graph/actions.ts
Reverts:
* #6549
* Part of #6553
Fixes #
> revert: fix: fail-safe dependency config lookup in action config processing

- core/src/plugins/kubernetes/container/extensions.ts
- core/src/plugins/openshift/deploy.ts
Call base handler from original container plugin before doing extra validation.
This fixes the behaviour discrepancy between `Deploy` and `Run/Test` actions validation in container plugin.
**Reproducible example:**
<details>
<summary>Click to see the configuration</summary>
```yml
kind: Build
name: my-build
---
kind: Deploy
description: Desc
name: my-deploy
dependencies:
- build.my-build
spec:
image: ${actions.build.my-build.outputs.deploymentImageId}
volumes:
- name: "my-volume"
containerPath: "my-container-path"
action: deploy.config # <-- reference to an action that is not listed in the dependencies list
---
kind: Run
description: Desc
name: my-run
dependencies:
- …
```
> fix: correct deploy action validation in container plugin extension

- package-lock.json
- package.json
- scripts/release.ts
This has been broken this the major `inquirer` version bump in #6540.
A follow-up fix for #6540.
> chore: fix compilation error in `release.ts` script

- support/debian.Dockerfile
> chore(support): bump google/cloud-sdk to 499.0.0 in debian.Dockerfile

- core/src/plugins/kubernetes/run.ts
- core/src/plugins/kubernetes/status/pod.ts
- core/src/plugins/kubernetes/status/workload.ts
- core/src/plugins/kubernetes/util.ts
- core/test/data/test-projects/kubernetes-type/action-simple/garden.yml
- core/test/integ/src/plugins/kubernetes/kubernetes-type/handlers.ts
- core/test/integ/src/plugins/kubernetes/util.ts
Before this commit, we'd show Pod logs from all _main_ containers for a
given K8s resource on failure but not from init containers.
This meant that:
a) If an init container would fail the user wouldn't see any logs
b) If a main container fails the user would see logs from all main
containers in all Pods, potentially drowning out the actual error
message.
With this change, we now only show logs from failed containers, and
include init containers as well.
I bumped into this while working on #6563. This doesn't close that specific issue but it's basically the first in a trilogy of PRs meant to address that which I'm splitting up to make it easier to review. 
This is what it looked …
> Show Pod logs from failed containers

- core/src/plugins/kubernetes/helm/config.ts
- core/src/plugins/kubernetes/helm/deployment.ts
- core/src/plugins/kubernetes/helm/handlers.ts
- core/src/plugins/kubernetes/helm/helm-cli.ts
- core/src/plugins/kubernetes/kubernetes-type/handlers.ts
- core/src/plugins/kubernetes/status/status.ts
- core/src/plugins/kubernetes/status/workload.ts
- core/src/plugins/kubernetes/util.ts
- core/test/data/test-projects/helm/api/garden.yml
- core/test/data/test-projects/helm/api/templates/deployment.yaml
- core/test/data/test-projects/helm/api/values.yaml
- core/test/data/test-projects/kubernetes-type/with-build-action/with-build.garden.yml
- core/test/integ/src/plugins/kubernetes/helm/deployment.ts
- docs/reference/action-types/Deploy/helm.md
- docs/reference/module-types/helm.md
- examples/vote-helm/api.garden.yml
Previously we would use Garden's own resource monitoring to monitor the
health of a Helm install/upgrade and fail fast if one of the resources
was unhealthy as well as show K8s events and Pod logs.
In commit https://github.com/garden-io/garden/commit/7a68373a175b1e757b67f391030c643d0fde55d4 we replaced that with Helm's own `--wait` flag.
The reason for that change was because a user reported issues with
Garden returning early from the Helm command in the success case
(see https://github.com/garden-io/garden/pull/6078 and https://github.com/garden-io/garden/issues/6053 for more details).
The problem with that change is that since we weren't using our own
resource monitoring we stopped showing events and logs when Helm
installs/upgrades fail. Another …
> feat(k8s): show Helm events and logs

- core/src/constants.ts
- core/src/graph/config-graph.ts
- core/src/mutagen.ts
- core/src/plugins/kubernetes/constants.ts
- core/src/plugins/kubernetes/sync.ts
- core/test/unit/src/verify-ext-tool-binary-hashes.ts
- docs/guides/code-synchronization.md
This PR removes any reference to the old `mutagen` sync mode and removes the `GARDEN_ENABLE_NEW_SYNC` environment variable.
Fixes #
> chore: remove old mutagen sync method coda paths

- core/src/build-staging/helpers.ts
Remove unnecessary child-class and use type intersection with factory method instead.
Fixes compilation errors in #6622.
> refactor: get rid of `fs.Stats` constructor deprecation warning

- core/src/plugins/kubernetes/kubernetes-type/kubernetes-exec.ts
- core/test/data/test-projects/kubernetes-type/module-simple/garden.yml
- core/test/integ/src/plugins/kubernetes/kubernetes-type/kubernetes-exec-run.ts
Prior to this fix, the `kubernetes-exec` action type was not able to consider a specified `podSelector` as a valid resource query.
**Reproducible example.**
<details>
<summary>Click to expand</summary>
```yml
kind: Project
name: vote
environments:
- name: local
providers:
- name: local-kubernetes
environments: [ local ]
---
kind: Run
name: test-run
type: kubernetes-exec
spec:
command: [ "echo", "foo" ]
resource:
podSelector:
name: "my-pod"
```
</details>
Without this fix, the example above will crash with the following error:
```console
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── …
```
> fix(k8s): respect pod selector in kubernetes-exec action type

- plugins/pulumi/src/cli.ts
Addresses GHSA-xr7q-jx4m-x55m - google.golang.org/grpc vulnerability.
Fixes #
> chore: exclude pulumi from workflow-runner images

- core/src/mutagen.ts
When the mutagen version changes, all local mutagen processes need to be cleaned up. Additionally the resources with sync enabled need to be redeployed in kubernetes. This is because the`k8s-sync` init container needs to ship the same mutagen version as the local version. The error message so far recommended this, but because the `k8s-sync` init container does not affect the version hash the deploy command would not really redeploy the pods with an updated init-container with the update image version. Therefore an environment needs to be deleted before redeployed.
Many thanks to @kevinthenet  for the detailed workaround instructions.
Fixes #6662
> chore: improve mutagen version changed error message

- core/src/graph/actions.ts
> chore: logging cleanup

- core/src/plugins/kubernetes/container/publish.ts
Allows using the regctl publish method which copies an image from one registry to another if the `--push` `extraArgs` are set in the build action spec. This behavior was already used for the container provider but is with this PR also usable when using the kubernetes provider.
Fixes #
> fix(publish): copy image from registry if it has been pushed directly after build

- core/src/plugins/kubernetes/kubernetes-type/kubernetes-exec.ts
In the kubernetes-exec actions we were not passing on the `action.spec.resource.containerName` resulting in always the first container to be picked e.g. for test actions.
Fixes #
> fix(k8s-exec): use containerName if specified for kubernetes-exec actions

- core/src/config/module.ts
- docs/reference/commands.md
- docs/reference/config-template-config.md
- docs/reference/module-types/configmap.md
- docs/reference/module-types/conftest.md
- docs/reference/module-types/container.md
- docs/reference/module-types/exec.md
- docs/reference/module-types/hadolint.md
- docs/reference/module-types/helm.md
- docs/reference/module-types/jib-container.md
- docs/reference/module-types/kubernetes.md
- docs/reference/module-types/persistentvolumeclaim.md
- docs/reference/module-types/pulumi.md
- docs/reference/module-types/terraform.md
While build dependencies had a special behavior in garden modules, in garden 0.13.x all modules are converted to actions and build dependencies between modules are not a thing anymore. This means that this special behavior in which the build in a disabled garden module will still run in case there is a build dependency on it does not exist any longer.
Fixes #
> docs: update docs about disabled modules

- garden-sea/src/node.rs
You can trigger flamegraph generation by exporting the environment variable `GARDEN_FLAMGEGRAPH=1`.
This will call the tool `0x` via `npx`. Kudos [to the authors of 0x](https://github.com/davidmarkclements/0x).
> feat(cli): allow generating flamegraphs for performance analysis

- core/src/template-string/template-string.ts
- core/test/unit/src/template-string.ts
Old error due to bug:
```
$filter clause in $forEach loop must resolve to a boolean value (got object)
```
New error:
```
Invalid template string (${var.volume-mount-set == item.key}) at path MY_VOLUMES.$concat.$filter: Could not find key volume-mount-set under var. Available keys: $merge, MY_VOLUMES and volumes.
```
> fix: improve error message if filter expression in foreach cannot be resolved

- core/src/template-string/ast.ts
- core/test/unit/src/template-string.ts
Older versions of garden did not throw an error when referencing
missing variables from unary operators like `!` and `typeof`. This
commit restores backwards-compatiblity that has been broken in #6685
> fix: retain bug-compatibility for referencing missing variables in unary operators (`!` and `typeof`).

- core/src/plugins/kubernetes/local/local.ts
We use the `clusterType` config field to determine the status of the nginx ingress controller when applicable for the `local-kubernetes` provider.
Before this fix however, we'd set the `clusterType` on the provider config (if needed) in the `prepareEnvironment` handler and not the `getEnvironmentStatus` handler.
This basically resulted in the `getEnvironmentStatus` handler always returning that nginx wasn't ready, then the `clusterType` would be set in the `prepareEnvironment` and the status checked again, this time correctly.
Now we "correctly" set the `clusterType` in the `getEnvironmentStatus` (arguably it should be set in the `configureProvider` handler but that would be a bigger refactor and I believe this is a pattern we use in other places as …
> fix(local-k8s): ensure correct nginx status when getting env status

- core/src/config/base.ts
- core/src/config/validation.ts
- core/src/exceptions.ts
- core/src/plugins/kubernetes/kubernetes-type/common.ts
- core/test/unit/src/config/base.ts
- core/test/unit/src/config/validation.ts
- core/test/unit/src/template-string.ts
- plugins/pulumi/src/helpers.ts
Include a snippet to the template string in a YAML file, and point to
YAML file if available.
> improvement: Point to YAML file for template string error messages if possible

- core/src/cloud/auth.ts
- core/src/cloud/backend.ts
- core/src/commands/login.ts
Makes `AuthRedirectServer` backend-agnostic.
Fixes #
> refactor(cloud): encapsulate backend-specific configs

- core/src/config/template-contexts/base.ts
- core/src/plugins/kubernetes/kubernetes-type/common.ts
- core/src/template-string/ast.ts
- core/src/template-string/parser.pegjs
- core/src/util/fs.ts
- core/test/data/test-projects/kubernetes-type/legacyAllowPartial/garden.yml
- core/test/data/test-projects/kubernetes-type/legacyAllowPartial/k8s/ifblock-doesnotexist.yaml
- core/test/data/test-projects/kubernetes-type/legacyAllowPartial/k8s/ifblock-false.yaml
- core/test/data/test-projects/kubernetes-type/legacyAllowPartial/k8s/ifblock-true.yaml
- core/test/integ/src/plugins/kubernetes/kubernetes-type/common.ts
- core/test/unit/src/template-string.ts
Template strings in Kubernetes manifest files are partially resolved for legacy reasons. The partial resolve behaviour has been changed to improve sanity in https://github.com/garden-io/garden/pull/6685 but for kubernetes manifest files, we need to have a version of the old behaviour.
The expected legacy behaviour looks like this:
- If template strings reference variables that do not exist there is no error
- If a template string contains multiple template expressions, each expression can be partially resolved.
- Template expressions are evaluated before parsing yaml, which means that valid yaml with template expressions can be resolved to invalid yaml (e.g. if variable values contain special characters)
This legacy behaviour can lead to quite some …
> fix(template): establish backwards bug-compatibility for kubernetes manifest files

- .circleci/continue-config.yml
This fixes CI build errors like [this](https://app.circleci.com/pipelines/github/garden-io/garden/28054/workflows/a0b286db-6ad9-4426-a7cd-b04e4110f682).
The Rust version 1.77.2 (that we used before) is no longer compatible with some dependencies.
Fixes #
A follow-up PR for #6000.
> ci(build-dist): update Rust version to 1.83.0

- core/src/graph/solver.ts
- core/test/unit/src/graph/solver.ts
This fix makes the `loop`  method in the solver much more efficient for large graphs (lots of actions and dependencies).
While graph evaluation in the solver isn't usually the performance bottleneck, the performance impact can be noticeable in larger projects.
Here, we use a generator to get leaf nodes ready for processing (whereas previously, we'd traverse the whole pending graph on each loop iteration and load it node-by-node into a new dependency graph data structure, which was costly when iterating over a large graph in a tight loop).
We also used a simple boolean flag (dirty) in the solver to track whether any tasks had been requested or completed (successfully or with an error) since the last loop. This was used to avoid evaluating the graph …
> perf: optimise solver graph evaluation loop

- plugins/pulumi/src/action.ts
- plugins/pulumi/src/helpers.ts
- plugins/pulumi/src/index.ts
- plugins/pulumi/test/test-project-k8s/k8s-namespace-new-module/Pulumi.local.yaml
- plugins/pulumi/test/test-project-k8s/k8s-namespace-new-module/Pulumi.yaml
- plugins/pulumi/test/test-project-k8s/k8s-namespace-new-module/garden.yml
- plugins/pulumi/test/test-project-k8s/k8s-namespace-new-module/index.ts
- plugins/pulumi/test/test-project-k8s/k8s-namespace-new-module/package-lock.json
- plugins/pulumi/test/test-project-k8s/k8s-namespace-new-module/package.json
- plugins/pulumi/test/test-project-k8s/k8s-namespace-new-module/varfile-new-schema.yaml
- plugins/pulumi/test/test-project-k8s/k8s-namespace-new/garden.yml
- plugins/pulumi/test/variables.ts
Enables the new Pulumi varfile schema for modules (implemented in https://github.com/garden-io/garden/pull/6729).
Fixes #6726
> feat(pulumi): enable new varfile schema for modules

- core/src/config/render-template.ts
- core/src/config/workflow.ts
- core/src/graph/actions.ts
- core/src/resolve-module.ts
- core/test/data/test-projects/config-templates-partial/garden.yml
- core/test/data/test-projects/config-templates-partial/schema.json
- core/test/unit/src/garden.ts
This PR fixes an issue where in certain cases we get errors like "`Could not find key item`" or "`Could not find key inputs`" since `0.13.46`, where the template parser has been rewritten.
Another PR is currently in progress, #6745, which will also fix this issue by capturing contexts instead of partially resolving templates. That PR won't get ready this week anymore though.
This fix is not complete, as the implementtion before 0.13.45 was not either – in certain situations partial resolution isn't cutting it, for example a template string like `${actions.build[input.name].outputs.log}`. Those cases will be solved by #6745
> fix: resolve parts of template strings, even if another part cannot be resolved yet.

- .github/workflows/reusable-create-homebrew-pr.yml
This became necessary due to https://github.com/cuchi/jinja2-action/issues/22 to keep updating our homebrew formula
> ci: replace broken jinja action with sed script

- core/src/vcs/git-repo.ts
That log statement can produce tens of megabytes of logs that do not help in debugging.
Fixes #
> chore: remove too noisy silly-log message

- core/src/plugin-context.ts
- core/src/plugins/kubernetes/init.ts
- core/src/plugins/kubernetes/kubernetes-type/handlers.ts
- core/src/plugins/kubernetes/namespace.ts
- core/src/router/base.ts
- core/test/integ/src/plugins/kubernetes/kubernetes-type/handlers.ts
- core/test/integ/src/plugins/kubernetes/namespace.ts
- core/test/integ/src/plugins/kubernetes/provider.ts
This was fixed by setting up the event forwarding during the initialization of the plugin event bus.
Before this fix, `namespaceStatus` events weren't actually being emitted during provider resolution, since the event bus on the plugin context hadn't been set up to pipe `namespaceStatus` events to the main event bus (this happened later in the flow).
This is the probable cause for some users experiencing dangling namespaces that weren't being cleared up by Cloud's automatic environment cleanup when module/action resolution failed (since the namespace status events that would usually be emitted by the "get status" and "deploy" handlers for those actions weren't being emitted). This still needs to be verified, but most likely fixes the issue.
> fix(core): emit namespaceStatus events during provider init

- docs/getting-started/installation.md
Garden requires Windows 10 or later and does not care about the edition. Docker Desktop on the other hand has more specific requirements.
> docs(install): clarify windows OS requirements

- core/src/plugin/handlers/Provider/getEnvironmentStatus.ts
- core/src/plugin/handlers/Provider/prepareEnvironment.ts
- core/src/plugins/exec/exec.ts
- core/src/plugins/kubernetes/commands/cluster-init.ts
- core/src/plugins/kubernetes/init.ts
- core/src/plugins/kubernetes/local/local.ts
- core/src/plugins/kubernetes/namespace.ts
- core/src/plugins/kubernetes/nginx/default-backend.ts
- core/src/plugins/kubernetes/nginx/ingress-controller-base.ts
- core/src/plugins/kubernetes/nginx/ingress-controller.ts
- core/src/plugins/kubernetes/nginx/nginx-helm.ts
- core/src/plugins/kubernetes/nginx/nginx-kind.ts
- core/src/plugins/kubernetes/nginx/nginx-microk8s.ts
- core/src/plugins/kubernetes/nginx/nginx-minikube.ts
- core/src/tasks/resolve-provider.ts
- core/test/integ/src/plugins/kubernetes/ingress-controller.ts
- core/test/integ/src/plugins/kubernetes/provider.ts
- core/test/unit/src/commands/get/get-outputs.ts
- core/test/unit/src/garden.ts
- core/test/unit/src/outputs.ts
- core/test/unit/src/router/provider.ts
- plugins/terraform/src/init.ts
- plugins/terraform/test/terraform.ts
Previously, Garden would first run the `getEnvironmentStatus` handler
and depending on the results, either run the `prepareEnvironment`
handler or not.
Now we always run the `prepareEnvironment` handler (if the provider
status is not cached).
The reason for this change is that the previous flow is an
unneeded abstraction that doesn't serve any purpose at this point and
makes the provider initialisation harder to reason about.
The specific motivation is that there's bug in the Kubernetes
provider where some resources aren't created when the
environment is prepared. It's actually more work to first check
the statuses of these resources, return those, and then create
them. In particular since we have helpers to create them in
an idempotent manner. …
> Simplify provider init

- core/src/plugins/kubernetes/config.ts
- core/src/plugins/kubernetes/container/build/common.ts
A `ConfigurationError` is now thrown instead of `InternalError` if the `deploymentRegistry` is not configured on the provider-level when using in-cluster building.
So Garden do not crash and quits gracefully with informative error message.
Fixes #
An attempt to use conditional validation for `deploymentRegistry` of the provider configuration was taken in 250b658cc9c40c4306f92a28bdef7e1b20c09a71.
It was reverted because of the of conditional validation support in the reference docs generation.
> fix: do not crash on missing `deploymentRegistry` for in-cluster builds

- core/src/plugin/handlers/Provider/getEnvironmentStatus.ts
- core/src/plugin/providers.ts
- core/src/tasks/resolve-provider.ts
In a previous commit we changed the behaviour such that the `getEnvironmentStatus` handler isn't called before preparing an environment and instead the `prepareEnvironment` handler is always called.
This leaves the `getEnvironmentStatus` pretty useless and it's currently only called with `statusOnly` commands like `garden get status`.
In these cases we might as well set the environment status to `unknown` and remove these handlers altogether and that's why we're deprecating it now.
Fixes #
> chore(framework): mark `getEnvironmentStatus` handler as deprecated

- core/src/commands/create/create-project.ts
Found this little bug which was causing the `garden create project` command to render a `project.garden.yaml` file with an `undefined` project name.
Fixes #
> fix: when using create project, the project name is undefined

- core/src/plugins/kubernetes/run.ts
Improve error handling when trying to create the archive of artifacts. 
Additionally, increases the timeout for the `tar` command to 10 minutes.
Fixes #
> improvement: add better error handling when failing to archive test artifacts

- core/src/actions/base.ts
- core/src/config/base.ts
- core/src/config/project.ts
- core/src/config/provider.ts
- core/src/config/references.ts
- core/src/config/secrets.ts
- core/src/config/template-contexts/base.ts
- core/src/config/template-contexts/input.ts
- core/src/config/template-contexts/variables.ts
- core/src/outputs.ts
- core/src/resolve-module.ts
- core/src/template/analysis.ts
- core/src/template/capture.ts
- core/src/template/templated-collections.ts
- core/test/data/test-projects/variable-crossreferences/garden.yml
- core/test/data/test-projects/variable-crossreferences/module-a/garden.yml
- core/test/data/test-projects/variable-crossreferences/module-b/garden.yml
- core/test/unit/src/commands/workflow.ts
- core/test/unit/src/config/project.ts
- core/test/unit/src/config/provider.ts
- core/test/unit/src/config/render-template.ts
- core/test/unit/src/config/template-contexts/base.ts
- core/test/unit/src/config/template-contexts/variables.ts
- core/test/unit/src/config/workflow.ts
- core/test/unit/src/garden.ts
- core/test/unit/src/template-string.ts
- core/test/unit/src/vcs/vcs.ts
Allows cross-referencing variables in the same scope.
Fixes #2730 (and some regressions of variable lookup behaviour introduced in #6745, there is no need to mention them in the release notes because we have not released it so far)
There are some caveats that are covered in the test cases, to maintain backwards-compatibility with older versions of 0.13.
> feat: allow cross-referencing variables in the same scope

- core/src/plugins/kubernetes/container/build/common.ts
Instead of failing completely, assume image needs to be rebuilt and print a warning. 
This is meant as a pain relieve for the issue encountered in this Discord thread: https://discord.com/channels/817392104711651328/1313997959121211463/1313997959121211463
This is not a full solution for the problem encountered in the thread.
> fix(cluster-buildkit): assume image needs rebuild if skopeo command fails and print a warning

- cli/src/cli.ts
- core/src/garden.ts
- core/src/plugin/sdk.ts
- core/src/plugins/hadolint/hadolint.ts
- core/src/plugins/plugins.ts
- core/src/util/deprecations.ts
- docs/guides/deprecations.md
This Pr deprecated some old plugins. It used the new deprecation machinery introduced in #6820.
Fixes #
> chore(plugins): deprecate conftest, hadolint and octant plugins

- docs/guides/deprecations.md
- docs/reference/providers/terraform.md
- plugins/terraform/src/handlers.ts
- plugins/terraform/src/helpers.ts
- plugins/terraform/src/provider.ts
This commit introduces a config option to optionally stream Terraform
logs to Garden Cloud/Enterprise.
Defaults to `false` but we may reconsider in a later breaking change
release.
Fixes #
> improvement(terraform): enable streaming logs to cloud

- core/src/exceptions.ts
- docs/reference/action-types/Deploy/terraform.md
- docs/reference/module-types/terraform.md
- docs/reference/providers/terraform.md
- docs/terraform-plugin/about.md
- docs/terraform-plugin/actions.md
- docs/terraform-plugin/configure-provider.md
- examples/terraform-dynamic-backend/README.md
- examples/terraform-dynamic-backend/main.tf
- examples/terraform-dynamic-backend/project.garden.yml
- plugins/terraform/package.json
- plugins/terraform/src/action.ts
- plugins/terraform/src/commands.ts
- plugins/terraform/src/handlers.ts
- plugins/terraform/src/helpers.ts
- plugins/terraform/src/init.ts
- plugins/terraform/src/provider.ts
- plugins/terraform/test/terraform.ts
- plugins/terraform/test/test-project-backendconfig-action/garden.yml
- plugins/terraform/test/test-project-backendconfig-action/tf/main.tf
- plugins/terraform/test/test-project-backendconfig/garden.yml
- plugins/terraform/test/test-project-backendconfig/tf/main.tf
This change introduces a `backendConfig` field on the Terraform
provider and action types.
This field allows users to dynamically set the backend config for
their Terraform stacks.
Terraform itself doesn't allow variables in the backend config
so this can be used instead to dynamically set the backend
based on e.g. the environment.
Fixes #
I still need to update the docs on the Terraform provider and remove the "`sed` hack". It's also an open question whether we mark this as experimental for now. 
But I can address both in a follow up PR.
> improvement(terraform): support dynamic backends

- core/src/actions/base.ts
- core/src/docs/generate.ts
- core/src/util/deprecations.ts
- docs/guides/deprecations.md
- docs/reference/action-types/Deploy/configmap.md
- docs/reference/action-types/Deploy/container.md
- docs/reference/action-types/Deploy/exec.md
- docs/reference/action-types/Deploy/helm.md
- docs/reference/action-types/Deploy/kubernetes.md
- docs/reference/action-types/Deploy/persistentvolumeclaim.md
- docs/reference/action-types/Deploy/pulumi.md
- docs/reference/action-types/Deploy/terraform.md
- docs/reference/action-types/Run/container.md
- docs/reference/action-types/Run/exec.md
- docs/reference/action-types/Run/helm-pod.md
- docs/reference/action-types/Run/kubernetes-exec.md
- docs/reference/action-types/Run/kubernetes-pod.md
- docs/reference/action-types/Test/conftest-helm.md
- docs/reference/action-types/Test/conftest.md
- docs/reference/action-types/Test/container.md
- docs/reference/action-types/Test/exec.md
- docs/reference/action-types/Test/hadolint.md
- docs/reference/action-types/Test/helm-pod.md
- docs/reference/action-types/Test/kubernetes-exec.md
- docs/reference/action-types/Test/kubernetes-pod.md
- docs/reference/commands.md
- docs/reference/providers/terraform.md
The `build` config field is not recommended to use since #5700 and #6207.
This PR officially deprecates that config field.
Fixes #
> chore: deprecate `build` config field in runtime actions

- core/src/garden.ts
- core/src/util/deprecations.ts
- docs/guides/deprecations.md
The legacy (rsync-based) file syncing mode for build staging has not been used since #6758.
Fixes #
> chore: deprecate rsync-based file syncing for build staging

- core/src/commands/sync/sync-start.ts
- core/src/util/deprecations.ts
- docs/guides/deprecations.md
Re-work #5747 to use the new deprecation machinery introduced in #6820 and #6823.
Fixes #
> chore(sync-mode): use new machinery for `sync start` deprecation

- core/src/plugins/kubernetes/volumes/configmap.ts
- core/src/plugins/kubernetes/volumes/persistentvolumeclaim.ts
- core/src/util/deprecations.ts
- docs/guides/deprecations.md
Fixes #
If a migration guide is necessary, it can be written in a follow-up PR. We have a project task to compose a migration guide, so the guide will not be missed.
> chore(k8s): deprecate `configmap` and `persistentvolumeclaim` deploy actions

- core/src/tasks/base.ts
Fix the case when an action depends on runtime outputs of a disabled action.
Error rendering example before fix:
```console
Run type=exec name=run-task depends on one or more runtime outputs from action
key() {
return actionReferenceToString(this);
}, which is disabled. Please either remove the reference or enable the action.
```
Error rendering example after fix:
```console
Run type=exec name=run-task depends on one or more runtime outputs from action deploy.tf-production, which is disabled. Please either remove the reference or enable the action.
```
The `action.key` function was not called in the error message, so it was rendered as a part of the code. Now it's fixed.
This PR also fixes some action name highlighting and removes unnecessary …
> fix: dependency error message rendering

- core/src/config/template-contexts/variables.ts
- core/test/data/test-projects/varfiles-with-templates/garden.yml
- core/test/data/test-projects/varfiles-with-templates/vars-action.yml
- core/test/data/test-projects/varfiles-with-templates/vars-env.yml
- core/test/data/test-projects/varfiles-with-templates/vars-project.yml
- core/test/unit/src/actions/action-configs-to-graph.ts
- core/test/unit/src/config/template-contexts/variables.ts
A follow-up fix for #6745
Fixes #6843
> fix(template): parse template strings in varfiles

- core/src/actions/base.ts
- core/src/actions/types.ts
- core/src/commands/base.ts
- core/src/commands/get/get-actions.ts
- core/src/commands/serve.ts
- core/src/events/action-status-events.ts
- core/src/plugin/base.ts
- core/src/plugin/handlers/Build/get-status.ts
- core/src/server/server.ts
- core/src/util/ink-divider.tsx
- core/src/util/logging.ts
- core/test/unit/src/server/server.ts
We were including the raw graph results in the results of commands requested over HTTP from the live page. This was always unnecessary (and the data structures involved were excessively large), but only started resulting in errors with our recent templating improvements (previously, we'd just leave the unresolved template strings in there).
Fixes live-mode commands run from the Cloud UI to fail under certain conditions.
> fix(dev): fix unresolved templates in cmd results

- core/src/config/provider.ts
- core/src/config/references.ts
- core/src/config/secrets.ts
- core/src/outputs.ts
- core/src/template/analysis.ts
- core/src/template/ast.ts
- core/src/template/capture.ts
- core/src/template/lazy-merge.ts
- core/src/template/templated-collections.ts
- core/src/template/templated-strings.ts
- core/src/template/types.ts
- core/test/unit/src/template-string.ts
This PR changes `getContextLookupReferences` to ignore dead code
branches
Fixes an issue where we considered implicit dependencies from action references in dead code branches.
**Addititional info**:
There was an alternate solution attempt, here: https://github.com/garden-io/garden/pull/6849
One of the benefits of the approach of detecting dead branches is that it now also works with logical AND (`&&`), logical OR (`||`), ternary expressions (`? :`) and if block expressions (`${if ...}`) and not just with structural if operators (`$if:` yaml keys).
Example / minimal repro:
```
kind: Project
name: test
environments:
- name: local
variables:
disabled: ${true}
---
kind: Run
type: exec
name: …
```
> fix: do not consider implicit dependencies from action references in dead code branches

- core/src/config/base.ts
- core/src/config/template-contexts/variables.ts
Ensures that template error messages in YAML varfiles will be correct
Correction for error behaviour for the changes in #6844
> fix: correct source mapping in varfiles

- core/src/build-staging/helpers.ts
This fixes the `scanDirectoryForClone` helper to always return paths in POSIX format. It makes the path comparison logic correct for all platforms, including Windows.
Fixes #
> fix(build-staging): fix the detection of paths to be deleted

- core/src/cli/cli.ts
- core/src/cli/params.ts
- core/src/logger/logger.ts
- core/test/unit/src/logger/logger.ts
Before this fix, setting the `GARDEN_LOGGER_TYPE` environment variable to `basic` would cause line-by-line logs to be written even if the `--output` option was being used.
This caused the output of the command no longer to be valid JSON/YAML.
> fix(core): always suppress logs when `--output` is used

- core/src/actions/types.ts
- core/src/commands/get/get-actions.ts
- core/test/unit/src/commands/get/get-actions.ts
- docs/reference/commands.md
See #6902 for more background. This adds additional fields to the `garden get actions --detail` output, which can be parsed to use images published by Garden for other deployments.
It adds the following new fields to the actions output:
- `version`: the full resolved version of a Garden action, including `versionString` and `files`.
- `allowPublish`: the value of `allowPublish` in the Garden action.
- `publishId`: the value of the `publishId` in the Garden action spec, or the default publish ID derived by Garden from the action name.
Fixes #6902
> feat(cli): add more fields to garden get actions detailed output

- core/src/plugins/kubernetes/kubernetes-type/kubernetes-pod.ts
Prior to fix the `spec.cacheResult: false` would not have any effect for Test actions of type `kubernetes-pod`.
This PR fixes it to respect the behaviour of that flag described in the [docs](https://docs.garden.io/reference/action-types/test/kubernetes-pod#spec.cacheresult).
The default value is still `true`. So, there are no breaking changes in the behaviour.
Fixes #
> fix(k8s): respect `spec.cacheResult` flag in `kubernetes-pod` Test actions

- CHANGELOG.md
- README.md
- cli/package.json
- core/package.json
- docs/getting-started/quickstart.md
- docs/guides/using-garden-in-circleci.md
- docs/k8s-plugins/actions/deploy/kubernetes.md
- docs/k8s-plugins/remote-k8s/ingress-and-dns.md
- docs/reference/action-types/Build/jib-container.md
- docs/reference/module-types/jib-container.md
- docs/reference/providers/conftest-kubernetes.md
- docs/reference/providers/conftest.md
- docs/reference/providers/hadolint.md
- docs/reference/providers/jib.md
- docs/terraform-plugin/about.md
- docs/terraform-plugin/configure-provider.md
- docs/use-cases/jumpstart-idp.md
- docs/use-cases/local-development-remote-clusters.md
- docs/use-cases/on-demand-preview-envs.md
- e2e/package.json
- package-lock.json
- package.json
- plugins/conftest-container/package.json
- plugins/conftest-kubernetes/package.json
- plugins/conftest/package.json
- plugins/jib/package.json
- plugins/pulumi/package.json
- plugins/terraform/package.json
- sdk/package.json
This is a maintenance release that includes some bug fixes, features, and improvements.
Garden 0.14 (Cedar) will be out soon, and this release of 0.13 (Bonsai) will warn you when you're relying on functionality that will be removed or that will be changed in the upcoming Garden 0.14 (Cedar) release.
If you're seeing such warnings, we recommend to follow the steps behind the link to silence them.
For the complete list of breaking changes in Garden 0.14, please refer to the [Deprecations and updating to Cedar](https://docs.garden.io/bonsai-0.13/guides/deprecations) guide in the docs.
Many thanks to @klara-meyer for contributing #6903 to this release!
Download the Garden binary for your platform from below or simply run `garden self-update` if you already have it installed.
* [Garden …
> chore: release `0.13.55`

- core/src/plugins/kubernetes/container/run.ts
- core/src/plugins/kubernetes/container/test.ts
- core/src/plugins/kubernetes/helm/helm-pod.ts
- core/src/plugins/kubernetes/kubernetes-type/kubernetes-pod.ts
- core/src/plugins/kubernetes/results-cache.ts
- core/src/plugins/kubernetes/run-results.ts
- core/src/plugins/kubernetes/test-results.ts
- core/test/integ/src/plugins/kubernetes/container/run.ts
- core/test/integ/src/plugins/kubernetes/helm/run.ts
- core/test/integ/src/plugins/kubernetes/kubernetes-type/kubernetes-exec-run.ts
- core/test/integ/src/plugins/kubernetes/kubernetes-type/kubernetes-exec-test.ts
- core/test/integ/src/plugins/kubernetes/kubernetes-type/kubernetes-pod-run.ts
- core/test/integ/src/plugins/kubernetes/task-results.ts
- core/test/integ/src/plugins/kubernetes/test-results.ts
Introduce `ResultCache` interface to avoid usage of a set of standalone helpers and ensure the usage of proper data types.
Fixes #
> refactor(k8s): introduce cache abstraction for `getResult` handlers of Run and Test actions

- core/src/logger/renderers.ts
Before this fix, empty messages from origins such as Kubernetes or Terraform would be misaligned. This fixes that.
Fixes #
> fix(logger): fix alignment for empty lines msg has section

- core/src/cloud/grow/api.ts
- core/src/cloud/grow/trpc.ts
- core/src/plugins/container/build.ts
- core/src/plugins/container/cloudbuilder.ts
Remove unnecessary error translation inside the tRPC client.
This PR also refactors the Cloud API V2 class by making its `api` field (a reference to the underlying tRPC client) private:
* The API calls are implemented as methods of the class.
* The methods delegate to the underlying tRPC client and do the error handling.
Fixes #
> fix(cloud): remove unnecessary error translation inside the tRPC client

- .circleci/continue-config.yml
Otherwise, e2e tests fail randomly with the errors complaining about the GCR deprecation. It looks like this error starts occurring after a certain number of requests.
Fixes #
> ci(e2e): temporarily mute some e2e tests

- core/src/plugins/container/config.ts
- core/src/plugins/container/container.ts
- core/src/plugins/container/moduleConfig.ts
- core/src/plugins/kubernetes/kubernetes-type/config.ts
- core/src/plugins/kubernetes/kubernetes-type/kubernetes-pod.ts
- core/src/util/deprecations.ts
- docs/guides/deprecations.md
- docs/reference/action-types/Deploy/container.md
- docs/reference/action-types/Deploy/kubernetes.md
- docs/reference/action-types/Run/container.md
- docs/reference/action-types/Run/kubernetes-pod.md
- docs/reference/action-types/Test/container.md
- docs/reference/action-types/Test/kubernetes-pod.md
- docs/reference/module-types/container.md
- docs/reference/module-types/jib-container.md
- docs/reference/providers/container.md
> (0.13) fix: add deprecation for action volume references, as that's implied when deprecating persistentvolumeclaim and configmap action types

- core/src/graph/actions.ts
- core/test/unit/src/actions/action-configs-to-graph.ts
- core/test/unit/src/graph/actions.ts
We now infer an `executed: true`  dependency for action output references when the referenced action is a Build, regardless of whether the output is a static or a runtime output.
This improves the user experience for the common use-case of referencing a container image in a runtime resource (like a `helm` Deploy), where the user intent is almost always that the referenced build should exist (i.e. the dependency should be processed) before the runtime resource is processed (i.e. deployed or run).
This is because Builds generally don't have side-effects other than producing artifacts, whereas Deploys and Runs often do.
Note: We could also always execute Test actions that are referenced, but we'll stick with only Builds for now.
> feat(framework): automatically infer action dependencies from references of `Build` actions outputs

- core/src/graph/actions.ts
- core/src/project-api-version.ts
- core/test/setup.ts
- core/test/unit/src/actions/action-configs-to-graph.ts
- core/test/unit/src/graph/actions.ts
- core/test/unit/src/template-string.ts
We now infer an `executed: true`  dependency for action output references when the referenced action is a Build, regardless of whether the output is a static or a runtime output.
We only do this for API version v2 (and keep the old behavior for v1 and v0).
This improves the user experience for the common use-case of referencing a container image in a runtime resource (like a `helm` Deploy), where the user intent is almost always that the referenced build should exist (i.e. the dependency should be processed) before the runtime resource is processed (i.e. deployed or run).
This is because Builds generally don't have side-effects other than producing artifacts, whereas Deploys and Runs often do.
Note: We could also always execute Test actions that are …
> (cherry pick #6979) improvement(core): fixes to output reference logic

- core/src/cloud/grow/auth.ts
> fix(cloud): automatically clear locally stored auth token if refresh token is invalid

- core/src/plugins/container/config.ts
- core/src/plugins/kubernetes/kubernetes-type/config.ts
- core/src/plugins/kubernetes/local/config.ts
- plugins/jib/src/index.ts
Some templatable configuration fields have type string and are marked as optional.
Since we no longer support the optional string syntax, the default values fallback values like `null` or `""` can violate the schema definitions.
In order to overcome that, we can interpret such special values as `undefined`, so those will be compatible with `joi.string().optional()` definition.
This is done by using `joi.empty(["", null])`. The same approach was used in pulumi plugin.
Fixes #
> fix(template): coerce `null` and empty strings to `undefined` in config fields of type optional-string

- core/src/cli/params.ts
- core/src/commands/self-update.ts
Fixes the crash while running self-update command with any non-existing `number`-compatible value, like `1` or `0.13`.
All values that can be interpreted as `number` in JavaScript are not getting converted to strings. So, the original issue comes from the `Parameter` class; the `StringParameter` does not ensure the `string` type of the runtime console input.
This PR brings a quick fix. Let's revisit the CLI parameter validation after the 0.14 release.
Fixes #6953
> fix(self-update): do not crash on missing numeric version

- core/src/cloud/api.ts
- core/src/plugins/container/build.ts
- core/src/plugins/container/cloudbuilder.ts
- core/src/plugins/container/container.ts
- core/src/plugins/kubernetes/container/build/kaniko.ts
- core/src/plugins/kubernetes/container/build/local.ts
- core/src/util/util.ts
- docs/reference/providers/container.md
* Rename "Garden Container Builder" to "Remote Container Builder"
* Align the saved time log message shape between Team Cache and Remote Container Builder
Now both logs have the logs like `${feature message} (saved ${rendered time})`.
~We still use separate helper functions to render saved time in Team Cache and Remote Container features.~
~The difference is that the former renders the values less than 1 second in the form of `{ddd}ms` and the latter one as `{0.dd} seconds`.~
~Do we want to align that formatting too? Which one is preferred? We can do it in a follow-up PR.~
Aligned the part above my always rendering actual ms for time spans less that 1 second. Zero-length time spans are rendered to empty strings.
> chore: update Remote Container logging

- core/src/plugins/container/cloudbuilder.ts
Prior to this fix it was impossible to enable/disable the Remote Container Builder via the relevant env var.
That was because of the wrapper condition `if (!!containerProviderConfig.gardenContainerBuilder)` that was a left-over from the version where we supported 2 backends.
This PR removes that wrapper condition and fixes the issue.
Fixes #
> fix: make Remote Container Builder controllable via env var

- core/src/plugins/container/cloudbuilder.ts
- core/src/plugins/container/container.ts
- docs/reference/providers/container.md
- feat: enable container builder by default when logged in to the new backend
- docs: update docs
- docs: regenerate docs
> feat: enable container builder by default on app.garden.io

- .circleci/continue-config.yml
- core/src/plugins/container/container.ts
This fixes some regression introduced in 0.14.0 and re-enables e2e tests which were disabled in #6965 and #6967.
> fix(module-k8s): fix `deploymentImageId` in module conversion

- core/src/plugins/kubernetes/constants.ts
- core/src/plugins/kubernetes/nginx/nginx-helm.ts
- core/src/plugins/kubernetes/nginx/nginx-kind-manifests.ts
> fix(k8s): update to nginx ingress controller 1.12.1 that is not affected by RCE vulnerability

- RELEASE_PROCESS.md
Update branch names:
* `main` to `0.13`
* `latest-release` to `latest-release-0.13`
Fixes #
> chore: update release guide for 0.13

- core/src/commands/self-update.ts
Fixes the regression in `garden self-update --major` behavior which was introduced by #7000.
Fixes #7039
> fix(self-update): fix version detection when use `--major` flag

- core/src/commands/sync/sync-stop.ts
Back-port #7056 to 0.13 (cherry picked from commit 88f564aa50dcb24c3fa2ffa33e24e0990d78c366).
Fixes #
> fix(sync): await monitors stop on `sync stop` completion

- core/src/graph/actions.ts
- core/test/data/test-projects/disabled-action-without-provider/garden.yml
- core/test/unit/src/garden.ts
We can avoid throwing an error in `processActionConfig` if the action is disabled.
Disabled actions with configured provider pass the error-check defined in `processActionConfig`. So, this PR ensures that the disabled actions without configured providers also pass that check.
Anyway, the disabled actions will not be executed, so there is no harm is bypassing that error-check.
At that point we know the resolved value of the `disabled` flag on the action config, so we can use it to identify disabled actions.
Fixes #6957
> fix: do not throw on unknown action types for disabled actions

- core/src/graph/actions.ts
- core/test/data/test-projects/disabled-action-without-provider/garden.yml
- core/test/unit/src/garden.ts
The helper ensures the correct and consistent behavior, because the action can be disabled not only explicitly by `disabled: true` flag, but also implicitly over the environment configuration.
Follow-up fix for #7062.
> fix(graph): use a special helper to check if an action is disabled

- core/src/plugins/kubernetes/commands/cleanup-cluster-registry.ts
- core/src/util/deprecations.ts
- docs/guides/deprecations.md
> chore: deprecate `cleanup-cluster-registry` command in `kubernetes` and `local-kubernetes` plugins

- .circleci/continue-config.yml
Update Kubernetes test matrix for intergation tests.
Kubernetes 1.29 was EOLed: https://endoflife.date/kubernetes
Fixes #
> ci(integ): update kind from 1.29.8 to 1.32.3

- core/src/plugins/container/build.ts
If time saved is zero, we want to still let the user know that the remote container builder has been utilised. We just won't display the time we saved
> fix: log "accelerated by remote container builder" even when timeSaved is 0

- core/src/plugins/container/cloudbuilder.ts
- core/src/plugins/container/container.ts
- docs/reference/providers/container.md
Prior to this this, the env variable `GARDEN_CONTAINER_BUILDER` and its deprecated alias `GARDEN_CLOUD_BUILDER` were only taken into account when the corresponding provider level `gardenContainerBuilder` (or deprecated `gardenCloudBuilder`) configurations were explicitly defined in the `garden.yml` config file.
Now, the override via env vars still takes precedence over the file-based config, but it's also possible to avoid any configs in file and use only env vars.
**Expected behavior:**
```console
GARDEN_CLOUDBUILDER=1 garden build 
```
The flag enables Remote Container Builder.
See the [0.13 docs](https://docs.garden.io/bonsai-0.13/reference/providers/container#providers-.gardencontainerbuilder.enabled):
> by …
> fix(container): always respect env vars to control remote builder

- core/src/config/common.ts
- core/src/config/template-contexts/project.ts
- core/src/docs/common.ts
- core/src/docs/joi-schema.ts
- docs/reference/commands.md
- docs/reference/template-strings/action-all-fields.md
- docs/reference/template-strings/action-specs.md
- docs/reference/template-strings/environments.md
- docs/reference/template-strings/modules.md
- docs/reference/template-strings/project-outputs.md
- docs/reference/template-strings/projects.md
- docs/reference/template-strings/providers.md
- docs/reference/template-strings/remote-sources.md
- docs/reference/template-strings/workflows.md
- docs/reference/workflow-config.md
This PR fixes the propagation of `deprecated` and `internal` meta flags of joi objects to their children.
Now we don't need to explicitly set `.meta({ internal: true })` on every child of an already internal joi schema to hide it from the generated docs.
The same fix applies to the `deprecated` meta flag.
There are also some type-safety improvements.
Fixes #
> chore: fix `deprecated` and `internal` flags propagation in reference docs 

- core/src/config/common.ts
- core/src/config/template-contexts/project.ts
- core/src/docs/common.ts
- core/src/docs/joi-schema.ts
- docs/reference/action-types/Deploy/container.md
- docs/reference/action-types/Deploy/helm.md
- docs/reference/action-types/Deploy/kubernetes.md
- docs/reference/commands.md
- docs/reference/module-types/container.md
- docs/reference/module-types/helm.md
- docs/reference/module-types/jib-container.md
- docs/reference/module-types/kubernetes.md
- docs/reference/providers/container.md
- docs/reference/template-strings/action-all-fields.md
- docs/reference/template-strings/action-specs.md
- docs/reference/template-strings/environments.md
- docs/reference/template-strings/modules.md
- docs/reference/template-strings/project-outputs.md
- docs/reference/template-strings/projects.md
- docs/reference/template-strings/providers.md
- docs/reference/template-strings/remote-sources.md
- docs/reference/template-strings/workflows.md
- docs/reference/workflow-config.md
Back-ports  #7142 to 0.13.
Fixes #
> chore: fix `deprecated` and `internal` flags propagation in reference docs

- core/src/garden.ts
- core/src/graph/solver.ts
- core/src/util/profiling.ts
- core/test/integ/src/plugins/kubernetes/container/build/build.ts
- core/test/unit/src/graph/solver.ts
- core/test/unit/src/tasks/resolve-action.ts
> fix(solver): throw if a dependency failed and `throwOnError` is true

- core/src/graph/actions.ts
- core/test/unit/src/actions/action-configs-to-graph.ts
- core/test/unit/src/graph/actions.ts
Back-port #7171 to 0.13.
Fixes #
> fix: prevent unnecessary execution of builds referenced in runtime actions

- .circleci/config.yml
Update the `circleci/path-filtering` orb version to the latest available.
That update was also done in 0.13 branch to make it possible to use path filtering, see #7181. Otherwise, the filtering step was failing.
Fixes #
> ci: update `circleci/path-filtering` orb version to 1.2.0

- .github/workflows/publish-release.yml
It has been failing starting from 0.13.24: https://www.npmjs.com/package/@garden-io/core
Fixes #
> chore: disable npm package publishing in release pipeline

- core/src/actions/base.ts
- core/src/config/base.ts
- core/src/plugins/container/config.ts
- core/src/plugins/kubernetes/config.ts
- core/src/plugins/kubernetes/kubernetes-type/config.ts
- core/src/plugins/kubernetes/local-mode.ts
The behavior of `deprecated` and `internal` metadata flags of joi schemas was fixed in #7174.
Now both of the flags are propagated to the child-objects recursively.
The presense of both flags makes no sense on the joi-schema level, because internal fields are never rendered in the reference documentation.
This PR removes the unnecessary manual flag declarations, and minimized the usage of `deprecated: true` flag with a `boolean` value. The goal is to get rid of the boolean values at all, and use type-safe deprecation flags which will be implemented in #7143.
Fixes #
The code joi-schema code changes made in this PR did not cause any changes in the generated reference docs.
> chore: cleanup in joi schema definitions

- core/src/plugins/container/config.ts
- core/src/plugins/container/moduleConfig.ts
- core/src/plugins/kubernetes/kubernetes-type/kubernetes-pod.ts
- core/src/plugins/kubernetes/kubernetes-type/module-config.ts
- core/src/util/deprecations.ts
- docs/misc/deprecations.md
- docs/reference/action-types/Run/kubernetes-pod.md
- docs/reference/action-types/Test/kubernetes-pod.md
We overlooked that in 0.14 release.
In fact, the `spec.files` field has not effect at all, but it could still be specified in the configuration file without a schema validation error.
This PR hides the reference documentation and prints warnings if the obsolete field is still defined in a configuration file.
Fixes #
> chore: deprecation for `spec.files` in `kubernetes-pod` action type

- core/package.json
- core/src/config-store/base.ts
- package-lock.json
We've seen some users encountering error messages when Garden couldn't
acquire the config store lock.
We're already preventing data corruption on concurrent modification by
relying on atomically writing by creating a new file and moving it.
This commit changes the lock mechanism to only protect concurrent writes
from the same garden process, but we accept data loss in the unlikely
event another garden process also updates the config store at the same
time (one of the writes will win).
Fixes #
> fix: improve reliability by removing config store file lock

- core/src/plugins/container/config.ts
- core/src/plugins/kubernetes/container/deployment.ts
- core/src/plugins/kubernetes/container/util.ts
- core/src/util/deprecations.ts
- core/test/unit/src/commands/get/get-config.ts
- core/test/unit/src/plugins/kubernetes/container/util.ts
- docs/misc/deprecations.md
- docs/reference/action-types/Deploy/container.md
- docs/reference/module-types/container.md
- docs/reference/module-types/jib-container.md
This PR also brings a minor UX improvement similar to #7068.
Now Garden prints a warning if both deprecated and new syntax is used. No behaviour breaking changes here. The old syntax is preferred and a user is informed.
This PR also simplifies the responsibility of function `getResourceRequirements`, that is no longer responsible for combining old and new config entries.
This also unlocks #7143.
Fixes #
> chore: deprecate legacy container limit syntax

- plugins/terraform/src/commands.ts
- plugins/terraform/src/handlers.ts
- plugins/terraform/src/helpers.ts
- plugins/terraform/test/terraform.ts
Before this fix, we weren't passing the `backendConfig` to Terraform when using plugins commands.
That is, for commands like `garden plugins terraform apply-root` the `backendConfig` specified in the Garden config would be ignored.
This commit fixes that and adds tests.
Fixes #
> fix(terraform): use backendConfig with plugin commands

- core/src/cloud/api.ts
- core/src/cloud/backend.ts
- core/src/cloud/grow/api.ts
- core/src/cloud/grow/auth.ts
- core/src/cloud/grow/trpc.ts
- core/src/commands/logout.ts
- core/test/unit/src/commands/logout.ts
* Handle tRPC errors on calls via non-authenticated client
* Align auth error handling in between old and new backends
* Less confusing logging on logout
```console
You're already logged out from https://grow.garden.io.
Successfully logged out from https://grow.garden.io.
```
is now just
```console
You're already logged out from https://grow.garden.io.
```
and the sucessful message is printed only on successful token revocation.
Fixes #7238
> fix(cloud): handle tRPC errors in authentication functions

- plugins/terraform/src/commands.ts
- plugins/terraform/src/handlers.ts
- plugins/terraform/src/helpers.ts
- plugins/terraform/test/terraform.ts
Cherry pick changes from #7249 to 0.13 branch. See original PR description below.
---
* fix(terraform): use backendConfig with plugin commands
Before this fix, we weren't passing the `backendConfig to Terraform when using plugins commands.
That is, for commands like `garden plugins terraform apply-root` the `backendConfig` specified in the Garden config would be ignored.
This commit fixes that and adds tests.
* tests: fix terraform tests
Fixes #
> fix(terraform): use backendConfig with plugin commands (#7249)

- core/src/plugin/handlers/base/configure.ts
- core/src/plugins/container/config.ts
- core/src/plugins/container/container.ts
- core/src/plugins/container/moduleConfig.ts
- core/src/plugins/kubernetes/container/deployment.ts
- core/src/plugins/kubernetes/container/service.ts
- core/src/plugins/kubernetes/helm/action.ts
- core/src/plugins/kubernetes/kubernetes-type/deploy.ts
- core/src/util/deprecations.ts
- docs/misc/deprecations.md
- docs/reference/action-types/Deploy/container.md
- docs/reference/module-types/container.md
- docs/reference/module-types/jib-container.md
This PR restores the missing docs that were mentioned in #1825 and uses the new deprecation utilities to deprecate the config field properly and emit warnings on its usage.
This PR also allows to bring #7143 to the finish line.
Fixes #
> chore: deprecate `hostPort` in `container` Deploy action spec

- core/src/plugins/kubernetes/constants.ts
- images/buildkit/Dockerfile
- images/buildkit/garden.yml
* Update `moby/buildkit` to v0.23.1
* Update `docker-credential-ecr-login` to 0.10.0
* Update `docker-credential-gcr` to 2.1.29
Supersedes #7375
> chore(images): version updates in Garden's `buildkit` docker image

- cli/package.json
- core/package.json
- e2e/package.json
- package-lock.json
- package.json
- sdk/package.json
We use Node 22 in production.
Supersedes #7385
> chore: update engine requirements to node >=22 and npm >=10

- .tool-versions
- cli/package.json
- core/lib/fsevents/package.json
- core/package.json
- e2e/package.json
- package-lock.json
- package.json
- plugins/jib/package.json
- plugins/pulumi/package.json
- plugins/terraform/package.json
- sdk/package.json
Combines the following renovate PRs:
* #7370
* #7371
* #7378
* #7385
* #7410
* #7411
* #7412
* #7415
This is done because of concurrency issues with pulumi plugin test. So the `test-plugins` fails quite often when multiple pipelines are running.
Fixes #
> chore(deps): cumulative dependency updates from renovate bot

- renovate.json
* Group minor and patches dependencies for npm and cargo package managers separately.
* Always combine major updates for dev dependencies.
* Ignore updates for copied libs like `fsevents`
The goal is to split the dependencies by language/package manager and to minimize the number of produced PRs.
We still keep individual PRs for major updates in prod dependencies, but for dev dependencies it should be fine to combine.
Fixes #
> chore(renovate): group PRs by package manager and version scope

- core/src/plugins/kubernetes/config.ts
- core/src/plugins/kubernetes/container/sync.ts
- core/src/plugins/kubernetes/kubernetes-type/config.ts
- core/src/plugins/kubernetes/sync.ts
- core/src/util/deprecations.ts
- core/test/integ/src/plugins/kubernetes/sync-mode.ts
- docs/misc/deprecations.md
- docs/reference/action-types/Deploy/kubernetes.md
- docs/reference/action-types/Run/kubernetes-pod.md
- docs/reference/action-types/Test/kubernetes-pod.md
- docs/reference/module-types/kubernetes.md
- plugins/README.md
This PR makes deprecates the usage of `podSelector` in sync mode.
The code was changed to throw a config error if only `podSelector` is specified as a target resource for sync mode.
That `podSelector` did not work properly prior to this fix and could lead to either a runtime error or to a non-working sync mode with warning. Throwing a meaningful configuration error looks like a better UX here.
Fixes #
> chore: deprecate `podSelector` in sync mode

- core/src/cloud/grow/grpc-event-stream.ts
- core/test/unit/src/cloud/grow/grpc-event-stream.ts
This PR fixes a regression introduced in https://github.com/garden-io/garden/pull/7457
- test: implement failing unit test case for out of order events
- fix: avoid out of order events (flush all buffered events before writing new incoming events)
> fix(GrpcEventStream): avoid out of order events

- .github/dependabot.yml
We maintain it manually to be consistent with `@buf/garden_grow-platform.bufbuild_es`.
Follow-up change for #7442.
> chore(dependabot): disable updates for `@bufbuild/protobuf`

- core/package.json
- package-lock.json
The `glob` library now has its own types and the `@types/glob` should not be used.
See https://www.npmjs.com/package/@types/glob
Supersedes #7513
> chore(deps): remove deprecated `@types/glob`

- renovate.json
There is no such option like `mergeConfidence`. Let's delete it.
Follow-up fix for #7564.
Fixes #7566 
> chore(renovate): fix config syntax

- core/src/config/template-contexts/base.ts
- core/src/config/template-contexts/variables.ts
- core/src/template/ast.ts
- core/src/template/capture.ts
- core/src/template/errors.ts
- core/test/data/test-projects/variable-crossreferences-merge/garden.yml
- core/test/data/test-projects/variable-crossreferences/garden.yml
- core/test/unit/src/config/template-contexts/base.ts
- core/test/unit/src/config/template-contexts/variables.ts
- core/test/unit/src/garden.ts
- core/test/unit/src/template-string.ts
This is a backport of #7550 for 0.13.
* fix(template): do not throw circular reference error
Fixes a condition we overlooked when implementing the new cross references feature (introduced in https://github.com/garden-io/garden/pull/6814)
In old garden versions, template expressions like
```
variables:
foo: ${var.foo}
```
where totally normal, as ${var.foo} just referred to a value in the parent context.
With cross referencing in mind, we will try to resolve var.foo in the peer variable context, but if that leads to a circular reference error we fall back to resolving the value in the parent context.
This seems like a good compromise to preserve the new functionality while retaining the behaviour from older garden versions.
> fix(template): do not throw circular reference error when resolving cross-references in the same scope

- core/src/garden.ts
- core/src/plugins/exec/build.ts
- core/src/plugins/exec/common.ts
- core/src/plugins/exec/config.ts
- core/src/plugins/exec/deploy.ts
- core/src/plugins/exec/run.ts
- core/src/plugins/exec/test.ts
- core/src/util/testing.ts
- core/test/unit/src/commands/build.ts
- core/test/unit/src/plugins/exec/common.ts
- core/test/unit/src/plugins/exec/exec.ts
- docs/reference/action-types/Build/exec.md
- docs/reference/action-types/Deploy/exec.md
- docs/reference/action-types/Run/exec.md
- docs/reference/action-types/Test/exec.md
From the docs:
---
Exec actions can write outputs to a JSON file or a directory. The action command is provided with the path to the outputs directory or JSON file via the `GARDEN_ACTION_OUTPUTS_PATH` or `GARDEN_ACTION_OUTPUTS_JSON_PATH` environment variables.
If you write a JSON file to `<GARDEN_ACTION_OUTPUTS_JSON_PATH>` this file will be read and its contents will be used as the action outputs. Nested JSON objects are not supported. Only the top-level key-value pairs, where values are primitive types (string, number, boolean, null), will be used.
You can also write outputs to files in the directory. In this scenario, each file with a valid identifier as a filename (this excludes paths starting with `.` for example) in the directory will be read and its filename will be added as the key …
> feat(exec): support arbitratry outputs from exec actions

- core/src/actions/base.ts
- core/src/commands/plugins.ts
- core/src/config/project.ts
- core/src/config/template-contexts/project.ts
- core/src/docs/generate.ts
- core/src/garden.ts
- core/src/graph/actions.ts
- core/src/graph/config-graph.ts
- core/src/tasks/resolve-action.ts
- core/test/data/test-projects/project-exclude-values/actions.garden.yml
- core/test/data/test-projects/project-exclude-values/project.garden.yml
- core/test/helpers.ts
- core/test/unit/src/actions/base.ts
- core/test/unit/src/config/project.ts
- core/test/unit/src/garden.ts
- docs/reference/project-config.md
This simplifies action version exclusion for larger projects. Effectively this allows adding a set of values to every action's `version.excludeValues`, which can make filtering out ephemeral values much simpler across many actions.
From the Project `excludeValuesFromActionVersions` reference:
---
A list of string values that should be excluded when computing action versions.
Setting values here is equivalent to adding them to the \`version.excludeValues\` field on all actions in the project.
These values can be templated, and generally should be templated. A typical example is to exclude the namespace of the environment, or a hostname suffix used across many Deploy actions. For example:
```yaml
excludeValuesFromActionVersions:
- "${var.hostname-suffix}"  # resolving to something like …
```
> feat(config): add project-level excludeValuesFromActionVersions field

- core/package.json
- core/src/actions/base.ts
- core/src/actions/types.ts
- core/src/cli/params.ts
- core/src/commands/commands.ts
- core/src/commands/diff.ts
- core/src/commands/logs.ts
- core/src/config/project.ts
- core/src/config/template-contexts/project.ts
- core/src/docs/common.ts
- core/src/docs/config.ts
- core/src/garden.ts
- core/src/graph/config-graph.ts
- core/src/util/string.ts
- core/test/data/test-projects/diff/garden.yml
- core/test/integ/src/commands/diff.ts
- core/test/unit/src/commands/diff.ts
- core/test/unit/src/commands/logs.ts
- core/test/unit/src/config-graph.ts
- core/test/unit/src/config/project.ts
- core/test/unit/src/config/template-contexts/module.ts
- core/test/unit/src/config/template-contexts/project.ts
- core/test/unit/src/config/template-contexts/workflow.ts
- docs/reference/commands.md
- package-lock.json
Adds an experimental command to compare the current project to a given branch,
commit, different variables, environment etc.
This is experimental for now, but should be good enough to ship and get
feedback.
From the command help text:
---
**[EXPERIMENTAL] This command is still under development and may change in the future, including parameters and output format.**
Compare the current working directory Garden project with the specified branch or commit.
Use this to understand the impact of your changes on action versions.
In most cases you should use this with the --resolve flag to ensure that the comparison is complete, but take caution as it may result in actions being executed during resolution (e.g. if a runtime output is referenced by another action, it will be executed in order to …
> feat: garden diff command, to compare action versions between branches/commits

- .circleci/continue-config.yml
- scripts/release.ts
- support/debian.Dockerfile
This commit fixes a couple of things I bumped into when releasing 0.14.8.
One was that there's apt-get install command that's missing the "-y" flag and timing out in CI.
I'm assuming this is coming up now because we merged a dependabot PR that updated the Dockerfile base image. Not sure why this hasn't come up before though.
Another issue was with an expired token and simply add a comment in the relevant place.
Fixes #
> chore(ci): fix apt-get command missing '-y' flag

- core/src/plugins/container/container.ts
Because the `spec.image` field is required for these actions, the input image is generally enough to determine the version. Users can manually set include/exclude if needed.
> improvement: default to `include:[]` for container Deploy/Test/Run actions
