core/src/plugins/container/build.ts
Tiny fix the ensures the second line in the error message isn't indented. 
Fixes #
=> fix(container): ensure error message is properly indented

core/src/plugins/container/config.ts, core/src/plugins/kubernetes/helm/config.ts, core/src/plugins/kubernetes/local-mode.ts, docs/reference/action-types/Deploy/container.md, docs/reference/action-types/Deploy/helm.md, docs/reference/action-types/Deploy/kubernetes.md, docs/reference/module-types/container.md, docs/reference/module-types/helm.md, docs/reference/module-types/jib-container.md, docs/reference/module-types/kubernetes.md
=> docs(local-mode): documentation update

core/src/cli/autocomplete.ts, core/src/commands/serve.ts, core/test/unit/src/cli/autocomplete.ts
See the added/updated test cases for detail. cc @trymbill
=> improvement(autocomplete): handful of small improvements based on feedback

core/src/cli/cli.ts, core/src/cloud/api.ts, core/src/commands/custom.ts, core/src/garden.ts, core/src/logger/logger.ts, core/src/plugins/kubernetes/status/status.ts, core/test/unit/src/analytics/analytics.ts, core/test/unit/src/logger/logger.ts
This is a cherry pick from the 0.12 branch. The original commit was for changes to the basic logger which don't really apply on 0.13 so conflicts were mostly solved by selecting the current 0.13 head. 
I'm working on further log fixes on a separate branch and will fix any issues this cherry pick may cause there. 
Fixes #
=> 0.13 cherry-pick: improvement(logger): various fixes to make basic logger render nicer

.github/ISSUE_TEMPLATE/0-13-issue-template.md
It was a bit tricky to write as it has to cover both issues and feature request but it'll have to do for now.
=> Add 0.13 issue template

scripts/test-release.sh
=> chore: fix sync mode testing in `test-release.sh`

README.md, core/src/commands/get/get-debug-info.ts, docs/advanced/cert-manager-integration.md, docs/basics/quickstart.md, docs/guides/adopting-garden.md, docs/guides/migrating-from-docker-compose.md, docs/k8s-plugins/about.md, docs/k8s-plugins/advanced/deploying-to-production.md, docs/k8s-plugins/remote-k8s/create-cluster/README.md, docs/misc/faq.md, docs/welcome.md
The discord link on the docs welcome page is expired however I found the working link in the README, so replaced the expired link everywhere with the working one.
Fixes #
N/A
=> docs: update discord invite link

scripts/test-release.sh
=> 0.13 fixes and improvements in `test-release.sh` script 

core/src/commands/self-update.ts, core/test/unit/src/commands/self-update.ts, docs/reference/commands.md
Cherry-picks #4022 to the `0.13` branch.
Fixes #
=> 0.13 cherry-pick: feat: support pre-release versions in `self-update` command (#4022)

core/test/integ/src/plugins/kubernetes/container/ingress.ts, core/test/unit/src/plugins/kubernetes/init.ts, core/test/unit/src/plugins/kubernetes/kubernetes.ts
Fixes #
This doesn't fix them all, but it fixes some of them that I bumped into when working on another thing.
=> chore(tests): use invalid domains instead of possibly-used ones

core/src/cli/autocomplete.ts, core/src/commands/base.ts, core/src/server/commands.ts, core/src/server/server.ts, core/test/unit/src/cli/autocomplete.ts, core/test/unit/src/server/server.ts
Makes it more straightforward to feed autocomplete suggestions back to the API.
cc @trymbill
=> improvement(api): allow unstructured string arguments in HTTP API commands

examples/local-mode/backend-local-1/.gitignore, examples/local-mode/backend-local-1/garden.yml, examples/local-mode/backend-local-2/.gitignore
=> chore(examples): clean up accidentally added files in local-mode example

core/src/plugins/kubernetes/kubernetes-type/common.ts, core/test/integ/src/plugins/kubernetes/container/ingress.ts, core/test/integ/src/plugins/kubernetes/kubernetes-module/handlers.ts
Works locally but want to make sure this doesn't trip up any integ tests
=> 0.13: fix kubernetes type sync

core/src/cli/cli.ts
* remove version check, because 0.13 branch still uses `0.12.x` version
* change 'beta' status to 'alpha'
Fixes #
=> chore: update 0.13 status warning

core/src/docs/generate.ts, docs/reference/action-types/README.md
=> docs: fix action kind rendering in reference docs

.github/workflows/actionlint.yml, .github/workflows/scorecards.yml
=> 0.13 cherry-pick: some dependency updates

docs/k8s-plugins/local-k8s/install.md
---------
Cherry-pick #3986 to `0.13`.
Fixes #
=> 0.13 cherry-pick: docs: update docs for minikube registry auth (#3986)

examples/vote-helm/worker-image/pom.xml, examples/vote/worker/pom.xml
=> 0.13 update example deps from main

docs/basics/how-garden-works.md
=> docs: embed 'How Garden Works' video to guide

core/src/plugins/kubernetes/commands/pull-image.ts
Cherry-picking https://github.com/garden-io/garden/pull/4094 onto 0.13 🍒 🌸
=> fix: use the correct secret in pullFromExternalRegistry in kaniko builds

core/src/commands/create/create-module.ts, core/src/commands/create/create-project.ts, core/src/commands/custom.ts, core/src/config/base.ts, core/src/garden.ts, core/test/unit/src/config/base.ts
This is in preparation for a transition to Bonsai (0.13).
=> refactor(config): warn on invalid kind instead of failing

core/src/config/module.ts, docs/misc/troubleshooting.md, docs/reference/commands.md, docs/reference/config-template-config.md, docs/reference/module-types/configmap.md, docs/reference/module-types/conftest.md, docs/reference/module-types/container.md, docs/reference/module-types/exec.md, docs/reference/module-types/hadolint.md, docs/reference/module-types/helm.md, docs/reference/module-types/jib-container.md, docs/reference/module-types/kubernetes.md, docs/reference/module-types/persistentvolumeclaim.md, docs/reference/module-types/pulumi.md, docs/reference/module-types/templated.md, docs/reference/module-types/terraform.md, docs/using-garden/configuration-overview.md, docs/using-garden/modules.md
Use the new `scan` configuration field instead of the deprecated ` modules` field.
This augments the changes made in #3069 and #4036, and partially addresses #4067.
Fixes #
=> 0.13 docs: update docs about include/exclude and ".ignore" files

core/src/plugin/handlers/base/base.ts, core/src/plugins/kubernetes/kubernetes-type/kubernetes-exec.ts
=> 0.13: some cleanup

docs/using-garden/config-templates.md
=> 0.13 docs vova 2

docs/README.md, docs/guides/running-service-in-local-mode.md
=> docs: update local mode guide to use `0.13` terms

docs/using-garden/using-the-cli.md
Also added some TODOs
Fixes #
There is still 1 TODO comment, because we don't `garden create action(s)` command yet.
=> docs: 0.13 update "Using the CLI" guide

core/src/plugins/kubernetes/kubernetes-type/kubernetes-exec.ts, docs/k8s-plugins/action-types/container.md, docs/k8s-plugins/action-types/helm.md, docs/reference/action-types/Run/kubernetes-exec.md, docs/reference/action-types/Test/kubernetes-exec.md, examples/vote-helm/postgres/garden.yml, examples/vote-helm/vote/garden.yml, examples/vote-helm/worker/garden.yml
Please make your way to the commits
=> 0.13: update docs, examples and some code

core/src/commands/cloud/helpers.ts, core/src/commands/cloud/secrets/secrets-delete.ts, core/src/commands/cloud/users/users-delete.ts, docs/reference/commands.md
Cherry-pick #4120 to `0.13`.
Fixes #
=> 0.13 cherry-pick: refactor: accept strings as secret and user ids in delete command

core/src/plugins/kubernetes/sync.ts
=> 0.13 sync mode fixes

core/src/plugins/kubernetes/logs.ts
Port https://github.com/garden-io/garden/pull/4131 to 0.13
Fixes #
=> 0.13 port: fix(k8s): stop retrying in LogFollower when Pod is in terminal phase

core/test/unit/src/logger/log-entry.ts, docs/README.md
Removes `.only` to run all the tests and fixes a missing doc link.
Fixes #
=> chore: 0.13 fix run all tests and add docs link

core/src/cloud/buffered-event-stream.ts, core/src/logger/log-entry.ts, core/src/logger/logger.ts, core/src/logger/renderers.ts, core/test/unit/src/logger/logger.ts, core/test/unit/src/logger/renderers.ts, core/test/unit/src/util/util.ts
Fix broken tests that got merged due to `only` flag being set. 
Fixes #
=> Fix broken tests (WIP)

core/src/commands/custom.ts
Fixes custom commands such as `garden generate-migration` in our platform repo
=> fix: custom commands: spread true

core/src/config/base.ts, core/test/unit/src/config/base.ts
Changed the error messages related to apiVersion.
Fixes #
=> chore: 0.13 fix apiVersion message

core/test/data/test-projects/helm/postgres/garden.yml, core/test/integ/src/plugins/kubernetes/helm/common.ts, e2e/projects/tasks-modules/postgres/garden.yml, e2e/projects/vote-helm-modules/postgres/garden.yml, examples/run-actions/postgres/garden.yml, examples/vote-helm/postgres/garden.yml, plugins/conftest-kubernetes/test/test-project/helm/garden.yml
This is an attempt to fix the remaining flakiness in the `vote-helm` end-to-end tests.
=> chore(examples): update postgres helm chart

core/src/commands/deploy.ts, core/src/commands/logs.ts, core/src/monitors/logs.ts, core/test/unit/src/commands/logs.ts
=> 0.13 fix tail since flags 2

core/src/server/server.ts
Tiny fix to for the server logs. I'll probably be adding a couple more but wanted to get this in to reduce log noice. 
Fixes #
=> improvement(server): bump log level to silly on debug line

.github/workflows/actionlint.yml, .github/workflows/scorecards.yml
harden-runner would be useful in our actual build or release workflows, but has no benefits actually in lint and scorecard.
Fixes #
=> chore: remove harden-runner

core/src/cli/command-line.ts, core/src/commands/deploy.ts, core/src/commands/dev.tsx
commits have all the juicy details
Solves https://github.com/orgs/garden-io/projects/5/views/1?pane=issue&itemId=23638561
=> 0.13 fix: dev mode react state update on unmounted component

core/src/server/server.ts, core/test/unit/src/server/server.ts
=> fix(server): ensure GARDEN_SERVER_PORT env var is respected

core/src/logger/log-entry.ts, core/src/tasks/base.ts, core/test/unit/src/logger/log-entry.ts
- improvement: remove unused code
- fix(framework): inherit metadata in createActionLog
Fixes #
=> fix(framework): inherit metadata in createActionLog

core/src/plugin/base.ts, core/src/plugin/handlers/Run/run.ts, core/src/plugin/handlers/Test/run.ts
=> 0.13 minor cleanup

.circleci/config.yml
=> ci(dockerhub): fix mistake in circleci bash script

support/docker-bake.hcl
Previously we tried to concatenate a list with a string which did not work.
Fixes #
=> fix: cache to fix

core/src/constants.ts, docs/reference/commands.md
Switching the Cloud Dashboard domain to https://app.garden.io
Fixes #
=> chore: update cloud dashboard domain

.circleci/config.yml
- re-enable windows tests in CI
- re-enable microk8s tests in CI
Fixes #
=> build: re-enable windows & microk8s tests in ci

core/src/commands/base.ts, core/src/server/commands.ts, core/src/server/server.ts
=> improvement(server): tone down server logs

.circleci/config.yml, support/docker-bake-test.sh, support/docker-bake.hcl
It does not work with the docker driver, unfortunately.
Co-authored-by: Tim Beyer <TimBeyer@users.noreply.github.com>
Fixes #
=> ci(docker): remove cache in bakefile

.circleci/config.yml
See https://discord.com/channels/817392104711651328/1107301553838227497
Fixes #
=> chore(ci): own pre-release tag for Bonsai

core/src/events.ts, core/src/plugin-context.ts, core/src/plugins/exec/convert.ts, core/src/plugins/kubernetes/container/status.ts
=> 0.13 more cleanup

core/src/commands/run.ts, examples/demo-project/backend/backend.garden.yml
=> fix: fix search predicate in `Run` action detection

core/src/server/server.ts
=> fix(server): ensure we clear tree cache before ws command runs

core/src/cli/autocomplete.ts, core/src/cli/command-line.ts, core/src/commands/dev.tsx, core/test/unit/src/cli/autocomplete.ts, core/test/unit/src/garden.ts
Couple of small things, see commits.
=> Small dev console fixes

docs/tutorials/migrating-to-bonsai.md
`apiVersion` is not a breaking change per se. Move mentioning the apiVersion to a separate section of the document, and link the Garden Cloud docs.
Fixes https://github.com/orgs/garden-io/projects/5/views/1?filterQuery=apiVersion&pane=issue&itemId=28052216
Should be reviewed together with https://github.com/garden-io/garden-platform/pull/2564
=> 0.13 docs(migration-guide): add information about mixed use and Garden Cloud

CONTRIBUTING.md, docs/README.md, docs/guides/using-garden-in-ci.md, docs/reference/dockerhub-containers.md, support/alpine.Dockerfile, support/buster.Dockerfile, support/docker-bake-test.sh, support/docker-bake.hcl
Add rootless container variant for use in environments where
using the root user is not possible, for example GitLab's Runner Operator
Supersedes #3865
Addresses #3993
=> feat(dockerhub): publish rootless containers

core/src/plugin/tools.ts, docs/reference/providers/terraform.md, plugins/terraform/cli.ts
Adding a new `terraform` version `1.4.6` which is currently the latest stable release.
This is required because some of our example code already depends on `required_version = ">= 1.3.0"`, but we only ship `1.2.9` with garden.
=> 0.13 update terraform

core/src/cloud/api.ts, core/src/garden.ts
Reduce/remove logging related to the dashboard. We print the link to the dashboard when connected and these logs are more for debugging. 
Fixes #
=> chore: 0.13 remove dashboard log

core/package.json, core/src/cli/command-line.ts, core/src/commands/dev.tsx, yarn.lock
=> improvement(dev): show spinner while commands are running

core/src/cli/cli.ts, docs/reference/module-types/configmap.md, docs/reference/module-types/conftest.md, docs/reference/module-types/container.md, docs/reference/module-types/exec.md, docs/reference/module-types/hadolint.md, docs/reference/module-types/helm.md, docs/reference/module-types/jib-container.md, docs/reference/module-types/kubernetes.md, docs/reference/module-types/persistentvolumeclaim.md, docs/reference/module-types/pulumi.md, docs/reference/module-types/templated.md, docs/reference/module-types/terraform.md, docs/using-garden/actions.md, static/docs/templates/module-type.hbs
- Adds a deprecation warning to all module type reference pages .
- fix a typo in action docs
- change bonsai issue report link to shinny new shortlink ;) 
Fixes #
=> Short bonsai report link & update docs with deprecation warning to module types reference pages

.circleci/config.yml
=> ci(dockerhub): fix tag release

docs/other-plugins/container.md, examples/vote-helm/worker/garden.yml
=> docs: 0.13 update for `container` plugin guide

.circleci/config.yml
=> ci(dockerhub): fix missing codename for stable releases

.circleci/config.yml
- port dockerhub tag release logic
- support events from main and 0.13 in circleci
Fixes #
=> ci(circleci): prepare 0.13 merge to main

core/test/data/test-projects/helm/api-image/requirements.txt, core/test/data/test-projects/kubernetes-module/api-image/requirements.txt, examples/vote-helm/api-image/requirements.txt, examples/vote/api/requirements.txt
To avoid unexpected runtime errors caused by backwards incompatibility between the library versions.
Cherry-pick #4237 to `main`.
Fixes [e2e CI failures](https://app.circleci.com/pipelines/github/garden-io/garden/17469/workflows/9990e63e-69d9-4e54-9b56-0a894d65cc6e/jobs/302099).
=> chore(examples): use explicit version of Python deps

scripts/test-release.sh
* `garden serve` requires Cloud login
* `garden create module` is deprecated
Fixes #
=> chore: remove unnecessary steps from `test-release.sh` script

docs/other-plugins/exec.md, examples/local-service/README.md, examples/local-service/frontend/garden.yml
This PR also updates the [`local-service` example](https://github.com/garden-io/garden/tree/0.13/examples/local-service).
Fixes #
=> docs: 0.13 update for `exec` plugin guide

docs/advanced/custom-commands.md
Related to https://github.com/garden-io/garden/issues/4067
=> docs: update custom-commands guide for 0.13

core/src/cli/command-line.ts, core/src/commands/serve.ts, core/src/server/commands.ts, core/src/server/instance-manager.ts, core/src/server/server.ts, core/test/unit/src/cli/cli.ts, core/test/unit/src/server/server.ts
=> fix(server): errors in abortCommand and loadConfig requests in cloud projects

core/src/cli/command-line.ts, core/src/cli/helpers.ts, core/src/commands/dev.tsx
Added some more descriptive text to the header about what can be done in the dev command.
Also sorted the command listing rendered by the `help` command by "popularity", with the primary / most commonly used commands appearing closer to the top (and putting less frequently used commands in their own section).
This should make the command listing more readable, especially for new users who aren't familiar with the available commands.
=> improvement(dev): better help text & header

core/src/commands/serve.ts
=> Resolve params with cloud api

core/src/server/server.ts
=> 0.13 use correct session id for load config

core/src/commands/base.ts, core/src/commands/deploy.ts, core/src/commands/workflow.ts, core/src/graph/solver.ts, core/src/logger/log-entry.ts, core/src/logger/renderers.ts, core/src/logger/util.ts, core/src/plugins/exec/common.ts, core/src/plugins/exec/deploy.ts, core/src/plugins/exec/exec.ts, core/src/tasks/build.ts, core/src/tasks/run.ts, core/test/unit/src/commands/logs.ts, core/test/unit/src/logger/log-entry.ts
Here, we make various fixes to rendering & consistency (colors, timestamps, skipping symbols in the command footer separator in the dev command etc).
=> improvement(core): logging tweaks

core/src/commands/deploy.ts
This fixes a regression where port-forwards weren't being started by the deploy command.
=> fix(deploy): port-forwards weren't being started

core/src/commands/sync/sync-status.ts, core/src/plugin/handlers/Deploy/get-sync-status.ts, core/src/plugins/kubernetes/sync.ts
We now show a sync status for syncs that aren't currently live (e.g. where the target resource isn't deployed).
=> improvement(sync-status): show all syncs

core/src/cloud/buffered-event-stream.ts, core/src/events.ts, core/src/server/server.ts
=> 0.13 stream fewer events

.circleci/config.yml
=> 0.12 remove vm minikube 1.19

RELEASE_PROCESS.md, scripts/draft-release-notes.ts, scripts/release.ts
=> 0.13 changelog improvements (sort release tags by semver instead of date)

cli/src/build-pkg.ts
=> chore: ensure commit hash in edge versions

scripts/test-release.sh
=> chore: remove unnecessary `timeout` from `test-release.sh`

cli/src/build-pkg.ts
Cherry-pick #4361 to `0.12`.
Fixes #
=> 0.12 cherry-pick: chore: ensure commit hash in edge versions

core/src/cli/cli.ts, core/src/cli/command-line.ts, core/src/commands/base.ts, core/src/server/server.ts
=> fix(server): set correct parent session ID for ws commands

examples/run-actions/hello/package-lock.json, examples/run-actions/hello/package.json
Closes a bunch of dependabot alerts.
- https://github.com/garden-io/garden/pull/4354
- https://github.com/garden-io/garden/pull/4355
- https://github.com/garden-io/garden/pull/4356
=> chore(examples): run-actions hello: dependency updates

core/src/server/helpers.ts, core/src/server/server.ts
See commits. One small fix + added a more optimal path to get autocomplete suggestions.
=> Server improvements

examples/remote-sources/garden.yml, examples/remote-sources/worker/garden.yml
I merged the remote sources' prs so this can be updated now
=> chore: update remote sources example

core/test/data/test-projects/helm/api-image/requirements.txt, core/test/data/test-projects/kubernetes-module/api-image/requirements.txt, e2e/projects/vote-helm-modules/api-image/requirements.txt, e2e/projects/vote-modules/api/requirements.txt, examples/vote-helm/api-image/requirements.txt, examples/vote/api/requirements.txt
This PR addresses a few [dependabot PRs](https://github.com/garden-io/garden/pulls?q=is%3Aopen+is%3Apr+author%3Aapp%2Fdependabot+label%3Adependencies+label%3Apython) for Python exampels.
Fixes #
Let's wait for CI completion before merging this.
=> chore: update `redis` to `4.4.4` in Python examples and test apps

README.md
Updates the README to include a table of contents, and simplifies and standardizes to [README conventions](https://github.com/dguo/make-a-readme): short description, usage, features, community, contributing, and license. We also include a GIF or two to more directly communicate *the gist*.
The Garden logo has been swapped for one with a background to accommodate users of any GitHub theme (big thanks to Andrea).
Here's the old logo with GitHub's default dark theme:
New logo 🍹 :
**Notes for reviewer**:
Generally, I've tried to put light on a few juicy features that directly communicate value. We've often heard Garden is just _too_ fantastically powerful and it can be hard to pull out just where to start and what to do. In this update, I've tried to …
=> docs: update and align README

docs/tutorials/migrating-to-bonsai.md
Fixes a tiny typo in the migration doc
Fixes #
=> fix: tiny typo in migration doc

core/src/cloud/api.ts
This reverts commit a3d2306cb86acc1a2d27961e2a943e9e1be00170.
Fixes #
=> revert: fix: temporary hard-code 0.13.0 version in api client

core/src/cloud/api.ts
=> chore: fix compilation error

core/src/server/commands.ts
Tiny fix. Not required for release. 
Fixes #
=> fix(serve): fix help message of internal command

docs/using-garden/workflows.md
Command outputs are back, so we should also document this in the workflow doc accordingly.
Fixes #
=> docs: re-add command step outputs to workflow docs

RELEASE_PROCESS.md
Fixes #
To be cherry-picked to `0.12`.
=> chore: a few notes on merging release PRs

.github/workflows/reusable-create-homebrew-pr.yml, .github/workflows/test-create-homebrew-pr.yml
=> ci(0.12): use new homebrew formula path for 0.12 releases

.github/dependabot.yml
=> ci: configure dependabot for dockerfiles in support/

core/src/commands/sync/sync-status.ts, core/src/plugins/kubernetes/sync.ts, docs/reference/action-types/Deploy/container.md, docs/reference/action-types/Deploy/helm.md, docs/reference/action-types/Deploy/kubernetes.md, docs/reference/module-types/container.md, docs/reference/module-types/helm.md, docs/reference/module-types/jib-container.md, docs/reference/module-types/kubernetes.md, docs/reference/providers/kubernetes.md, docs/reference/providers/local-kubernetes.md, examples/code-synchronization/README.md, examples/gatsby-code-sync/src/pages/index.js, examples/run-actions/README.md, examples/templated-k8s-container/README.md, examples/vote-helm/README.md
a few came up once gitlab has been switched to Bonsai
=> docs: fix dead links

.github/dependabot.yml
Some tools receive almost daily updates, but we won't release a new version of Garden every day. Let's change Dockerfiles in `support/` to weekly.
Fixes #
=> ci(dependabot): update dockerfiles in support/ weekly

RELEASE_PROCESS.md
Cherry-pick #4433 to `0.12`.
Fixes #
=> 0.12 backport: chore: a few notes on merging release PRs

core/src/config/common.ts, core/src/config/module.ts, core/src/config/project.ts, core/src/constants.ts, core/src/garden.ts, core/test/unit/src/commands/get/get-config.ts, core/test/unit/src/vcs/vcs.ts
Addresses [this note](https://github.com/garden-io/garden/pull/4297/files#r1202536260) on the `apiVersion` default value.
It also brings some minor refactoring and cleanup.
Fixes #
=> Set default value for `apiVersion`

core/src/commands/logs.ts, docs/reference/commands.md
Fixes https://github.com/garden-io/garden/issues/4487
=> chore: improve line breaks in `garden logs --help` description

core/src/plugins/kubernetes/helm/helm-cli.ts
Cherry-picks #4491 to the `main` branch.
Fixes #
=> 0.12 back-port: Update helm version from 3.7.2 to 3.12.0

.editorconfig
See also: https://editorconfig.org/
Fixes #
=> chore: fix typo in .editorconfig file

plugins/jib/test/index.ts, plugins/jib/test/test-project/garden.yml, plugins/jib/test/util.ts, plugins/jib/util.ts
=> Some bugs fixes in `jib-container` and re-enable jib tests

core/src/actions/types.ts, core/src/plugins/kubernetes/sync.ts, core/test/integ/src/plugins/kubernetes/container/build/buildkit.ts, core/test/integ/src/plugins/kubernetes/namespace.ts, core/test/unit/src/config/template-contexts/base.ts, core/test/unit/src/logger/log-entry.ts
=> Fix some linter warns

core/src/commands/tools.ts, core/src/commands/util/fetch-tools.ts, core/src/commands/util/mutagen.ts, core/src/garden.ts, core/src/mutagen.ts, core/src/plugin/tools.ts, core/src/plugins/container/container.ts, core/src/plugins/hadolint/hadolint.ts, core/src/plugins/kubernetes/helm/helm-cli.ts, core/src/plugins/kubernetes/kubectl.ts, core/src/plugins/kubernetes/kubernetes-type/kustomize.ts, core/src/plugins/kubernetes/local-mode.ts, core/src/plugins/kubernetes/port-forward.ts, core/src/plugins/kubernetes/sync.ts, core/src/plugins/octant/octant.ts, core/src/util/ext-tools.ts, core/src/util/util.ts, core/test/unit/src/commands/tools.ts, core/test/unit/src/commands/util/fetch-tools.ts, core/test/unit/src/garden.ts, core/test/unit/src/tasks/resolve-provider.ts, examples/terraform-gke/garden.yml, plugins/conftest/index.ts, plugins/jib/gradle.ts, plugins/jib/index.ts, plugins/jib/maven.ts, plugins/jib/mavend.ts, plugins/jib/openjdk.ts, plugins/pulumi/cli.ts, plugins/terraform/cli.ts
please help yourself to the commits, they're rather chonky, sorry
=> Fetch tools fixes

.circleci/config.yml, support/docker-bake-test.sh, support/docker-bake.hcl
Based on top of https://github.com/garden-io/garden/tree/0.12-release-instructions for now. The base will be automatically changed to `0.12` after the merge.
Fixes #
=> chore: rename `edge` tag to `edge-acorn`

core/src/plugins/kubernetes/api.ts
=> chore: rearranged imports, inlined local var

.circleci/config.yml, RELEASE_PROCESS.md, scripts/release.ts
=> chore: use `edge-bonsai` tag instead of `edge`

core/.mocharc.integ.yml, core/src/config/provider.ts, core/src/plugins/kubernetes/api.ts
No quick wins in the investigations. I've just increased the timeout for the integration tests. It made things better.
Addresses #4504
=> WIP: experiments with micro-k8s tests

.circleci/config.yml, core/src/commands/run.ts, core/src/config/provider.ts, core/src/plugins/exec/common.ts, core/src/plugins/exec/config.ts, core/src/plugins/exec/exec.ts, core/src/plugins/kubernetes/util.ts, core/src/router/provider.ts, core/src/util/util.ts, core/test/data/test-projects/exec-task-outputs/garden.yml, core/test/integ/src/plugins/exec/exec.ts, core/test/unit/src/plugins/exec/exec.ts, docs/other-plugins/exec.md, docs/reference/action-types/Build/exec.md, docs/reference/action-types/Deploy/exec.md, docs/reference/action-types/Run/exec.md, docs/reference/action-types/Test/exec.md, docs/reference/providers/exec.md, examples/local-exec/backend/backend.garden.yml, examples/local-exec/project.garden.yml
closes https://github.com/garden-io/garden/issues/3998
closes https://github.com/garden-io/garden/issues/4437
juicy details in commits
=> Add outputs to the exec provider and exec actions

plugins/pulumi/helpers.ts
Cherry-picks #4533 to the `0.12` branch.
Fixes #
=> 0.12 fix puliumi stack tag rm error

core/src/plugins/kubernetes/kubernetes-type/handlers.ts, core/src/plugins/kubernetes/local-mode.ts
=> chore: remove stale todos

RELEASE_PROCESS.md, scripts/draft-release-notes.ts
As we have already discussed, let's exclude the manual testing step from the release process.
Fixes #
=> Simplify release instructions

RELEASE_PROCESS.md, scripts/draft-release-notes.ts
Cherry-picks #4541 to the `0.12` branch.
Fixes #
=> chore: simplify release instructions (#4541)

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/basics/quickstart.md, docs/guides/using-garden-in-ci.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, e2e/package.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.1

core/src/commands/base.ts, core/src/garden.ts, docs/reference/commands.md
Adds name key to suggested commands
=> chore: add name to suggested commands

core/src/plugins/kubernetes/api.ts
Cherry-picks #4555 to `main`.
Fixes #
=> fix(k8s): handle intermittent socket hang up errors (`main`)

cli/package.json, core/package.json, core/src/cli/helpers.ts, core/src/plugin/handlers/Build/get-status.ts, core/src/plugins/container/helpers.ts, core/src/plugins/kubernetes/api.ts, core/src/plugins/kubernetes/status/status.ts, core/src/template-string/template-string.ts, core/src/util/util.ts, core/test/helpers.ts, e2e/package.json, package.json, sdk/package.json, yarn.lock
=> chore: update TS to 5.1.3

core/src/commands/self-update.ts
=> fix(self-update): fix list of the latest available versions

core/src/commands/self-update.ts
Cherry-pick #4568 to `0.12`.
Fixes #
=> 0.12 back-port: fix(self-update): fix list of the latest available versions

core/src/commands/self-update.ts
Clearer logging about the installation directory in the `self-update` command.
This mitigates #4515
I preferred to avoid using any platform-specific code here to infer whether the Garden has been installed with the homebrew on a user's machine.
=> chore: clearer logging in the `self-update` command

core/src/commands/self-update.ts
=> 0.12 back-port: chore: clearer logging in the self-update command

README.md, docs/basics/quickstart.md
=> (docs): Add interactive environments to Garden main repository

docs/tutorials/migrating-to-bonsai.md
Fixes #
Tiny improvement - mention the ways to update the CLI in our migration guide.
Feel free to add suggestions for better wording, if any!
=> chore: mention garden self-update in migrating guide

core/src/docs/generate.ts, core/src/plugins/openshift/config.ts, core/src/plugins/openshift/local/config.ts, core/src/plugins/openshift/local/local.ts, core/src/plugins/openshift/openshift.ts, core/src/plugins/plugins.ts, core/test/data/openshift/demo-project/garden.yml, core/test/integ/src/plugins/openshift/provider.ts
Fixes https://github.com/garden-io/garden/issues/4608
Taking inspiration from the `kubernetes` and `local-kubernetes` plugins.
(Might refactor to new style and zod _after_ https://github.com/garden-io/garden/pull/4535 has been merged, in a separate PR)
=> feat(openshift): initial provider scaffolding

core/package.json, package.json, yarn.lock
Resolves https://github.com/garden-io/garden/security/dependabot/87
Fixes #
#4595 didn't resolve it earlier.
=> chore: update dependencies

docs/reference/providers/pulumi.md, plugins/pulumi/cli.ts
Backported from #4585 
See #4585 
Fixes #
=> fix(pulumi): remove PULUMI_EXPERIMENTAL flag due to side effects

core/src/plugins/kubernetes/helm/handlers.ts, core/src/plugins/kubernetes/kubernetes-type/common.ts, core/src/plugins/kubernetes/kubernetes-type/handlers.ts
see commits for details
probably closes [#4580](https://github.com/garden-io/garden/issues/4580)
=> fix helm and kubernetes module conversion issues

docs/basics/quickstart.md
=> Fix pixel quantity

core/src/server/commands.ts
=> fix(analytics): do not track hidden commands

core/src/config/template-contexts/actions.ts, core/src/graph/actions.ts, core/src/router/base.ts, docs/reference/template-strings/action-all-fields.md, plugins/pulumi/commands.ts
Fixes #4616
~Still WIP, I need to add some unit tests~
We do not test each individual template string path. Context scanning and template string resolution are covered in https://github.com/garden-io/garden/blob/main/core/test/unit/src/template-string.ts.
=> feat(template): allow `this.name` and `this.mode` in action config

core/src/config/template-contexts/actions.ts, core/src/router/base.ts, plugins/terraform/cli.ts
A cleanup for #4646. Also does some linting.
Fixes #
=> chore: remove some dead code

core/src/actions/base.ts, core/src/actions/build.ts, core/src/config/template-contexts/actions.ts, core/src/config/template-contexts/module.ts, core/src/graph/actions.ts, core/src/graph/common.ts, core/src/router/base.ts, core/src/tasks/resolve-action.ts, core/test/helpers.ts, core/test/unit/src/config-graph.ts, core/test/unit/src/graph/actions.ts, plugins/pulumi/commands.ts
See individual commits. There is some refactored code. The feature itself is shipped as a separate commit.
Fixes #4619
=> feat(template): allow variable references in include/exclude config

examples/jib-container/helloworld/build.gradle
Fixes CVE-2023-2976 in jib-container example
Fixes #
=> chore(example): update guava version in gradle config

docs/reference/module-types/jib-container.md, plugins/jib/maven.ts, plugins/jib/mavend.ts
Cherry-picks #4670 to `0.12`.
Fixes #
=> 0.12 back-port: improvement(jib): update `mvn` and `mvnd` versions 

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/basics/quickstart.md, docs/guides/using-garden-in-ci.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, e2e/package.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.3

core/src/server/server.ts
Just slightly more informative logs for an "internal" dashboard command. 
Fixes #
=> improvement(server): better logging for loading config

core/src/graph/nodes.ts
=> improvement(logs): log resolve and statusOnly tasks at debug level

core/src/cli/command-line.ts
Basically commands could in certain instances get stuck, after some failure modes etc.
=> fix(dev): running command status message could become inconsistent

core/src/actions/helpers.ts, core/src/commands/get/get-status.ts, core/src/events/util.ts, core/src/server/commands.ts, core/src/server/instance-manager.ts
This is an internal/experimental cmd that'll only be used by the web dashboard for now.
Fixes #
=> feat(server): add internal/experimental cmd for getting action statuses

core/src/commands/base.ts, core/src/commands/deploy.ts, core/src/commands/helpers.ts, core/src/commands/serve.ts, core/src/commands/up.ts
This fixes some problems/limitations with the changes introduced in #4675.
Tests for the total flow will follow in a separate PR.
=> fix(cloud): fix session registration flow for dev

core/src/analytics/analytics.ts, core/src/commands/base.ts, core/src/exceptions.ts, core/src/garden.ts, core/test/unit/src/exceptions.ts
Updates error handling in getStackTraceMetadata and introduces support for wrappedErrors.
Fixes #
=> chore(analytics): error stack trace metadata error handling and wrapped errors in analytics

core/src/server/commands.ts
=> chore: fix import typo

core/src/constants.ts, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, plugins/jib/build-tool-base.ts, plugins/jib/index.ts, plugins/jib/maven.ts, plugins/jib/mavend.ts, plugins/jib/util.ts
=> imrpovement(jib): allow concurrent maven builds

core/src/server/server.ts, core/test/unit/src/server/server.ts
=> Ws command info

examples/jib-container/spring-boot/spring-boot.garden.yml
A follow-up cleanup PR for #4711
Fixes #
=> 0.12: fix jib example config

core/src/plugins/kubernetes/config.ts, docs/reference/providers/kubernetes.md, docs/reference/providers/local-kubernetes.md
This PR back-ports #4686 to `0.12`.
Fixes #
=> 0.12 back-port: update kaniko version

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/basics/quickstart.md, docs/guides/using-garden-in-ci.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, e2e/package.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.4

scripts/draft-release-notes.ts
* pass correct args to `git-chglog` to avoid unwanted chnages from the previous release
* some minor text and template corrections
Fixes #
=> chore: fix release notes draft generation

scripts/draft-release-notes.ts
Cherry-picks #4718 to `0.12`.
Fixes #
=> 0.12 back-port: fix release notes

core/src/actions/helpers.ts, core/src/commands/exec.ts, core/src/commands/self-update.ts, core/src/graph/actions.ts, core/src/plugins/kubernetes/container/deployment.ts, core/src/plugins/kubernetes/run.ts, core/test/unit/src/commands/get/get-actions-subcommands.ts
Use `satisfies never` feature from TypeScript 4.9+. See https://dev.to/cefn/typescript-satisfies-never-exhaustiveness-checking-in-typescript-49-58fh
Fixes #
=> chore: modernize exhaustive type checks

core/src/analytics/analytics.ts
In case of any runtime error in telemetry/analytics, the actual underlying error is suppressed but rather runtime error is thrown. With this, we wrap it in try/catch to catch such errors, and gracefully return in catch so the control flow continues.
=> fix(telemetry): do not throw in case of any runtime error

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/basics/quickstart.md, docs/guides/using-garden-in-ci.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, e2e/package.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.5

core/src/plugins/kubernetes/api.ts
Wrap `kubectl` call into existing retry-machinery. Add a way to avoid `shouldRetry` checker call,
because sometimes the error messages are not well-known in advance.
Use retry machinery when retrieve Kubernetes configs using `kubectl`.
Attempts to address #4591
=> improvement(k8s): retry on config retrieval failure

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/basics/quickstart.md, docs/guides/using-garden-in-ci.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, e2e/package.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.6

e2e/projects/remote-sources-modules/garden.yml, examples/remote-sources/garden.yml
Use main branch that contains the action-based configs and the updated Node vesrion.
Fixes #
=> chore(test): fix remote source repo link

RELEASE_PROCESS.md
We want consistent behaviour of `https://github.com/garden-io/garden/releases/latest` URL. Let it always point to the latest Bonsai version.
Fixes #
=> chore: more explicit instructions on the release process

core/src/plugins/exec/build.ts, core/src/plugins/exec/common.ts, core/src/plugins/exec/deploy.ts, core/src/plugins/exec/run.ts, core/src/plugins/exec/test.ts, core/src/tasks/base.ts
please see commits
related to https://github.com/garden-io/garden/issues/4687
=> error logging fixes

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/basics/quickstart.md, docs/guides/using-garden-in-ci.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, e2e/package.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.7

core/src/commands/deploy.ts, core/test/unit/src/commands/deploy.ts, docs/reference/commands.md
=> feat: add `with-dependants` deploy command flag

docs/basics/quickstart.md
Update Docker term in the docs
None
=> docs: update Docker settings term

core/src/template-string/functions.ts, core/test/unit/src/template-string.ts
Ports #4809 to the `main` branch.
Fixes #3398
=> fix(template): allow `null` as a valid argument in helper functions and fix `isEmpty()` helpers

docs/README.md, docs/garden-seeds/README.md, docs/garden-seeds/about.md, docs/garden-seeds/languages/README.md, docs/garden-seeds/languages/go-seed.md, docs/garden-seeds/languages/go.md, docs/misc/README.md
Started by adding the homepage; please, if the placement doesn't make sense, don't hesitate to reach out.
The first recipe is in progress, and it will be added in the same PR.
=> Add Garden Seeds main page and go-seed

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/basics/quickstart.md, docs/guides/using-garden-in-ci.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, e2e/package.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.8

e2e/projects/vote-helm-modules/vote-image/Dockerfile, e2e/projects/vote-helm-modules/vote-image/package.json, e2e/projects/vote-modules/vote/Dockerfile, e2e/projects/vote-modules/vote/package.json, examples/vote-helm/vote-image/Dockerfile, examples/vote-helm/vote-image/package.json
=> test: update deps + Node.js runtime for vote e2e tests

images/buildkit/Dockerfile, images/circleci-runner/Dockerfile, images/k8s-sync/Dockerfile, images/k8s-util/Dockerfile, images/skopeo/Dockerfile, support/alpine.Dockerfile, support/buster.Dockerfile
Verify downloads using sha256sum for extra security.
Fixes #3993
I verified that all the images under `images/` build; However, it is not necessary to publish another release of them because the images themselves have not changed (Only verification has been added for future changes)
=> improvement: verify downloads using sha256 in Dockerfiles

core/src/util/ext-tools.ts, plugins/pulumi/cli.ts, plugins/terraform/cli.ts
was caused by me in https://github.com/garden-io/garden/pull/4496
closes #4832
=> fix: enoent when version set to null on tf and pulumi

scripts/release.ts
Fix type error introduced in #4827.
Fixes #
=> chore: fix type error in the release script

core/package.json, core/src/config/base.ts, core/src/docs/table-of-contents.ts, core/src/server/server.ts, core/test/helpers/test-plugin.ts, yarn.lock
Update all the things ✨ 
Note: most of the changes are within the `yarn.lock` - plenty of libraries are getting updated!
=> chore: run `yarn upgrade` to update dependencies

core/package.json, yarn.lock
Fixes https://github.com/garden-io/garden/security/dependabot/868
Updated @google-cloud/kms at the root package.json in previous PR https://github.com/garden-io/garden/pull/4862
Forgot to update it in `core` as well.
=> chore: update `google-cloud/kms` in `core` package as well

examples/vote/vote/Dockerfile
Attempt to fix vote e2e tests
Fixes #
=> chore: update node in vote e2e test

core/src/config/config-template.ts, core/test/unit/src/config/render-template.ts, docs/reference/config-template-config.md, docs/using-garden/config-templates.md, plugins/pulumi/index.ts, plugins/terraform/index.ts
fixes: https://github.com/garden-io/garden/issues/4833
=> fix: properly handle build deps for pulumi and tf modules

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/basics/quickstart.md, docs/guides/using-garden-in-ci.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, e2e/package.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.9

docs/k8s-plugins/action-types/kubernetes.md
A follow-up PR for the feature (see https://github.com/garden-io/garden/commit/c9efb473d4f352ac13f12a7f8ada2a2b28445cb3) implemented in #4516.
Addresses the [comment](https://github.com/garden-io/garden/issues/3465#issuecomment-1644001593) from #3465
Just a documentation update. Feel free to suggest better style/wording.
=> docs(k8s): document glob patterns usage

.github/PULL_REQUEST_TEMPLATE.md
=> chore: update list of active contributors

core/src/resolve-module.ts, core/test/data/test-projects/template-configs/Dockerfile, core/test/data/test-projects/template-configs/garden.yml, core/test/data/test-projects/template-configs/schema.json, core/test/unit/src/resolve-module.ts
=> fix(template): inputs processing in module config resolution

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/basics/quickstart.md, docs/guides/using-garden-in-ci.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, e2e/package.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.10

core/src/plugins/kubernetes/volumes/persistentvolumeclaim.ts
Add delete handler for pvc
Fixes #1740
=> fix: delete pvc on namespace cleanup

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/basics/quickstart.md, docs/guides/using-garden-in-ci.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, e2e/package.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.11

core/src/plugins/kubernetes/local-mode.ts, examples/local-mode-helm/backend/garden.yml, examples/local-mode-helm/garden.yml, examples/local-mode-k8s/backend/garden.yml, examples/local-mode-k8s/garden.yml, examples/local-mode/backend-1/garden.yml, examples/local-mode/backend-2/garden.yml, examples/local-mode/garden.yml
=> fix(local-mode): fix port forward when having many local ssh keys

core/src/plugins/otel-collector/otel-collector.ts
=> fix: correct otel collector binary definition for arm64 linux

.circleci/config.yml
=> fix: properly escape the newline for the tag argument

core/src/util/module-overlap.ts
A follow-up minor refactoring for #4961.
Fixes #
=> refactor: rename interfaces

core/src/logger/logger.ts, core/src/server/server.ts
Small improvement to improve working with Desktop.
=> improvement(server): output more debug info

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/basics/quickstart.md, docs/guides/using-garden-in-ci.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, e2e/package.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.13

docs/README.md, docs/pulumi-plugin/action-configuration.md, docs/pulumi-plugin/configure-provider.md, docs/terraform-plugin/action-configuration.md, docs/terraform-plugin/configure-provider.md
=> docs: minor fixes to page titles

examples/k8s-deploy-config-templates/web/Dockerfile, examples/k8s-deploy-config-templates/web/package-lock.json, examples/k8s-deploy-config-templates/web/package.json
Fixes #
I tested the example locally, it worked well.
=> chore(deps): dependency updates in `k8s-deploy-config-templates` example

examples/k8s-deploy-shared-manifests/web/Dockerfile, examples/k8s-deploy-shared-manifests/web/garden.yml, examples/k8s-deploy-shared-manifests/web/package-lock.json, examples/k8s-deploy-shared-manifests/web/package.json
Fixes #
I tested the example locally, it worked well.
=> chore(examples): fix `k8s-deploy-shared-manifests` example

docs/README.md, docs/advanced/README.md, docs/basics/core-concepts.md, docs/basics/garden-vs-other-tools.md, docs/basics/quickstart.md, docs/garden-seeds/README.md, docs/guides/README.md, docs/k8s-plugins/README.md, docs/other-plugins/README.md, docs/pulumi-plugin/README.md, docs/reference/README.md, docs/terraform-plugin/README.md, docs/tutorials/README.md, docs/using-garden/README.md
=> docs: re-order some docs pages

docs/README.md, docs/basics/adopting-garden.md, docs/basics/core-concepts.md, docs/basics/garden-vs-other-tools.md, docs/welcome.md
=> docs: move and update 'Adopting Garden' guide

docs/basics/ephemeral-clusters.md, examples/ephemeral-cluster-demo/README.md
=> chore: update the links for ephemeral-cluster example demo and docs

core/src/config/base.ts, core/src/docs/generate.ts, core/src/garden.ts, docs/README.md, docs/guides/installation.md, docs/guides/migrating-to-bonsai.md, docs/reference/module-types/README.md, docs/reference/module-types/configmap.md, docs/reference/module-types/conftest.md, docs/reference/module-types/container.md, docs/reference/module-types/exec.md, docs/reference/module-types/hadolint.md, docs/reference/module-types/helm.md, docs/reference/module-types/jib-container.md, docs/reference/module-types/kubernetes.md, docs/reference/module-types/persistentvolumeclaim.md, docs/reference/module-types/pulumi.md, docs/reference/module-types/templated.md, docs/reference/module-types/terraform.md, docs/using-garden/configuration-overview.md, docs/using-garden/modules.md, static/docs/templates/module-type.hbs
=> docs: move Bonsai migration guide to 'Guides' section

core/src/garden.ts, core/src/util/module-overlap.ts
=> chore: error details cleanup

docs/advanced/using-remote-sources.md, docs/basics/adopting-garden.md, docs/k8s-plugins/action-types/container.md, docs/k8s-plugins/action-types/helm.md, docs/k8s-plugins/action-types/kubernetes-exec.md, docs/k8s-plugins/action-types/kubernetes.md
=> docs: fix some typos

docs/basics/ephemeral-clusters.md
Adds a step-by-step guide for the garden-kubernetes provider.
Fixes #
=> docs: add step-by-step guide for garden-kubernetes

core/src/plugins/kubernetes/ephemeral/config.ts, core/src/plugins/kubernetes/ephemeral/ephemeral.ts, core/src/plugins/kubernetes/init.ts, docs/README.md, docs/guides/code-synchronization.md, docs/guides/ephemeral-clusters.md, docs/guides/migrating-from-docker-compose.md, docs/guides/namespaces.md, docs/guides/using-garden-in-ci.md, docs/reference/providers/ephemeral-kubernetes.md, examples/ephemeral-cluster-demo/README.md
=> docs: move ephemeral kubernetes docs from basics to guides section

.circleci/config.yml
=> ci: disable plugin tests in external PRs

docs/overview/use-cases.md
Just some tiny fixes. The plan is still to split this up. 
Fixes #
=> docs: fix a few headings on the use cases page

docs/k8s-plugins/about.md, docs/welcome.md
Updates the docs welcome page.
This updated welcome page was built via the Gitbook editor and contains cards that require HTML elements.
Due to how Gitbook is currently set up, we can't make changes to the main docs page there because it would essentially merge the changes back to our main branch which is protected.
So instead these changes where made in a test project and copied over.
That's obviously an awful workflow and we need to figure out a proper solution here that allows us to edit on Gitbook without breaking branch protection rules.
I just took the hacky route for now so that we can get these changes in.
Fixes #
=> docs: update welcome page

CONTRIBUTING.md, core/src/docs/table-of-contents.ts, core/src/plugins/kubernetes/ephemeral/ephemeral.ts, core/src/plugins/kubernetes/local/local.ts, core/test/unit/src/docs/table-of-contents.ts, docs/README.md, docs/garden-seeds/languages/go.md, docs/getting-started/quickstart.md, docs/k8s-plugins/action-types/README.md, docs/k8s-plugins/action-types/kubernetes.md, docs/overview/adopting-garden.md, docs/overview/how-garden-works.md, docs/reference/providers/ephemeral-kubernetes.md, docs/reference/providers/local-kubernetes.md, docs/using-garden/using-the-cli.md, docs/welcome.md, examples/demo-project/README.md
Various copy fixes + fix broken links after docs restructure.
Fixes #
=> docs: various small fixes

core/src/plugins/kubernetes/constants.ts, images/buildkit/garden.yml
A follow-up PR for #5105.
Fixes #
=> deps: publish updated buildkit and switch default to 0.12.2

.gitbook.yaml
We forgot to add this redirect after moving the Bonsai guide from the "Tutorials" section to the "Guides" section. 
Fixes #
=> docs: add redirect for Bonsai migration guide

CONTRIBUTING.md, RELEASE_PROCESS.md, docs/other-plugins/exec.md, docs/using-garden/variables-and-templating.md, e2e/README.md, plugins/pulumi/.gitignore
Just updating the CONTRIBUTING.md 
Fixes #
=> chore: remove remaining yarn references

core/src/plugins/kubernetes/api.ts, core/src/plugins/kubernetes/helm/status.ts, core/src/plugins/kubernetes/kubectl.ts, core/src/plugins/kubernetes/kubernetes-type/handlers.ts, core/src/plugins/kubernetes/status/status.ts, core/src/util/hashing.ts, core/src/util/string.ts, core/src/vcs/git.ts, core/test/data/test-projects/kubernetes-type/module-simple-isolated/garden.yml, core/test/integ/src/plugins/kubernetes/kubernetes-type/handlers.ts
A follow-up fix for #4846 to address @stefreak 's [comment on the AEC](https://github.com/garden-io/garden/pull/4846#issuecomment-1695938718).
Fixes #
The commit-by-commit review might be easier :)
=> fix(k8s): handle AEC-paused resources properly

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/ephemeral-clusters.md, docs/guides/using-garden-in-ci.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, e2e/package.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.16

docs/getting-started/quickstart.md, docs/welcome.md
Add a call-to-action for the new Garden Web Dashboard to the docs Welcome page. 
Fixes #
=> docs: add dashboard cta to welcome page

core/src/plugins/kubernetes/ephemeral/config.ts
=> chore: re-use constant instead of hardcoded domain string

README.md, docs/getting-started/quickstart.md, docs/welcome.md
This increases the resolution of the web dashboard , crops in to remove the unsightly black frame, and adds the dashboard to the README. It also moves the dashboard outside the hint.
=> docs: update web dashboard

docs/README.md, docs/getting-started/next-steps.md, docs/overview/adopting-garden.md, docs/overview/use-cases.md
This basically splits up the "Overview/Adopting Garden" guide into "Overview/Adopting Garden" and "Getting Started/Next Steps".
Fixes #
=> docs: add a "Next Steps" guide to the "Getting Started" section

core/test/data/test-projects/helm/api-image/requirements.txt, core/test/data/test-projects/kubernetes-module/api-image/requirements.txt, examples/argocd/api/requirements.txt, examples/remote-sources/garden.yml, examples/vote-helm/api-image/requirements.txt, examples/vote/api/requirements.txt
Fixes `e2e-vote` and `e2e-remote-sources` CI steps.
=> test: fix Python dependencies and remote sources configs

core/package.json, core/src/plugins/kubernetes/task-results.ts, core/src/plugins/kubernetes/test-results.ts, core/src/util/testing.ts, core/src/util/util.ts, yarn.lock
Fixes #
0.12 backport of #5179
Expected/acceptable test failures:
* `e2e-tasks`
* `e2e-vote-helm`
* `test-plugins`
The rest tests must pass (with possible CI reruns).
=> chore(deps): remove cryo

docs/getting-started/quickstart.md
=> docs: change order of login command in quick-start guide

RELEASE_PROCESS.md
=> docs: correct homebrew command for garden update

.github/workflows/reusable-create-homebrew-pr.yml
See:
* https://github.com/cuchi/jinja2-action/issues/17
* https://github.com/cuchi/jinja2-action/pull/16
Fixes #5197
=> ci: use `jinja2-action` pinned to Python 3.11

docs/getting-started/next-steps.md
=> docs: fix typos

core/src/actions/build.ts, docs/reference/action-types/Build/container.md, docs/reference/action-types/Build/exec.md, docs/reference/action-types/Build/jib-container.md
=> fix(build): make `copyFrom.targetPath` default to `copyFrom.sourcePath`

support/alpine.Dockerfile, support/debian.Dockerfile
=> chore: bump azurecli in docker images

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-ci.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.18

support/docker-bake-test.sh
=> 0.12 ci fix docker bake test

support/docker-bake-test.sh
- test(dockerhub): ensure we never pull images in the test script
- test(dockerhub): make sure that test script can be executed from anywhere
Fixes #
=> dockerhub test improvements

examples/ephemeral-cluster-demo/README.md
A follow-up fix for #5195.
Fixes #
=> docs: fix the dead link to the k8s ephemeral cluster guide

core/src/cli/command-line.ts
...previously we whiteBright which doesn't render will in the dashboard
Fixes #
=> fix(core): print success message with cyan color

docs/getting-started/next-steps.md
=> docs: add apiVersion to config snipper

core/package.json
replace yarn with npm in script.
Fixes #
=> chore(core): fix dev script

docs/reference/action-types/Deploy/pulumi.md, plugins/pulumi/src/index.ts
=> docs(pulumi): fix action reference format

.circleci/config.yml
By implementing a setup workflow with path filtering, we accidentally excluded tags see https://discuss.circleci.com/t/dynamic-continue-config-doesnt-work-with-a-tag-filter/44427/3
Fixes #
=> ci: run workflows on tags

examples/k8s-deploy-shared-manifests/web/garden.yml, examples/k8s-deploy-shared-manifests/web/package.json, examples/k8s-deploy-shared-manifests/web/tests/integ/test.js
Fix the tests in the example. While working on something,  @thsig and I realized that the tests were broken in this example.
Fixes #
=> chore: fix tests in example k8s-deploy-shared-manifests

CHANGELOG.md, README.md, RELEASE_PROCESS.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-ci.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.19

.circleci/continue-config.yml
We referenced using the wrong name and that caused the CI to fail on
main.
Fixes #
=> chore(circleci): fix edge release pipeline

.circleci/continue-config.yml
With the goal to reduce the time we have to wait for these jobs.
The dockerhub job only runs after merged to main, or when the
Dockerfiles actually changed.
Fixes #
=> chore(circleci): increase executor size for dockerhub and windows

.circleci/continue-config.yml, cli/src/build-pkg.ts
=> chore: npm run dist nodejs archive caching

.circleci/continue-config.yml, package.json, scripts/check-docs.sh
=> chore: disable cache restore when package-lock.json changed

core/src/commands/base.ts, core/src/graph/nodes.ts, core/test/unit/src/graph/solver.ts
When a dependency fails, we now log a line for each aborted node.
Also fixed the counting logic used in the command error summary. Before this fix, we used to include aborted nodes in the failed count.
Note that we're no longer copying the error from the failed dependency to all the failed dependants in the command result. This might be seen as a breaking change.
If we'd rather keep the machine-readable command output the same, I can modify the logic to set the error for the aborted dependant keys in the command result.
=> improvement(core): log aborted nodes on dep error

.github/dependabot.yml
Now that we have ESM support, we can enable Dependabot to auto-update packages.
This tells Dependabot to open PRs also for updates that are not resolving Dependabot security alerts.
=> chore(dependabot): enable npm package ecosystem

core/src/plugins/kubernetes/retry.ts
Add a retry regex in an attempt to fix test flakes that were causing >90% of our merge queue flakes recently.
The full error message looked like this:
```
1) KubeApi
helpers
execInPod
should exec a command in a Pod and return the output:
Error: Error while performing Kubernetes API operation createNamespacedPod: ApiException
Response status code: 403
Kubernetes Message: pods "api-test-n122thrl" is forbidden: error looking up service account container-default/default: serviceaccount "default" not found
at toKubernetesError (file:///home/circleci/project/core/src/plugins/kubernetes/retry.ts:142:10)
at file:///home/circleci/project/core/src/plugins/kubernetes/api.ts:823:27
at processTicksAndRejections (node:internal/process/task_queues:95:5)
at retry …
```
=> chore: add retry for flaky api call

.github/dependabot.yml
=> chore(0.12): enable dependabot updates for `support/` for security-updates

scripts/release.ts
=> chore: fix `package.json` path in the release script

scripts/release.ts
=> chore: fix changelog generation

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-ci.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.20

cli/bin/garden-debug.js
=> chore: fix --inspect flag

core/src/util/serialization.ts, core/src/util/util.ts, core/test/unit/src/resolve-module.ts
This is the continuation of the util-refactoring PR series started in https://github.com/garden-io/garden/pull/5431.
Fixes #
=> chore: move yaml helper to serialization module

docs/misc/faq.md
=> docs(faq): add an entry on disabling colors

cli/src/build-pkg.ts
#5440 accidentally changed the release asset filenames in our edge release: https://github.com/garden-io/garden/releases/tag/edge-bonsai
They used to look like this:
`garden-edge-bonsai-alpine-amd64.tar.gz` and now look like this: `garden-0.13.20-edge-bonsai-2779705b6-alpine-amd64.tar.gz`
This commit reverts to the old filenames so self-update downloads the correct artifacts.
Makes sure self-update downloads the latest edge release.
Screenshot of the issue in action:
=> chore: fix edge build release artifact filenames

docs/welcome.md
The gif felt too noisy and drew the attention away from the actual content.
Fixes #
=> docs: remove gif from welcome page

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-ci.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.21

core/src/constants.ts, core/src/vcs/git.ts, core/src/vcs/vcs.ts, core/test/unit/src/vcs/vcs.ts
=> refactor(git): use named constant for default repo scan mode

core/src/actions/base.ts, core/test/unit/src/actions/base.ts
=> fix(core): avoid unnecessary config version changes

.github/ISSUE_TEMPLATE/0-13-issue-template.md, .github/ISSUE_TEMPLATE/BUG_REPORT.md
=> chore: automatically apply `bug` label to GH bugs

core/src/plugins/kubernetes/config.ts, docs/getting-started/next-steps.md, docs/reference/providers/kubernetes.md, docs/reference/providers/local-kubernetes.md, docs/welcome.md, examples/remote-k8s/README.md
=> docs: add link to video + update welcome page

core/src/mutagen.ts, core/src/plugins/kubernetes/commands/sync.ts
Fixes #
A tiny predecessor for #5551.
=> refactor(mutagen): always use `getMutagenEnv` helper to define Mutagen env

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.22

docs/k8s-plugins/local-k8s/install.md
Adds a section on how to update or remove the garden installed nginx ingress controller.
Fixes #
=> docs: add section on updating or removing garden ingress controller

plugins/terraform/cli.ts
Cherry-pick #5564 to `0.12`.
Fixes #
=> fix(terraform): fix sha256 hashes for some old terraform binaries 

plugins/terraform/src/cli.ts
Fixes #
The issue was found by the test script implemented in #5556.
=> fix(terraform): fix `sha256` hashes for some old terraform binaries

plugins/jib/src/mavend.ts
Fixes #
The issue was found by the test script implemented in #5556.
=> fix(mavend): fix Mavend `sha256` hash for `windows-amd64` binary

core/src/commands/publish.ts, core/src/plugin/handlers/Build/publish.ts, core/src/plugins/container/helpers.ts, core/src/plugins/container/publish.ts, core/src/plugins/kubernetes/container/publish.ts, core/src/tasks/publish.ts, core/test/integ/src/plugins/container/container.ts, core/test/integ/src/plugins/kubernetes/container/build/build.ts, core/test/unit/src/commands/publish.ts
Fixes #5094
Partially addresses #5581
=> fix(publish): respect the `spec.publishId` in build action config

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.23

examples/k8s-deploy-patch-resources/README.md
=> fix(examples): set correct header for patch resources example

.github/dependabot.yml
=> ci: disable dependabot for `0.12` branch

.circleci/continue-config.yml
=> ci: update kubernetes versions in tests

core/src/garden.ts, examples/k8s-deploy-config-templates/README.md, examples/k8s-deploy-config-templates/project.garden.yml, examples/k8s-deploy-config-templates/templates/garden.yml, examples/k8s-deploy-config-templates/web/.eslintrc.js, examples/k8s-deploy-config-templates/web/babel.config.js, examples/k8s-deploy-config-templates/web/package.json, examples/k8s-deploy-config-templates/web/vue.config.js, examples/k8s-deploy-patch-resources/project.garden.yml, examples/k8s-deploy-patch-resources/web/.eslintrc.js, examples/k8s-deploy-patch-resources/web/babel.config.js, examples/k8s-deploy-patch-resources/web/package.json, examples/k8s-deploy-patch-resources/web/vue.config.js, examples/k8s-deploy-shared-manifests/project.garden.yml, examples/k8s-deploy-shared-manifests/web/.eslintrc.js, examples/k8s-deploy-shared-manifests/web/babel.config.js, examples/k8s-deploy-shared-manifests/web/package.json, examples/k8s-deploy-shared-manifests/web/vue.config.js
In some example projects, the Vue web server wouldn't start correctly due to how `eslint` was set up and the version of some of its dependencies.
This commit fixes that.
Fixes #
This does not fix the issue with the page not being found when run on local Kubernetes. We'll need to address that specifically but I suspect it has to do with hostfile issue we've had in the past. 
I tested all examples by just creating a port forward and they worked as expected.
=> fix(examples): ensure Vue web servers start correctly

examples/argocd/web/package.json, examples/k8s-deploy-config-templates/web/package.json, examples/k8s-deploy-patch-resources/web/package.json, examples/k8s-deploy-shared-manifests/web/package.json
Garden does not export these variables
Fixes #
=> chore(examples): cleanup serve command in javascript examples

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.24

docs/getting-started/installation.md, docs/misc/faq.md
=> docs: add instructions on how to update Garden

core/src/plugins/kubernetes/kubectl.ts
=> improvement: update `kubectl` version to `1.29.1`

core/src/template-string/template-string.ts, core/test/unit/src/garden.ts, core/test/unit/src/template-string.ts
When available, include the path to the template string in the YAML doc in question.
Also stop truncating the template expression in the message.
=> improvement(core): include path in template errors

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.25

core/src/mutagen.ts, core/src/plugins/kubernetes/commands/pull-image.ts, core/src/plugins/kubernetes/constants.ts, core/src/plugins/kubernetes/container/build/common.ts, core/src/plugins/kubernetes/container/build/kaniko.ts, core/src/plugins/kubernetes/sync.ts, core/test/integ/src/plugins/kubernetes/container/deployment.ts, core/test/unit/src/plugins/kubernetes/container/build/buildkit.ts, core/test/unit/src/plugins/kubernetes/container/build/common.ts, core/test/unit/src/plugins/kubernetes/container/build/kaniko.ts, images/k8s-sync/Dockerfile, images/k8s-sync/README.md, images/k8s-sync/garden.yml, images/k8s-util/garden.yml
This PR updates the Mutagen tool to the latest available version. 
This should fix #5053
=> improvement(sync): update Mutagen to 0.17.5

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.26

core/src/commands/self-update.ts, core/src/plugin/tools.ts, core/src/util/arch-platform.ts, core/src/util/ext-tools.ts, docs/reference/commands.md, garden-sea/src/artifacts.rs, garden-sea/src/node.rs
To detect musl target, we use an environment variable in Garden SEA rust wrapper, because Nodejs does not expose musl target env via process.
=> fix(self-update): download alpine release artifacts on alpine

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.27

core/src/cli/helpers.ts, core/src/commands/create/create-project.ts, core/src/commands/sync/sync-status.ts, core/src/config/base.ts, core/src/config/common.ts, core/src/docs/common.ts, core/src/garden.ts, core/src/mutagen.ts, core/src/plugins/kubernetes/constants.ts, core/src/plugins/kubernetes/helm/action.ts, core/src/plugins/kubernetes/kubernetes.ts, core/src/plugins/kubernetes/local-mode.ts, core/src/plugins/kubernetes/volumes/configmap.ts, core/src/util/util.ts, core/src/util/validateInstall.ts, core/src/vcs/vcs.ts, core/test/unit/src/docs/util.ts
This PR addresses the [comment](https://github.com/garden-io/garden/pull/5754#discussion_r1497292095) from #5754.
=> refactor: convenience function to create styled doc links

RELEASE_PROCESS.md, scripts/draft-release-notes.ts
=> chore: update release instructions

core/src/plugins/container/container.ts
Update docker shipped with garden tools, to patch several high security issues in buildkit. See https://docs.docker.com/engine/release-notes/25.0/#security
Fixes #
=> chore: update docker shipped with garden tools

CHANGELOG.md, README.md, RELEASE_PROCESS.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.28

docs/k8s-plugins/actions/deploy/container.md
Docs fix
This is just a doc fix
=> Fix ordering of image reference in actions outputs

core/src/plugins/container/container.ts
(cherry picked from commit 7932c89969d4b48e11b494025ba41ef136fb280d)
Fixes #
=> chore: update docker shipped with garden tools (#5816)

CHANGELOG.md, README.md, RELEASE_PROCESS.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.29

core/src/vcs/git.ts
There has been an extra explicit profiler for `GitHandler#hashObject` method. It seems not necessary, because the entire class `GitHandler` is decorated with `@Profile()`.
Tried to generate large project (with 125617 untracked files. each one assume `hashObject` invocation) and got the following results.
**Before:**
```console
Profiling data:
─────────────────────────────────────────────────────────────────────────────────────────
Function/method               # Invocations  Total ms        Avg. ms      First ms    
GitHandler#hashObject         251244         34264925.52 ms  136.38 ms    58.28 ms    
```
**After:**
```console
Profiling data:
─────────────────────────────────────────────────────────────────────────────────────────
Function/method …
```
=> improvement(git): avoid duplicate profiling of `GitHandler.hashObject`

core/src/graph/common.ts, core/src/router/base.ts, core/src/template-string/template-string.ts, core/test/unit/src/garden.ts, core/test/unit/src/router/base.ts
Profile more function invocations. I'll implement cache misses/hits profiling in a separate PR.
Fixes #
=> chore(profiling): profile more functions

core/src/util/profiling.ts, core/src/vcs/git-repo.ts, core/src/vcs/vcs.ts
=> chore(profiling): profile VCS `TreeCache` hits and misses

README.md, docs/README.md, docs/getting-started/installation.md, docs/getting-started/next-steps.md, docs/getting-started/quickstart.md, docs/other-plugins/container.md, docs/pulumi-plugin/actions.md, docs/terraform-plugin/actions.md, docs/using-garden/about.md, docs/using-garden/actions.md, docs/using-garden/config-templates.md, docs/using-garden/configuration-overview.md, docs/using-garden/dashboard.md, docs/using-garden/modules.md, docs/using-garden/projects.md, docs/using-garden/runs.md, docs/using-garden/tests.md, docs/using-garden/using-the-cli.md, docs/using-garden/variables-and-templating.md, docs/using-garden/workflows.md
**First commit:**
Some minor updates to README. Namely:
- Change intro text to better match what we have in our docs
- Remove GIF, it felt noisy and didn't help explain the product
- Other README tweaks
**Second commit:**
This commit moves the contents of the 'Using Garden' README to its own
page to ensure it's visible. Also:
- Remove references to Rosetta, it's not longer needed
- Rename 'Action Configuration' to 'Actions'
- Other minor fixes
Fixes #
=> docs: update README

core/src/template-string/template-string.ts, core/src/util/profiling.ts
=> chore(profiler): print more metrics for invocations

core/src/cli/cli.ts
0.13 has been out for a long time now.
Fixes #
=> chore: remove bonsai warning (0.13 is a major release...)

core/src/cloud/api.ts
=> improvement(cloud): more informative error message on CA cert problems

core/src/cloud/api.ts, core/test/unit/src/commands/login.ts
=> chore: improve error message if auth token invalid

plugins/jib/openjdk.ts
Back-ports #5970 to 0.12.
Fixes #
=> improvement(jib): support JDK 21 LTS version

docs/reference/module-types/jib-container.md, plugins/jib/index.ts
=> fix(jib): allow the usage of the JDK 21

core/src/plugins/kubernetes/commands/pull-image.ts
If a  `nodeSelector` is specified for `clusterBuildkit` or `kaniko` also use it for the pull image pods. 
Fixes #
=> chore: add nodeSelector for pull-image pods

core/src/vcs/file-tree.ts, core/src/vcs/git.ts, core/src/vcs/vcs.ts
One more tidying and janitorial PR for VCS handling classes. Add-on for #5967.
=> refactor(vcs): keep class fields private and readonly if possible

cli/src/build-pkg.ts, cli/test/unit/src/build-pkg.ts, core/src/util/testing.ts
This will make the next NodeJS version updates a bit smoother and less error-prone.
Fixes #
=> test: verify the hashes of the bundled NodeJS binaries

support/install.sh
Make sure that if curl fails due to a network problem or the server
responding with a 4xx/5xx response, that we display an error message to
the user.
Related issue (Not a fix): #5905
=> improvement(install.sh): display curl error messages

core/package.json, e2e/package.json, package-lock.json, package.json, plugins/jib/package.json
=> chore(deps): update `@types/lodash-es`

support/install.sh
=> Revert "improvement(install.sh): display curl error messages"

core/src/plugins/kubernetes/helm/common.ts, core/test/integ/src/plugins/kubernetes/helm/common.ts
When more than one Helm Deploys that referenced the same dependency chart were executed simultaneously, this would trigger a race condition (since the concurrent calls to `helm dependency update` would result in one call cleaning up the temp directory while another call was using it).
This was fixed by adding an async lock (keyed by chart path) and a simple in-memory TTL (making sure we don't re-fetch the same dependency chart if it's already been fetched in the last 300 seconds).
Fixes #5979.
=> fix(helm): fix race condition when updating deps

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.30

core/src/cloud/api.ts, core/src/commands/cloud/helpers.ts, core/src/commands/cloud/secrets/secret-helpers.ts, core/src/commands/cloud/secrets/secrets-create.ts, core/src/commands/cloud/secrets/secrets-list.ts, core/src/commands/cloud/secrets/secrets-update.ts, core/src/commands/cloud/users/users-create.ts, core/test/unit/src/commands/cloud/secrets/secrets-update.ts
=> refactor(cloud): helpers to create and update secrets

core/src/cloud/api.ts, core/src/commands/cloud/secrets/secret-helpers.ts, core/src/commands/cloud/secrets/secrets-create.ts, core/src/commands/cloud/secrets/secrets-list.ts, core/src/commands/cloud/secrets/secrets-update.ts, core/test/unit/src/commands/cloud/secrets/secrets-update.ts
=> refactor(cloud): move secrets helpers to `CloudApi`

core/test/data/test-projects/kubernetes-type/api-image/requirements.txt, e2e/projects/vote-helm-modules/api-image/requirements.txt, e2e/projects/vote-modules/api/requirements.txt, examples/vote-helm/api-image/requirements.txt, examples/vote/api/requirements.txt
=> chore: update requests lib to 2.32.0 in Python projects

.circleci/continue-config.yml, images/circleci-runner/Dockerfile, images/circleci-runner/garden.yml
=> chore(images): update `circleci-runner`'s base images

core/src/actions/types.ts
=> refactor: re-use `OmitInternalConfig` type

README.md
Adds a warning on the main `README.md` about EOL for Garden Acorn.
Note: this is temporary and will be removed on the 1st of July.
Fixes #
=> Add EOL for Acorn to main README.md

core/src/plugins/kubernetes/helm/helm-cli.ts, docs/reference/action-types/Deploy/helm.md, docs/reference/module-types/helm.md
See full Helm changelog in the [release notes](https://github.com/helm/helm/releases/tag/v3.15.0).
Fixes #
=> tool(helm): update version to `3.15.1`

core/src/plugins/kubernetes/kubectl.ts, core/src/plugins/kubernetes/kubernetes-type/config.ts, docs/reference/action-types/Deploy/kubernetes.md, docs/reference/module-types/kubernetes.md
See the Discord thread for details: https://discord.com/channels/817392104711651328/1077431043482714282
Fixes #3839
=> feat: allow custom args in `kubectl apply` for kubernetes deployments

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.31

plugins/conftest/index.ts
=> chore(conftest): [0.12] exclude `conftest` from Garden Docker images

core/src/plugins/kubernetes/container/build/kaniko.ts, core/test/unit/src/plugins/kubernetes/container/build/kaniko.ts
=> fix: allow dashes in kaniko options

core/src/util/fs.ts, core/test/unit/src/vcs/git.ts
=> refactor(test): replace redundant helper with existing `makeTempDir`

core/test/unit/src/vcs/git.ts
=> refactor(test): simpler test config

core/test/unit/src/vcs/vcs.ts
=> test(git): fix some test configs and assertions

core/src/actions/base.ts, core/src/config/base.ts, core/src/vcs/vcs.ts, core/test/unit/src/vcs/vcs.ts
Avoid code duplication in VCS logic and in the `BaseAction` class.
Fixes #
=> refactor: helper to get action source path

docs/contributing/developing-garden.md
just fix a small typo :)
Fixes: none issue existing for this small thing 🫣
🤷
=> docs: fix typo „npm run run …“

docs/guides/migrating-to-bonsai.md
During the Bonsai release there was some confusion around the best practices for referencing a container build in a `container` Deploy action.
Originally we used the `build` field for this but it has caused confusion and only works for Deploy actions of type `container`, not e.g. `helm` or `kubernetes`.
So for consistency, we decided that the best practice should be to always explicitly set the corresponding Build action as a dependency for ALL Deploy actions (i.e. any type).
This commit updates the Bonsai migration guide to reflect that. Previously we've updated all our examples and other parts of our documentation.
Fixes #
=> improvement(docs): do not use `build` field in migration guide

core/test/data/test-projects/helm/api-image/requirements.txt, e2e/projects/vote-helm-modules/api-image/requirements.txt, e2e/projects/vote-modules/api/requirements.txt, examples/k8s-deploy-config-templates/api/requirements.txt, examples/k8s-deploy-patch-resources/api/requirements.txt, examples/k8s-deploy-shared-manifests/api/requirements.txt, examples/vote-helm/api-image/requirements.txt, examples/vote/api/requirements.txt
Applies the changes from #6191 to all Python projects (in examples and tests).
Fixes #
=> chore(deps): bump urllib3 to 1.26.19 in Python examples and tests

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.32

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.33

core/src/plugins/kubernetes/helm/helm-cli.ts, docs/reference/action-types/Deploy/helm.md, docs/reference/module-types/helm.md
=> tool(helm): update version to 3.15.2

support/debian.Dockerfile
=> chore(deps): bump google/cloud-sdk to 482.0.0 in debian.Dockerfile

plugins/conftest/src/index.ts
=> tool(conftest): exclude `conftest` from Docker images

cli/package.json, core/package.json, e2e/package.json, package-lock.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json
=> chore(deps-dev): bump mocha and @types/mocha

core/src/plugins/kubernetes/kubectl.ts
Update `kubectl` to the latest available version.
Fixes #
=> tool(kubectl): update version to 1.30.2

core/src/vcs/git-repo.ts
We need to evaluate real FS paths in `VcsHandler.getTreeVersion()` and use those in the downstream function calls.
This is necessary because we use cache that uses paths as parts of the keys.
If the input path starts with a symlink (e.g. `/var/...` with a symlink `/var -> /private/var`),
then the cache keys can be inconsistent in some scenarios.
Without this fix, test spec `"should not update content hash for Deploy, when there's no change in included files of Build"` would fail locally on macOS because of `/var -> /private/var` symlink.
That seems to be a rare failure case, but it's still a bug.
See the comments in the code for more technical details.
=> fix(git): use consistent cache keys for paths with symlinks

package-lock.json, plugins/terraform/package.json
=> chore(terraform): add missing @types/mocha in package.json

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.34

examples/k8s-deploy-config-templates/README.md, examples/k8s-deploy-patch-resources/README.md, examples/k8s-deploy-shared-manifests/README.md
It's easy to forget them if you copy the snippet from the READMEs.
Fixes #
=> fix(examples): mention in READMEs that build deps need to be set

core/src/docs/template-strings.ts, docs/reference/template-strings/action-all-fields.md
=> docs(typo): add missing whitespace

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.35

support/debian.Dockerfile
=> chore(deps): bump google/cloud-sdk to 484.0.0 in debian.Dockerfile

support/alpine.Dockerfile, support/debian.Dockerfile
=> chore(deps): bump aws/aws-cli to 2.17.15 in /support

support/alpine.Dockerfile, support/debian.Dockerfile
=> chore(deps): bump azure/azure-cli to 2.62.0 in /support

core/src/cli/cli.ts, core/src/cli/helpers.ts, core/src/commands/serve.ts, core/src/constants.ts
See the linked issue for the details.
Fixes #6303
=> feat(cli): `GARDEN_DISABLE_WEB_APP_WARN` flag to mute cloud login warn

docs/misc/troubleshooting.md
This is based on an internal learning. Not sure if Garden can be smarter her, so first step is at least to document the issue.
Fixes #
=> docs(troubleshooting): add entry on using int values in K8s manifests

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
This is a maintenance release that includes bug fixes and small improvements.
Download the Garden binary for your platform from below or simply run `garden self-update` if you already have it installed.
* [Garden v0.13.36 for Alpine AMD64 (tar.gz)](https://download.garden.io/core/0.13.36/garden-0.13.36-alpine-amd64.tar.gz)
* [Garden v0.13.36 for Linux AMD64 (tar.gz)](https://download.garden.io/core/0.13.36/garden-0.13.36-linux-amd64.tar.gz)
* [Garden v0.13.36 for Linux ARM64 (tar.gz)](https://download.garden.io/core/0.13.36/garden-0.13.36-linux-arm64.tar.gz)
* [Garden v0.13.36 for MacOS AMD64 (tar.gz)](https://download.garden.io/core/0.13.36/garden-0.13.36-macos-amd64.tar.gz)
* [Garden v0.13.36 for MacOS ARM64 (tar.gz)](https://download.garden.io/core/0.13.36/garden-0.13.36-macos-arm64.tar …
=> chore(release): bump version to 0.13.36

core/src/plugins/kubernetes/run.ts
Adds handling errors on stream end for podRunner log streams see https://www.npmjs.com/package/ts-stream#handling-a-stream-end
Fixes #
=> improvement: add error handler callback to podRunner log streams

.tool-versions, nix/tool-versions.nix, shell.nix
Tangential to conversation I've seen in existing GitHub Issues about packaging Garden for Nixpkgs, this PR sets up a nix-shell file to support complete developer environment setup via the `nix-shell` command.
This may not even be a desirable addition to the Garden repo, but I was writing the shell file for myself anyway, so I figured I'd see if you all wanted it upstream.
Fixes #
=> chore(tooling): add a shell.nix file

support/alpine.Dockerfile, support/debian.Dockerfile
=> chore(support): bump Azure and AWS CLI versions

support/alpine.Dockerfile, support/debian.Dockerfile
=> chore(support): bump Node to 22.6.0

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.37

core/src/plugins/container/container.ts, scripts/compute-ext-tool-binary-shas.sh
This was prompted by some security vulnerabilities with the previous version of the Docker CLI we were bundling with Garden.
=> tool(docker): update bundled Docker CLI to 27.1.1

core/package.json, e2e/package.json, package-lock.json, plugins/jib/package.json, plugins/terraform/package.json
=> chore(deps): bump split2 from 4.1.0 to 4.2.0

support/debian.Dockerfile
=> chore(support): bump google/cloud-sdk to 487.0.0 in debian.Dockerfile

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.38

examples/pulumi/k8s-namespace/garden.yml
Remove the reference to the build action that does not exist.
Fixes #
=> fix(examples): remove invalid action dependency from pulumi example

support/alpine.Dockerfile, support/debian.Dockerfile
=> chore(support): bump aws/aws-cli to 2.17.33 in Docker images

support/debian.Dockerfile
=> chore(support): bump google/cloud-sdk to 488.0.0 in debian.Dockerfile

examples/demo-project/garden.yml
=> chore(examples): remove wrong ignorefile config

core/src/garden.ts
=> fix(template): keep action variables when resolving disabled flag

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.39

support/debian.Dockerfile
=> chore(support): bump google/cloud-sdk to 490.0.0 in debian.Dockerfile

support/debian.Dockerfile
=> chore(support): bump google/cloud-sdk to 491.0.0 in debian.Dockerfile

docs/terraform-plugin/about.md
=> docs(terraform): update links in the Terraform plugin readme

support/debian.Dockerfile
=> chore(support): bump google/cloud-sdk to 492.0.0 in debian.Dockerfile

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.40

core/src/garden.ts, core/src/vcs/git-sub-tree.ts, core/src/vcs/git.ts, core/test/unit/src/vcs/file-tree.ts, core/test/unit/src/vcs/git.ts
Preliminary changes for lazy VCS files hashing.
Fixes #
=> refactor(git): refactor hashing machinery to be less complex

e2e/projects/tasks-modules/hello/package.json
Remove trailing comma. Dependabot complained about json syntax.
Fixes #
=> chore(e2e): fix json format

support/debian.Dockerfile
=> chore(support): bump google/cloud-sdk to 493.0.0 in debian.Dockerfile

support/alpine.Dockerfile, support/debian.Dockerfile
=> chore(support): bump azure-cli to 2.64.0

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.41

examples/gatsby-code-sync/README.md
=> chore: fix dead links in Gatsby example readme

docs/overview/garden-vs-other-tools.md
=> docs: fix header markdown

support/debian.Dockerfile
=> chore(support): bump google/cloud-sdk to 495.0.0 in debian.Dockerfile

core/src/plugins/kubernetes/constants.ts, images/buildkit/Dockerfile, images/buildkit/garden.yml
=> chore(images): update buildkit image

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.42

package-lock.json
Used `npm audit fix`.
This should resolve some dependency conflicts that block automated dependabot PRs.
Fixes #
=> chore(deps): auto-fix some vulnerabilities

support/alpine.Dockerfile, support/debian.Dockerfile
=> chore(support): bump azure-cli to 2.65.0 in Docker images

support/debian.Dockerfile
=> chore(support): bump google/cloud-sdk to 496.0.0 in debian.Dockerfile

core/src/config/provider.ts, core/src/garden.ts, core/src/graph/actions.ts, core/src/resolve-module.ts, core/src/util/util.ts, core/src/vcs/vcs.ts, core/test/unit/src/config/provider.ts
**What this PR does / why we need it:**
* deduplicate paths when find minimal repo roots
* process action configs in batches
=> perf: optimize action configs processing

core/package.json, package-lock.json
Update to the latest available 1.0 RC release instead of a fixed commit hash.
Fixes #
=> chore(deps): update kubernetes/client-node to 1.0.0-rc7

support/debian.Dockerfile
=> chore(support): bump google/cloud-sdk to 497.0.0 in debian.Dockerfile

core/src/config/base.ts, core/src/constants.ts, core/src/graph/actions.ts
=> chore: configurable action config processing batch size

support/debian.Dockerfile
=> chore(support): bump google/cloud-sdk to 498.0.0 in debian.Dockerfile

core/src/plugins/container/container.ts
=> fix: render action reference in error message

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.43

core/src/commands/base.ts, core/src/commands/cloud/helpers.ts, core/src/commands/create/create-project.ts, core/src/util/util.ts
That has been broken since the major version update of inquirer library on 0.13.43.
Fixes #6612
=> fix: fix user prompt function

plugins/terraform/src/cli.ts
=> chore: exclude terraform form workflow-runner images

core/src/plugins/kubernetes/kubectl.ts
=> tool(kubectl): update version to 1.31.2

core/src/plugins/kubernetes/helm/helm-cli.ts, core/src/plugins/kubernetes/kubernetes.ts, core/test/unit/src/verify-ext-tool-binary-hashes.ts, docs/reference/action-types/Deploy/helm.md, docs/reference/module-types/helm.md
=> tool(helm): update version to 3.16.2

support/debian.Dockerfile
=> chore(support): bump google/cloud-sdk to 500.0.0 in debian.Dockerfile

support/debian.Dockerfile
=> chore(support): bump google/cloud-sdk to 501.0.0 in debian.Dockerfile

core/src/mutagen.ts, core/src/plugins/kubernetes/constants.ts, images/k8s-sync/Dockerfile, images/k8s-sync/garden.yml, images/k8s-util/garden.yml
=> tool(mutagen): update version to 0.18.0

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.44

core/src/mutagen.ts, core/src/plugins/kubernetes/constants.ts, images/k8s-sync/Dockerfile, images/k8s-sync/garden.yml, images/k8s-util/garden.yml
=> revert: tool(mutagen): update version to 0.18.0

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.45

core/src/mutagen.ts
=> chore: use cleanup command and not deprecated delete in helper message

core/src/graph/config-graph.ts
=> perf(framework): avoid unnecessary config graph cloning

core/src/config/base.ts
=> chore(varfiles): avoid unnecessary path existence checks

docs/k8s-plugins/guides/in-cluster-building.md
We've seen stability issues with Kaniko in the past and now generally recommend using the `cluster-buildkit` build mode for in-cluster building.
This commit updates our docs to reflect that.
Fixes #
=> docs: recommend buildkit for in-cluster building

core/src/template-string/parser.pegjs, core/test/unit/src/template-string.ts
A follow-up for #6685.
Replays #6408 on top of #6685.
Fixes #
=> fix(template): fix template string escaping

core/src/mutagen.ts
The if condition was too strict, and mutagen changed the message
slightly
See also https://github.com/garden-io/garden/issues/6711#issuecomment-2539532564
=> fix: make sure to display the mutagen version update warning message

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
Download the Garden binary for your platform from below or simply run `garden self-update` if you already have it installed.
* [Garden v0.13.47 for Alpine AMD64 (tar.gz)](https://download.garden.io/core/0.13.47/garden-0.13.47-alpine-amd64.tar.gz)
* [Garden v0.13.47 for Linux AMD64 (tar.gz)](https://download.garden.io/core/0.13.47/garden-0.13.47-linux-amd64.tar.gz)
* [Garden v0.13.47 for Linux ARM64 (tar.gz)](https://download.garden.io/core/0.13.47/garden-0.13.47-linux-arm64.tar.gz)
* [Garden v0.13.47 for MacOS AMD64 (tar.gz)](https://download.garden.io/core/0.13.47/garden-0.13.47-macos-amd64.tar.gz)
* [Garden v0.13.47 for MacOS ARM64 (tar.gz)](https://download.garden.io/core/0.13.47/garden-0.13.47-macos-arm64.tar.gz)
* [Garden v0.13.47 for Windows AMD64 …
=> chore(release): bump version to 0.13.47

cli/src/cli.ts, core/src/analytics/analytics.ts, core/src/cli/cli.ts, core/src/cloud/api.ts, core/src/cloud/backend.ts, core/src/cloud/workflow-lifecycle.ts, core/src/commands/base.ts, core/src/commands/serve.ts, core/src/commands/workflow.ts, core/src/garden.ts, core/src/server/instance-manager.ts, core/src/server/server.ts, core/test/helpers/cli.ts, core/test/unit/src/cli/cli.ts, core/test/unit/src/commands/version.ts
=> refactor(cloud): improve type-safety and get rid of some default param values

cli/src/cli.ts, core/src/cli/cli.ts, core/src/cloud/api.ts, core/src/cloud/util.ts, core/src/commands/login.ts, core/src/commands/serve.ts, core/src/garden.ts, core/src/server/instance-manager.ts, core/src/server/server.ts, core/src/util/testing.ts, core/test/helpers/api.ts, core/test/helpers/cli.ts, core/test/integ/src/plugins/kubernetes/helm/deployment.ts, core/test/unit/src/analytics/analytics.ts, core/test/unit/src/cli/cli.ts, core/test/unit/src/commands/login.ts, core/test/unit/src/commands/version.ts, core/test/unit/src/garden.ts, core/test/unit/src/plugins/kubernetes/ephemeral.ts, core/test/unit/src/server/server.ts
=> refactor: move `CloudApi` creation to `resolveGardenParams`

core/src/cli/cli.ts
Print name of project with init log, useful for when users with multiple projects look back on logs.
Fixes #
=> improvement(core): print project name with init log

plugins/pulumi/test/test-project-k8s/k8s-namespace-new-module/package-lock.json
=> chore: update package-lock.json of pulumi test project

core/src/build-staging/build-staging.ts, core/src/constants.ts, core/src/garden.ts
=> fix: use non-legacy build staging file sync on Windows by default

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.49

docs/guides/code-synchronization.md
=> docs(sync): simplify the command to stop the lingering syncs manually

examples/run-actions/user/Dockerfile, examples/run-actions/user/Gemfile
Fixes `e2e-run-actions` tests.
Fixes #
=> ci: update Ruby image version

support/alpine.Dockerfile, support/debian.Dockerfile
=> chore(deps): bump azure-cli to 2.68.0

.circleci/continue-config.yml
The workspace already has the binary unzipped, so we can skip this step.
Fixes #
=> fix: remove unzip step from code-signing workflow

support/debian.Dockerfile
=> chore(deps): bump google/cloud-sdk to 506.0.0 in debian.Dockerfile

.circleci/continue-config.yml
=> fix: specify default region when trying to code-sign binary

.circleci/continue-config.yml
=> fix: remove dollar from aws-cli/setup job for code-signing

.circleci/continue-config.yml
=> fix: persist workspace after signing binaries

core/src/plugins/kubernetes/kubernetes-type/handlers.ts
This fixes an issue were in some (edge) cases the image pull secret is created in the target namespace is using the `kubernetes` Deploy type.
I say edge case because the image pull secret is usually ensured in other code paths, e.g. when initialising in-cluster builders and as AFAICT this only happens if using the cloud builder in the k8s Deploy type.
The operation is idempotent so calling it again here should be fine.
TODO @myself: I want to refactor this flow a little bit in a follow up commit but wanted to get the fix out the way first.
Fixes #
=> fix(k8s): ensure image pull secret is always created for K8s Deploy

core/src/plugins/kubernetes/helm/status.ts
Before this fix, we'd check for paused Helm resources by listing all rendered resources and not handling the error if the resource isn't deployed in the first place.
Furthermore, we were missing an `await` statement so the 404 error from a missing resource would pop up at a random time, usually after the status handler returns.
So essentially a `helm` Deploy could fail if using AEC and a potentially paused resource was missing.
Now we correctly ignore rendered resources that haven't been deployed and await for the API call.
Fixes #
=> fix(k8s): do not throw if paused resource is missing

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.51

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.52

core/src/plugins/kubernetes/constants.ts, images/k8s-sync/Dockerfile, images/k8s-sync/garden.yml, images/k8s-util/garden.yml
=> chore(image): update base image to Alpine to 3.21.2 in `k8s-sync` and `k8s-util`

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.53

core/src/garden.ts, core/src/plugins/hadolint/hadolint.ts, core/src/plugins/octant/octant.ts, core/src/util/deprecations.ts, docs/guides/deprecations.md, docs/reference/providers/terraform.md, plugins/conftest/src/index.ts
=> chore(plugins): re-work old plugins deprecation

core/src/commands/deploy.ts, core/src/commands/dev.tsx, core/src/commands/serve.ts, core/src/util/deprecations.ts, docs/guides/deprecations.md
=> chore: deprecate local-mode on the command level

core/src/analytics/analytics.ts, core/src/garden.ts, core/test/unit/src/analytics/analytics.ts, docs/misc/telemetry.md
Adds action counts to telemetry data. 
Fixes #
=> chore(core): add action count to data

core/src/plugins/kubernetes/container/deployment.ts
=> fix: mute false-positive deprecation warning for `deploymentStrategy`

core/src/template/evaluate.ts
=> fix(template): propagate condition recursively in `conditionallyDeepEvaluate`

core/src/plugins/kubernetes/kubernetes-type/deploy.ts
=> fix(k8s): crash if `spec.files` in a `kubernetes` `Deploy` action is a template value

core/package.json, package-lock.json
Version 1.0 has recently been released: https://github.com/kubernetes-client/javascript/releases/tag/1.0.0
Fixes some vulnerabilities in dependencies of the Kubernetes client.
=> chore(deps): update `kubernetes-client/javascript` to `1.0.0`

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
This is a maintenance release that includes bug fixes, features, and improvements.
Download the Garden binary for your platform from below or simply run `garden self-update` if you already have it installed.
* [Garden v0.13.54 for Alpine AMD64 (tar.gz)](https://download.garden.io/core/0.13.54/garden-0.13.54-alpine-amd64.tar.gz)
* [Garden v0.13.54 for Linux AMD64 (tar.gz)](https://download.garden.io/core/0.13.54/garden-0.13.54-linux-amd64.tar.gz)
* [Garden v0.13.54 for Linux ARM64 (tar.gz)](https://download.garden.io/core/0.13.54/garden-0.13.54-linux-arm64.tar.gz)
* [Garden v0.13.54 for MacOS AMD64 (tar.gz)](https://download.garden.io/core/0.13.54/garden-0.13.54-macos-amd64.tar.gz)
* [Garden v0.13.54 for MacOS ARM64 (tar.gz)](https://download.garden.io/core/0.13.54/garden-0.13.54-macos-arm6 …
=> release 0.13.54

core/src/plugins/kubernetes/config.ts, core/src/plugins/kubernetes/container/deployment.ts, core/src/util/deprecations.ts, docs/guides/deprecations.md, docs/reference/providers/kubernetes.md, docs/reference/providers/local-kubernetes.md
=> chore: deprecation warning corrections

core/src/graph/actions.ts, core/test/unit/src/graph/actions.ts
This commit fixes a regression introduced in #6745 where we stopped throwing an error for unknown keys in action configs.
Fixes #6846
=> fix(config): throw validation errors when encountering unknown keys in action configs

core/src/plugins/kubernetes/retry.ts
=> improvement(k8s): improve logs when maximum retry attempts exceeded

core/src/config/base.ts, core/src/garden.ts, core/src/project-api-version.ts, core/src/template/ast.ts, core/src/util/deprecations.ts, core/test/setup.ts, core/test/unit/src/template-string.ts, docs/guides/deprecations.md
=> chore(template): feature flag for optional template values

core/src/util/deprecations.ts, docs/guides/deprecations.md
=> chore: fix typos in deprecation guide

core/src/docs/generate.ts, docs/guides/deprecations.md
=> docs: Improve migration docs headlines to be easier to read

docs/README.md, docs/misc/cloud-announcement.md, docs/reference/commands.md
A draft announcement for the new Cloud version we can share with the community. There will be also be a more formal announcement around the launch itself.
Fixes #
=> docs: add draft announcement for new cloud version

docs/misc/cloud-announcement.md
=> docs: tweak formatting

core/src/plugins/container/config.ts, core/src/plugins/kubernetes/config.ts, core/src/plugins/kubernetes/helm/config.ts, core/src/plugins/kubernetes/kubernetes-type/kubernetes-pod.ts, docs/reference/action-types/Run/container.md, docs/reference/action-types/Run/helm-pod.md, docs/reference/action-types/Run/kubernetes-pod.md, docs/reference/action-types/Test/helm-pod.md, docs/reference/action-types/Test/kubernetes-pod.md, docs/reference/module-types/container.md, docs/reference/module-types/helm.md, docs/reference/module-types/jib-container.md, docs/reference/module-types/kubernetes.md
=> fix(docs): propagate correct action kind to k8s Run/Test reference docs

core/test/unit/src/config/base.ts
Fixes the unit test failures in the main branch.
Fixes #
=> test: fix test assertions in `prepareProjectResource`

core/src/docs/generate.ts, core/src/util/deprecations.ts, docs/guides/deprecations.md
=> docs: fix deep links to migration guide

docs/misc/cloud-announcement.md
=> docs: update cloud-announcement

core/src/util/deprecations.ts, docs/guides/deprecations.md, docs/misc/cloud-announcement.md
Refer to new container builder as Remote Container Builder as opposed to Managed Container Builder where applicable.
Fixes #
=> docs: mention team caches in announcement

docs/misc/cloud-announcement.md
=> docs: update release date in cloud announcement

core/src/cloud/api.ts, core/src/plugins/kubernetes/container/run.ts, core/src/plugins/kubernetes/container/test.ts, core/src/plugins/kubernetes/helm/helm-pod.ts, core/src/plugins/kubernetes/kubernetes-type/kubernetes-pod.ts, core/src/plugins/kubernetes/results-cache-base.ts, core/src/plugins/kubernetes/results-cache-cloud-v1.ts, core/src/plugins/kubernetes/results-cache-fs.ts, core/src/plugins/kubernetes/results-cache.ts, core/src/plugins/kubernetes/run-results.ts, core/src/plugins/kubernetes/test-results.ts, core/test/integ/src/plugins/kubernetes/container/run.ts, core/test/integ/src/plugins/kubernetes/helm/run.ts, core/test/integ/src/plugins/kubernetes/kubernetes-type/kubernetes-pod-run.ts, core/test/integ/src/plugins/kubernetes/run-results.ts, core/test/integ/src/plugins/kubernetes/test-results.ts, core/test/unit/src/plugins/kubernetes/result-cache-fs.ts
=> feat(k8s)!: action results caching in Garden Cloud V1

.circleci/continue-config.yml
Otherwise tests fail due to GCR being deprecated in favour of artifact registry (AFAICT).
We'll need to fix and re-enable post launch.
Feel free to close if we had a different approach in mind, was just following #6965 as I noticed tests are still failing.
Fixes #
=> ci(e2e): temporarily disable more e2e tests

core/src/cloud/grow/api.ts, core/src/cloud/grow/trpc-schema.ts, core/src/cloud/grow/trpc.ts, core/src/plugins/kubernetes/kubernetes-type/kubernetes-exec.ts, core/src/plugins/kubernetes/kubernetes-type/kubernetes-pod.ts, core/src/plugins/kubernetes/results-cache-base.ts, core/src/plugins/kubernetes/results-cache-cloud-v1.ts, core/src/plugins/kubernetes/results-cache-cloud-v2.ts, core/src/plugins/kubernetes/results-cache-fs.ts, core/src/plugins/kubernetes/results-cache.ts, core/src/plugins/kubernetes/run-results.ts, core/src/plugins/kubernetes/test-results.ts, core/src/tasks/base.ts, core/src/util/util.ts, core/test/integ/src/plugins/kubernetes/run-results.ts, core/test/unit/src/plugins/kubernetes/result-cache-fs.ts, examples/demo-project/garden.yml
=> feat(k8s)!: action results caching in Garden Cloud V2

examples/demo-project/garden.yml
AFAICT this was added by accident. Not sure though so I'll be happy to revert if I got this wrong.
Fixes #
=> chore(examples): remove org ID from demo project

core/src/cloud/api.ts, core/src/cloud/auth.ts, core/src/commands/login.ts, core/src/plugins/kubernetes/results-cache-base.ts, core/src/plugins/kubernetes/results-cache-cloud-v1.ts, core/src/plugins/kubernetes/results-cache-cloud-v2.ts, core/src/plugins/kubernetes/results-cache-fs.ts, core/src/plugins/kubernetes/run-results.ts, core/src/plugins/kubernetes/test-results.ts, core/src/tasks/base.ts, core/src/tasks/build.ts, core/src/tasks/deploy.ts, core/src/tasks/helpers.ts, core/src/tasks/run.ts, core/src/tasks/test.ts, core/test/unit/src/cloud/auth.ts
Various tweaks to log copy around action caching and the `login` command.
=> chore: improved log copy around login & cache

.gitbook.yaml
=> docs: remove deleted plugin paths from `gitbook.yaml`

core/src/plugins/container/config.ts, core/src/plugins/container/moduleConfig.ts, core/src/plugins/kubernetes/kubernetes-type/module-config.ts
=> chore: todos to deprecate `hotReload` config syntax in schemas

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.56

core/src/cloud/grow/api.ts, core/src/cloud/grow/auth.ts, core/src/cloud/grow/notices.ts, core/src/cloud/grow/trpc-schema.ts, core/src/cloud/grow/trpc.ts, project.garden.yml
=> feat: print backend error notices for managing client version phase out

core/src/cloud/grow/api.ts, core/src/cloud/grow/trpc.ts, core/src/plugins/kubernetes/results-cache-cloud-v2.ts
=> chore: ensure `organizationId` in every tRPC request

docs/features/remote-container-builder.md, docs/getting-started/quickstart.md, docs/guides/connecting-project.md, docs/guides/registry-mirror.md, docs/misc/faq.md
=> docs: minor copy tweaks

core/src/project-api-version.ts, core/src/util/deprecations.ts, docs/misc/migrating-to-cedar.md
- docs: add cedar migration guide
- chore: update migration guide docs links
- chore: improve the error for unsupported api version settings
=> docs: cedar migration guide

docs/misc/migrating-to-cedar.md
=> docs: fix title for cedar migration guide

CHANGELOG.md, README.md, cli/package.json, core/package.json, core/src/project-api-version.ts, docs/garden-for/kubernetes/deploy-k8s-resource.md, docs/garden-for/terraform/README.md, docs/garden-for/terraform/configure-provider.md, docs/guides/using-garden-in-circleci.md, docs/overview/use-cases/jumpstart-idp.md, docs/overview/use-cases/local-development-remote-clusters.md, docs/overview/use-cases/on-demand-preview-envs.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/jib.md, docs/tutorials/remote-k8s/ingress-and-dns.md, e2e/package.json, package-lock.json, package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.14.0

docs/README.md, docs/features/remote-container-builder.md, docs/misc/migrating-to-bonsai.md, docs/misc/migrating-to-cedar.md
=> docs: minor fixes

core/src/util/deprecations.ts, docs/README.md, docs/guides/deprecations.md
=> docs: minor corrections

docs/features/remote-container-builder.md, docs/garden-for/containers/using-remote-container-builder.md, docs/getting-started/next-steps.md, docs/getting-started/quickstart.md, docs/overview/what-is-garden.md
=> docs: update docs due to container builder being enabled by default

core/test/data/test-projects/helm/api-image/requirements.txt, core/test/data/test-projects/kubernetes-type/api-image/requirements.txt, e2e/projects/vote-helm-modules/api-image/requirements.txt, e2e/projects/vote-modules/api/requirements.txt, examples/k8s-deploy-config-templates/api/requirements.txt, examples/k8s-deploy-patch-resources/api/requirements.txt, examples/k8s-deploy-shared-manifests/api/requirements.txt, examples/vote-helm/api-image/requirements.txt, examples/vote/api/requirements.txt
=> chore(examples): update `gunicorn` in Python projects

core/src/cloud/api.ts, core/src/cloud/util.ts
=> chore: remove dead code from `GardenCloudApi`

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.57

docs/features/code-synchronization.md, docs/features/config-templates.md, docs/features/remote-sources.md, docs/features/variables-and-templating.md, docs/garden-for/containers/building-containers.md, docs/garden-for/kubernetes/deploy-k8s-resource.md, docs/garden-for/kubernetes/remote-kubernetes.md, docs/garden-for/local-scripts.md, docs/garden-for/pulumi/actions.md, docs/garden-for/pulumi/configure-provider.md, docs/garden-for/terraform/actions.md, docs/garden-for/terraform/configure-provider.md, docs/getting-started/next-steps.md, docs/guides/include-exclude.md, docs/guides/migrating-from-docker-compose.md, docs/guides/namespaces.md, docs/guides/using-garden-in-circleci.md, docs/misc/faq.md, docs/tutorials/remote-k8s/README.md, docs/tutorials/remote-k8s/configure-provider.md, docs/tutorials/your-first-project/3-add-actions.md
=> docs: update for 0.14

RELEASE_PROCESS.md
=> docs: update 0.13 release guide

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/garden-for/kubernetes/deploy-k8s-resource.md, docs/garden-for/terraform/README.md, docs/garden-for/terraform/configure-provider.md, docs/guides/using-garden-in-circleci.md, docs/overview/use-cases/jumpstart-idp.md, docs/overview/use-cases/local-development-remote-clusters.md, docs/overview/use-cases/on-demand-preview-envs.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/jib.md, docs/tutorials/remote-k8s/ingress-and-dns.md, e2e/package.json, package-lock.json, package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.14.1

docs/README.md, docs/misc/nginx-vulnerability.md
=> docs: add guide on nginx vuln

core/src/util/deprecations.ts, docs/guides/deprecations.md
=> docs: fix anchor links and typos in deprecations guide

core/src/commands/sync/sync-stop.ts
=> fix(sync): await monitors stop on `sync stop` completion

support/debian.Dockerfile
=> chore(deps): bump google/cloud-sdk from to 516.0.0 in debian.Dockerfile

core/src/util/deprecations.ts, docs/guides/deprecations.md
=> docs: minor corrections in deprecations guide

core/test/data/test-projects/disabled-action-without-provider/garden.yml
Ensures that the actions in question are disabled in different ways.
This properly covers the behaviour changes made in 52bb3537caad8a09a730358fb131f370e890a942.
A follow-up test correction for #7069.
=> test: correct test data to have a clear test data

support/alpine.Dockerfile, support/debian.Dockerfile
=> chore(support): bump azure-cli to 2.71.0 in support Docker images

docs/reference/action-types/Deploy/helm.md, docs/reference/module-types/helm.md
Follow-up docs fix for #7086.
Fixes #
=> docs(helm): re-generate helm docs

examples/demo-project/garden.yml
Remove the commented test config code that was unintentionally pushed in #7065.
Fixes #
=> chore(examples): cleanup provider config

.github/dependabot.yml
Dependabot updates for Garden Bonsai.
Fixes #
=> chore(dependabot): configure updates for 0.13 branch

CHANGELOG.md, README.md, RELEASE_PROCESS.md, cli/package.json, core/package.json, docs/getting-started/quickstart.md, docs/guides/using-garden-in-circleci.md, docs/k8s-plugins/actions/deploy/kubernetes.md, docs/k8s-plugins/remote-k8s/ingress-and-dns.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/conftest-kubernetes.md, docs/reference/providers/conftest.md, docs/reference/providers/hadolint.md, docs/reference/providers/jib.md, docs/terraform-plugin/about.md, docs/terraform-plugin/configure-provider.md, docs/use-cases/jumpstart-idp.md, docs/use-cases/local-development-remote-clusters.md, docs/use-cases/on-demand-preview-envs.md, e2e/package.json, package-lock.json, package.json, plugins/conftest-container/package.json, plugins/conftest-kubernetes/package.json, plugins/conftest/package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.13.58

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/garden-for/kubernetes/deploy-k8s-resource.md, docs/garden-for/terraform/README.md, docs/garden-for/terraform/configure-provider.md, docs/guides/using-garden-in-circleci.md, docs/overview/use-cases/jumpstart-idp.md, docs/overview/use-cases/local-development-remote-clusters.md, docs/overview/use-cases/on-demand-preview-envs.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/jib.md, docs/tutorials/remote-k8s/ingress-and-dns.md, e2e/package.json, package-lock.json, package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.14.2

support/homebrew-formula.rb.j2
=> chore: fix class name in homebrew formula template for 0.13

core/src/plugins/kubernetes/kubectl.ts
=> tool(kubectl): update version to 1.32.3

core/src/plugins/kubernetes/helm/helm-cli.ts, docs/reference/action-types/Deploy/helm.md, docs/reference/module-types/helm.md
Back-port #7084 to 0.13.
Fixes #
=> tool(helm): update version to 3.17.2

.gitbook.yaml
=> docs(gitbook): update redirect rules

.circleci/config.yml
Back-port #7085 to 0.13.
Fixes #
=> ci(integ): update kind from 1.29.8 to 1.32.3

core/src/plugins/kubernetes/kubernetes-type/deploy.ts
=> refactor: rename function for clarity and add jsdocs

core/src/mutagen.ts, core/src/plugins/kubernetes/constants.ts, images/k8s-sync/Dockerfile, images/k8s-sync/garden.yml, images/k8s-util/garden.yml
=> tool(mutagen): update mutagen to 0.18.1 and base alpine image to 3.21.3

images/k8s-sync/README.md, images/k8s-util/README.md
=> chore(images): update maintenance guides for `k8s-sync` and `k8s-util` Docker images

core/src/cloud/backend.ts
=> fix(login): send the right `organizationId` on login

core/src/plugins/container/container.ts, core/test/integ/src/plugins/kubernetes/container/deployment.ts
=> fix(module-k8s): fix `deploymentImageId` in module conversion

core/src/docs/generate.ts, docs/reference/module-types/README.md
=> docs: update the notice on the modules deprecation

core/src/garden.ts, core/src/graph/solver.ts, core/test/integ/src/plugins/kubernetes/container/build/build.ts, core/test/integ/src/plugins/kubernetes/helm/deployment.ts, core/test/unit/src/graph/solver.ts, core/test/unit/src/tasks/resolve-action.ts
Back-port #6577 to 0.13.
Fixes #
=> fix(solver): throw if a dependency failed and `throwOnError` is true

core/src/graph/actions.ts, core/test/data/test-projects/disabled-action-without-provider/garden.yml, core/test/unit/src/garden.ts
Back-port #7062 and #7069 to 0.13.
Fixes #6957 in 0.13.
=> fix: do not throw on unknown action types for disabled actions

.circleci/config.yml
Fixes #
The same fix for 0.13 was done in #7186.
=> ci: fix `path-filtering/filter` job to use compatible Python version

docs/tutorials/your-first-project/1-initialize-a-project.md, docs/tutorials/your-first-project/3-add-actions.md
=> docs: update "Your first project" tutorial to use correct manifest templates configuration

core/src/cloud/auth.ts, core/src/cloud/backend.ts, core/src/config/zod.ts
The right value is `jwtVal`, not `jwtval`. Without this fix the `tokenValidity` is resolved as `NaN` on the first login.
This PR also improves the validation for both old and new backend auth tokens and unifies the error handling.
Fixes #
=> fix(login): fix JWT token validity period retrieval and improve validation

docs/reference/action-types/Deploy/terraform.md, docs/reference/module-types/terraform.md, docs/reference/providers/terraform.md, plugins/terraform/src/helpers.ts
Back-port docs fix #7219 to 0.13.
Fixes #
=> fix(docs): correct config formatting in terraform examples

core/src/mutagen.ts
=> fix: log full error in debug loglevel when mutagen sync flush fails

core/src/cloud/grow/trpc-schema.ts, core/src/cloud/grow/trpc.ts
=> chore: update trpc schema in backend client

package-lock.json, package.json
This PR fixes CI failures in `check-docs` step (see example [here](https://app.circleci.com/pipelines/github/garden-io/garden/30680/workflows/5a298f5e-73b3-448c-9e52-89db490c9cee/jobs/648011)) in 0.13 branch.
Fixes #
=> chore(deps): update markdown-link-check to 3.13.7

package-lock.json
Done by `npm audit fix`
Fixes #
=> chore: sync package lockfile

core/package.json, core/src/monitors/base.ts, core/src/monitors/handler.ts, core/src/monitors/logs.ts, core/src/monitors/port-forward.ts, core/src/monitors/sync.ts, core/src/plugin/handlers/Deploy/get-logs.ts, core/src/plugins/exec/deploy.ts, core/src/plugins/exec/logs.ts, core/src/plugins/kubernetes/logs.ts, core/src/plugins/kubernetes/run.ts, core/test/integ/src/plugins/kubernetes/container/logs.ts, core/test/unit/src/commands/logs.ts, core/test/unit/src/plugins/exec/logs.ts, core/test/unit/src/router/deploy.ts, package-lock.json
=> refactor(logs): get rid of `ts-stream` library

docs/features/code-synchronization.md
=> docs(sync): fix version number in sync troubleshooting notes

core/src/commands/deploy.ts, core/src/plugin/handlers/base/configure.ts, core/src/plugins/kubernetes/container/deployment.ts, core/src/plugins/kubernetes/helm/config.ts, docs/reference/action-types/Deploy/helm.md, docs/reference/action-types/Deploy/kubernetes.md, docs/reference/commands.md
=> docs: remove local mode leftovers

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/garden-for/kubernetes/deploy-k8s-resource.md, docs/garden-for/terraform/README.md, docs/garden-for/terraform/configure-provider.md, docs/guides/using-garden-in-circleci.md, docs/overview/use-cases/jumpstart-idp.md, docs/overview/use-cases/local-development-remote-clusters.md, docs/overview/use-cases/on-demand-preview-envs.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/jib.md, docs/tutorials/remote-k8s/ingress-and-dns.md, e2e/package.json, package-lock.json, package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.14.4

core/package.json, core/src/types/test.ts, core/src/util/string.ts, package-lock.json
* Update `json-stable-stringify` to 1.3.0
* Fix types
* Fix test config stringification in the module configs
Supersedes #7302
=> chore(deps): update `json-stable-stringify`

core/src/plugins/kubernetes/kubectl.ts
=> tool(kubectl): update version to 1.33.2

renovate.json
=> chore(renovate): use chore instead of fix in PR titles

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/garden-for/kubernetes/deploy-k8s-resource.md, docs/garden-for/terraform/README.md, docs/garden-for/terraform/configure-provider.md, docs/guides/using-garden-in-circleci.md, docs/overview/use-cases/jumpstart-idp.md, docs/overview/use-cases/local-development-remote-clusters.md, docs/overview/use-cases/on-demand-preview-envs.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/jib.md, docs/tutorials/remote-k8s/ingress-and-dns.md, e2e/package.json, package-lock.json, package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.14.5

core/src/cloud/grow/trpc.ts
Before:
Unexpected token '<', "<html><h"... is not valid JSON
After:
HTTP status 503
Ported this fix over from https://github.com/garden-io/grow-platform/pull/519
=> fix: improve error message on 5xx errors

renovate.json
=> chore(renovate): ensure higher confidence level in deps update PRs

package-lock.json
=> chore(deps): auto-update `package-lock.json` with `npm audit fix`

renovate.json
A follow-up fix for #7561.
Fixes #
=> chore(renovate): fix config syntax for PR merge confidence

core/src/cloud/grow/api.ts, core/src/cloud/grow/trpc-schema.ts, core/src/cloud/grow/trpc.ts, core/src/cloud/util.ts, core/src/config/project.ts, core/src/constants.ts, core/src/docs/generate.ts, core/src/garden.ts, core/src/util/testing.ts, core/test/helpers.ts, core/test/unit/src/analytics/analytics.ts, core/test/unit/src/cloud/grow/api.ts, core/test/unit/src/commands/cloud/secrets/secrets-update.ts, core/test/unit/src/commands/login.ts, core/test/unit/src/config/project.ts, core/test/unit/src/garden.ts, docs/reference/project-config.md, examples/demo-project/garden.yml
This enables Garden to fetch variables from the new cloud backend, currently under a feature flag. 
Note that the functionality is not GA yet in Garden Cloud, we're rolling this out both sides under feature flags.
Fixes #
=> Experimental support for Cloud v2 variables

CHANGELOG.md, README.md, cli/package.json, core/package.json, docs/garden-for/kubernetes/deploy-k8s-resource.md, docs/garden-for/terraform/README.md, docs/garden-for/terraform/configure-provider.md, docs/guides/using-garden-in-circleci.md, docs/overview/use-cases/jumpstart-idp.md, docs/overview/use-cases/local-development-remote-clusters.md, docs/overview/use-cases/on-demand-preview-envs.md, docs/reference/action-types/Build/jib-container.md, docs/reference/module-types/jib-container.md, docs/reference/providers/jib.md, docs/tutorials/remote-k8s/ingress-and-dns.md, e2e/package.json, package-lock.json, package.json, plugins/jib/package.json, plugins/pulumi/package.json, plugins/terraform/package.json, sdk/package.json
=> chore(release): bump version to 0.14.9

core/src/commands/create/create-remote-variables.ts, core/src/commands/create/create.ts, core/src/commands/get/get-remote-variables.ts, core/src/config/project.ts, docs/reference/commands.md, docs/reference/project-config.md
=> chore(core): misc fixes to remote vars
